function agent = agentNoGloveIntentTd3(observationInfo, actionInfo)
%agentNoGloveIntentTd3 creates a fresh feedforward no-glove TD3 agent.

configs = configurables();
allowedVariants = ["intentMarkov60", ...
    "intentDeclaredRestHoldMarkov62"];
layout = buildObservationLayout(configs.observationVariant, ...
    configs.numEMGFeatures, configs.emgHistoryLength, 4);
if configs.referenceSource ~= "emgIntent" || ...
        ~any(configs.observationVariant == allowedVariants) || ...
        configs.stateLength ~= layout.totalLength || ...
        ~isequal(observationInfo.Dimension, [layout.totalLength, 1])
    error("agentNoGloveIntentTd3:InvalidObservationContract", ...
        ["The no-glove TD3 agent requires intentMarkov60 (60 inputs) " ...
        "or intentDeclaredRestHoldMarkov62 (62 inputs)."]);
end
if configs.td3.useRecurrent
    error("agentNoGloveIntentTd3:RecurrentNotAuthorized", ...
        "ETAPA 6 requires the initial feedforward TD3 architecture.");
end
if ~configs.newTraining || strlength(string(configs.agentFile)) > 0
    error("agentNoGloveIntentTd3:HistoricalCheckpointForbidden", ...
        "The ETAPA 6 agent must be initialized from scratch.");
end
if isfield(configs.td3Residual, "enabled") && configs.td3Residual.enabled
    error("agentNoGloveIntentTd3:ResidualBaseForbidden", ...
        "ETAPA 6 cannot use a residual or frozen historical base.");
end

agent = agentTd3(observationInfo, actionInfo);
end
