function provenance = advanceIntentReference(this, emg, currentEncoderNorm)
%advanceIntentReference builds the next causal reference from the new EMG.
%
% This method is called only after reward_t has been evaluated against the
% q_ref/v_ref stored in state_t. Therefore EMG read during transition t is
% visible in state_(t+1), never retroactively in reward_t.

provenance = [];
if this.referenceSource ~= "emgIntent" || ~this.intentDecoderEnabled
    return;
end

gateStateBefore = this.intentGateState;
referencePositionBefore = this.intentTarget(:)';
referenceVelocityBefore = this.intentVelocity(:)';
declaredRestBefore = this.intentDeclaredRest;
holdLatchBefore = this.intentHoldLatch;
holdPositionMseBefore = this.intentHoldPositionMse;
[desiredVelocity, ~, nextGateState, decoderDetails] = ...
    mapEmgToIntentVelocity(emg, this.intentCalibration, ...
    this.intentExpectedContext, this.intentGateState);
if size(desiredVelocity, 1) ~= 1 || ...
        decoderDetails.discardedSampleCount ~= 0
    error("Env:IntentWindowAlignment", ...
        ["Each environment transition must provide exactly one complete " ...
        "causal raw-EMG window."]);
end

[referencePosition, referenceVelocity, ~, referenceDiagnostics] = ...
    updateIntentReference( ...
    this.intentTarget(:)', desiredVelocity, this.intentCalibration, ...
    decoderDetails.isRest, this.intentVelocity(:)');

this.intentTarget = referencePosition(end, :)';
this.intentVelocity = referenceVelocity(end, :)';
this.intentGateState = nextGateState;
this.referenceTarget = this.intentTarget;
holdDetails = [];
if this.observationVariant == "intentDeclaredRestHoldMarkov62"
    this.intentDeclaredRest = logical(decoderDetails.isRest(end));
    [this.intentHoldLatch, holdDetails] = ...
        updateIntentDeclaredRestHoldState(this.intentHoldLatch, ...
        this.intentDeclaredRest, currentEncoderNorm, this.intentTarget, ...
        this.intentDeclaredRestHoldPositionMseTolerance);
    this.intentHoldPositionMse = holdDetails.positionMse;
end
zeroReferenceReason = classifyIntentZeroReferenceReason( ...
    referenceVelocity(end, :), desiredVelocity(end, :), ...
    decoderDetails, referenceDiagnostics, 1e-12);
provenance = struct( ...
    "schemaVersion", 1, "transitionStep", double(this.c), ...
    "gateStateBefore", gateStateBefore, ...
    "gateStateAfter", nextGateState, ...
    "activity", double(decoderDetails.activity(end)), ...
    "gateActive", logical(decoderDetails.gateActive(end)), ...
    "isRest", logical(decoderDetails.isRest(end)), ...
    "lowActivityCountdown", ...
        logical(decoderDetails.lowActivityCountdown(end)), ...
    "onCount", double(decoderDetails.onCount(end)), ...
    "offCount", double(decoderDetails.offCount(end)), ...
    "decodedIntent", double(decoderDetails.decodedIntent(end, :)), ...
    "desiredVelocity", double(desiredVelocity(end, :)), ...
    "referencePositionBefore", referencePositionBefore, ...
    "referenceVelocityBefore", referenceVelocityBefore, ...
    "referencePositionAfter", double(referencePosition(end, :)), ...
    "referenceVelocityAfter", double(referenceVelocity(end, :)), ...
    "positionLimited", ...
        logical(referenceDiagnostics.positionLimited(end, :)), ...
    "brakingLimited", ...
        logical(referenceDiagnostics.brakingLimited(end, :)), ...
    "accelerationLimited", ...
        logical(referenceDiagnostics.accelerationLimited(end, :)), ...
    "zeroReferenceReason", zeroReferenceReason);
if this.observationVariant == "intentDeclaredRestHoldMarkov62"
    provenance.schemaVersion = 2;
    provenance.declaredRestHoldContractVersion = 1;
    provenance.declaredRestBefore = declaredRestBefore;
    provenance.holdLatchBefore = holdLatchBefore;
    provenance.holdPositionMseBefore = holdPositionMseBefore;
    provenance.declaredRestAfter = this.intentDeclaredRest;
    provenance.holdLatchAfter = this.intentHoldLatch;
    provenance.holdPositionMseAfter = holdDetails.positionMse;
    provenance.nearTargetAfter = holdDetails.nearTarget;
    provenance.holdPositionMseTolerance = ...
        this.intentDeclaredRestHoldPositionMseTolerance;
end
end
