function dataset = buildSyntheticEmgIntentDataset(config)
%buildSyntheticEmgIntentDataset creates a deterministic offline-only fixture.
%
% This fixture is intentionally labelled synthetic. It validates arithmetic,
% bounds and causal state transitions; it is not evidence of human EMG
% separability, clinical performance or mechanically validated motor limits.

arguments
    config (1, 1) struct
end

requiredFields = {'seed', 'fixtureVersion', 'dataProvenance', ...
    'initialEncoder', 'calibrationOptions'};
if ~all(isfield(config, requiredFields)) || ...
        string(config.dataProvenance) ~= "synthetic"
    error("buildSyntheticEmgIntentDataset:InvalidConfig", ...
        "A scalar synthetic ETAPA 2 configuration is required.");
end
options = config.calibrationOptions;
channelCount = numel(options.channelOrder);
if channelCount ~= 8
    error("buildSyntheticEmgIntentDataset:InvalidChannelCount", ...
        "The deterministic fixture is defined for eight Myo channels.");
end

stream = RandStream("mt19937ar", "Seed", config.seed);
windowLength = options.windowLengthSamples;
restAmplitude = [0.012, 0.010, 0.011, 0.009, 0.010, 0.012, 0.011, 0];
patterns = struct( ...
    "close", [0.90, 0.76, 0.62, 0.10, 0.12, 0.16, 0.20, 0], ...
    "open", [0.12, 0.15, 0.18, 0.92, 0.75, 0.62, 0.20, 0], ...
    "thumbOppose", [0.12, 0.55, 0.15, 0.18, 0.22, 0.66, 0.95, 0], ...
    "thumbRelease", [0.56, 0.12, 0.18, 0.63, 0.18, 0.15, 0.90, 0]);

restRawEmg = makeRawWindows(stream, 16, windowLength, ...
    restAmplitude, 0.0015, false);
captureMetadata = struct( ...
    "userId", options.userId, ...
    "sessionId", options.sessionId, ...
    "capturedAt", options.calibratedAt, ...
    "channelOrder", options.channelOrder, ...
    "sampleRateHz", options.sampleRateHz, ...
    "rawEmgUnits", options.rawEmgUnits, ...
    "dataProvenance", options.dataProvenance);
restCapture = captureMetadata;
restCapture.rawEmg = restRawEmg;
directions = [1, 0; 1, 0; -1, 0; -1, 0; 0, 1; 0, 1; 0, -1; 0, -1];
labels = [ ...
    "close_moderate", "close_maximum", ...
    "open_moderate", "open_maximum", ...
    "thumb_oppose_moderate", "thumb_oppose_maximum", ...
    "thumb_release_moderate", "thumb_release_maximum"];
patternNames = [ ...
    "close", "close", "open", "open", ...
    "thumbOppose", "thumbOppose", "thumbRelease", "thumbRelease"];
amplitudeScales = [0.55, 1.00, 0.55, 1.00, 0.55, 1.00, 0.55, 1.00];
instructionTrials = repmat(struct( ...
    "rawEmg", zeros(0, channelCount), ...
    "intentDirection", zeros(1, 2), ...
    "label", "", ...
    "userId", options.userId, ...
    "sessionId", options.sessionId, ...
    "capturedAt", options.calibratedAt, ...
    "channelOrder", options.channelOrder, ...
    "sampleRateHz", options.sampleRateHz, ...
    "rawEmgUnits", options.rawEmgUnits, ...
    "dataProvenance", options.dataProvenance), numel(labels), 1);
for trialIdx = 1:numel(labels)
    amplitude = restAmplitude + amplitudeScales(trialIdx) .* ...
        patterns.(patternNames(trialIdx));
    instructionTrials(trialIdx).rawEmg = makeRawWindows( ...
        stream, 10, windowLength, amplitude, 0.004, false);
    instructionTrials(trialIdx).intentDirection = directions(trialIdx, :);
    instructionTrials(trialIdx).label = labels(trialIdx);
end

scenarioNames = [ ...
    "rest_initial", "transient_noise", "rest_after_noise", ...
    "close_moderate", "close_maximum", "rest_after_close", ...
    "open_maximum", "rest_after_open", ...
    "thumb_oppose_maximum", "rest_after_oppose", ...
    "thumb_release_maximum", "rest_final"];
scenarioCounts = [6, 1, 4, 5, 5, 6, 5, 6, 5, 6, 5, 8];
scenarioDirections = [ ...
     0,  0; 0, 0; 0, 0; ...
     1,  0; 1, 0; 0, 0; ...
    -1,  0; 0, 0; ...
     0,  1; 0, 0; ...
     0, -1; 0, 0];
scenarioScales = [0, 1.00, 0, 0.55, 1.00, 0, ...
    1.00, 0, 1.00, 0, 1.00, 0];
scenarioPatterns = [ ...
    "rest", "noise", "rest", "close", "close", "rest", ...
    "open", "rest", "thumbOppose", "rest", ...
    "thumbRelease", "rest"];

evaluationRawEmg = zeros(0, channelCount);
windowScenario = strings(0, 1);
expectedDirection = zeros(0, 2);
intendedRest = false(0, 1);
for scenarioIdx = 1:numel(scenarioNames)
    count = scenarioCounts(scenarioIdx);
    patternName = scenarioPatterns(scenarioIdx);
    if patternName == "rest"
        raw = makeRawWindows(stream, count, windowLength, ...
            restAmplitude, 0.0015, false);
    elseif patternName == "noise"
        % One supra-threshold broad-band burst. nOn=2 must reject it.
        raw = makeRawWindows(stream, count, windowLength, ...
            restAmplitude + 0.72 * patterns.close, 0.10, true);
    else
        amplitude = restAmplitude + scenarioScales(scenarioIdx) .* ...
            patterns.(patternName);
        raw = makeRawWindows(stream, count, windowLength, ...
            amplitude, 0.004, false);
    end
    evaluationRawEmg = [evaluationRawEmg; raw]; %#ok<AGROW>
    windowScenario = [windowScenario; ...
        repmat(scenarioNames(scenarioIdx), count, 1)]; %#ok<AGROW>
    expectedDirection = [expectedDirection; ...
        repmat(scenarioDirections(scenarioIdx, :), count, 1)]; %#ok<AGROW>
    intendedRest = [intendedRest; ...
        repmat(all(scenarioDirections(scenarioIdx, :) == 0), count, 1)]; %#ok<AGROW>
end

dataset = struct( ...
    "schemaVersion", 1, ...
    "fixtureVersion", config.fixtureVersion, ...
    "dataProvenance", "synthetic", ...
    "seed", config.seed, ...
    "sampleRateHz", options.sampleRateHz, ...
    "windowLengthSamples", windowLength, ...
    "hopLengthSamples", options.hopLengthSamples, ...
    "channelOrder", options.channelOrder, ...
    "rawEmgUnits", options.rawEmgUnits, ...
    "restCapture", restCapture, ...
    "instructionTrials", instructionTrials, ...
    "evaluationRawEmg", evaluationRawEmg, ...
    "evaluationWindowScenario", windowScenario, ...
    "evaluationExpectedDirection", expectedDirection, ...
    "evaluationIntendedRest", intendedRest, ...
    "initialEncoder", config.initialEncoder, ...
    "flatChannelIndex", 8, ...
    "patterns", patterns);
end

function raw = makeRawWindows( ...
        stream, windowCount, windowLength, amplitude, noiseScale, broadBand)
channelCount = numel(amplitude);
raw = zeros(windowCount * windowLength, channelCount);
sampleWithinWindow = (0:(windowLength - 1))';
for windowIdx = 1:windowCount
    rows = (windowIdx - 1) * windowLength + (1:windowLength);
    for channelIdx = 1:channelCount
        if amplitude(channelIdx) == 0
            raw(rows, channelIdx) = 0;
            continue;
        end
        phase = 0.29 * channelIdx + 0.07 * windowIdx;
        cycles = 2 + mod(channelIdx, 4);
        carrier = sin(2 * pi * cycles * sampleWithinWindow / ...
            windowLength + phase);
        if broadBand
            carrier = 0.65 * carrier + ...
                0.35 * randn(stream, windowLength, 1);
        end
        noise = noiseScale * amplitude(channelIdx) .* ...
            randn(stream, windowLength, 1);
        raw(rows, channelIdx) = amplitude(channelIdx) .* carrier + noise;
    end
end
end
