function calibration = calibrateEmgIntent(restCapture, instructionTrials, options)
%calibrateEmgIntent calibrates same-session EMG activation and an r=2 decoder.
%
% restCapture and each element of instructionTrials carry rawEmg plus
% user/session/channel/rate/unit metadata. Mismatches fail closed.
%
% instructionTrials is a struct array with fields:
%   rawEmg         samples-by-channels raw EMG (never WMoos features)
%   intentDirection signed 1-by-2 categorical instruction
%   label          auditable instruction label
%   userId, sessionId, capturedAt, channelOrder, sampleRateHz,
%   rawEmgUnits and dataProvenance compatibility metadata

% Decoder target magnitude is derived from normalized EMG activity; no glove
% or motor correspondence is used to estimate W.

arguments
    restCapture (1, 1) struct
    instructionTrials struct
    options struct
end

options = normalizeOptions(options);
restRawEmg = validateCapture(restCapture, options, "restCapture");
if isempty(instructionTrials) || ~isvector(instructionTrials)
    error("calibrateEmgIntent:InvalidTrials", ...
        "instructionTrials must be a nonempty struct vector.");
end
requiredTrialFields = { ...
    'rawEmg', 'intentDirection', 'label', 'userId', 'sessionId', ...
    'capturedAt', 'channelOrder', 'sampleRateHz', 'rawEmgUnits', ...
    'dataProvenance'};
if ~all(isfield(instructionTrials, requiredTrialFields))
    error("calibrateEmgIntent:InvalidTrials", ...
        "Every trial requires rawEmg, intentDirection and label.");
end

[restEnvelope, ~] = computeEmgEnvelope( ...
    restRawEmg, options.windowLengthSamples, options.hopLengthSamples);
if size(restEnvelope, 1) < options.minRestWindows
    error("calibrateEmgIntent:InsufficientRestWindows", ...
        "Rest calibration requires at least %d complete windows.", ...
        options.minRestWindows);
end
baselineMedian = median(restEnvelope, 1);
restEnvelopeMad = median(abs(restEnvelope - baselineMedian), 1);

trialEnvelopes = cell(numel(instructionTrials), 1);
trialDirections = zeros(numel(instructionTrials), 2);
trialLabels = strings(numel(instructionTrials), 1);
trialCapturedAt = strings(numel(instructionTrials), 1);
trialWindowCounts = zeros(numel(instructionTrials), 1);
trialSignalLevels = zeros(numel(instructionTrials), size(restRawEmg, 2));
for trialIdx = 1:numel(instructionTrials)
    trial = instructionTrials(trialIdx);
    trialRawEmg = validateCapture(trial, options, ...
        "instructionTrials(" + trialIdx + ")");
    direction = double(trial.intentDirection(:)');
    allowedDirections = [1, 0; -1, 0; 0, 1; 0, -1];
    if numel(direction) ~= 2 || any(~isfinite(direction)) || ...
            ~ismember(direction, allowedDirections, "rows")
        error("calibrateEmgIntent:InvalidIntentDirection", ...
            "Each categorical direction must be exactly +/- one r=2 axis.");
    end
    label = string(trial.label);
    if ~isscalar(label) || ismissing(label) || strlength(label) == 0
        error("calibrateEmgIntent:InvalidTrialLabel", ...
            "Each calibration trial requires a nonempty scalar label.");
    end

    trialEnvelopes{trialIdx} = computeEmgEnvelope( ...
        trialRawEmg, options.windowLengthSamples, options.hopLengthSamples);
    trialWindowCounts(trialIdx) = size(trialEnvelopes{trialIdx}, 1);
    if trialWindowCounts(trialIdx) < options.minWindowsPerInstruction
        error("calibrateEmgIntent:InsufficientInstructionWindows", ...
            "Instruction %s requires at least %d complete windows.", ...
            label, options.minWindowsPerInstruction);
    end
    trialDirections(trialIdx, :) = direction;
    trialLabels(trialIdx) = label;
    trialCapturedAt(trialIdx) = string(trial.capturedAt);
    trialSignalLevels(trialIdx, :) = robustPercentile( ...
        trialEnvelopes{trialIdx}, options.signalPercentile);
end

if numel(unique(trialLabels)) ~= numel(trialLabels)
    error("calibrateEmgIntent:DuplicateTrialLabel", ...
        "Calibration trial labels must be unique and auditable.");
end

if rank(trialDirections) < 2 || ...
        any(min(trialDirections, [], 1) >= 0) || ...
        any(max(trialDirections, [], 1) <= 0)
    error("calibrateEmgIntent:InsufficientIntentDirections", ...
        "Calibration requires positive and negative instructions for both r=2 synergies.");
end

% Max-of-within-instruction percentiles avoids diluting a channel that is
% informative for only one of the two calibrated synergies.
signalLevel = max(trialSignalLevels, [], 1);
signalRange = signalLevel - baselineMedian;
requiredSignalRange = max( ...
    options.minCalibrationRange * ones(size(signalRange)), ...
    options.flatChannelMadMultiplier * 1.4826 * restEnvelopeMad);
activeChannelMask = signalRange >= requiredSignalRange & signalRange > 0;
if sum(activeChannelMask) < 2
    error("calibrateEmgIntent:InsufficientActiveChannels", ...
        "At least two channels must exceed the robust calibration range.");
end

restActivation = normalizeEnvelope(restEnvelope, baselineMedian, ...
    signalLevel, options.epsilon, activeChannelMask);
activationRows = restActivation;
targetRows = zeros(size(restActivation, 1), 2);
classIndex = ones(size(restActivation, 1), 1);
sampleWeights = repmat(1 / size(restActivation, 1), ...
    size(restActivation, 1), 1);

for trialIdx = 1:numel(instructionTrials)
    activation = normalizeEnvelope(trialEnvelopes{trialIdx}, ...
        baselineMedian, signalLevel, options.epsilon, activeChannelMask);
    activity = mean(activation(:, activeChannelMask), 2);
    target = activity .* trialDirections(trialIdx, :);
    activationRows = [activationRows; activation]; %#ok<AGROW>
    targetRows = [targetRows; target]; %#ok<AGROW>
    classIndex = [classIndex; ...
        repmat(trialIdx + 1, size(activation, 1), 1)]; %#ok<AGROW>
    sampleWeights = [sampleWeights; ...
        repmat(1 / size(activation, 1), size(activation, 1), 1)]; %#ok<AGROW>
end
sampleWeights = sampleWeights / sum(sampleWeights);

centeredActivation = activationRows(:, activeChannelMask) - ...
    mean(activationRows(:, activeChannelMask), 1);
activationDesignRank = rank(centeredActivation);
if activationDesignRank < 2
    error("calibrateEmgIntent:UnidentifiableActivationDesign", ...
        "Normalized EMG activations do not identify two independent synergies.");
end

fitTarget = max(-options.decoderFitLimit, ...
    min(options.decoderFitLimit, targetRows));
fitTarget = atanh(fitTarget);
design = [activationRows, ones(size(activationRows, 1), 1)];
weightedDesign = sqrt(sampleWeights) .* design;
weightedTarget = sqrt(sampleWeights) .* fitTarget;
regularizer = diag([ones(1, size(activationRows, 2)), 0]);
coefficients = (weightedDesign' * weightedDesign + ...
    options.ridgeLambda * regularizer) \ ...
    (weightedDesign' * weightedTarget);
decoderW = coefficients(1:end-1, :)';
decoderBias = coefficients(end, :)';
decoderW(:, ~activeChannelMask) = 0;
decoderWeightRank = rank(decoderW(:, activeChannelMask));
if decoderWeightRank < 2
    error("calibrateEmgIntent:UnidentifiableDecoder", ...
        "The fitted decoder weights do not have rank 2 on active channels.");
end

predictedIntent = tanh(activationRows * decoderW' + decoderBias');
trainingRmse = sqrt(mean((predictedIntent - targetRows).^2, "all"));
if any(~isfinite(decoderW), "all") || any(~isfinite(decoderBias)) || ...
        ~isfinite(trainingRmse)
    error("calibrateEmgIntent:NonfiniteDecoder", ...
        "Decoder fitting produced nonfinite values.");
end
if trainingRmse > options.maxDecoderTrainingRmse
    error("calibrateEmgIntent:PoorDecoderFit", ...
        "Decoder training RMSE %.6f exceeds the configured limit %.6f.", ...
        trainingRmse, options.maxDecoderTrainingRmse);
end
classLabels = ["rest"; trialLabels];
classRmse = zeros(numel(classLabels), 1);
for classIdx = 1:numel(classLabels)
    selected = classIndex == classIdx;
    classRmse(classIdx) = sqrt(mean( ...
        (predictedIntent(selected, :) - targetRows(selected, :)).^2, "all"));
end

calibration = struct( ...
    "schemaVersion", 1, ...
    "userId", options.userId, ...
    "sessionId", options.sessionId, ...
    "calibratedAt", options.calibratedAt, ...
    "sourceCapturedAt", string(restCapture.capturedAt), ...
    "dataProvenance", options.dataProvenance, ...
    "channelOrder", options.channelOrder, ...
    "channelCount", numel(options.channelOrder), ...
    "sampleRateHz", options.sampleRateHz, ...
    "windowLengthSamples", options.windowLengthSamples, ...
    "hopLengthSamples", options.hopLengthSamples, ...
    "baselineMedian", baselineMedian, ...
    "signalLevel", signalLevel, ...
    "signalPercentile", options.signalPercentile, ...
    "restEnvelopeMad", restEnvelopeMad, ...
    "requiredSignalRange", requiredSignalRange, ...
    "epsilon", options.epsilon, ...
    "minCalibrationRange", options.minCalibrationRange, ...
    "flatChannelMadMultiplier", options.flatChannelMadMultiplier, ...
    "activeChannelMask", logical(activeChannelMask), ...
    "flatChannelMask", logical(~activeChannelMask), ...
    "activityAggregation", "meanActiveChannels", ...
    "minimumWindows", struct( ...
        "rest", options.minRestWindows, ...
        "perInstruction", options.minWindowsPerInstruction), ...
    "restWindowCount", size(restEnvelope, 1), ...
    "decoder", struct( ...
        "rank", 2, ...
        "activationDesignRank", activationDesignRank, ...
        "weightRank", decoderWeightRank, ...
        "W", decoderW, ...
        "bias", decoderBias, ...
        "ridgeLambda", options.ridgeLambda, ...
        "fitLimit", options.decoderFitLimit, ...
        "trainingRmse", trainingRmse, ...
        "maxTrainingRmse", options.maxDecoderTrainingRmse, ...
        "classLabels", classLabels, ...
        "classRmse", classRmse), ...
    "synergy", struct( ...
        "matrix", options.synergyMatrix, ...
        "version", options.synergyMatrixVersion), ...
    "motorOrder", options.motorOrder, ...
    "limits", struct( ...
        "velocityMax", options.velocityMax, ...
        "positionMin", options.positionMin, ...
        "positionMax", options.positionMax, ...
        "accelerationMax", options.accelerationMax, ...
        "deltaT", options.deltaT), ...
    "restGate", struct( ...
        "thetaOn", options.thetaOn, ...
        "thetaOff", options.thetaOff, ...
        "nOn", options.nOn, ...
        "nOff", options.nOff), ...
    "units", struct( ...
        "rawEmg", options.rawEmgUnits, ...
        "envelope", options.envelopeUnits, ...
        "position", options.positionUnits, ...
        "velocity", options.velocityUnits, ...
        "acceleration", options.accelerationUnits), ...
    "sourceDomain", "rawEmgSameSession", ...
    "wmoosStandardizationUsed", false, ...
    "instructionProtocol", struct( ...
        "version", options.instructionProtocolVersion, ...
        "labels", trialLabels, ...
        "directions", trialDirections, ...
        "capturedAt", trialCapturedAt, ...
        "windowCounts", trialWindowCounts), ...
    "trainingWindowCount", size(activationRows, 1));
calibration.contentSha256 = computeIntentCalibrationChecksum(calibration);

validation = validateIntentCalibration(calibration);
if ~validation.isValid
    error("calibrateEmgIntent:InvalidCalibration", ...
        "Generated calibration failed validation: %s", ...
        strjoin(validation.issues, "; "));
end
end

function options = normalizeOptions(options)
if ~isscalar(options)
    error("calibrateEmgIntent:InvalidOptions", ...
        "options must be a scalar struct.");
end

requiredFields = [ ...
    "userId", "sessionId", "calibratedAt", "dataProvenance", ...
    "instructionProtocolVersion", "channelOrder", ...
    "synergyMatrix", "synergyMatrixVersion", ...
    "motorOrder", ...
    "velocityMax", "positionMin", "positionMax", ...
    "accelerationMax", "deltaT"];
missingFields = requiredFields(~isfield(options, requiredFields));
if ~isempty(missingFields)
    error("calibrateEmgIntent:IncompleteOptions", ...
        "Missing option(s): %s", strjoin(missingFields, ", "));
end

defaults = struct( ...
    "sampleRateHz", 200, ...
    "windowLengthSamples", 40, ...
    "hopLengthSamples", 40, ...
    "signalPercentile", 95, ...
    "epsilon", 1e-8, ...
    "minCalibrationRange", 1e-4, ...
    "flatChannelMadMultiplier", 6, ...
    "ridgeLambda", 1e-3, ...
    "decoderFitLimit", 0.95, ...
    "maxDecoderTrainingRmse", 0.20, ...
    "minRestWindows", 8, ...
    "minWindowsPerInstruction", 5, ...
    "thetaOn", 0.18, ...
    "thetaOff", 0.08, ...
    "nOn", 2, ...
    "nOff", 3, ...
    "rawEmgUnits", "normalizedMyoAdc", ...
    "envelopeUnits", "meanAbsoluteNormalizedMyoAdc", ...
    "positionUnits", "encoderNormalized", ...
    "velocityUnits", "encoderNormalizedPerSecond", ...
    "accelerationUnits", "encoderNormalizedPerSecondSquared");
defaultFields = fieldnames(defaults);
for i = 1:numel(defaultFields)
    fieldName = defaultFields{i};
    if ~isfield(options, fieldName) || isempty(options.(fieldName))
        options.(fieldName) = defaults.(fieldName);
    end
end

allowedFields = [requiredFields, string(defaultFields)'];
unknownFields = setdiff(string(fieldnames(options)), allowedFields);
if ~isempty(unknownFields)
    error("calibrateEmgIntent:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknownFields, ", "));
end

options.userId = string(options.userId);
options.sessionId = string(options.sessionId);
options.calibratedAt = string(options.calibratedAt);
options.dataProvenance = string(options.dataProvenance);
options.instructionProtocolVersion = string(options.instructionProtocolVersion);
options.channelOrder = string(options.channelOrder(:)');
options.synergyMatrixVersion = string(options.synergyMatrixVersion);
options.motorOrder = string(options.motorOrder(:)');
if ~isscalar(options.userId) || strlength(options.userId) == 0 || ...
        ~isscalar(options.sessionId) || strlength(options.sessionId) == 0 || ...
        ~isscalar(options.calibratedAt) || strlength(options.calibratedAt) == 0 || ...
        ~isscalar(options.dataProvenance) || ...
        strlength(options.dataProvenance) == 0 || ...
        ~isscalar(options.instructionProtocolVersion) || ...
        strlength(options.instructionProtocolVersion) == 0
    error("calibrateEmgIntent:InvalidSessionMetadata", ...
        "User, session, date, provenance and protocol version must be " + ...
        "nonempty scalar strings.");
end
if isempty(options.channelOrder) || any(strlength(options.channelOrder) == 0) || ...
        numel(unique(options.channelOrder)) ~= numel(options.channelOrder)
    error("calibrateEmgIntent:InvalidChannelOrder", ...
        "channelOrder must contain unique nonempty labels.");
end
if numel(options.motorOrder) ~= 4 || any(strlength(options.motorOrder) == 0) || ...
        numel(unique(options.motorOrder)) ~= 4
    error("calibrateEmgIntent:InvalidMotorOrder", ...
        "motorOrder must contain four unique nonempty labels.");
end
if ~isequal(size(options.synergyMatrix), [4, 2]) || ...
        ~isFiniteNumeric(options.synergyMatrix) || ...
        any(abs(options.synergyMatrix) > 1, "all") || ...
        ~isscalar(options.synergyMatrixVersion) || ...
        strlength(options.synergyMatrixVersion) == 0
    error("calibrateEmgIntent:InvalidSynergyMatrix", ...
        "synergyMatrix must be a finite, versioned 4-by-2 matrix within [-1,1].");
end
if rank(double(options.synergyMatrix)) < 2
    error("calibrateEmgIntent:InvalidSynergyMatrix", ...
        "synergyMatrix must have rank 2 for the two declared synergies.");
end

rowFields = ["velocityMax", "positionMin", "positionMax", "accelerationMax"];
for fieldName = rowFields
    value = options.(fieldName);
    if ~isFiniteNumeric(value) || numel(value) ~= 4
        error("calibrateEmgIntent:InvalidLimit", ...
            "%s must be a finite four-vector.", fieldName);
    end
    options.(fieldName) = double(value(:)');
end
if any(options.velocityMax <= 0) || any(options.accelerationMax <= 0) || ...
        any(options.positionMax <= options.positionMin) || ...
        ~isPositiveScalar(options.deltaT)
    error("calibrateEmgIntent:InvalidLimit", ...
        "Position, velocity, acceleration and deltaT limits are invalid.");
end

positiveScalars = [ ...
    "sampleRateHz", "windowLengthSamples", "hopLengthSamples", ...
    "epsilon", "minCalibrationRange", "flatChannelMadMultiplier", ...
    "ridgeLambda", "maxDecoderTrainingRmse", ...
    "minRestWindows", "minWindowsPerInstruction", "nOn", "nOff"];
for fieldName = positiveScalars
    if ~isPositiveScalar(options.(fieldName))
        error("calibrateEmgIntent:InvalidOptionValue", ...
            "%s must be a positive finite scalar.", fieldName);
    end
end
if fix(options.windowLengthSamples) ~= options.windowLengthSamples || ...
        fix(options.hopLengthSamples) ~= options.hopLengthSamples || ...
        fix(options.minRestWindows) ~= options.minRestWindows || ...
        fix(options.minWindowsPerInstruction) ~= options.minWindowsPerInstruction || ...
        fix(options.nOn) ~= options.nOn || fix(options.nOff) ~= options.nOff
    error("calibrateEmgIntent:InvalidOptionValue", ...
        "Window, hop and hysteresis counts must be integers.");
end
if ~isFiniteScalar(options.signalPercentile) || ...
        options.signalPercentile <= 50 || options.signalPercentile > 100 || ...
        ~isFiniteScalar(options.decoderFitLimit) || ...
        options.decoderFitLimit <= 0 || options.decoderFitLimit >= 1 || ...
        options.maxDecoderTrainingRmse > 1 || ...
        ~isFiniteScalar(options.thetaOff) || ~isFiniteScalar(options.thetaOn) || ...
        options.thetaOff < 0 || options.thetaOff >= options.thetaOn || ...
        options.thetaOn > 1
    error("calibrateEmgIntent:InvalidOptionValue", ...
        "Percentile, decoder fit limit or hysteresis thresholds are invalid.");
end
if any((options.nOff - 1) .* options.accelerationMax .* options.deltaT < ...
        options.velocityMax - 128 * eps)
    error("calibrateEmgIntent:InfeasibleRestStop", ...
        "(nOff-1)*accelerationMax*deltaT must be at least velocityMax " + ...
        "because the nOff window enters exact rest hold.");
end
expectedDeltaT = options.hopLengthSamples / options.sampleRateHz;
if abs(options.deltaT - expectedDeltaT) > ...
        64 * eps(max(1, max(abs([options.deltaT, expectedDeltaT]))))
    error("calibrateEmgIntent:IncompatibleTiming", ...
        "deltaT must equal hopLengthSamples/sampleRateHz for causal replay.");
end

unitFields = ["rawEmgUnits", "envelopeUnits", "positionUnits", ...
    "velocityUnits", "accelerationUnits"];
for fieldName = unitFields
    options.(fieldName) = string(options.(fieldName));
    if ~isscalar(options.(fieldName)) || ...
            ismissing(options.(fieldName)) || strlength(options.(fieldName)) == 0
        error("calibrateEmgIntent:InvalidUnits", ...
            "%s must be a nonempty scalar string.", fieldName);
    end
end
end

function rawEmg = validateCapture(capture, options, fieldName)
requiredFields = { ...
    'rawEmg', 'userId', 'sessionId', 'capturedAt', 'channelOrder', ...
    'sampleRateHz', 'rawEmgUnits', 'dataProvenance'};
if ~isstruct(capture) || ~isscalar(capture) || ...
        ~all(isfield(capture, requiredFields))
    error("calibrateEmgIntent:InvalidCaptureMetadata", ...
        "%s lacks required raw-EMG capture metadata.", fieldName);
end

try
    userId = string(capture.userId);
    sessionId = string(capture.sessionId);
    capturedAt = string(capture.capturedAt);
    channelOrder = string(capture.channelOrder(:)');
    rawEmgUnits = string(capture.rawEmgUnits);
    dataProvenance = string(capture.dataProvenance);
catch
    error("calibrateEmgIntent:InvalidCaptureMetadata", ...
        "%s contains invalid metadata types.", fieldName);
end
validStrings = isscalar(userId) && isscalar(sessionId) && ...
    isscalar(capturedAt) && isscalar(rawEmgUnits) && ...
    isscalar(dataProvenance) && ~any(ismissing( ...
    [userId, sessionId, capturedAt, rawEmgUnits, dataProvenance])) && ...
    all(strlength([userId, sessionId, capturedAt, ...
    rawEmgUnits, dataProvenance]) > 0);
if ~validStrings || ~isequal(channelOrder, options.channelOrder) || ...
        userId ~= options.userId || sessionId ~= options.sessionId || ...
        rawEmgUnits ~= options.rawEmgUnits || ...
        dataProvenance ~= options.dataProvenance || ...
        ~isFiniteScalar(capture.sampleRateHz) || ...
        capture.sampleRateHz ~= options.sampleRateHz
    error("calibrateEmgIntent:IncompatibleCapture", ...
        "%s is incompatible with the configured user/session/channel/rate/units.", ...
        fieldName);
end
rawEmg = capture.rawEmg;
validateRawEmg(rawEmg, numel(options.channelOrder), fieldName + ".rawEmg");
end

function validateRawEmg(rawEmg, channelCount, fieldName)
if isempty(rawEmg) || ~isnumeric(rawEmg) || ~isreal(rawEmg) || ...
        ~ismatrix(rawEmg) || size(rawEmg, 2) ~= channelCount || ...
        any(~isfinite(rawEmg), "all")
    error("calibrateEmgIntent:InvalidRawEmg", ...
        "%s must be a finite real samples-by-%d raw EMG matrix.", ...
        fieldName, channelCount);
end
end

function activation = normalizeEnvelope(envelope, baseline, signalLevel, epsilon, activeMask)
activation = (double(envelope) - double(baseline)) ./ ...
    (double(signalLevel) - double(baseline) + epsilon);
activation = max(0, min(1, activation));
activation(:, ~activeMask) = 0;
end

function percentile = robustPercentile(values, percentileValue)
sortedValues = sort(double(values), 1);
rowCount = size(sortedValues, 1);
position = 1 + (rowCount - 1) * percentileValue / 100;
lowerIdx = floor(position);
upperIdx = ceil(position);
fraction = position - lowerIdx;
percentile = (1 - fraction) .* sortedValues(lowerIdx, :) + ...
    fraction .* sortedValues(upperIdx, :);
end

function tf = isFiniteNumeric(value)
tf = isnumeric(value) && isreal(value) && all(isfinite(value), "all");
end

function tf = isFiniteScalar(value)
tf = isFiniteNumeric(value) && isscalar(value);
end

function tf = isPositiveScalar(value)
tf = isFiniteScalar(value) && value > 0;
end
