function corpus = buildNoGloveStage7sRestSupportCorpus( ...
        profile, frozenEmgScale, options)
%buildNoGloveStage7sRestSupportCorpus builds a declared-rest gate stress set.
%
% The synthetic captures are causal raw EMG. They deliberately concentrate
% calibrated activation in one channel while keeping the existing mean
% activity gate below thetaOn. They are not physiological rest evidence.

arguments
    profile (1, 1) struct
    frozenEmgScale double
    options.seed (1, 1) double ...
        {mustBeInteger, mustBeNonnegative} = 7701
    options.episodeCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 80
    options.windowCount (1, 1) double ...
        {mustBeInteger, mustBeGreaterThan(options.windowCount, 1)} = 21
    options.targetActivity (1, 1) double ...
        {mustBePositive} = 0.13
    options.dominantMinimum (1, 1) double ...
        {mustBeInRange(options.dominantMinimum, 0, 1)} = 0.84
    options.dominantMaximum (1, 1) double ...
        {mustBeInRange(options.dominantMaximum, 0, 1)} = 0.90
    options.activityTolerance (1, 1) double ...
        {mustBePositive} = 1e-10
    options.minimumCrossDominantEmgRms (1, 1) double ...
        {mustBePositive} = 0.50
end

requiredProfile = ["referenceSource", "observationVariant", ...
    "intentCalibration", "intentExpectedContext"];
if ~all(isfield(profile, cellstr(requiredProfile))) || ...
        string(profile.referenceSource) ~= "emgIntent" || ...
        string(profile.observationVariant) ~= "intentMarkov60"
    error("buildNoGloveStage7sRestSupportCorpus:InvalidProfile", ...
        "A frozen intentMarkov60 EMG-only profile is required.");
end
if mod(options.episodeCount, 2) ~= 0
    error("buildNoGloveStage7sRestSupportCorpus:OddEpisodeCount", ...
        "Episodes must form an N-by-2 prerecorded EMG cell array.");
end
scale = double(frozenEmgScale(:)');
if ~isequal(size(scale), [1, 40]) || ~isreal(scale) || ...
        any(~isfinite(scale)) || any(scale <= 0)
    error("buildNoGloveStage7sRestSupportCorpus:InvalidScale", ...
        "frozenEmgScale must be a finite positive 1-by-40 row.");
end

calibration = profile.intentCalibration;
expected = profile.intentExpectedContext;
validation = validateIntentCalibration(calibration, expected);
if ~validation.isValid
    error("buildNoGloveStage7sRestSupportCorpus:InvalidCalibration", ...
        "Frozen calibration is incompatible: %s", ...
        strjoin(validation.issues, "; "));
end
activeChannels = find(calibration.activeChannelMask(:)');
flatChannels = find(calibration.flatChannelMask(:)');
activeCount = numel(activeChannels);
if calibration.channelCount ~= 8 || activeCount ~= 7 || ...
        ~isequal(flatChannels, 8) || ...
        options.targetActivity >= calibration.restGate.thetaOn || ...
        options.dominantMinimum >= options.dominantMaximum
    error("buildNoGloveStage7sRestSupportCorpus:ProtocolChanged", ...
        "ETAPA 7S requires seven active channels, flat channel 8 and A<thetaOn.");
end
minimumBackground = (activeCount*options.targetActivity - ...
    options.dominantMaximum)/(activeCount-1);
maximumBackground = (activeCount*options.targetActivity - ...
    options.dominantMinimum)/(activeCount-1);
if minimumBackground < 0 || maximumBackground > 1
    error("buildNoGloveStage7sRestSupportCorpus:InvalidActivationDesign", ...
        "Dominant bounds cannot preserve the target aggregate activity.");
end

defaults = configurables();
normalization = defaults.norm;
windowLength = calibration.windowLengthSamples;
channelCount = calibration.channelCount;
totalWindows = options.episodeCount*options.windowCount;
emgs = cell(options.episodeCount/2, 2);
features = zeros(totalWindows, 40);
captureMatrix = zeros(options.episodeCount, ...
    options.windowCount*windowLength*channelCount);

episode = zeros(totalWindows, 1);
cellRow = zeros(totalWindows, 1);
side = zeros(totalWindows, 1);
window = zeros(totalWindows, 1);
dominantChannel = zeros(totalWindows, 1);
dominantActivation = zeros(totalWindows, 1);
backgroundActivation = zeros(totalWindows, 1);
aggregateActivity = zeros(totalWindows, 1);
gateActive = false(totalWindows, 1);
lowActivityCountdown = false(totalWindows, 1);
featureMinimum = zeros(totalWindows, 1);
featureMaximum = zeros(totalWindows, 1);
cursor = 0;

for episodeIdx = 1:options.episodeCount
    raw = zeros(options.windowCount*windowLength, channelCount);
    targetActivation = zeros(options.windowCount, channelCount);
    episodeDominant = zeros(options.windowCount, 1);
    for windowIdx = 1:options.windowCount
        dominantRank = 1+mod((episodeIdx-1)*3+(windowIdx-1)*5, ...
            activeCount);
        dominant = activeChannels(dominantRank);
        levelCode = mod((episodeIdx-1)*11+(windowIdx-1)*7+ ...
            options.seed, 17)/16;
        dominantValue = options.dominantMinimum + ...
            (options.dominantMaximum-options.dominantMinimum)*levelCode;
        backgroundValue = (activeCount*options.targetActivity - ...
            dominantValue)/(activeCount-1);
        activation = zeros(1, channelCount);
        activation(activeChannels) = backgroundValue;
        activation(dominant) = dominantValue;
        targetActivation(windowIdx, :) = activation;
        episodeDominant(windowIdx) = dominant;

        envelope = calibration.baselineMedian + activation .* ...
            (calibration.signalLevel-calibration.baselineMedian + ...
            calibration.epsilon);
        rows = (windowIdx-1)*windowLength+(1:windowLength);
        raw(rows, :) = makeWindow(envelope, episodeIdx, windowIdx, ...
            options.seed, flatChannels);
    end

    [velocity, ~, ~, details] = mapEmgToIntentVelocity( ...
        raw, calibration, expected);
    if numel(details.activity) ~= options.windowCount || ...
            max(abs(details.activity-options.targetActivity)) > ...
            options.activityTolerance || any(details.gateActive) || ...
            any(details.lowActivityCountdown) || ...
            any(abs(velocity) > options.activityTolerance, "all")
        error("buildNoGloveStage7sRestSupportCorpus:RestContract", ...
            "Episode %d did not remain in calibrated declared rest.", ...
            episodeIdx);
    end
    if any(abs(details.normalizedActivation-targetActivation) > ...
            options.activityTolerance, "all")
        error("buildNoGloveStage7sRestSupportCorpus:EnvelopeMismatch", ...
            "Episode %d did not reproduce its calibrated activation.", ...
            episodeIdx);
    end

    rowIdx = ceil(episodeIdx/2);
    sideIdx = 1+mod(episodeIdx-1, 2);
    emgs{rowIdx, sideIdx} = raw;
    captureMatrix(episodeIdx, :) = raw(:)';
    for windowIdx = 1:options.windowCount
        cursor = cursor+1;
        rows = (windowIdx-1)*windowLength+(1:windowLength);
        feature = getWmoosFeatures(raw(rows, :), ...
            normalization.C, normalization.S);
        features(cursor, :) = double(feature(:)');
        episode(cursor) = episodeIdx;
        cellRow(cursor) = rowIdx;
        side(cursor) = sideIdx;
        window(cursor) = windowIdx;
        dominantChannel(cursor) = episodeDominant(windowIdx);
        dominantActivation(cursor) = ...
            targetActivation(windowIdx, episodeDominant(windowIdx));
        otherActive = setdiff(activeChannels, episodeDominant(windowIdx));
        backgroundActivation(cursor) = ...
            mean(targetActivation(windowIdx, otherActive));
        aggregateActivity(cursor) = details.activity(windowIdx);
        gateActive(cursor) = details.gateActive(windowIdx);
        lowActivityCountdown(cursor) = ...
            details.lowActivityCountdown(windowIdx);
        featureMinimum(cursor) = min(feature);
        featureMaximum(cursor) = max(feature);
    end
end

if size(unique(captureMatrix, "rows"), 1) ~= options.episodeCount
    error("buildNoGloveStage7sRestSupportCorpus:DuplicateCapture", ...
        "Every prospective capture must be distinct.");
end
minimumDistance = minimumCrossDominantDistance( ...
    features, dominantChannel, scale);
if minimumDistance < options.minimumCrossDominantEmgRms
    error("buildNoGloveStage7sRestSupportCorpus:InsufficientEmgSeparation", ...
        "Cross-dominant emgRms %.17g is below %.17g.", ...
        minimumDistance, options.minimumCrossDominantEmgRms);
end

designTable = table(episode, cellRow, side, window, dominantChannel, ...
    dominantActivation, backgroundActivation, aggregateActivity, ...
    gateActive, lowActivityCountdown, featureMinimum, featureMaximum);
metadata = struct( ...
    "schemaVersion", 1, "stage", "7S", ...
    "role", "prospective_declared_rest_gate_stress", ...
    "dataProvenance", "synthetic", ...
    "physiologicalRestEvidence", false, ...
    "seed", options.seed, "episodeCount", options.episodeCount, ...
    "windowCount", options.windowCount, ...
    "targetActivity", options.targetActivity, ...
    "thetaOn", calibration.restGate.thetaOn, ...
    "thetaOff", calibration.restGate.thetaOff, ...
    "channelOrder", calibration.channelOrder, ...
    "sampleRateHz", calibration.sampleRateHz, ...
    "windowLengthSamples", windowLength, ...
    "rawEmgUnits", calibration.units.rawEmg, ...
    "calibrationContentSha256", calibration.contentSha256, ...
    "wmoosStandardized", true, ...
    "minimumCrossDominantEmgRms", minimumDistance, ...
    "hardwareUsed", false);
checks = struct( ...
    "episodeCountExact", numel(emgs) == options.episodeCount, ...
    "captureDimensionsExact", all(cellfun(@(value) ...
        isequal(size(value), [options.windowCount*windowLength, 8]), emgs), ...
        "all"), ...
    "capturesUnique", size(unique(captureMatrix, "rows"), 1) == ...
        options.episodeCount, ...
    "finite", all(cellfun(@(value) all(isfinite(value), "all"), emgs), ...
        "all"), ...
    "activityExact", max(abs(aggregateActivity-options.targetActivity)) ...
        <= options.activityTolerance, ...
    "gateNeverActive", ~any(gateActive), ...
    "countdownNeverActive", ~any(lowActivityCountdown), ...
    "crossDominantSeparation", minimumDistance >= ...
        options.minimumCrossDominantEmgRms, ...
    "flatChannelPreserved", all(captureMatrix(:, ...
        (flatChannels-1)*options.windowCount*windowLength + ...
        (1:options.windowCount*windowLength)) == 0, "all"), ...
    "noHardware", true);
if ~all(struct2array(checks))
    error("buildNoGloveStage7sRestSupportCorpus:ContractFailed", ...
        "A prospective dataset invariant failed.");
end

corpus = struct( ...
    "schemaVersion", 1, "stage", "7S", ...
    "emgs", {emgs}, "metadata", metadata, ...
    "designTable", designTable, "featureMatrix", features, ...
    "frozenEmgScale", scale, ...
    "minimumCrossDominantEmgRms", minimumDistance, ...
    "checks", checks, "trainingUsed", false, ...
    "simulationUsed", false, "hardwareUsed", false);
end

function raw = makeWindow(envelope, episode, window, seed, flatChannels)
sampleCount = 40;
channelCount = numel(envelope);
sample = (0:sampleCount-1)';
raw = zeros(sampleCount, channelCount);
for channel = 1:channelCount
    if ismember(channel, flatChannels)
        continue;
    end
    modulationCode = mod(seed+13*episode+5*window+3*channel, 19)/18;
    modulationDepth = 0.04+0.08*modulationCode;
    frequency = 1+mod(episode+2*window+channel, 5);
    phase = 0.17*episode+0.11*window+0.07*channel;
    shape = 1+modulationDepth*sin( ...
        2*pi*frequency*sample/sampleCount+phase);
    shape = shape/mean(shape);
    carrier = (-1).^(sample+mod(episode+window+channel, 2));
    raw(:, channel) = envelope(channel).*shape.*carrier;
end
end

function value = minimumCrossDominantDistance( ...
        features, dominantChannel, scale)
value = inf;
for row = 1:size(features, 1)
    candidates = dominantChannel ~= dominantChannel(row);
    difference = (features(row, :) - features(candidates, :))./scale;
    distances = sqrt(mean(difference.^2, 2));
    value = min(value, min(distances));
end
if ~isfinite(value)
    error("buildNoGloveStage7sRestSupportCorpus:NoCrossDominantPairs", ...
        "At least two dominant channels are required.");
end
end
