function config = buildNoGloveSimulationPositionSafety(calibration, enabled)
%buildNoGloveSimulationPositionSafety builds an explicit simulation adapter.

arguments
    calibration (1, 1) struct
    enabled (1, 1) logical = true
end

if ~isfield(calibration, "limits") || ...
        ~isfield(calibration.limits, "positionMin") || ...
        ~isfield(calibration.limits, "positionMax")
    error("buildNoGloveSimulationPositionSafety:MissingLimits", ...
        "Calibration must contain positionMin and positionMax.");
end

config = struct( ...
    "enabled", enabled, ...
    "mode", "clipTrajectoryOutput", ...
    "positionMin", double(calibration.limits.positionMin(:)'), ...
    "positionMax", double(calibration.limits.positionMax(:)'), ...
    "encoderScale", [26500, 11500, 8500, 9000]);

% Central validation prevents a launcher from publishing an invalid limit.
limitSimulationPosition(zeros(0, 4), config);
end
