function corpus = buildNoGloveStage7bTemporalCorpus( ...
        calibration, expectedContext, options)
%buildNoGloveStage7bTemporalCorpus creates designed EMG-only pulses.
%
% Profiles use raw windows from the same deterministic synthetic session as
% ETAPA 6. Each pulse has pre-rest, ramp-up, plateau, ramp-down and a long
% final hold. This is a simulator-identification fixture, not human EMG.

arguments
    calibration (1, 1) struct
    expectedContext (1, 1) struct
    options.calibrationSeed (1, 1) double ...
        {mustBeInteger, mustBeNonnegative} = 11
    options.profileSeed (1, 1) double ...
        {mustBeInteger, mustBeNonnegative} = 7701
    options.repetitionsPerAxis (1, 1) double ...
        {mustBeInteger, mustBePositive} = 4
end

validation = validateIntentCalibration(calibration, expectedContext);
if ~validation.isValid
    error("buildNoGloveStage7bTemporalCorpus:InvalidCalibration", ...
        "A valid same-session calibration is required: %s.", ...
        strjoin(validation.issues, "; "));
end

baseConfig = buildNoGloveStage2OfflineConfig(options.calibrationSeed);
baseDataset = buildSyntheticEmgIntentDataset(baseConfig);
baseCalibration = calibrateEmgIntent( ...
    baseDataset.restCapture, baseDataset.instructionTrials, ...
    baseConfig.calibrationOptions);
if string(baseCalibration.contentSha256) ~= ...
        string(calibration.contentSha256)
    error("buildNoGloveStage7bTemporalCorpus:CalibrationMismatch", ...
        "The designed corpus must use the exact ETAPA 6 calibration session.");
end

[scaleSchedule, phaseSchedule] = buildSchedule();
windowCount = numel(scaleSchedule);
windowLength = double(calibration.windowLengthSamples);
profileCount = 2 * options.repetitionsPerAxis;
emgs = cell(profileCount, 2);
protocolRows = repmat(emptyProtocolRow(), profileCount * 2, 1);
validationRows = repmat(emptyValidationRow(), profileCount * 2, 1);

labels = string({baseDataset.instructionTrials.label});
restRaw = double(baseDataset.restCapture.rawEmg);
rowIdx = 0;
for repetitionId = 1:profileCount
    if repetitionId <= options.repetitionsPerAxis
        axisName = "primary";
        positiveLabel = "close_maximum";
        negativeLabel = "open_maximum";
        axisIndex = 1;
    else
        axisName = "thumb";
        positiveLabel = "thumb_oppose_maximum";
        negativeLabel = "thumb_release_maximum";
        axisIndex = 2;
    end
    trialLabels = [positiveLabel, negativeLabel];
    directions = [1, -1];
    directionNames = ["positive", "negative"];
    for side = 1:2
        rowIdx = rowIdx + 1;
        trialMatch = find(labels == trialLabels(side));
        if numel(trialMatch) ~= 1
            error("buildNoGloveStage7bTemporalCorpus:TrialNotFound", ...
                "Expected one source trial %s.", trialLabels(side));
        end
        activeRaw = double( ...
            baseDataset.instructionTrials(trialMatch).rawEmg);
        raw = blendProfileWindows(restRaw, activeRaw, scaleSchedule, ...
            windowLength, options.profileSeed, repetitionId, side);
        emgs{repetitionId, side} = raw;
        profileId = sprintf("%s_%s_r%02d", ...
            axisName, directionNames(side), repetitionId);
        decoded = validateProfile(raw, calibration, expectedContext, ...
            axisName, axisIndex, directions(side), scaleSchedule, ...
            phaseSchedule);

        protocol = emptyProtocolRow();
        protocol.profileId = profileId;
        protocol.repetitionId = repetitionId;
        protocol.side = side;
        protocol.synergyAxis = axisName;
        protocol.directionName = directionNames(side);
        protocol.expectedIntentSign = directions(side);
        protocol.sourceTrialLabel = trialLabels(side);
        protocol.windowCount = windowCount;
        protocol.sampleCount = size(raw, 1);
        protocol.preRestWindows = sum(phaseSchedule == "pre_rest");
        protocol.rampUpWindows = sum(phaseSchedule == "ramp_up");
        protocol.plateauWindows = sum(phaseSchedule == "plateau");
        protocol.rampDownWindows = sum(phaseSchedule == "ramp_down");
        protocol.finalHoldWindows = sum(phaseSchedule == "final_hold");
        protocolRows(rowIdx) = protocol;

        profileValidation = emptyValidationRow();
        profileValidation.profileId = profileId;
        profileValidation.repetitionId = repetitionId;
        profileValidation.side = side;
        profileValidation.synergyAxis = axisName;
        profileValidation.directionName = directionNames(side);
        profileValidation.axisIntentMean = decoded.axisIntentMean;
        profileValidation.crossAxisIntentMean = ...
            decoded.crossAxisIntentMean;
        profileValidation.axisDominanceRatio = ...
            decoded.axisDominanceRatio;
        profileValidation.activeWindowCount = decoded.activeWindowCount;
        profileValidation.firstActiveWindow = decoded.firstActiveWindow;
        profileValidation.lastActiveWindow = decoded.lastActiveWindow;
        profileValidation.initialRestValid = decoded.initialRestValid;
        profileValidation.finalHoldValid = decoded.finalHoldValid;
        profileValidation.intentSignValid = decoded.intentSignValid;
        profileValidation.axisDominanceValid = ...
            decoded.axisDominanceValid;
        profileValidation.finiteAndBounded = decoded.finiteAndBounded;
        profileValidation.isValid = decoded.isValid;
        validationRows(rowIdx) = profileValidation;
    end
end

protocolTable = struct2table(protocolRows);
validationTable = struct2table(validationRows);
if ~all(validationTable.isValid)
    invalid = validationTable.profileId(~validationTable.isValid);
    error("buildNoGloveStage7bTemporalCorpus:InvalidProfile", ...
        "Designed profile validation failed: %s.", strjoin(invalid, ", "));
end

windowProtocol = table((1:windowCount)', phaseSchedule(:), ...
    scaleSchedule(:), 'VariableNames', ...
    ["windowIndex", "phase", "amplitudeScale"]);
metadata = struct( ...
    "schemaVersion", 1, ...
    "stage", "7B", ...
    "role", "designed_temporal_excitation", ...
    "fixtureVersion", "no-glove-stage7b-temporal-v1", ...
    "dataProvenance", "synthetic_same_session", ...
    "calibrationSeed", options.calibrationSeed, ...
    "profileSeed", options.profileSeed, ...
    "calibrationContentSha256", calibration.contentSha256, ...
    "userId", calibration.userId, ...
    "sessionId", calibration.sessionId, ...
    "channelOrder", calibration.channelOrder, ...
    "sampleRateHz", calibration.sampleRateHz, ...
    "windowLengthSamples", calibration.windowLengthSamples, ...
    "hopLengthSamples", calibration.hopLengthSamples, ...
    "rawEmgUnits", calibration.units.rawEmg, ...
    "profileCount", height(protocolTable), ...
    "repetitionCount", profileCount, ...
    "profilesPerRepetition", 2, ...
    "hardwareUsed", false);

corpus = struct( ...
    "schemaVersion", 1, ...
    "stage", "7B", ...
    "fixtureVersion", metadata.fixtureVersion, ...
    "emgs", {emgs}, ...
    "metadata", metadata, ...
    "protocolTable", protocolTable, ...
    "validationTable", validationTable, ...
    "windowProtocol", windowProtocol, ...
    "scaleSchedule", scaleSchedule(:), ...
    "phaseSchedule", phaseSchedule(:), ...
    "calibrationContentSha256", calibration.contentSha256, ...
    "expectedSimulationCount", numel(emgs), ...
    "agent7250Used", false, ...
    "hardwareUsed", false);
end

function [scales, phases] = buildSchedule()
preRest = zeros(1, 8);
rampUp = linspace(0.25, 1.00, 6);
plateau = ones(1, 12);
rampDown = linspace(0.85, 0.15, 6);
finalHold = zeros(1, 20);
scales = [preRest, rampUp, plateau, rampDown, finalHold];
phases = [repmat("pre_rest", size(preRest)), ...
    repmat("ramp_up", size(rampUp)), ...
    repmat("plateau", size(plateau)), ...
    repmat("ramp_down", size(rampDown)), ...
    repmat("final_hold", size(finalHold))];
end

function raw = blendProfileWindows(restRaw, activeRaw, scales, ...
        windowLength, profileSeed, repetitionId, side)
restWindowCount = size(restRaw, 1) / windowLength;
activeWindowCount = size(activeRaw, 1) / windowLength;
if fix(restWindowCount) ~= restWindowCount || ...
        fix(activeWindowCount) ~= activeWindowCount
    error("buildNoGloveStage7bTemporalCorpus:InvalidSourceWindows", ...
        "Source captures must contain complete calibrated windows.");
end
channelCount = size(restRaw, 2);
raw = zeros(numel(scales) * windowLength, channelCount);
offset = double(profileSeed) + 17*repetitionId + 31*side;
for windowIdx = 1:numel(scales)
    outputRows = (windowIdx-1)*windowLength + (1:windowLength);
    restIdx = 1 + mod(offset + 3*windowIdx - 1, restWindowCount);
    activeIdx = 1 + mod(offset + 5*windowIdx - 1, activeWindowCount);
    restRows = (restIdx-1)*windowLength + (1:windowLength);
    activeRows = (activeIdx-1)*windowLength + (1:windowLength);
    raw(outputRows, :) = restRaw(restRows, :) + ...
        scales(windowIdx) .* activeRaw(activeRows, :);
end
end

function result = validateProfile(raw, calibration, expectedContext, ...
        axisName, axisIndex, expectedSign, scales, phases)
[velocity, intent, ~, details] = mapEmgToIntentVelocity( ...
    raw, calibration, expectedContext);
plateau = phases == "plateau";
axisMean = mean(intent(plateau, axisIndex));
crossAxisIndex = 3-axisIndex;
crossAxisMean = mean(intent(plateau, crossAxisIndex));
dominanceRatio = abs(axisMean) / max(1e-12, abs(crossAxisMean));
activeWindows = find(details.gateActive);
if isempty(activeWindows)
    firstActive = NaN;
    lastActive = NaN;
else
    firstActive = activeWindows(1);
    lastActive = activeWindows(end);
end
initialRestValid = ~any(details.gateActive(phases == "pre_rest"));
finalIndices = find(phases == "final_hold");
finalIndices = finalIndices(max(1, end-9):end);
finalHoldValid = ~any(details.gateActive(finalIndices)) && ...
    all(velocity(finalIndices, :) == 0, "all");
intentSignValid = sign(axisMean) == expectedSign && abs(axisMean) >= 0.25;
axisDominanceValid = dominanceRatio >= 1.25;
vMax = double(calibration.limits.velocityMax(:)');
finiteAndBounded = all(isfinite(raw), "all") && ...
    all(isfinite(intent), "all") && all(isfinite(velocity), "all") && ...
    all(abs(velocity) <= vMax + 128*eps(max(vMax)), "all") && ...
    ~details.wmoosStandardizationUsed;
isValid = initialRestValid && finalHoldValid && intentSignValid && ...
    axisDominanceValid && finiteAndBounded && any(scales > 0) && ...
    any(details.gateActive(plateau));
result = struct( ...
    "axisName", axisName, ...
    "axisIntentMean", axisMean, ...
    "crossAxisIntentMean", crossAxisMean, ...
    "axisDominanceRatio", dominanceRatio, ...
    "activeWindowCount", sum(details.gateActive), ...
    "firstActiveWindow", firstActive, ...
    "lastActiveWindow", lastActive, ...
    "initialRestValid", initialRestValid, ...
    "finalHoldValid", finalHoldValid, ...
    "intentSignValid", intentSignValid, ...
    "axisDominanceValid", axisDominanceValid, ...
    "finiteAndBounded", finiteAndBounded, ...
    "isValid", isValid);
end

function row = emptyProtocolRow()
row = struct("profileId", "", "repetitionId", 0, "side", 0, ...
    "synergyAxis", "", "directionName", "", ...
    "expectedIntentSign", 0, "sourceTrialLabel", "", ...
    "windowCount", 0, "sampleCount", 0, "preRestWindows", 0, ...
    "rampUpWindows", 0, "plateauWindows", 0, ...
    "rampDownWindows", 0, "finalHoldWindows", 0);
end

function row = emptyValidationRow()
row = struct("profileId", "", "repetitionId", 0, "side", 0, ...
    "synergyAxis", "", "directionName", "", ...
    "axisIntentMean", NaN, "crossAxisIntentMean", NaN, ...
    "axisDominanceRatio", NaN, "activeWindowCount", 0, ...
    "firstActiveWindow", NaN, "lastActiveWindow", NaN, ...
    "initialRestValid", false, "finalHoldValid", false, ...
    "intentSignValid", false, "axisDominanceValid", false, ...
    "finiteAndBounded", false, "isValid", false);
end
