function override = buildNoGloveStage6Override( ...
        calibration, expectedContext, randomSeed, trainingEpisodes, ...
        trainingSaveEvery, datasetPath, trainingBaseDirectory)
%buildNoGloveStage6Override creates a new intentMarkov60 TD3 profile.

arguments
    calibration (1, 1) struct
    expectedContext (1, 1) struct
    randomSeed (1, 1) double {mustBeInteger, mustBeNonnegative}
    trainingEpisodes (1, 1) double {mustBeInteger, mustBePositive}
    trainingSaveEvery (1, 1) double {mustBeInteger, mustBePositive}
    datasetPath (1, 1) string
    trainingBaseDirectory (1, 1) string
end

validation = validateIntentCalibration(calibration, expectedContext);
if ~validation.isValid
    error("buildNoGloveStage6Override:InvalidCalibration", ...
        "ETAPA 6 requires a compatible calibration: %s", ...
        strjoin(validation.issues, "; "));
end
if ~isfile(datasetPath)
    error("buildNoGloveStage6Override:DatasetNotFound", ...
        "EMG-only training dataset not found: %s", datasetPath);
end
if trainingSaveEvery > trainingEpisodes || ...
        mod(trainingEpisodes, trainingSaveEvery) ~= 0
    error("buildNoGloveStage6Override:InvalidCheckpointCadence", ...
        "Save cadence must divide the episode budget and include the final episode.");
end

[datasetFolder, datasetStem] = fileparts(datasetPath);
datasetName = string(datasetStem);
override = buildNoGloveStage4Override( ...
    calibration, expectedContext, randomSeed);
override.run_training = true;
override.newTraining = true;
override.agentFile = "";
override.agent_id = "td3_no_glove_intent";
override.trainingMaxEpisodes = trainingEpisodes;
override.trainingSaveAgentEvery = trainingSaveEvery;
override.trainingPlots = "none";
override.flagSaveTraining = true;
override.episode_save_freq = 1;
override.enableDetailedActionDiagnostics = true;
override.savePerMotorMetrics = true;
override.dataset = {char(datasetName)};
override.dataset_folder = string(datasetFolder);
override.agents_directory = @(agent_id, variant) fullfile( ...
    trainingBaseDirectory, ...
    string(datetime("now", "Format", "yy-MM-dd HH m s")));

% A completely new feedforward policy. The full hyperparameter struct is
% explicit because an override replaces a top-level struct atomically.
% No historical checkpoint, replay buffer or residual base may influence
% actor or critics.
override.td3 = struct( ...
    "numHiddenUnits", 64, ...
    "useRecurrent", false, ...
    "recurrentUnits", 16, ...
    "sequenceLength", 1, ...
    "numStepsToLookAhead", 1, ...
    "actorLearnRate", 1e-4, ...
    "criticLearnRate", 1e-3, ...
    "actorL2Regularization", 1e-4, ...
    "criticL2Regularization", 1e-4, ...
    "gradientThreshold", 1, ...
    "targetSmoothFactor", 5e-3, ...
    "discountFactor", 0.95, ...
    "miniBatchSize", 64, ...
    "experienceBufferLength", 1e5, ...
    "sampleTime", calibration.limits.deltaT, ...
    "policyUpdateFrequency", 2, ...
    "targetUpdateFrequency", 2, ...
    "explorationStd", 0.2, ...
    "explorationStdDecayRate", 1e-4, ...
    "explorationStdMin", 0.02, ...
    "resetExperienceBufferBeforeTraining", true, ...
    "targetPolicyStd", 0.2, ...
    "targetPolicyNoiseClip", 0.5);
override.td3Residual = struct( ...
    "enabled", false, ...
    "baseCheckpointPath", "", ...
    "baseLabel", "", ...
    "residualScale", 0, ...
    "hiddenUnits", 0, ...
    "logDiagnostics", false);

override.referenceSource = "emgIntent";
override.observationVariant = "intentMarkov60";
override.rewardType = "trackingIntentActionRateReward";
override.actionInterfaceVariant = "baselineQuantized";
override.quantizeCommandsForSimulation = true;
override.unifyActions = false;
override.usePrerecorded = true;
override.simMotors = true;
override.connect_glove = false;
override.plotEpisodeOnTest = false;
override.verbose = false;
end
