function config = buildNoGloveStage2OfflineConfig(seed)
%buildNoGloveStage2OfflineConfig creates the deterministic ETAPA 2 profile.
%
% Mechanical values and B are synthetic validation-fixture parameters. They
% are explicit and versioned, but are not asserted to be validated limits or
% a physical four-DoF decomposition.

arguments
    seed (1, 1) double {mustBeInteger, mustBeNonnegative} = 11
end

channelOrder = "myo_ch" + (1:8);
motorOrder = ["little", "idx", "thumb", "mid"];
synergyMatrix = [ ...
    1.00,  0.00; ...
    0.85,  0.10; ...
    0.45,  1.00; ...
    0.75, -0.10];

calibrationOptions = struct( ...
    "userId", "synthetic-user-stage2", ...
    "sessionId", "synthetic-session-stage2-seed-" + seed, ...
    "calibratedAt", "2026-08-18T00:00:00Z", ...
    "dataProvenance", "synthetic", ...
    "instructionProtocolVersion", "categorical-r2-v1", ...
    "channelOrder", channelOrder, ...
    "sampleRateHz", 200, ...
    "windowLengthSamples", 40, ...
    "hopLengthSamples", 40, ...
    "signalPercentile", 95, ...
    "epsilon", 1e-8, ...
    "minCalibrationRange", 1e-3, ...
    "flatChannelMadMultiplier", 6, ...
    "ridgeLambda", 1e-3, ...
    "decoderFitLimit", 0.95, ...
    "maxDecoderTrainingRmse", 0.20, ...
    "minRestWindows", 8, ...
    "minWindowsPerInstruction", 5, ...
    "synergyMatrix", synergyMatrix, ...
    "synergyMatrixVersion", "synthetic-unvalidated-mechanics-v1", ...
    "motorOrder", motorOrder, ...
    "velocityMax", [0.24, 0.22, 0.18, 0.20], ...
    "positionMin", zeros(1, 4), ...
    "positionMax", ones(1, 4), ...
    "accelerationMax", [0.80, 0.75, 0.65, 0.70], ...
    "deltaT", 0.2, ...
    "thetaOn", 0.14, ...
    "thetaOff", 0.06, ...
    "nOn", 2, ...
    "nOff", 3, ...
    "rawEmgUnits", "normalizedMyoAdc", ...
    "envelopeUnits", "meanAbsoluteNormalizedMyoAdc", ...
    "positionUnits", "encoderNormalized", ...
    "velocityUnits", "encoderNormalizedPerSecond", ...
    "accelerationUnits", "encoderNormalizedPerSecondSquared");

config = struct( ...
    "stage", 2, ...
    "schemaVersion", 1, ...
    "seed", seed, ...
    "dataProvenance", "synthetic", ...
    "fixtureVersion", "no-glove-intent-stage2-synthetic-v1", ...
    "referenceSource", "emgIntent", ...
    "simMotors", true, ...
    "connectGlove", false, ...
    "usePrerecorded", true, ...
    "runTraining", false, ...
    "newTraining", false, ...
    "simulatorUsed", false, ...
    "hardwareUsed", false, ...
    "reinforcementLearningUsed", false, ...
    "agent7250Used", false, ...
    "wmoosUsedForIntent", false, ...
    "wmoosFeaturesComputedSeparately", true, ...
    "initialEncoder", [0.45, 0.50, 0.40, 0.55], ...
    "calibrationOptions", calibrationOptions);
end
