function corpus = buildNoGloveStage6SyntheticCorpus(calibrationSeed)
%buildNoGloveStage6SyntheticCorpus builds the ETAPA 6 EMG-only corpus.
%
% The published Denis dataset has no compatible rest/opposition calibration
% protocol. ETAPA 6 therefore uses independent synthetic captures declared
% as belonging to the same synthetic session as the ETAPA 2 calibration.
% This is an integration/training fixture, not evidence about human EMG.

arguments
    calibrationSeed (1, 1) double {mustBeInteger, mustBeNonnegative} = 11
end

calibrationConfig = buildNoGloveStage2OfflineConfig(calibrationSeed);
calibrationDataset = buildSyntheticEmgIntentDataset(calibrationConfig);
calibration = calibrateEmgIntent( ...
    calibrationDataset.restCapture, ...
    calibrationDataset.instructionTrials, ...
    calibrationConfig.calibrationOptions);
expectedContext = buildExpectedContext( ...
    calibrationDataset, calibrationConfig.calibrationOptions, calibration);
validation = validateIntentCalibration(calibration, expectedContext);
if ~validation.isValid
    error("buildNoGloveStage6SyntheticCorpus:InvalidCalibration", ...
        "Synthetic calibration is invalid: %s", ...
        strjoin(validation.issues, "; "));
end

trainingSeeds = 6101:6112;
evaluationSeeds = 6201:6212;
restSeeds = 6301:6306;
trainingEmgs = buildCaptureCells( ...
    calibrationConfig, trainingSeeds, "evaluationRawEmg");
evaluationEmgs = buildCaptureCells( ...
    calibrationConfig, evaluationSeeds, "evaluationRawEmg");
restEmgs = buildCaptureCells( ...
    calibrationConfig, restSeeds, "restCapture");

metadataBase = struct( ...
    "schemaVersion", 1, ...
    "stage", 6, ...
    "dataProvenance", "synthetic", ...
    "fixtureVersion", "no-glove-intent-stage6-synthetic-v1", ...
    "userId", calibration.userId, ...
    "sessionId", calibration.sessionId, ...
    "channelOrder", calibration.channelOrder, ...
    "sampleRateHz", calibration.sampleRateHz, ...
    "windowLengthSamples", calibration.windowLengthSamples, ...
    "hopLengthSamples", calibration.hopLengthSamples, ...
    "rawEmgUnits", calibration.units.rawEmg, ...
    "calibrationContentSha256", calibration.contentSha256);

trainingMetadata = metadataBase;
trainingMetadata.role = "training";
trainingMetadata.captureSeeds = trainingSeeds;
evaluationMetadata = metadataBase;
evaluationMetadata.role = "acceptance_evaluation";
evaluationMetadata.captureSeeds = evaluationSeeds;
restMetadata = metadataBase;
restMetadata.role = "steady_calibrated_rest";
restMetadata.captureSeeds = restSeeds;

[restFalseActivationFraction, restWindowCount] = ...
    computeRestFalseActivation(restEmgs, calibration, expectedContext);

corpus = struct( ...
    "schemaVersion", 1, ...
    "stage", 6, ...
    "fixtureVersion", metadataBase.fixtureVersion, ...
    "dataProvenance", "synthetic", ...
    "calibrationSeed", calibrationSeed, ...
    "calibration", calibration, ...
    "calibrationValidation", validation, ...
    "expectedContext", expectedContext, ...
    "trainingEmgs", {trainingEmgs}, ...
    "evaluationEmgs", {evaluationEmgs}, ...
    "restEmgs", {restEmgs}, ...
    "trainingMetadata", trainingMetadata, ...
    "evaluationMetadata", evaluationMetadata, ...
    "restMetadata", restMetadata, ...
    "trainingCaptureSeeds", trainingSeeds, ...
    "evaluationCaptureSeeds", evaluationSeeds, ...
    "restCaptureSeeds", restSeeds, ...
    "restFalseActivationFraction", restFalseActivationFraction, ...
    "restWindowCount", restWindowCount, ...
    "agent7250Used", false, ...
    "hardwareUsed", false);
end

function emgs = buildCaptureCells(baseConfig, captureSeeds, sourceField)
if mod(numel(captureSeeds), 2) ~= 0
    error("buildNoGloveStage6SyntheticCorpus:OddCaptureCount", ...
        "Capture seeds must form N-by-2 EMG cells.");
end

emgs = cell(numel(captureSeeds) / 2, 2);
for captureIdx = 1:numel(captureSeeds)
    captureConfig = baseConfig;
    captureConfig.seed = captureSeeds(captureIdx);
    captureDataset = buildSyntheticEmgIntentDataset(captureConfig);
    if sourceField == "evaluationRawEmg"
        rawEmg = captureDataset.evaluationRawEmg;
    elseif sourceField == "restCapture"
        rawEmg = captureDataset.restCapture.rawEmg;
    else
        error("buildNoGloveStage6SyntheticCorpus:UnknownCaptureField", ...
            "Unsupported capture source %s.", sourceField);
    end
    rowIdx = ceil(captureIdx / 2);
    columnIdx = 1 + mod(captureIdx - 1, 2);
    emgs{rowIdx, columnIdx} = rawEmg;
end
end

function expectedContext = buildExpectedContext(dataset, options, calibration)
expectedUnits = struct( ...
    "rawEmg", dataset.restCapture.rawEmgUnits, ...
    "envelope", options.envelopeUnits, ...
    "position", options.positionUnits, ...
    "velocity", options.velocityUnits, ...
    "acceleration", options.accelerationUnits);
expectedContext = struct( ...
    "userId", dataset.restCapture.userId, ...
    "sessionId", dataset.restCapture.sessionId, ...
    "channelOrder", dataset.restCapture.channelOrder, ...
    "sampleRateHz", dataset.restCapture.sampleRateHz, ...
    "windowLengthSamples", dataset.windowLengthSamples, ...
    "hopLengthSamples", dataset.hopLengthSamples, ...
    "dataProvenance", dataset.restCapture.dataProvenance, ...
    "motorOrder", options.motorOrder, ...
    "units", expectedUnits, ...
    "synergyMatrixVersion", options.synergyMatrixVersion, ...
    "instructionProtocolVersion", options.instructionProtocolVersion, ...
    "sourceDomain", "rawEmgSameSession", ...
    "calibrationContentSha256", calibration.contentSha256);
end

function [fraction, windowCount] = computeRestFalseActivation( ...
        restEmgs, calibration, expectedContext)
activeCount = 0;
windowCount = 0;
for captureIdx = 1:numel(restEmgs)
    [~, ~, ~, details] = mapEmgToIntentVelocity( ...
        restEmgs{captureIdx}, calibration, expectedContext);
    activeCount = activeCount + sum(details.gateActive);
    windowCount = windowCount + numel(details.gateActive);
end
fraction = activeCount / max(1, windowCount);
end
