function override = buildNoGloveStage1Override(randomSeed)
%buildNoGloveStage1Override returns the simulation-only ETAPA 1 profile.

arguments
    randomSeed (1, 1) double {mustBeInteger, mustBeNonnegative} = 11
end

override = struct( ...
    "referenceSource", "emgIntent", ...
    "run_training", false, ...
    "newTraining", false, ...
    "usePrerecorded", true, ...
    "simMotors", true, ...
    "connect_glove", false, ...
    "randomSeed", randomSeed, ...
    "dataset", "DENIS", ...
    "dataset_folder", '.\data\datasets\Denis Dataset\', ...
    "period", 0.2, ...
    "maxNumberStepsInEpisodes", 50, ...
    "observationVariant", "markov52", ...
    "numEMGFeatures", 40, ...
    "emgHistoryLength", 3, ...
    "rewardType", "trackingMseActionRateReward", ...
    "rewardActionWeight", 0.01, ...
    "rewardDeltaActionWeight", 0.05, ...
    "actionInterfaceVariant", "baselineQuantized", ...
    "unifyActions", false, ...
    "speeds", 255 * ones(1, 4), ...
    "quantizeCommandsForSimulation", true, ...
    "actionCommandActivationThreshold", 0.05, ...
    "actionCommandLevels", [0 64 96 128 160 192 224 255], ...
    "rf_modify_actions", false, ...
    "plotEpisodeOnTest", false, ...
    "flagSaveTraining", false, ...
    "verbose", false, ...
    "td3Residual", struct( ...
        "enabled", false, ...
        "baseCheckpointPath", "", ...
        "baseLabel", "", ...
        "residualScale", 0, ...
        "hiddenUnits", 0, ...
        "logDiagnostics", false));
end
