function override = buildNoGloveStage5Override( ...
        calibration, expectedContext, randomSeed)
%buildNoGloveStage5Override simulation-only conventional baseline profile.

arguments
    calibration (1, 1) struct
    expectedContext (1, 1) struct
    randomSeed (1, 1) double {mustBeInteger, mustBeNonnegative} = 11
end

override = buildNoGloveStage4Override( ...
    calibration, expectedContext, randomSeed);

% Conservative first baseline: P control capped at the first nonzero
% baselineQuantized level (64/255). The same implementation supports an
% explicit PD profile later without changing plant, target or quantizer.
override.conventionalController = struct( ...
    "schemaVersion", 1, ...
    "type", "P", ...
    "kp", 1.50 * ones(4, 1), ...
    "kd", zeros(4, 1), ...
    "maxAction", (64 / 255) * ones(4, 1), ...
    "positionTolerance", 0.01 * ones(4, 1), ...
    "velocityTolerance", 0.03 * ones(4, 1));
override.plantDiagnostic = struct( ...
    "schemaVersion", 1, ...
    "initialModes", ["home", "intermediate"], ...
    "pwmLevels", [64, 96, 128, 160, 192, 224, 255], ...
    "stepDuration", 2.0, ...
    "simulatorSamplingPeriod", 0.14, ...
    "movementThresholdNormalized", 0.005, ...
    "referenceStepAmplitude", 0.20, ...
    "referenceRampRate", 0.10, ...
    "closedLoopDuration", 3.0, ...
    "positionMin", zeros(1, 4), ...
    "positionMax", ones(1, 4));

override.referenceSource = "emgIntent";
override.observationVariant = "intentMarkov60";
override.run_training = false;
override.newTraining = false;
override.usePrerecorded = true;
override.simMotors = true;
override.connect_glove = false;
override.actionInterfaceVariant = "baselineQuantized";
override.quantizeCommandsForSimulation = true;
override.unifyActions = false;
override.flagSaveTraining = false;
override.plotEpisodeOnTest = false;
end
