function [actor, policyManifest, agent] = loadE2AFrozenActor()
%loadE2AFrozenActor carga Agent7250 solo como instrumento causal congelado.
% No crea agentes, no modifica optimizadores ni ejecuta entrenamiento.
% La inferencia usa getAction(actor, {state}), sin politica de exploracion.
% Se rechaza un checkpoint distinto de la copia canonica versionada.

checkpointPath = string(getAgent7250CheckpointPath());
canonicalPath = string(fullfile(getCanonicalCheckpointRoot(), ...
    "Agent7250_valid_baseline", "Agent7250_valid_baseline.mat"));
if checkpointPath ~= canonicalPath || ~isfile(canonicalPath)
    error("ProtesisPracticas:E2ACanonicalActorMissing", ...
        "E2A requiere el checkpoint canonico versionado de Agent7250.");
end

agent = loadSavedAgent(checkpointPath);
actor = getActor(agent);
if ~isa(actor, "rl.function.rlContinuousDeterministicActor") || ...
        ~isequal(actor.ObservationInfo.Dimension, [52 1]) || ...
        ~isequal(actor.ActionInfo.Dimension, [4 1])
    error("ProtesisPracticas:E2AActorContract", ...
        "El instrumento causal debe ser un actor determinista 52 -> 4.");
end
if string(actor.UseDevice) ~= "cpu"
    error("ProtesisPracticas:E2AActorDevice", ...
        "La comparacion causal exige el actor congelado en CPU.");
end
network = getModel(actor);
if numel(network.InputNames) ~= 1 || ~isempty(network.State)
    error("ProtesisPracticas:E2AActorState", ...
        "E2A requiere una sola entrada de observacion y una red sin estado recurrente.");
end

policyManifest = struct( ...
    "label", "Agent7250", ...
    "purpose", "FROZEN_CAUSAL_INSTRUMENT_ONLY", ...
    "checkpointPath", checkpointPath, ...
    "checkpointSHA256", fileSha256(checkpointPath), ...
    "trainingPlantSource", "HISTORICAL_SOURCE_NOT_RECORDED", ...
    "agentClass", string(class(agent)), ...
    "actorClass", string(class(actor)), ...
    "observationDimension", actor.ObservationInfo.Dimension, ...
    "actionDimension", actor.ActionInfo.Dimension, ...
    "device", string(actor.UseDevice), ...
    "inputNames", string(network.InputNames), ...
    "outputNames", string(network.OutputNames), ...
    "layerCount", numel(network.Layers), ...
    "recurrentStatePresent", ~isempty(network.State), ...
    "inferenceAPI", "getAction(actor, {state})", ...
    "explorationUsed", false, ...
    "trainingExecuted", false);
end

function hash = fileSha256(path)
[fid, message] = fopen(path, "rb");
if fid < 0
    error("ProtesisPracticas:E2AActorReadFailed", "%s", message);
end
closeFile = onCleanup(@() fclose(fid)); %#ok<NASGU>
digest = java.security.MessageDigest.getInstance("SHA-256");
digest.update(fread(fid, inf, "*uint8"));
hash = string(lower(reshape(dec2hex(typecast(digest.digest(), "uint8"), 2)', 1, [])));
end
