function audit = validateNoGloveStage7sEvaluationProfile( ...
        profile, checkpointPath, datasetPath, options)
%validateNoGloveStage7sEvaluationProfile rejects unsafe 7S acquisition.

arguments
    profile (1, 1) struct
    checkpointPath (1, 1) string
    datasetPath (1, 1) string
    options.seed (1, 1) double {mustBeInteger} = 7701
    options.episodeCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 80
    options.maxSteps (1, 1) double ...
        {mustBeInteger, mustBePositive} = 20
    options.calibrationSha256 (1, 1) string = ...
        "9c2ff4aba271c337df076874b5ff7ed08a4a07bcf7970f358c886e05e15e43a2"
end

required = ["referenceSource", "run_training", "newTraining", ...
    "usePrerecorded", "simMotors", "connect_glove", "randomSeed", ...
    "dataset", "dataset_folder", "observationVariant", "rewardType", ...
    "actionInterfaceVariant", "agentFile", "agent_id", ...
    "episode_save_freq", "plotEpisodeOnTest", "td3", "td3Residual", ...
    "intentCalibration", "intentExpectedContext", ...
    "simulationPositionSafety", "simOpts", ...
    "intentRewardPositionWeight", "intentRewardVelocityWeight", ...
    "intentRewardActionWeight", "intentRewardDeltaActionWeight", ...
    "intentRewardSaturationWeight", "intentRewardSoftActionLimit"];
if ~all(isfield(profile, cellstr(required)))
    error("validateNoGloveStage7sEvaluationProfile:MissingField", ...
        "The ETAPA 7S evaluation profile is incomplete.");
end
[datasetFolder, datasetStem] = fileparts(datasetPath);
datasetValue = string(profile.dataset);
if iscell(profile.dataset)
    datasetValue = string(profile.dataset{1});
end
datasetExact = numel(datasetValue) == 1 && ...
    datasetValue == string(datasetStem) && ...
    string(profile.dataset_folder) == string(datasetFolder);
simulationOptionsExact = profile.simOpts.NumSimulations == ...
    options.episodeCount && profile.simOpts.MaxSteps == options.maxSteps && ...
    ~profile.simOpts.UseParallel && ...
    string(profile.simOpts.StopOnError) == "on";
safety = profile.simulationPositionSafety;
safeMode = isstruct(safety) && isscalar(safety) && ...
    all(isfield(safety, ["enabled", "mode"])) && ...
    logical(safety.enabled) && string(safety.mode) == ...
    "clipTrajectoryOutput";
td3Safe = isstruct(profile.td3) && isfield(profile.td3, "useRecurrent") && ...
    ~logical(profile.td3.useRecurrent);
residualSafe = isstruct(profile.td3Residual) && ...
    isfield(profile.td3Residual, "enabled") && ...
    ~logical(profile.td3Residual.enabled);
calibrationExact = string(profile.intentCalibration.contentSha256) == ...
    options.calibrationSha256 && ...
    string(profile.intentExpectedContext.calibrationContentSha256) == ...
    options.calibrationSha256;

audit = struct( ...
    "noTraining", ~logical(profile.run_training) && ...
        ~logical(profile.newTraining), ...
    "prerecordedOnly", logical(profile.usePrerecorded), ...
    "simulatorOnly", logical(profile.simMotors) && ...
        ~logical(profile.connect_glove), ...
    "state60", string(profile.observationVariant) == "intentMarkov60", ...
    "emgIntent", string(profile.referenceSource) == "emgIntent", ...
    "rewardFrozen", string(profile.rewardType) == ...
        "trackingIntentActionRateReward" && ...
        profile.intentRewardPositionWeight == 1.00 && ...
        profile.intentRewardVelocityWeight == 0.00 && ...
        profile.intentRewardActionWeight == 0.05 && ...
        profile.intentRewardDeltaActionWeight == 0.05 && ...
        profile.intentRewardSaturationWeight == 0.02 && ...
        profile.intentRewardSoftActionLimit == 0.90, ...
    "quantizationFrozen", string(profile.actionInterfaceVariant) == ...
        "baselineQuantized", ...
    "feedforward", td3Safe && residualSafe, ...
    "safetyFrozen", safeMode, ...
    "checkpointExact", string(profile.agentFile) == checkpointPath && ...
        string(profile.agent_id) == "td3_no_glove_intent", ...
    "datasetExact", datasetExact, ...
    "seedExact", profile.randomSeed == options.seed, ...
    "simulationOptionsExact", simulationOptionsExact, ...
    "allEpisodesSaved", profile.episode_save_freq == 1, ...
    "plotsDisabled", ~logical(profile.plotEpisodeOnTest), ...
    "calibrationFrozen", calibrationExact, ...
    "noHardware", true);
if ~all(struct2array(audit))
    failed = string(fieldnames(audit));
    failed = failed(~struct2array(audit)');
    error("validateNoGloveStage7sEvaluationProfile:UnsafeProfile", ...
        "ETAPA 7S profile invariant(s) failed: %s", ...
        strjoin(failed, ", "));
end
end
