function results = run_markov52_offline_bc_warmstart(options)
%run_markov52_offline_bc_warmstart performs offline TD3+BC warm-start runs.

arguments
    options = struct()
end

options = normalizeOfflineOptions(options);

paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = char(paths.matlabRoot);
repoRoot = char(paths.workspaceRoot);
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));

clearConfigurablesOverride();

baseConfigs = configurables();
benchmark = getAgent7250Benchmark();

if strlength(string(options.demoRoot)) > 0
    demoRoot = string(options.demoRoot);
    demoResults = loadExistingDemoResults(demoRoot);
else
    demoOptions = struct( ...
        "numEpisodes", options.demoEpisodes, ...
        "sanityEpisodes", options.demoSanityEpisodes, ...
        "deadband", options.deadband, ...
        "errorBins", options.errorBins, ...
        "actionMagnitudes", options.actionMagnitudes, ...
        "maxDelta", options.maxDelta, ...
        "resultsRoot", options.demoResultsRoot);
    demoResults = collect_markov52_reference_demos(demoOptions);
    demoRoot = string(demoResults.resultsRoot);
end

if options.enforceSanityGate && ~demoResults.datasetSummary.acceptedBySanityGate
    error("Reference demo dataset did not pass sanity gate; aborting offline warm-start.");
end

resultsRoot = resolveResultsRoot(options.resultsRoot, repoRoot, "markov52_offline_bc_warmstart");
mkdir(resultsRoot);
mkdir(fullfile(resultsRoot, "training_runs"));

demoFiles = dir(fullfile(demoRoot, "episodes", "demo_episode_*.mat"));
if isempty(demoFiles)
    error("No demo files found in %s", fullfile(demoRoot, "episodes"));
end
demoFilePaths = string(fullfile({demoFiles.folder}, {demoFiles.name}))';

rows = cell(numel(options.bcWeights), 1);
for i = 1:numel(options.bcWeights)
    bcWeight = options.bcWeights(i);
    comboLabel = "bcWeight_" + encodeNumeric(bcWeight);
    runDir = fullfile(resultsRoot, "training_runs", comboLabel);
    mkdir(runDir);

    try
        override = buildMarkov52BaselineOverride(baseConfigs, struct( ...
            "run_training", true, ...
            "newTraining", true, ...
            "trainingPlots", "none", ...
            "plotEpisodeOnTest", false, ...
            "verbose", false, ...
            "flagSaveTraining", true));
        setConfigurablesOverride(override);
        clear configurables
        configs = configurables();
        hardware = definitions();

        obsInfo = Env.defineObservationInfo();
        actionInfo = Env.defineActionInfo();
        agent = load_agent(obsInfo, actionInfo, "td3", "", "");
        agent.AgentOptions.BatchDataRegularizerOptions = ...
            rlBehaviorCloningRegularizerOptions( ...
            BehaviorCloningRegularizerWeight=bcWeight);

        trainOpts = rlTrainingFromDataOptions( ...
            MaxEpochs=options.maxEpochs, ...
            NumStepsPerEpoch=options.numStepsPerEpoch, ...
            SaveAgentCriteria="EpochFrequency", ...
            SaveAgentValue=options.saveAgentEvery, ...
            SaveAgentDirectory=runDir, ...
            Plots=options.trainingPlots, ...
            Verbose=options.verbose);

        fds = fileDatastore(demoFilePaths, ReadFcn=@readExperienceEpisode);
        trainingInfo = trainFromData(agent, fds, trainOpts);
        normalizeOfflineCheckpointNames(runDir);

        offlineMeta = struct( ...
            "mode", "offline_bc_warmstart", ...
            "demoRoot", demoRoot, ...
            "bcWeight", bcWeight, ...
            "trainOptions", options);
        save(fullfile(runDir, "00_configs.mat"), ...
            "configs", "hardware", "offlineMeta");
        save(fullfile(runDir, "training_info.mat"), "trainingInfo");

        auditOptions = struct( ...
            "experimentDir", runDir, ...
            "samplingPolicy", struct("mode", "every_k", "k", options.saveAgentEvery), ...
            "resultsRoot", fullfile(runDir, "audit"), ...
            "verbose", false);
        auditResults = runCheckpointAudit( ...
            options.auditFastSimulations, ...
            options.auditFullSimulations, ...
            options.auditTopK, ...
            auditOptions);

        bestRow = table2struct(auditResults.phaseBTable(1, :));
        rows{i} = struct( ...
            "comboLabel", string(comboLabel), ...
            "bcWeight", bcWeight, ...
            "experimentDir", string(runDir), ...
            "demoRoot", demoRoot, ...
            "bestCheckpointPath", string(bestRow.checkpointPath), ...
            "bestCheckpointEpisode", double(bestRow.checkpointEpisode), ...
            "trackingMseMean", double(bestRow.trackingMseMean), ...
            "trackingMaeMean", double(bestRow.trackingMaeMean), ...
            "actionL2Mean", double(bestRow.actionL2Mean), ...
            "saturationFractionMean", double(bestRow.saturationFractionMean), ...
            "deltaActionL2Mean", double(bestRow.deltaActionL2Mean), ...
            "benchmarkStatus", string(bestRow.benchmarkStatus), ...
            "meetsConditionA", logical(bestRow.meetsConditionA), ...
            "meetsConditionB", logical(bestRow.meetsConditionB), ...
            "status", "ok", ...
            "errorMessage", "");

        save(fullfile(runDir, "offline_bc_result.mat"), ...
            "trainingInfo", "auditResults", "bestRow", "offlineMeta", "benchmark");
    catch ME
        clearConfigurablesOverride();
        rows{i} = struct( ...
            "comboLabel", string(comboLabel), ...
            "bcWeight", bcWeight, ...
            "experimentDir", string(runDir), ...
            "demoRoot", demoRoot, ...
            "bestCheckpointPath", "", ...
            "bestCheckpointEpisode", NaN, ...
            "trackingMseMean", NaN, ...
            "trackingMaeMean", NaN, ...
            "actionL2Mean", NaN, ...
            "saturationFractionMean", NaN, ...
            "deltaActionL2Mean", NaN, ...
            "benchmarkStatus", "Error", ...
            "meetsConditionA", false, ...
            "meetsConditionB", false, ...
            "status", "error", ...
            "errorMessage", string(ME.message));
    end
end

consolidatedTable = struct2table(vertcat(rows{:}));
consolidatedTable.statusRank = double(consolidatedTable.status ~= "ok");
consolidatedTable = sortrows(consolidatedTable, ...
    {'statusRank','trackingMseMean','saturationFractionMean','deltaActionL2Mean','actionL2Mean'}, ...
    {'ascend','ascend','ascend','ascend','ascend'});

results = struct( ...
    "resultsRoot", string(resultsRoot), ...
    "demoRoot", demoRoot, ...
    "demoSummary", demoResults.datasetSummary, ...
    "benchmark", benchmark, ...
    "options", options, ...
    "consolidatedTable", consolidatedTable, ...
    "bestCheckpointPath", string(consolidatedTable.bestCheckpointPath(1)));

writetable(consolidatedTable, fullfile(resultsRoot, "offline_bc_warmstart_summary.csv"));
writeTextFile(fullfile(resultsRoot, "offline_bc_warmstart_summary.txt"), ...
    buildOfflineSummaryText(consolidatedTable, demoResults.datasetSummary, benchmark));
save(fullfile(resultsRoot, "offline_bc_warmstart_results.mat"), ...
    "results", "consolidatedTable", "benchmark");
clearConfigurablesOverride();
end

function options = normalizeOfflineOptions(options)
defaults = struct( ...
    "demoRoot", "", ...
    "demoResultsRoot", "", ...
    "demoEpisodes", 200, ...
    "demoSanityEpisodes", 20, ...
    "deadband", 0.03, ...
    "errorBins", [0.06 0.12 0.20], ...
    "actionMagnitudes", [0.376 0.627 0.878 1.0], ...
    "maxDelta", 0.251, ...
    "bcWeights", [0.05 0.10 0.20], ...
    "maxEpochs", 200, ...
    "numStepsPerEpoch", 250, ...
    "saveAgentEvery", 25, ...
    "trainingPlots", "none", ...
    "verbose", true, ...
    "auditFastSimulations", 20, ...
    "auditFullSimulations", 50, ...
    "auditTopK", 2, ...
    "resultsRoot", "", ...
    "enforceSanityGate", true);

fields = fieldnames(defaults);
for i = 1:numel(fields)
    if ~isfield(options, fields{i}) || isempty(options.(fields{i}))
        options.(fields{i}) = defaults.(fields{i});
    end
end
end

function demoResults = loadExistingDemoResults(demoRoot)
demoRoot = char(string(demoRoot));
resultsFile = fullfile(demoRoot, "reference_demo_results.mat");
if isfile(resultsFile)
    data = load(resultsFile, "results");
    demoResults = data.results;
    return;
end

episodeFiles = dir(fullfile(demoRoot, "episodes", "demo_episode_*.mat"));
if isempty(episodeFiles)
    error("No demo dataset found in %s", demoRoot);
end

rows = cell(numel(episodeFiles), 1);
for i = 1:numel(episodeFiles)
    data = load(fullfile(episodeFiles(i).folder, episodeFiles(i).name), "episodeData");
    summary = data.episodeData.EpisodeSummary;
    summary.episodeIdx = i;
    summary.numExperiences = numel(data.episodeData.Experience);
    summary.filePath = string(fullfile(episodeFiles(i).folder, episodeFiles(i).name));
    rows{i} = summary;
end
episodeTable = struct2table(vertcat(rows{:}));
demoResults = struct( ...
    "resultsRoot", string(demoRoot), ...
    "episodesDir", string(fullfile(demoRoot, "episodes")), ...
    "controllerOptions", struct(), ...
    "episodeTable", episodeTable, ...
    "datasetSummary", summarizeLoadedDemoTable(episodeTable));
demoResults.datasetSummary.acceptedBySanityGate = ...
    demoResults.datasetSummary.trackingMseSanityMean <= 0.10 && ...
    demoResults.datasetSummary.saturationFractionSanityMean <= 0.10 && ...
    demoResults.datasetSummary.deltaActionL2SanityMean <= 0.10;
end

function summary = summarizeLoadedDemoTable(episodeTable)
sanityRows = min(20, height(episodeTable));
summary = struct( ...
    "numEpisodes", height(episodeTable), ...
    "trackingMseMean", mean(episodeTable.trackingMseMean, "omitnan"), ...
    "trackingMaeMean", mean(episodeTable.trackingMaeMean, "omitnan"), ...
    "actionL2Mean", mean(episodeTable.actionL2Mean, "omitnan"), ...
    "saturationFractionMean", mean(episodeTable.saturationFractionMean, "omitnan"), ...
    "deltaActionL2Mean", mean(episodeTable.deltaActionL2Mean, "omitnan"), ...
    "absPwmMean", mean(episodeTable.absPwmMean, "omitnan"), ...
    "trackingMseSanityMean", mean(episodeTable.trackingMseMean(1:sanityRows), "omitnan"), ...
    "saturationFractionSanityMean", mean(episodeTable.saturationFractionMean(1:sanityRows), "omitnan"), ...
    "deltaActionL2SanityMean", mean(episodeTable.deltaActionL2Mean(1:sanityRows), "omitnan"));
end

function normalizeOfflineCheckpointNames(runDir)
fileInfo = dir(fullfile(runDir, "*.mat"));
for i = 1:numel(fileInfo)
    fileName = string(fileInfo(i).name);
    if startsWith(fileName, ["Agent", "00_", "training_info", "offline_bc_result"])
        continue;
    end
    token = regexp(fileName, '(\d+)', 'tokens', 'once');
    if isempty(token)
        continue;
    end
    targetName = "Agent" + token{1} + ".mat";
    targetPath = fullfile(fileInfo(i).folder, targetName);
    if ~isfile(targetPath)
        movefile(fullfile(fileInfo(i).folder, fileInfo(i).name), targetPath);
    end
end
end

function resultsRoot = resolveResultsRoot(requestedRoot, repoRoot, folderName)
requestedRoot = string(requestedRoot);
if strlength(requestedRoot) > 0
    resultsRoot = char(requestedRoot);
else
    resultsRoot = fullfile(repoRoot, "Agentes", folderName, ...
        string(datetime("now", "Format", "yy-MM-dd HH mm ss")));
end
end

function encoded = encodeNumeric(value)
encoded = strrep(sprintf("%.4f", value), ".", "p");
encoded = regexprep(encoded, "p?0+$", "");
encoded = regexprep(encoded, "p$", "");
end

function textValue = buildOfflineSummaryText(consolidatedTable, demoSummary, benchmark)
lines = strings(0, 1);
lines(end+1) = "markov52 offline BC warm-start";
lines(end+1) = "=============================";
lines(end+1) = "";
lines(end+1) = sprintf("Demo trackingMSE mean: %.6f", demoSummary.trackingMseMean);
lines(end+1) = sprintf("Demo saturationFraction mean: %.6f", demoSummary.saturationFractionMean);
lines(end+1) = sprintf("Benchmark trackingMSE: %.6f", benchmark.trackingMse);
lines(end+1) = sprintf("Benchmark saturationFraction: %.6f", benchmark.saturationFraction);
lines(end+1) = "";
lines(end+1) = strtrim(string(evalc("disp(consolidatedTable)")));
textValue = strjoin(lines, newline);
end

function writeTextFile(filePath, textValue)
fid = fopen(filePath, "w");
if fid < 0
    error("Could not open %s for writing.", filePath);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, "%s", textValue);
end
