function results = run_agent7250_low_exploration_finetune(options)
%run_agent7250_low_exploration_finetune continues Agent7250 with lower exploration.

arguments
    options = struct()
end

options = normalizeFineTuneOptions(options);

paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = char(paths.matlabRoot);
repoRoot = char(paths.workspaceRoot);
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));

clearConfigurablesOverride();
cleanup = onCleanup(@() clearConfigurablesOverride()); %#ok<NASGU>

baseConfigs = configurables();
benchmark = getAgent7250Benchmark();
resetBufferSupported = checkpointSupportsResetBuffer(options.checkpointPath);
protocolInfo = buildProtocolInfo(baseConfigs, options);
resultsRoot = resolveResultsRoot(options.resultsRoot, repoRoot);
mkdir(resultsRoot);
mkdir(fullfile(resultsRoot, "training_runs"));

gridTable = buildExplorationGrid(options);
rows = cell(height(gridTable), 1);

for i = 1:height(gridTable)
    explorationStd = gridTable.explorationStd(i);
    explorationStdMin = gridTable.explorationStdMin(i);
    explorationStdDecayRate = gridTable.explorationStdDecayRate(i);
    resetBuffer = logical(gridTable.resetBuffer(i));
    comboLabel = buildComboLabel(explorationStd, explorationStdMin, explorationStdDecayRate, resetBuffer);
    comboBaseDir = fullfile(resultsRoot, "training_runs", comboLabel);
    mkdir(comboBaseDir);

    try
        override = buildFineTuneOverride( ...
            baseConfigs, options, comboBaseDir, ...
            explorationStd, explorationStdMin, explorationStdDecayRate, resetBuffer);
        setConfigurablesOverride(override);

        trainInterface("td3", "lowExplore", comboLabel);
        clearConfigurablesOverride();

        runDir = findNewestSubdir(comboBaseDir);
        trainingResult = analyzeExperimentRun(runDir);
        auditOptions = struct( ...
            "experimentDir", runDir, ...
            "samplingPolicy", struct( ...
                "mode", "tail_every_k_last_n", ...
                "k", options.auditEveryK, ...
                "n", options.auditTailCount), ...
            "resultsRoot", fullfile(comboBaseDir, "audit"), ...
            "verbose", false);
        auditResults = runCheckpointAudit( ...
            options.auditFastSimulations, ...
            options.auditFullSimulations, ...
            options.auditTopK, ...
            auditOptions);

        bestRow = table2struct(auditResults.phaseBTable(1, :));
        rows{i} = struct( ...
            "comboLabel", string(comboLabel), ...
            "explorationStd", explorationStd, ...
            "explorationStdMin", explorationStdMin, ...
            "explorationStdDecayRate", explorationStdDecayRate, ...
            "resetExperienceBufferBeforeTraining", resetBuffer, ...
            "resetBufferSupported", resetBufferSupported, ...
            "thresholdAwareProtocol", logical(protocolInfo.thresholdAware), ...
            "activationThreshold", double(protocolInfo.activationThreshold), ...
            "firstEffectiveActionLevel", double(protocolInfo.firstEffectiveActionLevel), ...
            "experimentDir", string(runDir), ...
            "bestCheckpointPath", string(bestRow.checkpointPath), ...
            "bestCheckpointEpisode", double(bestRow.checkpointEpisode), ...
            "trackingMseMean", double(bestRow.trackingMseMean), ...
            "trackingMaeMean", double(bestRow.trackingMaeMean), ...
            "actionL2Mean", double(bestRow.actionL2Mean), ...
            "saturationFractionMean", double(bestRow.saturationFractionMean), ...
            "deltaActionL2Mean", double(bestRow.deltaActionL2Mean), ...
            "benchmarkStatus", string(bestRow.benchmarkStatus), ...
            "meetsConditionA", logical(bestRow.meetsConditionA), ...
            "meetsConditionB", logical(bestRow.meetsConditionB), ...
            "trackingMsePctVsBenchmark", double(bestRow.trackingMsePctVsBenchmark), ...
            "saturationFractionPctVsBenchmark", double(bestRow.saturationFractionPctVsBenchmark), ...
            "actionL2PctVsBenchmark", double(bestRow.actionL2PctVsBenchmark), ...
            "deltaActionL2PctVsBenchmark", double(bestRow.deltaActionL2PctVsBenchmark), ...
            "bestAverageRewardEpisode", getStructField(trainingResult.trainingSummary, "bestAverageRewardEpisode", NaN), ...
            "trainingAverageRewardFinal", getStructField(trainingResult.trainingSummary, "averageRewardFinal", NaN), ...
            "status", "ok", ...
            "errorMessage", "");

        save(fullfile(comboBaseDir, "combination_result.mat"), ...
            "trainingResult", "auditResults", "bestRow", "benchmark", ...
            "explorationStd", "explorationStdMin", "explorationStdDecayRate", ...
            "resetBuffer", "comboLabel", "options", "protocolInfo");
    catch ME
        clearConfigurablesOverride();
        rows{i} = struct( ...
            "comboLabel", string(comboLabel), ...
            "explorationStd", explorationStd, ...
            "explorationStdMin", explorationStdMin, ...
            "explorationStdDecayRate", explorationStdDecayRate, ...
            "resetExperienceBufferBeforeTraining", resetBuffer, ...
            "resetBufferSupported", resetBufferSupported, ...
            "thresholdAwareProtocol", logical(protocolInfo.thresholdAware), ...
            "activationThreshold", double(protocolInfo.activationThreshold), ...
            "firstEffectiveActionLevel", double(protocolInfo.firstEffectiveActionLevel), ...
            "experimentDir", string(comboBaseDir), ...
            "bestCheckpointPath", "", ...
            "bestCheckpointEpisode", NaN, ...
            "trackingMseMean", NaN, ...
            "trackingMaeMean", NaN, ...
            "actionL2Mean", NaN, ...
            "saturationFractionMean", NaN, ...
            "deltaActionL2Mean", NaN, ...
            "benchmarkStatus", "Error", ...
            "meetsConditionA", false, ...
            "meetsConditionB", false, ...
            "trackingMsePctVsBenchmark", NaN, ...
            "saturationFractionPctVsBenchmark", NaN, ...
            "actionL2PctVsBenchmark", NaN, ...
            "deltaActionL2PctVsBenchmark", NaN, ...
            "bestAverageRewardEpisode", NaN, ...
            "trainingAverageRewardFinal", NaN, ...
            "status", "error", ...
            "errorMessage", string(ME.message));
    end
end

consolidatedTable = struct2table(vertcat(rows{:}));
consolidatedTable.statusRank = double(consolidatedTable.status ~= "ok");
consolidatedTable = sortrows( ...
    consolidatedTable, ...
    {'statusRank', 'trackingMseMean', 'saturationFractionMean', 'deltaActionL2Mean', 'actionL2Mean'}, ...
    {'ascend', 'ascend', 'ascend', 'ascend', 'ascend'});

results = struct( ...
    "resultsRoot", string(resultsRoot), ...
    "benchmark", benchmark, ...
    "resetBufferSupported", resetBufferSupported, ...
    "protocolInfo", protocolInfo, ...
    "options", options, ...
    "consolidatedTable", consolidatedTable);

writetable(consolidatedTable, fullfile(resultsRoot, "agent7250_low_exploration_summary.csv"));
save(fullfile(resultsRoot, "agent7250_low_exploration_results.mat"), ...
    "results", "consolidatedTable", "benchmark", "options", "protocolInfo");
writeTextFile(fullfile(resultsRoot, "agent7250_low_exploration_summary.txt"), ...
    buildSummaryText(consolidatedTable, benchmark, options, resetBufferSupported, protocolInfo));
end

function options = normalizeFineTuneOptions(options)
defaults = struct( ...
    "checkpointPath", getAgent7250CheckpointPath(), ...
    "explorationStdValues", 0.05, ...
    "explorationStdMinValues", 0.01, ...
    "explorationStdDecayRateValues", 1e-4, ...
    "resetBufferValues", false, ...
    "trainingEpisodes", 1500, ...
    "trainingSaveEvery", 50, ...
    "trainingPlots", "training-progress", ...
    "auditFastSimulations", 20, ...
    "auditFullSimulations", 50, ...
    "auditTopK", 2, ...
    "auditEveryK", 50, ...
    "auditTailCount", 12, ...
    "resultsRoot", "", ...
    "enableDetailedActionDiagnostics", false, ...
    "savePerMotorMetrics", true, ...
    "thresholdAware", false);

fields = fieldnames(defaults);
for i = 1:numel(fields)
    if ~isfield(options, fields{i}) || isempty(options.(fields{i}))
        options.(fields{i}) = defaults.(fields{i});
    end
end

if isfield(options, "explorationStdDecayRate") && ...
        (~isfield(options, "explorationStdDecayRateValues") || isempty(options.explorationStdDecayRateValues))
    options.explorationStdDecayRateValues = options.explorationStdDecayRate;
end

options.checkpointPath = string(options.checkpointPath);
options.explorationStdValues = double(options.explorationStdValues);
options.explorationStdMinValues = double(options.explorationStdMinValues);
options.explorationStdDecayRateValues = double(options.explorationStdDecayRateValues);
options.resetBufferValues = logical(options.resetBufferValues);

if numel(options.explorationStdValues) == 1 && ...
        numel(options.explorationStdMinValues) == 1 && ...
        numel(options.explorationStdDecayRateValues) == 1 && ...
        numel(options.resetBufferValues) == 1
    options.trainingPlots = string(options.trainingPlots);
else
    options.trainingPlots = "none";
end
end

function gridTable = buildExplorationGrid(options)
[stdGrid, stdMinGrid, decayGrid, resetGrid] = ndgrid( ...
    options.explorationStdValues, ...
    options.explorationStdMinValues, ...
    options.explorationStdDecayRateValues, ...
    double(options.resetBufferValues));
gridTable = table( ...
    stdGrid(:), stdMinGrid(:), decayGrid(:), logical(resetGrid(:)), ...
    'VariableNames', {'explorationStd', 'explorationStdMin', 'explorationStdDecayRate', 'resetBuffer'});
end

function override = buildFineTuneOverride(baseConfigs, options, comboBaseDir, explorationStd, explorationStdMin, explorationStdDecayRate, resetBuffer)
override = buildMarkov52BaselineOverride(baseConfigs, struct( ...
    "run_training", true, ...
    "newTraining", false, ...
    "agentFile", string(options.checkpointPath), ...
    "agent_id", "td3", ...
    "trainingMaxEpisodes", options.trainingEpisodes, ...
    "trainingSaveAgentEvery", options.trainingSaveEvery, ...
    "trainingPlots", string(options.trainingPlots), ...
    "plotEpisodeOnTest", false, ...
    "enableDetailedActionDiagnostics", options.enableDetailedActionDiagnostics, ...
    "savePerMotorMetrics", options.savePerMotorMetrics));

override.td3.explorationStd = explorationStd;
override.td3.explorationStdMin = explorationStdMin;
override.td3.explorationStdDecayRate = explorationStdDecayRate;
override.td3.resetExperienceBufferBeforeTraining = logical(resetBuffer);
override.agents_directory = @(agent_id, variant) fullfile( ...
    comboBaseDir, string(datetime("now", "Format", "yy-MM-dd HH m s")));
end

function label = buildComboLabel(explorationStd, explorationStdMin, explorationStdDecayRate, resetBuffer)
label = sprintf( ...
    "explore_%s__min_%s__decay_%s__reset_%s", ...
    encodeNumeric(explorationStd), ...
    encodeNumeric(explorationStdMin), ...
    encodeNumeric(explorationStdDecayRate), ...
    string(logical(resetBuffer)));
end

function encoded = encodeNumeric(value)
encoded = lower(string(sprintf("%.6g", value)));
encoded = replace(encoded, ".", "p");
encoded = replace(encoded, "-", "m");
encoded = replace(encoded, "+", "");
end

function resultsRoot = resolveResultsRoot(requestedRoot, repoRoot)
requestedRoot = string(requestedRoot);
if strlength(requestedRoot) > 0
    resultsRoot = char(requestedRoot);
else
    resultsRoot = fullfile( ...
        repoRoot, "Agentes", "agent7250_low_exploration_finetune", ...
        string(datetime("now", "Format", "yy-MM-dd HH mm ss")));
end
end

function newestDir = findNewestSubdir(parentDir)
dirInfo = dir(parentDir);
dirInfo = dirInfo([dirInfo.isdir]);
dirInfo = dirInfo(~ismember({dirInfo.name}, {'.', '..'}));
if isempty(dirInfo)
    error("No training subdirectory found in %s", parentDir);
end
[~, idx] = max([dirInfo.datenum]);
newestDir = string(fullfile(dirInfo(idx).folder, dirInfo(idx).name));
end

function value = getStructField(s, fieldName, defaultValue)
if isstruct(s) && isfield(s, fieldName)
    value = s.(fieldName);
else
    value = defaultValue;
end
end

function textValue = buildSummaryText(consolidatedTable, benchmark, options, resetBufferSupported, protocolInfo)
titleText = "Agent7250 low-exploration fine-tune";
lines = strings(0, 1);
lines(end+1) = titleText;
lines(end+1) = join(repmat("=", 1, strlength(titleText)), "");
lines(end+1) = "";
lines(end+1) = sprintf("Checkpoint base: %s", string(options.checkpointPath));
lines(end+1) = sprintf("ResetExperienceBufferBeforeTraining supported: %d", resetBufferSupported);
if protocolInfo.thresholdAware
    lines(end+1) = "Protocol: threshold-aware exploration";
    lines(end+1) = sprintf("Activation threshold = %.6f", protocolInfo.activationThreshold);
    lines(end+1) = sprintf("First effective action level = %.6f", protocolInfo.firstEffectiveActionLevel);
else
    lines(end+1) = "Protocol: generic low-exploration fine-tune";
end
lines(end+1) = sprintf("Benchmark: %s", string(benchmark.label));
lines(end+1) = sprintf( ...
    "Benchmark trackingMSE = %.6f | saturationFraction = %.6f | actionL2 = %.6f", ...
    benchmark.trackingMse, benchmark.saturationFraction, benchmark.actionL2);
lines(end+1) = "";
lines(end+1) = strtrim(string(evalc("disp(consolidatedTable)")));
textValue = strjoin(lines, newline);
end

function writeTextFile(filePath, textValue)
fid = fopen(filePath, "w");
if fid < 0
    error("Could not open %s for writing.", filePath);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, "%s", textValue);
end

function tf = checkpointSupportsResetBuffer(checkpointPath)
tf = false;
vars = who('-file', checkpointPath);
if any(strcmp(vars, "agent"))
    aux = load(checkpointPath, "agent");
    agent = aux.agent;
elseif any(strcmp(vars, "saved_agent"))
    aux = load(checkpointPath, "saved_agent");
    agent = aux.saved_agent;
else
    return;
end
if isprop(agent, "AgentOptions") && ~isempty(agent.AgentOptions)
    tf = isprop(agent.AgentOptions, "ResetExperienceBufferBeforeTraining");
end
end

function protocolInfo = buildProtocolInfo(baseConfigs, options)
levels = sort(unique(abs(double(baseConfigs.actionCommandLevels(:)))));
levels = levels(levels > 0);
if isempty(levels)
    firstEffectiveActionLevel = NaN;
else
    firstEffectiveActionLevel = levels(1) / max(abs(double(baseConfigs.speeds(:))));
end

protocolInfo = struct( ...
    "thresholdAware", logical(options.thresholdAware), ...
    "activationThreshold", double(baseConfigs.actionCommandActivationThreshold), ...
    "firstEffectiveActionLevel", double(firstEffectiveActionLevel));
end
