function [reward, rewardVector] = normalizeRewardOutputs( ...
        reward, rewardVector, expectedActionSize)
%normalizeRewardOutputs validates the scalar and per-motor reward outputs.

if ~isnumeric(expectedActionSize) || ~isreal(expectedActionSize) || ...
        ~isscalar(expectedActionSize) || ~isfinite(expectedActionSize) || ...
        expectedActionSize < 1 || fix(expectedActionSize) ~= expectedActionSize
    error("normalizeRewardOutputs:InvalidExpectedActionSize", ...
        "expectedActionSize must be a positive integer scalar.");
end

if ~isnumeric(reward) || ~isreal(reward) || ~isscalar(reward) || ...
        ~isfinite(reward)
    error("normalizeRewardOutputs:InvalidReward", ...
        "reward must be a finite real numeric scalar.");
end

if ~isnumeric(rewardVector) || ~isreal(rewardVector) || ...
        numel(rewardVector) ~= expectedActionSize || ...
        any(~isfinite(rewardVector), "all")
    error("normalizeRewardOutputs:InvalidRewardVector", ...
        "rewardVector must be a finite real numeric %d-vector.", ...
        expectedActionSize);
end

reward = double(reward);
rewardVector = double(rewardVector(:)');
end
