function rewardInfo = normalizeRewardInfo(rewardInfo, context)
%normalizeRewardInfo completes and validates the per-step reward contract.
%
% The function is deliberately pure: context contains only the effective
% action, previous action, tracking error and reference source. It never
% reads Env, glove data or EMG data.

if isempty(rewardInfo)
    rewardInfo = struct();
end
if ~isstruct(rewardInfo) || ~isscalar(rewardInfo)
    error("normalizeRewardInfo:InvalidRewardInfo", ...
        "rewardInfo must be a scalar struct.");
end
if ~isstruct(context) || ~isscalar(context)
    error("normalizeRewardInfo:InvalidContext", ...
        "context must be a scalar struct.");
end

requiredContextFields = { ...
    'effectiveAction', ...
    'previousEffectiveAction', ...
    'trackingError', ...
    'referenceSource'};
if ~all(isfield(context, requiredContextFields))
    error("normalizeRewardInfo:IncompleteContext", ...
        "Reward context is missing required fields.");
end

action = validateFourVector(context.effectiveAction, "effectiveAction");
previousAction = validateFourVector( ...
    context.previousEffectiveAction, "previousEffectiveAction");
trackingError = validateFourVector(context.trackingError, "trackingError");
referenceSource = string(context.referenceSource);
if ~isscalar(referenceSource) || ...
        ~any(referenceSource == ["glove", "emgIntent"])
    error("normalizeRewardInfo:InvalidReferenceSource", ...
        "referenceSource must be either 'glove' or 'emgIntent'.");
end

defaults = struct( ...
    "trackingMse", mean(trackingError.^2), ...
    "trackingMae", mean(abs(trackingError)), ...
    "actionL2", mean(action.^2), ...
    "progressTerm", 0, ...
    "smoothnessPenalty", 0, ...
    "deltaActionL2", mean((action - previousAction).^2), ...
    "saturationFraction", mean(abs(action) >= 0.95), ...
    "saturationPenalty", 0, ...
    "referenceSource", referenceSource, ...
    "schemaVersion", 1);

defaultFields = fieldnames(defaults);
for i = 1:numel(defaultFields)
    fieldName = defaultFields{i};
    if ~isfield(rewardInfo, fieldName) || isempty(rewardInfo.(fieldName))
        rewardInfo.(fieldName) = defaults.(fieldName);
    end
end

infoReferenceSource = string(rewardInfo.referenceSource);
if ~isscalar(infoReferenceSource) || ...
        ~any(infoReferenceSource == ["glove", "emgIntent"])
    error("normalizeRewardInfo:InvalidReferenceSource", ...
        "rewardInfo.referenceSource must be 'glove' or 'emgIntent'.");
end
if infoReferenceSource ~= referenceSource
    error("normalizeRewardInfo:ReferenceSourceMismatch", ...
        "rewardInfo.referenceSource does not match the active source.");
end
rewardInfo.referenceSource = referenceSource;

numericFields = { ...
    'trackingMse', ...
    'trackingMae', ...
    'actionL2', ...
    'progressTerm', ...
    'smoothnessPenalty', ...
    'deltaActionL2', ...
    'saturationFraction', ...
    'saturationPenalty'};
for i = 1:numel(numericFields)
    fieldName = numericFields{i};
    value = rewardInfo.(fieldName);
    if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) || ~isfinite(value)
        error("normalizeRewardInfo:InvalidMetric", ...
            "rewardInfo.%s must be a finite real numeric scalar.", fieldName);
    end
end

if rewardInfo.saturationFraction < 0 || rewardInfo.saturationFraction > 1
    error("normalizeRewardInfo:InvalidMetric", ...
        "rewardInfo.saturationFraction must be within [0, 1].");
end

if ~isnumeric(rewardInfo.schemaVersion) || ...
        ~isscalar(rewardInfo.schemaVersion) || rewardInfo.schemaVersion ~= 1
    error("normalizeRewardInfo:InvalidSchemaVersion", ...
        "rewardInfo.schemaVersion must equal 1.");
end
end

function value = validateFourVector(value, fieldName)
if ~isnumeric(value) || ~isreal(value) || numel(value) ~= 4 || ...
        any(~isfinite(value), "all")
    error("normalizeRewardInfo:InvalidContextVector", ...
        "%s must be a finite real numeric four-vector.", fieldName);
end
value = double(value(:)');
end
