function [reward, rewardVector, rewardInfo] = ...
    trackingIntentActionRateReward(~, action, rewardContext)
%trackingIntentActionRateReward causal reward for the no-glove intent line.
%
% The current effective action is evaluated against q_ref and v_ref that
% were already visible in state_t. The function is pure with respect to Env:
% all temporal inputs, including u_eff,t-1, are supplied in rewardContext.

requiredFields = [ ...
    "trackingTarget", ...
    "trackingPrediction", ...
    "trackingVelocityTarget", ...
    "trackingVelocityPrediction", ...
    "previousEffectiveAction", ...
    "referenceSource"];
if ~isstruct(rewardContext) || ~isscalar(rewardContext) || ...
        ~all(isfield(rewardContext, requiredFields))
    error("trackingIntentActionRateReward:InvalidContext", ...
        "The causal intent reward context is incomplete.");
end
referenceSource = string(rewardContext.referenceSource);
if ~isscalar(referenceSource) || ismissing(referenceSource) || ...
        referenceSource ~= "emgIntent"
    error("trackingIntentActionRateReward:InvalidReferenceSource", ...
        "trackingIntentActionRateReward is restricted to emgIntent.");
end

action = validateFourVector(action, "action");
previousAction = validateFourVector( ...
    rewardContext.previousEffectiveAction, "previousEffectiveAction");
positionTarget = validateFourVector( ...
    rewardContext.trackingTarget, "trackingTarget");
positionPrediction = validateFourVector( ...
    rewardContext.trackingPrediction, "trackingPrediction");
velocityTarget = validateFourVector( ...
    rewardContext.trackingVelocityTarget, "trackingVelocityTarget");
velocityPrediction = validateFourVector( ...
    rewardContext.trackingVelocityPrediction, ...
    "trackingVelocityPrediction");

wQ = configurables("intentRewardPositionWeight");
wV = configurables("intentRewardVelocityWeight");
wU = configurables("intentRewardActionWeight");
wDu = configurables("intentRewardDeltaActionWeight");
wSat = configurables("intentRewardSaturationWeight");
uSoft = configurables("intentRewardSoftActionLimit");

positionError = positionPrediction - positionTarget;
velocityError = velocityPrediction - velocityTarget;
deltaAction = action - previousAction;
softSaturationVector = max(0, abs(action) - uSoft).^2;

rewardVector = -( ...
    wQ .* positionError.^2 + ...
    wV .* velocityError.^2 + ...
    wU .* action.^2 + ...
    wDu .* deltaAction.^2 + ...
    wSat .* softSaturationVector);
reward = mean(rewardVector);

rewardInfo = struct( ...
    "trackingMse", mean(positionError.^2), ...
    "trackingMae", mean(abs(positionError)), ...
    "velocityMse", mean(velocityError.^2), ...
    "actionL2", mean(action.^2), ...
    "progressTerm", 0, ...
    "smoothnessPenalty", wDu .* mean(deltaAction.^2), ...
    "deltaActionL2", mean(deltaAction.^2), ...
    "saturationFraction", mean(abs(action) >= 0.95), ...
    "softSaturationPenalty", mean(softSaturationVector), ...
    "saturationPenalty", wSat .* mean(softSaturationVector), ...
    "referenceSource", "emgIntent");
end

function value = validateFourVector(value, fieldName)
if ~isnumeric(value) || ~isreal(value) || numel(value) ~= 4 || ...
        any(~isfinite(value), "all")
    error("trackingIntentActionRateReward:InvalidVector", ...
        "%s must be a finite real numeric four-vector.", fieldName);
end
value = double(value(:)');
end
