function tests = testTrackingIntentActionRateReward
%testTrackingIntentActionRateReward deterministic ETAPA 4 reward tests.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
testDir = fileparts(mfilename("fullpath"));
matlabRoot = fileparts(fileparts(testDir));
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
[dataset, calibration, expected] = buildFixture(11);
testCase.TestData.dataset = dataset;
testCase.TestData.calibration = calibration;
testCase.TestData.expected = expected;
end

function teardown(~)
clearConfigurablesOverride();
close all force;
end

function testPerfectTrackingAndRest(testCase)
applyStage4Profile(testCase);
context = makeContext();
[reward, rewardVector, info] = ...
    trackingIntentActionRateReward([], zeros(4, 1), context);

testCase.verifyEqual(reward, 0, "AbsTol", 1e-15);
testCase.verifyEqual(rewardVector, zeros(1, 4), "AbsTol", 1e-15);
testCase.verifyEqual(info.trackingMse, 0);
testCase.verifyEqual(info.trackingMae, 0);
testCase.verifyEqual(info.velocityMse, 0);
testCase.verifyEqual(info.actionL2, 0);
testCase.verifyEqual(info.deltaActionL2, 0);
testCase.verifyEqual(info.saturationFraction, 0);
testCase.verifyEqual(info.softSaturationPenalty, 0);
end

function testPositionErrorAndEveryMotor(testCase)
applyStage4Profile(testCase);
for motorIdx = 1:4
    context = makeContext();
    context.trackingPrediction(motorIdx) = 0.4;
    [reward, rewardVector, info] = ...
        trackingIntentActionRateReward([], zeros(1, 4), context);
    expectedVector = zeros(1, 4);
    expectedVector(motorIdx) = -0.4^2;
    testCase.verifyEqual(rewardVector, expectedVector, "AbsTol", 1e-15);
    testCase.verifyEqual(reward, mean(expectedVector), "AbsTol", 1e-15);
    testCase.verifyEqual(info.trackingMse, 0.4^2 / 4, ...
        "AbsTol", 1e-15);
    testCase.verifyEqual(info.trackingMae, 0.4 / 4, ...
        "AbsTol", 1e-15);
end
end

function testAbruptActionAndSaturation(testCase)
applyStage4Profile(testCase);
context = makeContext();
action = [1, -1, 0.96, 0.94];
[reward, rewardVector, info] = ...
    trackingIntentActionRateReward([], action, context);
configs = configurables();
softVector = max(0, abs(action) - ...
    configs.intentRewardSoftActionLimit).^2;
expectedVector = -( ...
    configs.intentRewardActionWeight .* action.^2 + ...
    configs.intentRewardDeltaActionWeight .* action.^2 + ...
    configs.intentRewardSaturationWeight .* softVector);

testCase.verifyEqual(rewardVector, expectedVector, "AbsTol", 1e-15);
testCase.verifyEqual(reward, mean(expectedVector), "AbsTol", 1e-15);
testCase.verifyEqual(info.deltaActionL2, mean(action.^2), ...
    "AbsTol", 1e-15);
testCase.verifyEqual(info.saturationFraction, 3/4, "AbsTol", 1e-15);
testCase.verifyEqual(info.softSaturationPenalty, mean(softVector), ...
    "AbsTol", 1e-15);
testCase.verifyEqual(info.saturationPenalty, ...
    configs.intentRewardSaturationWeight * mean(softVector), ...
    "AbsTol", 1e-15);
end

function testVelocityTermAndSelector(testCase)
profile = stage4Profile(testCase);
profile.intentRewardVelocityWeight = 0.25;
setConfigurablesOverride(profile);
context = makeContext();
context.trackingVelocityPrediction = [1, -2, 0.5, -0.25];
[rewardDirect, vectorDirect, infoDirect] = ...
    trackingIntentActionRateReward([], zeros(4, 1), context);
[rewardSelected, vectorSelected, infoSelected] = ...
    rewardFunctionSelector([], "trackingIntentActionRateReward", ...
    zeros(4, 1), context);
expectedVelocityMse = mean(context.trackingVelocityPrediction.^2);

testCase.verifyEqual(rewardDirect, -0.25 * expectedVelocityMse, ...
    "AbsTol", 1e-15);
testCase.verifyEqual(vectorDirect, ...
    -0.25 .* context.trackingVelocityPrediction.^2, ...
    "AbsTol", 1e-15);
testCase.verifyEqual(infoDirect.velocityMse, expectedVelocityMse, ...
    "AbsTol", 1e-15);
testCase.verifyEqual(rewardSelected, rewardDirect, "AbsTol", 1e-15);
testCase.verifyEqual(vectorSelected, vectorDirect, "AbsTol", 1e-15);
testCase.verifyEqual(infoSelected, infoDirect);
end

function testContractDefaultsAndInvalidInputs(testCase)
applyStage4Profile(testCase);
context = makeContext();
action = [1, 0, -0.5, 0.25];
contract = struct( ...
    "effectiveAction", action, ...
    "previousEffectiveAction", zeros(1, 4), ...
    "trackingError", [0.1, -0.2, 0.3, -0.4], ...
    "velocityError", [1, -1, 2, -2], ...
    "softSaturationThreshold", 0.9, ...
    "referenceSource", "emgIntent");
info = normalizeRewardInfo(struct(), contract);
testCase.verifyEqual(info.velocityMse, 2.5, "AbsTol", 1e-15);
testCase.verifyEqual(info.softSaturationPenalty, 0.1^2 / 4, ...
    "AbsTol", 1e-15);

invalidContext = context;
invalidContext.trackingVelocityTarget = [0, 0, NaN, 0];
testCase.verifyError(@() trackingIntentActionRateReward( ...
    [], action, invalidContext), ...
    "trackingIntentActionRateReward:InvalidVector");
invalidSource = context;
invalidSource.referenceSource = "glove";
testCase.verifyError(@() trackingIntentActionRateReward( ...
    [], action, invalidSource), ...
    "trackingIntentActionRateReward:InvalidReferenceSource");
incomplete = rmfield(context, "trackingVelocityPrediction");
testCase.verifyError(@() trackingIntentActionRateReward( ...
    [], action, incomplete), ...
    "trackingIntentActionRateReward:InvalidContext");

badContract = contract;
badContract.softSaturationThreshold = 1.1;
testCase.verifyError(@() normalizeRewardInfo(struct(), badContract), ...
    "normalizeRewardInfo:InvalidSoftSaturationThreshold");
end

function testStage4ProfileIsIsolatedAndFailsClosed(testCase)
stage3 = buildNoGloveStage3Override(testCase.TestData.calibration, ...
    testCase.TestData.expected, 11);
stage4 = stage4Profile(testCase);
invariants = [ ...
    "referenceSource", "observationVariant", "simMotors", ...
    "usePrerecorded", "connect_glove", "actionInterfaceVariant", ...
    "period", "intentDecoderEnabled"];
for fieldIdx = 1:numel(invariants)
    fieldName = invariants(fieldIdx);
    testCase.verifyEqual(stage4.(fieldName), stage3.(fieldName));
end
testCase.verifyEqual(stage3.rewardType, ...
    "trackingMseActionRateReward");
testCase.verifyEqual(stage4.rewardType, ...
    "trackingIntentActionRateReward");
testCase.verifyEqual(stage4.intentRewardVelocityWeight, 0);
testCase.verifyEqual(stage4.intentRewardSoftActionLimit, 0.9);
setConfigurablesOverride(stage3);
effectiveStage3 = configurables();
setConfigurablesOverride(stage4);
effectiveStage4 = configurables();
testCase.verifyEqual(effectiveStage3.stateLength, 60);
testCase.verifyEqual(effectiveStage4.stateLength, 60);

stage4.observationVariant = "markov52";
stage4.intentDecoderEnabled = false;
stage4.stateLength = 52;
setConfigurablesOverride(stage4);
testCase.verifyError(@() configurables(), ...
    "configurables:IntentRewardRequiresIntentState");

stage4 = stage4Profile(testCase);
stage4.intentRewardActionWeight = -1;
setConfigurablesOverride(stage4);
testCase.verifyError(@() configurables(), ...
    "configurables:InvalidIntentRewardWeight");
end

function testCompleteSimulatedEpisodeAndPersistence(testCase)
tempDir = string(tempname);
mkdir(tempDir);
cleanup = onCleanup(@() removeTempDir(tempDir));
profile = stage4Profile(testCase);
profile.maxNumberStepsInEpisodes = 12;
setConfigurablesOverride(profile);
samplesPerStep = round(profile.period * ...
    testCase.TestData.dataset.sampleRateHz);
rawEmg = testCase.TestData.dataset.evaluationRawEmg( ...
    1:(profile.maxNumberStepsInEpisodes + 1) * samplesPerStep, :);
env = Env(tempDir, true, {rawEmg, rawEmg}, {});
reset(env);
isDone = false;
stepCount = 0;
actionPattern = [ ...
    0, 0, 0, 0; ...
    0.4, 0, 0, 0; ...
    -0.4, 0.4, 0, 0; ...
    1, -1, 0.96, 0.94];
while ~isDone
    stepCount = stepCount + 1;
    action = actionPattern(mod(stepCount - 1, ...
        size(actionPattern, 1)) + 1, :)';
    [~, reward, isDone] = step(env, action);
    info = env.rewardInfoLog{stepCount};
    configs = configurables();
    reconstructedReward = -( ...
        configs.intentRewardPositionWeight * info.trackingMse + ...
        configs.intentRewardVelocityWeight * info.velocityMse + ...
        configs.intentRewardActionWeight * info.actionL2 + ...
        configs.intentRewardDeltaActionWeight * info.deltaActionL2 + ...
        configs.intentRewardSaturationWeight * ...
            info.softSaturationPenalty);
    testCase.verifyEqual(reward, reconstructedReward, "AbsTol", 1e-12);
end
testCase.verifyEqual(stepCount, 12);
testCase.verifyTrue(all(isfinite([ ...
    env.rewardLog(1:stepCount); ...
    env.trackingMseLog(1:stepCount); ...
    env.trackingMaeLog(1:stepCount); ...
    env.velocityMseLog(1:stepCount); ...
    env.actionL2Log(1:stepCount); ...
    env.deltaActionL2Log(1:stepCount); ...
    env.saturationFractionLog(1:stepCount); ...
    env.softSaturationPenaltyLog(1:stepCount)])));
testCase.verifyEqual(env.referenceHistoryCount, stepCount);

env.saveEpisode();
episodePath = fullfile(tempDir, "episode00001.mat");
saved = load(episodePath, "velocityMseLog", ...
    "softSaturationPenaltyLog", "rewardInfoLog", "referenceSource");
testCase.verifySize(saved.velocityMseLog, [stepCount, 1]);
testCase.verifySize(saved.softSaturationPenaltyLog, [stepCount, 1]);
testCase.verifyEqual(saved.referenceSource, "emgIntent");
testCase.verifyTrue(all(cellfun(@(x) isfield(x, "velocityMse") && ...
    isfield(x, "softSaturationPenalty"), saved.rewardInfoLog)));

summary = summarizeEpisodeDirectory(tempDir);
testCase.verifyEqual(summary.velocityMseMean, ...
    mean(saved.velocityMseLog), "AbsTol", 1e-12);
testCase.verifyEqual(summary.softSaturationPenaltyMean, ...
    mean(saved.softSaturationPenaltyLog), "AbsTol", 1e-12);

legacyDir = fullfile(tempDir, "legacy_schema");
mkdir(legacyDir);
legacy = load(episodePath);
legacy = rmfield(legacy, { ...
    'velocityMseLog', 'softSaturationPenaltyLog'});
for idx = 1:numel(legacy.rewardInfoLog)
    legacy.rewardInfoLog{idx} = rmfield(legacy.rewardInfoLog{idx}, ...
        {'velocityMse', 'softSaturationPenalty'});
end
save(fullfile(legacyDir, "episode00001.mat"), "-struct", "legacy");
legacySummary = summarizeEpisodeDirectory(legacyDir);
testCase.verifyTrue(isnan(legacySummary.velocityMseMean));
testCase.verifyEqual(legacySummary.softSaturationPenaltyMean, 0);
end

function context = makeContext()
context = struct( ...
    "trackingTarget", zeros(1, 4), ...
    "trackingPrediction", zeros(1, 4), ...
    "trackingVelocityTarget", zeros(1, 4), ...
    "trackingVelocityPrediction", zeros(1, 4), ...
    "previousEffectiveAction", zeros(1, 4), ...
    "referenceSource", "emgIntent");
end

function applyStage4Profile(testCase)
setConfigurablesOverride(stage4Profile(testCase));
end

function profile = stage4Profile(testCase)
profile = buildNoGloveStage4Override(testCase.TestData.calibration, ...
    testCase.TestData.expected, 11);
end

function [dataset, calibration, expected] = buildFixture(seed)
config = buildNoGloveStage2OfflineConfig(seed);
dataset = buildSyntheticEmgIntentDataset(config);
calibration = calibrateEmgIntent(dataset.restCapture, ...
    dataset.instructionTrials, config.calibrationOptions);
options = config.calibrationOptions;
expected = struct( ...
    "userId", dataset.restCapture.userId, ...
    "sessionId", dataset.restCapture.sessionId, ...
    "channelOrder", dataset.restCapture.channelOrder, ...
    "sampleRateHz", dataset.restCapture.sampleRateHz, ...
    "windowLengthSamples", dataset.windowLengthSamples, ...
    "hopLengthSamples", dataset.hopLengthSamples, ...
    "dataProvenance", dataset.restCapture.dataProvenance, ...
    "motorOrder", options.motorOrder, ...
    "units", struct( ...
        "rawEmg", dataset.restCapture.rawEmgUnits, ...
        "envelope", options.envelopeUnits, ...
        "position", options.positionUnits, ...
        "velocity", options.velocityUnits, ...
        "acceleration", options.accelerationUnits), ...
    "synergyMatrixVersion", options.synergyMatrixVersion, ...
    "instructionProtocolVersion", options.instructionProtocolVersion, ...
    "sourceDomain", "rawEmgSameSession", ...
    "calibrationContentSha256", calibration.contentSha256);
end

function removeTempDir(tempDir)
if isfolder(tempDir)
    rmdir(tempDir, "s");
end
end
