function tests = testNoGloveStage6cMatchedController
% Deterministic tests for the simulation-only ETAPA 6C comparison.
tests = functiontests(localfunctions);
end

function testExactReferenceAndInitialPositionPairing(testCase)
[episodeDir, cleanup] = createFixture(); %#ok<ASGLU>
configs = fixtureConfig();
result = evaluateNoGloveStage6cMatchedController( ...
    episodeDir, configs, "acceptance");

testCase.verifyTrue(result.pairing.allExact);
testCase.verifyEqual(result.pairing.episodeCount, 1);
testCase.verifyEqual(result.pairing.referenceMaxAbs, 0);
testCase.verifyEqual(result.pairing.referenceVelocityMaxAbs, 0);
testCase.verifyEqual(result.pairing.initialPositionMaxAbs, 0);
testCase.verifyEqual(unique(result.componentTable.commandSource), ...
    ["Agent200"; "conventionalP"]);
testCase.verifyLessThanOrEqual(max(abs( ...
    result.componentTable.appliedPwm( ...
    result.componentTable.commandSource == "conventionalP"))), 64);
testCase.verifyFalse(result.agentLoaded);
testCase.verifyFalse(result.reinforcementLearningInvoked);
testCase.verifyTrue(result.simulatorInvokedForConventionalOnly);
testCase.verifyFalse(result.hardwareUsed);
testCase.verifyFalse(result.dtwCalculated);
end

function testReplayIsDeterministic(testCase)
[episodeDir, cleanup] = createFixture(); %#ok<ASGLU>
configs = fixtureConfig();
first = evaluateNoGloveStage6cMatchedController( ...
    episodeDir, configs, "acceptance");
second = evaluateNoGloveStage6cMatchedController( ...
    episodeDir, configs, "acceptance");
firstRows = first.componentTable( ...
    first.componentTable.commandSource == "conventionalP", :);
secondRows = second.componentTable( ...
    second.componentTable.commandSource == "conventionalP", :);
testCase.verifyEqual(firstRows.qAfter, secondRows.qAfter, ...
    "AbsTol", 0);
testCase.verifyEqual(firstRows.appliedPwm, secondRows.appliedPwm, ...
    "AbsTol", 0);
testCase.verifyEqual(firstRows.safetyInterventionCount, ...
    secondRows.safetyInterventionCount, "AbsTol", 0);
end

function testSafetyMismatchFailsClosed(testCase)
[episodeDir, cleanup] = createFixture(); %#ok<ASGLU>
configs = fixtureConfig();
configs.simulationPositionSafety.positionMax(2) = 0.9;
testCase.verifyError(@() evaluateNoGloveStage6cMatchedController( ...
    episodeDir, configs, "acceptance"), ...
    "evaluateNoGloveStage6cMatchedController:SafetyMismatch");
end

function testUnsafeHardwareProfileRejected(testCase)
[episodeDir, cleanup] = createFixture(); %#ok<ASGLU>
configs = fixtureConfig();
configs.simMotors = false;
testCase.verifyError(@() evaluateNoGloveStage6cMatchedController( ...
    episodeDir, configs, "acceptance"), ...
    "evaluateNoGloveStage6cMatchedController:UnsafeConfig");
end

function testMissingReferenceFailsClosed(testCase)
[episodeDir, cleanup] = createFixture(); %#ok<ASGLU>
episodePath = fullfile(episodeDir, "episode00001.mat");
data = load(episodePath);
data = rmfield(data, "referenceHistory");
save(episodePath, "-struct", "data");
testCase.verifyError(@() evaluateNoGloveStage6cMatchedController( ...
    episodeDir, fixtureConfig(), "acceptance"), ...
    "evaluateNoGloveStage6cMatchedController:MissingEpisodeField");
end

function [episodeDir, cleanup] = createFixture()
episodeDir = string(tempname);
mkdir(episodeDir);
cleanup = onCleanup(@() removeFixture(episodeDir));

layout = buildObservationLayout("intentMarkov60", 40, 3, 4);
stepCount = 6;
stateLog = zeros(stepCount, layout.totalLength);
qReference = zeros(stepCount, 4);
qReference(:, 1) = [0; 0.02; 0.04; 0.06; 0.08; 0.10];
vReference = zeros(stepCount, 4);
vReference(2:end, 1) = 0.1;
stateLog(:, layout.referencePosition) = qReference;
stateLog(:, layout.referenceVelocity) = vReference;

trackingPredictionHistory = zeros(stepCount, 4);
referenceHistory = qReference;
actionLog = zeros(stepCount, 4);
actionSatLog = zeros(stepCount, 4);
actionPwmLog = zeros(stepCount, 4);
positionSafetyInterventionLog = zeros(stepCount, 4);
fixtureConfigs = fixtureConfig();
simulationPositionSafety = fixtureConfigs.simulationPositionSafety;
referenceSource = "emgIntent";
observationVariant = "intentMarkov60";
stateLength = layout.totalLength;
repetitionId = 7;
save(fullfile(episodeDir, "episode00001.mat"), ...
    "stateLog", "trackingPredictionHistory", "referenceHistory", ...
    "actionLog", "actionSatLog", "actionPwmLog", ...
    "positionSafetyInterventionLog", "simulationPositionSafety", ...
    "referenceSource", "observationVariant", "stateLength", ...
    "repetitionId");
end

function configs = fixtureConfig()
configs = struct( ...
    "simMotors", true, ...
    "connect_glove", false, ...
    "usePrerecorded", true, ...
    "referenceSource", "emgIntent", ...
    "observationVariant", "intentMarkov60", ...
    "actionInterfaceVariant", "baselineQuantized", ...
    "quantizeCommandsForSimulation", true, ...
    "unifyActions", false, ...
    "period", 0.2, ...
    "speeds", [255, 255, 255, 255], ...
    "actionCommandActivationThreshold", 0.125, ...
    "actionCommandLevels", [0, 64, 96, 128, 160, 192, 224, 255], ...
    "conventionalController", struct( ...
        "schemaVersion", 1, "type", "P", ...
        "kp", 1.5 * ones(4, 1), "kd", zeros(4, 1), ...
        "maxAction", (64 / 255) * ones(4, 1), ...
        "positionTolerance", 0.01 * ones(4, 1), ...
        "velocityTolerance", 0.03 * ones(4, 1)), ...
    "simulationPositionSafety", struct( ...
        "enabled", true, "mode", "clipTrajectoryOutput", ...
        "positionMin", zeros(1, 4), ...
        "positionMax", ones(1, 4), ...
        "encoderScale", [26500, 11500, 8500, 9000]));
end

function removeFixture(pathValue)
if isfolder(pathValue)
    rmdir(pathValue, "s");
end
end
