function tests = testNoGloveStage7hHoldRewardAblation
%testNoGloveStage7hHoldRewardAblation deterministic ETAPA 7H gate tests.
tests = functiontests(localfunctions);
end

function setupOnce(~)
testDir = fileparts(mfilename("fullpath"));
matlabRoot = fileparts(fileparts(testDir));
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));
end

function teardown(~)
clearConfigurablesOverride();
end

function testSupportedClassification(testCase)
[control, candidate] = nominalPair();
analysis = analyzeNoGloveStage7hHoldRewardAblation( ...
    control, candidate);
testCase.verifyTrue(analysis.gatePassed);
testCase.verifyEqual(analysis.classification, ...
    "holdConditionedRegularizationSupported");
testCase.verifyTrue(all(analysis.gateChecks.passed));
testCase.verifyEqual(analysis.ablationFactor, ...
    "intentHoldActionWeight");
testCase.verifyFalse(analysis.pilotAuthorized);
testCase.verifyFalse(analysis.rootCauseIdentified);
end

function testExposureFailurePrecedesOtherScientificFailures(testCase)
[control, candidate] = nominalPair();
candidate.rest.holdActiveFraction = 0.5;
candidate.rest.windowAnyCommandFraction = 1;
candidate.acceptance.trackingMse = 1;
analysis = analyzeNoGloveStage7hHoldRewardAblation( ...
    control, candidate);
testCase.verifyFalse(analysis.gatePassed);
testCase.verifyEqual(analysis.classification, ...
    "holdExposureInsufficient");
end

function testTrackingAndRestClassifications(testCase)
[control, candidate] = nominalPair();
candidate.acceptance.trackingMse = 0.106;
analysis = analyzeNoGloveStage7hHoldRewardAblation( ...
    control, candidate);
testCase.verifyEqual(analysis.classification, "trackingRegression");

[control, candidate] = nominalPair();
candidate.rest.windowAnyCommandFraction = 0.02;
analysis = analyzeNoGloveStage7hHoldRewardAblation( ...
    control, candidate);
testCase.verifyEqual(analysis.classification, "restGateFailed");
end

function testFunctionalAndDynamicClassifications(testCase)
[control, candidate] = nominalPair();
candidate.acceptance.motor2FunctionalFlagCount = 1;
analysis = analyzeNoGloveStage7hHoldRewardAblation( ...
    control, candidate);
testCase.verifyEqual(analysis.classification, "functionalGateFailed");

[control, candidate] = nominalPair();
candidate.acceptance.actionL2 = control.acceptance.actionL2+0.01;
analysis = analyzeNoGloveStage7hHoldRewardAblation( ...
    control, candidate);
testCase.verifyEqual(analysis.classification, ...
    "dynamicRegularityGateFailed");
end

function testSafetyFailureAndInvalidVariant(testCase)
[control, candidate] = nominalPair();
candidate.rest.positionViolationEpisodeCount = 1;
analysis = analyzeNoGloveStage7hHoldRewardAblation( ...
    control, candidate);
testCase.verifyEqual(analysis.classification, ...
    "safetyOrValidityFailure");

[control, candidate] = nominalPair();
candidate.holdWeight = 0.19;
testCase.verifyError(@() ...
    analyzeNoGloveStage7hHoldRewardAblation(control, candidate), ...
    "analyzeNoGloveStage7hHoldRewardAblation:InvalidVariant");
end

function testHoldSummaryReplaysStateDecisionExactly(testCase)
tempDir = string(tempname);
mkdir(tempDir);
cleanup = onCleanup(@() removeTempDir(tempDir));
layout = buildObservationLayout("intentMarkov60", 40, 3, 4);
stateLog = zeros(3, 60);
stateLog(:, layout.encoder) = [zeros(1, 4); ...
    0.02.*ones(1, 4); zeros(1, 4)];
stateLog(:, layout.referencePosition) = zeros(3, 4);
stateLog(:, layout.referenceVelocity) = zeros(3, 4);
actionSatLog = [0.5, 0, 0, 0; 0.5, 0, 0, 0; 0, 0, 0, 0];
actionPwmLog = [128, 0, 0, 0; 128, 0, 0, 0; 0, 0, 0, 0];
positionMse = [0; 4e-4; 0];
active = [1; 0; 1];
rewardInfoLog = cell(3, 1);
for idx = 1:3
    holdAction = active(idx)*mean(actionSatLog(idx, :).^2);
    rewardInfoLog{idx} = struct( ...
        "holdActive", active(idx), ...
        "holdPositionMse", positionMse(idx), ...
        "holdVelocityMaxAbs", 0, ...
        "holdActionL2", holdAction, ...
        "holdActionPenalty", 0.2*holdAction);
end
referenceSource = "emgIntent";
observationVariant = "intentMarkov60";
save(fullfile(tempDir, "episode00001.mat"), "stateLog", ...
    "actionSatLog", "actionPwmLog", "rewardInfoLog", ...
    "referenceSource", "observationVariant");
settings = struct("actionWeight", 0.2, ...
    "velocityTolerance", 1e-12, ...
    "positionMseTolerance", 1e-4);
summary = summarizeNoGloveStage7hHoldReward(tempDir, settings, ...
    "requireSteadyRest", true);
testCase.verifyEqual(summary.holdActiveFraction, 2/3, ...
    "AbsTol", 1e-15);
testCase.verifyEqual(summary.holdActionPenaltyMean, ...
    mean([0.2*0.5^2/4, 0, 0]), "AbsTol", 1e-15);
testCase.verifyEqual(summary.maximumDiagnosticReplayError, 0);

rewardInfoLog{1}.holdActive = 0;
save(fullfile(tempDir, "episode00001.mat"), "stateLog", ...
    "actionSatLog", "actionPwmLog", "rewardInfoLog", ...
    "referenceSource", "observationVariant");
testCase.verifyError(@() summarizeNoGloveStage7hHoldReward( ...
    tempDir, settings), ...
    "summarizeNoGloveStage7hHoldReward:DiagnosticMismatch");
end

function testStage6OptionsFailClosedBeforeTraining(testCase)
testCase.verifyError(@() run_no_glove_stage6_training(struct( ...
    "intentHoldRewardEnabled", "yes")), ...
    "run_no_glove_stage6_training:InvalidHoldRewardOption");
testCase.verifyError(@() run_no_glove_stage6_training(struct( ...
    "intentHoldActionWeight", -1)), ...
    "run_no_glove_stage6_training:InvalidHoldRewardValue");
end

function [control, candidate] = nominalPair()
training = struct("allFinite", true, ...
    "positionViolationEpisodeCount", 0, ...
    "positionSafetyInterventionCount", 2);
acceptance = struct("allFinite", true, ...
    "positionViolationEpisodeCount", 0, ...
    "positionSafetyInterventionCount", 1, ...
    "trackingMse", 0.10, "trackingMae", 0.20, ...
    "actionL2", 0.20, "deltaActionL2", 0.20, ...
    "saturationFraction", 0.10, ...
    "motor2FunctionalFlagCount", 0, ...
    "otherMotorFunctionalFlagCount", 0);
rest = struct("allFinite", true, ...
    "positionViolationEpisodeCount", 0, ...
    "positionSafetyInterventionCount", 0, ...
    "commandActiveFraction", 0.005, ...
    "windowAnyCommandFraction", 0.005, "meanAbsPwm", 1, ...
    "saturationFraction", 0, ...
    "commandActiveFractionByMotor", 0.005.*ones(1, 4), ...
    "meanAbsPwmByMotor", ones(1, 4), ...
    "saturationFractionByMotor", zeros(1, 4), ...
    "holdActiveFraction", 0.95, "holdActionL2Mean", 0.01, ...
    "holdActionPenaltyMean", 0, ...
    "maximumDiagnosticReplayError", 0);
control = struct("label", "control", "holdWeight", 0, ...
    "actionWeight", 0.05, "training", training, ...
    "acceptance", acceptance, "rest", rest, ...
    "decodedRestFalseActivationFraction", 0, ...
    "checkpointSha256", "control-sha");
candidate = control;
candidate.label = "candidate";
candidate.holdWeight = 0.20;
candidate.checkpointSha256 = "candidate-sha";
candidate.training.positionSafetyInterventionCount = 1;
candidate.acceptance.trackingMse = 0.09;
candidate.acceptance.actionL2 = 0.18;
candidate.acceptance.deltaActionL2 = 0.18;
candidate.acceptance.saturationFraction = 0.08;
candidate.rest.holdActionPenaltyMean = 0.002;
end

function removeTempDir(path)
if isfolder(path) && startsWith(path, string(tempdir))
    rmdir(path, "s");
end
end
