function tests = testNoGloveStage7kIntentProvenance
%testNoGloveStage7kIntentProvenance deterministic ETAPA 7K tests.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
testDir = fileparts(mfilename("fullpath"));
matlabRoot = fileparts(fileparts(testDir));
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));
[dataset, calibration, expected] = buildFixture(11);
testCase.TestData.dataset = dataset;
testCase.TestData.calibration = calibration;
testCase.TestData.expected = expected;
end

function testReasonClassifierOrder(testCase)
decoder = decoderDetails(false, true, false);
reference = referenceDetails(false, false, false);
testCase.verifyEqual(classifyIntentZeroReferenceReason( ...
    [0.1, 0, 0, 0], zeros(1, 4), decoder, reference), ...
    "movingReference");
testCase.verifyEqual(classifyIntentZeroReferenceReason( ...
    zeros(1, 4), zeros(1, 4), decoder, reference), ...
    "decoderRest");

decoder = decoderDetails(true, false, true);
testCase.verifyEqual(classifyIntentZeroReferenceReason( ...
    zeros(1, 4), zeros(1, 4), decoder, reference), ...
    "activeCountdownZero");
decoder.lowActivityCountdown = false;
testCase.verifyEqual(classifyIntentZeroReferenceReason( ...
    zeros(1, 4), zeros(1, 4), decoder, reference), ...
    "activeSynergyZero");

desired = [0.1, 0, 0, 0];
reference.positionLimited(1) = true;
testCase.verifyEqual(classifyIntentZeroReferenceReason( ...
    zeros(1, 4), desired, decoder, reference), ...
    "mechanicalPositionLimitZero");
reference.positionLimited(:) = false;
reference.accelerationLimited(1) = true;
testCase.verifyEqual(classifyIntentZeroReferenceReason( ...
    zeros(1, 4), desired, decoder, reference), ...
    "mechanicalRateLimitZero");
reference.accelerationLimited(:) = false;
testCase.verifyEqual(classifyIntentZeroReferenceReason( ...
    zeros(1, 4), desired, decoder, reference), ...
    "unresolvedActiveZero");
end

function testClassifierRejectsIncompleteDiagnostics(testCase)
decoder = decoderDetails(false, true, false);
reference = rmfield(referenceDetails(false, false, false), ...
    "positionLimited");
testCase.verifyError(@() classifyIntentZeroReferenceReason( ...
    zeros(1, 4), zeros(1, 4), decoder, reference), ...
    "classifyIntentZeroReferenceReason:InvalidContract");
end

function testOfflineReplayAlignmentAndLabels(testCase)
root = string(tempname);
mkdir(root);
cleanup = onCleanup(@() removeTempDir(root));
[path, stepCount] = writeReplayFixture(root, ...
    testCase.TestData.dataset, testCase.TestData.calibration, ...
    testCase.TestData.expected);
episodeAudit = table("candidate", "training", 1, 1, path, ...
    'VariableNames', ["variant", "source", "episode", ...
    "repetitionId", "episodePath"]);
step = (1:stepCount)';
windows = table(repmat("candidate", stepCount, 1), ...
    repmat("training", stepCount, 1), ones(stepCount, 1), ...
    ones(stepCount, 1), step, step, zeros(stepCount, 1), ...
    true(stepCount, 1), ...
    'VariableNames', ["variant", "source", "episode", ...
    "repetitionId", "step", "windowIndex", ...
    "holdPositionMse", "stopped"]);
latch = table(windows.variant, windows.source, windows.episode, ...
    windows.repetitionId, step, step, true(stepCount, 1), ...
    false(stepCount, 1), ones(stepCount, 1), false(stepCount, 1), ...
    'VariableNames', ["variant", "source", "episode", ...
    "repetitionId", "step", "windowIndex", "latchActive", ...
    "recoveredByMemory", "stoppedSegmentId", ...
    "segmentFarStarted"]);
profile = struct("intentCalibration", testCase.TestData.calibration, ...
    "intentExpectedContext", testCase.TestData.expected);
profiles = struct("control", profile, "candidate", profile);
analysis = replayNoGloveStage7kIntentProvenance( ...
    episodeAudit, windows, latch, profiles, ...
    "expectedEpisodeCount", 1, "expectedWindowCount", stepCount);
testCase.verifyTrue(analysis.replayGatePassed);
testCase.verifyEqual(analysis.classification, ...
    "zeroReferenceFullyExplainedByRestGate");
testCase.verifyEqual(analysis.decisionAudit.provenance(1), ...
    "episodeInitialization");
testCase.verifyTrue(all(analysis.decisionAudit.provenance(2:end) == ...
    "decoderRest"));
testCase.verifyEqual( ...
    max(analysis.transitionAudit.shiftedPositionReplayError), 0);
testCase.verifyEqual( ...
    max(analysis.transitionAudit.shiftedVelocityReplayError), 0);
testCase.verifyFalse( ...
    analysis.episodeReplayAudit.directProvenanceLogPresent);
end

function testLauncherOptionsFailClosed(testCase)
testCase.verifyError(@() ...
    run_no_glove_stage7k_intent_provenance_audit(struct("unknown", 1)), ...
    "run_no_glove_stage7k_intent_provenance_audit:UnknownOption");
testCase.verifyError(@() ...
    run_no_glove_stage7k_intent_provenance_audit(struct( ...
        "stage7jRunRoot", fullfile(tempdir, "missing-stage7j"))), ...
    "run_no_glove_stage7k_intent_provenance_audit:MissingStage7j");
end

function [path, stepCount] = writeReplayFixture( ...
        root, dataset, calibration, expected)
stepCount = 3;
windowLength = calibration.windowLengthSamples;
raw = double(dataset.restCapture.rawEmg);
emgLog = cell(stepCount, 1);
for idx = 1:stepCount
    rows = (idx-1)*windowLength+(1:windowLength);
    emgLog{idx} = raw(rows, :);
end
layout = buildObservationLayout("intentMarkov60", 40, 3, 4);
stateLog = zeros(stepCount, 60);
qCurrent = (calibration.limits.positionMin+ ...
    calibration.limits.positionMax)./2;
vCurrent = zeros(1, 4);
stateLog(1, layout.referencePosition) = qCurrent;
stateLog(1, layout.referenceVelocity) = vCurrent;
gateState = struct("isActive", false, "onCount", 0, "offCount", 0);
for idx = 1:stepCount
    [desired, ~, gateState, details] = mapEmgToIntentVelocity( ...
        emgLog{idx}, calibration, expected, gateState);
    [qNext, vNext] = updateIntentReference(qCurrent, desired, ...
        calibration, details.isRest, vCurrent);
    if idx < stepCount
        stateLog(idx+1, layout.referencePosition) = qNext(end, :);
        stateLog(idx+1, layout.referenceVelocity) = vNext(end, :);
    end
    qCurrent = qNext(end, :);
    vCurrent = vNext(end, :);
end
referenceHistory = stateLog(:, layout.referencePosition);
referenceHistoryCount = stepCount;
intentTarget = qCurrent(:);
intentVelocity = vCurrent(:);
intentGateState = gateState;
intentCalibrationContentSha256 = calibration.contentSha256;
referenceSource = "emgIntent";
observationVariant = "intentMarkov60";
stateLength = 60;
repetitionId = 1;
path = fullfile(root, "episode00001.mat");
save(path, "stateLog", "emgLog", "referenceHistory", ...
    "referenceHistoryCount", "intentTarget", "intentVelocity", ...
    "intentGateState", "intentCalibrationContentSha256", ...
    "referenceSource", "observationVariant", "stateLength", ...
    "repetitionId");
end

function value = decoderDetails(gateActive, isRest, countdown)
value = struct("gateActive", logical(gateActive), ...
    "isRest", logical(isRest), ...
    "lowActivityCountdown", logical(countdown));
end

function value = referenceDetails(position, braking, acceleration)
value = struct("positionLimited", repmat(logical(position), 1, 4), ...
    "brakingLimited", repmat(logical(braking), 1, 4), ...
    "accelerationLimited", repmat(logical(acceleration), 1, 4));
end

function [dataset, calibration, expected] = buildFixture(seed)
config = buildNoGloveStage2OfflineConfig(seed);
dataset = buildSyntheticEmgIntentDataset(config);
calibration = calibrateEmgIntent(dataset.restCapture, ...
    dataset.instructionTrials, config.calibrationOptions);
options = config.calibrationOptions;
expected = struct( ...
    "userId", dataset.restCapture.userId, ...
    "sessionId", dataset.restCapture.sessionId, ...
    "channelOrder", dataset.restCapture.channelOrder, ...
    "sampleRateHz", dataset.restCapture.sampleRateHz, ...
    "windowLengthSamples", dataset.windowLengthSamples, ...
    "hopLengthSamples", dataset.hopLengthSamples, ...
    "dataProvenance", dataset.restCapture.dataProvenance, ...
    "motorOrder", options.motorOrder, ...
    "units", struct("rawEmg", dataset.restCapture.rawEmgUnits, ...
        "envelope", options.envelopeUnits, ...
        "position", options.positionUnits, ...
        "velocity", options.velocityUnits, ...
        "acceleration", options.accelerationUnits), ...
    "synergyMatrixVersion", options.synergyMatrixVersion, ...
    "instructionProtocolVersion", options.instructionProtocolVersion, ...
    "sourceDomain", "rawEmgSameSession", ...
    "calibrationContentSha256", calibration.contentSha256);
end

function removeTempDir(path)
if isfolder(path) && startsWith(path, string(tempdir))
    rmdir(path, "s");
end
end
