function report = run_no_glove_stage7m_observable_hold_state(options)
%run_no_glove_stage7m_observable_hold_state validates the 62-value state.
%
% Two deterministic SimController traces compare intentMarkov60 against the
% opt-in 62-value observation. No agent, training, DTW or hardware is used.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7m_observable_hold_state");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7m_observable_hold_state:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testFiles = [ ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testIntentDeclaredRestHoldMarkov62.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testIntentMarkov60.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testReferenceSources.m")];
testResults = runtests(testFiles);
save(fullfile(runRoot, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7m_observable_hold_state:TestsFailed", ...
        "ETAPA 7M tests failed. See %s.", runRoot);
end

[stage7l, sourceHashesBefore, parentAudit] = ...
    loadAndValidateParent(options.stage7lRunRoot);
[dataset, calibration, expected] = buildFixture(options.randomSeed);
profile60 = buildNoGloveStage4Override( ...
    calibration, expected, options.randomSeed);
profile60.maxNumberStepsInEpisodes = options.smokeStepCount+2;
profile62 = buildNoGloveStage7mOverride( ...
    calibration, expected, options.randomSeed);
profile62.maxNumberStepsInEpisodes = options.smokeStepCount+2;
actions = deterministicActions(options.smokeStepCount);
trace60 = runTrace(profile60, dataset.evaluationRawEmg, actions, ...
    options.randomSeed);
trace62 = runTrace(profile62, dataset.evaluationRawEmg, actions, ...
    options.randomSeed);

layoutAudit = buildLayoutAudit();
configurationAudit = buildConfigurationAudit(profile60, profile62);
equivalenceAudit = buildEquivalenceAudit(trace60, trace62);
runtimeAlignmentAudit = buildRuntimeAlignmentAudit(trace62, profile62);
semanticTransitionAudit = buildSemanticTransitionAudit( ...
    profile62.intentDeclaredRestHoldPositionMseTolerance);
[gateChecks, classification] = buildGateChecks(layoutAudit, ...
    configurationAudit, equivalenceAudit, runtimeAlignmentAudit, ...
    semanticTransitionAudit, testResults);
if ~all(gateChecks.passed)
    error("run_no_glove_stage7m_observable_hold_state:GateFailed", ...
        "One or more predeclared ETAPA 7M gates failed.");
end

sourceHashesAfter = hashParentSources(options.stage7lRunRoot);
if ~isequal(sourceHashesBefore, sourceHashesAfter)
    error("run_no_glove_stage7m_observable_hold_state:ParentModified", ...
        "A frozen ETAPA 7L artifact changed during the smoke.");
end

sourceDecision = buildSourceDecision(classification, ...
    equivalenceAudit, runtimeAlignmentAudit, semanticTransitionAudit);
writetable(sourceHashesBefore, fullfile(runRoot, "source_hashes.csv"));
writetable(parentAudit, fullfile(runRoot, "parent_audit.csv"));
writetable(layoutAudit, fullfile(runRoot, "layout_audit.csv"));
writetable(configurationAudit, ...
    fullfile(runRoot, "configuration_audit.csv"));
writetable(equivalenceAudit, ...
    fullfile(runRoot, "paired_equivalence_audit.csv"));
writetable(runtimeAlignmentAudit, ...
    fullfile(runRoot, "runtime_alignment_audit.csv"));
writetable(semanticTransitionAudit, ...
    fullfile(runRoot, "semantic_transition_audit.csv"));
writetable(gateChecks, fullfile(runRoot, "gate_checks.csv"));
writetable(sourceDecision, fullfile(runRoot, "source_decision.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = string(stage7l.agent7250CheckpointPath);
agent7250Hash = fileSha256(agent7250Path);
if agent7250Hash ~= string(stage7l.agent7250CheckpointSha256)
    error("run_no_glove_stage7m_observable_hold_state:Agent7250Hash", ...
        "The canonical Agent7250 file changed.");
end
manifest = struct("stage", "7M", "schemaVersion", 1, ...
    "result", "PASS", "scientificResult", classification, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "environmentVersion", Env.v, ...
    "launcher", "run_no_glove_stage7m_observable_hold_state", ...
    "preregistrationCommit", ...
        "155399a15ec9919e01b41bdb70fd0978a044aa0a", ...
    "stage7lRunRoot", options.stage7lRunRoot, ...
    "stage7lManifestSha256", sourceHashesBefore.sha256(1), ...
    "stage7lResultsSha256", sourceHashesBefore.sha256(2), ...
    "stage7lSourceDecisionSha256", sourceHashesBefore.sha256(3), ...
    "parentAudit", table2struct(parentAudit), ...
    "randomSeed", options.randomSeed, ...
    "smokeStepCount", options.smokeStepCount, ...
    "referenceSource", "emgIntent", ...
    "controlObservationVariant", "intentMarkov60", ...
    "candidateObservationVariant", ...
        "intentDeclaredRestHoldMarkov62", ...
    "controlStateLength", 60, "candidateStateLength", 62, ...
    "declaredRestIndex", 61, "holdLatchIndex", 62, ...
    "holdPositionMseTolerance", ...
        profile62.intentDeclaredRestHoldPositionMseTolerance, ...
    "rewardType", string(profile62.rewardType), ...
    "actionInterfaceVariant", ...
        string(profile62.actionInterfaceVariant), ...
    "layoutAudit", table2struct(layoutAudit), ...
    "configurationAudit", table2struct(configurationAudit), ...
    "gateChecks", table2struct(gateChecks), ...
    "sourceDecision", table2struct(sourceDecision), ...
    "observationVariantImplemented", true, ...
    "runtimeSemanticLoggingImplemented", true, ...
    "intentMarkov60LoggingSchemaPreserved", true, ...
    "historicalObservationVariantsPreserved", true, ...
    "stage7jContractReauthorized", false, ...
    "stage7lContractPreserved", true, ...
    "behavioralInterventionExecuted", false, ...
    "behavioralAblationAuthorized", false, ...
    "rootCauseIdentified", false, ...
    "policyChanged", false, "stateChanged", true, ...
    "defaultStateChanged", false, "rewardChanged", false, ...
    "referenceChanged", false, "quantizationChanged", false, ...
    "simulatorChanged", false, "safetyLayerChanged", false, ...
    "runTraining", false, "newTraining", false, ...
    "agentLoaded", false, "envCreated", true, ...
    "simulatorInvoked", true, "simMotors", true, ...
    "rewardFunctionInvoked", true, "dtwCalculated", false, ...
    "hardwareUsed", false, "pilotAuthorized", false, ...
    "longCampaignAuthorized", false, "agent7250Loaded", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", agent7250Hash, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);
save(fullfile(runRoot, "stage7m_results.mat"), "manifest", ...
    "layoutAudit", "configurationAudit", "equivalenceAudit", ...
    "runtimeAlignmentAudit", "semanticTransitionAudit", ...
    "gateChecks", "sourceDecision", "sourceHashesBefore", ...
    "parentAudit", "stage7l", "profile60", "profile62", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", classification, "outputPath", runRoot, ...
    "manifest", manifest, "gateChecks", gateChecks, ...
    "sourceDecision", sourceDecision);
fprintf("ETAPA 7M OBSERVABLE HOLD STATE PASS\n");
fprintf("Scientific result: %s\n", classification);
fprintf("Output: %s\n", runRoot);
disp(gateChecks);
disp(sourceDecision);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7m_observable_hold_state:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct("resultsRoot", "", "stage7lRunRoot", ...
    "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7l_artifacts\" + ...
    "stage7l_final\2026-08-28_21-44-35-302", ...
    "randomSeed", 11, "smokeStepCount", 20);
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7m_observable_hold_state:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.stage7lRunRoot = string(options.stage7lRunRoot);
if ~isnumeric(options.randomSeed) || ~isscalar(options.randomSeed) || ...
        ~isfinite(options.randomSeed) || options.randomSeed < 0 || ...
        fix(options.randomSeed) ~= options.randomSeed
    error("run_no_glove_stage7m_observable_hold_state:InvalidSeed", ...
        "randomSeed must be a nonnegative integer.");
end
if ~isnumeric(options.smokeStepCount) || ...
        ~isscalar(options.smokeStepCount) || ...
        ~isfinite(options.smokeStepCount) || ...
        options.smokeStepCount < 4 || ...
        fix(options.smokeStepCount) ~= options.smokeStepCount
    error("run_no_glove_stage7m_observable_hold_state:InvalidStepCount", ...
        "smokeStepCount must be an integer of at least four.");
end
if ~isfile(fullfile(options.stage7lRunRoot, "manifest.json"))
    error("run_no_glove_stage7m_observable_hold_state:MissingStage7l", ...
        "ETAPA 7L manifest not found under %s.", options.stage7lRunRoot);
end
end

function [manifest, hashes, audit] = loadAndValidateParent(root)
manifest = jsondecode(fileread(fullfile(root, "manifest.json")));
valid = string(manifest.stage) == "7L" && ...
    string(manifest.result) == "PASS" && ...
    string(manifest.scientificResult) == ...
        "offlineDeclaredRestEligibilitySupported" && ...
    logical(manifest.contractSupported) && ...
    double(manifest.inputEpisodeCount) == 548 && ...
    double(manifest.inputWindowCount) == 31220 && ...
    logical(manifest.inputsPreserved) && ...
    ~logical(manifest.observationVariantImplemented) && ...
    ~logical(manifest.behavioralAblationAuthorized) && ...
    ~logical(manifest.stage7jContractReauthorized) && ...
    ~logical(manifest.runTraining) && ~logical(manifest.agentLoaded) && ...
    ~logical(manifest.simulatorInvoked) && ...
    ~logical(manifest.dtwCalculated) && ~logical(manifest.hardwareUsed) && ...
    ~logical(manifest.agent7250Loaded);
if ~valid
    error("run_no_glove_stage7m_observable_hold_state:Stage7lContract", ...
        "Input manifest is not the frozen ETAPA 7L result.");
end
required = ["stage7l_results.mat", "source_decision.csv"];
for name = required
    if ~isfile(fullfile(root, name))
        error("run_no_glove_stage7m_observable_hold_state:Stage7lArtifact", ...
            "Frozen ETAPA 7L artifact %s is missing.", name);
    end
end
hashes = hashParentSources(root);
audit = table(string(manifest.scientificResult), ...
    logical(manifest.contractSupported), ...
    double(manifest.inputEpisodeCount), ...
    double(manifest.inputWindowCount), logical(manifest.inputsPreserved), ...
    logical(manifest.stage7jContractReauthorized), ...
    logical(manifest.observationVariantImplemented), ...
    logical(manifest.behavioralAblationAuthorized), ...
    'VariableNames', ["scientificResult", "contractSupported", ...
    "episodeCount", "windowCount", "inputsPreserved", ...
    "stage7jContractReauthorized", "observationVariantImplemented", ...
    "behavioralAblationAuthorized"]);
end

function hashes = hashParentSources(root)
names = ["manifest.json"; "stage7l_results.mat"; ...
    "source_decision.csv"];
labels = ["stage7lManifest"; "stage7lResults"; ...
    "stage7lSourceDecision"];
paths = fullfile(root, names);
sha256 = strings(numel(paths), 1);
bytes = zeros(numel(paths), 1);
for idx = 1:numel(paths)
    info = dir(paths(idx));
    if isempty(info)
        error("run_no_glove_stage7m_observable_hold_state:SourceMissing", ...
            "Frozen source %s is missing.", paths(idx));
    end
    sha256(idx) = fileSha256(paths(idx));
    bytes(idx) = info.bytes;
end
hashes = table(labels, paths, sha256, bytes);
end

function trace = runTrace(profile, raw, actions, seed)
rng(seed, "twister");
setConfigurablesOverride(profile);
root = string(tempname);
mkdir(root);
cleanup = onCleanup(@() removeTempDir(root));
env = Env(root, true, {raw, raw}, {});
layout = buildObservationLayout(string(profile.observationVariant), 40, 3, 4);
obsInfo = env.getObservationInfo();
count = size(actions, 1);
trace.variant = string(profile.observationVariant);
trace.layout = layout;
trace.observations = nan(count+1, layout.totalLength);
trace.rewards = nan(count, 1);
trace.provenance = cell(count, 1);
trace.observations(1, :) = reset(env)';
for idx = 1:count
    [observation, trace.rewards(idx)] = step(env, actions(idx, :)');
    trace.observations(idx+1, :) = observation';
    trace.provenance{idx} = env.intentProvenanceLog{idx};
end
trace.rawAction = env.actionLog(1:count, :);
trace.effectiveAction = env.actionSatLog(1:count, :);
trace.pwm = env.actionPwmLog(1:count, :);
trace.referenceHistory = env.referenceHistory(1:count, :);
trace.safety = env.positionSafetyInterventionLog(1:count, :);
trace.lowerLimit = obsInfo.LowerLimit(:)';
trace.upperLimit = obsInfo.UpperLimit(:)';
end

function audit = buildLayoutAudit()
variants = ["legacy44", "markov52", "intentMarkov60", ...
    "intentDeclaredRestHoldMarkov62", "stackedEmg132"]';
count = numel(variants);
totalLength = zeros(count, 1);
emgIndices = strings(count, 1);
encoderIndices = strings(count, 1);
referencePositionIndices = strings(count, 1);
referenceVelocityIndices = strings(count, 1);
declaredRestIndex = nan(count, 1);
holdLatchIndex = nan(count, 1);
for idx = 1:count
    layout = buildObservationLayout(variants(idx), 40, 3, 4);
    totalLength(idx) = layout.totalLength;
    emgIndices(idx) = mat2str(layout.emg);
    encoderIndices(idx) = mat2str(layout.encoder);
    referencePositionIndices(idx) = mat2str(layout.referencePosition);
    referenceVelocityIndices(idx) = mat2str(layout.referenceVelocity);
    if ~isempty(layout.declaredRest)
        declaredRestIndex(idx) = layout.declaredRest;
        holdLatchIndex(idx) = layout.holdLatch;
    end
end
audit = table(variants, totalLength, emgIndices, encoderIndices, ...
    referencePositionIndices, referenceVelocityIndices, ...
    declaredRestIndex, holdLatchIndex);
end

function audit = buildConfigurationAudit(profile60, profile62)
clearConfigurablesOverride();
defaults = configurables();
setConfigurablesOverride(profile60);
control = configurables();
setConfigurablesOverride(profile62);
candidate = configurables();
names = ["default"; "control"; "candidate"];
observationVariant = [string(defaults.observationVariant); ...
    string(control.observationVariant); ...
    string(candidate.observationVariant)];
stateLength = [defaults.stateLength; control.stateLength; ...
    candidate.stateLength];
referenceSource = [string(defaults.referenceSource); ...
    string(control.referenceSource); string(candidate.referenceSource)];
intentDecoderEnabled = [defaults.intentDecoderEnabled; ...
    control.intentDecoderEnabled; candidate.intentDecoderEnabled];
simMotors = [defaults.simMotors; control.simMotors; candidate.simMotors];
runTraining = [defaults.run_training; control.run_training; ...
    candidate.run_training];
rewardType = [string(defaults.rewardType); string(control.rewardType); ...
    string(candidate.rewardType)];
actionInterfaceVariant = [string(defaults.actionInterfaceVariant); ...
    string(control.actionInterfaceVariant); ...
    string(candidate.actionInterfaceVariant)];
holdPositionMseTolerance = [ ...
    defaults.intentDeclaredRestHoldPositionMseTolerance; ...
    control.intentDeclaredRestHoldPositionMseTolerance; ...
    candidate.intentDeclaredRestHoldPositionMseTolerance];
audit = table(names, observationVariant, stateLength, referenceSource, ...
    intentDecoderEnabled, simMotors, runTraining, rewardType, ...
    actionInterfaceVariant, holdPositionMseTolerance);
end

function audit = buildEquivalenceAudit(control, candidate)
count = size(control.observations, 1);
decisionIndex = (0:count-1)';
statePrefixMaxAbsDifference = max(abs( ...
    control.observations-candidate.observations(:, 1:60)), [], 2);
referencePositionMaxAbsDifference = max(abs( ...
    control.observations(:, 53:56)- ...
    candidate.observations(:, 53:56)), [], 2);
referenceVelocityMaxAbsDifference = max(abs( ...
    control.observations(:, 57:60)- ...
    candidate.observations(:, 57:60)), [], 2);
rewardAbsDifference = [NaN; abs(control.rewards-candidate.rewards)];
rawActionMaxAbsDifference = [NaN; max(abs( ...
    control.rawAction-candidate.rawAction), [], 2)];
effectiveActionMaxAbsDifference = [NaN; max(abs( ...
    control.effectiveAction-candidate.effectiveAction), [], 2)];
pwmMaxAbsDifference = [NaN; max(abs(control.pwm-candidate.pwm), [], 2)];
safetyMaxAbsDifference = [NaN; max(abs( ...
    control.safety-candidate.safety), [], 2)];
controlFinite = all(isfinite(control.observations), 2);
candidateFinite = all(isfinite(candidate.observations), 2);
candidateWithinBounds = all(candidate.observations >= ...
    candidate.lowerLimit & candidate.observations <= ...
    candidate.upperLimit, 2);
audit = table(decisionIndex, statePrefixMaxAbsDifference, ...
    referencePositionMaxAbsDifference, ...
    referenceVelocityMaxAbsDifference, rewardAbsDifference, ...
    rawActionMaxAbsDifference, effectiveActionMaxAbsDifference, ...
    pwmMaxAbsDifference, safetyMaxAbsDifference, controlFinite, ...
    candidateFinite, candidateWithinBounds);
end

function audit = buildRuntimeAlignmentAudit(trace, profile)
layout = trace.layout;
count = size(trace.observations, 1);
decisionIndex = (0:count-1)';
provenance = strings(count, 1);
observedDeclaredRest = logical( ...
    trace.observations(:, layout.declaredRest));
observedHoldLatch = logical(trace.observations(:, layout.holdLatch));
expectedDeclaredRest = false(count, 1);
expectedHoldLatch = false(count, 1);
positionMse = zeros(count, 1);
nearTarget = false(count, 1);
schemaVersion = nan(count, 1);
expectedDeclaredRest(1) = true;
expectedHoldLatch(1) = true;
provenance(1) = "episodeInitialization";
positionMse(1) = mean((trace.observations(1, layout.encoder)- ...
    trace.observations(1, layout.referencePosition)).^2);
nearTarget(1) = positionMse(1) <= ...
    profile.intentDeclaredRestHoldPositionMseTolerance;
for idx = 2:count
    item = trace.provenance{idx-1};
    provenance(idx) = string(item.zeroReferenceReason);
    expectedDeclaredRest(idx) = logical(item.isRest);
    positionMse(idx) = mean((trace.observations(idx, layout.encoder)- ...
        trace.observations(idx, layout.referencePosition)).^2);
    nearTarget(idx) = positionMse(idx) <= ...
        profile.intentDeclaredRestHoldPositionMseTolerance;
    if ~expectedDeclaredRest(idx)
        expectedHoldLatch(idx) = false;
    elseif nearTarget(idx)
        expectedHoldLatch(idx) = true;
    else
        expectedHoldLatch(idx) = expectedHoldLatch(idx-1);
    end
    schemaVersion(idx) = item.schemaVersion;
end
declaredRestMismatch = observedDeclaredRest ~= expectedDeclaredRest;
holdLatchMismatch = observedHoldLatch ~= expectedHoldLatch;
audit = table(decisionIndex, provenance, positionMse, nearTarget, ...
    observedDeclaredRest, expectedDeclaredRest, declaredRestMismatch, ...
    observedHoldLatch, expectedHoldLatch, holdLatchMismatch, schemaVersion);
end

function audit = buildSemanticTransitionAudit(tolerance)
caseName = ["initializeNear"; "retainFarRest"; ...
    "releaseCountdownNear"; "remainInactiveFarRest"];
previousLatch = logical([0; 1; 1; 0]);
declaredRest = logical([1; 1; 0; 1]);
encoder = repmat([0.2, 0.3, 0.4, 0.5], 4, 1);
reference = encoder;
reference(2, :) = reference(2, :)+0.02;
reference(4, :) = reference(4, :)+0.02;
expectedLatch = logical([1; 1; 0; 0]);
observedLatch = false(4, 1);
nearTarget = false(4, 1);
positionMse = zeros(4, 1);
for idx = 1:4
    [observedLatch(idx), details] = ...
        updateIntentDeclaredRestHoldState(previousLatch(idx), ...
        declaredRest(idx), encoder(idx, :), reference(idx, :), tolerance);
    nearTarget(idx) = details.nearTarget;
    positionMse(idx) = details.positionMse;
end
geometricNearWouldActivate = nearTarget;
semanticGeometricDivergence = observedLatch ~= ...
    geometricNearWouldActivate;
passed = observedLatch == expectedLatch;
audit = table(caseName, previousLatch, declaredRest, positionMse, ...
    nearTarget, expectedLatch, observedLatch, ...
    geometricNearWouldActivate, semanticGeometricDivergence, passed);
end

function [checks, classification] = buildGateChecks(layout, config, ...
        equivalence, runtime, semantic, tests)
candidateLayout = layout(layout.variants == ...
    "intentDeclaredRestHoldMarkov62", :);
candidateConfig = config(config.names == "candidate", :);
defaultConfig = config(config.names == "default", :);
tolerance = 1e-12;
values = [candidateLayout.totalLength; ...
    double(candidateLayout.declaredRestIndex == 61 && ...
        candidateLayout.holdLatchIndex == 62); ...
    double(defaultConfig.observationVariant == "markov52" && ...
        defaultConfig.stateLength == 52); ...
    double(candidateConfig.simMotors && ~candidateConfig.runTraining); ...
    max(equivalence.statePrefixMaxAbsDifference); ...
    max(equivalence.rewardAbsDifference(2:end)); ...
    max([equivalence.referencePositionMaxAbsDifference; ...
        equivalence.referenceVelocityMaxAbsDifference]); ...
    max([equivalence.rawActionMaxAbsDifference(2:end); ...
        equivalence.effectiveActionMaxAbsDifference(2:end); ...
        equivalence.pwmMaxAbsDifference(2:end); ...
        equivalence.safetyMaxAbsDifference(2:end)]); ...
    sum(runtime.declaredRestMismatch); sum(runtime.holdLatchMismatch); ...
    double(runtime.observedDeclaredRest(1) && ...
        runtime.observedHoldLatch(1)); ...
    double(all(semantic.passed)); ...
    double(any(semantic.semanticGeometricDivergence & ...
        ~semantic.declaredRest & semantic.nearTarget)); ...
    double(all(equivalence.controlFinite & ...
        equivalence.candidateFinite & equivalence.candidateWithinBounds)); ...
    double(all([tests.Passed]))];
threshold = [62; 1; 1; 1; tolerance; tolerance; tolerance; ...
    tolerance; 0; 0; 1; 1; 1; 1; 1];
comparison = ["equal"; "equal"; "equal"; "equal"; ...
    "lessOrEqual"; "lessOrEqual"; "lessOrEqual"; "lessOrEqual"; ...
    "equal"; "equal"; "equal"; "equal"; "equal"; "equal"; "equal"];
passed = false(numel(values), 1);
for idx = 1:numel(values)
    if comparison(idx) == "lessOrEqual"
        passed(idx) = values(idx) <= threshold(idx);
    else
        passed(idx) = values(idx) == threshold(idx);
    end
end
check = ["candidateStateLength"; "semanticBitIndices"; ...
    "historicalDefaultPreserved"; "simulationOnlyProfile"; ...
    "statePrefixDifference"; "rewardDifference"; ...
    "referenceDifference"; "actuatorAndSafetyDifference"; ...
    "declaredRestReplayMismatchCount"; "holdLatchReplayMismatchCount"; ...
    "initialSemanticBits"; "semanticTransitions"; ...
    "countdownGeometricDivergence"; "finiteBoundedObservations"; ...
    "specificTests"];
checks = table(check, values, threshold, comparison, passed, ...
    'VariableNames', ["check", "observed", "threshold", ...
    "comparison", "passed"]);
if ~all(passed(1:4))
    classification = "intentDeclaredRestHoldLayoutInvalid";
elseif ~all(passed(9:13))
    classification = "intentDeclaredRestHoldCausalityInvalid";
elseif ~all(passed([5:8, 14]))
    classification = "intentDeclaredRestHoldBehavioralRegression";
elseif ~passed(15)
    classification = "intentDeclaredRestHoldTestFailure";
else
    classification = "intentDeclaredRestHoldMarkov62Implemented";
end
end

function decision = buildSourceDecision(classification, equivalence, ...
        runtime, semantic)
decision = table(classification, true, ...
    max(equivalence.statePrefixMaxAbsDifference), ...
    max(equivalence.rewardAbsDifference(2:end)), ...
    max([equivalence.referencePositionMaxAbsDifference; ...
        equivalence.referenceVelocityMaxAbsDifference]), ...
    max([equivalence.effectiveActionMaxAbsDifference(2:end); ...
        equivalence.pwmMaxAbsDifference(2:end); ...
        equivalence.safetyMaxAbsDifference(2:end)]), ...
    sum(runtime.declaredRestMismatch), sum(runtime.holdLatchMismatch), ...
    sum(runtime.observedDeclaredRest), sum(runtime.observedHoldLatch), ...
    any(semantic.semanticGeometricDivergence & ...
        ~semantic.declaredRest & semantic.nearTarget), ...
    true, true, false, false, false, ...
    'VariableNames', ["classification", "allGatesPassed", ...
    "maximumStatePrefixDifference", "maximumRewardDifference", ...
    "maximumReferenceDifference", ...
    "maximumActuatorOrSafetyDifference", ...
    "declaredRestReplayMismatchCount", "holdLatchReplayMismatchCount", ...
    "declaredRestDecisionCount", "holdLatchDecisionCount", ...
    "countdownGeometricDivergenceDemonstrated", ...
    "observationVariantImplemented", "explicitMemoryObservable", ...
    "behavioralAblationAuthorized", "trainingAuthorized", ...
    "stage7jContractReauthorized"]);
end

function [dataset, calibration, expected] = buildFixture(seed)
config = buildNoGloveStage2OfflineConfig(seed);
dataset = buildSyntheticEmgIntentDataset(config);
calibration = calibrateEmgIntent(dataset.restCapture, ...
    dataset.instructionTrials, config.calibrationOptions);
options = config.calibrationOptions;
expected = struct( ...
    "userId", dataset.restCapture.userId, ...
    "sessionId", dataset.restCapture.sessionId, ...
    "channelOrder", dataset.restCapture.channelOrder, ...
    "sampleRateHz", dataset.restCapture.sampleRateHz, ...
    "windowLengthSamples", dataset.windowLengthSamples, ...
    "hopLengthSamples", dataset.hopLengthSamples, ...
    "dataProvenance", dataset.restCapture.dataProvenance, ...
    "motorOrder", options.motorOrder, ...
    "units", struct("rawEmg", dataset.restCapture.rawEmgUnits, ...
        "envelope", options.envelopeUnits, ...
        "position", options.positionUnits, ...
        "velocity", options.velocityUnits, ...
        "acceleration", options.accelerationUnits), ...
    "synergyMatrixVersion", options.synergyMatrixVersion, ...
    "instructionProtocolVersion", options.instructionProtocolVersion, ...
    "sourceDomain", "rawEmgSameSession", ...
    "calibrationContentSha256", calibration.contentSha256);
end

function actions = deterministicActions(count)
pattern = [0.4, -0.4, 0.2, -0.2; 0, 0, 0, 0; ...
    -0.2, 0.2, -0.4, 0.4; 0.1, 0.1, -0.1, -0.1];
actions = repmat(pattern, ceil(count/size(pattern, 1)), 1);
actions = actions(1:count, :);
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf("cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7m_observable_hold_state(struct(" + ...
    "'resultsRoot','%s','stage7lRunRoot','%s'," + ...
    "'randomSeed',%d,'smokeStepCount',%d))", ...
    escapeQuote(matlabRoot), escapeQuote(string(fileparts(runRoot))), ...
    escapeQuote(options.stage7lRunRoot), options.randomSeed, ...
    options.smokeStepCount);
end

function value = buildOfflineReport(manifest)
d = manifest.sourceDecision;
lines = ["# ETAPA 7M - observable declared-rest hold state"; ""; ...
    "- Engineering result: PASS."; ...
    "- Scientific result: " + manifest.scientificResult + "."; ...
    "- Candidate state: intentDeclaredRestHoldMarkov62 (62 values)."; ...
    sprintf("- Maximum 60-prefix difference: %.3g.", ...
        d.maximumStatePrefixDifference); ...
    sprintf("- Maximum reward difference: %.3g.", ...
        d.maximumRewardDifference); ...
    sprintf("- Maximum reference difference: %.3g.", ...
        d.maximumReferenceDifference); ...
    sprintf("- Declared-rest/latch replay mismatches: %d/%d.", ...
        d.declaredRestReplayMismatchCount, ...
        d.holdLatchReplayMismatchCount); ...
    "- Synthetic countdown/geometric divergence: demonstrated."; ...
    "- Historical default: markov52; Stage 7J remains unauthorized."; ...
    "- Agent/training/DTW/hardware: no/no/no/no."];
value = strjoin(lines, newline);
end

function hashes = inventoryArtifacts(runRoot)
names = ["test_results.mat", "source_hashes.csv", ...
    "parent_audit.csv", "layout_audit.csv", ...
    "configuration_audit.csv", "paired_equivalence_audit.csv", ...
    "runtime_alignment_audit.csv", "semantic_transition_audit.csv", ...
    "gate_checks.csv", "source_decision.csv", ...
    "stage7m_results.mat", "offline_report.md", ...
    "reproducible_command.txt"];
hashes = repmat(struct("path", "", "sha256", ""), numel(names), 1);
for idx = 1:numel(names)
    hashes(idx).path = names(idx);
    hashes(idx).sha256 = fileSha256(fullfile(runRoot, names(idx)));
end
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
commit = "unknown";
if status == 0
    commit = string(strtrim(output));
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[trackedStatus, trackedOutput] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = trackedStatus ~= 0 || ...
    strlength(strtrim(string(trackedOutput))) > 0;
end

function hash = fileSha256(path)
fid = fopen(path, "r");
if fid < 0
    error("run_no_glove_stage7m_observable_hold_state:HashFailed", ...
        "Could not open %s for hashing.", path);
end
cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid, Inf, "*uint8");
digest = java.security.MessageDigest.getInstance("SHA-256");
digest.update(bytes);
digestBytes = typecast(digest.digest(), "uint8");
hash = upper(string(reshape(dec2hex(digestBytes, 2)', 1, [])));
end

function value = escapeQuote(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7m_observable_hold_state:WriteFailed", ...
        "Could not open %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function removeTempDir(root)
if isfolder(root) && startsWith(root, string(tempdir))
    rmdir(root, "s");
end
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
