function report = run_no_glove_stage7_offline_temporal_analysis(options)
%run_no_glove_stage7_offline_temporal_analysis executes ETAPA 7 only.
%
% The launcher reads ETAPA 6C traces, calculates bounded discrete lags,
% correlations and one shared four-motor DTW path per episode. It does not
% load an agent, create Env, invoke a simulator/reward or use hardware.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));
clearConfigurablesOverride();

[inputManifest, inputManifestPath, inputResultsPath] = ...
    loadAndValidateInput(options.stage6cRunRoot);
inputResultsHashBefore = fileSha256(inputResultsPath);
expectedResultsHash = findArtifactHash( ...
    inputManifest.artifactHashes, "stage6c_results.mat");
if inputResultsHashBefore ~= expectedResultsHash
    error("run_no_glove_stage7_offline_temporal_analysis:InputHashMismatch", ...
        "ETAPA 6C results do not match their manifest.");
end

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7_offline_temporal");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runDir)
    error("run_no_glove_stage7_offline_temporal_analysis:OutputExists", ...
        "Refusing to reuse output directory %s.", runDir);
end
mkdir(runDir);

testPath = fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage7TemporalMetrics.m");
testResults = runtests(testPath);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7_offline_temporal_analysis:TestsFailed", ...
        "ETAPA 7 tests failed; analysis is forbidden. See %s.", runDir);
end

source = load(inputResultsPath, "acceptance", "rest");
analysisOptions = struct( ...
    "maxDiscreteLagSteps", options.maxDiscreteLagSteps, ...
    "dtwMaxLagSteps", options.dtwMaxLagSteps, ...
    "activeVelocityThreshold", options.activeVelocityThreshold, ...
    "minimumRegimeSamples", options.minimumRegimeSamples, ...
    "minimumBenefitFraction", options.minimumBenefitFraction, ...
    "fixedLagDominanceFraction", options.fixedLagDominanceFraction, ...
    "periodSec", options.periodSec);
analysisArguments = namedargs2cell(analysisOptions);

acceptanceTic = tic;
acceptance = analyzeNoGloveStage7TemporalMetrics( ...
    source.acceptance.componentTable, "acceptance", ...
    analysisArguments{:});
acceptanceElapsedSec = toc(acceptanceTic);
restTic = tic;
rest = analyzeNoGloveStage7TemporalMetrics( ...
    source.rest.componentTable, "steady_rest", ...
    analysisArguments{:});
restElapsedSec = toc(restTic);

inputResultsHashAfter = fileSha256(inputResultsPath);
if inputResultsHashAfter ~= inputResultsHashBefore
    error("run_no_glove_stage7_offline_temporal_analysis:InputModified", ...
        "Immutable ETAPA 6C results changed during ETAPA 7.");
end

writeAnalysisTables(runDir, "acceptance", acceptance);
writeAnalysisTables(runDir, "steady_rest", rest);
primaryDecision = acceptance.evidenceDecision( ...
    acceptance.evidenceDecision.commandSource == "Agent200", :);
if height(primaryDecision) ~= 1
    error("run_no_glove_stage7_offline_temporal_analysis:MissingPrimary", ...
        "Expected exactly one Agent200 acceptance decision.");
end
temporalBenefitGatePassed = ...
    primaryDecision.classification == "dtwMetricCandidate";
fixedLagPreferred = ...
    primaryDecision.classification == "fixedLagPreferred";
cancelDtwRewardStages = ...
    primaryDecision.classification == "noMaterialTemporalBenefit";

save(fullfile(runDir, "stage7_results.mat"), ...
    "acceptance", "rest", "analysisOptions", "primaryDecision", ...
    "temporalBenefitGatePassed", "fixedLagPreferred", ...
    "cancelDtwRewardStages", "acceptanceElapsedSec", ...
    "restElapsedSec", "inputManifest", "-v7.3");

reproducibleCommand = buildReproducibleCommand( ...
    matlabRoot, options, fileparts(runDir));
writeText(fullfile(runDir, "reproducible_command.txt"), ...
    reproducibleCommand);
writeOfflineReport(fullfile(runDir, "offline_report.md"), ...
    acceptance, rest, primaryDecision, analysisOptions, ...
    acceptanceElapsedSec, restElapsedSec, runDir);

primaryArtifacts = [ ...
    "acceptance_discrete_lags.csv", ...
    "acceptance_discrete_summary.csv", ...
    "acceptance_regime_lags.csv", ...
    "acceptance_regime_summary.csv", ...
    "acceptance_episode_dtw.csv", ...
    "acceptance_dtw_summary.csv", ...
    "acceptance_evidence_decision.csv", ...
    "steady_rest_discrete_lags.csv", ...
    "steady_rest_discrete_summary.csv", ...
    "steady_rest_regime_lags.csv", ...
    "steady_rest_regime_summary.csv", ...
    "steady_rest_episode_dtw.csv", ...
    "steady_rest_dtw_summary.csv", ...
    "steady_rest_evidence_decision.csv", ...
    "stage7_results.mat", "test_results.mat", ...
    "reproducible_command.txt", "offline_report.md"];
artifactHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(primaryArtifacts), 1);
for artifactIdx = 1:numel(primaryArtifacts)
    artifactHashes(artifactIdx).path = primaryArtifacts(artifactIdx);
    artifactHashes(artifactIdx).sha256 = fileSha256( ...
        fullfile(runDir, primaryArtifacts(artifactIdx)));
end
writetable(struct2table(artifactHashes), ...
    fullfile(runDir, "artifact_hashes.csv"));

[gitCommit, gitDirty, trackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", 7, ...
    "schemaVersion", 1, ...
    "result", "PASS", ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, ...
    "gitDirty", gitDirty, ...
    "gitTrackedDirty", trackedDirty, ...
    "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7_offline_temporal_analysis", ...
    "inputStage6cRunRoot", options.stage6cRunRoot, ...
    "inputManifestPath", inputManifestPath, ...
    "inputManifestSha256", fileSha256(inputManifestPath), ...
    "inputResultsPath", inputResultsPath, ...
    "inputResultsSha256Before", inputResultsHashBefore, ...
    "inputResultsSha256After", inputResultsHashAfter, ...
    "inputResultsPreserved", true, ...
    "inputGitCommit", string(inputManifest.gitCommit), ...
    "analysisOptions", analysisOptions, ...
    "acceptanceEpisodeCountPerSource", ...
        acceptance.episodeCountPerSource, ...
    "restEpisodeCountPerSource", rest.episodeCountPerSource, ...
    "primaryCommandSource", "Agent200", ...
    "primaryClassification", primaryDecision.classification, ...
    "primaryBestFixedLagSteps", primaryDecision.bestFixedLagSteps, ...
    "primaryBestFixedLagSec", primaryDecision.bestFixedLagSec, ...
    "primaryFixedLagImprovementFraction", ...
        primaryDecision.fixedLagImprovementFraction, ...
    "primaryDtwImprovementFraction", ...
        primaryDecision.dtwImprovementFraction, ...
    "primaryDtwMeanAbsLagSteps", primaryDecision.dtwMeanAbsLagSteps, ...
    "temporalBenefitGatePassed", temporalBenefitGatePassed, ...
    "fixedLagPreferred", fixedLagPreferred, ...
    "cancelDtwRewardStages", cancelDtwRewardStages, ...
    "stage8Authorized", false, ...
    "dtwMetricOnly", true, ...
    "dtwRewardUsed", false, ...
    "stateChanged", false, ...
    "rewardChanged", false, ...
    "policyChanged", false, ...
    "referenceChanged", false, ...
    "quantizationChanged", false, ...
    "simulatorChanged", false, ...
    "runTraining", false, ...
    "agentLoaded", false, ...
    "reinforcementLearningInvoked", false, ...
    "envCreated", false, ...
    "simulatorInvoked", false, ...
    "rewardInvoked", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "agent7250Loaded", false, ...
    "hardwareUsed", false, ...
    "acceptanceElapsedSec", acceptanceElapsedSec, ...
    "restElapsedSec", restElapsedSec, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "artifactHashes", artifactHashes, ...
    "outputPath", runDir);
save(fullfile(runDir, "manifest.mat"), "manifest", "artifactHashes");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct( ...
    "result", "PASS", ...
    "outputPath", runDir, ...
    "manifest", manifest, ...
    "acceptance", acceptance, ...
    "rest", rest, ...
    "primaryDecision", primaryDecision, ...
    "testResults", testResults);
fprintf("ETAPA 7 OFFLINE TEMPORAL PASS\n");
fprintf("Output: %s\n", runDir);
disp(acceptance.discreteLagSummary);
disp(acceptance.dtwSummary);
disp(acceptance.evidenceDecision);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7_offline_temporal_analysis:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "stage6cRunRoot", "", "resultsRoot", "", ...
    "maxDiscreteLagSteps", 3, "dtwMaxLagSteps", 1, ...
    "activeVelocityThreshold", 0.005, ...
    "minimumRegimeSamples", 10, ...
    "minimumBenefitFraction", 0.05, ...
    "fixedLagDominanceFraction", 0.80, ...
    "periodSec", 0.2);
unknown = setdiff(string(fieldnames(options)), ...
    string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7_offline_temporal_analysis:UnknownOption", ...
        "Unknown option(s): %s.", strjoin(unknown, ", "));
end
fields = fieldnames(defaults);
for fieldIdx = 1:numel(fields)
    name = fields{fieldIdx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.stage6cRunRoot = string(options.stage6cRunRoot);
options.resultsRoot = string(options.resultsRoot);
if ~isscalar(options.stage6cRunRoot) || ...
        strlength(options.stage6cRunRoot) == 0
    error("run_no_glove_stage7_offline_temporal_analysis:MissingInput", ...
        "stage6cRunRoot is required.");
end
integerFields = ["maxDiscreteLagSteps", "dtwMaxLagSteps", ...
    "minimumRegimeSamples"];
for fieldIdx = 1:numel(integerFields)
    name = integerFields(fieldIdx);
    value = options.(name);
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
            value < 0 || fix(value) ~= value
        error("run_no_glove_stage7_offline_temporal_analysis:InvalidOption", ...
            "%s must be a nonnegative integer.", name);
    end
end
if options.minimumRegimeSamples < 1 || ...
        options.dtwMaxLagSteps > options.maxDiscreteLagSteps
    error("run_no_glove_stage7_offline_temporal_analysis:InvalidOption", ...
        "Invalid sample count or lag bounds.");
end
boundedFields = ["activeVelocityThreshold", ...
    "minimumBenefitFraction", "fixedLagDominanceFraction", "periodSec"];
for fieldIdx = 1:numel(boundedFields)
    name = boundedFields(fieldIdx);
    value = options.(name);
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
            value < 0
        error("run_no_glove_stage7_offline_temporal_analysis:InvalidOption", ...
            "%s must be finite and nonnegative.", name);
    end
end
if options.minimumBenefitFraction > 1 || ...
        options.fixedLagDominanceFraction > 1 || options.periodSec <= 0
    error("run_no_glove_stage7_offline_temporal_analysis:InvalidOption", ...
        "Invalid fraction or period.");
end
end

function [manifest, manifestPath, resultsPath] = ...
        loadAndValidateInput(stage6cRunRoot)
manifestPath = fullfile(stage6cRunRoot, "manifest.json");
resultsPath = fullfile(stage6cRunRoot, "stage6c_results.mat");
if ~isfile(manifestPath) || ~isfile(resultsPath)
    error("run_no_glove_stage7_offline_temporal_analysis:InputNotFound", ...
        "ETAPA 6C manifest/results are missing from %s.", stage6cRunRoot);
end
manifest = jsondecode(fileread(manifestPath));
required = ["stage", "result", "hardwareUsed", "agentLoaded", ...
    "reinforcementLearningInvoked", "dtwCalculated", ...
    "stage7Executed", "sourceEpisodeHashesPreserved", ...
    "artifactHashes", "gitCommit"];
if ~all(isfield(manifest, cellstr(required)))
    error("run_no_glove_stage7_offline_temporal_analysis:InvalidManifest", ...
        "Input manifest lacks the ETAPA 6C audit contract.");
end
valid = string(manifest.stage) == "6C" && ...
    string(manifest.result) == "PASS" && ...
    ~logical(manifest.hardwareUsed) && ~logical(manifest.agentLoaded) && ...
    ~logical(manifest.reinforcementLearningInvoked) && ...
    ~logical(manifest.dtwCalculated) && ...
    ~logical(manifest.stage7Executed) && ...
    logical(manifest.sourceEpisodeHashesPreserved);
if ~valid
    error("run_no_glove_stage7_offline_temporal_analysis:IncompatibleManifest", ...
        "ETAPA 7 requires the immutable PASS output of ETAPA 6C.");
end
end

function expected = findArtifactHash(artifactHashes, artifactName)
paths = string({artifactHashes.path});
match = paths == artifactName;
if sum(match) ~= 1
    error("run_no_glove_stage7_offline_temporal_analysis:HashNotFound", ...
        "Manifest does not contain one hash for %s.", artifactName);
end
expected = upper(string(artifactHashes(match).sha256));
end

function writeAnalysisTables(runDir, prefix, analysis)
writetable(analysis.discreteLagTable, ...
    fullfile(runDir, prefix + "_discrete_lags.csv"));
writetable(analysis.discreteLagSummary, ...
    fullfile(runDir, prefix + "_discrete_summary.csv"));
writetable(analysis.regimeLagTable, ...
    fullfile(runDir, prefix + "_regime_lags.csv"));
writetable(analysis.regimeLagSummary, ...
    fullfile(runDir, prefix + "_regime_summary.csv"));
writetable(analysis.episodeDtwTable, ...
    fullfile(runDir, prefix + "_episode_dtw.csv"));
writetable(analysis.dtwSummary, ...
    fullfile(runDir, prefix + "_dtw_summary.csv"));
writetable(analysis.evidenceDecision, ...
    fullfile(runDir, prefix + "_evidence_decision.csv"));
end

function command = buildReproducibleCommand(matlabRoot, options, resultsRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7_offline_temporal_analysis(struct(" + ...
    "'stage6cRunRoot','%s','resultsRoot','%s'," + ...
    "'maxDiscreteLagSteps',%d,'dtwMaxLagSteps',%d," + ...
    "'activeVelocityThreshold',%.17g,'minimumRegimeSamples',%d," + ...
    "'minimumBenefitFraction',%.17g," + ...
    "'fixedLagDominanceFraction',%.17g,'periodSec',%.17g))", ...
    escape(matlabRoot), escape(options.stage6cRunRoot), ...
    escape(resultsRoot), options.maxDiscreteLagSteps, ...
    options.dtwMaxLagSteps, options.activeVelocityThreshold, ...
    options.minimumRegimeSamples, options.minimumBenefitFraction, ...
    options.fixedLagDominanceFraction, options.periodSec);
end

function writeOfflineReport(pathValue, acceptance, rest, decision, ...
        analysisOptions, acceptanceElapsedSec, restElapsedSec, runDir)
agentDiscrete = acceptance.discreteLagSummary( ...
    acceptance.discreteLagSummary.commandSource == "Agent200", :);
agentDtw = acceptance.dtwSummary( ...
    acceptance.dtwSummary.commandSource == "Agent200", :);
pDiscrete = acceptance.discreteLagSummary( ...
    acceptance.discreteLagSummary.commandSource == "conventionalP", :);
pDtw = acceptance.dtwSummary( ...
    acceptance.dtwSummary.commandSource == "conventionalP", :);
lines = strings(0, 1);
lines(end+1) = "# ETAPA 7 - métricas temporales offline";
lines(end+1) = "";
lines(end+1) = "- Ejecución: PASS.";
lines(end+1) = "- Agente/Env/simulador/reward/hardware: no/no/no/no/no.";
lines(end+1) = sprintf( ...
    "- Lags discretos: ±%d pasos (±%.3f s).", ...
    analysisOptions.maxDiscreteLagSteps, ...
    analysisOptions.maxDiscreteLagSteps * analysisOptions.periodSec);
lines(end+1) = sprintf( ...
    "- DTW: ruta compartida 4-motor, squared, maxLag=%d paso(s).", ...
    analysisOptions.dtwMaxLagSteps);
lines(end+1) = "";
lines(end+1) = "## Aceptación";
lines(end+1) = "";
lines(end+1) = sprintf( ...
    "- Agent200: MSE extremo %.9f; mejor lag %+d (%.3f s), " + ...
    "mejora %.3f%%; DTW %.9f, mejora %.3f%%, lag absoluto " + ...
    "medio %.6f pasos.", agentDiscrete.zeroLagMse, ...
    agentDiscrete.bestMseLagSteps, agentDiscrete.bestMseLagSec, ...
    100*agentDiscrete.bestLagImprovementFraction, agentDtw.dtwMse, ...
    100*agentDtw.dtwReductionFraction, agentDtw.meanAbsLagSteps);
lines(end+1) = sprintf( ...
    "- P: MSE extremo %.9f; mejor lag %+d (%.3f s), " + ...
    "mejora %.3f%%; DTW %.9f, mejora %.3f%%, lag absoluto " + ...
    "medio %.6f pasos.", pDiscrete.zeroLagMse, ...
    pDiscrete.bestMseLagSteps, pDiscrete.bestMseLagSec, ...
    100*pDiscrete.bestLagImprovementFraction, pDtw.dtwMse, ...
    100*pDtw.dtwReductionFraction, pDtw.meanAbsLagSteps);
lines(end+1) = "- Clasificación primaria: " + decision.classification + ".";
lines(end+1) = "- Recomendación: " + decision.recommendation;
lines(end+1) = "";
lines(end+1) = "## Reposo";
lines(end+1) = "";
restLines = strings(height(rest.dtwSummary), 1);
for rowIdx = 1:height(rest.dtwSummary)
    row = rest.dtwSummary(rowIdx, :);
    restLines(rowIdx) = sprintf( ...
        "- %s: endpoint %.9f; DTW %.9f; mejora %.3f%%.", ...
        row.commandSource, row.endpointMse, row.dtwMse, ...
        100*row.dtwReductionFraction);
end
lines = vertcat(lines(:), restLines);
lines(end+1) = "";
lines(end+1) = sprintf( ...
    "Costo offline: aceptación %.6f s; reposo %.6f s.", ...
    acceptanceElapsedSec, restElapsedSec);
lines(end+1) = "";
lines(end+1) = "El error de extremo se conserva; DTW no entró en reward.";
lines(end+1) = "Ruta: `" + string(runDir) + "`.";
writeText(pathValue, strjoin(lines, newline));
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[workingStatus, ~] = system(sprintf('git -C "%s" diff --quiet', repoRoot));
[indexStatus, ~] = system(sprintf('git -C "%s" diff --cached --quiet', repoRoot));
trackedDirty = workingStatus ~= 0 || indexStatus ~= 0;
end

function hash = fileSha256(filePath)
escapedPath = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escapedPath);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7_offline_temporal_analysis:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = upper(string(strtrim(output)));
end

function escaped = escape(value)
escaped = strrep(char(string(value)), "'", "''");
end

function writeText(filePath, value)
fid = fopen(filePath, "w");
if fid < 0
    error("run_no_glove_stage7_offline_temporal_analysis:WriteFailed", ...
        "Could not open %s.", filePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
