function report = run_no_glove_stage7i_hold_support_audit(options)
%run_no_glove_stage7i_hold_support_audit audits frozen 7H logs offline.
%
% The launcher reconstructs the causal hold condition from state_t, maps
% steady-rest coverage against far-correction exposure and audits temporal
% exits from the hold region. It never loads an agent, creates Env, invokes
% the simulator/reward, trains, calculates DTW or accesses hardware.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7i_hold_support_audit");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7i_hold_support_audit:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testResults = runtests(fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage7iHoldSupport.m"));
save(fullfile(runRoot, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7i_hold_support_audit:TestsFailed", ...
        "ETAPA 7I tests failed. See %s.", runRoot);
end

[stage7h, child, profiles, sourceAudit] = loadAndValidateInputs( ...
    options.stage7hRunRoot);
inputHashesBefore = inventoryEpisodeInputs(child);
validateEpisodeInventory(inputHashesBefore);
controlSettings = holdSettings(profiles.control);
candidateSettings = holdSettings(profiles.candidate);
[controlWindows, controlEpisodes] = ...
    loadNoGloveStage7iHoldSupportCorpus("control", ...
        episodeDirectories(child.control), controlSettings);
[candidateWindows, candidateEpisodes] = ...
    loadNoGloveStage7iHoldSupportCorpus("candidate", ...
        episodeDirectories(child.candidate), candidateSettings);
windows = [controlWindows; candidateWindows];
episodeAudit = [controlEpisodes; candidateEpisodes];
analysis = analyzeNoGloveStage7iHoldSupport(windows);

inputHashesAfter = inventoryEpisodeInputs(child);
if ~isequal(inputHashesBefore, inputHashesAfter)
    error("run_no_glove_stage7i_hold_support_audit:InputModified", ...
        "A source episode changed during the offline audit.");
end
sourceHashesAfter = hashSourceFiles(options.stage7hRunRoot, child);
if ~isequal(sourceAudit.sourceHashesBefore, sourceHashesAfter)
    error("run_no_glove_stage7i_hold_support_audit:SourceModified", ...
        "A source manifest, profile or checkpoint changed.");
end

profileAudit = buildProfileAudit(profiles);
writetable(inputHashesBefore, ...
    fullfile(runRoot, "episode_input_hashes.csv"));
writetable(episodeAudit, fullfile(runRoot, "episode_audit.csv"));
writetable(profileAudit, fullfile(runRoot, "profile_audit.csv"));
writetable(windows, fullfile(runRoot, "window_corpus.csv"));
writetable(analysis.episodeTimeline, ...
    fullfile(runRoot, "rest_episode_timeline.csv"));
writetable(analysis.exitAudit, ...
    fullfile(runRoot, "rest_exit_audit.csv"));
writetable(analysis.timelineSummary, ...
    fullfile(runRoot, "timeline_summary.csv"));
writetable(analysis.stratumSummary, ...
    fullfile(runRoot, "stratum_summary.csv"));
writetable(analysis.epsilonCurve, ...
    fullfile(runRoot, "epsilon_curve.csv"));
writetable(analysis.supportDecision, ...
    fullfile(runRoot, "support_decision.csv"));
writetable(analysis.softGateSummary, ...
    fullfile(runRoot, "soft_gate_summary.csv"));
writetable(analysis.sourceDecision, ...
    fullfile(runRoot, "source_decision.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct("stage", "7I", "schemaVersion", 1, ...
    "result", "PASS", "scientificResult", analysis.classification, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7i_hold_support_audit", ...
    "preregistrationCommit", ...
        "52c454758a9a3c942fcf7148e65d5ed9c16a5bd3", ...
    "stage7hRunRoot", options.stage7hRunRoot, ...
    "stage7hManifestSha256", sourceAudit.stage7hManifestSha256, ...
    "controlRunRoot", child.control.runRoot, ...
    "candidateRunRoot", child.candidate.runRoot, ...
    "controlManifestSha256", sourceAudit.controlManifestSha256, ...
    "candidateManifestSha256", sourceAudit.candidateManifestSha256, ...
    "controlCheckpointSha256", sourceAudit.controlCheckpointSha256, ...
    "candidateCheckpointSha256", ...
        sourceAudit.candidateCheckpointSha256, ...
    "episodeInputCount", height(inputHashesBefore), ...
    "episodeInputsPreserved", true, ...
    "episodeCount", height(episodeAudit), ...
    "windowCount", height(windows), ...
    "maximumDiagnosticReplayError", ...
        max(episodeAudit.maximumDiagnosticReplayError), ...
    "profileAudit", table2struct(profileAudit), ...
    "thresholds", analysis.thresholds, ...
    "supportDecision", table2struct(analysis.supportDecision), ...
    "sourceDecision", table2struct(analysis.sourceDecision), ...
    "rootCauseIdentified", false, ...
    "behavioralInterventionExecuted", false, ...
    "referenceSource", "emgIntent", ...
    "observationVariant", "intentMarkov60", ...
    "actionInterfaceVariant", "baselineQuantized", ...
    "policyChanged", false, "quantizationChanged", false, ...
    "rewardChanged", false, "referenceChanged", false, ...
    "simulatorChanged", false, "safetyLayerChanged", false, ...
    "runTraining", false, "newTraining", false, ...
    "agentLoaded", false, "envCreated", false, ...
    "simulatorInvoked", false, "rewardFunctionInvoked", false, ...
    "dtwCalculated", false, "hardwareUsed", false, ...
    "simMotors", true, "pilotAuthorized", false, ...
    "longCampaignAuthorized", false, ...
    "agent7250Loaded", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);
save(fullfile(runRoot, "stage7i_results.mat"), "manifest", ...
    "analysis", "windows", "episodeAudit", "inputHashesBefore", ...
    "profileAudit", "stage7h", "sourceAudit", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest, analysis));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "outputPath", runRoot, "manifest", manifest, ...
    "analysis", analysis);
fprintf("ETAPA 7I HOLD SUPPORT AUDIT PASS\n");
fprintf("Scientific result: %s\n", analysis.classification);
fprintf("Output: %s\n", runRoot);
disp(analysis.supportDecision);
disp(analysis.sourceDecision);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7i_hold_support_audit:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct("resultsRoot", "", "stage7hRunRoot", ...
    "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7h_artifacts\" + ...
    "stage7h_final\2026-08-28_16-00-33-357");
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7i_hold_support_audit:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.stage7hRunRoot = string(options.stage7hRunRoot);
if ~isfile(fullfile(options.stage7hRunRoot, "manifest.json"))
    error("run_no_glove_stage7i_hold_support_audit:MissingStage7h", ...
        "ETAPA 7H manifest not found under %s.", options.stage7hRunRoot);
end
end

function [stage7h, child, profiles, audit] = loadAndValidateInputs(root)
manifestPath = fullfile(root, "manifest.json");
stage7h = jsondecode(fileread(manifestPath));
if string(stage7h.stage) ~= "7H" || string(stage7h.result) ~= "PASS" || ...
        string(stage7h.scientificResult) ~= "holdExposureInsufficient" || ...
        logical(stage7h.hardwareUsed) || logical(stage7h.pilotAuthorized) || ...
        string(stage7h.referenceSource) ~= "emgIntent" || ...
        string(stage7h.observationVariant) ~= "intentMarkov60" || ...
        string(stage7h.rewardType) ~= "trackingIntentHoldActionReward" || ...
        string(stage7h.actionInterfaceVariant) ~= "baselineQuantized"
    error("run_no_glove_stage7i_hold_support_audit:Stage7hContract", ...
        "Input manifest is not the frozen ETAPA 7H result.");
end
control = loadChild(string(stage7h.controlRunRoot), 0.00);
candidate = loadChild(string(stage7h.candidateRunRoot), 0.20);
child = struct("control", control, "candidate", candidate);
controlData = load(fullfile(control.runRoot, "seed_11", ...
    "effective_training_profile.mat"), "profile");
candidateData = load(fullfile(candidate.runRoot, "seed_11", ...
    "effective_training_profile.mat"), "profile");
profiles = struct("control", controlData.profile, ...
    "candidate", candidateData.profile);
validateProfiles(profiles);
sourceHashes = hashSourceFiles(root, child);
audit = struct("stage7hManifestSha256", sourceHashes.sha256(1), ...
    "controlManifestSha256", sourceHashes.sha256(2), ...
    "candidateManifestSha256", sourceHashes.sha256(3), ...
    "controlCheckpointSha256", sourceHashes.sha256(6), ...
    "candidateCheckpointSha256", sourceHashes.sha256(7), ...
    "sourceHashesBefore", sourceHashes);
end

function child = loadChild(root, expectedHoldWeight)
manifestPath = fullfile(root, "manifest.json");
if ~isfile(manifestPath)
    error("run_no_glove_stage7i_hold_support_audit:ChildManifest", ...
        "Missing child manifest under %s.", root);
end
m = jsondecode(fileread(manifestPath));
if string(m.stage) ~= "6" || string(m.phase) ~= "smoke" || ...
        double(m.episodeBudget) ~= 200 || ~isequal(double(m.seeds), 11) || ...
        ~logical(m.newTraining) || logical(m.agent7250Loaded) || ...
        logical(m.hardwareUsed) || ~logical(m.simMotors) || ...
        string(m.referenceSource) ~= "emgIntent" || ...
        string(m.observationVariant) ~= "intentMarkov60" || ...
        string(m.rewardType) ~= "trackingIntentHoldActionReward" || ...
        string(m.actionInterfaceVariant) ~= "baselineQuantized" || ...
        double(m.intentHoldActionWeight) ~= expectedHoldWeight
    error("run_no_glove_stage7i_hold_support_audit:ChildContract", ...
        "A 7H child run violates the frozen smoke contract.");
end
seed = m.seedSummary;
child = struct("runRoot", root, "manifest", m, ...
    "trainingDirectory", string(seed.trainingDirectory), ...
    "acceptanceDirectory", string(seed.acceptanceDirectory), ...
    "restDirectory", string(seed.restDirectory), ...
    "finalCheckpoint", string(seed.finalCheckpoint));
required = [child.trainingDirectory; child.acceptanceDirectory; ...
    child.restDirectory; child.finalCheckpoint];
if ~all([isfolder(required(1:3)); isfile(required(4))])
    error("run_no_glove_stage7i_hold_support_audit:ChildArtifacts", ...
        "A frozen child artifact is missing.");
end
end

function validateProfiles(profiles)
c = profiles.control;
k = profiles.candidate;
valid = c.intentHoldActionWeight == 0 && ...
    k.intentHoldActionWeight == 0.20 && ...
    c.intentHoldRewardEnabled && k.intentHoldRewardEnabled && ...
    c.intentHoldVelocityTolerance == 1e-12 && ...
    k.intentHoldVelocityTolerance == 1e-12 && ...
    c.intentHoldPositionMseTolerance == 1e-4 && ...
    k.intentHoldPositionMseTolerance == 1e-4 && ...
    c.intentRewardActionWeight == 0.05 && ...
    k.intentRewardActionWeight == 0.05 && ...
    string(c.observationVariant) == "intentMarkov60" && ...
    string(k.observationVariant) == "intentMarkov60" && ...
    logical(c.simMotors) && logical(k.simMotors);
if ~valid
    error("run_no_glove_stage7i_hold_support_audit:ProfileContract", ...
        "Effective profiles violate the pre-registered 7I contract.");
end
end

function value = holdSettings(profile)
value = struct("holdActionWeight", ...
    double(profile.intentHoldActionWeight), ...
    "velocityTolerance", double(profile.intentHoldVelocityTolerance), ...
    "positionMseTolerance", ...
        double(profile.intentHoldPositionMseTolerance));
end

function value = episodeDirectories(child)
value = struct("training", child.trainingDirectory, ...
    "acceptance", child.acceptanceDirectory, ...
    "steadyRest", child.restDirectory);
end

function tableValue = buildProfileAudit(profiles)
tableValue = table(["control"; "candidate"], [0; 0.20], ...
    [profiles.control.intentRewardActionWeight; ...
        profiles.candidate.intentRewardActionWeight], ...
    [profiles.control.intentHoldVelocityTolerance; ...
        profiles.candidate.intentHoldVelocityTolerance], ...
    [profiles.control.intentHoldPositionMseTolerance; ...
        profiles.candidate.intentHoldPositionMseTolerance], ...
    [string(profiles.control.observationVariant); ...
        string(profiles.candidate.observationVariant)], ...
    [string(profiles.control.actionInterfaceVariant); ...
        string(profiles.candidate.actionInterfaceVariant)], ...
    [logical(profiles.control.simMotors); ...
        logical(profiles.candidate.simMotors)], ...
    'VariableNames', ["variant", "holdActionWeight", ...
    "actionWeight", "holdVelocityTolerance", ...
    "holdPositionMseTolerance", "observationVariant", ...
    "actionInterfaceVariant", "simMotors"]);
end

function hashes = hashSourceFiles(stage7hRoot, child)
paths = [fullfile(stage7hRoot, "manifest.json"); ...
    fullfile(child.control.runRoot, "manifest.json"); ...
    fullfile(child.candidate.runRoot, "manifest.json"); ...
    fullfile(child.control.runRoot, "seed_11", ...
        "effective_training_profile.mat"); ...
    fullfile(child.candidate.runRoot, "seed_11", ...
        "effective_training_profile.mat"); ...
    child.control.finalCheckpoint; child.candidate.finalCheckpoint];
labels = ["stage7hManifest"; "controlManifest"; ...
    "candidateManifest"; "controlProfile"; "candidateProfile"; ...
    "controlAgent200"; "candidateAgent200"];
sha256 = strings(numel(paths), 1);
for idx = 1:numel(paths)
    sha256(idx) = fileSha256(paths(idx));
end
hashes = table(labels, paths, sha256);
end

function tableValue = inventoryEpisodeInputs(child)
parts = cell(6, 1);
variants = ["control", "candidate"];
sources = ["training", "acceptance", "steadyRest"];
cursor = 0;
for variant = variants
    for source = sources
        cursor = cursor+1;
        directory = episodeDirectories(child.(variant));
        parts{cursor} = hashEpisodeDirectory(variant, source, ...
            directory.(source));
    end
end
tableValue = vertcat(parts{:});
end

function tableValue = hashEpisodeDirectory(variant, source, directory)
files = dir(fullfile(directory, "episode*.mat"));
[~, order] = sort({files.name});
files = files(order);
episode = zeros(numel(files), 1);
path = strings(numel(files), 1);
sha256 = strings(numel(files), 1);
bytes = zeros(numel(files), 1);
for idx = 1:numel(files)
    token = regexp(files(idx).name, '^episode(\d+)\.mat$', ...
        'tokens', 'once');
    episode(idx) = str2double(token{1});
    path(idx) = string(fullfile(files(idx).folder, files(idx).name));
    sha256(idx) = fileSha256(path(idx));
    bytes(idx) = files(idx).bytes;
end
tableValue = table(repmat(variant, numel(files), 1), ...
    repmat(source, numel(files), 1), episode, path, sha256, bytes, ...
    'VariableNames', ["variant", "source", "episode", "path", ...
    "sha256", "bytes"]);
end

function validateEpisodeInventory(audit)
expected = table( ...
    ["control"; "control"; "control"; ...
        "candidate"; "candidate"; "candidate"], ...
    ["training"; "acceptance"; "steadyRest"; ...
        "training"; "acceptance"; "steadyRest"], ...
    [200; 50; 24; 200; 50; 24], ...
    'VariableNames', ["variant", "source", "episodeCount"]);
for idx = 1:height(expected)
    rows = audit.variant == expected.variant(idx) & ...
        audit.source == expected.source(idx);
    if sum(rows) ~= expected.episodeCount(idx)
        error("run_no_glove_stage7i_hold_support_audit:EpisodeInventory", ...
            "Unexpected %s/%s episode inventory.", ...
            expected.variant(idx), expected.source(idx));
    end
end
if height(audit) ~= 548
    error("run_no_glove_stage7i_hold_support_audit:EpisodeInventory", ...
        "Expected exactly 548 frozen episode files.");
end
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf("cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7i_hold_support_audit(struct(" + ...
    "'resultsRoot','%s','stage7hRunRoot','%s'))", ...
    escapeQuote(matlabRoot), escapeQuote(string(fileparts(runRoot))), ...
    escapeQuote(options.stage7hRunRoot));
end

function value = buildOfflineReport(manifest, analysis)
d = manifest.sourceDecision;
candidate = analysis.supportDecision( ...
    analysis.supportDecision.variant == "candidate", :);
lines = ["# ETAPA 7I - offline hold-support audit"; ""; ...
    "- Engineering result: PASS."; ...
    "- Scientific result: " + manifest.scientificResult + "."; ...
    sprintf("- Current rest coverage: %.9f.", ...
        candidate.currentRestCoverage); ...
    sprintf("- Current far-correction exposure: %.9f.", ...
        candidate.currentFarCorrectionExposure); ...
    "- Feasible exact threshold exists: " + ...
        string(d.feasibleThresholdExists) + "."; ...
    sprintf("- Minimum rest-only epsilon_q2: %.17g.", ...
        d.minimumRestOnlyPositionMseTolerance); ...
    sprintf("- Far exposure there: %.9f.", ...
        d.farCorrectionExposureAtRestThreshold); ...
    "- Root cause identified: no; the result is an offline support classification."; ...
    "- Training/simulation/agent/Env/reward/DTW/hardware: no/no/no/no/no/no/no."];
value = strjoin(lines, newline);
end

function hashes = inventoryArtifacts(runRoot)
names = ["test_results.mat", "episode_input_hashes.csv", ...
    "episode_audit.csv", "profile_audit.csv", "window_corpus.csv", ...
    "rest_episode_timeline.csv", "rest_exit_audit.csv", ...
    "timeline_summary.csv", "stratum_summary.csv", ...
    "epsilon_curve.csv", "support_decision.csv", ...
    "soft_gate_summary.csv", "source_decision.csv", ...
    "stage7i_results.mat", "offline_report.md", ...
    "reproducible_command.txt"];
hashes = repmat(struct("path", "", "sha256", ""), numel(names), 1);
for idx = 1:numel(names)
    hashes(idx).path = names(idx);
    hashes(idx).sha256 = fileSha256(fullfile(runRoot, names(idx)));
end
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
commit = "unknown";
if status == 0
    commit = string(strtrim(output));
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[trackedStatus, trackedOutput] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = trackedStatus ~= 0 || ...
    strlength(strtrim(string(trackedOutput))) > 0;
end

function hash = fileSha256(path)
fid = fopen(path, "r");
if fid < 0
    error("run_no_glove_stage7i_hold_support_audit:HashFailed", ...
        "Could not open %s for hashing.", path);
end
cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid, Inf, "*uint8");
digest = java.security.MessageDigest.getInstance("SHA-256");
digest.update(bytes);
digestBytes = typecast(digest.digest(), "uint8");
hash = upper(string(reshape(dec2hex(digestBytes, 2)', 1, [])));
end

function value = escapeQuote(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7i_hold_support_audit:WriteFailed", ...
        "Could not open %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
