function report = run_no_glove_stage7b_designed_excitation(options)
%run_no_glove_stage7b_designed_excitation executes ETAPA 7B only.
%
% A frozen Agent200 and the validated P controller receive matched designed
% EMG-intent reference profiles in simulation. No training, Agent7250, DTW,
% hardware or behavioral configuration change is permitted.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
addpath(genpath(fullfile(matlabRoot, "tests")));
clearConfigurablesOverride();

[stage7aManifest, stage7aManifestPath, stage7aResultsPath] = ...
    loadAndValidateStage7a(options.stage7aRunRoot);
[stage6Manifest, stage6ManifestPath, agentPath, agentExpectedHash, ...
    trainingProfile] = loadAndValidateStage6(options.stage6RunRoot);
stage7aHashBefore = fileSha256(stage7aResultsPath);
stage6ManifestHashBefore = fileSha256(stage6ManifestPath);
agentHashBefore = fileSha256(agentPath);
if agentHashBefore ~= agentExpectedHash
    error("run_no_glove_stage7b_designed_excitation:AgentHashMismatch", ...
        "Agent200 does not match the ETAPA 6 inventory.");
end

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7b_designed_excitation");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runDir)
    error("run_no_glove_stage7b_designed_excitation:OutputExists", ...
        "Refusing to reuse output directory %s.", runDir);
end
mkdir(runDir);

testPath = fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage7bDesignedExcitation.m");
testResults = runtests(testPath);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7b_designed_excitation:TestsFailed", ...
        "ETAPA 7B tests failed; simulation is forbidden. See %s.", runDir);
end

corpus = buildNoGloveStage7bTemporalCorpus( ...
    trainingProfile.intentCalibration, ...
    trainingProfile.intentExpectedContext, ...
    "calibrationSeed", options.calibrationSeed, ...
    "profileSeed", options.profileSeed, ...
    "repetitionsPerAxis", options.repetitionsPerAxis);
fixtureDir = fullfile(runDir, "fixture");
mkdir(fixtureDir);
fullDatasetPath = fullfile(fixtureDir, ...
    "stage7b_designed_temporal_emg_only.mat");
smokeDatasetPath = fullfile(fixtureDir, ...
    "stage7b_smoke_temporal_emg_only.mat");
writeDataset(fullDatasetPath, corpus.emgs, corpus.metadata);
smokeMetadata = corpus.metadata;
smokeMetadata.role = "designed_temporal_smoke";
smokeMetadata.profileCount = 2;
writeDataset(smokeDatasetPath, corpus.emgs(1, :), smokeMetadata);
writetable(corpus.protocolTable, fullfile(runDir, "profile_protocol.csv"));
writetable(corpus.validationTable, ...
    fullfile(runDir, "profile_validation.csv"));
writetable(corpus.windowProtocol, ...
    fullfile(runDir, "window_protocol.csv"));

matchedProfile = buildMatchedProfile(trainingProfile);
smokeProfile = buildEvaluationProfile(trainingProfile, agentPath, ...
    smokeDatasetPath, options.smokeSeed, 2, ...
    fullfile(runDir, "smoke", "agent200"));
assertSafeEvaluationProfile(smokeProfile, agentPath, 2);
save(fullfile(runDir, "effective_smoke_profile.mat"), "smokeProfile");
smokeAgentDir = runAgentEvaluation(smokeProfile);
smokeMatched = evaluateNoGloveStage6cMatchedController( ...
    smokeAgentDir, matchedProfile, "designed_temporal_smoke", ...
    "activeVelocityThreshold", options.activeVelocityThreshold, ...
    "motionTolerance", options.motionTolerance, ...
    "positionTolerance", options.positionTolerance, ...
    "saturationThreshold", options.saturationThreshold, ...
    "simulatorSamplingPeriod", options.simulatorSamplingPeriod);
if ~smokeMatched.pairing.allExact || ...
        any(smokeMatched.componentTable.positionViolation) || ...
        height(smokeMatched.pairingTable) ~= 2
    error("run_no_glove_stage7b_designed_excitation:SmokeFailed", ...
        "The two-episode designed smoke failed pairing or safety.");
end
smokeEpisodeHashes = inventoryEpisodes(smokeAgentDir);
writetable(smokeEpisodeHashes, ...
    fullfile(runDir, "smoke_episode_hashes.csv"));

evaluationProfile = buildEvaluationProfile(trainingProfile, agentPath, ...
    fullDatasetPath, options.evaluationSeed, ...
    corpus.expectedSimulationCount, ...
    fullfile(runDir, "evaluation", "agent200"));
assertSafeEvaluationProfile(evaluationProfile, agentPath, ...
    corpus.expectedSimulationCount);
save(fullfile(runDir, "effective_evaluation_profile.mat"), ...
    "evaluationProfile", "matchedProfile", "options");
evaluationTic = tic;
agentEvaluationDir = runAgentEvaluation(evaluationProfile);
agentEvaluationElapsedSec = toc(evaluationTic);
agentEpisodeHashes = inventoryEpisodes(agentEvaluationDir);
if height(agentEpisodeHashes) ~= corpus.expectedSimulationCount
    error("run_no_glove_stage7b_designed_excitation:EpisodeCountMismatch", ...
        "Expected %d frozen-agent episodes, found %d.", ...
        corpus.expectedSimulationCount, height(agentEpisodeHashes));
end
writetable(agentEpisodeHashes, ...
    fullfile(runDir, "agent_episode_hashes.csv"));

matchedTic = tic;
matched = evaluateNoGloveStage6cMatchedController( ...
    agentEvaluationDir, matchedProfile, "designed_temporal", ...
    "activeVelocityThreshold", options.activeVelocityThreshold, ...
    "motionTolerance", options.motionTolerance, ...
    "positionTolerance", options.positionTolerance, ...
    "saturationThreshold", options.saturationThreshold, ...
    "simulatorSamplingPeriod", options.simulatorSamplingPeriod);
matchedElapsedSec = toc(matchedTic);
if ~matched.pairing.allExact || any(matched.componentTable.positionViolation)
    error("run_no_glove_stage7b_designed_excitation:PairingFailed", ...
        "Full Agent200/P matching or position safety failed.");
end

analysisOptions = struct( ...
    "targetMotors", options.targetMotors, ...
    "maxLagSteps", options.maxLagSteps, ...
    "activeVelocityThreshold", options.activeVelocityThreshold, ...
    "motionVelocityThreshold", options.motionVelocityThreshold, ...
    "offsetHoldSteps", options.offsetHoldSteps, ...
    "minimumSamplesPerFold", options.minimumSamplesPerFold, ...
    "minimumBenefitFraction", options.minimumBenefitFraction, ...
    "minimumMaterialFoldFraction", ...
        options.minimumMaterialFoldFraction, ...
    "minimumSignConsistency", options.minimumSignConsistency, ...
    "maximumBoundaryFraction", options.maximumBoundaryFraction, ...
    "minimumFiniteOnsetFraction", ...
        options.minimumFiniteOnsetFraction, ...
    "periodSec", options.periodSec);
analysisArguments = namedargs2cell(analysisOptions);
analysisTic = tic;
analysis = analyzeNoGloveStage7bDesignedResponse( ...
    matched.componentTable, matched.pairingTable, ...
    corpus.protocolTable, "designed_temporal", analysisArguments{:});
analysisElapsedSec = toc(analysisTic);

writeAnalysisTables(runDir, matched, analysis);
causalCompensationGatePassed = ...
    logical(analysis.primaryDecision.causalCompensationCandidate);
compensationInterventionExecuted = false;
filteredReferenceInterventionExecuted = false;
dtwCalculated = false;
stage8Authorized = false;
save(fullfile(runDir, "stage7b_results.mat"), ...
    "corpus", "matched", "analysis", "analysisOptions", ...
    "causalCompensationGatePassed", ...
    "compensationInterventionExecuted", ...
    "filteredReferenceInterventionExecuted", "dtwCalculated", ...
    "stage8Authorized", "stage7aManifest", "stage6Manifest", ...
    "agentEvaluationElapsedSec", "matchedElapsedSec", ...
    "analysisElapsedSec", "-v7.3");

stage7aHashAfter = fileSha256(stage7aResultsPath);
stage6ManifestHashAfter = fileSha256(stage6ManifestPath);
agentHashAfter = fileSha256(agentPath);
if stage7aHashAfter ~= stage7aHashBefore || ...
        stage6ManifestHashAfter ~= stage6ManifestHashBefore || ...
        agentHashAfter ~= agentHashBefore
    error("run_no_glove_stage7b_designed_excitation:InputModified", ...
        "An immutable input or Agent200 changed during ETAPA 7B.");
end

reproducibleCommand = buildReproducibleCommand( ...
    matlabRoot, options, fileparts(runDir));
writeText(fullfile(runDir, "reproducible_command.txt"), ...
    reproducibleCommand);
writeOfflineReport(fullfile(runDir, "offline_report.md"), ...
    analysis, matched, corpus, options, ...
    agentEvaluationElapsedSec, matchedElapsedSec, ...
    analysisElapsedSec, runDir);

primaryArtifacts = ["profile_protocol.csv", "profile_validation.csv", ...
    "window_protocol.csv", "smoke_episode_hashes.csv", ...
    "agent_episode_hashes.csv", "pairing.csv", ...
    "episode_summary.csv", "motor_summary.csv", ...
    "aggregate_summary.csv", "lag_confirmation_summary.csv", ...
    "held_out_fold_evaluation.csv", "event_latency.csv", ...
    "event_latency_summary.csv", "designed_gate.csv", ...
    "source_decision.csv", "stage7b_results.mat", ...
    "test_results.mat", "effective_smoke_profile.mat", ...
    "effective_evaluation_profile.mat", ...
    "reproducible_command.txt", "offline_report.md", ...
    "fixture/stage7b_designed_temporal_emg_only.mat", ...
    "fixture/stage7b_smoke_temporal_emg_only.mat"];
artifactHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(primaryArtifacts), 1);
for artifactIdx = 1:numel(primaryArtifacts)
    artifactHashes(artifactIdx).path = primaryArtifacts(artifactIdx);
    artifactHashes(artifactIdx).sha256 = fileSha256( ...
        fullfile(runDir, primaryArtifacts(artifactIdx)));
end
writetable(struct2table(artifactHashes), ...
    fullfile(runDir, "artifact_hashes.csv"));

[gitCommit, gitDirty, trackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", "7B", "schemaVersion", 1, "result", "PASS", ...
    "scientificGateResult", ...
        string(analysis.primaryDecision.classification), ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", trackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7b_designed_excitation", ...
    "inputStage7aRunRoot", options.stage7aRunRoot, ...
    "inputStage7aManifestPath", stage7aManifestPath, ...
    "inputStage7aManifestSha256", fileSha256(stage7aManifestPath), ...
    "inputStage7aResultsPath", stage7aResultsPath, ...
    "inputStage7aResultsSha256Before", stage7aHashBefore, ...
    "inputStage7aResultsSha256After", stage7aHashAfter, ...
    "inputStage6RunRoot", options.stage6RunRoot, ...
    "inputStage6ManifestPath", stage6ManifestPath, ...
    "inputStage6ManifestSha256Before", stage6ManifestHashBefore, ...
    "inputStage6ManifestSha256After", stage6ManifestHashAfter, ...
    "inputsPreserved", true, ...
    "agentCheckpointPath", agentPath, ...
    "agentCheckpointLabel", "Agent200", ...
    "agentCheckpointSha256Before", agentHashBefore, ...
    "agentCheckpointSha256After", agentHashAfter, ...
    "agentCheckpointPreserved", agentHashBefore == agentHashAfter, ...
    "agentFrozen", true, "newTraining", false, ...
    "checkpointLoadedForTraining", false, ...
    "calibrationSeed", options.calibrationSeed, ...
    "profileSeed", options.profileSeed, ...
    "smokeSeed", options.smokeSeed, ...
    "evaluationSeed", options.evaluationSeed, ...
    "fixtureVersion", corpus.fixtureVersion, ...
    "calibrationContentSha256", corpus.calibrationContentSha256, ...
    "profileCount", height(corpus.protocolTable), ...
    "repetitionCount", size(corpus.emgs, 1), ...
    "smokeSimulationCount", 2, ...
    "evaluationSimulationCount", corpus.expectedSimulationCount, ...
    "analysisOptions", analysisOptions, ...
    "exactPairing", matched.pairing.allExact, ...
    "positionViolationCount", sum(matched.componentTable.positionViolation), ...
    "primaryCommandSource", "Agent200", ...
    "primaryClassification", analysis.primaryDecision.classification, ...
    "primaryCausalCandidateCount", ...
        analysis.primaryDecision.causalCandidateCount, ...
    "primaryUnresolvedCount", analysis.primaryDecision.unresolvedCount, ...
    "primaryRejectedCount", analysis.primaryDecision.rejectedCount, ...
    "causalCompensationGatePassed", causalCompensationGatePassed, ...
    "compensationInterventionExecuted", ...
        compensationInterventionExecuted, ...
    "filteredReferenceInterventionExecuted", ...
        filteredReferenceInterventionExecuted, ...
    "dtwCalculated", dtwCalculated, "dtwRewardUsed", false, ...
    "stage8Authorized", stage8Authorized, ...
    "designedEvaluationDataset", true, ...
    "evaluationReferenceProfilesChanged", true, ...
    "referenceGeneratorChanged", false, "stateChanged", false, ...
    "rewardChanged", false, "policyChanged", false, ...
    "quantizationChanged", false, "simulatorChanged", false, ...
    "safetyLayerChanged", false, "conventionalControllerChanged", false, ...
    "simMotors", true, "runTraining", false, ...
    "agentLoaded", true, "agentEvaluationOnly", true, ...
    "reinforcementLearningInvoked", true, ...
    "reinforcementLearningTrainingInvoked", false, ...
    "envCreated", true, "simulatorInvoked", true, ...
    "rewardInvokedUnchanged", true, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "agent7250Loaded", false, "hardwareUsed", false, ...
    "agentEvaluationElapsedSec", agentEvaluationElapsedSec, ...
    "matchedElapsedSec", matchedElapsedSec, ...
    "analysisElapsedSec", analysisElapsedSec, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "artifactHashes", artifactHashes, "outputPath", runDir);
save(fullfile(runDir, "manifest.mat"), "manifest", "artifactHashes");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", "outputPath", runDir, ...
    "manifest", manifest, "analysis", analysis, "matched", matched, ...
    "corpus", corpus, "testResults", testResults);
fprintf("ETAPA 7B DESIGNED EXCITATION PASS\n");
fprintf("Output: %s\n", runDir);
disp(analysis.designedGateTable);
disp(analysis.sourceDecision);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7b_designed_excitation:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct("stage7aRunRoot", "", "stage6RunRoot", "", ...
    "resultsRoot", "", "calibrationSeed", 11, "profileSeed", 7701, ...
    "smokeSeed", 7702, "evaluationSeed", 7703, ...
    "repetitionsPerAxis", 4, "targetMotors", [2 3], ...
    "maxLagSteps", 5, "activeVelocityThreshold", 0.005, ...
    "motionVelocityThreshold", 0.001, "offsetHoldSteps", 2, ...
    "minimumSamplesPerFold", 10, "minimumBenefitFraction", 0.05, ...
    "minimumMaterialFoldFraction", 0.75, ...
    "minimumSignConsistency", 0.75, ...
    "maximumBoundaryFraction", 0.25, ...
    "minimumFiniteOnsetFraction", 1.0, "periodSec", 0.2, ...
    "motionTolerance", 1e-4, "positionTolerance", 1e-9, ...
    "saturationThreshold", 0.95, "simulatorSamplingPeriod", 0.14);
unknown = setdiff(string(fieldnames(options)), ...
    string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7b_designed_excitation:UnknownOption", ...
        "Unknown option(s): %s.", strjoin(unknown, ", "));
end
fields = fieldnames(defaults);
for fieldIdx = 1:numel(fields)
    name = fields{fieldIdx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.stage7aRunRoot = string(options.stage7aRunRoot);
options.stage6RunRoot = string(options.stage6RunRoot);
options.resultsRoot = string(options.resultsRoot);
if strlength(options.stage7aRunRoot) == 0 || ...
        strlength(options.stage6RunRoot) == 0
    error("run_no_glove_stage7b_designed_excitation:MissingInput", ...
        "stage7aRunRoot and stage6RunRoot are required.");
end
integerFields = ["calibrationSeed", "profileSeed", "smokeSeed", ...
    "evaluationSeed", "repetitionsPerAxis", "maxLagSteps", ...
    "offsetHoldSteps", "minimumSamplesPerFold"];
for fieldIdx = 1:numel(integerFields)
    name = integerFields(fieldIdx);
    value = options.(name);
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
            value < 0 || fix(value) ~= value
        error("run_no_glove_stage7b_designed_excitation:InvalidOption", ...
            "%s must be a nonnegative integer.", name);
    end
end
if options.repetitionsPerAxis < 3 || options.maxLagSteps < 1 || ...
        options.offsetHoldSteps < 1 || options.minimumSamplesPerFold < 1
    error("run_no_glove_stage7b_designed_excitation:InvalidOption", ...
        "Fold, lag, hold and sample counts are too small.");
end
end

function [manifest, manifestPath, resultsPath] = ...
        loadAndValidateStage7a(runRoot)
manifestPath = fullfile(runRoot, "manifest.json");
resultsPath = fullfile(runRoot, "stage7a_results.mat");
if ~isfile(manifestPath) || ~isfile(resultsPath)
    error("run_no_glove_stage7b_designed_excitation:Stage7aNotFound", ...
        "ETAPA 7A manifest/results are missing.");
end
manifest = jsondecode(fileread(manifestPath));
required = ["stage", "result", "causalCompensationGatePassed", ...
    "compensationInterventionExecuted", ...
    "filteredReferenceInterventionExecuted", "dtwCalculated", ...
    "stage8Authorized", "hardwareUsed", "artifactHashes"];
if ~all(isfield(manifest, cellstr(required)))
    error("run_no_glove_stage7b_designed_excitation:InvalidStage7a", ...
        "ETAPA 7A manifest contract is incomplete.");
end
valid = string(manifest.stage) == "7A" && ...
    string(manifest.result) == "PASS" && ...
    ~logical(manifest.causalCompensationGatePassed) && ...
    ~logical(manifest.compensationInterventionExecuted) && ...
    ~logical(manifest.filteredReferenceInterventionExecuted) && ...
    ~logical(manifest.dtwCalculated) && ~logical(manifest.stage8Authorized) && ...
    ~logical(manifest.hardwareUsed);
if ~valid
    error("run_no_glove_stage7b_designed_excitation:IncompatibleStage7a", ...
        "ETAPA 7B requires the no-intervention ETAPA 7A output.");
end
expectedHash = findArtifactHash(manifest.artifactHashes, ...
    "stage7a_results.mat");
if fileSha256(resultsPath) ~= expectedHash
    error("run_no_glove_stage7b_designed_excitation:Stage7aHashMismatch", ...
        "ETAPA 7A results do not match their manifest.");
end
end

function [manifest, manifestPath, agentPath, agentHash, profile] = ...
        loadAndValidateStage6(runRoot)
manifestPath = fullfile(runRoot, "manifest.json");
inventoryPath = fullfile(runRoot, "checkpoint_inventory.csv");
if ~isfile(manifestPath) || ~isfile(inventoryPath)
    error("run_no_glove_stage7b_designed_excitation:Stage6NotFound", ...
        "ETAPA 6 manifest/inventory are missing.");
end
manifest = jsondecode(fileread(manifestPath));
if double(manifest.stage) ~= 6 || string(manifest.phase) ~= "smoke" || ...
        string(manifest.result) ~= "PARTIAL" || ...
        logical(manifest.hardwareUsed) || ~logical(manifest.simMotors) || ...
        logical(manifest.agent7250Loaded) || ...
        ~logical(manifest.positionSafetyAblation)
    error("run_no_glove_stage7b_designed_excitation:IncompatibleStage6", ...
        "ETAPA 7B requires the bounded position-safety Agent200 smoke.");
end
agentPath = string(manifest.seedSummary.finalCheckpoint);
if ~endsWith(agentPath, "Agent200.mat") || ~isfile(agentPath)
    error("run_no_glove_stage7b_designed_excitation:AgentNotFound", ...
        "Frozen Agent200 checkpoint is missing.");
end
inventory = readtable(inventoryPath, "TextType", "string");
match = inventory.checkpointPath == agentPath & inventory.episode == 200;
if sum(match) ~= 1
    error("run_no_glove_stage7b_designed_excitation:AgentInventoryMismatch", ...
        "Agent200 is not uniquely identified by the ETAPA 6 inventory.");
end
agentHash = upper(string(inventory.checkpointSha256(match)));
configPath = fullfile(fileparts(agentPath), "00_configs.mat");
if ~isfile(configPath)
    error("run_no_glove_stage7b_designed_excitation:ConfigNotFound", ...
        "Agent200 effective configuration is missing.");
end
loaded = load(configPath, "configs");
profile = loaded.configs;
required = ["intentCalibration", "intentExpectedContext", ...
    "referenceSource", "observationVariant", "rewardType", ...
    "actionInterfaceVariant", "simulationPositionSafety", ...
    "quantizeCommandsForSimulation", "td3", "td3Residual"];
if ~all(isfield(profile, cellstr(required)))
    error("run_no_glove_stage7b_designed_excitation:IncompleteProfile", ...
        "Agent200 profile is incomplete.");
end
safe = string(profile.referenceSource) == "emgIntent" && ...
    string(profile.observationVariant) == "intentMarkov60" && ...
    string(profile.rewardType) == "trackingIntentActionRateReward" && ...
    string(profile.actionInterfaceVariant) == "baselineQuantized" && ...
    logical(profile.quantizeCommandsForSimulation) && ...
    logical(profile.simulationPositionSafety.enabled) && ...
    ~logical(profile.td3.useRecurrent) && ...
    ~logical(profile.td3Residual.enabled);
if ~safe
    error("run_no_glove_stage7b_designed_excitation:UnsafeProfile", ...
        "Agent200 profile drifted from the bounded no-glove contract.");
end
end

function expected = findArtifactHash(artifactHashes, artifactName)
paths = string({artifactHashes.path});
match = paths == artifactName;
if sum(match) ~= 1
    error("run_no_glove_stage7b_designed_excitation:HashNotFound", ...
        "Manifest does not contain one hash for %s.", artifactName);
end
expected = upper(string(artifactHashes(match).sha256));
end

function profile = buildEvaluationProfile( ...
        trainingProfile, agentPath, datasetPath, randomSeed, ...
        simulationCount, outputBase)
[datasetFolder, datasetStem] = fileparts(datasetPath);
profile = trainingProfile;
profile.run_training = false;
profile.newTraining = false;
profile.agentFile = agentPath;
profile.agent_id = "td3_no_glove_intent";
profile.randomSeed = randomSeed;
profile.dataset = {char(string(datasetStem))};
profile.dataset_folder = string(datasetFolder);
profile.flagSaveTraining = true;
profile.episode_save_freq = 1;
profile.plotEpisodeOnTest = false;
profile.trainingPlots = "none";
profile.simOpts = rlSimulationOptions( ...
    "MaxSteps", profile.maxNumberStepsInEpisodes, ...
    "NumSimulations", simulationCount, "StopOnError", "on", ...
    "UseParallel", false);
profile.agents_directory = @(agent_id, variant) fullfile( ...
    outputBase, string(datetime("now", "Format", "yy-MM-dd HH m s")));
profile.simMotors = true;
profile.connect_glove = false;
profile.usePrerecorded = true;
profile.referenceSource = "emgIntent";
end

function assertSafeEvaluationProfile(profile, agentPath, simulationCount)
safe = ~logical(profile.run_training) && ~logical(profile.newTraining) && ...
    string(profile.agentFile) == agentPath && ...
    string(profile.agent_id) == "td3_no_glove_intent" && ...
    logical(profile.simMotors) && ~logical(profile.connect_glove) && ...
    logical(profile.usePrerecorded) && ...
    string(profile.referenceSource) == "emgIntent" && ...
    string(profile.observationVariant) == "intentMarkov60" && ...
    string(profile.rewardType) == "trackingIntentActionRateReward" && ...
    string(profile.actionInterfaceVariant) == "baselineQuantized" && ...
    logical(profile.quantizeCommandsForSimulation) && ...
    logical(profile.simulationPositionSafety.enabled) && ...
    profile.simOpts.NumSimulations == simulationCount;
if ~safe
    error("run_no_glove_stage7b_designed_excitation:UnsafeEvaluation", ...
        "Frozen Agent200 evaluation profile violates an invariant.");
end
end

function profile = buildMatchedProfile(trainingProfile)
stage5 = buildNoGloveStage5Override( ...
    trainingProfile.intentCalibration, ...
    trainingProfile.intentExpectedContext, 11);
profile = trainingProfile;
profile.conventionalController = stage5.conventionalController;
profile.run_training = false;
profile.newTraining = false;
profile.agentFile = "";
profile.flagSaveTraining = false;
profile.plotEpisodeOnTest = false;
profile.simMotors = true;
profile.connect_glove = false;
profile.usePrerecorded = true;
profile.referenceSource = "emgIntent";
profile.observationVariant = "intentMarkov60";
profile.actionInterfaceVariant = "baselineQuantized";
profile.quantizeCommandsForSimulation = true;
profile.unifyActions = false;
expected = struct("schemaVersion", 1, "type", "P", ...
    "kp", 1.5*ones(4, 1), "kd", zeros(4, 1), ...
    "maxAction", (64/255)*ones(4, 1), ...
    "positionTolerance", 0.01*ones(4, 1), ...
    "velocityTolerance", 0.03*ones(4, 1));
if ~isequal(profile.conventionalController, expected)
    error("run_no_glove_stage7b_designed_excitation:ControllerDrift", ...
        "Validated ETAPA 5 P controller has changed.");
end
end

function writeDataset(pathValue, emgsValue, metadataValue)
emgs = emgsValue;
metadata = metadataValue;
save(pathValue, "emgs", "metadata");
end

function evaluationDir = runAgentEvaluation(profile)
outputBase = string(fileparts(profile.agents_directory("", "")));
if ~isfolder(outputBase)
    mkdir(outputBase);
end
rng(profile.randomSeed, "twister");
setConfigurablesOverride(profile);
trainInterface("td3_no_glove_intent", "", "");
clearConfigurablesOverride();
evaluationDir = findNewestSubdir(outputBase);
end

function inventory = inventoryEpisodes(directory)
files = dir(fullfile(directory, "episode*.mat"));
[~, order] = sort({files.name});
files = files(order);
paths = strings(numel(files), 1);
hashes = strings(numel(files), 1);
bytes = zeros(numel(files), 1);
for fileIdx = 1:numel(files)
    paths(fileIdx) = string(fullfile(files(fileIdx).folder, files(fileIdx).name));
    hashes(fileIdx) = fileSha256(paths(fileIdx));
    bytes(fileIdx) = files(fileIdx).bytes;
end
inventory = table(string({files.name})', paths, hashes, bytes, ...
    'VariableNames', ["fileName", "path", "sha256", "bytes"]);
end

function writeAnalysisTables(runDir, matched, analysis)
writetable(matched.pairingTable, fullfile(runDir, "pairing.csv"));
writetable(matched.episodeSummary, ...
    fullfile(runDir, "episode_summary.csv"));
writetable(matched.motorSummary, fullfile(runDir, "motor_summary.csv"));
writetable(matched.aggregateSummary, ...
    fullfile(runDir, "aggregate_summary.csv"));
writetable(analysis.lagConfirmationSummary, ...
    fullfile(runDir, "lag_confirmation_summary.csv"));
writetable(analysis.foldEvaluationTable, ...
    fullfile(runDir, "held_out_fold_evaluation.csv"));
writetable(analysis.eventLatencyTable, ...
    fullfile(runDir, "event_latency.csv"));
writetable(analysis.eventLatencySummary, ...
    fullfile(runDir, "event_latency_summary.csv"));
writetable(analysis.designedGateTable, ...
    fullfile(runDir, "designed_gate.csv"));
writetable(analysis.sourceDecision, ...
    fullfile(runDir, "source_decision.csv"));
end

function command = buildReproducibleCommand(matlabRoot, options, resultsRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7b_designed_excitation(struct(" + ...
    "'stage7aRunRoot','%s','stage6RunRoot','%s'," + ...
    "'resultsRoot','%s','calibrationSeed',%d,'profileSeed',%d," + ...
    "'smokeSeed',%d,'evaluationSeed',%d,'repetitionsPerAxis',%d," + ...
    "'maxLagSteps',%d,'activeVelocityThreshold',%.17g," + ...
    "'motionVelocityThreshold',%.17g,'offsetHoldSteps',%d," + ...
    "'minimumSamplesPerFold',%d,'minimumBenefitFraction',%.17g," + ...
    "'minimumMaterialFoldFraction',%.17g," + ...
    "'minimumSignConsistency',%.17g," + ...
    "'maximumBoundaryFraction',%.17g," + ...
    "'minimumFiniteOnsetFraction',%.17g,'periodSec',%.17g," + ...
    "'motionTolerance',%.17g,'positionTolerance',%.17g," + ...
    "'saturationThreshold',%.17g,'simulatorSamplingPeriod',%.17g))", ...
    escape(matlabRoot), escape(options.stage7aRunRoot), ...
    escape(options.stage6RunRoot), escape(resultsRoot), ...
    options.calibrationSeed, options.profileSeed, options.smokeSeed, ...
    options.evaluationSeed, options.repetitionsPerAxis, ...
    options.maxLagSteps, options.activeVelocityThreshold, ...
    options.motionVelocityThreshold, options.offsetHoldSteps, ...
    options.minimumSamplesPerFold, options.minimumBenefitFraction, ...
    options.minimumMaterialFoldFraction, options.minimumSignConsistency, ...
    options.maximumBoundaryFraction, options.minimumFiniteOnsetFraction, ...
    options.periodSec, options.motionTolerance, options.positionTolerance, ...
    options.saturationThreshold, options.simulatorSamplingPeriod);
end

function writeOfflineReport(pathValue, analysis, matched, corpus, ...
        options, agentSec, matchedSec, analysisSec, runDir)
lines = strings(0, 1);
lines(end+1, 1) = "# ETAPA 7B - excitacion temporal disenada";
lines(end+1, 1) = "";
lines(end+1, 1) = "- Ejecucion: PASS.";
lines(end+1, 1) = "- Entrenamiento/Agent7250/DTW/hardware: no/no/no/no.";
lines(end+1, 1) = sprintf("- Perfiles: %d; simulaciones: %d.", ...
    height(corpus.protocolTable), corpus.expectedSimulationCount);
lines(end+1, 1) = sprintf("- Lag pre-registrado: +/- %d pasos.", ...
    options.maxLagSteps);
lines(end+1, 1) = sprintf("- Emparejamiento exacto: %d.", ...
    matched.pairing.allExact);
lines(end+1, 1) = "";
lines(end+1, 1) = "## Gate por fuente";
lines(end+1, 1) = "";
decisionLines = strings(height(analysis.sourceDecision), 1);
for rowIdx = 1:height(analysis.sourceDecision)
    row = analysis.sourceDecision(rowIdx, :);
    decisionLines(rowIdx) = sprintf( ...
        "- %s: %s; candidatos=%d; no resueltos=%d; rechazados=%d.", ...
        row.commandSource, row.classification, ...
        row.causalCandidateCount, row.unresolvedCount, row.rejectedCount);
end
lines = vertcat(lines, decisionLines);
lines(end+1, 1) = "";
lines(end+1, 1) = "No se ejecuto compensacion, filtro ni DTW.";
lines(end+1, 1) = sprintf( ...
    "Costo: Agent200 %.6f s; P emparejado %.6f s; analisis %.6f s.", ...
    agentSec, matchedSec, analysisSec);
lines(end+1, 1) = "Ruta: `" + string(runDir) + "`.";
writeText(pathValue, strjoin(lines, newline));
end

function newestDir = findNewestSubdir(parentDir)
info = dir(parentDir);
info = info([info.isdir]);
info = info(~ismember({info.name}, {'.', '..'}));
if isempty(info)
    error("run_no_glove_stage7b_designed_excitation:MissingOutput", ...
        "No output directory found under %s.", parentDir);
end
[~, idx] = max([info.datenum]);
newestDir = string(fullfile(info(idx).folder, info(idx).name));
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[workingStatus, ~] = system(sprintf('git -C "%s" diff --quiet', repoRoot));
[indexStatus, ~] = system(sprintf( ...
    'git -C "%s" diff --cached --quiet', repoRoot));
trackedDirty = workingStatus ~= 0 || indexStatus ~= 0;
end

function hash = fileSha256(filePath)
escapedPath = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escapedPath);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7b_designed_excitation:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = upper(string(strtrim(output)));
end

function escaped = escape(value)
escaped = strrep(char(string(value)), "'", "''");
end

function writeText(filePath, value)
[fid, message] = fopen(filePath, "w", "n", "UTF-8");
if fid < 0
    error("run_no_glove_stage7b_designed_excitation:WriteFailed", ...
        "Could not open %s: %s.", filePath, message);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
