function report = run_no_glove_stage7c_rest_attribution(options)
%run_no_glove_stage7c_rest_attribution executes ETAPA 7C only.
%
% Agent200 is replayed offline on immutable ETAPA 7B pre-rest states. Local
% single-block sensitivity uses observed same-episode donors. No Env,
% simulator, reward, training, behavior change, DTW or hardware is invoked.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
addpath(genpath(fullfile(matlabRoot, "tests")));
clearConfigurablesOverride();

[stage7bManifest, inputPaths] = validateStage7b(options.stage7bRunRoot);
inputHashesBefore = hashInputPaths(inputPaths);
[inventory, episodeHashesBefore] = loadAndValidateEpisodeInventory( ...
    inputPaths.episodeInventory);
[evaluationProfile, matchedProfile] = loadAndValidateProfiles( ...
    inputPaths.effectiveProfile, stage7bManifest);
agentPath = string(stage7bManifest.agentCheckpointPath);
agentHashBefore = fileSha256(agentPath);
if agentHashBefore ~= upper(string( ...
        stage7bManifest.agentCheckpointSha256After))
    error("run_no_glove_stage7c_rest_attribution:AgentHashMismatch", ...
        "Agent200 does not match the ETAPA 7B manifest.");
end

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7c_rest_attribution");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runDir)
    error("run_no_glove_stage7c_rest_attribution:OutputExists", ...
        "Refusing to reuse output directory %s.", runDir);
end
mkdir(runDir);

testPath = fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage7cRestAttribution.m");
testResults = runtests(testPath);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7c_rest_attribution:TestsFailed", ...
        "ETAPA 7C tests failed; actor replay is forbidden. See %s.", ...
        runDir);
end

protocol = readtable(inputPaths.profileProtocol, "Delimiter", ",", ...
    "TextType", "string", "VariableNamingRule", "preserve");
episodes = loadEpisodeInputs(inventory, protocol);
loadedStage7b = load(inputPaths.results, "matched");
if ~isfield(loadedStage7b, "matched") || ...
        ~isfield(loadedStage7b.matched, "componentTable")
    error("run_no_glove_stage7c_rest_attribution:MissingMatchedData", ...
        "ETAPA 7B results do not contain the matched component table.");
end
matchedP = loadedStage7b.matched.componentTable( ...
    loadedStage7b.matched.componentTable.commandSource == ...
    "conventionalP", :);

agent = loadSavedAgent(agentPath);
actor = getActor(agent);
actorEvaluator = @(states) evaluateFrozenActorStates(actor, states);
actuator = struct( ...
    "maxPwm", max(abs(double(evaluationProfile.speeds))), ...
    "activationThreshold", ...
        double(evaluationProfile.actionCommandActivationThreshold), ...
    "commandLevels", double(evaluationProfile.actionCommandLevels));
analysisOptions = struct( ...
    "preRestWindows", options.preRestWindows, ...
    "periodSec", options.periodSec, ...
    "replayTolerance", options.replayTolerance, ...
    "stateTolerance", options.stateTolerance, ...
    "minimumDonorBlockDistance", ...
        options.minimumDonorBlockDistance, ...
    "maximumComplementDistance", ...
        options.maximumComplementDistance, ...
    "materialRawActionDelta", options.materialRawActionDelta, ...
    "minimumMaterialFraction", options.minimumMaterialFraction, ...
    "minimumLocalCoverage", options.minimumLocalCoverage, ...
    "minimumIdentifiableFraction", ...
        options.minimumIdentifiableFraction, ...
    "falseActivationLimit", options.falseActivationLimit, ...
    "saturationThreshold", options.saturationThreshold);
analysisArguments = namedargs2cell(analysisOptions);

smokeEpisodes = episodes(1:2);
smokeIds = [smokeEpisodes.episode];
smokeProtocol = protocol(ismember(protocol.repetitionId, ...
    [smokeEpisodes.repetitionId]) & ismember(protocol.side, ...
    [smokeEpisodes.side]), :);
smokeProtocol = smokeProtocol(ismember(string(smokeProtocol.profileId), ...
    string({smokeEpisodes.profileId})), :);
smokeMatchedP = matchedP(ismember(matchedP.episode, smokeIds), :);
smokeAnalysis = analyzeNoGloveStage7cRestCommands( ...
    smokeEpisodes, smokeProtocol, smokeMatchedP, actorEvaluator, ...
    matchedProfile.conventionalController, actuator, ...
    analysisArguments{:});
if smokeAnalysis.replayMaximumAbsoluteError > options.replayTolerance || ...
        smokeAnalysis.hardwareUsed || smokeAnalysis.simulatorInvoked || ...
        smokeAnalysis.runTraining
    error("run_no_glove_stage7c_rest_attribution:SmokeFailed", ...
        "Two-episode offline smoke violated an invariant.");
end
writetable(smokeAnalysis.sourceDecision, ...
    fullfile(runDir, "smoke_source_decision.csv"));

analysisTic = tic;
analysis = analyzeNoGloveStage7cRestCommands( ...
    episodes, protocol, matchedP, actorEvaluator, ...
    matchedProfile.conventionalController, actuator, ...
    analysisArguments{:});
analysisElapsedSec = toc(analysisTic);
writeAnalysisTables(runDir, analysis);
save(fullfile(runDir, "stage7c_results.mat"), ...
    "analysis", "analysisOptions", "smokeAnalysis", ...
    "stage7bManifest", "analysisElapsedSec", "-v7.3");

inputHashesAfter = hashInputPaths(inputPaths);
episodeHashesAfter = hashEpisodePaths(inventory.path);
agentHashAfter = fileSha256(agentPath);
if ~isequal(inputHashesAfter, inputHashesBefore) || ...
        ~isequal(episodeHashesAfter, episodeHashesBefore) || ...
        agentHashAfter ~= agentHashBefore
    error("run_no_glove_stage7c_rest_attribution:InputModified", ...
        "ETAPA 7B evidence or Agent200 changed during ETAPA 7C.");
end
writetable(inventory, fullfile(runDir, "episode_input_hashes.csv"));

reproducibleCommand = buildReproducibleCommand( ...
    matlabRoot, options, fileparts(runDir));
writeText(fullfile(runDir, "reproducible_command.txt"), ...
    reproducibleCommand);
writeOfflineReport(fullfile(runDir, "offline_report.md"), ...
    analysis, analysisElapsedSec, runDir);

primaryArtifacts = ["test_results.mat", ...
    "smoke_source_decision.csv", "episode_input_hashes.csv", ...
    "episode_audit.csv", "observed_rest_commands.csv", ...
    "initial_anchor_components.csv", "initial_anchor_summary.csv", ...
    "block_scales.csv", "local_block_interventions.csv", ...
    "block_summary.csv", "block_decision.csv", ...
    "control_summary.csv", "source_decision.csv", ...
    "stage7c_results.mat", "reproducible_command.txt", ...
    "offline_report.md"];
artifactHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(primaryArtifacts), 1);
for artifactIdx = 1:numel(primaryArtifacts)
    artifactHashes(artifactIdx).path = primaryArtifacts(artifactIdx);
    artifactHashes(artifactIdx).sha256 = fileSha256( ...
        fullfile(runDir, primaryArtifacts(artifactIdx)));
end
writetable(struct2table(artifactHashes), ...
    fullfile(runDir, "artifact_hashes.csv"));

[gitCommit, gitDirty, trackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
decision = analysis.sourceDecision(1, :);
aggregateControl = analysis.controlSummary( ...
    analysis.controlSummary.motor == 0, :);
agentControl = aggregateControl( ...
    aggregateControl.commandSource == "Agent200Observed", :);
matchedControl = aggregateControl( ...
    aggregateControl.commandSource == ...
    "conventionalPMatchedTrajectory", :);
manifest = struct( ...
    "stage", "7C", "schemaVersion", 1, "result", "PASS", ...
    "scientificResult", decision.classification, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", trackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7c_rest_attribution", ...
    "inputStage7bRunRoot", options.stage7bRunRoot, ...
    "inputStage7bManifestPath", inputPaths.manifest, ...
    "inputStage7bManifestSha256Before", inputHashesBefore.manifest, ...
    "inputStage7bManifestSha256After", inputHashesAfter.manifest, ...
    "inputStage7bResultsSha256Before", inputHashesBefore.results, ...
    "inputStage7bResultsSha256After", inputHashesAfter.results, ...
    "inputEpisodeCount", height(inventory), ...
    "inputEpisodeHashesPreserved", ...
        isequal(episodeHashesBefore, episodeHashesAfter), ...
    "inputEvidencePreserved", isequal(inputHashesBefore, inputHashesAfter), ...
    "agentCheckpointPath", agentPath, ...
    "agentCheckpointLabel", "Agent200", ...
    "agentCheckpointSha256Before", agentHashBefore, ...
    "agentCheckpointSha256After", agentHashAfter, ...
    "agentCheckpointPreserved", agentHashBefore == agentHashAfter, ...
    "agentFrozen", true, "newTraining", false, ...
    "checkpointLoadedForTraining", false, ...
    "analysisOptions", analysisOptions, ...
    "smokeEpisodeCount", numel(smokeEpisodes), ...
    "evaluationEpisodeCount", numel(episodes), ...
    "preRestWindowsPerEpisode", options.preRestWindows, ...
    "preRestStateCount", numel(episodes)*options.preRestWindows, ...
    "replayMaximumAbsoluteError", ...
        analysis.replayMaximumAbsoluteError, ...
    "restCommandActiveFraction", ...
        decision.restCommandActiveFraction, ...
    "restWindowAnyCommandFraction", ...
        decision.restWindowAnyCommandFraction, ...
    "initialCommandActiveFraction", ...
        decision.initialCommandActiveFraction, ...
    "homeAnchorEpisodeCount", decision.homeAnchorEpisodeCount, ...
    "homeAnchorCommandActiveFraction", ...
        decision.homeAnchorCommandActiveFraction, ...
    "commandDuringCalibratedRestConfirmed", ...
        decision.commandDuringCalibratedRestConfirmed, ...
    "commandAtObservedEmgOnlyStateConfirmed", ...
        decision.commandAtObservedEmgOnlyStateConfirmed, ...
    "restEmgLocalSensitivityObserved", ...
        decision.restEmgLocalSensitivityObserved, ...
    "rootCauseIdentified", decision.rootCauseIdentified, ...
    "restSafetyInterventionCount", ...
        decision.restSafetyInterventionCount, ...
    "restSafetyInterventionComponentFraction", ...
        decision.restSafetyInterventionComponentFraction, ...
    "agentRestMeanAbsPwm", agentControl.meanAbsPwm, ...
    "matchedPRestCommandActiveFraction", ...
        matchedControl.commandActiveFraction, ...
    "behavioralInterventionExecuted", false, ...
    "compensationInterventionExecuted", false, ...
    "filteredReferenceInterventionExecuted", false, ...
    "dtwCalculated", false, "dtwRewardUsed", false, ...
    "stage8Authorized", false, ...
    "referenceGeneratorChanged", false, "stateChanged", false, ...
    "rewardChanged", false, "policyChanged", false, ...
    "quantizationChanged", false, "simulatorChanged", false, ...
    "safetyLayerChanged", false, "controllerChanged", false, ...
    "simMotorsInvariant", true, "runTraining", false, ...
    "agentLoaded", true, "agentEvaluationOnly", true, ...
    "reinforcementLearningInvoked", true, ...
    "reinforcementLearningTrainingInvoked", false, ...
    "offlineActorReplay", true, "envCreated", false, ...
    "simulatorInvoked", false, "rewardInvoked", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "agent7250Loaded", false, "hardwareUsed", false, ...
    "analysisElapsedSec", analysisElapsedSec, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "artifactHashes", artifactHashes, "outputPath", runDir);
save(fullfile(runDir, "manifest.mat"), "manifest", "artifactHashes");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", "outputPath", runDir, ...
    "manifest", manifest, "analysis", analysis, ...
    "testResults", testResults);
fprintf("ETAPA 7C REST ATTRIBUTION PASS\n");
fprintf("Output: %s\n", runDir);
disp(analysis.sourceDecision);
disp(analysis.blockDecision);
disp(aggregateControl);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7c_rest_attribution:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct("stage7bRunRoot", "", "resultsRoot", "", ...
    "preRestWindows", 8, "periodSec", 0.2, ...
    "replayTolerance", 1e-12, "stateTolerance", 1e-12, ...
    "minimumDonorBlockDistance", 1e-12, ...
    "maximumComplementDistance", 2.0, ...
    "materialRawActionDelta", 0.05, ...
    "minimumMaterialFraction", 0.25, ...
    "minimumLocalCoverage", 0.75, ...
    "minimumIdentifiableFraction", 0.75, ...
    "falseActivationLimit", 0.01, ...
    "saturationThreshold", 0.95);
unknown = setdiff(string(fieldnames(options)), ...
    string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7c_rest_attribution:UnknownOption", ...
        "Unknown option(s): %s.", strjoin(unknown, ", "));
end
fields = fieldnames(defaults);
for fieldIdx = 1:numel(fields)
    name = fields{fieldIdx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.stage7bRunRoot = string(options.stage7bRunRoot);
options.resultsRoot = string(options.resultsRoot);
if strlength(options.stage7bRunRoot) == 0
    error("run_no_glove_stage7c_rest_attribution:MissingInput", ...
        "stage7bRunRoot is required.");
end
numericFields = setdiff(string(fieldnames(defaults)), ...
    ["stage7bRunRoot", "resultsRoot"]);
for fieldIdx = 1:numel(numericFields)
    value = options.(numericFields(fieldIdx));
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value < 0
        error("run_no_glove_stage7c_rest_attribution:InvalidOption", ...
            "%s must be a finite nonnegative scalar.", ...
            numericFields(fieldIdx));
    end
end
if fix(options.preRestWindows) ~= options.preRestWindows || ...
        options.preRestWindows < 2 || options.periodSec <= 0 || ...
        options.maximumComplementDistance <= 0 || ...
        options.materialRawActionDelta <= 0 || ...
        options.minimumMaterialFraction > 1 || ...
        options.minimumLocalCoverage > 1 || ...
        options.minimumIdentifiableFraction > 1 || ...
        options.falseActivationLimit > 1 || ...
        options.saturationThreshold > 1
    error("run_no_glove_stage7c_rest_attribution:InvalidOption", ...
        "ETAPA 7C option bounds are invalid.");
end
end

function [manifest, paths] = validateStage7b(runRoot)
paths = struct( ...
    "manifest", fullfile(runRoot, "manifest.json"), ...
    "results", fullfile(runRoot, "stage7b_results.mat"), ...
    "episodeInventory", fullfile(runRoot, "agent_episode_hashes.csv"), ...
    "profileProtocol", fullfile(runRoot, "profile_protocol.csv"), ...
    "effectiveProfile", fullfile(runRoot, ...
        "effective_evaluation_profile.mat"));
pathFields = fieldnames(paths);
for pathIdx = 1:numel(pathFields)
    if ~isfile(paths.(pathFields{pathIdx}))
        error("run_no_glove_stage7c_rest_attribution:Stage7bNotFound", ...
            "Missing ETAPA 7B input %s.", paths.(pathFields{pathIdx}));
    end
end
manifest = jsondecode(fileread(paths.manifest));
required = ["stage", "result", "scientificGateResult", ...
    "causalCompensationGatePassed", "compensationInterventionExecuted", ...
    "filteredReferenceInterventionExecuted", "dtwCalculated", ...
    "stage8Authorized", "agentFrozen", "runTraining", ...
    "agentCheckpointPath", "agentCheckpointSha256After", ...
    "agent7250Loaded", "hardwareUsed", "exactPairing", ...
    "positionViolationCount", "artifactHashes"];
if ~all(isfield(manifest, cellstr(required)))
    error("run_no_glove_stage7c_rest_attribution:InvalidStage7b", ...
        "ETAPA 7B manifest contract is incomplete.");
end
valid = string(manifest.stage) == "7B" && ...
    string(manifest.result) == "PASS" && ...
    string(manifest.scientificGateResult) == ...
        "designedTemporalPatternUnresolved" && ...
    ~logical(manifest.causalCompensationGatePassed) && ...
    ~logical(manifest.compensationInterventionExecuted) && ...
    ~logical(manifest.filteredReferenceInterventionExecuted) && ...
    ~logical(manifest.dtwCalculated) && ~logical(manifest.stage8Authorized) && ...
    logical(manifest.agentFrozen) && ~logical(manifest.runTraining) && ...
    ~logical(manifest.agent7250Loaded) && ~logical(manifest.hardwareUsed) && ...
    logical(manifest.exactPairing) && double(manifest.positionViolationCount) == 0;
if ~valid
    error("run_no_glove_stage7c_rest_attribution:IncompatibleStage7b", ...
        "ETAPA 7C requires the canonical no-intervention ETAPA 7B output.");
end
artifactNames = ["stage7b_results.mat", "agent_episode_hashes.csv", ...
    "profile_protocol.csv", "effective_evaluation_profile.mat"];
artifactPaths = [paths.results, paths.episodeInventory, ...
    paths.profileProtocol, paths.effectiveProfile];
for artifactIdx = 1:numel(artifactNames)
    expected = findArtifactHash(manifest.artifactHashes, ...
        artifactNames(artifactIdx));
    if fileSha256(artifactPaths(artifactIdx)) ~= expected
        error("run_no_glove_stage7c_rest_attribution:Stage7bHashMismatch", ...
            "%s does not match the ETAPA 7B manifest.", ...
            artifactNames(artifactIdx));
    end
end
end

function hashes = hashInputPaths(paths)
hashes = struct( ...
    "manifest", fileSha256(paths.manifest), ...
    "results", fileSha256(paths.results), ...
    "episodeInventory", fileSha256(paths.episodeInventory), ...
    "profileProtocol", fileSha256(paths.profileProtocol), ...
    "effectiveProfile", fileSha256(paths.effectiveProfile));
end

function [inventory, hashes] = loadAndValidateEpisodeInventory(pathValue)
inventory = readtable(pathValue, "Delimiter", ",", "TextType", "string", ...
    "VariableNamingRule", "preserve");
required = ["fileName", "path", "sha256", "bytes"];
if ~all(ismember(required, string(inventory.Properties.VariableNames))) || ...
        height(inventory) ~= 16 || numel(unique(inventory.path)) ~= 16
    error("run_no_glove_stage7c_rest_attribution:InvalidInventory", ...
        "ETAPA 7B episode inventory must contain 16 unique files.");
end
hashes = hashEpisodePaths(inventory.path);
if any(hashes ~= upper(inventory.sha256))
    error("run_no_glove_stage7c_rest_attribution:EpisodeHashMismatch", ...
        "An ETAPA 7B episode does not match its inventory.");
end
for rowIdx = 1:height(inventory)
    info = dir(inventory.path(rowIdx));
    if numel(info) ~= 1 || double(info.bytes) ~= double(inventory.bytes(rowIdx))
        error("run_no_glove_stage7c_rest_attribution:EpisodeSizeMismatch", ...
            "Episode size does not match its inventory.");
    end
end
end

function hashes = hashEpisodePaths(paths)
hashes = strings(numel(paths), 1);
for pathIdx = 1:numel(paths)
    if ~isfile(paths(pathIdx))
        error("run_no_glove_stage7c_rest_attribution:EpisodeNotFound", ...
            "Missing episode %s.", paths(pathIdx));
    end
    hashes(pathIdx) = fileSha256(paths(pathIdx));
end
end

function [evaluationProfile, matchedProfile] = ...
        loadAndValidateProfiles(pathValue, manifest)
loaded = load(pathValue, "evaluationProfile", "matchedProfile");
if ~isfield(loaded, "evaluationProfile") || ...
        ~isfield(loaded, "matchedProfile")
    error("run_no_glove_stage7c_rest_attribution:MissingProfile", ...
        "ETAPA 7B effective profiles are incomplete.");
end
evaluationProfile = loaded.evaluationProfile;
matchedProfile = loaded.matchedProfile;
required = ["run_training", "newTraining", "agentFile", ...
    "simMotors", "connect_glove", "referenceSource", ...
    "observationVariant", "rewardType", "actionInterfaceVariant", ...
    "quantizeCommandsForSimulation", "simulationPositionSafety", ...
    "td3", "td3Residual", "speeds", ...
    "actionCommandActivationThreshold", "actionCommandLevels"];
if ~all(isfield(evaluationProfile, cellstr(required))) || ...
        ~isfield(matchedProfile, "conventionalController")
    error("run_no_glove_stage7c_rest_attribution:IncompleteProfile", ...
        "ETAPA 7B profiles do not satisfy the frozen contract.");
end
safe = ~logical(evaluationProfile.run_training) && ...
    ~logical(evaluationProfile.newTraining) && ...
    string(evaluationProfile.agentFile) == ...
        string(manifest.agentCheckpointPath) && ...
    logical(evaluationProfile.simMotors) && ...
    ~logical(evaluationProfile.connect_glove) && ...
    string(evaluationProfile.referenceSource) == "emgIntent" && ...
    string(evaluationProfile.observationVariant) == "intentMarkov60" && ...
    string(evaluationProfile.rewardType) == ...
        "trackingIntentActionRateReward" && ...
    string(evaluationProfile.actionInterfaceVariant) == ...
        "baselineQuantized" && ...
    logical(evaluationProfile.quantizeCommandsForSimulation) && ...
    logical(evaluationProfile.simulationPositionSafety.enabled) && ...
    ~logical(evaluationProfile.td3.useRecurrent) && ...
    ~logical(evaluationProfile.td3Residual.enabled);
expectedController = struct("schemaVersion", 1, "type", "P", ...
    "kp", 1.5*ones(4, 1), "kd", zeros(4, 1), ...
    "maxAction", (64/255)*ones(4, 1), ...
    "positionTolerance", 0.01*ones(4, 1), ...
    "velocityTolerance", 0.03*ones(4, 1));
if ~safe || ~isequal(matchedProfile.conventionalController, ...
        expectedController)
    error("run_no_glove_stage7c_rest_attribution:ProfileDrift", ...
        "Policy, interface, safety or conventional P has drifted.");
end
end

function episodes = loadEpisodeInputs(inventory, protocol)
template = struct("episode", 0, "repetitionId", 0, "side", 0, ...
    "profileId", "", "stateLog", [], "rawAction", [], ...
    "effectiveAction", [], "appliedPwm", [], ...
    "referenceHistory", [], "positionSafetyInterventionLog", [], ...
    "referenceSource", "", "observationVariant", "", ...
    "stateLength", 0);
episodes = repmat(template, height(inventory), 1);
for episodeIdx = 1:height(inventory)
    expectedName = sprintf("episode%05d.mat", episodeIdx);
    if inventory.fileName(episodeIdx) ~= expectedName
        error("run_no_glove_stage7c_rest_attribution:EpisodeOrder", ...
            "Episode inventory is not in canonical order.");
    end
    required = ["repetitionId", "stateLog", "actionLog", ...
        "actionSatLog", "actionPwmLog", "referenceHistory", ...
        "positionSafetyInterventionLog", "referenceSource", ...
        "observationVariant", "stateLength"];
    available = string(who("-file", inventory.path(episodeIdx)));
    if ~all(ismember(required, available))
        error("run_no_glove_stage7c_rest_attribution:IncompleteEpisode", ...
            "Episode %d is missing required fields.", episodeIdx);
    end
    requiredCell = cellstr(required);
    loaded = load(inventory.path(episodeIdx), requiredCell{:});
    side = 1+mod(episodeIdx-1, 2);
    match = protocol.repetitionId == loaded.repetitionId & ...
        protocol.side == side;
    if sum(match) ~= 1
        error("run_no_glove_stage7c_rest_attribution:ProtocolMismatch", ...
            "Episode %d does not map to one profile.", episodeIdx);
    end
    episodes(episodeIdx) = struct( ...
        "episode", episodeIdx, "repetitionId", loaded.repetitionId, ...
        "side", side, "profileId", protocol.profileId(match), ...
        "stateLog", loaded.stateLog, "rawAction", loaded.actionLog, ...
        "effectiveAction", loaded.actionSatLog, ...
        "appliedPwm", loaded.actionPwmLog, ...
        "referenceHistory", loaded.referenceHistory, ...
        "positionSafetyInterventionLog", ...
            loaded.positionSafetyInterventionLog, ...
        "referenceSource", loaded.referenceSource, ...
        "observationVariant", loaded.observationVariant, ...
        "stateLength", loaded.stateLength);
end
end

function writeAnalysisTables(runDir, analysis)
writetable(analysis.episodeAudit, fullfile(runDir, "episode_audit.csv"));
writetable(analysis.observedRestTable, ...
    fullfile(runDir, "observed_rest_commands.csv"));
writetable(analysis.anchorTable, ...
    fullfile(runDir, "initial_anchor_components.csv"));
writetable(analysis.anchorSummary, ...
    fullfile(runDir, "initial_anchor_summary.csv"));
writetable(analysis.blockScaleTable, ...
    fullfile(runDir, "block_scales.csv"));
writetable(analysis.interventionTable, ...
    fullfile(runDir, "local_block_interventions.csv"));
writetable(analysis.blockSummary, fullfile(runDir, "block_summary.csv"));
writetable(analysis.blockDecision, fullfile(runDir, "block_decision.csv"));
writetable(analysis.controlSummary, fullfile(runDir, "control_summary.csv"));
writetable(analysis.sourceDecision, fullfile(runDir, "source_decision.csv"));
end

function command = buildReproducibleCommand(matlabRoot, options, resultsRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7c_rest_attribution(struct(" + ...
    "'stage7bRunRoot','%s','resultsRoot','%s'," + ...
    "'preRestWindows',%d,'periodSec',%.17g," + ...
    "'replayTolerance',%.17g,'stateTolerance',%.17g," + ...
    "'minimumDonorBlockDistance',%.17g," + ...
    "'maximumComplementDistance',%.17g," + ...
    "'materialRawActionDelta',%.17g," + ...
    "'minimumMaterialFraction',%.17g," + ...
    "'minimumLocalCoverage',%.17g," + ...
    "'minimumIdentifiableFraction',%.17g," + ...
    "'falseActivationLimit',%.17g,'saturationThreshold',%.17g))", ...
    escape(matlabRoot), escape(options.stage7bRunRoot), ...
    escape(resultsRoot), options.preRestWindows, options.periodSec, ...
    options.replayTolerance, options.stateTolerance, ...
    options.minimumDonorBlockDistance, ...
    options.maximumComplementDistance, options.materialRawActionDelta, ...
    options.minimumMaterialFraction, options.minimumLocalCoverage, ...
    options.minimumIdentifiableFraction, ...
    options.falseActivationLimit, options.saturationThreshold);
end

function writeOfflineReport(pathValue, analysis, elapsedSec, runDir)
decision = analysis.sourceDecision(1, :);
lines = [ ...
    "# ETAPA 7C - atribucion offline de comandos en reposo"; ""; ...
    "- Ejecucion de ingenieria: PASS."; ...
    "- Clasificacion: `" + decision.classification + "`."; ...
    sprintf("- Activacion en reposo: %.9f.", ...
        decision.restCommandActiveFraction); ...
    sprintf("- Activacion en anchors EMG-only observados: %.9f.", ...
        decision.homeAnchorCommandActiveFraction); ...
    "- Causa raiz identificada: no."; ...
    "- Entrenamiento/Env/simulador/reward/DTW/hardware: no/no/no/no/no/no."; ...
    sprintf("- Tiempo de analisis: %.6f s.", elapsedSec); ...
    "- Ruta: `" + string(runDir) + "`." ...
    ];
writeText(pathValue, strjoin(lines, newline));
end

function expected = findArtifactHash(artifactHashes, artifactName)
paths = string({artifactHashes.path});
match = paths == artifactName;
if sum(match) ~= 1
    error("run_no_glove_stage7c_rest_attribution:HashNotFound", ...
        "ETAPA 7B manifest does not contain one hash for %s.", ...
        artifactName);
end
expected = upper(string(artifactHashes(match).sha256));
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[workingStatus, ~] = system(sprintf('git -C "%s" diff --quiet', repoRoot));
[indexStatus, ~] = system(sprintf( ...
    'git -C "%s" diff --cached --quiet', repoRoot));
trackedDirty = workingStatus ~= 0 || indexStatus ~= 0;
end

function hash = fileSha256(filePath)
escapedPath = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escapedPath);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7c_rest_attribution:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = upper(string(strtrim(output)));
end

function escaped = escape(value)
escaped = strrep(char(string(value)), "'", "''");
end

function writeText(filePath, value)
[fid, message] = fopen(filePath, "w", "n", "UTF-8");
if fid < 0
    error("run_no_glove_stage7c_rest_attribution:WriteFailed", ...
        "Could not open %s: %s.", filePath, message);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
