function report = run_no_glove_stage1_validation(options)
%run_no_glove_stage1_validation validates ETAPA 1 without training/hardware.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = char(paths.matlabRoot);
repoRoot = char(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage1_validation");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss")));
if ~isfolder(runDir)
    mkdir(runDir);
end

clearConfigurablesOverride();
rng(options.seed, "twister");

testResults = runtests(fullfile(matlabRoot, "tests", "no_glove"), ...
    "IncludeSubfolders", true);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage1_validation:TestsFailed", ...
        "At least one ETAPA 1 unit test failed. See %s", runDir);
end

profile = buildNoGloveStage1Override(options.seed);
setConfigurablesOverride(profile);
effectiveConfigs = configurables();
assertSafeProfile(effectiveConfigs);
rng(options.seed, "twister");

[emgSet, gloveSet] = getDataset( ...
    effectiveConfigs.dataset, effectiveConfigs.dataset_folder, ...
    effectiveConfigs.referenceSource);
if ~isempty(gloveSet)
    error("run_no_glove_stage1_validation:UnexpectedGloveData", ...
        "The EMG-only loader returned glove data.");
end

env = Env(runDir, true, emgSet, {});
if ~isa(env.prosthesis, "SimController") || ~isa(env.myo, "RecordedMyo")
    error("run_no_glove_stage1_validation:UnsafeDevice", ...
        "Validation requires SimController and RecordedMyo.");
end

episodeRows = repmat(struct( ...
    "episode", 0, ...
    "steps", 0, ...
    "meanReward", NaN, ...
    "trackingMse", NaN, ...
    "saturationFraction", NaN, ...
    "referenceHeld", false, ...
    "endedByMyo", false), options.numEpisodes, 1);

for episodeIdx = 1:options.numEpisodes
    observation = reset(env);
    initialTarget = env.intentTarget;
    if any(~isfinite(observation), "all")
        error("run_no_glove_stage1_validation:NonfiniteObservation", ...
            "Initial observation is not finite.");
    end

    isDone = false;
    stepCount = 0;
    rewards = nan(effectiveConfigs.maxNumberStepsInEpisodes, 1);
    while ~isDone && stepCount < effectiveConfigs.maxNumberStepsInEpisodes
        stepCount = stepCount + 1;
        [observation, rewards(stepCount), isDone] = step(env, zeros(4, 1));
        if any(~isfinite(observation), "all") || ~isfinite(rewards(stepCount))
            error("run_no_glove_stage1_validation:NonfiniteTransition", ...
                "Episode %d step %d produced nonfinite data.", ...
                episodeIdx, stepCount);
        end
    end
    if ~isDone
        error("run_no_glove_stage1_validation:EpisodeDidNotFinish", ...
            "Episode %d did not finish within the configured limit.", episodeIdx);
    end

    usedReferences = env.referenceHistory(1:env.referenceHistoryCount, :);
    expectedReferences = repmat(initialTarget(:)', stepCount, 1);
    referenceHeld = isequal(size(usedReferences), size(expectedReferences)) && ...
        all(abs(usedReferences - expectedReferences) < 1e-12, "all");
    if ~referenceHeld || env.referenceHistoryCount ~= stepCount
        error("run_no_glove_stage1_validation:ReferenceDrift", ...
            "The ETAPA 1 hold reference changed during episode %d.", episodeIdx);
    end
    if any(env.actionPwmLog(1:stepCount, :) ~= 0, "all")
        error("run_no_glove_stage1_validation:UnexpectedPwm", ...
            "Zero scripted actions must produce zero simulated PWM.");
    end

    episodeRows(episodeIdx) = struct( ...
        "episode", episodeIdx, ...
        "steps", stepCount, ...
        "meanReward", mean(rewards(1:stepCount)), ...
        "trackingMse", mean(env.trackingMseLog(1:stepCount)), ...
        "saturationFraction", mean(env.saturationFractionLog(1:stepCount)), ...
        "referenceHeld", referenceHeld, ...
        "endedByMyo", env.myo.exhausted);
end

episodeSummary = struct2table(episodeRows);
writetable(episodeSummary, fullfile(runDir, "episode_summary.csv"));
effectiveConfigPath = fullfile(runDir, "effective_config.mat");
save(effectiveConfigPath, "effectiveConfigs", "profile");

datasetPath = fullfile(matlabRoot, "data", "datasets", ...
    "Denis Dataset", "DENIS.mat");
[gitCommit, gitDirty] = getGitState(repoRoot);
manifest = struct( ...
    "stage", 1, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, ...
    "gitDirty", gitDirty, ...
    "matlabVersion", string(version), ...
    "seed", options.seed, ...
    "referenceSource", effectiveConfigs.referenceSource, ...
    "referenceScaffold", "holdInitialEncoder", ...
    "dataset", "DENIS", ...
    "datasetPath", string(datasetPath), ...
    "datasetSha256", fileSha256(datasetPath), ...
    "effectiveConfigPath", string(effectiveConfigPath), ...
    "effectiveConfigSha256", fileSha256(effectiveConfigPath), ...
    "scriptedAction", "zeros(4,1)", ...
    "numEpisodes", options.numEpisodes, ...
    "runTraining", false, ...
    "simMotors", true, ...
    "usePrerecorded", true, ...
    "connectGlove", false, ...
    "hardwareUsed", false, ...
    "checkpointUsed", "", ...
    "outputPath", string(runDir));

save(fullfile(runDir, "manifest.mat"), "manifest", "episodeSummary");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));
reproducibleCommand = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage1_validation(struct('seed',%d," + ...
    "'numEpisodes',%d,'resultsRoot','%s'))", ...
    strrep(matlabRoot, "'", "''"), options.seed, options.numEpisodes, ...
    strrep(char(options.resultsRoot), "'", "''"));
writeText(fullfile(runDir, "reproducible_command.txt"), reproducibleCommand);

report = struct( ...
    "result", "PASS", ...
    "outputPath", string(runDir), ...
    "manifest", manifest, ...
    "episodeSummary", episodeSummary, ...
    "testResults", testResults);

fprintf("ETAPA 1 validation PASS\n");
fprintf("Output: %s\n", runDir);
disp(episodeSummary);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage1_validation:InvalidOptions", ...
        "options must be a scalar struct.");
end
allowedFields = ["seed", "numEpisodes", "resultsRoot"];
unknownFields = setdiff(string(fieldnames(options)), allowedFields);
if ~isempty(unknownFields)
    error("run_no_glove_stage1_validation:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknownFields, ", "));
end
defaults = struct("seed", 11, "numEpisodes", 2, "resultsRoot", "");
defaultFields = fieldnames(defaults);
for i = 1:numel(defaultFields)
    fieldName = defaultFields{i};
    if ~isfield(options, fieldName) || isempty(options.(fieldName))
        options.(fieldName) = defaults.(fieldName);
    end
end
if ~isnumeric(options.seed) || ~isscalar(options.seed) || ...
        ~isfinite(options.seed) || options.seed < 0 || fix(options.seed) ~= options.seed
    error("run_no_glove_stage1_validation:InvalidSeed", ...
        "seed must be a nonnegative integer.");
end
if ~isnumeric(options.numEpisodes) || ~isscalar(options.numEpisodes) || ...
        ~isfinite(options.numEpisodes) || options.numEpisodes < 1 || ...
        fix(options.numEpisodes) ~= options.numEpisodes
    error("run_no_glove_stage1_validation:InvalidEpisodeCount", ...
        "numEpisodes must be a positive integer.");
end
options.resultsRoot = string(options.resultsRoot);
if ~isscalar(options.resultsRoot) || ismissing(options.resultsRoot)
    error("run_no_glove_stage1_validation:InvalidResultsRoot", ...
        "resultsRoot must be a scalar string or character vector.");
end
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end

function assertSafeProfile(configs)
if configs.run_training || configs.newTraining || ...
        ~configs.usePrerecorded || ~configs.simMotors || configs.connect_glove || ...
        configs.referenceSource ~= "emgIntent" || ...
        configs.actionInterfaceVariant ~= "baselineQuantized" || ...
        configs.rewardType ~= "trackingMseActionRateReward" || ...
        configs.td3Residual.enabled
    error("run_no_glove_stage1_validation:UnsafeProfile", ...
        "The effective ETAPA 1 profile is not simulation-only EMG intent.");
end
end

function [commit, dirty] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status ~= 0
    commit = "unknown";
else
    commit = string(strtrim(output));
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
dirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function hash = fileSha256(filePath)
if ispc
    escapedPath = strrep(char(filePath), "'", "''");
    command = sprintf([ ...
        'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
        '-LiteralPath ''%s'').Hash"'], escapedPath);
else
    command = sprintf('sha256sum "%s"', char(filePath));
end
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage1_validation:HashFailed", ...
        "Could not calculate SHA-256 for %s.", filePath);
end
tokens = split(strtrim(string(output)));
hash = upper(tokens(1));
end

function writeText(filePath, content)
fid = fopen(filePath, "w");
if fid < 0
    error("run_no_glove_stage1_validation:WriteFailed", ...
        "Could not open %s for writing.", filePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s\n", content);
end
