function results = run_motor2_calibrated_action_ablation(options)
%run_motor2_calibrated_action_ablation tests calibrated action quantization.
%
% This launcher is simulation-only. It does not promote the calibrated
% interface; it compares it against current baseline action handling.

arguments
    options = struct()
end

paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = char(paths.matlabRoot);
workspaceRoot = char(paths.workspaceRoot);
cd(matlabRoot);
addpath(genpath(matlabRoot));
clearConfigurablesOverride();

baseConfigs = configurables();
options = localNormalizeOptions(options, baseConfigs);

resultsRoot = localResolveResultsRoot(options.resultsRoot, workspaceRoot);
summaryRoot = fullfile(resultsRoot, "summary");
figuresRoot = fullfile(resultsRoot, "figures");
ensureDirectoryExists(resultsRoot);
ensureDirectoryExists(summaryRoot);
ensureDirectoryExists(figuresRoot);

allConfigs = localBuildAblationConfigs(options);
configsToRun = localSelectInitialConfigs(allConfigs, options);
seedTables = {};
configResults = {};
skippedConfigs = strings(0, 1);

for configIdx = 1:numel(configsToRun)
    [seedTables, configResults] = localRunConfig( ...
        configsToRun(configIdx), options, resultsRoot, seedTables, configResults);
end

if isempty(options.configNames)
    partialSummary = localSummarizeAblations(vertcat(seedTables{:}));
    weightedConfig = allConfigs(string({allConfigs.label}) == "motor_calibrated_weighted");
    if options.forceWeightedCalibrated || localShouldRunWeighted(partialSummary)
        [seedTables, configResults] = localRunConfig( ...
            weightedConfig, options, resultsRoot, seedTables, configResults);
    else
        skippedConfigs(end+1, 1) = "motor_calibrated_weighted";
    end
end

perSeedTable = vertcat(seedTables{:});
ablationSummary = localSummarizeAblations(perSeedTable);
referenceTable = localBuildReferenceTable(ablationSummary);

summaryCsvPath = fullfile(summaryRoot, "calibrated_action_ablation_summary.csv");
summaryTxtPath = fullfile(summaryRoot, "calibrated_action_ablation_summary.txt");
matPath = fullfile(summaryRoot, "calibrated_action_ablation_results.mat");
motor2FigurePath = fullfile(figuresRoot, "calibrated_action_ablation_motor2.png");
comparisonFigurePath = fullfile(figuresRoot, ...
    "calibrated_action_ablation_final_comparison.png");

writetable(ablationSummary, summaryCsvPath);
writetable(referenceTable, fullfile(summaryRoot, ...
    "calibrated_action_ablation_final_comparison.csv"));
localCreateMotor2SummaryFigure(ablationSummary, motor2FigurePath);
localCreateFinalComparisonFigure(referenceTable, comparisonFigurePath);
localWriteTextFile(summaryTxtPath, localBuildSummaryText( ...
    options, ablationSummary, skippedConfigs, resultsRoot));

results = struct();
results.resultsRoot = string(resultsRoot);
results.summaryRoot = string(summaryRoot);
results.figuresRoot = string(figuresRoot);
results.options = options;
results.configResults = configResults;
results.perSeedTable = perSeedTable;
results.ablationSummary = ablationSummary;
results.referenceTable = referenceTable;
results.skippedConfigs = skippedConfigs;
results.figurePaths = struct( ...
    "motor2Summary", string(motor2FigurePath), ...
    "finalComparison", string(comparisonFigurePath));

save(matPath, "results", "perSeedTable", "ablationSummary", ...
    "referenceTable", "options", "configResults", "skippedConfigs");
end

function options = localNormalizeOptions(options, baseConfigs)
defaults = struct( ...
    "seeds", [11 22 55], ...
    "trainingEpisodes", 3000, ...
    "trainingSaveEvery", 100, ...
    "episodeSaveFreq", 100, ...
    "auditFastSimulations", 5, ...
    "auditFullSimulations", 10, ...
    "auditTopK", 5, ...
    "finalTestEpisodes", 20, ...
    "plotEpisodeOnTest", true, ...
    "useGpu", true, ...
    "selectionMode", "motor2_aware", ...
    "forceWeightedCalibrated", false, ...
    "configNames", string.empty(1, 0), ...
    "resultsRoot", "", ...
    "actionCommandLevels", baseConfigs.actionCommandLevels, ...
    "actionCommandLevelsByMotor", baseConfigs.actionCommandLevelsByMotor);

fields = fieldnames(defaults);
for i = 1:numel(fields)
    if ~isfield(options, fields{i}) || isempty(options.(fields{i}))
        options.(fields{i}) = defaults.(fields{i});
    end
end

options.seeds = double(options.seeds(:))';
options.trainingEpisodes = double(options.trainingEpisodes);
options.trainingSaveEvery = double(options.trainingSaveEvery);
options.episodeSaveFreq = double(options.episodeSaveFreq);
options.auditFastSimulations = max(1, double(options.auditFastSimulations));
options.auditFullSimulations = max(1, double(options.auditFullSimulations));
options.auditTopK = max(1, double(options.auditTopK));
options.finalTestEpisodes = max(1, double(options.finalTestEpisodes));
options.plotEpisodeOnTest = logical(options.plotEpisodeOnTest);
options.useGpu = logical(options.useGpu);
options.selectionMode = lower(string(options.selectionMode));
options.forceWeightedCalibrated = logical(options.forceWeightedCalibrated);
options.configNames = string(options.configNames);
options.resultsRoot = string(options.resultsRoot);
options.actionCommandLevels = double(options.actionCommandLevels(:))';
options.actionCommandLevelsByMotor = localNormalizeActionLevelsByMotor( ...
    options.actionCommandLevelsByMotor, options.actionCommandLevels);

if isempty(options.seeds)
    error("options.seeds must contain at least one seed.");
end
if ~ismember(options.selectionMode, ["global", "motor2_aware"])
    error("Unsupported selectionMode '%s'.", options.selectionMode);
end
end

function configs = localBuildAblationConfigs(options)
baseLevels = options.actionCommandLevels;
levelsByMotor = options.actionCommandLevelsByMotor;
configs = [ ...
    struct( ...
        "label", "baseline_current", ...
        "rewardType", "trackingMseActionRateReward", ...
        "rewardMotorWeights", [1 2 1 1], ...
        "rewardActionMotorWeights", [1 1 1 1], ...
        "rewardDeltaActionMotorWeights", [1 1 1 1], ...
        "quantizeCommandsForSimulation", true, ...
        "actionInterfaceVariant", "baselineQuantized", ...
        "actionCommandLevels", baseLevels, ...
        "actionCommandLevelsByMotor", levelsByMotor), ...
    struct( ...
        "label", "continuous_action_baseline", ...
        "rewardType", "trackingMseActionRateReward", ...
        "rewardMotorWeights", [1 2 1 1], ...
        "rewardActionMotorWeights", [1 1 1 1], ...
        "rewardDeltaActionMotorWeights", [1 1 1 1], ...
        "quantizeCommandsForSimulation", false, ...
        "actionInterfaceVariant", "baselineQuantized", ...
        "actionCommandLevels", baseLevels, ...
        "actionCommandLevelsByMotor", levelsByMotor), ...
    struct( ...
        "label", "motor_calibrated_quantized", ...
        "rewardType", "trackingMseActionRateReward", ...
        "rewardMotorWeights", [1 2 1 1], ...
        "rewardActionMotorWeights", [1 1 1 1], ...
        "rewardDeltaActionMotorWeights", [1 1 1 1], ...
        "quantizeCommandsForSimulation", true, ...
        "actionInterfaceVariant", "motorCalibratedQuantized", ...
        "actionCommandLevels", baseLevels, ...
        "actionCommandLevelsByMotor", levelsByMotor), ...
    struct( ...
        "label", "motor_calibrated_weighted", ...
        "rewardType", "trackingMseActionRateMotorWeightedReward", ...
        "rewardMotorWeights", [1 2 1 1], ...
        "rewardActionMotorWeights", [1 1 1 1], ...
        "rewardDeltaActionMotorWeights", [1 1 1 1], ...
        "quantizeCommandsForSimulation", true, ...
        "actionInterfaceVariant", "motorCalibratedQuantized", ...
        "actionCommandLevels", baseLevels, ...
        "actionCommandLevelsByMotor", levelsByMotor)];
end

function configsToRun = localSelectInitialConfigs(allConfigs, options)
if ~isempty(options.configNames)
    keep = ismember(string({allConfigs.label}), options.configNames);
    configsToRun = allConfigs(keep);
    if isempty(configsToRun)
        error("No calibrated action ablation configs selected.");
    end
    return;
end

configsToRun = allConfigs(1:3);
end

function [seedTables, configResults] = localRunConfig( ...
        cfg, options, resultsRoot, seedTables, configResults)
configRoot = fullfile(resultsRoot, char(cfg.label));
runOptions = struct( ...
    "seeds", options.seeds, ...
    "trainingEpisodes", options.trainingEpisodes, ...
    "trainingSaveEvery", options.trainingSaveEvery, ...
    "episodeSaveFreq", options.episodeSaveFreq, ...
    "auditFastSimulations", options.auditFastSimulations, ...
    "auditFullSimulations", options.auditFullSimulations, ...
    "auditTopK", options.auditTopK, ...
    "finalTestEpisodes", options.finalTestEpisodes, ...
    "plotEpisodeOnTest", options.plotEpisodeOnTest, ...
    "useGpu", options.useGpu, ...
    "selectionMode", options.selectionMode, ...
    "rewardType", cfg.rewardType, ...
    "rewardMotorWeights", cfg.rewardMotorWeights, ...
    "rewardActionMotorWeights", cfg.rewardActionMotorWeights, ...
    "rewardDeltaActionMotorWeights", cfg.rewardDeltaActionMotorWeights, ...
    "quantizeCommandsForSimulation", cfg.quantizeCommandsForSimulation, ...
    "actionInterfaceVariant", cfg.actionInterfaceVariant, ...
    "actionCommandLevels", cfg.actionCommandLevels, ...
    "actionCommandLevelsByMotor", cfg.actionCommandLevelsByMotor, ...
    "configLabel", cfg.label, ...
    "runMotor2SanityCheck", false, ...
    "evaluateReferenceCheckpoints", false, ...
    "generateReport", false, ...
    "compileReport", false, ...
    "resultsRoot", string(configRoot));

result = run_benchmark_td3_seeded_retrain_motor2_diagnostic(runOptions);
configResults{end+1, 1} = result;
seedTables{end+1, 1} = result.perSeedTable;
end

function levelsByMotor = localNormalizeActionLevelsByMotor(levelsByMotor, fallbackLevels)
if iscell(levelsByMotor)
    tmp = struct();
    for motorIdx = 1:min(4, numel(levelsByMotor))
        tmp.(sprintf("m%d", motorIdx)) = double(levelsByMotor{motorIdx}(:))';
    end
    levelsByMotor = tmp;
end
if ~isstruct(levelsByMotor)
    levelsByMotor = struct();
end
for motorIdx = 1:4
    fieldName = sprintf("m%d", motorIdx);
    if ~isfield(levelsByMotor, fieldName) || isempty(levelsByMotor.(fieldName))
        levelsByMotor.(fieldName) = fallbackLevels;
    else
        levelsByMotor.(fieldName) = double(levelsByMotor.(fieldName)(:))';
    end
end
end

function shouldRun = localShouldRunWeighted(summaryTable)
baseline = summaryTable(string(summaryTable.configLabel) == "baseline_current", :);
calibrated = summaryTable(string(summaryTable.configLabel) == ...
    "motor_calibrated_quantized", :);
if isempty(baseline) || isempty(calibrated)
    shouldRun = false;
    return;
end

improvesFlags = calibrated.motor2_flat_response_count < ...
    baseline.motor2_flat_response_count || ...
    calibrated.motor2_action_no_motion_count < ...
    baseline.motor2_action_no_motion_count;
improvesRange = calibrated.responseRange_motor2 > baseline.responseRange_motor2;
trackingOk = calibrated.trackingMSE_motor2 <= 1.10 * baseline.trackingMSE_motor2;
shouldRun = (improvesFlags || improvesRange) && trackingOk;
end

function summaryTable = localSummarizeAblations(perSeedTable)
configLabels = unique(string(perSeedTable.configLabel), "stable");
rows = cell(numel(configLabels), 1);
for i = 1:numel(configLabels)
    idx = string(perSeedTable.configLabel) == configLabels(i);
    subset = perSeedTable(idx, :);
    rows{i} = struct( ...
        "configLabel", configLabels(i), ...
        "numSeeds", height(subset), ...
        "trackingMSE", mean(double(subset.trackingMSE), "omitnan"), ...
        "trackingMAE", mean(double(subset.trackingMAE), "omitnan"), ...
        "actionL2", mean(double(subset.actionL2), "omitnan"), ...
        "saturationFraction", mean(double(subset.saturationFraction), "omitnan"), ...
        "deltaActionL2", mean(double(subset.deltaActionL2), "omitnan"), ...
        "trackingMSE_motor2", mean(double(subset.trackingMSE_motor2), "omitnan"), ...
        "responseRange_motor2", mean(double(subset.responseRange_motor2), "omitnan"), ...
        "targetRange_motor2", mean(double(subset.targetRange_motor2), "omitnan"), ...
        "motor2_flat_response_count", sum(logical(subset.motor2_flat_response)), ...
        "motor2_action_no_motion_count", sum(logical(subset.motor2_action_no_motion)), ...
        "motor2_tracking_outlier_count", sum(logical(subset.motor2_tracking_outlier)));
end
summaryTable = struct2table(vertcat(rows{:}));
summaryTable.acceptedCalibration = localEvaluateAcceptance(summaryTable);
end

function accepted = localEvaluateAcceptance(summaryTable)
accepted = false(height(summaryTable), 1);
baseline = summaryTable(string(summaryTable.configLabel) == "baseline_current", :);
if isempty(baseline)
    return;
end

for i = 1:height(summaryTable)
    if string(summaryTable.configLabel(i)) == "baseline_current"
        continue;
    end
    accepted(i) = ...
        summaryTable.motor2_flat_response_count(i) <= ...
            baseline.motor2_flat_response_count && ...
        summaryTable.motor2_action_no_motion_count(i) <= ...
            baseline.motor2_action_no_motion_count && ...
        summaryTable.responseRange_motor2(i) > baseline.responseRange_motor2 && ...
        summaryTable.trackingMSE_motor2(i) <= baseline.trackingMSE_motor2 && ...
        summaryTable.trackingMSE(i) <= 1.10 * baseline.trackingMSE && ...
        summaryTable.saturationFraction(i) <= 1.15 * baseline.saturationFraction;
end
end

function referenceTable = localBuildReferenceTable(ablationSummary)
benchmark = getAgent7250Benchmark();
rows = cell(height(ablationSummary) + 1, 1);
rows{1} = struct( ...
    "candidateLabel", "Agent7250", ...
    "trackingMSE", benchmark.trackingMse, ...
    "trackingMAE", benchmark.trackingMae, ...
    "actionL2", benchmark.actionL2, ...
    "saturationFraction", benchmark.saturationFraction, ...
    "deltaActionL2", benchmark.deltaActionL2, ...
    "trackingMSE_motor2", NaN, ...
    "responseRange_motor2", NaN);
for i = 1:height(ablationSummary)
    rows{i+1} = struct( ...
        "candidateLabel", string(ablationSummary.configLabel(i)), ...
        "trackingMSE", double(ablationSummary.trackingMSE(i)), ...
        "trackingMAE", double(ablationSummary.trackingMAE(i)), ...
        "actionL2", double(ablationSummary.actionL2(i)), ...
        "saturationFraction", double(ablationSummary.saturationFraction(i)), ...
        "deltaActionL2", double(ablationSummary.deltaActionL2(i)), ...
        "trackingMSE_motor2", double(ablationSummary.trackingMSE_motor2(i)), ...
        "responseRange_motor2", double(ablationSummary.responseRange_motor2(i)));
end
referenceTable = struct2table(vertcat(rows{:}));
end

function localCreateMotor2SummaryFigure(summaryTable, figurePath)
[figureDir, ~, ~] = fileparts(figurePath);
if strlength(string(figureDir)) > 0 && ~exist(figureDir, "dir")
    mkdir(figureDir);
end

labels = string(summaryTable.configLabel);
f = figure("Visible", "off", "Color", "w", "Position", [100 100 1400 850]);
tiledlayout(f, 1, 3, "TileSpacing", "compact", "Padding", "compact");

bar(nexttile, categorical(labels), summaryTable.trackingMSE_motor2);
title("Motor 2 tracking MSE");
grid on;

bar(nexttile, categorical(labels), summaryTable.responseRange_motor2);
title("Motor 2 response range");
grid on;

bar(nexttile, categorical(labels), [ ...
    summaryTable.motor2_flat_response_count, ...
    summaryTable.motor2_action_no_motion_count]);
title("Motor 2 flags");
legend(["flat", "action-no-motion"], "Location", "best");
grid on;

sgtitle(f, "Calibrated action ablation - motor 2");
exportgraphics(f, figurePath, "Resolution", 220);
close(f);
end

function localCreateFinalComparisonFigure(referenceTable, figurePath)
[figureDir, ~, ~] = fileparts(figurePath);
if strlength(string(figureDir)) > 0 && ~exist(figureDir, "dir")
    mkdir(figureDir);
end

labels = string(referenceTable.candidateLabel);
f = figure("Visible", "off", "Color", "w", "Position", [100 100 1400 850]);
tiledlayout(f, 1, 3, "TileSpacing", "compact", "Padding", "compact");

bar(nexttile, categorical(labels), referenceTable.trackingMSE);
title("Global tracking MSE");
grid on;

bar(nexttile, categorical(labels), referenceTable.saturationFraction);
title("Saturation fraction");
grid on;

bar(nexttile, categorical(labels), referenceTable.responseRange_motor2);
title("Motor 2 response range");
grid on;

sgtitle(f, "Calibrated action ablation final comparison");
exportgraphics(f, figurePath, "Resolution", 220);
close(f);
end

function text = localBuildSummaryText(options, summaryTable, skippedConfigs, resultsRoot)
lines = strings(0, 1);
lines(end+1) = "Motor 2 calibrated action ablation";
lines(end+1) = "Results root: " + string(resultsRoot);
lines(end+1) = "Seeds: " + mat2str(options.seeds);
lines(end+1) = "Training episodes: " + string(options.trainingEpisodes);
lines(end+1) = "Final test episodes: " + string(options.finalTestEpisodes);
lines(end+1) = "Selection mode: " + string(options.selectionMode);
if ~isempty(skippedConfigs)
    lines(end+1) = "Skipped configs: " + strjoin(skippedConfigs.', ", ");
end
lines(end+1) = "";
for i = 1:height(summaryTable)
    lines(end+1) = sprintf( ...
        "%s: trackingMSE=%.6f, motor2MSE=%.6f, motor2Range=%.6f, flat=%d, actionNoMotion=%d, accepted=%d", ...
        string(summaryTable.configLabel(i)), ...
        summaryTable.trackingMSE(i), ...
        summaryTable.trackingMSE_motor2(i), ...
        summaryTable.responseRange_motor2(i), ...
        summaryTable.motor2_flat_response_count(i), ...
        summaryTable.motor2_action_no_motion_count(i), ...
        summaryTable.acceptedCalibration(i));
end
text = strjoin(lines, newline);
end

function localWriteTextFile(filePath, text)
fid = fopen(filePath, "w");
if fid < 0
    error("Could not write %s", filePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s\n", text);
end

function resultsRoot = localResolveResultsRoot(resultsRootOption, workspaceRoot)
if strlength(string(resultsRootOption)) > 0
    resultsRoot = char(string(resultsRootOption));
else
    resultsRoot = fullfile(workspaceRoot, "Agentes", ...
        "motor2_calibrated_action_ablation", ...
        string(datetime("now", "Format", "yy-MM-dd_HH-mm-ss")));
end
end
