function report = run_no_glove_stage7a_lag_confirmation(options)
%run_no_glove_stage7a_lag_confirmation executes the ETAPA 7A gate only.
%
% The launcher confirms fixed lags with held-out repetitions and identical
% support for every lag. It does not execute compensation, filtering, DTW,
% an agent, Env, simulator, reward, training or hardware.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));
clearConfigurablesOverride();
rng(options.seed, "twister");

[stage7Manifest, stage7ManifestPath, stage7ResultsPath, ...
    stage6cResultsPath] = loadAndValidateInput(options.stage7RunRoot);
stage7HashBefore = fileSha256(stage7ResultsPath);
stage6cHashBefore = fileSha256(stage6cResultsPath);

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7a_lag_confirmation");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runDir)
    error("run_no_glove_stage7a_lag_confirmation:OutputExists", ...
        "Refusing to reuse output directory %s.", runDir);
end
mkdir(runDir);

testPath = fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage7aLagConfirmation.m");
testResults = runtests(testPath);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7a_lag_confirmation:TestsFailed", ...
        "ETAPA 7A tests failed; analysis is forbidden. See %s.", runDir);
end

source = load(stage6cResultsPath, "acceptance");
analysisOptions = struct( ...
    "targetMotors", options.targetMotors, ...
    "targetRegimes", options.targetRegimes, ...
    "maxLagSteps", options.maxLagSteps, ...
    "activeVelocityThreshold", options.activeVelocityThreshold, ...
    "minimumSamplesPerFold", options.minimumSamplesPerFold, ...
    "minimumBenefitFraction", options.minimumBenefitFraction, ...
    "minimumMaterialFoldFraction", ...
        options.minimumMaterialFoldFraction, ...
    "minimumSignConsistency", options.minimumSignConsistency, ...
    "maximumBoundaryFraction", options.maximumBoundaryFraction, ...
    "periodSec", options.periodSec);
analysisArguments = namedargs2cell(analysisOptions);
analysisTic = tic;
analysis = analyzeNoGloveStage7aLagConfirmation( ...
    source.acceptance.componentTable, "acceptance", ...
    analysisArguments{:});
analysisElapsedSec = toc(analysisTic);

stage7HashAfter = fileSha256(stage7ResultsPath);
stage6cHashAfter = fileSha256(stage6cResultsPath);
if stage7HashAfter ~= stage7HashBefore || ...
        stage6cHashAfter ~= stage6cHashBefore
    error("run_no_glove_stage7a_lag_confirmation:InputModified", ...
        "An immutable ETAPA 7/6C input changed during ETAPA 7A.");
end

writetable(analysis.calibrationLagTable, ...
    fullfile(runDir, "calibration_lags.csv"));
writetable(analysis.foldEvaluationTable, ...
    fullfile(runDir, "held_out_fold_evaluation.csv"));
writetable(analysis.confirmationSummary, ...
    fullfile(runDir, "lag_confirmation_summary.csv"));
writetable(analysis.sourceDecision, ...
    fullfile(runDir, "source_decision.csv"));

primaryDecision = analysis.primaryDecision;
causalCompensationGatePassed = ...
    logical(primaryDecision.causalCompensationCandidate);
compensationInterventionExecuted = false;
filteredReferenceInterventionExecuted = false;
dtwCalculated = false;
stage8Authorized = false;

save(fullfile(runDir, "stage7a_results.mat"), ...
    "analysis", "analysisOptions", "primaryDecision", ...
    "causalCompensationGatePassed", ...
    "compensationInterventionExecuted", ...
    "filteredReferenceInterventionExecuted", "dtwCalculated", ...
    "stage8Authorized", "stage7Manifest", "analysisElapsedSec", ...
    "-v7.3");

reproducibleCommand = buildReproducibleCommand( ...
    matlabRoot, options, fileparts(runDir));
writeText(fullfile(runDir, "reproducible_command.txt"), ...
    reproducibleCommand);
writeOfflineReport(fullfile(runDir, "offline_report.md"), ...
    analysis, analysisOptions, analysisElapsedSec, runDir);

primaryArtifacts = ["calibration_lags.csv", ...
    "held_out_fold_evaluation.csv", "lag_confirmation_summary.csv", ...
    "source_decision.csv", "stage7a_results.mat", "test_results.mat", ...
    "reproducible_command.txt", "offline_report.md"];
artifactHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(primaryArtifacts), 1);
for artifactIdx = 1:numel(primaryArtifacts)
    artifactHashes(artifactIdx).path = primaryArtifacts(artifactIdx);
    artifactHashes(artifactIdx).sha256 = fileSha256( ...
        fullfile(runDir, primaryArtifacts(artifactIdx)));
end
writetable(struct2table(artifactHashes), ...
    fullfile(runDir, "artifact_hashes.csv"));

[gitCommit, gitDirty, trackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", "7A", ...
    "schemaVersion", 1, ...
    "result", "PASS", ...
    "scientificGateResult", string(primaryDecision.classification), ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, ...
    "gitDirty", gitDirty, ...
    "gitTrackedDirty", trackedDirty, ...
    "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7a_lag_confirmation", ...
    "seed", options.seed, ...
    "inputStage7RunRoot", options.stage7RunRoot, ...
    "inputStage7ManifestPath", stage7ManifestPath, ...
    "inputStage7ManifestSha256", fileSha256(stage7ManifestPath), ...
    "inputStage7ResultsPath", stage7ResultsPath, ...
    "inputStage7ResultsSha256Before", stage7HashBefore, ...
    "inputStage7ResultsSha256After", stage7HashAfter, ...
    "inputStage6cResultsPath", stage6cResultsPath, ...
    "inputStage6cResultsSha256Before", stage6cHashBefore, ...
    "inputStage6cResultsSha256After", stage6cHashAfter, ...
    "inputsPreserved", true, ...
    "analysisOptions", analysisOptions, ...
    "heldOutFoldVariable", analysis.heldOutFoldVariable, ...
    "heldOutRepetitions", analysis.heldOutRepetitions, ...
    "primaryCommandSource", "Agent200", ...
    "primaryClassification", primaryDecision.classification, ...
    "primaryConfirmedFixedLagCount", ...
        primaryDecision.confirmedFixedLagCount, ...
    "primaryCausalCandidateCount", primaryDecision.causalCandidateCount, ...
    "primaryUnresolvedCount", primaryDecision.unresolvedCount, ...
    "causalCompensationGatePassed", causalCompensationGatePassed, ...
    "compensationInterventionExecuted", ...
        compensationInterventionExecuted, ...
    "filteredReferenceInterventionExecuted", ...
        filteredReferenceInterventionExecuted, ...
    "dtwCalculated", dtwCalculated, ...
    "dtwRewardUsed", false, ...
    "stage8Authorized", stage8Authorized, ...
    "stateChanged", false, ...
    "rewardChanged", false, ...
    "policyChanged", false, ...
    "referenceChanged", false, ...
    "quantizationChanged", false, ...
    "simulatorChanged", false, ...
    "simMotors", true, ...
    "runTraining", false, ...
    "agentLoaded", false, ...
    "reinforcementLearningInvoked", false, ...
    "envCreated", false, ...
    "simulatorInvoked", false, ...
    "rewardInvoked", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "agent7250Loaded", false, ...
    "hardwareUsed", false, ...
    "analysisElapsedSec", analysisElapsedSec, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "artifactHashes", artifactHashes, ...
    "outputPath", runDir);
save(fullfile(runDir, "manifest.mat"), "manifest", "artifactHashes");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct( ...
    "result", "PASS", ...
    "outputPath", runDir, ...
    "manifest", manifest, ...
    "analysis", analysis, ...
    "primaryDecision", primaryDecision, ...
    "testResults", testResults);
fprintf("ETAPA 7A HELD-OUT LAG CONFIRMATION PASS\n");
fprintf("Output: %s\n", runDir);
disp(analysis.confirmationSummary);
disp(analysis.sourceDecision);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7a_lag_confirmation:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "stage7RunRoot", "", "resultsRoot", "", "seed", 7171, ...
    "targetMotors", [2 3], ...
    "targetRegimes", ["opening" "closing"], ...
    "maxLagSteps", 5, "activeVelocityThreshold", 0.005, ...
    "minimumSamplesPerFold", 10, ...
    "minimumBenefitFraction", 0.05, ...
    "minimumMaterialFoldFraction", 2/3, ...
    "minimumSignConsistency", 0.80, ...
    "maximumBoundaryFraction", 0.50, "periodSec", 0.2);
unknown = setdiff(string(fieldnames(options)), ...
    string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7a_lag_confirmation:UnknownOption", ...
        "Unknown option(s): %s.", strjoin(unknown, ", "));
end
fields = fieldnames(defaults);
for fieldIdx = 1:numel(fields)
    name = fields{fieldIdx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.stage7RunRoot = string(options.stage7RunRoot);
options.resultsRoot = string(options.resultsRoot);
options.targetRegimes = string(options.targetRegimes);
if ~isscalar(options.stage7RunRoot) || ...
        strlength(options.stage7RunRoot) == 0
    error("run_no_glove_stage7a_lag_confirmation:MissingInput", ...
        "stage7RunRoot is required.");
end
integerFields = ["seed", "maxLagSteps", "minimumSamplesPerFold"];
for fieldIdx = 1:numel(integerFields)
    name = integerFields(fieldIdx);
    value = options.(name);
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
            value < 1 || fix(value) ~= value
        error("run_no_glove_stage7a_lag_confirmation:InvalidOption", ...
            "%s must be a positive integer.", name);
    end
end
numericFields = ["activeVelocityThreshold", "minimumBenefitFraction", ...
    "minimumMaterialFoldFraction", "minimumSignConsistency", ...
    "maximumBoundaryFraction", "periodSec"];
for fieldIdx = 1:numel(numericFields)
    name = numericFields(fieldIdx);
    value = options.(name);
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value <= 0
        error("run_no_glove_stage7a_lag_confirmation:InvalidOption", ...
            "%s must be finite and positive.", name);
    end
end
fractionFields = ["minimumBenefitFraction", ...
    "minimumMaterialFoldFraction", "minimumSignConsistency", ...
    "maximumBoundaryFraction"];
for fieldIdx = 1:numel(fractionFields)
    if options.(fractionFields(fieldIdx)) > 1
        error("run_no_glove_stage7a_lag_confirmation:InvalidOption", ...
            "%s must not exceed one.", fractionFields(fieldIdx));
    end
end
end

function [manifest, manifestPath, resultsPath, stage6cResultsPath] = ...
        loadAndValidateInput(stage7RunRoot)
manifestPath = fullfile(stage7RunRoot, "manifest.json");
resultsPath = fullfile(stage7RunRoot, "stage7_results.mat");
if ~isfile(manifestPath) || ~isfile(resultsPath)
    error("run_no_glove_stage7a_lag_confirmation:InputNotFound", ...
        "ETAPA 7 manifest/results are missing from %s.", stage7RunRoot);
end
manifest = jsondecode(fileread(manifestPath));
required = ["stage", "result", "temporalBenefitGatePassed", ...
    "cancelDtwRewardStages", "stage8Authorized", "hardwareUsed", ...
    "inputResultsPath", "inputResultsSha256After", "artifactHashes"];
if ~all(isfield(manifest, cellstr(required)))
    error("run_no_glove_stage7a_lag_confirmation:InvalidManifest", ...
        "Input manifest lacks the ETAPA 7 audit contract.");
end
valid = double(manifest.stage) == 7 && string(manifest.result) == "PASS" && ...
    ~logical(manifest.temporalBenefitGatePassed) && ...
    logical(manifest.cancelDtwRewardStages) && ...
    ~logical(manifest.stage8Authorized) && ~logical(manifest.hardwareUsed);
if ~valid
    error("run_no_glove_stage7a_lag_confirmation:IncompatibleManifest", ...
        "ETAPA 7A requires the immutable no-DTW decision from ETAPA 7.");
end
expectedStage7Hash = findArtifactHash( ...
    manifest.artifactHashes, "stage7_results.mat");
if fileSha256(resultsPath) ~= expectedStage7Hash
    error("run_no_glove_stage7a_lag_confirmation:InputHashMismatch", ...
        "ETAPA 7 results do not match their manifest.");
end
stage6cResultsPath = string(manifest.inputResultsPath);
if ~isfile(stage6cResultsPath) || ...
        fileSha256(stage6cResultsPath) ~= ...
        upper(string(manifest.inputResultsSha256After))
    error("run_no_glove_stage7a_lag_confirmation:InputHashMismatch", ...
        "ETAPA 6C results do not match the hash inherited by ETAPA 7.");
end
end

function expected = findArtifactHash(artifactHashes, artifactName)
paths = string({artifactHashes.path});
match = paths == artifactName;
if sum(match) ~= 1
    error("run_no_glove_stage7a_lag_confirmation:HashNotFound", ...
        "Manifest does not contain one hash for %s.", artifactName);
end
expected = upper(string(artifactHashes(match).sha256));
end

function command = buildReproducibleCommand(matlabRoot, options, resultsRoot)
motors = sprintf("%d ", options.targetMotors);
regimes = strjoin(compose('"%s"', options.targetRegimes), " ");
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7a_lag_confirmation(struct(" + ...
    "'stage7RunRoot','%s','resultsRoot','%s','seed',%d," + ...
    "'targetMotors',[%s],'targetRegimes',[%s]," + ...
    "'maxLagSteps',%d,'activeVelocityThreshold',%.17g," + ...
    "'minimumSamplesPerFold',%d,'minimumBenefitFraction',%.17g," + ...
    "'minimumMaterialFoldFraction',%.17g," + ...
    "'minimumSignConsistency',%.17g," + ...
    "'maximumBoundaryFraction',%.17g,'periodSec',%.17g))", ...
    escape(matlabRoot), escape(options.stage7RunRoot), ...
    escape(resultsRoot), options.seed, strtrim(motors), regimes, ...
    options.maxLagSteps, options.activeVelocityThreshold, ...
    options.minimumSamplesPerFold, options.minimumBenefitFraction, ...
    options.minimumMaterialFoldFraction, ...
    options.minimumSignConsistency, options.maximumBoundaryFraction, ...
    options.periodSec);
end

function writeOfflineReport(pathValue, analysis, options, elapsedSec, runDir)
lines = strings(0, 1);
lines(end+1, 1) = "# ETAPA 7A - confirmacion held-out de lag";
lines(end+1, 1) = "";
lines(end+1, 1) = "- Ejecucion de ingenieria: PASS.";
lines(end+1, 1) = "- Agente/Env/simulador/reward/DTW/hardware: no/no/no/no/no/no.";
lines(end+1, 1) = sprintf( ...
    "- Soporte comun: +/- %d pasos (%.3f s por lado).", ...
    options.maxLagSteps, options.maxLagSteps*options.periodSec);
lines(end+1, 1) = "- Fold held-out: repetitionId.";
lines(end+1, 1) = "";
lines(end+1, 1) = "## Resultados por motor y regimen";
lines(end+1, 1) = "";
resultLines = strings(height(analysis.confirmationSummary), 1);
for rowIdx = 1:height(analysis.confirmationSummary)
    row = analysis.confirmationSummary(rowIdx, :);
    resultLines(rowIdx) = sprintf( ...
        "- %s M%d %s: endpoint %.9f; zero comun %.9f; " + ...
        "lag held-out %.9f; mejora %.3f%%; lags [%+d,%+d]; " + ...
        "borde %.1f%%; %s.", ...
        row.commandSource, row.motor, row.regime, row.fullEndpointMse, ...
        row.commonSupportZeroLagMse, row.heldOutSelectedLagMse, ...
        100*row.heldOutImprovementFraction, row.minimumSelectedLagSteps, ...
        row.maximumSelectedLagSteps, ...
        100*row.boundarySelectionFraction, row.classification);
end
lines = vertcat(lines, resultLines);
lines(end+1, 1) = "";
lines(end+1, 1) = "## Decision";
lines(end+1, 1) = "";
decisionLines = strings(height(analysis.sourceDecision), 1);
for rowIdx = 1:height(analysis.sourceDecision)
    row = analysis.sourceDecision(rowIdx, :);
    decisionLines(rowIdx) = sprintf( ...
        "- %s: %s; candidatos causales=%d; no resueltos=%d.", ...
        row.commandSource, row.classification, ...
        row.causalCandidateCount, row.unresolvedCount);
end
lines = vertcat(lines, decisionLines);
lines(end+1, 1) = "";
lines(end+1, 1) = ...
    "No se ejecuto compensacion ni filtro: esta etapa termina en el gate.";
lines(end+1, 1) = sprintf("Costo offline: %.6f s.", elapsedSec);
lines(end+1, 1) = "Ruta: `" + string(runDir) + "`.";
writeText(pathValue, strjoin(lines, newline));
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[workingStatus, ~] = system(sprintf('git -C "%s" diff --quiet', repoRoot));
[indexStatus, ~] = system(sprintf( ...
    'git -C "%s" diff --cached --quiet', repoRoot));
trackedDirty = workingStatus ~= 0 || indexStatus ~= 0;
end

function hash = fileSha256(filePath)
escapedPath = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escapedPath);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7a_lag_confirmation:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = upper(string(strtrim(output)));
end

function escaped = escape(value)
escaped = strrep(char(string(value)), "'", "''");
end

function writeText(filePath, value)
[fid, message] = fopen(filePath, "w", "n", "UTF-8");
if fid < 0
    error("run_no_glove_stage7a_lag_confirmation:WriteFailed", ...
        "Could not open %s: %s.", filePath, message);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
