function report = run_no_glove_stage7r_real_state_emg_attribution(options)
%run_no_glove_stage7r_real_state_emg_attribution matches real EMG states.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));

data = loadNoGloveStage7rEvidence(options.stage7qRunRoot, ...
    options.stage7pRunRoot, options.stage7nRunRoot);
if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7r_real_state_emg_attribution");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7r_real_state_emg_attribution:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testFiles = [ ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7rRealStateEmgAttribution.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7qCommandAttribution.m")];
testResults = runtests(testFiles);
save(fullfile(runRoot, "preflight_test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7r_real_state_emg_attribution:TestsFailed", ...
        "ETAPA 7R tests failed. See %s.", runRoot);
end

pairSet = buildNoGloveStage7rRealPairs(data.primaryCorpus);
if ~isequal(pairSet.statesEvaluated, data.primaryCorpus.states)
    error("run_no_glove_stage7r_real_state_emg_attribution:StateMutation", ...
        "Pair construction changed a frozen state.");
end
analysis = analyzeNoGloveStage7rEmgAttribution( ...
    pairSet, data.sharedEvaluations);
inputInventory = buildInputInventory(data, options);

writetable(analysis.featureContract.families, ...
    fullfile(runRoot, "wmoos_family_contract.csv"));
writetable(analysis.featureContract.channels, ...
    fullfile(runRoot, "wmoos_channel_contract.csv"));
writetable(analysis.pairTable, fullfile(runRoot, "real_pairs.csv"));
writetable(analysis.pairActionTable, ...
    fullfile(runRoot, "pair_actions.csv"));
writetable(analysis.supportSummary, ...
    fullfile(runRoot, "pair_support_summary.csv"));
writetable(analysis.gridSummary, ...
    fullfile(runRoot, "matching_grid_summary.csv"));
writetable(analysis.familyModelSummary, ...
    fullfile(runRoot, "family_model_summary.csv"));
writetable(analysis.channelModelSummary, ...
    fullfile(runRoot, "channel_model_summary.csv"));
writetable(analysis.familyDecisionAudit, ...
    fullfile(runRoot, "family_decision_audit.csv"));
writetable(analysis.allEmgDecisionAudit, ...
    fullfile(runRoot, "all_emg_decision_audit.csv"));
writetable(analysis.supportDecisionAudit, ...
    fullfile(runRoot, "support_decision_audit.csv"));
writetable(inputInventory, fullfile(runRoot, "input_inventory.csv"));

operationalChecks = struct( ...
    "stage7qValidated", data.stage7q.validated, ...
    "stage7pValidated", data.stage7p.validated, ...
    "stage7nValidated", data.stage7n.validated, ...
    "state60Selected", analysis.stateDecision == "intentMarkov60", ...
    "state62Rejected", analysis.state62Disposition == ...
        "provisionallyRejected", ...
    "primaryCohortMatched", analysis.primaryComponentCount == 2064, ...
    "completeStatesUnchanged", isequal(pairSet.statesEvaluated, ...
        data.primaryCorpus.states), ...
    "stateCounterfactualExcluded", ~analysis.stateCounterfactualUsed, ...
    "hybridStateExcluded", ~analysis.hybridStateUsed, ...
    "futureLeakageExcluded", ~analysis.futureLeakageUsed, ...
    "checkpointsNotLoaded", ~data.agentCheckpointsLoaded, ...
    "trainingLogsExcluded", ~data.trainingLogsUsed, ...
    "rewardUnchanged", true, "quantizationUnchanged", true, ...
    "td3Unchanged", true, "simulatorUnchanged", true, ...
    "safetyUnchanged", true, "gateUnchanged", true, ...
    "noTraining", true, "noEnvironment", true, ...
    "noSimulation", true, "noHardware", true, "noDtw", true);
if ~all(struct2array(operationalChecks))
    error("run_no_glove_stage7r_real_state_emg_attribution:OperationalGate", ...
        "An ETAPA 7R operational invariant failed.");
end
writetable(struct2table(operationalChecks), ...
    fullfile(runRoot, "operational_checks.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", "7R", "schemaVersion", 1, "result", "PASS", ...
    "scientificResult", analysis.scientificResult, ...
    "stateDecision", analysis.stateDecision, ...
    "state62Disposition", analysis.state62Disposition, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7r_real_state_emg_attribution", ...
    "preregistrationCommit", "64eceb8f", ...
    "parentStage7q", compactParent(data.stage7q), ...
    "parentStage7p", compactParent(data.stage7p), ...
    "parentStage7n", compactParent(data.stage7n), ...
    "checkpoints", table2struct(data.checkpointInventory), ...
    "primaryComponentCount", analysis.primaryComponentCount, ...
    "pairCount", analysis.pairCount, ...
    "matching", struct("contextMaximumThreshold", ...
        pairSet.contextMaximumThreshold, "minimumEmgDistance", ...
        pairSet.minimumEmgDistance, "foldCount", pairSet.foldCount), ...
    "operationalChecks", operationalChecks, ...
    "rewardChanged", false, "quantizationChanged", false, ...
    "td3Changed", false, "simulatorChanged", false, ...
    "safetyLayerChanged", false, "restGateChanged", false, ...
    "trainingUsed", false, "environmentUsed", false, ...
    "simulationUsed", false, "simMotors", true, ...
    "hardwareUsed", false, "myoUsed", false, ...
    "gloveUsed", false, "dtwCalculated", false, ...
    "stateCounterfactualUsed", false, "hybridStateUsed", false, ...
    "agentCheckpointsLoaded", false, ...
    "agent7250Loaded", false, "agent7250Used", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "state62CheckpointLoaded", false, ...
    "smokeAuthorized", false, "smokeExecuted", false, ...
    "pilotAuthorized", false, "pilotExecuted", false, ...
    "campaignAuthorized", false, "campaignExecuted", false, ...
    "futureAblationExecuted", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);

save(fullfile(runRoot, "stage7r_results.mat"), ...
    "manifest", "analysis", "pairSet", "operationalChecks", ...
    "inputInventory", "options", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest, analysis));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.scientificResult, ...
    "stateDecision", analysis.stateDecision, ...
    "outputPath", runRoot, "manifest", manifest, ...
    "analysis", analysis);
fprintf("ETAPA 7R REAL-STATE EMG ATTRIBUTION PASS\n");
fprintf("Scientific result: %s\n", analysis.scientificResult);
fprintf("Matched pairs: %d\n", analysis.pairCount);
fprintf("Output: %s\n", runRoot);
disp(analysis.supportDecisionAudit);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7r_real_state_emg_attribution:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "resultsRoot", "", ...
    "stage7qRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7q_artifacts\stage7q_final\2026-08-30_16-44-30-296", ...
    "stage7pRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7p_artifacts\stage7p_final\2026-08-29_23-15-59-803", ...
    "stage7nRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7n_artifacts\stage7n_corrected_final\2026-08-29_07-34-46-814");
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7r_real_state_emg_attribution:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.stage7qRunRoot = string(options.stage7qRunRoot);
options.stage7pRunRoot = string(options.stage7pRunRoot);
options.stage7nRunRoot = string(options.stage7nRunRoot);
end

function inventory = buildInputInventory(data, options)
category = strings(0, 1);
checkpointEpisode = zeros(0, 1);
source = strings(0, 1);
episode = zeros(0, 1);
filePath = strings(0, 1);
bytes = zeros(0, 1);
sha256 = strings(0, 1);
parentPaths = [ ...
    fullfile(options.stage7qRunRoot, "manifest.json"); ...
    fullfile(options.stage7qRunRoot, "stage7q_results.mat"); ...
    fullfile(options.stage7pRunRoot, "manifest.json"); ...
    fullfile(options.stage7pRunRoot, "stage7p_results.mat"); ...
    fullfile(options.stage7nRunRoot, "manifest.json"); ...
    fullfile(options.stage7nRunRoot, "checkpoint_summary.csv")];
for idx = 1:numel(parentPaths)
    [category, checkpointEpisode, source, episode, filePath, ...
        bytes, sha256] = appendInventory(category, checkpointEpisode, ...
        source, episode, filePath, bytes, sha256, "parent", 0, ...
        "", 0, parentPaths(idx));
end
for idx = 1:height(data.checkpointInventory)
    [category, checkpointEpisode, source, episode, filePath, ...
        bytes, sha256] = appendInventory(category, checkpointEpisode, ...
        source, episode, filePath, bytes, sha256, "checkpoint", ...
        data.checkpointInventory.episode(idx), "", 0, ...
        data.checkpointInventory.checkpointPath(idx));
end
for corpusIdx = 1:numel(data.ownCorpora)
    rows = data.ownCorpora(corpusIdx).corpus.inventory;
    for row = 1:height(rows)
        [category, checkpointEpisode, source, episode, filePath, ...
            bytes, sha256] = appendInventory(category, ...
            checkpointEpisode, source, episode, filePath, bytes, ...
            sha256, "episode", data.ownCorpora(corpusIdx).episode, ...
            rows.source(row), rows.episode(row), rows.filePath(row));
    end
end
inventory = table(category, checkpointEpisode, source, episode, ...
    filePath, bytes, sha256);
end

function [category, checkpointEpisode, source, episode, filePath, ...
        bytes, sha256] = appendInventory(category, checkpointEpisode, ...
        source, episode, filePath, bytes, sha256, newCategory, ...
        newCheckpoint, newSource, newEpisode, newPath)
info = dir(newPath);
category(end+1, 1) = string(newCategory);
checkpointEpisode(end+1, 1) = double(newCheckpoint);
source(end+1, 1) = string(newSource);
episode(end+1, 1) = double(newEpisode);
filePath(end+1, 1) = string(newPath);
bytes(end+1, 1) = info.bytes;
sha256(end+1, 1) = fileSha256(newPath);
end

function parent = compactParent(value)
parent = struct("runRoot", value.runRoot, ...
    "manifestSha256", value.manifestSha256, ...
    "gitCommit", string(value.manifest.gitCommit), ...
    "scientificResult", string(value.manifest.scientificResult), ...
    "validated", value.validated);
end

function hashes = inventoryArtifacts(runRoot)
names = ["preflight_test_results.mat", "wmoos_family_contract.csv", ...
    "wmoos_channel_contract.csv", "real_pairs.csv", ...
    "pair_actions.csv", "pair_support_summary.csv", ...
    "matching_grid_summary.csv", "family_model_summary.csv", ...
    "channel_model_summary.csv", "family_decision_audit.csv", ...
    "all_emg_decision_audit.csv", "support_decision_audit.csv", ...
    "input_inventory.csv", "operational_checks.csv", ...
    "stage7r_results.mat", "offline_report.md", ...
    "reproducible_command.txt"];
hashes = repmat(struct("artifact", "", "sha256", ""), ...
    numel(names), 1);
for idx = 1:numel(names)
    path = fullfile(runRoot, names(idx));
    hashes(idx) = struct("artifact", names(idx), ...
        "sha256", fileSha256(path));
end
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7r_real_state_emg_attribution(struct(" + ...
    "'resultsRoot','%s','stage7qRunRoot','%s'," + ...
    "'stage7pRunRoot','%s','stage7nRunRoot','%s'))", ...
    escape(matlabRoot), escape(string(fileparts(runRoot))), ...
    escape(options.stage7qRunRoot), escape(options.stage7pRunRoot), ...
    escape(options.stage7nRunRoot));
end

function value = buildOfflineReport(manifest, analysis)
support = analysis.supportDecisionAudit;
lines = [ ...
    "# ETAPA 7R - atribucion EMG con pares reales"; ""; ...
    "- Resultado: PASS."; ...
    "- Resultado cientifico: `" + manifest.scientificResult + "`."; ...
    sprintf("- Pares reales dirigidos: %d.", manifest.pairCount); ...
    sprintf("- Motores soportados within/cross: %d/%d.", ...
        support.withinSupportedMotorCount, ...
        support.crossSupportedMotorCount); ...
    "- Estados hibridos/contrafactuales: no/no."; ...
    "- Entrenamiento/Env/simulacion/hardware/DTW: no/no/no/no/no."; ...
    ""; "No se ejecuto ninguna ablacion ni se autorizo smoke o piloto." ...
    ];
value = strjoin(lines, newline);
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function hash = fileSha256(filePath)
escaped = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escaped);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7r_real_state_emg_attribution:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = string(strtrim(output));
end

function value = escape(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7r_real_state_emg_attribution:WriteFailed", ...
        "Could not write %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
