function report = run_no_glove_stage7p_interface_diagnostic(options)
%run_no_glove_stage7p_interface_diagnostic audits the frozen PWM interface.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));

[parent7o, parent7n, checkpoint] = validateParents( ...
    options.stage7oRunRoot, options.stage7nRunRoot);
if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7p_interface_diagnostic");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7p_interface_diagnostic:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testFiles = [ ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7pInterfaceDiagnostic.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7oBitCounterfactual.m")];
testResults = runtests(testFiles);
save(fullfile(runRoot, "preflight_test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7p_interface_diagnostic:TestsFailed", ...
        "ETAPA 7P tests failed. See %s.", runRoot);
end

actuator = loadActuatorContract(checkpoint.path);
sources = struct("acceptance", checkpoint.acceptanceDirectory, ...
    "steadyRest", checkpoint.restDirectory);
corpus = loadNoGloveStage7pInterfaceCorpus(sources, actuator);
corpus.inventory.sha256 = strings(height(corpus.inventory), 1);
corpus.inventory.bytes = zeros(height(corpus.inventory), 1);
for idx = 1:height(corpus.inventory)
    pathValue = corpus.inventory.filePath(idx);
    corpus.inventory.sha256(idx) = fileSha256(pathValue);
    info = dir(pathValue);
    corpus.inventory.bytes(idx) = info.bytes;
end
save(fullfile(runRoot, "stage7p_corpus.mat"), ...
    "corpus", "sources", "actuator", "-v7.3");
writetable(corpus.metadata, fullfile(runRoot, "window_metadata.csv"));
writetable(corpus.inventory, fullfile(runRoot, "input_inventory.csv"));
writetable(corpus.alignmentAudit, ...
    fullfile(runRoot, "alignment_audit.csv"));

agent = loadSavedAgent(checkpoint.path);
actor = getActor(agent);
model = getModel(actor);
serialAction = evaluateFrozenActorStates(actor, corpus.states);
batchAction = evaluateFrozenActorModelStates(model, corpus.states);
[~, batchPwm] = quantizeRows(batchAction, actuator);
replayAudit = table(size(corpus.states, 1), ...
    max(abs(serialAction-corpus.rawAction), [], "all"), ...
    max(abs(batchAction-serialAction), [], "all"), ...
    sum(batchPwm ~= corpus.pwm, "all"), ...
    'VariableNames', ["evaluatedWindowCount", ...
    "serialSavedMaximumError", "batchSerialMaximumError", ...
    "batchPwmMismatchCount"]);
if replayAudit.serialSavedMaximumError > 1e-12 || ...
        replayAudit.batchSerialMaximumError > 1e-5 || ...
        replayAudit.batchPwmMismatchCount ~= 0
    error("run_no_glove_stage7p_interface_diagnostic:ActorReplay", ...
        "Frozen state-60 Agent200 does not replay exactly.");
end
clear agent actor model serialAction batchAction batchPwm

analysis = analyzeNoGloveStage7pInterface(corpus, actuator);
componentTable = analysis.componentTable;
canonicalSweep = analysis.canonicalSweep;
interfaceSummary = analysis.interfaceSummary;
levelSignSummary = analysis.levelSignSummary;
gateMotorSummary = analysis.gateMotorSummary;
gateWindowSummary = analysis.gateWindowSummary;
safetySummary = analysis.safetySummary;
safetyContextSummary = analysis.safetyContextSummary;
decisionAudit = analysis.decisionAudit;
writetable(replayAudit, fullfile(runRoot, "actor_replay_audit.csv"));
writetable(componentTable, fullfile(runRoot, "interface_components.csv"));
writetable(canonicalSweep, fullfile(runRoot, "canonical_sweep.csv"));
writetable(interfaceSummary, fullfile(runRoot, "interface_summary.csv"));
writetable(levelSignSummary, fullfile(runRoot, "level_sign_summary.csv"));
writetable(gateMotorSummary, fullfile(runRoot, "gate_motor_summary.csv"));
writetable(gateWindowSummary, fullfile(runRoot, "gate_window_summary.csv"));
writetable(safetySummary, fullfile(runRoot, "safety_summary.csv"));
writetable(safetyContextSummary, ...
    fullfile(runRoot, "safety_context_summary.csv"));
writetable(decisionAudit, fullfile(runRoot, "decision_audit.csv"));

operationalChecks = struct( ...
    "parent7oValidated", parent7o.validated, ...
    "parent7nValidated", parent7n.validated, ...
    "checkpointHashMatched", checkpoint.hashMatched, ...
    "state60Selected", analysis.stateDecision == "intentMarkov60", ...
    "state62Rejected", ...
        analysis.state62Disposition == "provisionallyRejected", ...
    "temporalAlignment", allAlignmentPassed(corpus.alignmentAudit), ...
    "actorReplay", replayAudit.serialSavedMaximumError <= 1e-12 && ...
        replayAudit.batchSerialMaximumError <= 1e-5 && ...
        replayAudit.batchPwmMismatchCount == 0, ...
    "canonicalQuantizer", analysis.canonicalDiscontinuityPassed, ...
    "allObservedFinite", all(isfinite([corpus.states(:); ...
        corpus.rawAction(:); corpus.effectiveAction(:); ...
        corpus.pwm(:); corpus.qAfter(:); ...
        corpus.safetyIntervention(:)])), ...
    "trainingLogsExcluded", ~corpus.trainingLogsUsed, ...
    "futureLeakageExcluded", ~corpus.futureLeakageUsed, ...
    "rewardUnchanged", true, "quantizationUnchanged", true, ...
    "td3Unchanged", true, "simulatorUnchanged", true, ...
    "safetyUnchanged", true, "gateUnchanged", true, ...
    "noTraining", true, "noEnvironment", true, ...
    "noSimulation", true, "noHardware", true, "noDtw", true);
if ~all(struct2array(operationalChecks))
    error("run_no_glove_stage7p_interface_diagnostic:OperationalGate", ...
        "An ETAPA 7P operational invariant failed.");
end
writetable(struct2table(operationalChecks), ...
    fullfile(runRoot, "operational_checks.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", "7P", "schemaVersion", 1, "result", "PASS", ...
    "scientificResult", analysis.futureAblationSelection, ...
    "stateDecision", analysis.stateDecision, ...
    "state62Disposition", analysis.state62Disposition, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7p_interface_diagnostic", ...
    "preregistrationCommit", ...
        "c263a5ae", ...
    "parentStage7o", parent7o, "parentStage7n", parent7n, ...
    "checkpoint", checkpoint, "sources", sources, ...
    "actuator", actuator, "windowCount", corpus.windowCount, ...
    "componentCount", corpus.componentCount, ...
    "nearThresholdComponentCount", ...
        analysis.nearThresholdComponentCount, ...
    "nearThresholdFraction", analysis.nearThresholdFraction, ...
    "canonicalDiscontinuityPassed", ...
        analysis.canonicalDiscontinuityPassed, ...
    "nearCounterfactualPassed", analysis.nearCounterfactualPassed, ...
    "gateInactiveReferenceFraction", ...
        analysis.gateInactiveReferenceFraction, ...
    "gateInactiveReferenceNonzeroPwmFraction", ...
        analysis.gateInactiveReferenceNonzeroPwmFraction, ...
    "safetyInterventionComponentStepCount", ...
        analysis.safetyInterventionComponentStepCount, ...
    "safetyInterventionSampleCount", ...
        analysis.safetyInterventionSampleCount, ...
    "interiorInterventionSampleFraction", ...
        analysis.interiorInterventionSampleFraction, ...
    "decisionThresholds", struct( ...
        "thresholdNeighborhood", analysis.thresholdNeighborhood, ...
        "crossingEpsilon", analysis.crossingEpsilon, ...
        "minimumQuantizerExposure", 0.01, ...
        "minimumGateInactiveReference", 0.10, ...
        "minimumGateNonzeroPwm", 0.10), ...
    "operationalChecks", operationalChecks, ...
    "rewardChanged", false, "quantizationChanged", false, ...
    "td3Changed", false, "simulatorChanged", false, ...
    "safetyLayerChanged", false, "restGateChanged", false, ...
    "trainingUsed", false, "environmentUsed", false, ...
    "simulationUsed", false, "simMotors", true, ...
    "hardwareUsed", false, "myoUsed", false, ...
    "gloveUsed", false, "dtwCalculated", false, ...
    "agent7250Loaded", false, "agent7250Used", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "state62CheckpointLoaded", false, ...
    "pilotAuthorized", false, "pilotExecuted", false, ...
    "campaignAuthorized", false, "campaignExecuted", false, ...
    "futureAblationExecuted", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);

save(fullfile(runRoot, "stage7p_results.mat"), ...
    "manifest", "analysis", "corpus", "actuator", ...
    "replayAudit", "operationalChecks", "options", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.futureAblationSelection, ...
    "stateDecision", analysis.stateDecision, ...
    "outputPath", runRoot, "manifest", manifest, ...
    "analysis", analysis);
fprintf("ETAPA 7P INTERFACE DIAGNOSTIC PASS\n");
fprintf("State decision: %s\n", analysis.stateDecision);
fprintf("Future ablation: %s\n", analysis.futureAblationSelection);
fprintf("Near-threshold exposure: %.9g\n", ...
    analysis.nearThresholdFraction);
fprintf("Safety interventions: %d motor-step components / %d samples\n", ...
    analysis.safetyInterventionComponentStepCount, ...
    analysis.safetyInterventionSampleCount);
fprintf("Output: %s\n", runRoot);
disp(decisionAudit);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7p_interface_diagnostic:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "resultsRoot", "", ...
    "stage7oRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7o_artifacts\stage7o_final\2026-08-29_22-22-07-025", ...
    "stage7nRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7n_artifacts\stage7n_corrected_final\2026-08-29_07-34-46-814");
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7p_interface_diagnostic:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.stage7oRunRoot = string(options.stage7oRunRoot);
options.stage7nRunRoot = string(options.stage7nRunRoot);
end

function [parent7o, parent7n, checkpoint] = validateParents( ...
        stage7oRoot, stage7nRoot)
path7o = fullfile(stage7oRoot, "manifest.json");
path7n = fullfile(stage7nRoot, "manifest.json");
summaryPath = fullfile(stage7nRoot, "checkpoint_summary.csv");
if ~isfile(path7o) || ~isfile(path7n) || ~isfile(summaryPath)
    error("run_no_glove_stage7p_interface_diagnostic:MissingParent", ...
        "Canonical ETAPA 7O/7N artifacts are missing.");
end
hash7o = fileSha256(path7o);
hash7n = fileSha256(path7n);
expected7o = ...
    "8173E7ABB11B0FAA7A7CB7AADE74502071E804BBD5F5E4E6145448FCA53254D9";
expected7n = ...
    "082DADB41DAA1DAB6AE2B5E02AE15191479410F10B5DF0398837814BFC53D480";
m7o = jsondecode(fileread(path7o));
m7n = jsondecode(fileread(path7n));
valid7o = hash7o == expected7o && string(m7o.stage) == "7O" && ...
    string(m7o.result) == "PASS" && ...
    string(m7o.scientificResult) == "bitsContextDependent" && ...
    string(m7o.recommendation) == ...
        "holdTrainingReturnProvisionallyToIntentMarkov60" && ...
    ~logical(m7o.hardwareUsed) && ~logical(m7o.runTraining);
valid7n = hash7n == expected7n && string(m7n.stage) == "7N" && ...
    string(m7n.result) == "PASS" && ~logical(m7n.hardwareUsed);
if ~valid7o || ~valid7n
    error("run_no_glove_stage7p_interface_diagnostic:ParentChanged", ...
        "ETAPA 7O or 7N does not match the preregistered parent.");
end
parent7o = struct("runRoot", stage7oRoot, ...
    "manifestSha256", hash7o, ...
    "scientificResult", string(m7o.scientificResult), ...
    "recommendation", string(m7o.recommendation), ...
    "gitCommit", string(m7o.gitCommit), "validated", true);
parent7n = struct("runRoot", stage7nRoot, ...
    "manifestSha256", hash7n, ...
    "scientificResult", string(m7n.scientificResult), ...
    "gitCommit", string(m7n.gitCommit), "validated", true);

summary = readtable(summaryPath, "TextType", "string");
row = summary(summary.variant == "control60" & ...
    summary.episode == 200, :);
if height(row) ~= 1
    error("run_no_glove_stage7p_interface_diagnostic:CheckpointRow", ...
        "Expected exactly one control60 Agent200 row.");
end
path = string(row.checkpointPath);
expectedHash = ...
    "440F003450A368A13A0E5DACB04FD7755BB929033EB879B217E47F32B5AA185E";
actualHash = fileSha256(path);
checkpoint = struct("label", "control60", "episode", 200, ...
    "observationVariant", "intentMarkov60", "stateLength", 60, ...
    "path", path, "expectedSha256", expectedHash, ...
    "actualSha256", actualHash, "hashMatched", actualHash == expectedHash, ...
    "acceptanceDirectory", string(row.acceptanceDirectory), ...
    "restDirectory", string(row.restDirectory));
if ~checkpoint.hashMatched
    error("run_no_glove_stage7p_interface_diagnostic:CheckpointChanged", ...
        "Frozen control60 Agent200 hash changed.");
end
end

function actuator = loadActuatorContract(checkpointPath)
configPath = fullfile(fileparts(checkpointPath), "00_configs.mat");
data = load(configPath, "configs");
c = data.configs;
safety = c.simulationPositionSafety;
valid = string(c.observationVariant) == "intentMarkov60" && ...
    double(c.stateLength) == 60 && ...
    string(c.actionInterfaceVariant) == "baselineQuantized" && ...
    logical(c.quantizeCommandsForSimulation) && ~logical(c.unifyActions) && ...
    c.actionCommandActivationThreshold == 0.05 && ...
    isequal(double(c.actionCommandLevels), ...
        [0, 64, 96, 128, 160, 192, 224, 255]) && ...
    all(double(c.speeds) == 255) && logical(c.run_training) && ...
    logical(c.simMotors) && ~logical(c.connect_glove) && ...
    isstruct(safety) && logical(safety.enabled) && ...
    string(safety.mode) == "clipTrajectoryOutput" && ...
    isequal(double(safety.positionMin), zeros(1, 4)) && ...
    isequal(double(safety.positionMax), ones(1, 4)) && ...
    string(c.rewardType) == "trackingIntentActionRateReward";
if ~valid
    error("run_no_glove_stage7p_interface_diagnostic:ActuatorContract", ...
        "Frozen Agent200 configuration changed.");
end
actuator = struct("interface", "baselineQuantized", ...
    "maxPwm", 255, "activationThreshold", 0.05, ...
    "commandLevels", double(c.actionCommandLevels), ...
    "saturationThreshold", 0.95, ...
    "positionMinimum", double(safety.positionMin), ...
    "positionMaximum", double(safety.positionMax));
end

function passed = allAlignmentPassed(audit)
numeric = [audit.referenceMaximumError; ...
    audit.nextStateMaximumError; ...
    audit.provenancePositionMaximumError; ...
    audit.provenanceVelocityMaximumError; ...
    audit.effectiveActionMaximumError];
passed = all(numeric <= 1e-12) && all(audit.pwmMismatchCount == 0);
end

function [effective, pwm] = quantizeRows(raw, actuator)
effective = zeros(size(raw));
pwm = zeros(size(raw));
for idx = 1:size(raw, 1)
    [e, p] = quantizeBaselineAction(raw(idx, :), ...
        actuator.maxPwm, actuator.activationThreshold, ...
        actuator.commandLevels);
    effective(idx, :) = double(e(:))';
    pwm(idx, :) = double(p(:))';
end
end

function hashes = inventoryArtifacts(runRoot)
names = ["stage7p_corpus.mat", "window_metadata.csv", ...
    "input_inventory.csv", "alignment_audit.csv", ...
    "actor_replay_audit.csv", "interface_components.csv", ...
    "canonical_sweep.csv", "interface_summary.csv", ...
    "level_sign_summary.csv", "gate_motor_summary.csv", ...
    "gate_window_summary.csv", "safety_summary.csv", ...
    "safety_context_summary.csv", ...
    "decision_audit.csv", "operational_checks.csv", ...
    "stage7p_results.mat", "offline_report.md", ...
    "reproducible_command.txt"];
hashes = repmat(struct("artifact", "", "sha256", ""), ...
    numel(names), 1);
for idx = 1:numel(names)
    path = fullfile(runRoot, names(idx));
    hashes(idx) = struct("artifact", names(idx), ...
        "sha256", fileSha256(path));
end
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7p_interface_diagnostic(struct(" + ...
    "'resultsRoot','%s','stage7oRunRoot','%s'," + ...
    "'stage7nRunRoot','%s'))", escape(matlabRoot), ...
    escape(string(fileparts(runRoot))), ...
    escape(options.stage7oRunRoot), escape(options.stage7nRunRoot));
end

function value = buildOfflineReport(manifest)
lines = [ ...
    "# ETAPA 7P - diagnostico offline de interfaz"; ""; ...
    "- Resultado: PASS."; ...
    "- Estado seleccionado: `" + manifest.stateDecision + "`."; ...
    "- Estado 62: `" + manifest.state62Disposition + "`."; ...
    "- Hipotesis futura: `" + manifest.scientificResult + "`."; ...
    sprintf("- Exposicion cerca de theta: %.9g.", ...
        manifest.nearThresholdFraction); ...
    sprintf("- Intervenciones: %d componentes motor-paso / %d muestras.", ...
        manifest.safetyInterventionComponentStepCount, ...
        manifest.safetyInterventionSampleCount); ...
    "- Entrenamiento/Env/simulacion/hardware/DTW: no/no/no/no/no."; ...
    ""; "No se ejecuto ninguna ablacion ni se autorizo piloto." ...
    ];
value = strjoin(lines, newline);
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function hash = fileSha256(filePath)
escaped = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escaped);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7p_interface_diagnostic:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = string(strtrim(output));
end

function value = escape(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7p_interface_diagnostic:WriteFailed", ...
        "Could not write %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
