function report = run_no_glove_stage7e_checkpoint_evolution(options)
%run_no_glove_stage7e_checkpoint_evolution executes ETAPA 7E only.
%
% Agent50/100/150/200 are replayed offline on the same recorded training
% preActivationHold states. Recorded training behavior and reward terms are
% audited separately. No Env, simulator, reward function, training, DTW,
% behavioral change or hardware is invoked.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
addpath(genpath(fullfile(matlabRoot, "tests")));
clearConfigurablesOverride();

[stage7dManifest, inputPaths] = validateStage7d(options.stage7dRunRoot);
inputHashesBefore = hashInputPaths(inputPaths);
[trainingInventory, trainingHashesBefore] = ...
    validateTrainingInventory(inputPaths.trainingInventory);
[checkpointInventory, checkpointHashesBefore] = ...
    buildCheckpointInventory(string(stage7dManifest.trainingRoot));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7e_checkpoint_evolution");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runDir)
    error("run_no_glove_stage7e_checkpoint_evolution:OutputExists", ...
        "Refusing to reuse output directory %s.", runDir);
end
mkdir(runDir);

testPath = fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage7eCheckpointEvolution.m");
testResults = runtests(testPath);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7e_checkpoint_evolution:TestsFailed", ...
        "ETAPA 7E tests failed. See %s.", runDir);
end

[actuator, rewardWeights, profileAudit] = ...
    loadTrainingProfile(inputPaths.effectiveTrainingProfile);
[training, trainingEpisodeAudit] = loadTrainingCorpus( ...
    trainingInventory, options);
[checkpoints, checkpointAudit] = loadFrozenCheckpoints( ...
    checkpointInventory);

analysisOptions = struct( ...
    "referenceTolerance", options.referenceTolerance, ...
    "rewardTolerance", options.rewardTolerance, ...
    "falseActivationLimit", options.falseActivationLimit, ...
    "materialRelativeAttenuation", ...
        options.materialRelativeAttenuation, ...
    "saturationThreshold", options.saturationThreshold);
analysisArguments = namedargs2cell(analysisOptions);

smokeEpisodes = [1 51 101 151];
smokeTraining = subsetTraining(training, ...
    ismember(training.episode, smokeEpisodes));
smokeAnalysis = analyzeNoGloveStage7eCheckpointEvolution( ...
    smokeTraining, checkpoints, actuator, rewardWeights, ...
    analysisArguments{:});
if smokeAnalysis.rewardAudit.maximumAuditError > ...
        options.rewardTolerance || smokeAnalysis.runTraining || ...
        smokeAnalysis.envCreated || smokeAnalysis.simulatorInvoked || ...
        smokeAnalysis.rewardFunctionInvoked || smokeAnalysis.hardwareUsed
    error("run_no_glove_stage7e_checkpoint_evolution:SmokeFailed", ...
        "Offline smoke violated an ETAPA 7E invariant.");
end
writetable(smokeAnalysis.sourceDecision, ...
    fullfile(runDir, "smoke_source_decision.csv"));

analysisTic = tic;
analysis = analyzeNoGloveStage7eCheckpointEvolution( ...
    training, checkpoints, actuator, rewardWeights, ...
    analysisArguments{:});
analysisElapsedSec = toc(analysisTic);

writeAnalysisTables(runDir, analysis, checkpointAudit, ...
    trainingEpisodeAudit, profileAudit);
writetable(trainingInventory, ...
    fullfile(runDir, "training_episode_input_hashes.csv"));
writetable(checkpointInventory, ...
    fullfile(runDir, "checkpoint_input_hashes.csv"));
save(fullfile(runDir, "stage7e_results.mat"), ...
    "analysis", "analysisOptions", "smokeAnalysis", ...
    "checkpointAudit", "trainingEpisodeAudit", "profileAudit", ...
    "stage7dManifest", "rewardWeights", "analysisElapsedSec", "-v7.3");

inputHashesAfter = hashInputPaths(inputPaths);
trainingHashesAfter = hashPaths(trainingInventory.path);
checkpointHashesAfter = hashPaths(checkpointInventory.path);
if ~isequal(inputHashesAfter, inputHashesBefore) || ...
        ~isequal(trainingHashesAfter, trainingHashesBefore) || ...
        ~isequal(checkpointHashesAfter, checkpointHashesBefore)
    error("run_no_glove_stage7e_checkpoint_evolution:InputModified", ...
        "ETAPA 7D, training logs or checkpoints changed during ETAPA 7E.");
end

reproducibleCommand = buildReproducibleCommand( ...
    matlabRoot, options, fileparts(runDir));
writeText(fullfile(runDir, "reproducible_command.txt"), ...
    reproducibleCommand);
writeOfflineReport(fullfile(runDir, "offline_report.md"), ...
    analysis, analysisElapsedSec, runDir);

primaryArtifacts = ["test_results.mat", ...
    "smoke_source_decision.csv", ...
    "training_episode_input_hashes.csv", ...
    "checkpoint_input_hashes.csv", "checkpoint_audit.csv", ...
    "training_episode_audit.csv", "training_profile_audit.csv", ...
    "checkpoint_summary.csv", "checkpoint_motor_summary.csv", ...
    "checkpoint_episode_summary.csv", "checkpoint_trend.csv", ...
    "checkpoint_action_components.csv", ...
    "historical_training_summary.csv", ...
    "historical_training_motor_summary.csv", ...
    "block_end_replay_comparison.csv", "recorded_reward_terms.csv", ...
    "recorded_reward_summary.csv", ...
    "recorded_reward_episode_summary.csv", "reward_audit.csv", ...
    "source_decision.csv", "stage7e_results.mat", ...
    "reproducible_command.txt", "offline_report.md"];
artifactHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(primaryArtifacts), 1);
for artifactIdx = 1:numel(primaryArtifacts)
    artifactHashes(artifactIdx).path = primaryArtifacts(artifactIdx);
    artifactHashes(artifactIdx).sha256 = fileSha256( ...
        fullfile(runDir, primaryArtifacts(artifactIdx)));
end
writetable(struct2table(artifactHashes), ...
    fullfile(runDir, "artifact_hashes.csv"));

[gitCommit, gitDirty, trackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
decision = analysis.sourceDecision(1, :);
rewardAll = analysis.rewardSummary(analysis.rewardSummary.episodeBlock == ...
    "allEpisodes", :);
manifest = struct( ...
    "stage", "7E", "schemaVersion", 1, "result", "PASS", ...
    "scientificResult", decision.classification, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", trackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7e_checkpoint_evolution", ...
    "inputStage7dRunRoot", options.stage7dRunRoot, ...
    "inputStage7dManifestPath", inputPaths.stage7dManifest, ...
    "inputStage7dManifestSha256Before", ...
        inputHashesBefore.stage7dManifest, ...
    "inputStage7dManifestSha256After", ...
        inputHashesAfter.stage7dManifest, ...
    "inputStage7dResultsSha256Before", ...
        inputHashesBefore.stage7dResults, ...
    "inputStage7dResultsSha256After", ...
        inputHashesAfter.stage7dResults, ...
    "inputStage6ManifestPath", inputPaths.stage6Manifest, ...
    "inputStage6ManifestSha256Before", ...
        inputHashesBefore.stage6Manifest, ...
    "inputStage6ManifestSha256After", ...
        inputHashesAfter.stage6Manifest, ...
    "effectiveTrainingProfilePath", inputPaths.effectiveTrainingProfile, ...
    "effectiveTrainingProfileSha256Before", ...
        inputHashesBefore.effectiveTrainingProfile, ...
    "effectiveTrainingProfileSha256After", ...
        inputHashesAfter.effectiveTrainingProfile, ...
    "inputEvidencePreserved", isequal(inputHashesBefore, inputHashesAfter), ...
    "trainingEpisodeCount", height(trainingInventory), ...
    "trainingEpisodeHashesPreserved", ...
        isequal(trainingHashesBefore, trainingHashesAfter), ...
    "preActivationStateCount", analysis.trainingStateCount, ...
    "checkpointCount", height(checkpointInventory), ...
    "checkpointHashesPreserved", ...
        isequal(checkpointHashesBefore, checkpointHashesAfter), ...
    "checkpointLabels", checkpointInventory.label, ...
    "checkpointEpisodes", checkpointInventory.episode, ...
    "checkpointSha256", checkpointInventory.sha256, ...
    "checkpointExperienceBufferLengths", ...
        checkpointAudit.experienceBufferLength, ...
    "analysisOptions", analysisOptions, ...
    "stateCorpusContract", analysis.stateCorpusContract, ...
    "historicalActionContract", analysis.historicalActionContract, ...
    "rewardAuditContract", analysis.rewardAuditContract, ...
    "firstActiveCheckpoint", decision.firstActiveCheckpoint, ...
    "earlyCommandActiveFraction", decision.earlyCommandActiveFraction, ...
    "finalCommandActiveFraction", decision.finalCommandActiveFraction, ...
    "earlyWindowAnyCommandFraction", ...
        decision.earlyWindowAnyCommandFraction, ...
    "finalWindowAnyCommandFraction", ...
        decision.finalWindowAnyCommandFraction, ...
    "earlyMeanAbsPwm", decision.earlyMeanAbsPwm, ...
    "finalMeanAbsPwm", decision.finalMeanAbsPwm, ...
    "relativeMeanAbsPwmReduction", ...
        decision.relativeMeanAbsPwmReduction, ...
    "materialAttenuation", decision.materialAttenuation, ...
    "maximumRewardAuditError", analysis.rewardAudit.maximumAuditError, ...
    "meanRecordedRestReward", rewardAll.meanRecordedReward, ...
    "meanRecordedRestPositionCost", rewardAll.meanPositionCost, ...
    "meanRecordedRestActionCost", rewardAll.meanActionCost, ...
    "meanRecordedRestDeltaActionCost", rewardAll.meanDeltaActionCost, ...
    "meanRecordedRestSaturationCost", rewardAll.meanSaturationCost, ...
    "rootCauseIdentified", false, ...
    "checkpointSelectedAsWinner", false, ...
    "historicalActionInterpretedAsDeterministicActor", false, ...
    "explorationEffectIsolated", false, ...
    "counterfactualRewardCalculated", false, ...
    "agentFrozen", true, "newTraining", false, ...
    "checkpointLoadedForTraining", false, ...
    "behavioralInterventionExecuted", false, ...
    "compensationInterventionExecuted", false, ...
    "filteredReferenceInterventionExecuted", false, ...
    "dtwCalculated", false, "dtwRewardUsed", false, ...
    "stage8Authorized", false, ...
    "referenceGeneratorChanged", false, "stateChanged", false, ...
    "rewardChanged", false, "policyChanged", false, ...
    "quantizationChanged", false, "simulatorChanged", false, ...
    "safetyLayerChanged", false, "controllerChanged", false, ...
    "simMotorsInvariant", true, "runTraining", false, ...
    "agentLoaded", true, "agentEvaluationOnly", true, ...
    "reinforcementLearningInvoked", true, ...
    "reinforcementLearningTrainingInvoked", false, ...
    "offlineActorReplay", true, "envCreated", false, ...
    "simulatorInvoked", false, "rewardFunctionInvoked", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "agent7250Loaded", false, "hardwareUsed", false, ...
    "analysisElapsedSec", analysisElapsedSec, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "artifactHashes", artifactHashes, "outputPath", runDir);
save(fullfile(runDir, "manifest.mat"), "manifest", "artifactHashes");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", "outputPath", runDir, ...
    "manifest", manifest, "analysis", analysis, ...
    "testResults", testResults);
fprintf("ETAPA 7E CHECKPOINT EVOLUTION PASS\n");
fprintf("Output: %s\n", runDir);
disp(decision);
disp(analysis.checkpointSummary);
disp(analysis.checkpointTrend);
disp(analysis.rewardSummary);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7e_checkpoint_evolution:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct("stage7dRunRoot", "", "resultsRoot", "", ...
    "referenceTolerance", 1e-12, "rewardTolerance", 1e-12, ...
    "falseActivationLimit", 0.01, ...
    "materialRelativeAttenuation", 0.25, ...
    "saturationThreshold", 0.95);
unknown = setdiff(string(fieldnames(options)), ...
    string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7e_checkpoint_evolution:UnknownOption", ...
        "Unknown option(s): %s.", strjoin(unknown, ", "));
end
fields = fieldnames(defaults);
for fieldIdx = 1:numel(fields)
    name = fields{fieldIdx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.stage7dRunRoot = string(options.stage7dRunRoot);
options.resultsRoot = string(options.resultsRoot);
if strlength(options.stage7dRunRoot) == 0
    error("run_no_glove_stage7e_checkpoint_evolution:MissingInput", ...
        "stage7dRunRoot is required.");
end
numericFields = setdiff(string(fieldnames(defaults)), ...
    ["stage7dRunRoot", "resultsRoot"]);
for fieldIdx = 1:numel(numericFields)
    value = options.(numericFields(fieldIdx));
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value < 0
        error("run_no_glove_stage7e_checkpoint_evolution:InvalidOption", ...
            "%s must be a finite nonnegative scalar.", numericFields(fieldIdx));
    end
end
if options.falseActivationLimit > 1 || ...
        options.materialRelativeAttenuation > 1 || ...
        options.saturationThreshold > 1
    error("run_no_glove_stage7e_checkpoint_evolution:InvalidOption", ...
        "ETAPA 7E option bounds are invalid.");
end
end

function [manifest, paths] = validateStage7d(runRoot)
paths = struct( ...
    "stage7dManifest", fullfile(runRoot, "manifest.json"), ...
    "stage7dResults", fullfile(runRoot, "stage7d_results.mat"), ...
    "trainingInventory", fullfile(runRoot, ...
        "training_episode_input_hashes.csv"), ...
    "trainingAudit", fullfile(runRoot, "training_episode_audit.csv"));
fields = fieldnames(paths);
for fieldIdx = 1:numel(fields)
    if ~isfile(paths.(fields{fieldIdx}))
        error("run_no_glove_stage7e_checkpoint_evolution:Stage7dNotFound", ...
            "Missing ETAPA 7D input %s.", paths.(fields{fieldIdx}));
    end
end
manifest = jsondecode(fileread(paths.stage7dManifest));
required = ["stage", "result", "scientificResult", ...
    "trainingRestAlsoCommands", "rootCauseIdentified", ...
    "trainingRoot", "trainingEpisodeCount", ...
    "trainingPreActivationStateCount", "agentCheckpointPath", ...
    "agentCheckpointSha256After", "agentFrozen", "runTraining", ...
    "agent7250Loaded", "envCreated", "simulatorInvoked", ...
    "rewardInvoked", "dtwCalculated", "hardwareUsed", "artifactHashes"];
if ~all(isfield(manifest, cellstr(required)))
    error("run_no_glove_stage7e_checkpoint_evolution:InvalidStage7d", ...
        "ETAPA 7D manifest contract is incomplete.");
end
valid = string(manifest.stage) == "7D" && ...
    string(manifest.result) == "PASS" && ...
    string(manifest.scientificResult) == "trainingRestAlsoCommands" && ...
    logical(manifest.trainingRestAlsoCommands) && ...
    ~logical(manifest.rootCauseIdentified) && ...
    double(manifest.trainingEpisodeCount) == 200 && ...
    double(manifest.trainingPreActivationStateCount) == 2200 && ...
    logical(manifest.agentFrozen) && ~logical(manifest.runTraining) && ...
    ~logical(manifest.agent7250Loaded) && ~logical(manifest.envCreated) && ...
    ~logical(manifest.simulatorInvoked) && ~logical(manifest.rewardInvoked) && ...
    ~logical(manifest.dtwCalculated) && ~logical(manifest.hardwareUsed);
if ~valid
    error("run_no_glove_stage7e_checkpoint_evolution:IncompatibleStage7d", ...
        "ETAPA 7E requires the canonical PASS ETAPA 7D evidence.");
end
artifactNames = ["stage7d_results.mat", ...
    "training_episode_input_hashes.csv", "training_episode_audit.csv"];
artifactPaths = [paths.stage7dResults, paths.trainingInventory, ...
    paths.trainingAudit];
for artifactIdx = 1:numel(artifactNames)
    if fileSha256(artifactPaths(artifactIdx)) ~= findArtifactHash( ...
            manifest.artifactHashes, artifactNames(artifactIdx))
        error("run_no_glove_stage7e_checkpoint_evolution:Stage7dHashMismatch", ...
            "%s does not match the ETAPA 7D manifest.", ...
            artifactNames(artifactIdx));
    end
end
trainingRoot = string(manifest.trainingRoot);
seedRoot = string(fileparts(fileparts(trainingRoot)));
stage6Root = string(fileparts(seedRoot));
paths.stage6Manifest = fullfile(stage6Root, "manifest.json");
paths.effectiveTrainingProfile = fullfile(seedRoot, ...
    "effective_training_profile.mat");
if ~isfile(paths.stage6Manifest) || ~isfile(paths.effectiveTrainingProfile)
    error("run_no_glove_stage7e_checkpoint_evolution:Stage6NotFound", ...
        "The original ETAPA 6 manifest/profile is unavailable.");
end
stage6 = jsondecode(fileread(paths.stage6Manifest));
requiredStage6 = ["stage", "phase", "result", "protocol", ...
    "phaseGatePassed", "agent7250Loaded", "hardwareUsed", ...
    "referenceSource", "observationVariant", "rewardType", ...
    "actionInterfaceVariant", "simMotors", "seedSummary"];
if ~all(isfield(stage6, cellstr(requiredStage6))) || ...
        double(stage6.stage) ~= 6 || string(stage6.phase) ~= "smoke" || ...
        string(stage6.result) ~= "PARTIAL" || ...
        logical(stage6.phaseGatePassed) || ...
        double(stage6.protocol.episodes) ~= 200 || ...
        double(stage6.protocol.saveEvery) ~= 50 || ...
        logical(stage6.agent7250Loaded) || logical(stage6.hardwareUsed) || ...
        string(stage6.referenceSource) ~= "emgIntent" || ...
        string(stage6.observationVariant) ~= "intentMarkov60" || ...
        string(stage6.rewardType) ~= "trackingIntentActionRateReward" || ...
        string(stage6.actionInterfaceVariant) ~= "baselineQuantized" || ...
        ~logical(stage6.simMotors) || ...
        string(stage6.seedSummary.finalCheckpoint) ~= ...
            string(manifest.agentCheckpointPath)
    error("run_no_glove_stage7e_checkpoint_evolution:Stage6Drift", ...
        "The original ETAPA 6 smoke contract has drifted.");
end
end

function hashes = hashInputPaths(paths)
hashes = struct( ...
    "stage7dManifest", fileSha256(paths.stage7dManifest), ...
    "stage7dResults", fileSha256(paths.stage7dResults), ...
    "trainingInventory", fileSha256(paths.trainingInventory), ...
    "trainingAudit", fileSha256(paths.trainingAudit), ...
    "stage6Manifest", fileSha256(paths.stage6Manifest), ...
    "effectiveTrainingProfile", ...
        fileSha256(paths.effectiveTrainingProfile));
end

function [inventory, hashes] = validateTrainingInventory(pathValue)
inventory = readtable(pathValue, "Delimiter", ",", "TextType", "string", ...
    "VariableNamingRule", "preserve");
required = ["fileName", "path", "sha256", "bytes"];
if ~all(ismember(required, string(inventory.Properties.VariableNames))) || ...
        height(inventory) ~= 200 || numel(unique(inventory.path)) ~= 200
    error("run_no_glove_stage7e_checkpoint_evolution:TrainingInventory", ...
        "The ETAPA 7D training inventory must contain 200 unique episodes.");
end
hashes = hashPaths(inventory.path);
if any(hashes ~= upper(inventory.sha256))
    error("run_no_glove_stage7e_checkpoint_evolution:TrainingHashMismatch", ...
        "A published training episode changed.");
end
end

function [inventory, hashes] = buildCheckpointInventory(trainingRoot)
episodes = [50; 100; 150; 200];
label = "Agent"+string(episodes);
fileName = label+".mat";
path = fullfile(trainingRoot, fileName);
bytes = zeros(4, 1);
for checkpointIdx = 1:4
    if ~isfile(path(checkpointIdx))
        error("run_no_glove_stage7e_checkpoint_evolution:CheckpointNotFound", ...
            "Missing checkpoint %s.", path(checkpointIdx));
    end
    info = dir(path(checkpointIdx));
    bytes(checkpointIdx) = info.bytes;
end
hashes = hashPaths(path);
inventory = table(label, episodes, fileName, path, hashes, bytes, ...
    'VariableNames', ["label", "episode", "fileName", "path", ...
    "sha256", "bytes"]);
end

function [actuator, weights, audit] = loadTrainingProfile(pathValue)
loaded = load(pathValue, "profile", "protocol");
if ~isfield(loaded, "profile") || ~isfield(loaded, "protocol")
    error("run_no_glove_stage7e_checkpoint_evolution:ProfileMissing", ...
        "The effective training profile is incomplete.");
end
profile = loaded.profile;
required = ["run_training", "newTraining", "simMotors", ...
    "connect_glove", "referenceSource", "observationVariant", ...
    "rewardType", "actionInterfaceVariant", ...
    "quantizeCommandsForSimulation", "speeds", ...
    "actionCommandActivationThreshold", "actionCommandLevels", ...
    "intentRewardPositionWeight", "intentRewardVelocityWeight", ...
    "intentRewardActionWeight", "intentRewardDeltaActionWeight", ...
    "intentRewardSaturationWeight", "intentRewardSoftActionLimit"];
if ~all(isfield(profile, cellstr(required))) || ...
        ~logical(profile.run_training) || ~logical(profile.newTraining) || ...
        ~logical(profile.simMotors) || logical(profile.connect_glove) || ...
        string(profile.referenceSource) ~= "emgIntent" || ...
        string(profile.observationVariant) ~= "intentMarkov60" || ...
        string(profile.rewardType) ~= "trackingIntentActionRateReward" || ...
        string(profile.actionInterfaceVariant) ~= "baselineQuantized" || ...
        ~logical(profile.quantizeCommandsForSimulation) || ...
        double(loaded.protocol.episodes) ~= 200 || ...
        double(loaded.protocol.saveEvery) ~= 50
    error("run_no_glove_stage7e_checkpoint_evolution:ProfileDrift", ...
        "The effective ETAPA 6 training profile has drifted.");
end
actuator = struct("maxPwm", max(abs(double(profile.speeds))), ...
    "activationThreshold", ...
        double(profile.actionCommandActivationThreshold), ...
    "commandLevels", double(profile.actionCommandLevels));
weights = struct( ...
    "position", double(profile.intentRewardPositionWeight), ...
    "velocity", double(profile.intentRewardVelocityWeight), ...
    "action", double(profile.intentRewardActionWeight), ...
    "deltaAction", double(profile.intentRewardDeltaActionWeight), ...
    "saturation", double(profile.intentRewardSaturationWeight), ...
    "softActionLimit", double(profile.intentRewardSoftActionLimit));
audit = table(logical(profile.run_training), logical(profile.newTraining), ...
    logical(profile.simMotors), logical(profile.connect_glove), ...
    string(profile.referenceSource), string(profile.observationVariant), ...
    string(profile.rewardType), string(profile.actionInterfaceVariant), ...
    weights.position, weights.velocity, weights.action, ...
    weights.deltaAction, weights.saturation, weights.softActionLimit, ...
    'VariableNames', ["historicalRunTraining", "historicalNewTraining", ...
    "historicalSimMotors", "historicalConnectGlove", ...
    "referenceSource", "observationVariant", "rewardType", ...
    "actionInterfaceVariant", "positionWeight", "velocityWeight", ...
    "actionWeight", "deltaActionWeight", "saturationWeight", ...
    "softActionLimit"]);
end

function [training, audit] = loadTrainingCorpus(inventory, options)
layout = buildObservationLayout("intentMarkov60", 40, 3, 4);
stateCells = cell(height(inventory), 1);
previousCells = cell(height(inventory), 1);
episodeCells = cell(height(inventory), 1);
stepCells = cell(height(inventory), 1);
rawCells = cell(height(inventory), 1);
effectiveCells = cell(height(inventory), 1);
pwmCells = cell(height(inventory), 1);
rewardCells = cell(height(inventory), 1);
rewardVectorCells = cell(height(inventory), 1);
rewardInfoCells = cell(height(inventory), 1);
auditRows = repmat(struct("episode", 0, "stepCount", 0, ...
    "firstActiveStep", 0, "preActivationStateCount", 0, ...
    "temporalPreviousActionMaximumError", NaN, ...
    "rewardInfoComplete", false), height(inventory), 1);
requiredRewardFields = ["trackingMse", "trackingMae", "velocityMse", ...
    "actionL2", "smoothnessPenalty", "deltaActionL2", ...
    "saturationFraction", "softSaturationPenalty", ...
    "saturationPenalty", "referenceSource"];
for episodeIdx = 1:height(inventory)
    expectedName = sprintf("episode%05d.mat", episodeIdx);
    if inventory.fileName(episodeIdx) ~= expectedName
        error("run_no_glove_stage7e_checkpoint_evolution:EpisodeOrder", ...
            "Training inventory is not in canonical order.");
    end
    required = ["stateLog", "actionLog", "actionSatLog", ...
        "actionPwmLog", "rewardLog", "rewardVectorLog", ...
        "rewardInfoLog", "referenceSource", ...
        "observationVariant", "stateLength"];
    available = string(who("-file", inventory.path(episodeIdx)));
    if ~all(ismember(required, available))
        error("run_no_glove_stage7e_checkpoint_evolution:EpisodeIncomplete", ...
            "Training episode %d is incomplete.", episodeIdx);
    end
    requiredCell = cellstr(required);
    loaded = load(inventory.path(episodeIdx), requiredCell{:});
    x = double(loaded.stateLog);
    raw = double(loaded.actionLog);
    effective = double(loaded.actionSatLog);
    pwm = double(loaded.actionPwmLog);
    reward = double(loaded.rewardLog(:));
    rewardVector = double(loaded.rewardVectorLog);
    stepCount = size(x, 1);
    temporalError = max(abs(x(2:end, ...
        layout.previousEffectiveAction)-effective(1:end-1, :)), [], "all");
    if stepCount ~= 61 || size(x, 2) ~= 60 || ...
            ~isequal(size(raw), [stepCount, 4]) || ...
            ~isequal(size(effective), [stepCount, 4]) || ...
            ~isequal(size(pwm), [stepCount, 4]) || ...
            numel(reward) ~= stepCount || ...
            ~isequal(size(rewardVector), [stepCount, 4]) || ...
            numel(loaded.rewardInfoLog) ~= stepCount || ...
            string(loaded.referenceSource) ~= "emgIntent" || ...
            string(loaded.observationVariant) ~= "intentMarkov60" || ...
            double(loaded.stateLength) ~= 60 || ...
            any(~isfinite(x), "all") || any(~isfinite(raw), "all") || ...
            any(~isfinite(effective), "all") || any(~isfinite(pwm), "all") || ...
            any(~isfinite(reward), "all") || ...
            any(~isfinite(rewardVector), "all") || ...
            temporalError > options.referenceTolerance
        error("run_no_glove_stage7e_checkpoint_evolution:EpisodeInvalid", ...
            "Training episode %d violates the recorded-state contract.", ...
            episodeIdx);
    end
    zeroVelocity = max(abs(x(:, layout.referenceVelocity)), [], 2) <= ...
        options.referenceTolerance;
    held = [false; max(abs(diff(x(:, layout.referencePosition))), [], 2) <= ...
        options.referenceTolerance];
    firstActive = find(~zeroVelocity, 1, "first");
    pre = zeroVelocity & held & (1:stepCount)' < firstActive;
    selectedSteps = find(pre);
    if isempty(firstActive) || firstActive ~= 13 || sum(pre) ~= 11
        error("run_no_glove_stage7e_checkpoint_evolution:PreRestCoverage", ...
            "Episode %d must contribute the canonical 11 pre-rest states.", ...
            episodeIdx);
    end
    rewardInfoStruct = vertcat(loaded.rewardInfoLog{selectedSteps});
    complete = all(isfield(rewardInfoStruct, cellstr(requiredRewardFields)));
    if ~complete
        error("run_no_glove_stage7e_checkpoint_evolution:RewardInfoIncomplete", ...
            "Episode %d rewardInfo is incomplete.", episodeIdx);
    end
    stateCells{episodeIdx} = x(pre, :);
    previousCells{episodeIdx} = ...
        x(selectedSteps-1, layout.referencePosition);
    episodeCells{episodeIdx} = repmat(episodeIdx, sum(pre), 1);
    stepCells{episodeIdx} = selectedSteps;
    rawCells{episodeIdx} = raw(pre, :);
    effectiveCells{episodeIdx} = effective(pre, :);
    pwmCells{episodeIdx} = pwm(pre, :);
    rewardCells{episodeIdx} = reward(pre);
    rewardVectorCells{episodeIdx} = rewardVector(pre, :);
    rewardInfoCells{episodeIdx} = struct2table(rewardInfoStruct);
    auditRows(episodeIdx) = struct("episode", episodeIdx, ...
        "stepCount", stepCount, "firstActiveStep", firstActive, ...
        "preActivationStateCount", sum(pre), ...
        "temporalPreviousActionMaximumError", temporalError, ...
        "rewardInfoComplete", complete);
end
training = struct("state", vertcat(stateCells{:}), ...
    "episode", vertcat(episodeCells{:}), ...
    "step", vertcat(stepCells{:}), ...
    "previousReferencePosition", vertcat(previousCells{:}), ...
    "historicalRawAction", vertcat(rawCells{:}), ...
    "historicalEffectiveAction", vertcat(effectiveCells{:}), ...
    "historicalPwm", vertcat(pwmCells{:}), ...
    "recordedReward", vertcat(rewardCells{:}), ...
    "recordedRewardVector", vertcat(rewardVectorCells{:}), ...
    "rewardInfo", vertcat(rewardInfoCells{:}));
if size(training.state, 1) ~= 2200
    error("run_no_glove_stage7e_checkpoint_evolution:CorpusSize", ...
        "Canonical ETAPA 7E corpus must contain 2200 states.");
end
audit = struct2table(auditRows);
end

function [checkpoints, audit] = loadFrozenCheckpoints(inventory)
checkpoints = repmat(struct("label", "", "episode", 0, ...
    "evaluator", []), 1, height(inventory));
auditRows = repmat(struct("label", "", "episode", 0, "class", "", ...
    "observationDimension", 0, "actionDimension", 0, ...
    "learnableParameterCount", 0, "experienceBufferLength", NaN, ...
    "experienceBufferMaxLength", NaN, ...
    "trainingResultLastEpisode", NaN, ...
    "trainingResultTotalAgentSteps", NaN), height(inventory), 1);
for checkpointIdx = 1:height(inventory)
    loaded = load(inventory.path(checkpointIdx), ...
        "saved_agent", "savedAgentResult");
    if ~isfield(loaded, "saved_agent") || ...
            ~isfield(loaded, "savedAgentResult")
        error("run_no_glove_stage7e_checkpoint_evolution:CheckpointInvalid", ...
            "%s lacks agent or training result.", inventory.label(checkpointIdx));
    end
    agent = loaded.saved_agent;
    actor = getActor(agent);
    parameters = getLearnableParameters(actor);
    parameterCount = sum(cellfun(@numel, parameters));
    observationDimension = prod(double(agent.ObservationInfo.Dimension));
    actionDimension = prod(double(agent.ActionInfo.Dimension));
    result = loaded.savedAgentResult;
    lastEpisode = double(result.EpisodeIndex(end));
    totalSteps = double(result.TotalAgentSteps(end));
    if ~isa(agent, "rl.agent.rlTD3Agent") || ...
            observationDimension ~= 60 || actionDimension ~= 4 || ...
            lastEpisode ~= inventory.episode(checkpointIdx) || ...
            ~isprop(agent, "ExperienceBuffer")
        error("run_no_glove_stage7e_checkpoint_evolution:CheckpointDrift", ...
            "%s architecture or episode label drifted.", ...
            inventory.label(checkpointIdx));
    end
    actorLocal = actor;
    checkpoints(checkpointIdx) = struct( ...
        "label", inventory.label(checkpointIdx), ...
        "episode", inventory.episode(checkpointIdx), ...
        "evaluator", @(states) evaluateFrozenActorStates( ...
            actorLocal, states));
    auditRows(checkpointIdx) = struct( ...
        "label", inventory.label(checkpointIdx), ...
        "episode", inventory.episode(checkpointIdx), ...
        "class", string(class(agent)), ...
        "observationDimension", observationDimension, ...
        "actionDimension", actionDimension, ...
        "learnableParameterCount", parameterCount, ...
        "experienceBufferLength", double(agent.ExperienceBuffer.Length), ...
        "experienceBufferMaxLength", ...
            double(agent.ExperienceBuffer.MaxLength), ...
        "trainingResultLastEpisode", lastEpisode, ...
        "trainingResultTotalAgentSteps", totalSteps);
end
audit = struct2table(auditRows);
end

function value = subsetTraining(value, mask)
fields = fieldnames(value);
for fieldIdx = 1:numel(fields)
    field = fields{fieldIdx};
    data = value.(field);
    if istable(data) && height(data) == numel(mask)
        value.(field) = data(mask, :);
    elseif ~istable(data) && size(data, 1) == numel(mask)
        value.(field) = data(mask, :);
    end
end
end

function writeAnalysisTables(runDir, analysis, checkpointAudit, ...
        trainingAudit, profileAudit)
writetable(checkpointAudit, fullfile(runDir, "checkpoint_audit.csv"));
writetable(trainingAudit, fullfile(runDir, "training_episode_audit.csv"));
writetable(profileAudit, fullfile(runDir, "training_profile_audit.csv"));
writetable(analysis.checkpointSummary, ...
    fullfile(runDir, "checkpoint_summary.csv"));
writetable(analysis.checkpointMotorSummary, ...
    fullfile(runDir, "checkpoint_motor_summary.csv"));
writetable(analysis.checkpointEpisodeSummary, ...
    fullfile(runDir, "checkpoint_episode_summary.csv"));
writetable(analysis.checkpointTrend, ...
    fullfile(runDir, "checkpoint_trend.csv"));
writetable(analysis.checkpointActionComponents, ...
    fullfile(runDir, "checkpoint_action_components.csv"));
writetable(analysis.historicalSummary, ...
    fullfile(runDir, "historical_training_summary.csv"));
writetable(analysis.historicalMotorSummary, ...
    fullfile(runDir, "historical_training_motor_summary.csv"));
writetable(analysis.blockEndReplayComparison, ...
    fullfile(runDir, "block_end_replay_comparison.csv"));
writetable(analysis.rewardAuditTable, ...
    fullfile(runDir, "recorded_reward_terms.csv"));
writetable(analysis.rewardSummary, ...
    fullfile(runDir, "recorded_reward_summary.csv"));
writetable(analysis.rewardEpisodeSummary, ...
    fullfile(runDir, "recorded_reward_episode_summary.csv"));
writetable(analysis.rewardAudit, fullfile(runDir, "reward_audit.csv"));
writetable(analysis.sourceDecision, fullfile(runDir, "source_decision.csv"));
end

function command = buildReproducibleCommand(matlabRoot, options, resultsRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7e_checkpoint_evolution(struct(" + ...
    "'stage7dRunRoot','%s','resultsRoot','%s'," + ...
    "'referenceTolerance',%.17g,'rewardTolerance',%.17g," + ...
    "'falseActivationLimit',%.17g," + ...
    "'materialRelativeAttenuation',%.17g," + ...
    "'saturationThreshold',%.17g))", ...
    escape(matlabRoot), escape(options.stage7dRunRoot), ...
    escape(resultsRoot), options.referenceTolerance, ...
    options.rewardTolerance, options.falseActivationLimit, ...
    options.materialRelativeAttenuation, options.saturationThreshold);
end

function writeOfflineReport(pathValue, analysis, elapsedSec, runDir)
decision = analysis.sourceDecision(1, :);
rewardAll = analysis.rewardSummary(analysis.rewardSummary.episodeBlock == ...
    "allEpisodes", :);
lines = [ ...
    "# ETAPA 7E - evolucion offline del comando de reposo"; ""; ...
    "- Ejecucion de ingenieria: PASS."; ...
    "- Clasificacion: `" + decision.classification + "`."; ...
    "- Primer checkpoint activo: `" + ...
        decision.firstActiveCheckpoint + "`."; ...
    sprintf("- PWM abs. medio Agent50/Agent200: %.9f / %.9f.", ...
        decision.earlyMeanAbsPwm, decision.finalMeanAbsPwm); ...
    sprintf("- Reduccion relativa Agent50->Agent200: %.9f.", ...
        decision.relativeMeanAbsPwmReduction); ...
    sprintf("- Error maximo de auditoria reward: %.17g.", ...
        analysis.rewardAudit.maximumAuditError); ...
    sprintf("- Reward medio registrado en reposo: %.9f.", ...
        rewardAll.meanRecordedReward); ...
    "- Causa raiz unica identificada: no."; ...
    "- Entrenamiento/Env/simulador/reward function/DTW/hardware: no/no/no/no/no/no."; ...
    sprintf("- Tiempo de analisis: %.6f s.", elapsedSec); ...
    "- Ruta: `" + string(runDir) + "`." ...
    ];
writeText(pathValue, strjoin(lines, newline));
end

function hashes = hashPaths(paths)
hashes = strings(numel(paths), 1);
for pathIdx = 1:numel(paths)
    if ~isfile(paths(pathIdx))
        error("run_no_glove_stage7e_checkpoint_evolution:InputNotFound", ...
            "Missing input %s.", paths(pathIdx));
    end
    hashes(pathIdx) = fileSha256(paths(pathIdx));
end
end

function expected = findArtifactHash(artifactHashes, artifactName)
paths = string({artifactHashes.path});
match = paths == artifactName;
if sum(match) ~= 1
    error("run_no_glove_stage7e_checkpoint_evolution:HashNotFound", ...
        "Manifest does not contain one hash for %s.", artifactName);
end
expected = upper(string(artifactHashes(match).sha256));
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[workingStatus, ~] = system(sprintf('git -C "%s" diff --quiet', repoRoot));
[indexStatus, ~] = system(sprintf( ...
    'git -C "%s" diff --cached --quiet', repoRoot));
trackedDirty = workingStatus ~= 0 || indexStatus ~= 0;
end

function hash = fileSha256(filePath)
escapedPath = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escapedPath);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7e_checkpoint_evolution:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = upper(string(strtrim(output)));
end

function escaped = escape(value)
escaped = strrep(char(string(value)), "'", "''");
end

function writeText(filePath, value)
[fid, message] = fopen(filePath, "w", "n", "UTF-8");
if fid < 0
    error("run_no_glove_stage7e_checkpoint_evolution:WriteFailed", ...
        "Could not open %s: %s.", filePath, message);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
try
    clearConfigurablesOverride();
catch
end
try
    cd(originalDir);
catch
end
end
