function report = run_no_glove_stage7j_causal_hold_latch_audit(options)
%run_no_glove_stage7j_causal_hold_latch_audit replays a latch offline.
%
% The frozen 7I corpus is read as numeric tables. No agent, Env, simulator,
% reward function, training, DTW or hardware route is invoked.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7j_causal_hold_latch");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7j_causal_hold_latch_audit:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testResults = runtests(fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage7jCausalLatch.m"));
save(fullfile(runRoot, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7j_causal_hold_latch_audit:TestsFailed", ...
        "ETAPA 7J tests failed. See %s.", runRoot);
end

[stage7i, frozen, sourceHashesBefore, parentAudit] = ...
    loadAndValidateInput(options.stage7iRunRoot);
episodeHashesBefore = rehashEpisodeInputs(frozen.inputHashesBefore);
if ~isequal(frozen.inputHashesBefore, episodeHashesBefore)
    error("run_no_glove_stage7j_causal_hold_latch_audit:EpisodeHash", ...
        "A frozen 7H episode differs from the 7I inventory.");
end
analysis = analyzeNoGloveStage7jCausalLatch(frozen.windows);
episodeHashesAfter = rehashEpisodeInputs(frozen.inputHashesBefore);
if ~isequal(episodeHashesBefore, episodeHashesAfter)
    error("run_no_glove_stage7j_causal_hold_latch_audit:InputModified", ...
        "A frozen episode changed during the offline replay.");
end
sourceHashesAfter = hashStage7iSources(options.stage7iRunRoot);
if ~isequal(sourceHashesBefore, sourceHashesAfter)
    error("run_no_glove_stage7j_causal_hold_latch_audit:SourceModified", ...
        "A frozen 7I artifact changed during the offline replay.");
end

writetable(episodeHashesBefore, ...
    fullfile(runRoot, "episode_input_hashes.csv"));
writetable(sourceHashesBefore, fullfile(runRoot, "source_hashes.csv"));
writetable(parentAudit, fullfile(runRoot, "parent_audit.csv"));
writetable(analysis.windowAudit, ...
    fullfile(runRoot, "window_latch_audit.csv"));
writetable(analysis.segmentAudit, ...
    fullfile(runRoot, "stopped_segment_audit.csv"));
writetable(analysis.restEpisodeAudit, ...
    fullfile(runRoot, "rest_episode_audit.csv"));
writetable(analysis.sourceSummary, ...
    fullfile(runRoot, "source_summary.csv"));
writetable(analysis.variantSummary, ...
    fullfile(runRoot, "variant_summary.csv"));
writetable(analysis.gateChecks, fullfile(runRoot, "gate_checks.csv"));
writetable(analysis.sourceDecision, ...
    fullfile(runRoot, "source_decision.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = string(stage7i.agent7250CheckpointPath);
agent7250Hash = fileSha256(agent7250Path);
if agent7250Hash ~= string(stage7i.agent7250CheckpointSha256)
    error("run_no_glove_stage7j_causal_hold_latch_audit:Agent7250Hash", ...
        "The canonical Agent7250 file changed.");
end
manifest = struct("stage", "7J", "schemaVersion", 1, ...
    "result", "PASS", "scientificResult", analysis.classification, ...
    "contractSupported", analysis.contractSupported, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7j_causal_hold_latch_audit", ...
    "preregistrationCommit", ...
        "2de6cb380a97d7a34653a3774216816cc1ea7aa7", ...
    "stage7iRunRoot", options.stage7iRunRoot, ...
    "stage7iManifestSha256", sourceHashesBefore.sha256(1), ...
    "stage7iResultsSha256", sourceHashesBefore.sha256(2), ...
    "stage7iWindowCorpusSha256", sourceHashesBefore.sha256(3), ...
    "stage7iEpisodeInventorySha256", sourceHashesBefore.sha256(4), ...
    "stage7hRunRoot", string(stage7i.stage7hRunRoot), ...
    "stage7jInputEpisodeCount", height(episodeHashesBefore), ...
    "stage7jInputWindowCount", height(frozen.windows), ...
    "inputsPreserved", true, "parentAudit", table2struct(parentAudit), ...
    "thresholds", analysis.thresholds, ...
    "variantSummary", table2struct(analysis.variantSummary), ...
    "gateChecks", table2struct(analysis.gateChecks), ...
    "sourceDecision", table2struct(analysis.sourceDecision), ...
    "prefixCheckCount", analysis.prefixCheckCount, ...
    "prefixMismatchCount", analysis.prefixMismatchCount, ...
    "explicitMemoryRequired", analysis.explicitMemoryRequired, ...
    "proposedObservationVariant", analysis.proposedObservationVariant, ...
    "proposedObservationDimension", ...
        analysis.proposedObservationDimension, ...
    "observationVariantImplemented", false, ...
    "behavioralInterventionExecuted", false, ...
    "behavioralAblationAuthorized", false, ...
    "rootCauseIdentified", false, ...
    "referenceSource", "emgIntent", ...
    "observationVariant", "intentMarkov60", ...
    "actionInterfaceVariant", "baselineQuantized", ...
    "policyChanged", false, "stateChanged", false, ...
    "rewardChanged", false, "referenceChanged", false, ...
    "quantizationChanged", false, "simulatorChanged", false, ...
    "safetyLayerChanged", false, "runTraining", false, ...
    "newTraining", false, "agentLoaded", false, ...
    "envCreated", false, "simulatorInvoked", false, ...
    "rewardFunctionInvoked", false, "dtwCalculated", false, ...
    "simMotors", true, "hardwareUsed", false, ...
    "pilotAuthorized", false, "longCampaignAuthorized", false, ...
    "agent7250Loaded", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", agent7250Hash, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);
save(fullfile(runRoot, "stage7j_results.mat"), "manifest", ...
    "analysis", "episodeHashesBefore", "sourceHashesBefore", ...
    "parentAudit", "stage7i", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "contractSupported", analysis.contractSupported, ...
    "outputPath", runRoot, "manifest", manifest, ...
    "analysis", analysis);
fprintf("ETAPA 7J CAUSAL HOLD LATCH AUDIT PASS\n");
fprintf("Scientific result: %s\n", analysis.classification);
fprintf("Contract supported: %d\n", analysis.contractSupported);
fprintf("Output: %s\n", runRoot);
disp(analysis.variantSummary);
disp(analysis.gateChecks);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7j_causal_hold_latch_audit:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct("resultsRoot", "", "stage7iRunRoot", ...
    "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7i_artifacts\" + ...
    "stage7i_final\2026-08-28_17-54-13-526");
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7j_causal_hold_latch_audit:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.stage7iRunRoot = string(options.stage7iRunRoot);
if ~isfile(fullfile(options.stage7iRunRoot, "manifest.json"))
    error("run_no_glove_stage7j_causal_hold_latch_audit:MissingStage7i", ...
        "ETAPA 7I manifest not found under %s.", options.stage7iRunRoot);
end
end

function [manifest, frozen, sourceHashes, parentAudit] = ...
        loadAndValidateInput(root)
manifest = jsondecode(fileread(fullfile(root, "manifest.json")));
valid = string(manifest.stage) == "7I" && ...
    string(manifest.result) == "PASS" && ...
    string(manifest.scientificResult) == ...
        "holdSupportNotSeparableFromFarCorrection" && ...
    double(manifest.episodeInputCount) == 548 && ...
    double(manifest.windowCount) == 31220 && ...
    logical(manifest.episodeInputsPreserved) && ...
    ~logical(manifest.runTraining) && ...
    ~logical(manifest.simulatorInvoked) && ...
    ~logical(manifest.agentLoaded) && ~logical(manifest.envCreated) && ...
    ~logical(manifest.rewardFunctionInvoked) && ...
    ~logical(manifest.dtwCalculated) && ~logical(manifest.hardwareUsed) && ...
    ~logical(manifest.agent7250Loaded) && ...
    string(manifest.referenceSource) == "emgIntent" && ...
    string(manifest.observationVariant) == "intentMarkov60" && ...
    string(manifest.actionInterfaceVariant) == "baselineQuantized";
if ~valid
    error("run_no_glove_stage7j_causal_hold_latch_audit:Stage7iContract", ...
        "Input manifest is not the frozen ETAPA 7I result.");
end
required = ["stage7i_results.mat", "window_corpus.csv", ...
    "episode_input_hashes.csv", "source_decision.csv"];
for name = required
    if ~isfile(fullfile(root, name))
        error("run_no_glove_stage7j_causal_hold_latch_audit:Stage7iArtifact", ...
            "Frozen ETAPA 7I artifact %s is missing.", name);
    end
end
data = load(fullfile(root, "stage7i_results.mat"), ...
    "windows", "episodeAudit", "inputHashesBefore", "analysis");
if height(data.windows) ~= 31220 || ...
        height(data.episodeAudit) ~= 548 || ...
        height(data.inputHashesBefore) ~= 548 || ...
        string(data.analysis.classification) ~= ...
        string(manifest.scientificResult) || ...
        data.analysis.behavioralInterventionExecuted || ...
        data.analysis.hardwareUsed
    error("run_no_glove_stage7j_causal_hold_latch_audit:Stage7iResults", ...
        "Frozen ETAPA 7I MAT contents violate the published contract.");
end
frozen = struct("windows", data.windows, ...
    "episodeAudit", data.episodeAudit, ...
    "inputHashesBefore", data.inputHashesBefore, ...
    "analysis", data.analysis);
sourceHashes = hashStage7iSources(root);
parentAudit = table(string(manifest.scientificResult), ...
    double(manifest.episodeInputCount), double(manifest.windowCount), ...
    double(manifest.maximumDiagnosticReplayError), ...
    logical(manifest.episodeInputsPreserved), ...
    logical(manifest.gitTrackedDirty), ...
    string(manifest.gitCommit), ...
    'VariableNames', ["scientificResult", "episodeCount", ...
    "windowCount", "maximumDiagnosticReplayError", ...
    "episodeInputsPreserved", "gitTrackedDirty", "gitCommit"]);
end

function hashes = hashStage7iSources(root)
names = ["manifest.json"; "stage7i_results.mat"; ...
    "window_corpus.csv"; "episode_input_hashes.csv"; ...
    "source_decision.csv"];
labels = ["stage7iManifest"; "stage7iResults"; ...
    "stage7iWindowCorpus"; "stage7iEpisodeInventory"; ...
    "stage7iSourceDecision"];
paths = fullfile(root, names);
sha256 = strings(numel(paths), 1);
bytes = zeros(numel(paths), 1);
for idx = 1:numel(paths)
    info = dir(paths(idx));
    sha256(idx) = fileSha256(paths(idx));
    bytes(idx) = info.bytes;
end
hashes = table(labels, paths, sha256, bytes);
end

function observed = rehashEpisodeInputs(expected)
required = ["variant", "source", "episode", "path", "sha256", "bytes"];
if height(expected) ~= 548 || ~all(ismember(required, ...
        string(expected.Properties.VariableNames)))
    error("run_no_glove_stage7j_causal_hold_latch_audit:EpisodeInventory", ...
        "The frozen episode inventory is incomplete.");
end
observed = expected;
for idx = 1:height(expected)
    path = string(expected.path(idx));
    if ~isfile(path)
        error("run_no_glove_stage7j_causal_hold_latch_audit:EpisodeMissing", ...
            "Frozen episode %s is missing.", path);
    end
    info = dir(path);
    observed.bytes(idx) = info.bytes;
    observed.sha256(idx) = fileSha256(path);
end
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf("cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7j_causal_hold_latch_audit(struct(" + ...
    "'resultsRoot','%s','stage7iRunRoot','%s'))", ...
    escapeQuote(matlabRoot), escapeQuote(string(fileparts(runRoot))), ...
    escapeQuote(options.stage7iRunRoot));
end

function value = buildOfflineReport(manifest)
d = manifest.sourceDecision;
lines = ["# ETAPA 7J - causal hold latch offline audit"; ""; ...
    "- Engineering result: PASS."; ...
    "- Scientific result: " + manifest.scientificResult + "."; ...
    "- Contract supported: " + string(manifest.contractSupported) + "."; ...
    sprintf("- Candidate rest coverage: %.9f.", ...
        d.candidateRestCoverage); ...
    sprintf("- Candidate far-correction exposure: %.9f.", ...
        d.candidateFarCorrectionExposure); ...
    sprintf("- Recovered windows: %d.", ...
        d.candidateRecoveredWindowCount); ...
    sprintf("- Premature latch windows: %d.", ...
        d.candidatePrematureLatchWindowCount); ...
    "- Explicit memory required: " + ...
        string(manifest.explicitMemoryRequired) + "."; ...
    "- State/reward behavior changed: no/no; training/simulation/hardware: no/no/no."];
value = strjoin(lines, newline);
end

function hashes = inventoryArtifacts(runRoot)
names = ["test_results.mat", "episode_input_hashes.csv", ...
    "source_hashes.csv", "parent_audit.csv", ...
    "window_latch_audit.csv", "stopped_segment_audit.csv", ...
    "rest_episode_audit.csv", "source_summary.csv", ...
    "variant_summary.csv", "gate_checks.csv", ...
    "source_decision.csv", "stage7j_results.mat", ...
    "offline_report.md", "reproducible_command.txt"];
hashes = repmat(struct("path", "", "sha256", ""), numel(names), 1);
for idx = 1:numel(names)
    hashes(idx).path = names(idx);
    hashes(idx).sha256 = fileSha256(fullfile(runRoot, names(idx)));
end
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
commit = "unknown";
if status == 0
    commit = string(strtrim(output));
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[trackedStatus, trackedOutput] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = trackedStatus ~= 0 || ...
    strlength(strtrim(string(trackedOutput))) > 0;
end

function hash = fileSha256(path)
fid = fopen(path, "r");
if fid < 0
    error("run_no_glove_stage7j_causal_hold_latch_audit:HashFailed", ...
        "Could not open %s for hashing.", path);
end
cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid, Inf, "*uint8");
digest = java.security.MessageDigest.getInstance("SHA-256");
digest.update(bytes);
digestBytes = typecast(digest.digest(), "uint8");
hash = upper(string(reshape(dec2hex(digestBytes, 2)', 1, [])));
end

function value = escapeQuote(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7j_causal_hold_latch_audit:WriteFailed", ...
        "Could not open %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
