function report = run_no_glove_stage7d_training_support(options)
%run_no_glove_stage7d_training_support executes ETAPA 7D only.
%
% Agent200 is frozen. The launcher compares the 128 ETAPA 7B pre-rest
% observations with real observations saved during its 200 training
% episodes. It does not create Env, run the simulator, calculate reward or
% DTW, train, alter behavior or use hardware.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
addpath(genpath(fullfile(matlabRoot, "tests")));
clearConfigurablesOverride();

[stage7cManifest, inputPaths] = validateStage7c(options.stage7cRunRoot);
inputHashesBefore = hashInputPaths(inputPaths);
[queryInventory, queryHashesBefore] = ...
    validateQueryInventory(inputPaths.queryInventory);
agentPath = string(stage7cManifest.agentCheckpointPath);
agentHashBefore = fileSha256(agentPath);
if agentHashBefore ~= upper(string( ...
        stage7cManifest.agentCheckpointSha256After))
    error("run_no_glove_stage7d_training_support:AgentHashMismatch", ...
        "Agent200 does not match the ETAPA 7C manifest.");
end
trainingRoot = string(fileparts(agentPath));
[trainingInventory, trainingHashesBefore] = ...
    buildTrainingInventory(trainingRoot);

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7d_training_support");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runDir)
    error("run_no_glove_stage7d_training_support:OutputExists", ...
        "Refusing to reuse output directory %s.", runDir);
end
mkdir(runDir);

testPath = fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage7dTrainingSupport.m");
testResults = runtests(testPath);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7d_training_support:TestsFailed", ...
        "ETAPA 7D tests failed. See %s.", runDir);
end

query = loadQueryStates(queryInventory, options);
[training, trainingEpisodeAudit] = loadTrainingStates( ...
    trainingInventory, options);
[agent, checkpointAudit, checkpointContents] = ...
    auditCheckpoint(agentPath);
[queryActorEvaluator, trainingActorEvaluator, ...
    biaslessActorEvaluator, batchCrosscheckEvaluator, biasAudit] = ...
    buildActorEvaluators(agent);
actuator = loadActuatorContract(inputPaths.effectiveProfile, ...
    stage7cManifest);
evaluationRouteAudit = buildEvaluationRouteAudit(query, ...
    queryActorEvaluator, batchCrosscheckEvaluator, actuator);

analysisOptions = struct( ...
    "referenceTolerance", options.referenceTolerance, ...
    "replayTolerance", options.replayTolerance, ...
    "scaleTolerance", options.scaleTolerance, ...
    "distanceTolerance", options.distanceTolerance, ...
    "supportQuantile", options.supportQuantile, ...
    "minimumSupportFraction", options.minimumSupportFraction, ...
    "falseActivationLimit", options.falseActivationLimit, ...
    "materialRawActionDelta", options.materialRawActionDelta, ...
    "minimumMaterialBiasFraction", ...
        options.minimumMaterialBiasFraction, ...
    "minimumBiasActiveReduction", ...
        options.minimumBiasActiveReduction, ...
    "saturationThreshold", options.saturationThreshold);
analysisArguments = namedargs2cell(analysisOptions);

smokeQuery = subsetRows(query, query.episode <= 2);
smokeTraining = subsetRows(training, training.episode <= 4);
smokeAnalysis = analyzeNoGloveStage7dTrainingSupport( ...
    smokeQuery, smokeTraining, queryActorEvaluator, ...
    trainingActorEvaluator, biaslessActorEvaluator, ...
    biasAudit, actuator, analysisArguments{:});
if smokeAnalysis.replayMaximumAbsoluteError > options.replayTolerance || ...
        smokeAnalysis.runTraining || smokeAnalysis.envCreated || ...
        smokeAnalysis.simulatorInvoked || smokeAnalysis.rewardInvoked || ...
        smokeAnalysis.hardwareUsed
    error("run_no_glove_stage7d_training_support:SmokeFailed", ...
        "Offline smoke violated an ETAPA 7D invariant.");
end
writetable(smokeAnalysis.sourceDecision, ...
    fullfile(runDir, "smoke_source_decision.csv"));

analysisTic = tic;
analysis = analyzeNoGloveStage7dTrainingSupport( ...
    query, training, queryActorEvaluator, trainingActorEvaluator, ...
    biaslessActorEvaluator, ...
    biasAudit, actuator, analysisArguments{:});
analysisElapsedSec = toc(analysisTic);

writeAnalysisTables(runDir, analysis, trainingEpisodeAudit, ...
    checkpointAudit, checkpointContents, evaluationRouteAudit);
writetable(trainingInventory, ...
    fullfile(runDir, "training_episode_input_hashes.csv"));
writetable(queryInventory, ...
    fullfile(runDir, "query_episode_input_hashes.csv"));
save(fullfile(runDir, "stage7d_results.mat"), ...
    "analysis", "analysisOptions", "smokeAnalysis", ...
    "checkpointAudit", "checkpointContents", ...
    "evaluationRouteAudit", ...
    "trainingEpisodeAudit", "stage7cManifest", ...
    "analysisElapsedSec", "-v7.3");

inputHashesAfter = hashInputPaths(inputPaths);
queryHashesAfter = hashPaths(queryInventory.path);
trainingHashesAfter = hashPaths(trainingInventory.path);
agentHashAfter = fileSha256(agentPath);
if ~isequal(inputHashesAfter, inputHashesBefore) || ...
        ~isequal(queryHashesAfter, queryHashesBefore) || ...
        ~isequal(trainingHashesAfter, trainingHashesBefore) || ...
        agentHashAfter ~= agentHashBefore
    error("run_no_glove_stage7d_training_support:InputModified", ...
        "ETAPA 7C, training evidence or Agent200 changed during ETAPA 7D.");
end

reproducibleCommand = buildReproducibleCommand( ...
    matlabRoot, options, fileparts(runDir));
writeText(fullfile(runDir, "reproducible_command.txt"), ...
    reproducibleCommand);
writeOfflineReport(fullfile(runDir, "offline_report.md"), ...
    analysis, checkpointAudit, analysisElapsedSec, runDir);

primaryArtifacts = ["test_results.mat", ...
    "smoke_source_decision.csv", ...
    "training_episode_input_hashes.csv", ...
    "query_episode_input_hashes.csv", ...
    "checkpoint_audit.csv", "checkpoint_contents.csv", ...
    "actor_evaluation_route_audit.csv", ...
    "training_episode_audit.csv", "feature_scales.csv", ...
    "block_support.csv", "nearest_training_state_by_block.csv", ...
    "joint_nearest_training_state.csv", ...
    "nearest_state_action_comparison.csv", "action_summary.csv", ...
    "motor_action_summary.csv", "bias_parameter_summary.csv", ...
    "bias_effect_summary.csv", "zero_input_ood_probe.csv", ...
    "source_decision.csv", "stage7d_results.mat", ...
    "reproducible_command.txt", "offline_report.md"];
artifactHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(primaryArtifacts), 1);
for artifactIdx = 1:numel(primaryArtifacts)
    artifactHashes(artifactIdx).path = primaryArtifacts(artifactIdx);
    artifactHashes(artifactIdx).sha256 = fileSha256( ...
        fullfile(runDir, primaryArtifacts(artifactIdx)));
end
writetable(struct2table(artifactHashes), ...
    fullfile(runDir, "artifact_hashes.csv"));

[gitCommit, gitDirty, trackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
decision = analysis.sourceDecision(1, :);
trainingRest = analysis.actionSummary(analysis.actionSummary.source == ...
    "trainingPreActivationHold", :);
queryRest = analysis.actionSummary(analysis.actionSummary.source == ...
    "queryObservedPreRest", :);
biaslessQuery = analysis.actionSummary(analysis.actionSummary.source == ...
    "biaslessQueryObservedPreRest", :);
zeroProbe = analysis.zeroInputProbe(1, :);
manifest = struct( ...
    "stage", "7D", "schemaVersion", 1, "result", "PASS", ...
    "scientificResult", decision.classification, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", trackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7d_training_support", ...
    "inputStage7cRunRoot", options.stage7cRunRoot, ...
    "inputStage7cManifestPath", inputPaths.stage7cManifest, ...
    "inputStage7cManifestSha256Before", ...
        inputHashesBefore.stage7cManifest, ...
    "inputStage7cManifestSha256After", ...
        inputHashesAfter.stage7cManifest, ...
    "inputStage7cResultsSha256Before", ...
        inputHashesBefore.stage7cResults, ...
    "inputStage7cResultsSha256After", ...
        inputHashesAfter.stage7cResults, ...
    "inputEvidencePreserved", isequal(inputHashesBefore, inputHashesAfter), ...
    "queryEpisodeCount", height(queryInventory), ...
    "queryStateCount", analysis.queryStateCount, ...
    "queryEpisodeHashesPreserved", ...
        isequal(queryHashesBefore, queryHashesAfter), ...
    "trainingRoot", trainingRoot, ...
    "trainingEpisodeCount", height(trainingInventory), ...
    "trainingEligibleStateCount", analysis.trainingEligibleStateCount, ...
    "trainingPreActivationStateCount", ...
        analysis.trainingPreActivationStateCount, ...
    "trainingPostActivationStateCount", ...
        analysis.trainingPostActivationStateCount, ...
    "trainingEpisodeHashesPreserved", ...
        isequal(trainingHashesBefore, trainingHashesAfter), ...
    "checkpointExperienceBufferPresent", ...
        checkpointAudit.experienceBufferPresent, ...
    "checkpointExperienceBufferLength", ...
        checkpointAudit.experienceBufferLength, ...
    "checkpointExperienceBufferUsable", ...
        checkpointAudit.experienceBufferUsable, ...
    "querySerialReplayMaximumAbsoluteError", ...
        evaluationRouteAudit.maximumAbsoluteDifference(1), ...
    "queryBatchCrosscheckMaximumAbsoluteDifference", ...
        evaluationRouteAudit.maximumAbsoluteDifference(2), ...
    "queryBatchCrosscheckQuantizationMismatchCount", ...
        evaluationRouteAudit.quantizationMismatchCount(2), ...
    "supportCorpusSource", checkpointAudit.supportCorpusSource, ...
    "analysisOptions", analysisOptions, ...
    "supportCorpusContract", analysis.supportCorpusContract, ...
    "supportCalibrationContract", analysis.supportCalibrationContract, ...
    "jointSupportFraction", decision.jointSupportFraction, ...
    "emgSupportFraction", decision.emgSupportFraction, ...
    "restStateOutOfTrainingSupport", ...
        decision.restStateOutOfTrainingSupport, ...
    "trainingRestAlsoCommands", decision.trainingRestAlsoCommands, ...
    "actorBiasContribution", decision.actorBiasContribution, ...
    "queryRestCommandActiveFraction", ...
        queryRest.commandActiveFraction, ...
    "queryRestWindowAnyCommandFraction", ...
        queryRest.windowAnyCommandFraction, ...
    "trainingRestCommandActiveFraction", ...
        trainingRest.commandActiveFraction, ...
    "trainingRestWindowAnyCommandFraction", ...
        trainingRest.windowAnyCommandFraction, ...
    "biaslessQueryCommandActiveFraction", ...
        biaslessQuery.commandActiveFraction, ...
    "biaslessQueryWindowAnyCommandFraction", ...
        biaslessQuery.windowAnyCommandFraction, ...
    "zeroInputProbeDeclaredOod", zeroProbe.declaredOodProbe, ...
    "zeroInputWithinMeasuredTrainingSupport", ...
        zeroProbe.withinMeasuredTrainingSupport, ...
    "zeroInputInterpretedAsPhysicalEmgAmplitude", false, ...
    "rootCauseIdentified", false, ...
    "agentCheckpointPath", agentPath, ...
    "agentCheckpointLabel", "Agent200", ...
    "agentCheckpointSha256Before", agentHashBefore, ...
    "agentCheckpointSha256After", agentHashAfter, ...
    "agentCheckpointPreserved", agentHashBefore == agentHashAfter, ...
    "agentFrozen", true, "newTraining", false, ...
    "checkpointLoadedForTraining", false, ...
    "hybridStateCreated", false, ...
    "behavioralInterventionExecuted", false, ...
    "compensationInterventionExecuted", false, ...
    "filteredReferenceInterventionExecuted", false, ...
    "dtwCalculated", false, "dtwRewardUsed", false, ...
    "stage8Authorized", false, ...
    "referenceGeneratorChanged", false, "stateChanged", false, ...
    "rewardChanged", false, "policyChanged", false, ...
    "quantizationChanged", false, "simulatorChanged", false, ...
    "safetyLayerChanged", false, "controllerChanged", false, ...
    "simMotorsInvariant", true, "runTraining", false, ...
    "agentLoaded", true, "agentEvaluationOnly", true, ...
    "reinforcementLearningInvoked", true, ...
    "reinforcementLearningTrainingInvoked", false, ...
    "offlineActorReplay", true, "envCreated", false, ...
    "simulatorInvoked", false, "rewardInvoked", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "agent7250Loaded", false, "hardwareUsed", false, ...
    "analysisElapsedSec", analysisElapsedSec, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "artifactHashes", artifactHashes, "outputPath", runDir);
save(fullfile(runDir, "manifest.mat"), "manifest", "artifactHashes");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", "outputPath", runDir, ...
    "manifest", manifest, "analysis", analysis, ...
    "testResults", testResults);
fprintf("ETAPA 7D TRAINING SUPPORT PASS\n");
fprintf("Output: %s\n", runDir);
disp(decision);
disp(analysis.blockSupport);
disp(analysis.actionSummary);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7d_training_support:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct("stage7cRunRoot", "", "resultsRoot", "", ...
    "preRestWindows", 8, "referenceTolerance", 1e-12, ...
    "replayTolerance", 1e-12, "scaleTolerance", 1e-12, ...
    "distanceTolerance", 1e-12, "supportQuantile", 0.95, ...
    "minimumSupportFraction", 0.75, ...
    "falseActivationLimit", 0.01, ...
    "materialRawActionDelta", 0.05, ...
    "minimumMaterialBiasFraction", 0.25, ...
    "minimumBiasActiveReduction", 0.50, ...
    "saturationThreshold", 0.95);
unknown = setdiff(string(fieldnames(options)), ...
    string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7d_training_support:UnknownOption", ...
        "Unknown option(s): %s.", strjoin(unknown, ", "));
end
fields = fieldnames(defaults);
for fieldIdx = 1:numel(fields)
    name = fields{fieldIdx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.stage7cRunRoot = string(options.stage7cRunRoot);
options.resultsRoot = string(options.resultsRoot);
if strlength(options.stage7cRunRoot) == 0
    error("run_no_glove_stage7d_training_support:MissingInput", ...
        "stage7cRunRoot is required.");
end
numericFields = setdiff(string(fieldnames(defaults)), ...
    ["stage7cRunRoot", "resultsRoot"]);
for fieldIdx = 1:numel(numericFields)
    value = options.(numericFields(fieldIdx));
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value < 0
        error("run_no_glove_stage7d_training_support:InvalidOption", ...
            "%s must be a finite nonnegative scalar.", ...
            numericFields(fieldIdx));
    end
end
if fix(options.preRestWindows) ~= options.preRestWindows || ...
        options.preRestWindows < 2 || options.supportQuantile < 0.5 || ...
        options.supportQuantile > 1 || ...
        options.minimumSupportFraction > 1 || ...
        options.falseActivationLimit > 1 || ...
        options.materialRawActionDelta <= 0 || ...
        options.minimumMaterialBiasFraction > 1 || ...
        options.minimumBiasActiveReduction > 1 || ...
        options.saturationThreshold > 1
    error("run_no_glove_stage7d_training_support:InvalidOption", ...
        "ETAPA 7D option bounds are invalid.");
end
end

function [manifest, paths] = validateStage7c(runRoot)
paths = struct( ...
    "stage7cManifest", fullfile(runRoot, "manifest.json"), ...
    "stage7cResults", fullfile(runRoot, "stage7c_results.mat"), ...
    "queryInventory", fullfile(runRoot, "episode_input_hashes.csv"));
fields = fieldnames(paths);
for fieldIdx = 1:numel(fields)
    if ~isfile(paths.(fields{fieldIdx}))
        error("run_no_glove_stage7d_training_support:Stage7cNotFound", ...
            "Missing ETAPA 7C input %s.", paths.(fields{fieldIdx}));
    end
end
manifest = jsondecode(fileread(paths.stage7cManifest));
required = ["stage", "result", "scientificResult", ...
    "rootCauseIdentified", "inputStage7bRunRoot", ...
    "inputStage7bManifestPath", "inputStage7bManifestSha256After", ...
    "inputStage7bResultsSha256After", "inputEpisodeCount", ...
    "preRestStateCount", "replayMaximumAbsoluteError", ...
    "agentCheckpointPath", "agentCheckpointSha256After", ...
    "agentFrozen", "runTraining", "agent7250Loaded", ...
    "envCreated", "simulatorInvoked", "rewardInvoked", ...
    "dtwCalculated", "hardwareUsed", "artifactHashes"];
if ~all(isfield(manifest, cellstr(required)))
    error("run_no_glove_stage7d_training_support:InvalidStage7c", ...
        "ETAPA 7C manifest contract is incomplete.");
end
valid = string(manifest.stage) == "7C" && ...
    string(manifest.result) == "PASS" && ...
    string(manifest.scientificResult) == ...
        "restCommandAtObservedEmgOnlyStateUnresolved" && ...
    ~logical(manifest.rootCauseIdentified) && ...
    double(manifest.inputEpisodeCount) == 16 && ...
    double(manifest.preRestStateCount) == 128 && ...
    double(manifest.replayMaximumAbsoluteError) == 0 && ...
    logical(manifest.agentFrozen) && ~logical(manifest.runTraining) && ...
    ~logical(manifest.agent7250Loaded) && ~logical(manifest.envCreated) && ...
    ~logical(manifest.simulatorInvoked) && ~logical(manifest.rewardInvoked) && ...
    ~logical(manifest.dtwCalculated) && ~logical(manifest.hardwareUsed);
if ~valid
    error("run_no_glove_stage7d_training_support:IncompatibleStage7c", ...
        "ETAPA 7D requires the canonical unresolved ETAPA 7C evidence.");
end
if fileSha256(paths.stage7cResults) ~= findArtifactHash( ...
        manifest.artifactHashes, "stage7c_results.mat")
    error("run_no_glove_stage7d_training_support:Stage7cHashMismatch", ...
        "stage7c_results.mat does not match its manifest.");
end
paths.stage7bManifest = string(manifest.inputStage7bManifestPath);
paths.stage7bResults = fullfile(string(manifest.inputStage7bRunRoot), ...
    "stage7b_results.mat");
paths.effectiveProfile = fullfile(string(manifest.inputStage7bRunRoot), ...
    "effective_evaluation_profile.mat");
if fileSha256(paths.stage7bManifest) ~= upper(string( ...
        manifest.inputStage7bManifestSha256After)) || ...
        fileSha256(paths.stage7bResults) ~= upper(string( ...
        manifest.inputStage7bResultsSha256After)) || ...
        ~isfile(paths.effectiveProfile)
    error("run_no_glove_stage7d_training_support:Stage7bHashMismatch", ...
        "ETAPA 7B evidence behind ETAPA 7C is unavailable or changed.");
end
stage7b = jsondecode(fileread(paths.stage7bManifest));
if fileSha256(paths.effectiveProfile) ~= findArtifactHash( ...
        stage7b.artifactHashes, "effective_evaluation_profile.mat")
    error("run_no_glove_stage7d_training_support:ProfileHashMismatch", ...
        "The ETAPA 7B effective profile changed.");
end
end

function hashes = hashInputPaths(paths)
hashes = struct( ...
    "stage7cManifest", fileSha256(paths.stage7cManifest), ...
    "stage7cResults", fileSha256(paths.stage7cResults), ...
    "queryInventory", fileSha256(paths.queryInventory), ...
    "stage7bManifest", fileSha256(paths.stage7bManifest), ...
    "stage7bResults", fileSha256(paths.stage7bResults), ...
    "effectiveProfile", fileSha256(paths.effectiveProfile));
end

function [inventory, hashes] = validateQueryInventory(pathValue)
inventory = readtable(pathValue, "Delimiter", ",", "TextType", "string", ...
    "VariableNamingRule", "preserve");
required = ["fileName", "path", "sha256", "bytes"];
if ~all(ismember(required, string(inventory.Properties.VariableNames))) || ...
        height(inventory) ~= 16 || numel(unique(inventory.path)) ~= 16
    error("run_no_glove_stage7d_training_support:InvalidQueryInventory", ...
        "The ETAPA 7C inventory must contain 16 unique episodes.");
end
hashes = hashPaths(inventory.path);
if any(hashes ~= upper(inventory.sha256))
    error("run_no_glove_stage7d_training_support:QueryHashMismatch", ...
        "An ETAPA 7B query episode changed.");
end
end

function [inventory, hashes] = buildTrainingInventory(trainingRoot)
files = dir(fullfile(trainingRoot, "episode*.mat"));
names = string({files.name});
[names, order] = sort(names);
files = files(order);
names = names(:);
files = files(:);
if numel(files) ~= 200 || names(1) ~= "episode00001.mat" || ...
        names(end) ~= "episode00200.mat"
    error("run_no_glove_stage7d_training_support:TrainingCoverage", ...
        "Exactly the 200 published training episodes are required.");
end
path = strings(numel(files), 1);
bytes = zeros(numel(files), 1);
for fileIdx = 1:numel(files)
    expected = sprintf("episode%05d.mat", fileIdx);
    if names(fileIdx) ~= expected
        error("run_no_glove_stage7d_training_support:TrainingOrder", ...
            "Training episode sequence is incomplete at %d.", fileIdx);
    end
    path(fileIdx) = fullfile(files(fileIdx).folder, files(fileIdx).name);
    bytes(fileIdx) = files(fileIdx).bytes;
end
hashes = hashPaths(path);
inventory = table(names, path, hashes, bytes, ...
    'VariableNames', ["fileName", "path", "sha256", "bytes"]);
end

function query = loadQueryStates(inventory, options)
rowCount = height(inventory)*options.preRestWindows;
state = nan(rowCount, 60);
rawAction = nan(rowCount, 4);
episode = zeros(rowCount, 1);
step = zeros(rowCount, 1);
cursor = 0;
for episodeIdx = 1:height(inventory)
    required = ["stateLog", "actionLog", "referenceSource", ...
        "observationVariant", "stateLength"];
    available = string(who("-file", inventory.path(episodeIdx)));
    if ~all(ismember(required, available))
        error("run_no_glove_stage7d_training_support:IncompleteQuery", ...
            "Query episode %d is incomplete.", episodeIdx);
    end
    requiredCell = cellstr(required);
    loaded = load(inventory.path(episodeIdx), requiredCell{:});
    x = double(loaded.stateLog);
    u = double(loaded.actionLog);
    rows = cursor+(1:options.preRestWindows);
    if size(x, 2) ~= 60 || size(x, 1) < options.preRestWindows || ...
            ~isequal(size(u, 1), size(x, 1)) || size(u, 2) ~= 4 || ...
            string(loaded.referenceSource) ~= "emgIntent" || ...
            string(loaded.observationVariant) ~= "intentMarkov60" || ...
            double(loaded.stateLength) ~= 60 || ...
            any(~isfinite(x), "all") || any(~isfinite(u), "all") || ...
            any(abs(x(1:options.preRestWindows, 57:60)) > ...
                options.referenceTolerance, "all") || ...
            any(abs(x(1:options.preRestWindows, 53:56)- ...
                x(1, 53:56)) > options.referenceTolerance, "all")
        error("run_no_glove_stage7d_training_support:InvalidQuery", ...
            "Query episode %d is not the validated pre-rest contract.", ...
            episodeIdx);
    end
    state(rows, :) = x(1:options.preRestWindows, :);
    rawAction(rows, :) = u(1:options.preRestWindows, :);
    episode(rows) = episodeIdx;
    step(rows) = (1:options.preRestWindows)';
    cursor = cursor+options.preRestWindows;
end
query = struct("state", state, "rawAction", rawAction, ...
    "episode", episode, "step", step);
end

function [training, audit] = loadTrainingStates(inventory, options)
layout = buildObservationLayout("intentMarkov60", 40, 3, 4);
stateCells = cell(height(inventory), 1);
previousCells = cell(height(inventory), 1);
episodeCells = cell(height(inventory), 1);
stepCells = cell(height(inventory), 1);
phaseCells = cell(height(inventory), 1);
auditRows = repmat(struct("episode", 0, "stepCount", 0, ...
    "eligibleStateCount", 0, "preActivationStateCount", 0, ...
    "postActivationStateCount", 0, "firstActiveStep", 0, ...
    "temporalPreviousActionMaximumError", NaN), height(inventory), 1);
for episodeIdx = 1:height(inventory)
    required = ["stateLog", "actionSatLog", "referenceSource", ...
        "observationVariant", "stateLength"];
    available = string(who("-file", inventory.path(episodeIdx)));
    if ~all(ismember(required, available))
        error("run_no_glove_stage7d_training_support:IncompleteTraining", ...
            "Training episode %d is incomplete.", episodeIdx);
    end
    requiredCell = cellstr(required);
    loaded = load(inventory.path(episodeIdx), requiredCell{:});
    x = double(loaded.stateLog);
    effective = double(loaded.actionSatLog);
    stepCount = size(x, 1);
    temporalError = max(abs(x(2:end, ...
        layout.previousEffectiveAction)-effective(1:end-1, :)), [], "all");
    if stepCount < 3 || size(x, 2) ~= 60 || ...
            ~isequal(size(effective), [stepCount, 4]) || ...
            string(loaded.referenceSource) ~= "emgIntent" || ...
            string(loaded.observationVariant) ~= "intentMarkov60" || ...
            double(loaded.stateLength) ~= 60 || ...
            any(~isfinite(x), "all") || any(~isfinite(effective), "all") || ...
            temporalError > options.replayTolerance
        error("run_no_glove_stage7d_training_support:InvalidTraining", ...
            "Training episode %d violates the state-log contract.", ...
            episodeIdx);
    end
    vRef = x(:, layout.referenceVelocity);
    qRef = x(:, layout.referencePosition);
    heldFromPrior = [false; max(abs(diff(qRef, 1, 1)), [], 2) <= ...
        options.referenceTolerance];
    zeroVelocity = max(abs(vRef), [], 2) <= options.referenceTolerance;
    eligible = heldFromPrior & zeroVelocity;
    firstActive = find(~zeroVelocity, 1, "first");
    if isempty(firstActive)
        error("run_no_glove_stage7d_training_support:NoActiveReference", ...
            "Training episode %d contains no active reference.", episodeIdx);
    end
    pre = eligible & (1:stepCount)' < firstActive;
    post = eligible & (1:stepCount)' > firstActive;
    if ~any(pre) || ~any(post)
        error("run_no_glove_stage7d_training_support:MissingHoldPhase", ...
            "Training episode %d lacks a reference-hold phase.", episodeIdx);
    end
    eligibleSteps = find(eligible);
    phase = repmat("postActivationHold", numel(eligibleSteps), 1);
    phase(eligibleSteps < firstActive) = "preActivationHold";
    stateCells{episodeIdx} = x(eligible, :);
    previousCells{episodeIdx} = qRef(eligibleSteps-1, :);
    episodeCells{episodeIdx} = repmat(episodeIdx, numel(eligibleSteps), 1);
    stepCells{episodeIdx} = eligibleSteps;
    phaseCells{episodeIdx} = phase;
    auditRows(episodeIdx) = struct("episode", episodeIdx, ...
        "stepCount", stepCount, ...
        "eligibleStateCount", sum(eligible), ...
        "preActivationStateCount", sum(pre), ...
        "postActivationStateCount", sum(post), ...
        "firstActiveStep", firstActive, ...
        "temporalPreviousActionMaximumError", temporalError);
end
training = struct("state", vertcat(stateCells{:}), ...
    "episode", vertcat(episodeCells{:}), ...
    "step", vertcat(stepCells{:}), ...
    "previousReferencePosition", vertcat(previousCells{:}), ...
    "phase", vertcat(phaseCells{:}));
audit = struct2table(auditRows);
end

function [agent, audit, contents] = auditCheckpoint(pathValue)
contents = struct2table(whos("-file", pathValue));
agent = loadSavedAgent(pathValue);
present = isprop(agent, "ExperienceBuffer");
if present
    bufferLength = double(agent.ExperienceBuffer.Length);
    bufferMaxLength = double(agent.ExperienceBuffer.MaxLength);
else
    bufferLength = NaN;
    bufferMaxLength = NaN;
end
usable = present && bufferLength > 0;
source = "checkpointExperienceBuffer";
if ~usable
    source = "publishedTrainingEpisodeLogs";
end
directStateMatrix = any(contents.class == "double" & ...
    contains(lower(contents.name), "state") & ...
    contents.size(:, 2) == 60);
audit = table(present, bufferLength, bufferMaxLength, usable, ...
    directStateMatrix, source, ...
    'VariableNames', ["experienceBufferPresent", ...
    "experienceBufferLength", "experienceBufferMaxLength", ...
    "experienceBufferUsable", "checkpointDirectStateMatrixPresent", ...
    "supportCorpusSource"]);
end

function [queryEvaluator, trainingEvaluator, biaslessEvaluator, ...
        batchCrosscheckEvaluator, audit] = ...
        buildActorEvaluators(agent)
actor = getActor(agent);
model = getModel(actor);
learnables = model.Learnables;
biasRows = learnables.Parameter == "Bias";
if sum(biasRows) ~= 3
    error("run_no_glove_stage7d_training_support:UnexpectedActor", ...
        "Agent200 actor must contain exactly three bias vectors.");
end
layer = learnables.Layer(biasRows);
parameterCount = zeros(sum(biasRows), 1);
l1Norm = zeros(sum(biasRows), 1);
l2Norm = zeros(sum(biasRows), 1);
maximumAbsoluteValue = zeros(sum(biasRows), 1);
values = learnables.Value(biasRows);
for rowIdx = 1:numel(values)
    value = double(extractdata(values{rowIdx}));
    parameterCount(rowIdx) = numel(value);
    l1Norm(rowIdx) = sum(abs(value), "all");
    l2Norm(rowIdx) = norm(value(:), 2);
    maximumAbsoluteValue(rowIdx) = max(abs(value), [], "all");
end
parameterTable = table(layer, parameterCount, l1Norm, l2Norm, ...
    maximumAbsoluteValue);

parameters = getLearnableParameters(actor);
for parameterIdx = find(biasRows)'
    parameters{parameterIdx} = zeros(size(parameters{parameterIdx}), ...
        "like", parameters{parameterIdx});
end
biaslessActor = setLearnableParameters(actor, parameters);
queryEvaluator = @(states) evaluateFrozenActorStates(actor, states);
trainingEvaluator = queryEvaluator;
biaslessEvaluator = @(states) ...
    evaluateFrozenActorStates(biaslessActor, states);
batchCrosscheckEvaluator = @(states) ...
    evaluateFrozenActorModelStates(model, states);
zeroState = zeros(1, 60);
audit = struct("parameterTable", parameterTable, ...
    "zeroInputOriginalAction", queryEvaluator(zeroState), ...
    "zeroInputBiaslessAction", biaslessEvaluator(zeroState));
end

function audit = buildEvaluationRouteAudit(query, serialEvaluator, ...
        batchEvaluator, actuator)
serialAction = serialEvaluator(query.state);
batchAction = batchEvaluator(query.state);
[serialEffective, serialPwm] = quantizeLocal(serialAction, actuator);
[batchEffective, batchPwm] = quantizeLocal(batchAction, actuator);
serialReplayError = max(abs(serialAction-query.rawAction), [], "all");
batchDifference = max(abs(batchAction-serialAction), [], "all");
if serialReplayError > 1e-12 || batchDifference > 1e-6
    error("run_no_glove_stage7d_training_support:ActorRouteMismatch", ...
        "Actor evaluation routes exceed their numeric audit tolerance.");
end
batchQuantizationMismatch = sum(serialEffective ~= batchEffective, "all") + ...
    sum(serialPwm ~= batchPwm, "all");
if batchQuantizationMismatch ~= 0
    error("run_no_glove_stage7d_training_support:BatchQuantizationMismatch", ...
        "Vectorized evaluation changes a query PWM decision.");
end
route = ["queryReplay"; "queryBatchCrosscheck"; "trainingSupport"];
evaluator = ["getActionPerRecordedState"; ...
    "dlnetworkPredictCB"; "getActionPerRecordedState"];
stateCount = [size(query.state, 1); size(query.state, 1); NaN];
comparison = ["savedStage7bActionLog"; ...
    "serialGetAction"; "noSavedAgent200Action"];
maximumAbsoluteDifference = [serialReplayError; batchDifference; NaN];
quantizationMismatchCount = [0; batchQuantizationMismatch; NaN];
audit = table(route, evaluator, stateCount, comparison, ...
    maximumAbsoluteDifference, quantizationMismatchCount);
end

function [effective, pwm] = quantizeLocal(actions, actuator)
effective = zeros(size(actions));
pwm = zeros(size(actions));
for rowIdx = 1:size(actions, 1)
    [effectiveRow, pwmRow] = quantizeBaselineAction( ...
        actions(rowIdx, :), actuator.maxPwm, ...
        actuator.activationThreshold, actuator.commandLevels);
    effective(rowIdx, :) = double(effectiveRow(:))';
    pwm(rowIdx, :) = double(pwmRow(:))';
end
end

function actuator = loadActuatorContract(pathValue, manifest)
loaded = load(pathValue, "evaluationProfile");
if ~isfield(loaded, "evaluationProfile")
    error("run_no_glove_stage7d_training_support:MissingProfile", ...
        "ETAPA 7B profile is incomplete.");
end
profile = loaded.evaluationProfile;
required = ["run_training", "newTraining", "agentFile", ...
    "simMotors", "connect_glove", "referenceSource", ...
    "observationVariant", "rewardType", "actionInterfaceVariant", ...
    "quantizeCommandsForSimulation", "speeds", ...
    "actionCommandActivationThreshold", "actionCommandLevels"];
if ~all(isfield(profile, cellstr(required))) || ...
        logical(profile.run_training) || logical(profile.newTraining) || ...
        string(profile.agentFile) ~= string(manifest.agentCheckpointPath) || ...
        ~logical(profile.simMotors) || logical(profile.connect_glove) || ...
        string(profile.referenceSource) ~= "emgIntent" || ...
        string(profile.observationVariant) ~= "intentMarkov60" || ...
        string(profile.rewardType) ~= "trackingIntentActionRateReward" || ...
        string(profile.actionInterfaceVariant) ~= "baselineQuantized" || ...
        ~logical(profile.quantizeCommandsForSimulation)
    error("run_no_glove_stage7d_training_support:ProfileDrift", ...
        "Policy, reference, interface or simulator safety contract drifted.");
end
actuator = struct("maxPwm", max(abs(double(profile.speeds))), ...
    "activationThreshold", ...
        double(profile.actionCommandActivationThreshold), ...
    "commandLevels", double(profile.actionCommandLevels));
end

function value = subsetRows(value, mask)
fields = fieldnames(value);
for fieldIdx = 1:numel(fields)
    field = fields{fieldIdx};
    data = value.(field);
    if size(data, 1) == numel(mask)
        value.(field) = data(mask, :);
    end
end
end

function writeAnalysisTables(runDir, analysis, trainingAudit, ...
        checkpointAudit, checkpointContents, evaluationRouteAudit)
writetable(checkpointAudit, fullfile(runDir, "checkpoint_audit.csv"));
writetable(checkpointContents, fullfile(runDir, "checkpoint_contents.csv"));
writetable(evaluationRouteAudit, ...
    fullfile(runDir, "actor_evaluation_route_audit.csv"));
writetable(trainingAudit, fullfile(runDir, "training_episode_audit.csv"));
writetable(analysis.featureScaleTable, fullfile(runDir, "feature_scales.csv"));
writetable(analysis.blockSupport, fullfile(runDir, "block_support.csv"));
writetable(analysis.nearestByBlock, ...
    fullfile(runDir, "nearest_training_state_by_block.csv"));
writetable(analysis.jointNearest, ...
    fullfile(runDir, "joint_nearest_training_state.csv"));
writetable(analysis.nearestActionTable, ...
    fullfile(runDir, "nearest_state_action_comparison.csv"));
writetable(analysis.actionSummary, fullfile(runDir, "action_summary.csv"));
writetable(analysis.motorActionSummary, ...
    fullfile(runDir, "motor_action_summary.csv"));
writetable(analysis.biasParameterSummary, ...
    fullfile(runDir, "bias_parameter_summary.csv"));
writetable(analysis.biasEffectSummary, ...
    fullfile(runDir, "bias_effect_summary.csv"));
writetable(analysis.zeroInputProbe, ...
    fullfile(runDir, "zero_input_ood_probe.csv"));
writetable(analysis.sourceDecision, ...
    fullfile(runDir, "source_decision.csv"));
end

function command = buildReproducibleCommand(matlabRoot, options, resultsRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7d_training_support(struct(" + ...
    "'stage7cRunRoot','%s','resultsRoot','%s'," + ...
    "'preRestWindows',%d,'referenceTolerance',%.17g," + ...
    "'replayTolerance',%.17g,'scaleTolerance',%.17g," + ...
    "'distanceTolerance',%.17g,'supportQuantile',%.17g," + ...
    "'minimumSupportFraction',%.17g,'falseActivationLimit',%.17g," + ...
    "'materialRawActionDelta',%.17g," + ...
    "'minimumMaterialBiasFraction',%.17g," + ...
    "'minimumBiasActiveReduction',%.17g," + ...
    "'saturationThreshold',%.17g))", ...
    escape(matlabRoot), escape(options.stage7cRunRoot), ...
    escape(resultsRoot), options.preRestWindows, ...
    options.referenceTolerance, options.replayTolerance, ...
    options.scaleTolerance, options.distanceTolerance, ...
    options.supportQuantile, options.minimumSupportFraction, ...
    options.falseActivationLimit, options.materialRawActionDelta, ...
    options.minimumMaterialBiasFraction, ...
    options.minimumBiasActiveReduction, options.saturationThreshold);
end

function writeOfflineReport(pathValue, analysis, checkpointAudit, ...
        elapsedSec, runDir)
decision = analysis.sourceDecision(1, :);
trainingRest = analysis.actionSummary(analysis.actionSummary.source == ...
    "trainingPreActivationHold", :);
lines = [ ...
    "# ETAPA 7D - soporte de entrenamiento y biases del actor"; ""; ...
    "- Ejecucion de ingenieria: PASS."; ...
    "- Clasificacion: `" + decision.classification + "`."; ...
    sprintf("- Replay buffer guardado: presente=%d, longitud=%g, utilizable=%d.", ...
        checkpointAudit.experienceBufferPresent, ...
        checkpointAudit.experienceBufferLength, ...
        checkpointAudit.experienceBufferUsable); ...
    sprintf("- Estados reales elegibles de entrenamiento: %d.", ...
        analysis.trainingEligibleStateCount); ...
    sprintf("- Soporte conjunto/EMG de las consultas: %.9f / %.9f.", ...
        decision.jointSupportFraction, decision.emgSupportFraction); ...
    sprintf("- Activacion por componente en reposo inicial de entrenamiento: %.9f.", ...
        trainingRest.commandActiveFraction); ...
    "- El vector de entrada cero se reporta solo como probe OOD matematico."; ...
    "- Causa raiz unica identificada: no."; ...
    "- Entrenamiento/Env/simulador/reward/DTW/hardware: no/no/no/no/no/no."; ...
    sprintf("- Tiempo de analisis: %.6f s.", elapsedSec); ...
    "- Ruta: `" + string(runDir) + "`." ...
    ];
writeText(pathValue, strjoin(lines, newline));
end

function hashes = hashPaths(paths)
hashes = strings(numel(paths), 1);
for pathIdx = 1:numel(paths)
    if ~isfile(paths(pathIdx))
        error("run_no_glove_stage7d_training_support:InputNotFound", ...
            "Missing input %s.", paths(pathIdx));
    end
    hashes(pathIdx) = fileSha256(paths(pathIdx));
end
end

function expected = findArtifactHash(artifactHashes, artifactName)
paths = string({artifactHashes.path});
match = paths == artifactName;
if sum(match) ~= 1
    error("run_no_glove_stage7d_training_support:HashNotFound", ...
        "Manifest does not contain one hash for %s.", artifactName);
end
expected = upper(string(artifactHashes(match).sha256));
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[workingStatus, ~] = system(sprintf('git -C "%s" diff --quiet', repoRoot));
[indexStatus, ~] = system(sprintf( ...
    'git -C "%s" diff --cached --quiet', repoRoot));
trackedDirty = workingStatus ~= 0 || indexStatus ~= 0;
end

function hash = fileSha256(filePath)
escapedPath = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escapedPath);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7d_training_support:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = upper(string(strtrim(output)));
end

function escaped = escape(value)
escaped = strrep(char(string(value)), "'", "''");
end

function writeText(filePath, value)
[fid, message] = fopen(filePath, "w", "n", "UTF-8");
if fid < 0
    error("run_no_glove_stage7d_training_support:WriteFailed", ...
        "Could not open %s: %s.", filePath, message);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
try
    clearConfigurablesOverride();
catch
end
try
    cd(originalDir);
catch
end
end
