function report = run_no_glove_stage7h_hold_reward_ablation(options)
%run_no_glove_stage7h_hold_reward_ablation runs the bounded paired smoke.
%
% Only intentHoldActionWeight changes: 0 versus 0.20. Both policies use the
% same explicit reward route, start from scratch with seed 11 and stop at
% 200 episodes. Pilot and campaign are never started here.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7h_hold_reward_ablation");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7h_hold_reward_ablation:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testFiles = [ ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testTrackingIntentHoldActionReward.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7hHoldRewardAblation.m")];
testResults = runtests(testFiles);
save(fullfile(runRoot, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7h_hold_reward_ablation:TestsFailed", ...
        "ETAPA 7H tests failed; training is forbidden. See %s.", runRoot);
end

fixed = struct( ...
    "phase", "smoke", "calibrationSeed", 11, ...
    "evaluationSeed", 7601, "evaluationSimulations", 50, ...
    "restSimulations", 24, "positionSafetyAblation", true, ...
    "intentRewardActionWeight", 0.05, ...
    "intentHoldRewardEnabled", true, ...
    "intentHoldVelocityTolerance", 1e-12, ...
    "intentHoldPositionMseTolerance", 1e-4);
controlOptions = fixed;
controlOptions.resultsRoot = fullfile(runRoot, "control_whold_0");
controlOptions.intentHoldActionWeight = 0.00;
candidateOptions = fixed;
candidateOptions.resultsRoot = fullfile(runRoot, "candidate_whold_0p20");
candidateOptions.intentHoldActionWeight = 0.20;

reuseCompletedRuns = strlength(options.completedControlRunRoot) > 0;
if reuseCompletedRuns
    controlReport = loadCompletedStage6Run( ...
        options.completedControlRunRoot);
    candidateReport = loadCompletedStage6Run( ...
        options.completedCandidateRunRoot);
else
    controlReport = run_no_glove_stage6_training(controlOptions);
    candidateReport = run_no_glove_stage6_training(candidateOptions);
end
assertBoundedFreshSmoke(controlReport, 0.00);
assertBoundedFreshSmoke(candidateReport, 0.20);

[profileAudit, initializationAudit, datasetAudit, ...
    zeroWeightEquivalenceAudit] = auditMatchedDesign( ...
    controlReport, candidateReport);
control = buildVariant("control", 0.00, controlReport);
candidate = buildVariant("candidate", 0.20, candidateReport);
analysis = analyzeNoGloveStage7hHoldRewardAblation( ...
    control, candidate);

variantSummary = analysis.variantSummary;
comparison = analysis.comparison;
gateChecks = analysis.gateChecks;
restMotorSummary = analysis.restMotorSummary;
holdContextSummary = buildHoldContextSummary(control, candidate);
checkpointInventory = [addVariantColumn( ...
    controlReport.checkpointTable, "control"); ...
    addVariantColumn(candidateReport.checkpointTable, "candidate")];
writetable(variantSummary, fullfile(runRoot, "variant_summary.csv"));
writetable(comparison, fullfile(runRoot, "comparison.csv"));
writetable(gateChecks, fullfile(runRoot, "gate_checks.csv"));
writetable(restMotorSummary, fullfile(runRoot, "rest_motor_summary.csv"));
writetable(holdContextSummary, ...
    fullfile(runRoot, "hold_context_summary.csv"));
writetable(checkpointInventory, ...
    fullfile(runRoot, "checkpoint_inventory.csv"));
writetable(struct2table(profileAudit), ...
    fullfile(runRoot, "profile_audit.csv"));
writetable(struct2table(initializationAudit), ...
    fullfile(runRoot, "initialization_audit.csv"));
writetable(struct2table(datasetAudit), ...
    fullfile(runRoot, "dataset_audit.csv"));
writetable(struct2table(zeroWeightEquivalenceAudit), ...
    fullfile(runRoot, "zero_weight_equivalence_audit.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", "7H", "schemaVersion", 1, "result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7h_hold_reward_ablation", ...
    "preregistrationCommit", ...
        "fcfd04f1fe5cfd2a4cc548cb1b70f97620f87fe2", ...
    "controlHoldActionWeight", 0.00, ...
    "candidateHoldActionWeight", 0.20, ...
    "sharedActionWeight", 0.05, ...
    "holdVelocityTolerance", 1e-12, ...
    "holdPositionMseTolerance", 1e-4, ...
    "singleChangedFactor", "intentHoldActionWeight", ...
    "protocol", fixed, "episodeBudgetPerVariant", 200, ...
    "seed", 11, "checkpointCadence", 50, ...
    "controlRunRoot", controlReport.outputPath, ...
    "candidateRunRoot", candidateReport.outputPath, ...
    "reusedCompletedChildRuns", reuseCompletedRuns, ...
    "controlManifestSha256", fileSha256(fullfile( ...
        controlReport.outputPath, "manifest.json")), ...
    "candidateManifestSha256", fileSha256(fullfile( ...
        candidateReport.outputPath, "manifest.json")), ...
    "profileAudit", profileAudit, ...
    "initializationAudit", initializationAudit, ...
    "datasetAudit", datasetAudit, ...
    "zeroWeightEquivalenceAudit", zeroWeightEquivalenceAudit, ...
    "thresholds", analysis.thresholds, ...
    "gatePassed", analysis.gatePassed, "gateChecks", analysis.checks, ...
    "comparison", table2struct(comparison), ...
    "control", table2struct(variantSummary(1, :)), ...
    "candidate", table2struct(variantSummary(2, :)), ...
    "rootCauseIdentified", false, ...
    "newTraining", true, "checkpointLoadedForTraining", false, ...
    "agent7250Loaded", false, "agent7250UsedAsStartingPoint", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "referenceSource", "emgIntent", ...
    "observationVariant", "intentMarkov60", ...
    "rewardType", "trackingIntentHoldActionReward", ...
    "actionInterfaceVariant", "baselineQuantized", ...
    "simulationPositionSafetyEnabled", true, ...
    "simMotors", true, "simulatorUsed", true, ...
    "hardwareUsed", false, "dtwCalculated", false, ...
    "pilotAuthorized", false, "longCampaignAuthorized", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);
save(fullfile(runRoot, "stage7h_results.mat"), "manifest", ...
    "analysis", "control", "candidate", "controlReport", ...
    "candidateReport", "profileAudit", "initializationAudit", ...
    "datasetAudit", "zeroWeightEquivalenceAudit", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "gatePassed", analysis.gatePassed, "outputPath", runRoot, ...
    "manifest", manifest, "analysis", analysis, ...
    "controlReport", controlReport, ...
    "candidateReport", candidateReport);
fprintf("ETAPA 7H HOLD REWARD ABLATION PASS\n");
fprintf("Scientific result: %s\n", analysis.classification);
fprintf("Gate passed: %d\n", analysis.gatePassed);
fprintf("Output: %s\n", runRoot);
disp(variantSummary);
disp(comparison);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7h_hold_reward_ablation:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct("resultsRoot", "", ...
    "completedControlRunRoot", "", ...
    "completedCandidateRunRoot", "");
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7h_hold_reward_ablation:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.completedControlRunRoot = string(options.completedControlRunRoot);
options.completedCandidateRunRoot = string( ...
    options.completedCandidateRunRoot);
hasControl = strlength(options.completedControlRunRoot) > 0;
hasCandidate = strlength(options.completedCandidateRunRoot) > 0;
if xor(hasControl, hasCandidate)
    error("run_no_glove_stage7h_hold_reward_ablation:IncompleteResume", ...
        "Both completed child run roots are required for offline resume.");
end
if hasControl
    assertCompletedRunRoot(options.completedControlRunRoot);
    assertCompletedRunRoot(options.completedCandidateRunRoot);
end
end

function assertCompletedRunRoot(runRoot)
required = ["manifest.json", "stage6_results.mat", ...
    fullfile("seed_11", "effective_training_profile.mat")];
for idx = 1:numel(required)
    if ~isfile(fullfile(runRoot, required(idx)))
        error("run_no_glove_stage7h_hold_reward_ablation:InvalidResumeRun", ...
            "Completed child run is missing %s under %s.", ...
            required(idx), runRoot);
    end
end
end

function report = loadCompletedStage6Run(runRoot)
data = load(fullfile(runRoot, "stage6_results.mat"), ...
    "manifest", "seedResults", "seedTable", "checkpointTable");
report = struct("result", string(data.manifest.result), ...
    "phase", string(data.manifest.phase), ...
    "phaseGatePassed", logical(data.manifest.phaseGatePassed), ...
    "outputPath", string(runRoot), "manifest", data.manifest, ...
    "seedTable", data.seedTable, ...
    "checkpointTable", data.checkpointTable, ...
    "seedResults", {data.seedResults});
end

function assertBoundedFreshSmoke(report, expectedHoldWeight)
m = report.manifest;
valid = string(m.phase) == "smoke" && m.protocol.episodes == 200 && ...
    isequal(double(m.seeds), 11) && m.newTraining && ...
    strlength(string(m.checkpointLoadedForTraining)) == 0 && ...
    ~m.agent7250Loaded && ~m.agent7250UsedAsStartingPoint && ...
    m.simMotors && ~m.hardwareUsed && m.positionSafetyAblation && ...
    string(m.referenceSource) == "emgIntent" && ...
    string(m.observationVariant) == "intentMarkov60" && ...
    string(m.rewardType) == "trackingIntentHoldActionReward" && ...
    string(m.actionInterfaceVariant) == "baselineQuantized" && ...
    m.intentRewardActionWeight == 0.05 && ...
    m.intentHoldRewardEnabled && ...
    m.intentHoldActionWeight == expectedHoldWeight && ...
    m.intentHoldVelocityTolerance == 1e-12 && ...
    m.intentHoldPositionMseTolerance == 1e-4;
if ~valid
    error("run_no_glove_stage7h_hold_reward_ablation:InvariantViolation", ...
        "A child smoke violated the pre-registered ETAPA 7H contract.");
end
end

function [profileAudit, initAudit, datasetAudit, rewardAudit] = ...
        auditMatchedDesign(controlReport, candidateReport)
controlPath = fullfile(controlReport.outputPath, ...
    "seed_11", "effective_training_profile.mat");
candidatePath = fullfile(candidateReport.outputPath, ...
    "seed_11", "effective_training_profile.mat");
controlData = load(controlPath, "profile");
candidateData = load(candidatePath, "profile");
control = controlData.profile;
candidate = candidateData.profile;

controlNormalized = normalizeProfile(control);
candidateNormalized = normalizeProfile(candidate);
profileAudit = struct( ...
    "controlHoldActionWeight", control.intentHoldActionWeight, ...
    "candidateHoldActionWeight", candidate.intentHoldActionWeight, ...
    "equalExceptHoldWeightAndOutputPaths", ...
        isequaln(controlNormalized, candidateNormalized), ...
    "sameRandomSeed", control.randomSeed == candidate.randomSeed, ...
    "sameEpisodeBudget", ...
        control.trainingMaxEpisodes == candidate.trainingMaxEpisodes, ...
    "sameCheckpointCadence", ...
        control.trainingSaveAgentEvery == ...
        candidate.trainingSaveAgentEvery, ...
    "sameSafety", isequaln(control.simulationPositionSafety, ...
        candidate.simulationPositionSafety), ...
    "sameSharedRewardSettings", ...
        sharedRewardSettingsEqual(control, candidate));
checks = struct2array(profileAudit);
if ~all(checks(3:end))
    error("run_no_glove_stage7h_hold_reward_ablation:ProfileMismatch", ...
        "Effective profiles differ beyond w_hold and output paths.");
end

initAudit = compareInitialActors(control, candidate);
datasetAudit = compareDatasets(controlReport.manifest, ...
    candidateReport.manifest);
rewardAudit = auditZeroWeightEquivalence(control);
if ~initAudit.actorLearnablesExactlyEqual || ...
        ~datasetAudit.allDatasetContentsEqual || ...
        ~rewardAudit.exactlyEquivalent
    error("run_no_glove_stage7h_hold_reward_ablation:PairingFailed", ...
        "Initialization, datasets or zero-weight reward did not match.");
end
end

function profile = normalizeProfile(profile)
profile.intentHoldActionWeight = 0;
profile.dataset_folder = "<matched-dataset-folder>";
profile = rmfield(profile, "agents_directory");
end

function equal = sharedRewardSettingsEqual(a, b)
fields = ["rewardType", "intentRewardPositionWeight", ...
    "intentRewardVelocityWeight", "intentRewardActionWeight", ...
    "intentRewardDeltaActionWeight", ...
    "intentRewardSaturationWeight", ...
    "intentRewardSoftActionLimit", ...
    "intentHoldVelocityTolerance", ...
    "intentHoldPositionMseTolerance"];
equal = all(arrayfun(@(name) isequaln(a.(name), b.(name)), fields));
end

function audit = compareInitialActors(control, candidate)
clearConfigurablesOverride();
setConfigurablesOverride(control);
rng(double(control.randomSeed), "twister");
agentA = agentNoGloveIntentTd3( ...
    Env.defineObservationInfo(), Env.defineActionInfo());
paramsA = getLearnableParameters(getActor(agentA));
clearConfigurablesOverride();
setConfigurablesOverride(candidate);
rng(double(candidate.randomSeed), "twister");
agentB = agentNoGloveIntentTd3( ...
    Env.defineObservationInfo(), Env.defineActionInfo());
paramsB = getLearnableParameters(getActor(agentB));
clearConfigurablesOverride();
if numel(paramsA) ~= numel(paramsB)
    maxError = Inf;
    parameterCount = NaN;
else
    errors = zeros(numel(paramsA), 1);
    counts = zeros(numel(paramsA), 1);
    for idx = 1:numel(paramsA)
        a = numericParameter(paramsA{idx});
        b = numericParameter(paramsB{idx});
        errors(idx) = max(abs(a-b), [], "all");
        counts(idx) = numel(a);
    end
    maxError = max(errors);
    parameterCount = sum(counts);
end
audit = struct("randomSeed", double(control.randomSeed), ...
    "actorLearnableArrayCount", numel(paramsA), ...
    "actorLearnableParameterCount", parameterCount, ...
    "maximumActorInitializationError", maxError, ...
    "actorLearnablesExactlyEqual", maxError == 0);
end

function value = numericParameter(value)
if isa(value, "dlarray")
    value = extractdata(value);
end
if ~isnumeric(value)
    error("run_no_glove_stage7h_hold_reward_ablation:LearnableType", ...
        "Actor learnables must be numeric or dlarray values.");
end
value = double(value);
end

function audit = compareDatasets(control, candidate)
names = ["trainingDatasetPath", "evaluationDatasetPath", ...
    "restDatasetPath"];
equal = false(1, numel(names));
for idx = 1:numel(names)
    a = load(string(control.(names(idx))), "emgs", "metadata");
    b = load(string(candidate.(names(idx))), "emgs", "metadata");
    equal(idx) = isequaln(a.emgs, b.emgs) && ...
        isequaln(a.metadata, b.metadata);
end
audit = struct( ...
    "trainingDatasetContentEqual", equal(1), ...
    "evaluationDatasetContentEqual", equal(2), ...
    "restDatasetContentEqual", equal(3), ...
    "calibrationContentSha256Equal", ...
        string(control.calibrationContentSha256) == ...
        string(candidate.calibrationContentSha256), ...
    "allDatasetContentsEqual", all(equal));
end

function audit = auditZeroWeightEquivalence(profile)
clearConfigurablesOverride();
setConfigurablesOverride(profile);
contexts = repmat(makeRewardContext(), 3, 1);
contexts(2).trackingPrediction = [0.1, -0.2, 0.3, -0.4];
contexts(2).trackingVelocityPrediction = [0.2, 0, -0.1, 0];
contexts(3).trackingVelocityTarget = [0, 0.01, 0, 0];
contexts(3).decisionPositionPrediction = 0.03.*ones(1, 4);
actions = [0.4, -0.3, 0.2, -0.1; 1, -1, 0.96, 0.94; ...
    0, 0.5, 0, -0.5];
errors = zeros(3, 2);
for idx = 1:3
    [baseReward, baseVector] = trackingIntentActionRateReward( ...
        [], actions(idx, :), contexts(idx));
    [holdReward, holdVector] = trackingIntentHoldActionReward( ...
        [], actions(idx, :), contexts(idx));
    errors(idx, :) = [abs(baseReward-holdReward), ...
        max(abs(baseVector-holdVector))];
end
clearConfigurablesOverride();
audit = struct("caseCount", 3, ...
    "maximumScalarRewardError", max(errors(:, 1)), ...
    "maximumVectorRewardError", max(errors(:, 2)), ...
    "exactlyEquivalent", max(errors, [], "all") == 0);
end

function context = makeRewardContext()
context = struct( ...
    "trackingTarget", zeros(1, 4), ...
    "trackingPrediction", zeros(1, 4), ...
    "trackingVelocityTarget", zeros(1, 4), ...
    "trackingVelocityPrediction", zeros(1, 4), ...
    "decisionPositionPrediction", zeros(1, 4), ...
    "previousEffectiveAction", zeros(1, 4), ...
    "referenceSource", "emgIntent");
end

function variant = buildVariant(label, holdWeight, childReport)
seed = unwrapSingleSeedResult(childReport.seedResults);
settings = struct("actionWeight", holdWeight, ...
    "velocityTolerance", 1e-12, ...
    "positionMseTolerance", 1e-4);
restCommands = summarizeNoGloveStage7fRestCommands(seed.restDirectory);
restHold = summarizeNoGloveStage7hHoldReward( ...
    seed.restDirectory, settings, "requireSteadyRest", true);
restCommands = mergeHoldSummary(restCommands, restHold);
restCommands.positionViolationEpisodeCount = ...
    seed.rest.positionViolationEpisodeCount;
restCommands.positionSafetyInterventionCount = ...
    seed.rest.positionSafetyInterventionCount;
acceptanceHold = summarizeNoGloveStage7hHoldReward( ...
    seed.acceptanceDirectory, settings);
training = selectSafetyMetrics(seed.trainingSafety);
acceptance = selectAcceptanceMetrics(seed.acceptance);
finalRow = childReport.checkpointTable( ...
    childReport.checkpointTable.isFinal, :);
variant = struct("label", label, "holdWeight", holdWeight, ...
    "actionWeight", 0.05, "training", training, ...
    "acceptance", acceptance, "rest", restCommands, ...
    "acceptanceHold", acceptanceHold, ...
    "decodedRestFalseActivationFraction", ...
        childReport.manifest.restFalseActivationFraction, ...
    "checkpointSha256", string(finalRow.checkpointSha256));
end

function seed = unwrapSingleSeedResult(seedResults)
if iscell(seedResults) && isscalar(seedResults)
    seed = seedResults{1};
elseif isstruct(seedResults) && isscalar(seedResults)
    seed = seedResults;
else
    error("run_no_glove_stage7h_hold_reward_ablation:SeedResultContract", ...
        "A 7H child smoke must contain exactly one seed result.");
end
if ~isstruct(seed) || ~isscalar(seed)
    error("run_no_glove_stage7h_hold_reward_ablation:SeedResultContract", ...
        "The single seed result must be a scalar struct.");
end
end

function target = mergeHoldSummary(target, source)
names = string(fieldnames(source));
for idx = 1:numel(names)
    target.(names(idx)) = source.(names(idx));
end
end

function value = selectSafetyMetrics(source)
value = struct("allFinite", logical(source.allFinite), ...
    "positionViolationEpisodeCount", ...
        double(source.positionViolationEpisodeCount), ...
    "positionSafetyInterventionCount", ...
        double(source.positionSafetyInterventionCount));
end

function value = selectAcceptanceMetrics(source)
value = selectSafetyMetrics(source);
names = ["trackingMse", "trackingMae", "actionL2", ...
    "deltaActionL2", "saturationFraction", ...
    "motor2FunctionalFlagCount", "otherMotorFunctionalFlagCount"];
for idx = 1:numel(names)
    value.(names(idx)) = double(source.(names(idx)));
end
end

function tableValue = addVariantColumn(tableValue, label)
tableValue = addvars(tableValue, ...
    repmat(string(label), height(tableValue), 1), ...
    'Before', 1, 'NewVariableNames', "variant");
end

function tableValue = buildHoldContextSummary(control, candidate)
variants = [control, candidate];
rows = cell(4, 1);
cursor = 0;
for variantIdx = 1:2
    value = variants(variantIdx);
    sources = ["acceptance", "steadyRest"];
    summaries = {value.acceptanceHold, value.rest};
    for sourceIdx = 1:2
        cursor = cursor+1;
        summary = summaries{sourceIdx};
        rows{cursor} = table(string(value.label), sources(sourceIdx), ...
            summary.episodeCount, summary.windowCount, ...
            summary.holdActiveFraction, summary.holdPositionMseMean, ...
            summary.holdPositionMseMax, summary.holdVelocityMaxAbs, ...
            summary.holdActionL2Mean, summary.holdActionPenaltyMean, ...
            summary.activeHoldWindowAnyCommandFraction, ...
            summary.maximumDiagnosticReplayError, ...
            'VariableNames', ["variant", "source", "episodeCount", ...
            "windowCount", "holdActiveFraction", ...
            "holdPositionMseMean", "holdPositionMseMax", ...
            "holdVelocityMaxAbs", "holdActionL2Mean", ...
            "holdActionPenaltyMean", ...
            "activeHoldWindowAnyCommandFraction", ...
            "maximumDiagnosticReplayError"]);
    end
end
tableValue = vertcat(rows{:});
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
root = string(fileparts(runRoot));
resume = "";
if strlength(options.completedControlRunRoot) > 0
    resume = sprintf(", 'completedControlRunRoot','%s'," + ...
        "'completedCandidateRunRoot','%s'", ...
        escapeQuote(options.completedControlRunRoot), ...
        escapeQuote(options.completedCandidateRunRoot));
end
command = sprintf("cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7h_hold_reward_ablation(struct(" + ...
    "'resultsRoot','%s'%s))", escapeQuote(matlabRoot), ...
    escapeQuote(root), resume);
end

function value = buildOfflineReport(manifest)
c = manifest.comparison;
lines = ["# ETAPA 7H - hold-conditioned reward ablation"; ""; ...
    "- Engineering result: PASS."; ...
    "- Scientific result: " + manifest.scientificResult + "."; ...
    "- Gate passed: " + string(manifest.gatePassed) + "."; ...
    sprintf("- Tracking MSE ratio: %.9f.", c.trackingMseRatio); ...
    sprintf("- Rest PWM relative reduction: %.9f.", ...
        c.restPwmReduction); ...
    "- Changed factor: intentHoldActionWeight 0 -> 0.20."; ...
    "- Training: two fresh 200-episode seed-11 TD3 policies."; ...
    "- Hardware: no; simulator: yes; DTW: no; pilot: not authorized."];
value = strjoin(lines, newline);
end

function hashes = inventoryArtifacts(runRoot)
names = ["test_results.mat", "variant_summary.csv", ...
    "comparison.csv", "gate_checks.csv", "rest_motor_summary.csv", ...
    "hold_context_summary.csv", "checkpoint_inventory.csv", ...
    "profile_audit.csv", "initialization_audit.csv", ...
    "dataset_audit.csv", "zero_weight_equivalence_audit.csv", ...
    "stage7h_results.mat", "offline_report.md", ...
    "reproducible_command.txt"];
hashes = repmat(struct("path", "", "sha256", ""), numel(names), 1);
for idx = 1:numel(names)
    hashes(idx).path = names(idx);
    hashes(idx).sha256 = fileSha256(fullfile(runRoot, names(idx)));
end
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
commit = "unknown";
if status == 0
    commit = string(strtrim(output));
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[trackedStatus, trackedOutput] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = trackedStatus ~= 0 || ...
    strlength(strtrim(string(trackedOutput))) > 0;
end

function hash = fileSha256(path)
escaped = strrep(char(string(path)), "'", "''");
command = sprintf(['powershell -NoProfile -Command "(Get-FileHash ' ...
    '-Algorithm SHA256 -LiteralPath ''%s'').Hash"'], escaped);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7h_hold_reward_ablation:HashFailed", ...
        "Could not hash %s.", path);
end
hash = string(strtrim(output));
end

function value = escapeQuote(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7h_hold_reward_ablation:WriteFailed", ...
        "Could not open %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
