function report = run_no_glove_stage4_reward_validation(options)
%run_no_glove_stage4_reward_validation validates the causal intent reward.
%
% This launcher runs deterministic numeric tests and one short prerecorded
% EMG-only episode with SimController. It never creates or trains an agent,
% loads a checkpoint, opens a glove, or accesses physical motor hardware.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage4_reward");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runDir)
    error("run_no_glove_stage4_reward_validation:OutputExists", ...
        "Refusing to reuse output directory %s.", runDir);
end
mkdir(runDir);

clearConfigurablesOverride();
rng(options.seed, "twister");
testPath = fullfile(matlabRoot, "tests", "no_glove", ...
    "testTrackingIntentActionRateReward.m");
testResults = runtests(testPath);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage4_reward_validation:TestsFailed", ...
        "At least one ETAPA 4 test failed. See %s.", runDir);
end

[stage2Config, dataset, calibration, expectedContext] = ...
    buildFixture(options.seed);
profile = buildNoGloveStage4Override( ...
    calibration, expectedContext, options.seed);
profile.maxNumberStepsInEpisodes = options.maxSteps;
setConfigurablesOverride(profile);
configs = configurables();
assertSafeStage4Config(configs);
save(fullfile(runDir, "effective_profile.mat"), ...
    "profile", "configs", "stage2Config", "expectedContext");
save(fullfile(runDir, "intent_calibration.mat"), "calibration");

manualCases = evaluateManualCases(configs);
writetable(manualCases, fullfile(runDir, "manual_reward_cases.csv"));
if any(manualCases.absoluteResidual > 1e-12) || ...
        any(~isfinite(manualCases.actualReward))
    error("run_no_glove_stage4_reward_validation:ManualCaseMismatch", ...
        "At least one hand-computed reward case did not match.");
end

samplesPerStep = round(configs.period * dataset.sampleRateHz);
requiredSamples = (options.maxSteps + 1) * samplesPerStep;
if size(dataset.evaluationRawEmg, 1) < requiredSamples
    error("run_no_glove_stage4_reward_validation:InsufficientFixture", ...
        "Synthetic fixture cannot supply the requested smoke length.");
end
smokeEmg = dataset.evaluationRawEmg(1:requiredSamples, :);
emgSet = {smokeEmg, smokeEmg};
env = Env(runDir, true, emgSet, {});
observation = reset(env);
actionPattern = [ ...
    0, 0, 0, 0; ...
    0.4, 0, 0, 0; ...
    -0.4, 0.4, 0, 0; ...
    1, -1, 0.96, 0.94];
stateBefore = nan(options.maxSteps, configs.stateLength);
stateAfter = nan(options.maxSteps, configs.stateLength);
actionRequested = nan(options.maxSteps, 4);
rewardLog = nan(options.maxSteps, 1);
rewardResidual = nan(options.maxSteps, 1);
doneLog = false(options.maxSteps, 1);
stepCount = 0;
isDone = false;
while ~isDone && stepCount < options.maxSteps
    stepCount = stepCount + 1;
    action = actionPattern(mod(stepCount - 1, ...
        size(actionPattern, 1)) + 1, :)';
    stateBefore(stepCount, :) = observation(:)';
    actionRequested(stepCount, :) = action(:)';
    [observation, reward, isDone] = step(env, action);
    stateAfter(stepCount, :) = observation(:)';
    rewardLog(stepCount) = reward;
    doneLog(stepCount) = isDone;
    info = env.rewardInfoLog{stepCount};
    reconstructed = -( ...
        configs.intentRewardPositionWeight * info.trackingMse + ...
        configs.intentRewardVelocityWeight * info.velocityMse + ...
        configs.intentRewardActionWeight * info.actionL2 + ...
        configs.intentRewardDeltaActionWeight * info.deltaActionL2 + ...
        configs.intentRewardSaturationWeight * ...
            info.softSaturationPenalty);
    rewardResidual(stepCount) = reward - reconstructed;
end
if ~isDone
    error("run_no_glove_stage4_reward_validation:EpisodeDidNotFinish", ...
        "The smoke episode exceeded %d steps.", options.maxSteps);
end

stateBefore = stateBefore(1:stepCount, :);
stateAfter = stateAfter(1:stepCount, :);
actionRequested = actionRequested(1:stepCount, :);
rewardLog = rewardLog(1:stepCount);
rewardResidual = rewardResidual(1:stepCount);
doneLog = doneLog(1:stepCount);
env.saveEpisode();
episodeSummary = summarizeEpisodeDirectory(runDir);

metrics = struct( ...
    "episodeSteps", stepCount, ...
    "stateLength", configs.stateLength, ...
    "finiteFraction", mean(isfinite([ ...
        stateBefore, stateAfter, actionRequested, rewardLog]), "all"), ...
    "rewardReconstructionMaxAbs", max(abs(rewardResidual)), ...
    "trackingMseMean", mean(env.trackingMseLog(1:stepCount)), ...
    "trackingMaeMean", mean(env.trackingMaeLog(1:stepCount)), ...
    "velocityMseMean", mean(env.velocityMseLog(1:stepCount)), ...
    "actionL2Mean", mean(env.actionL2Log(1:stepCount)), ...
    "deltaActionL2StepMean", mean(env.deltaActionL2Log(1:stepCount)), ...
    "saturationFraction", ...
        mean(env.saturationFractionLog(1:stepCount)), ...
    "softSaturationPenaltyMean", ...
        mean(env.softSaturationPenaltyLog(1:stepCount)), ...
    "episodeReward", sum(rewardLog), ...
    "referenceHistoryCount", env.referenceHistoryCount, ...
    "hardwareUsed", false, ...
    "simulatorUsed", true, ...
    "reinforcementLearningUsed", false);
assertStage4Metrics(metrics, options.maxSteps);

trace = buildTrace(stateBefore, stateAfter, actionRequested, ...
    env.actionSatLog(1:stepCount, :), rewardLog, rewardResidual, doneLog, ...
    env.trackingMseLog(1:stepCount), ...
    env.trackingMaeLog(1:stepCount), ...
    env.velocityMseLog(1:stepCount), ...
    env.actionL2Log(1:stepCount), ...
    env.deltaActionL2Log(1:stepCount), ...
    env.saturationFractionLog(1:stepCount), ...
    env.softSaturationPenaltyLog(1:stepCount));
writetable(trace, fullfile(runDir, "episode_trace.csv"));
save(fullfile(runDir, "stage4_results.mat"), ...
    "metrics", "manualCases", "episodeSummary", ...
    "stateBefore", "stateAfter", "actionRequested", ...
    "rewardLog", "rewardResidual", "doneLog");
writeOfflineReport(fullfile(runDir, "offline_report.md"), ...
    metrics, configs, calibration, runDir);

reproducibleCommand = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage4_reward_validation(struct('seed',%d," + ...
    "'maxSteps',%d,'resultsRoot','%s'))", ...
    strrep(char(matlabRoot), "'", "''"), options.seed, ...
    options.maxSteps, strrep(char(options.resultsRoot), "'", "''"));
writeText(fullfile(runDir, "reproducible_command.txt"), ...
    reproducibleCommand);

primaryArtifacts = [ ...
    "effective_profile.mat", "intent_calibration.mat", ...
    "test_results.mat", "manual_reward_cases.csv", ...
    "episode00001.mat", "episode_trace.csv", "stage4_results.mat", ...
    "offline_report.md", "reproducible_command.txt"];
artifactHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(primaryArtifacts), 1);
for artifactIdx = 1:numel(primaryArtifacts)
    artifactHashes(artifactIdx).path = primaryArtifacts(artifactIdx);
    artifactHashes(artifactIdx).sha256 = fileSha256( ...
        fullfile(runDir, primaryArtifacts(artifactIdx)));
end
writetable(struct2table(artifactHashes), ...
    fullfile(runDir, "artifact_hashes.csv"));

[gitCommit, gitDirty] = getGitState(repoRoot);
manifest = struct( ...
    "stage", 4, ...
    "schemaVersion", 1, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, ...
    "gitDirty", gitDirty, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage4_reward_validation", ...
    "reproducibleCommand", string(reproducibleCommand), ...
    "seed", options.seed, ...
    "dataProvenance", "synthetic", ...
    "fixtureVersion", stage2Config.fixtureVersion, ...
    "calibrationContentSha256", calibration.contentSha256, ...
    "referenceSource", configs.referenceSource, ...
    "observationVariant", configs.observationVariant, ...
    "stateLength", configs.stateLength, ...
    "actionInterfaceVariant", configs.actionInterfaceVariant, ...
    "rewardType", configs.rewardType, ...
    "rewardWeights", struct( ...
        "wQ", configs.intentRewardPositionWeight, ...
        "wV", configs.intentRewardVelocityWeight, ...
        "wU", configs.intentRewardActionWeight, ...
        "wDu", configs.intentRewardDeltaActionWeight, ...
        "wSat", configs.intentRewardSaturationWeight, ...
        "uSoft", configs.intentRewardSoftActionLimit), ...
    "runTraining", false, ...
    "reinforcementLearningUsed", false, ...
    "simMotors", true, ...
    "simulatorUsed", true, ...
    "usePrerecorded", true, ...
    "connectGlove", false, ...
    "hardwareUsed", false, ...
    "checkpointUsed", "", ...
    "agent7250Used", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "testsIncomplete", sum([testResults.Incomplete]), ...
    "metrics", metrics, ...
    "episodeSummary", episodeSummary, ...
    "artifactHashes", artifactHashes, ...
    "outputPath", runDir);
save(fullfile(runDir, "manifest.mat"), "manifest", "metrics", ...
    "episodeSummary", "artifactHashes");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct( ...
    "result", "PASS", ...
    "outputPath", runDir, ...
    "manifest", manifest, ...
    "metrics", metrics, ...
    "episodeSummary", episodeSummary, ...
    "testResults", testResults);
fprintf("ETAPA 4 causal intent reward validation PASS\n");
fprintf("Output: %s\n", runDir);
disp(struct2table(metrics));
end

function options = normalizeOptions(options)
if ~isscalar(options)
    error("run_no_glove_stage4_reward_validation:InvalidOptions", ...
        "options must be a scalar struct.");
end
allowedFields = ["seed", "maxSteps", "resultsRoot"];
unknown = setdiff(string(fieldnames(options)), allowedFields);
if ~isempty(unknown)
    error("run_no_glove_stage4_reward_validation:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
defaults = struct("seed", 11, "maxSteps", 20, "resultsRoot", "");
fields = fieldnames(defaults);
for fieldIdx = 1:numel(fields)
    if ~isfield(options, fields{fieldIdx})
        options.(fields{fieldIdx}) = defaults.(fields{fieldIdx});
    end
end
if ~isnumeric(options.seed) || ~isscalar(options.seed) || ...
        ~isfinite(options.seed) || options.seed < 0 || ...
        fix(options.seed) ~= options.seed
    error("run_no_glove_stage4_reward_validation:InvalidSeed", ...
        "seed must be a nonnegative integer scalar.");
end
if ~isnumeric(options.maxSteps) || ~isscalar(options.maxSteps) || ...
        ~isfinite(options.maxSteps) || options.maxSteps < 1 || ...
        fix(options.maxSteps) ~= options.maxSteps
    error("run_no_glove_stage4_reward_validation:InvalidMaxSteps", ...
        "maxSteps must be a positive integer scalar.");
end
options.resultsRoot = string(options.resultsRoot);
if ~isscalar(options.resultsRoot) || ismissing(options.resultsRoot)
    error("run_no_glove_stage4_reward_validation:InvalidResultsRoot", ...
        "resultsRoot must be a scalar string or character vector.");
end
end

function [config, dataset, calibration, expected] = buildFixture(seed)
config = buildNoGloveStage2OfflineConfig(seed);
dataset = buildSyntheticEmgIntentDataset(config);
calibration = calibrateEmgIntent(dataset.restCapture, ...
    dataset.instructionTrials, config.calibrationOptions);
options = config.calibrationOptions;
expected = struct( ...
    "userId", dataset.restCapture.userId, ...
    "sessionId", dataset.restCapture.sessionId, ...
    "channelOrder", dataset.restCapture.channelOrder, ...
    "sampleRateHz", dataset.restCapture.sampleRateHz, ...
    "windowLengthSamples", dataset.windowLengthSamples, ...
    "hopLengthSamples", dataset.hopLengthSamples, ...
    "dataProvenance", dataset.restCapture.dataProvenance, ...
    "motorOrder", options.motorOrder, ...
    "units", struct( ...
        "rawEmg", dataset.restCapture.rawEmgUnits, ...
        "envelope", options.envelopeUnits, ...
        "position", options.positionUnits, ...
        "velocity", options.velocityUnits, ...
        "acceleration", options.accelerationUnits), ...
    "synergyMatrixVersion", options.synergyMatrixVersion, ...
    "instructionProtocolVersion", options.instructionProtocolVersion, ...
    "sourceDomain", "rawEmgSameSession", ...
    "calibrationContentSha256", calibration.contentSha256);
end

function assertSafeStage4Config(configs)
unsafe = configs.run_training || configs.newTraining || ...
    ~configs.usePrerecorded || ~configs.simMotors || configs.connect_glove;
if unsafe || configs.referenceSource ~= "emgIntent" || ...
        configs.observationVariant ~= "intentMarkov60" || ...
        configs.stateLength ~= 60 || ~configs.intentDecoderEnabled || ...
        configs.actionInterfaceVariant ~= "baselineQuantized" || ...
        configs.rewardType ~= "trackingIntentActionRateReward" || ...
        configs.intentRewardVelocityWeight ~= 0
    error("run_no_glove_stage4_reward_validation:UnsafeConfig", ...
        "Effective configuration violates the ETAPA 4 profile.");
end
end

function cases = evaluateManualCases(configs)
names = [ ...
    "perfect", "rest", "position_error", "abrupt_action", ...
    "saturation", "motor_1", "motor_2", "motor_3", "motor_4"]';
numCases = numel(names);
actualReward = nan(numCases, 1);
expectedReward = nan(numCases, 1);
trackingMse = nan(numCases, 1);
velocityMse = nan(numCases, 1);
actionL2 = nan(numCases, 1);
deltaActionL2 = nan(numCases, 1);
saturationFraction = nan(numCases, 1);
softSaturationPenalty = nan(numCases, 1);
for caseIdx = 1:numCases
    context = baseContext();
    action = zeros(1, 4);
    switch names(caseIdx)
        case "position_error"
            context.trackingPrediction = [0.4, -0.2, 0.1, 0];
        case "abrupt_action"
            action = [0.5, -0.5, 0.25, -0.25];
        case "saturation"
            action = [1, -1, 0.96, 0.94];
        case {"motor_1", "motor_2", "motor_3", "motor_4"}
            motorIdx = str2double(extractAfter(names(caseIdx), "motor_"));
            context.trackingPrediction(motorIdx) = 0.4;
    end
    [actualReward(caseIdx), ~, info] = ...
        trackingIntentActionRateReward([], action, context);
    trackingMse(caseIdx) = info.trackingMse;
    velocityMse(caseIdx) = info.velocityMse;
    actionL2(caseIdx) = info.actionL2;
    deltaActionL2(caseIdx) = info.deltaActionL2;
    saturationFraction(caseIdx) = info.saturationFraction;
    softSaturationPenalty(caseIdx) = info.softSaturationPenalty;
    expectedReward(caseIdx) = -( ...
        configs.intentRewardPositionWeight * info.trackingMse + ...
        configs.intentRewardVelocityWeight * info.velocityMse + ...
        configs.intentRewardActionWeight * info.actionL2 + ...
        configs.intentRewardDeltaActionWeight * info.deltaActionL2 + ...
        configs.intentRewardSaturationWeight * ...
            info.softSaturationPenalty);
end
absoluteResidual = abs(actualReward - expectedReward);
cases = table(names, actualReward, expectedReward, absoluteResidual, ...
    trackingMse, velocityMse, actionL2, deltaActionL2, ...
    saturationFraction, softSaturationPenalty);
end

function context = baseContext()
context = struct( ...
    "trackingTarget", zeros(1, 4), ...
    "trackingPrediction", zeros(1, 4), ...
    "trackingVelocityTarget", zeros(1, 4), ...
    "trackingVelocityPrediction", zeros(1, 4), ...
    "previousEffectiveAction", zeros(1, 4), ...
    "referenceSource", "emgIntent");
end

function assertStage4Metrics(metrics, expectedSteps)
if metrics.episodeSteps ~= expectedSteps || metrics.stateLength ~= 60 || ...
        metrics.finiteFraction ~= 1 || ...
        metrics.rewardReconstructionMaxAbs > 1e-12 || ...
        metrics.referenceHistoryCount ~= expectedSteps || ...
        metrics.hardwareUsed || ~metrics.simulatorUsed || ...
        metrics.reinforcementLearningUsed
    error("run_no_glove_stage4_reward_validation:GateFailed", ...
        "At least one causal reward smoke gate failed.");
end
end

function trace = buildTrace(stateBefore, stateAfter, rawAction, ...
        effectiveAction, reward, residual, done, trackingMse, ...
        trackingMae, velocityMse, actionL2, deltaActionL2, ...
        saturationFraction, softSaturationPenalty)
step = (1:size(stateBefore, 1))';
beforeNames = compose("state_before_%02d", 1:size(stateBefore, 2));
afterNames = compose("state_after_%02d", 1:size(stateAfter, 2));
rawActionNames = compose("raw_action_%d", 1:4);
effectiveActionNames = compose("effective_action_%d", 1:4);
trace = [table(step, reward, residual, done, trackingMse, ...
    trackingMae, velocityMse, actionL2, deltaActionL2, ...
    saturationFraction, softSaturationPenalty), ...
    array2table(rawAction, "VariableNames", cellstr(rawActionNames)), ...
    array2table(effectiveAction, ...
        "VariableNames", cellstr(effectiveActionNames)), ...
    array2table(stateBefore, "VariableNames", cellstr(beforeNames)), ...
    array2table(stateAfter, "VariableNames", cellstr(afterNames))];
end

function writeOfflineReport(reportPath, metrics, configs, calibration, runDir)
lines = [ ...
    "# ETAPA 4 reward causal sin DTW"; ...
    ""; ...
    "- Resultado: PASS."; ...
    "- Reward: trackingIntentActionRateReward."; ...
    "- Pesos w_q/w_v/w_u/w_du/w_sat: " + ...
        compose("%.6g", configs.intentRewardPositionWeight) + "/" + ...
        compose("%.6g", configs.intentRewardVelocityWeight) + "/" + ...
        compose("%.6g", configs.intentRewardActionWeight) + "/" + ...
        compose("%.6g", configs.intentRewardDeltaActionWeight) + "/" + ...
        compose("%.6g", configs.intentRewardSaturationWeight) + "."; ...
    "- u_soft: " + compose("%.6g", ...
        configs.intentRewardSoftActionLimit) + "."; ...
    "- Pasos simulados: " + metrics.episodeSteps + "."; ...
    "- Residuo maximo reward/reconstruccion: " + ...
        compose("%.12g", metrics.rewardReconstructionMaxAbs) + "."; ...
    "- Checksum calibracion: `" + calibration.contentSha256 + "`."; ...
    "- Hardware/RL usados: no/no. Simulador software: si."; ...
    ""; ...
    "Ruta: `" + string(runDir) + "`." ...
    ];
writeText(reportPath, strjoin(lines, newline));
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end

function [commit, dirty] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status ~= 0
    commit = "unknown";
else
    commit = string(strtrim(output));
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
dirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function hash = fileSha256(filePath)
if ispc
    escapedPath = strrep(char(filePath), "'", "''");
    command = sprintf([ ...
        'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
        '-LiteralPath ''%s'').Hash"'], escapedPath);
else
    command = sprintf('sha256sum "%s"', char(filePath));
end
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage4_reward_validation:HashFailed", ...
        "Could not calculate SHA-256 for %s.", filePath);
end
tokens = split(strtrim(string(output)));
hash = upper(tokens(1));
end

function writeText(filePath, content)
fid = fopen(filePath, "w");
if fid < 0
    error("run_no_glove_stage4_reward_validation:WriteFailed", ...
        "Could not open %s for writing.", filePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s\n", content);
end
