function report = run_no_glove_stage3_state_validation(options)
%run_no_glove_stage3_state_validation validates intentMarkov60 in simulation.
%
% The launcher never trains or loads an agent. It uses prerecorded
% deterministic synthetic EMG, SimController and zero actions to audit
% state ordering, q_ref initialization and transition-time causality.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage3_state");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runDir)
    error("run_no_glove_stage3_state_validation:OutputExists", ...
        "Refusing to reuse output directory %s.", runDir);
end
mkdir(runDir);

clearConfigurablesOverride();
rng(options.seed, "twister");
testPath = fullfile(matlabRoot, "tests", "no_glove", ...
    "testIntentMarkov60.m");
testResults = runtests(testPath);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage3_state_validation:TestsFailed", ...
        "At least one ETAPA 3 test failed. See %s.", runDir);
end

[stage2Config, dataset, calibration, expectedContext] = ...
    buildFixture(options.seed);
profile = buildNoGloveStage3Override( ...
    calibration, expectedContext, options.seed);
setConfigurablesOverride(profile);
configs = configurables();
assertSafeStage3Config(configs);

effectiveProfilePath = fullfile(runDir, "effective_profile.mat");
save(effectiveProfilePath, "profile", "configs", "stage2Config", ...
    "expectedContext");
calibrationPath = fullfile(runDir, "intent_calibration.mat");
save(calibrationPath, "calibration");

emgSet = {dataset.evaluationRawEmg, dataset.evaluationRawEmg};
env = Env(runDir, true, emgSet, {});
layout = buildObservationLayout("intentMarkov60", ...
    configs.numEMGFeatures, configs.emgHistoryLength, 4);
observationInfo = env.getObservationInfo();
observation = reset(env);
initialObservation = observation;
maxSteps = configs.maxNumberStepsInEpisodes;
stateBeforeLog = nan(maxSteps, layout.totalLength);
stateAfterLog = nan(maxSteps, layout.totalLength);
rewardLog = nan(maxSteps, 1);
doneLog = false(maxSteps, 1);
referenceUsedLog = nan(maxSteps, 4);
predictionLog = nan(maxSteps, 4);
effectiveActionLog = nan(maxSteps, 4);

stepCount = 0;
isDone = false;
while ~isDone && stepCount < maxSteps
    stepCount = stepCount + 1;
    stateBeforeLog(stepCount, :) = observation(:)';
    [observation, reward, isDone] = step(env, zeros(4, 1));
    stateAfterLog(stepCount, :) = observation(:)';
    rewardLog(stepCount) = reward;
    doneLog(stepCount) = isDone;
    referenceUsedLog(stepCount, :) = env.referenceHistory(stepCount, :);
    predictionLog(stepCount, :) = ...
        env.trackingPredictionHistory(stepCount, :);
    effectiveActionLog(stepCount, :) = env.actionSatLog(stepCount, :);
end
if ~isDone
    error("run_no_glove_stage3_state_validation:EpisodeDidNotFinish", ...
        "Synthetic episode exceeded %d steps.", maxSteps);
end

stateBeforeLog = stateBeforeLog(1:stepCount, :);
stateAfterLog = stateAfterLog(1:stepCount, :);
rewardLog = rewardLog(1:stepCount);
doneLog = doneLog(1:stepCount);
referenceUsedLog = referenceUsedLog(1:stepCount, :);
predictionLog = predictionLog(1:stepCount, :);
effectiveActionLog = effectiveActionLog(1:stepCount, :);

metrics = calculateMetrics(initialObservation, stateBeforeLog, ...
    stateAfterLog, referenceUsedLog, effectiveActionLog, ...
    calibration, layout, rewardLog, stepCount, ...
    observationInfo.LowerLimit, observationInfo.UpperLimit);
assertStage3Metrics(metrics);
stateTrace = buildStateTrace(stateBeforeLog, stateAfterLog, ...
    rewardLog, doneLog, referenceUsedLog, predictionLog);
writetable(stateTrace, fullfile(runDir, "state_trace.csv"));
save(fullfile(runDir, "stage3_results.mat"), ...
    "metrics", "layout", "initialObservation", "stateBeforeLog", ...
    "stateAfterLog", "rewardLog", "doneLog", ...
    "referenceUsedLog", "predictionLog", "effectiveActionLog");

reportPath = fullfile(runDir, "offline_report.md");
writeOfflineReport(reportPath, metrics, calibration, runDir);
reproducibleCommand = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage3_state_validation(struct('seed',%d," + ...
    "'resultsRoot','%s'))", ...
    strrep(char(matlabRoot), "'", "''"), options.seed, ...
    strrep(char(options.resultsRoot), "'", "''"));
writeText(fullfile(runDir, "reproducible_command.txt"), ...
    reproducibleCommand);

primaryArtifacts = [ ...
    "effective_profile.mat", "intent_calibration.mat", ...
    "test_results.mat", "state_trace.csv", "stage3_results.mat", ...
    "offline_report.md", "reproducible_command.txt"];
artifactHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(primaryArtifacts), 1);
for artifactIdx = 1:numel(primaryArtifacts)
    artifactHashes(artifactIdx).path = primaryArtifacts(artifactIdx);
    artifactHashes(artifactIdx).sha256 = fileSha256( ...
        fullfile(runDir, primaryArtifacts(artifactIdx)));
end
artifactHashTable = struct2table(artifactHashes);
writetable(artifactHashTable, fullfile(runDir, "artifact_hashes.csv"));

[gitCommit, gitDirty] = getGitState(repoRoot);
manifest = struct( ...
    "stage", 3, ...
    "schemaVersion", 1, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, ...
    "gitDirty", gitDirty, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage3_state_validation", ...
    "reproducibleCommand", string(reproducibleCommand), ...
    "seed", options.seed, ...
    "dataProvenance", "synthetic", ...
    "fixtureVersion", stage2Config.fixtureVersion, ...
    "calibrationContentSha256", calibration.contentSha256, ...
    "referenceSource", configs.referenceSource, ...
    "observationVariant", configs.observationVariant, ...
    "stateLength", configs.stateLength, ...
    "stateOrder", [ ...
        "phi_EMG_1_40", "q_41_44", "delta_q_45_48", ...
        "u_eff_previous_49_52", "q_ref_53_56", "v_ref_57_60"], ...
    "period", configs.period, ...
    "actionInterfaceVariant", configs.actionInterfaceVariant, ...
    "rewardType", configs.rewardType, ...
    "runTraining", false, ...
    "reinforcementLearningUsed", false, ...
    "simMotors", true, ...
    "simulatorUsed", true, ...
    "usePrerecorded", true, ...
    "connectGlove", false, ...
    "hardwareUsed", false, ...
    "checkpointUsed", "", ...
    "agent7250Used", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "testsIncomplete", sum([testResults.Incomplete]), ...
    "metrics", metrics, ...
    "effectiveProfileSha256", fileSha256(effectiveProfilePath), ...
    "artifactHashes", artifactHashes, ...
    "artifactHashesCsvSha256", fileSha256( ...
        fullfile(runDir, "artifact_hashes.csv")), ...
    "outputPath", runDir);
save(fullfile(runDir, "manifest.mat"), "manifest", "metrics", ...
    "artifactHashes");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct( ...
    "result", "PASS", ...
    "outputPath", runDir, ...
    "manifest", manifest, ...
    "metrics", metrics, ...
    "testResults", testResults);
fprintf("ETAPA 3 intentMarkov60 validation PASS\n");
fprintf("Output: %s\n", runDir);
disp(struct2table(metrics));
end

function options = normalizeOptions(options)
if ~isscalar(options)
    error("run_no_glove_stage3_state_validation:InvalidOptions", ...
        "options must be a scalar struct.");
end
allowedFields = ["seed", "resultsRoot"];
unknown = setdiff(string(fieldnames(options)), allowedFields);
if ~isempty(unknown)
    error("run_no_glove_stage3_state_validation:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
defaults = struct("seed", 11, "resultsRoot", "");
fields = fieldnames(defaults);
for fieldIdx = 1:numel(fields)
    if ~isfield(options, fields{fieldIdx})
        options.(fields{fieldIdx}) = defaults.(fields{fieldIdx});
    end
end
if ~isnumeric(options.seed) || ~isscalar(options.seed) || ...
        ~isfinite(options.seed) || options.seed < 0 || ...
        fix(options.seed) ~= options.seed
    error("run_no_glove_stage3_state_validation:InvalidSeed", ...
        "seed must be a nonnegative integer scalar.");
end
options.resultsRoot = string(options.resultsRoot);
if ~isscalar(options.resultsRoot) || ismissing(options.resultsRoot)
    error("run_no_glove_stage3_state_validation:InvalidResultsRoot", ...
        "resultsRoot must be a scalar string or character vector.");
end
end

function [config, dataset, calibration, expected] = buildFixture(seed)
config = buildNoGloveStage2OfflineConfig(seed);
dataset = buildSyntheticEmgIntentDataset(config);
calibration = calibrateEmgIntent(dataset.restCapture, ...
    dataset.instructionTrials, config.calibrationOptions);
options = config.calibrationOptions;
expected = struct( ...
    "userId", dataset.restCapture.userId, ...
    "sessionId", dataset.restCapture.sessionId, ...
    "channelOrder", dataset.restCapture.channelOrder, ...
    "sampleRateHz", dataset.restCapture.sampleRateHz, ...
    "windowLengthSamples", dataset.windowLengthSamples, ...
    "hopLengthSamples", dataset.hopLengthSamples, ...
    "dataProvenance", dataset.restCapture.dataProvenance, ...
    "motorOrder", options.motorOrder, ...
    "units", struct( ...
        "rawEmg", dataset.restCapture.rawEmgUnits, ...
        "envelope", options.envelopeUnits, ...
        "position", options.positionUnits, ...
        "velocity", options.velocityUnits, ...
        "acceleration", options.accelerationUnits), ...
    "synergyMatrixVersion", options.synergyMatrixVersion, ...
    "instructionProtocolVersion", options.instructionProtocolVersion, ...
    "sourceDomain", "rawEmgSameSession", ...
    "calibrationContentSha256", calibration.contentSha256);
end

function assertSafeStage3Config(configs)
unsafe = configs.run_training || configs.newTraining || ...
    ~configs.usePrerecorded || ~configs.simMotors || configs.connect_glove;
if unsafe || configs.referenceSource ~= "emgIntent" || ...
        configs.observationVariant ~= "intentMarkov60" || ...
        configs.stateLength ~= 60 || ~configs.intentDecoderEnabled || ...
        configs.actionInterfaceVariant ~= "baselineQuantized" || ...
        configs.rewardType ~= "trackingMseActionRateReward"
    error("run_no_glove_stage3_state_validation:UnsafeConfig", ...
        "Effective configuration violates the ETAPA 3 profile.");
end
end

function metrics = calculateMetrics(initialObservation, stateBefore, ...
        stateAfter, referenceUsed, effectiveAction, ...
        calibration, layout, rewardLog, stepCount, lowerLimit, upperLimit)
qRefBefore = stateBefore(:, layout.referencePosition);
qRefAfter = stateAfter(:, layout.referencePosition);
vRefAfter = stateAfter(:, layout.referenceVelocity);
vRefBefore = stateBefore(:, layout.referenceVelocity);
integrationResidual = qRefAfter - qRefBefore - ...
    calibration.limits.deltaT .* vRefAfter;
accelerationStep = calibration.limits.accelerationMax .* ...
    calibration.limits.deltaT;
stateBoundsViolationCount = nnz(stateBefore < lowerLimit' | ...
    stateBefore > upperLimit') + nnz(stateAfter < lowerLimit' | ...
    stateAfter > upperLimit');

metrics = struct( ...
    "episodeSteps", stepCount, ...
    "stateLength", size(stateAfter, 2), ...
    "finiteFraction", mean(isfinite([stateBefore, stateAfter, rewardLog]), "all"), ...
    "initialReferenceEncoderError", max(abs( ...
        initialObservation(layout.referencePosition) - ...
        initialObservation(layout.encoder))), ...
    "referenceRewardAlignmentMaxAbs", max(abs( ...
        qRefBefore - referenceUsed), [], "all"), ...
    "integrationResidualMaxAbs", max(abs(integrationResidual), [], "all"), ...
    "previousActionAlignmentMaxAbs", max(abs( ...
        stateAfter(:, layout.previousEffectiveAction) - effectiveAction), [], "all"), ...
    "velocityViolationCount", nnz(abs(vRefAfter) > ...
        calibration.limits.velocityMax + 1e-12), ...
    "accelerationViolationCount", nnz(abs(vRefAfter - vRefBefore) > ...
        accelerationStep + 1e-12), ...
    "positionViolationCount", nnz(qRefAfter < ...
        calibration.limits.positionMin - 1e-12 | qRefAfter > ...
        calibration.limits.positionMax + 1e-12), ...
    "stateBoundsViolationCount", stateBoundsViolationCount, ...
    "referenceMotionMaxAbs", max(abs(qRefAfter - ...
        initialObservation(layout.referencePosition)'), [], "all"), ...
    "rewardFiniteFraction", mean(isfinite(rewardLog)), ...
    "hardwareUsed", false, ...
    "simulatorUsed", true, ...
    "reinforcementLearningUsed", false);
end

function assertStage3Metrics(metrics)
if metrics.stateLength ~= 60 || metrics.finiteFraction ~= 1 || ...
        metrics.initialReferenceEncoderError > 1e-12 || ...
        metrics.referenceRewardAlignmentMaxAbs > 1e-12 || ...
        metrics.integrationResidualMaxAbs > 1e-12 || ...
        metrics.previousActionAlignmentMaxAbs > 1e-12 || ...
        metrics.velocityViolationCount ~= 0 || ...
        metrics.accelerationViolationCount ~= 0 || ...
        metrics.positionViolationCount ~= 0 || ...
        metrics.stateBoundsViolationCount ~= 0 || ...
        metrics.referenceMotionMaxAbs <= 0 || ...
        metrics.rewardFiniteFraction ~= 1
    error("run_no_glove_stage3_state_validation:GateFailed", ...
        "At least one intentMarkov60 validation gate failed.");
end
end

function trace = buildStateTrace(stateBefore, stateAfter, reward, done, ...
        referenceUsed, prediction)
step = (1:size(stateBefore, 1))';
beforeNames = compose("state_before_%02d", 1:size(stateBefore, 2));
afterNames = compose("state_after_%02d", 1:size(stateAfter, 2));
referenceNames = compose("reference_used_%d", 1:4);
predictionNames = compose("tracking_prediction_%d", 1:4);
trace = [table(step, reward, done), ...
    array2table(stateBefore, "VariableNames", cellstr(beforeNames)), ...
    array2table(stateAfter, "VariableNames", cellstr(afterNames)), ...
    array2table(referenceUsed, "VariableNames", cellstr(referenceNames)), ...
    array2table(prediction, "VariableNames", cellstr(predictionNames))];
end

function writeOfflineReport(reportPath, metrics, calibration, runDir)
lines = [ ...
    "# ETAPA 3 intentMarkov60 smoke"; ...
    ""; ...
    "- Resultado: PASS."; ...
    "- Estado: 60 = 40 EMG + 4 q + 4 Deltaq + 4 u_eff,t-1 + 4 q_ref + 4 v_ref."; ...
    "- Pasos: " + metrics.episodeSteps + "."; ...
    "- Error reset q_ref/encoder: " + ...
        compose("%.12g", metrics.initialReferenceEncoderError) + "."; ...
    "- Error de alineacion referencia/reward: " + ...
        compose("%.12g", metrics.referenceRewardAlignmentMaxAbs) + "."; ...
    "- Residuo maximo de integracion: " + ...
        compose("%.12g", metrics.integrationResidualMaxAbs) + "."; ...
    "- Violaciones posicion/velocidad/aceleracion: " + ...
        metrics.positionViolationCount + "/" + ...
        metrics.velocityViolationCount + "/" + ...
        metrics.accelerationViolationCount + "."; ...
    "- Checksum calibracion: `" + calibration.contentSha256 + "`."; ...
    "- Hardware/RL usados: no/no. Simulador software: si."; ...
    ""; ...
    "Ruta: `" + string(runDir) + "`." ...
    ];
writeText(reportPath, strjoin(lines, newline));
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end

function [commit, dirty] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status ~= 0
    commit = "unknown";
else
    commit = string(strtrim(output));
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
dirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function hash = fileSha256(filePath)
if ispc
    escapedPath = strrep(char(filePath), "'", "''");
    command = sprintf([ ...
        'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
        '-LiteralPath ''%s'').Hash"'], escapedPath);
else
    command = sprintf('sha256sum "%s"', char(filePath));
end
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage3_state_validation:HashFailed", ...
        "Could not calculate SHA-256 for %s.", filePath);
end
tokens = split(strtrim(string(output)));
hash = upper(tokens(1));
end

function writeText(filePath, content)
fid = fopen(filePath, "w");
if fid < 0
    error("run_no_glove_stage3_state_validation:WriteFailed", ...
        "Could not open %s for writing.", filePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s\n", content);
end
