function report = run_no_glove_stage7k_intent_provenance_audit(options)
%run_no_glove_stage7k_intent_provenance_audit replays intent provenance.
%
% Scientific results are reconstructed offline from raw EMG logs. Runtime
% tests exercise only additive diagnostic logging with SimController.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7k_intent_provenance");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7k_intent_provenance_audit:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testFiles = [ ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7kIntentProvenance.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testIntentMarkov60.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testReferenceSources.m")];
testResults = runtests(testFiles);
save(fullfile(runRoot, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7k_intent_provenance_audit:TestsFailed", ...
        "ETAPA 7K tests failed. See %s.", runRoot);
end

[stage7j, stage7i, frozen, profiles, sourceHashesBefore, ...
    parentAudit] = loadAndValidateInputs(options.stage7jRunRoot);
episodeHashesBefore = rehashEpisodeInputs(frozen.inputHashesBefore);
if ~isequal(frozen.inputHashesBefore, episodeHashesBefore)
    error("run_no_glove_stage7k_intent_provenance_audit:EpisodeHash", ...
        "A frozen episode differs from the 7I inventory.");
end
analysis = replayNoGloveStage7kIntentProvenance( ...
    frozen.episodeAudit, frozen.windows, frozen.latchAudit, profiles);
episodeHashesAfter = rehashEpisodeInputs(frozen.inputHashesBefore);
if ~isequal(episodeHashesBefore, episodeHashesAfter)
    error("run_no_glove_stage7k_intent_provenance_audit:InputModified", ...
        "A frozen episode changed during the offline replay.");
end
sourceHashesAfter = hashFrozenSources(options.stage7jRunRoot, ...
    string(stage7j.stage7iRunRoot), stage7i);
if ~isequal(sourceHashesBefore, sourceHashesAfter)
    error("run_no_glove_stage7k_intent_provenance_audit:SourceModified", ...
        "A frozen parent artifact changed during the replay.");
end

loggingContractAudit = table("intentProvenanceLog", 1, true, true, ...
    false, false, false, false, true, ...
    'VariableNames', ["logVariable", "schemaVersion", ...
    "resetPerEpisode", "savedPerTransition", ...
    "includedInObservation", "includedInRewardContext", ...
    "changesReference", "changesAction", "glovePathRemainsEmpty"]);
writetable(episodeHashesBefore, ...
    fullfile(runRoot, "episode_input_hashes.csv"));
writetable(sourceHashesBefore, fullfile(runRoot, "source_hashes.csv"));
writetable(parentAudit, fullfile(runRoot, "parent_audit.csv"));
writetable(loggingContractAudit, ...
    fullfile(runRoot, "logging_contract_audit.csv"));
writetable(analysis.decisionAudit, ...
    fullfile(runRoot, "decision_provenance.csv"));
writetable(analysis.transitionAudit, ...
    fullfile(runRoot, "transition_replay.csv"));
writetable(analysis.episodeReplayAudit, ...
    fullfile(runRoot, "episode_replay_audit.csv"));
writetable(analysis.provenanceSummary, ...
    fullfile(runRoot, "provenance_summary.csv"));
writetable(analysis.segmentProvenanceAudit, ...
    fullfile(runRoot, "segment_provenance.csv"));
writetable(analysis.gateChecks, fullfile(runRoot, "gate_checks.csv"));
writetable(analysis.sourceDecision, ...
    fullfile(runRoot, "source_decision.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = string(stage7j.agent7250CheckpointPath);
agent7250Hash = fileSha256(agent7250Path);
if agent7250Hash ~= string(stage7j.agent7250CheckpointSha256)
    error("run_no_glove_stage7k_intent_provenance_audit:Agent7250Hash", ...
        "The canonical Agent7250 file changed.");
end
manifest = struct("stage", "7K", "schemaVersion", 1, ...
    "result", "PASS", "scientificResult", analysis.classification, ...
    "replayGatePassed", analysis.replayGatePassed, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7k_intent_provenance_audit", ...
    "preregistrationCommit", ...
        "0467d7e2093a253f10d33b051da0c1bb6cb1e278", ...
    "stage7jRunRoot", options.stage7jRunRoot, ...
    "stage7iRunRoot", string(stage7j.stage7iRunRoot), ...
    "stage7jManifestSha256", sourceHashesBefore.sha256(1), ...
    "stage7jResultsSha256", sourceHashesBefore.sha256(2), ...
    "stage7iManifestSha256", sourceHashesBefore.sha256(4), ...
    "stage7iResultsSha256", sourceHashesBefore.sha256(5), ...
    "inputEpisodeCount", height(episodeHashesBefore), ...
    "inputWindowCount", height(frozen.windows), ...
    "inputsPreserved", true, "parentAudit", table2struct(parentAudit), ...
    "thresholds", analysis.thresholds, ...
    "gateChecks", table2struct(analysis.gateChecks), ...
    "sourceDecision", table2struct(analysis.sourceDecision), ...
    "directPerStepLabelAbsentInFrozenInputs", ...
        analysis.directPerStepLabelAbsentInFrozenInputs, ...
    "offlineReconstructionAvailable", true, ...
    "loggingInstrumentationImplemented", true, ...
    "loggingContractAudit", table2struct(loggingContractAudit), ...
    "loggingChanged", true, "loggingAffectsObservation", false, ...
    "loggingAffectsReward", false, "loggingAffectsReference", false, ...
    "loggingAffectsAction", false, "loggingAffectsSafety", false, ...
    "latchContractReauthorized", false, ...
    "intentHoldMarkov61Implemented", false, ...
    "behavioralInterventionExecuted", false, ...
    "rootCauseIdentified", false, ...
    "referenceSource", "emgIntent", ...
    "observationVariant", "intentMarkov60", ...
    "actionInterfaceVariant", "baselineQuantized", ...
    "policyChanged", false, "stateChanged", false, ...
    "rewardChanged", false, "referenceChanged", false, ...
    "quantizationChanged", false, "simulatorChanged", false, ...
    "safetyLayerChanged", false, "runTraining", false, ...
    "newTraining", false, "agentLoaded", false, ...
    "scientificReplaySimulatorInvoked", false, ...
    "simulationUsedByLoggingTests", true, ...
    "simMotors", true, "rewardFunctionInvokedForAnalysis", false, ...
    "dtwCalculated", false, "hardwareUsed", false, ...
    "pilotAuthorized", false, "longCampaignAuthorized", false, ...
    "agent7250Loaded", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", agent7250Hash, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);
save(fullfile(runRoot, "stage7k_results.mat"), "manifest", ...
    "analysis", "episodeHashesBefore", "sourceHashesBefore", ...
    "parentAudit", "loggingContractAudit", "stage7j", "stage7i", ...
    "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "replayGatePassed", analysis.replayGatePassed, ...
    "outputPath", runRoot, "manifest", manifest, ...
    "analysis", analysis);
fprintf("ETAPA 7K INTENT PROVENANCE AUDIT PASS\n");
fprintf("Scientific result: %s\n", analysis.classification);
fprintf("Replay gate passed: %d\n", analysis.replayGatePassed);
fprintf("Output: %s\n", runRoot);
disp(analysis.gateChecks);
disp(analysis.sourceDecision);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7k_intent_provenance_audit:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct("resultsRoot", "", "stage7jRunRoot", ...
    "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7j_artifacts\" + ...
    "stage7j_final\2026-08-28_21-02-19-544");
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7k_intent_provenance_audit:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.stage7jRunRoot = string(options.stage7jRunRoot);
if ~isfile(fullfile(options.stage7jRunRoot, "manifest.json"))
    error("run_no_glove_stage7k_intent_provenance_audit:MissingStage7j", ...
        "ETAPA 7J manifest not found under %s.", options.stage7jRunRoot);
end
end

function [stage7j, stage7i, frozen, profiles, hashes, audit] = ...
        loadAndValidateInputs(stage7jRoot)
stage7j = jsondecode(fileread(fullfile(stage7jRoot, "manifest.json")));
if string(stage7j.stage) ~= "7J" || string(stage7j.result) ~= "PASS" || ...
        string(stage7j.scientificResult) ~= ...
        "latchedHoldNotSeparableFromFarCorrection" || ...
        logical(stage7j.contractSupported) || ...
        logical(stage7j.behavioralInterventionExecuted) || ...
        logical(stage7j.runTraining) || logical(stage7j.hardwareUsed) || ...
        logical(stage7j.agentLoaded) || logical(stage7j.dtwCalculated)
    error("run_no_glove_stage7k_intent_provenance_audit:Stage7jContract", ...
        "Input manifest is not the frozen ETAPA 7J result.");
end
stage7iRoot = string(stage7j.stage7iRunRoot);
stage7i = jsondecode(fileread(fullfile(stage7iRoot, "manifest.json")));
if string(stage7i.stage) ~= "7I" || string(stage7i.result) ~= "PASS" || ...
        double(stage7i.episodeInputCount) ~= 548 || ...
        double(stage7i.windowCount) ~= 31220 || ...
        ~logical(stage7i.episodeInputsPreserved) || ...
        logical(stage7i.hardwareUsed) || logical(stage7i.runTraining)
    error("run_no_glove_stage7k_intent_provenance_audit:Stage7iContract", ...
        "7J does not point to the frozen ETAPA 7I corpus.");
end
stage7jData = load(fullfile(stage7jRoot, "stage7j_results.mat"), ...
    "analysis");
stage7iData = load(fullfile(stage7iRoot, "stage7i_results.mat"), ...
    "windows", "episodeAudit", "inputHashesBefore");
if height(stage7jData.analysis.windowAudit) ~= 31220 || ...
        height(stage7iData.windows) ~= 31220 || ...
        height(stage7iData.episodeAudit) ~= 548 || ...
        height(stage7iData.inputHashesBefore) ~= 548
    error("run_no_glove_stage7k_intent_provenance_audit:ParentResults", ...
        "Frozen parent MAT files have unexpected dimensions.");
end
controlData = load(fullfile(string(stage7i.controlRunRoot), ...
    "seed_11", "effective_training_profile.mat"), "profile");
candidateData = load(fullfile(string(stage7i.candidateRunRoot), ...
    "seed_11", "effective_training_profile.mat"), "profile");
profiles = struct("control", controlData.profile, ...
    "candidate", candidateData.profile);
if string(profiles.control.intentCalibration.contentSha256) ~= ...
        string(profiles.candidate.intentCalibration.contentSha256) || ...
        ~profiles.control.simMotors || ~profiles.candidate.simMotors || ...
        string(profiles.control.observationVariant) ~= "intentMarkov60" || ...
        string(profiles.candidate.observationVariant) ~= "intentMarkov60"
    error("run_no_glove_stage7k_intent_provenance_audit:ProfileContract", ...
        "Frozen profiles do not share the causal intent calibration.");
end
frozen = struct("windows", stage7iData.windows, ...
    "episodeAudit", stage7iData.episodeAudit, ...
    "inputHashesBefore", stage7iData.inputHashesBefore, ...
    "latchAudit", stage7jData.analysis.windowAudit);
hashes = hashFrozenSources(stage7jRoot, stage7iRoot, stage7i);
audit = table(string(stage7j.scientificResult), ...
    logical(stage7j.contractSupported), string(stage7i.scientificResult), ...
    double(stage7i.episodeInputCount), double(stage7i.windowCount), ...
    string(profiles.control.intentCalibration.contentSha256), ...
    logical(stage7j.inputsPreserved), logical(stage7i.episodeInputsPreserved), ...
    'VariableNames', ["stage7jScientificResult", ...
    "stage7jContractSupported", "stage7iScientificResult", ...
    "episodeCount", "windowCount", "calibrationSha256", ...
    "stage7jInputsPreserved", "stage7iInputsPreserved"]);
end

function hashes = hashFrozenSources(stage7jRoot, stage7iRoot, stage7i)
paths = [fullfile(stage7jRoot, "manifest.json"); ...
    fullfile(stage7jRoot, "stage7j_results.mat"); ...
    fullfile(stage7jRoot, "window_latch_audit.csv"); ...
    fullfile(stage7iRoot, "manifest.json"); ...
    fullfile(stage7iRoot, "stage7i_results.mat"); ...
    fullfile(stage7iRoot, "episode_input_hashes.csv"); ...
    fullfile(string(stage7i.controlRunRoot), "seed_11", ...
        "effective_training_profile.mat"); ...
    fullfile(string(stage7i.candidateRunRoot), "seed_11", ...
        "effective_training_profile.mat")];
labels = ["stage7jManifest"; "stage7jResults"; ...
    "stage7jWindowLatchAudit"; "stage7iManifest"; ...
    "stage7iResults"; "stage7iEpisodeInventory"; ...
    "controlProfile"; "candidateProfile"];
sha256 = strings(numel(paths), 1);
bytes = zeros(numel(paths), 1);
for idx = 1:numel(paths)
    info = dir(paths(idx));
    if isempty(info)
        error("run_no_glove_stage7k_intent_provenance_audit:SourceMissing", ...
            "Frozen source %s is missing.", paths(idx));
    end
    sha256(idx) = fileSha256(paths(idx));
    bytes(idx) = info.bytes;
end
hashes = table(labels, paths, sha256, bytes);
end

function observed = rehashEpisodeInputs(expected)
observed = expected;
for idx = 1:height(expected)
    path = string(expected.path(idx));
    if ~isfile(path)
        error("run_no_glove_stage7k_intent_provenance_audit:EpisodeMissing", ...
            "Frozen episode %s is missing.", path);
    end
    info = dir(path);
    observed.bytes(idx) = info.bytes;
    observed.sha256(idx) = fileSha256(path);
end
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf("cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7k_intent_provenance_audit(struct(" + ...
    "'resultsRoot','%s','stage7jRunRoot','%s'))", ...
    escapeQuote(matlabRoot), escapeQuote(string(fileparts(runRoot))), ...
    escapeQuote(options.stage7jRunRoot));
end

function value = buildOfflineReport(manifest)
d = manifest.sourceDecision;
lines = ["# ETAPA 7K - intent-zero provenance audit"; ""; ...
    "- Engineering result: PASS."; ...
    "- Scientific result: " + manifest.scientificResult + "."; ...
    "- Replay gate passed: " + string(manifest.replayGatePassed) + "."; ...
    sprintf("- Stopped windows: %d.", d.stoppedWindowCount); ...
    sprintf("- Stopped label coverage: %.9f.", ...
        d.stoppedLabelCoverage); ...
    sprintf("- Unresolved active-zero windows: %d.", ...
        d.unresolvedActiveZeroCount); ...
    sprintf("- Latched-far windows from far-started segments: %d.", ...
        d.latchedFarFromFarStartedSegmentCount); ...
    "- Direct frozen label: absent; exact offline reconstruction: available."; ...
    "- Future logging added without state/reward/reference/action changes."; ...
    "- Training/DTW/hardware: no/no/no; latch 7J remains unauthorized."];
value = strjoin(lines, newline);
end

function hashes = inventoryArtifacts(runRoot)
names = ["test_results.mat", "episode_input_hashes.csv", ...
    "source_hashes.csv", "parent_audit.csv", ...
    "logging_contract_audit.csv", "decision_provenance.csv", ...
    "transition_replay.csv", "episode_replay_audit.csv", ...
    "provenance_summary.csv", "segment_provenance.csv", ...
    "gate_checks.csv", "source_decision.csv", ...
    "stage7k_results.mat", "offline_report.md", ...
    "reproducible_command.txt"];
hashes = repmat(struct("path", "", "sha256", ""), numel(names), 1);
for idx = 1:numel(names)
    hashes(idx).path = names(idx);
    hashes(idx).sha256 = fileSha256(fullfile(runRoot, names(idx)));
end
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
commit = "unknown";
if status == 0
    commit = string(strtrim(output));
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[trackedStatus, trackedOutput] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = trackedStatus ~= 0 || ...
    strlength(strtrim(string(trackedOutput))) > 0;
end

function hash = fileSha256(path)
fid = fopen(path, "r");
if fid < 0
    error("run_no_glove_stage7k_intent_provenance_audit:HashFailed", ...
        "Could not open %s for hashing.", path);
end
cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid, Inf, "*uint8");
digest = java.security.MessageDigest.getInstance("SHA-256");
digest.update(bytes);
digestBytes = typecast(digest.digest(), "uint8");
hash = upper(string(reshape(dec2hex(digestBytes, 2)', 1, [])));
end

function value = escapeQuote(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7k_intent_provenance_audit:WriteFailed", ...
        "Could not open %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
