function report = run_no_glove_stage7n_state_ablation(options)
%run_no_glove_stage7n_state_ablation runs the bounded 60/62 TD3 smoke.
%
% The launcher creates two fresh feedforward policies with seed 11, trains
% at most 200 episodes per variant and evaluates every checkpoint. It never
% starts a pilot, campaign, DTW analysis or hardware route.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));

parentAudit = validateStage7mParent(options.stage7mRunRoot);
if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7n_state_ablation");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7n_state_ablation:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testFiles = [ ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage6Training.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testIntentDeclaredRestHoldMarkov62.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7nStateAblation.m")];
testResults = runtests(testFiles);
save(fullfile(runRoot, "preflight_test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7n_state_ablation:TestsFailed", ...
        "ETAPA 7N tests failed; training is forbidden. See %s.", runRoot);
end

fixed = struct( ...
    "phase", "smoke", "calibrationSeed", 11, ...
    "evaluationSeed", 7601, ...
    "evaluationSimulations", 1, "restSimulations", 1, ...
    "positionSafetyAblation", true, ...
    "intentRewardActionWeight", 0.05, ...
    "intentHoldRewardEnabled", false, ...
    "intentHoldActionWeight", 0.00, ...
    "intentHoldVelocityTolerance", 1e-12, ...
    "intentHoldPositionMseTolerance", 1e-4);

controlOptions = fixed;
controlOptions.observationVariant = "intentMarkov60";
controlOptions.resultsRoot = fullfile(runRoot, "control60_training");
candidateOptions = fixed;
candidateOptions.observationVariant = ...
    "intentDeclaredRestHoldMarkov62";
candidateOptions.resultsRoot = fullfile(runRoot, "candidate62_training");

controlReport = obtainChildRun(options.completedControlRunRoot, ...
    controlOptions);
assertBoundedFreshSmoke(controlReport, "intentMarkov60", 60);
candidateReport = obtainChildRun(options.completedCandidateRunRoot, ...
    candidateOptions);
assertBoundedFreshSmoke(candidateReport, ...
    "intentDeclaredRestHoldMarkov62", 62);

[profileAudit, profiles] = auditProfiles(controlReport, candidateReport);
datasetAudit = auditDatasets(controlReport.manifest, ...
    candidateReport.manifest);
[initializationAudit, initializationArrays] = ...
    auditInitializations(profiles, runRoot);

[controlRows, controlMotors] = evaluateAllCheckpoints( ...
    "control60", controlReport, profiles.control, runRoot, ...
    options.acceptanceSimulations, options.restSimulations, ...
    options.evaluationSeed);
[candidateRows, candidateMotors] = evaluateAllCheckpoints( ...
    "candidate62", candidateReport, profiles.candidate, runRoot, ...
    options.acceptanceSimulations, options.restSimulations, ...
    options.evaluationSeed);
checkpointSummary = [controlRows; candidateRows];
motorSummary = [controlMotors; candidateMotors];

runAudit = buildRunAudit(controlReport, candidateReport, ...
    profileAudit, datasetAudit, initializationAudit, checkpointSummary);
analysis = analyzeNoGloveStage7nStateAblation( ...
    checkpointSummary, runAudit);

writetable(checkpointSummary, ...
    fullfile(runRoot, "checkpoint_summary.csv"));
writetable(motorSummary, fullfile(runRoot, "motor_summary.csv"));
writetable(analysis.perCheckpointComparison, ...
    fullfile(runRoot, "checkpoint_comparison.csv"));
writetable(analysis.gateChecks, fullfile(runRoot, "gate_checks.csv"));
writetable(struct2table(profileAudit), ...
    fullfile(runRoot, "profile_audit.csv"));
writetable(struct2table(datasetAudit), ...
    fullfile(runRoot, "dataset_audit.csv"));
writetable(initializationArrays, ...
    fullfile(runRoot, "initialization_arrays.csv"));
writetable(struct2table(initializationAudit), ...
    fullfile(runRoot, "initialization_audit.csv"));
writetable(struct2table(runAudit), ...
    fullfile(runRoot, "run_audit.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", "7N", "schemaVersion", 1, "result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "scientificGatePassed", analysis.gatePassed, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7n_state_ablation", ...
    "preregistrationCommit", ...
        "b103a4578d3c200a586d6368b22a5fafc3c616eb", ...
    "parentStage7m", parentAudit, ...
    "singleChangedFactor", "observationVariant", ...
    "controlObservationVariant", "intentMarkov60", ...
    "controlStateLength", 60, ...
    "candidateObservationVariant", ...
        "intentDeclaredRestHoldMarkov62", ...
    "candidateStateLength", 62, ...
    "declaredRestIndex", 61, "holdLatchIndex", 62, ...
    "holdPositionMseTolerance", 1e-4, ...
    "episodeBudgetPerVariant", 200, "seed", 11, ...
    "checkpointCadence", 50, ...
    "checkpointEpisodes", [50, 100, 150, 200], ...
    "evaluationSeed", options.evaluationSeed, ...
    "acceptanceSimulationsPerCheckpoint", ...
        options.acceptanceSimulations, ...
    "restSimulationsPerCheckpoint", options.restSimulations, ...
    "primaryCheckpointEpisode", 200, ...
    "controlRunRoot", controlReport.outputPath, ...
    "candidateRunRoot", candidateReport.outputPath, ...
    "controlRunManifestSha256", fileSha256(fullfile( ...
        controlReport.outputPath, "manifest.json")), ...
    "candidateRunManifestSha256", fileSha256(fullfile( ...
        candidateReport.outputPath, "manifest.json")), ...
    "profileAudit", profileAudit, "datasetAudit", datasetAudit, ...
    "initializationAudit", initializationAudit, ...
    "runAudit", runAudit, "thresholds", analysis.thresholds, ...
    "gateChecks", analysis.checks, ...
    "primaryComparison", analysis.primaryComparison, ...
    "newTraining", true, "checkpointLoadedForTraining", false, ...
    "agent7250Loaded", false, "agent7250UsedAsStartingPoint", false, ...
    "agent200Loaded", false, "agent200UsedAsStartingPoint", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "referenceSource", "emgIntent", ...
    "rewardType", "trackingIntentActionRateReward", ...
    "intentRewardPositionWeight", 1.00, ...
    "intentRewardVelocityWeight", 0.00, ...
    "intentRewardActionWeight", 0.05, ...
    "intentRewardDeltaActionWeight", 0.05, ...
    "intentRewardSaturationWeight", 0.02, ...
    "intentRewardSoftActionLimit", 0.90, ...
    "actionInterfaceVariant", "baselineQuantized", ...
    "actorCriticArchitecture", "feedforward", ...
    "simulationPositionSafetyEnabled", true, ...
    "simMotors", true, "simulatorUsed", true, ...
    "hardwareUsed", false, "dtwCalculated", false, ...
    "pilotAuthorized", false, "longCampaignAuthorized", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);

save(fullfile(runRoot, "stage7n_results.mat"), ...
    "manifest", "analysis", "checkpointSummary", "motorSummary", ...
    "profileAudit", "datasetAudit", "initializationAudit", ...
    "initializationArrays", "runAudit", "parentAudit", "options", ...
    "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest, checkpointSummary, analysis));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "scientificGatePassed", analysis.gatePassed, ...
    "outputPath", runRoot, "manifest", manifest, ...
    "analysis", analysis, "checkpointSummary", checkpointSummary, ...
    "motorSummary", motorSummary, "runAudit", runAudit);
fprintf("ETAPA 7N STATE ABLATION PASS\n");
fprintf("Scientific result: %s\n", analysis.classification);
fprintf("Scientific gate passed: %d\n", analysis.gatePassed);
fprintf("Output: %s\n", runRoot);
disp(checkpointSummary);
disp(analysis.gateChecks);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7n_state_ablation:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "resultsRoot", "", ...
    "stage7mRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7m_artifacts\stage7m_final\2026-08-29_00-58-24-394", ...
    "completedControlRunRoot", "", ...
    "completedCandidateRunRoot", "", ...
    "evaluationSeed", 7601, ...
    "acceptanceSimulations", 50, ...
    "restSimulations", 24);
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7n_state_ablation:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
stringFields = ["resultsRoot", "stage7mRunRoot", ...
    "completedControlRunRoot", "completedCandidateRunRoot"];
for idx = 1:numel(stringFields)
    name = stringFields(idx);
    options.(name) = string(options.(name));
    if ~isscalar(options.(name)) || ismissing(options.(name))
        error("run_no_glove_stage7n_state_ablation:InvalidStringOption", ...
            "%s must be a scalar string.", name);
    end
end
numericFields = ["evaluationSeed", "acceptanceSimulations", ...
    "restSimulations"];
for idx = 1:numel(numericFields)
    name = numericFields(idx);
    value = options.(name);
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
            value <= 0 || fix(value) ~= value
        error("run_no_glove_stage7n_state_ablation:InvalidCount", ...
            "%s must be a positive integer.", name);
    end
end
if options.evaluationSeed ~= 7601 || ...
        options.acceptanceSimulations ~= 50 || ...
        options.restSimulations ~= 24
    error("run_no_glove_stage7n_state_ablation:ProtocolChanged", ...
        "ETAPA 7N requires seed 7601 and 50/24 evaluations.");
end
end

function audit = validateStage7mParent(runRoot)
manifestPath = fullfile(runRoot, "manifest.json");
if ~isfile(manifestPath)
    error("run_no_glove_stage7n_state_ablation:MissingStage7m", ...
        "ETAPA 7M manifest not found at %s.", manifestPath);
end
expectedHash = ...
    "CDB80438A5BE67E90F2BD58699C38C989815265B26B7F95CC28EA1ED674C7812";
actualHash = fileSha256(manifestPath);
manifest = jsondecode(fileread(manifestPath));
valid = actualHash == expectedHash && string(manifest.stage) == "7M" && ...
    string(manifest.result) == "PASS" && ...
    string(manifest.scientificResult) == ...
        "intentDeclaredRestHoldMarkov62Implemented" && ...
    logical(manifest.observationVariantImplemented) && ...
    ~logical(manifest.hardwareUsed) && ~logical(manifest.dtwCalculated);
if ~valid
    error("run_no_glove_stage7n_state_ablation:Stage7mChanged", ...
        "ETAPA 7M does not match the pre-registered parent.");
end
audit = struct("runRoot", runRoot, "manifestPath", manifestPath, ...
    "manifestSha256", actualHash, ...
    "implementationCommit", string(manifest.gitCommit), ...
    "scientificResult", string(manifest.scientificResult), ...
    "validated", true);
end

function report = obtainChildRun(completedRunRoot, trainingOptions)
if strlength(completedRunRoot) == 0
    report = run_no_glove_stage6_training(trainingOptions);
else
    report = loadCompletedChild(completedRunRoot);
end
end

function report = loadCompletedChild(runRoot)
required = ["manifest.json", "stage6_results.mat", ...
    fullfile("seed_11", "effective_training_profile.mat")];
for idx = 1:numel(required)
    if ~isfile(fullfile(runRoot, required(idx)))
        error("run_no_glove_stage7n_state_ablation:InvalidResume", ...
            "Completed child run lacks %s under %s.", ...
            required(idx), runRoot);
    end
end
data = load(fullfile(runRoot, "stage6_results.mat"), ...
    "manifest", "seedResults", "seedTable", "checkpointTable");
report = struct("result", string(data.manifest.result), ...
    "phase", string(data.manifest.phase), ...
    "phaseGatePassed", logical(data.manifest.phaseGatePassed), ...
    "outputPath", string(runRoot), "manifest", data.manifest, ...
    "seedTable", data.seedTable, ...
    "checkpointTable", data.checkpointTable, ...
    "seedResults", {data.seedResults});
end

function assertBoundedFreshSmoke(report, expectedVariant, expectedLength)
m = report.manifest;
checkpointEpisodes = sort(double(report.checkpointTable.episode));
valid = string(m.phase) == "smoke" && m.protocol.episodes == 200 && ...
    isequal(double(m.seeds), 11) && m.newTraining && ...
    strlength(string(m.checkpointLoadedForTraining)) == 0 && ...
    ~m.agent7250Loaded && ~m.agent7250UsedAsStartingPoint && ...
    m.simMotors && ~m.hardwareUsed && m.positionSafetyAblation && ...
    string(m.referenceSource) == "emgIntent" && ...
    string(m.observationVariant) == expectedVariant && ...
    double(m.stateLength) == expectedLength && ...
    string(m.rewardType) == "trackingIntentActionRateReward" && ...
    string(m.actionInterfaceVariant) == "baselineQuantized" && ...
    m.intentRewardActionWeight == 0.05 && ...
    ~m.intentHoldRewardEnabled && height(report.checkpointTable) == 4 && ...
    isequal(checkpointEpisodes(:), [50; 100; 150; 200]);
if ~valid
    error("run_no_glove_stage7n_state_ablation:ChildInvariant", ...
        "A child run violates the pre-registered fresh smoke contract.");
end
end

function [audit, profiles] = auditProfiles(controlReport, candidateReport)
controlPath = fullfile(controlReport.outputPath, ...
    "seed_11", "effective_training_profile.mat");
candidatePath = fullfile(candidateReport.outputPath, ...
    "seed_11", "effective_training_profile.mat");
controlData = load(controlPath, "profile");
candidateData = load(candidatePath, "profile");
profiles = struct("control", controlData.profile, ...
    "candidate", candidateData.profile);
normalizedControl = normalizeProfile(profiles.control);
normalizedCandidate = normalizeProfile(profiles.candidate);
audit = struct( ...
    "controlObservationVariant", ...
        string(profiles.control.observationVariant), ...
    "candidateObservationVariant", ...
        string(profiles.candidate.observationVariant), ...
    "equalExceptObservationAndOutputPaths", ...
        isequaln(normalizedControl, normalizedCandidate), ...
    "sameRandomSeed", ...
        profiles.control.randomSeed == profiles.candidate.randomSeed, ...
    "sameEpisodeBudget", profiles.control.trainingMaxEpisodes == ...
        profiles.candidate.trainingMaxEpisodes, ...
    "sameCheckpointCadence", ...
        profiles.control.trainingSaveAgentEvery == ...
        profiles.candidate.trainingSaveAgentEvery, ...
    "sameReward", rewardSettingsEqual( ...
        profiles.control, profiles.candidate), ...
    "sameSafety", isequaln(profiles.control.simulationPositionSafety, ...
        profiles.candidate.simulationPositionSafety), ...
    "profileMatched", false);
audit.profileMatched = audit.equalExceptObservationAndOutputPaths && ...
    audit.sameRandomSeed && audit.sameEpisodeBudget && ...
    audit.sameCheckpointCadence && audit.sameReward && audit.sameSafety;
if ~audit.profileMatched
    error("run_no_glove_stage7n_state_ablation:ProfileMismatch", ...
        "Profiles differ beyond observation variant and output paths.");
end
end

function profile = normalizeProfile(profile)
profile.observationVariant = "<ablated-observation>";
profile.dataset_folder = "<matched-dataset-folder>";
profile = rmfield(profile, "agents_directory");
end

function equal = rewardSettingsEqual(a, b)
fields = ["rewardType", "intentRewardPositionWeight", ...
    "intentRewardVelocityWeight", "intentRewardActionWeight", ...
    "intentRewardDeltaActionWeight", ...
    "intentRewardSaturationWeight", "intentRewardSoftActionLimit"];
equal = all(arrayfun(@(name) isequaln(a.(name), b.(name)), fields));
end

function audit = auditDatasets(control, candidate)
names = ["trainingDatasetPath", "evaluationDatasetPath", ...
    "restDatasetPath"];
equal = false(1, numel(names));
for idx = 1:numel(names)
    a = load(string(control.(names(idx))), "emgs", "metadata");
    b = load(string(candidate.(names(idx))), "emgs", "metadata");
    equal(idx) = isequaln(a.emgs, b.emgs) && ...
        isequaln(a.metadata, b.metadata);
end
audit = struct( ...
    "trainingDatasetContentEqual", equal(1), ...
    "evaluationDatasetContentEqual", equal(2), ...
    "restDatasetContentEqual", equal(3), ...
    "calibrationContentSha256Equal", ...
        string(control.calibrationContentSha256) == ...
        string(candidate.calibrationContentSha256), ...
    "allDatasetContentsEqual", all(equal));
if ~audit.allDatasetContentsEqual || ...
        ~audit.calibrationContentSha256Equal
    error("run_no_glove_stage7n_state_ablation:DatasetMismatch", ...
        "The child runs did not use identical corpus contents.");
end
end

function [audit, arrays] = auditInitializations(profiles, runRoot)
[controlFirst, controlRows] = initializeActor( ...
    profiles.control, "control60", ...
    fullfile(runRoot, "control60_initial_actor.bin"));
[controlSecond, ~] = initializeActor( ...
    profiles.control, "control60_replay", ...
    fullfile(runRoot, "control60_initial_actor_replay.bin"));
[candidateFirst, candidateRows] = initializeActor( ...
    profiles.candidate, "candidate62", ...
    fullfile(runRoot, "candidate62_initial_actor.bin"));
[candidateSecond, ~] = initializeActor( ...
    profiles.candidate, "candidate62_replay", ...
    fullfile(runRoot, "candidate62_initial_actor_replay.bin"));
controlReproducible = parametersEqual(controlFirst, controlSecond);
candidateReproducible = parametersEqual(candidateFirst, candidateSecond);
arrays = [controlRows; candidateRows];
audit = struct( ...
    "randomSeed", 11, ...
    "controlActorLearnableArrayCount", numel(controlFirst), ...
    "candidateActorLearnableArrayCount", numel(candidateFirst), ...
    "controlActorParameterCount", countParameters(controlFirst), ...
    "candidateActorParameterCount", countParameters(candidateFirst), ...
    "controlActorSha256", fileSha256(fullfile( ...
        runRoot, "control60_initial_actor.bin")), ...
    "candidateActorSha256", fileSha256(fullfile( ...
        runRoot, "candidate62_initial_actor.bin")), ...
    "controlReplaySha256", fileSha256(fullfile( ...
        runRoot, "control60_initial_actor_replay.bin")), ...
    "candidateReplaySha256", fileSha256(fullfile( ...
        runRoot, "candidate62_initial_actor_replay.bin")), ...
    "controlInitializationReproducible", controlReproducible, ...
    "candidateInitializationReproducible", candidateReproducible, ...
    "initializationReproducible", ...
        controlReproducible && candidateReproducible, ...
    "tensorIdentityRequiredAcrossVariants", false);
if ~audit.initializationReproducible || ...
        audit.controlActorSha256 ~= audit.controlReplaySha256 || ...
        audit.candidateActorSha256 ~= audit.candidateReplaySha256
    error("run_no_glove_stage7n_state_ablation:InitializationMismatch", ...
        "Fresh actor initialization is not reproducible by seed.");
end
end

function [parameters, rows] = initializeActor(profile, label, binaryPath)
clearConfigurablesOverride();
setConfigurablesOverride(profile);
rng(double(profile.randomSeed), "twister");
agent = agentNoGloveIntentTd3( ...
    Env.defineObservationInfo(), Env.defineActionInfo());
parameters = getLearnableParameters(getActor(agent));
clearConfigurablesOverride();
fid = fopen(binaryPath, "wb");
if fid < 0
    error("run_no_glove_stage7n_state_ablation:BinaryWrite", ...
        "Could not create %s.", binaryPath);
end
cleanup = onCleanup(@() fclose(fid));
rowParts = cell(numel(parameters), 1);
for idx = 1:numel(parameters)
    value = numericParameter(parameters{idx});
    dimensions = size(value);
    fwrite(fid, uint64(numel(dimensions)), "uint64");
    fwrite(fid, uint64(dimensions), "uint64");
    fwrite(fid, value(:), "double");
    rowParts{idx} = table(string(label), idx, ...
        string(mat2str(dimensions)), numel(value), ...
        'VariableNames', ["variant", "arrayIndex", ...
        "dimensions", "parameterCount"]);
end
rows = vertcat(rowParts{:});
end

function value = numericParameter(value)
if isa(value, "dlarray")
    value = extractdata(value);
end
if ~isnumeric(value)
    error("run_no_glove_stage7n_state_ablation:LearnableType", ...
        "Actor learnables must be numeric or dlarray.");
end
value = double(value);
end

function equal = parametersEqual(a, b)
if numel(a) ~= numel(b)
    equal = false;
    return;
end
equal = true;
for idx = 1:numel(a)
    if ~isequaln(numericParameter(a{idx}), numericParameter(b{idx}))
        equal = false;
        return;
    end
end
end

function count = countParameters(parameters)
count = 0;
for idx = 1:numel(parameters)
    count = count + numel(numericParameter(parameters{idx}));
end
end

function [summaryTable, motorTable] = evaluateAllCheckpoints( ...
        label, childReport, profile, runRoot, acceptanceCount, ...
        restCount, evaluationSeed)
inventory = sortrows(childReport.checkpointTable, "episode");
rowParts = cell(height(inventory), 1);
motorParts = cell(height(inventory), 1);
for idx = 1:height(inventory)
    episode = double(inventory.episode(idx));
    checkpointPath = string(inventory.checkpointPath(idx));
    base = fullfile(runRoot, "checkpoint_evaluations", label, ...
        sprintf("episode_%03d", episode));
    acceptanceDir = runEvaluation(profile, checkpointPath, ...
        string(childReport.manifest.evaluationDatasetPath), ...
        fullfile(base, "acceptance"), evaluationSeed, acceptanceCount);
    restDir = runEvaluation(profile, checkpointPath, ...
        string(childReport.manifest.restDatasetPath), ...
        fullfile(base, "steady_rest"), evaluationSeed, restCount);
    [rowParts{idx}, motorParts{idx}] = summarizeCheckpoint( ...
        label, episode, checkpointPath, ...
        string(inventory.checkpointSha256(idx)), ...
        acceptanceDir, restDir, profile, ...
        double(childReport.manifest.restFalseActivationFraction));
end
summaryTable = vertcat(rowParts{:});
motorTable = vertcat(motorParts{:});
end

function evaluationDir = runEvaluation(profile, checkpointPath, ...
        datasetPath, evaluationBase, evaluationSeed, simulationCount)
mkdir(evaluationBase);
[datasetFolder, datasetStem] = fileparts(datasetPath);
evaluationProfile = profile;
evaluationProfile.run_training = false;
evaluationProfile.newTraining = false;
evaluationProfile.agentFile = checkpointPath;
evaluationProfile.agent_id = "td3_no_glove_intent";
evaluationProfile.randomSeed = evaluationSeed;
evaluationProfile.dataset = {char(string(datasetStem))};
evaluationProfile.dataset_folder = string(datasetFolder);
evaluationProfile.flagSaveTraining = true;
evaluationProfile.episode_save_freq = 1;
evaluationProfile.plotEpisodeOnTest = false;
evaluationProfile.simOpts = rlSimulationOptions( ...
    "MaxSteps", evaluationProfile.maxNumberStepsInEpisodes, ...
    "NumSimulations", simulationCount, "StopOnError", "on", ...
    "UseParallel", false);
evaluationProfile.agents_directory = @(agent_id, variant) fullfile( ...
    evaluationBase, string(datetime("now", "Format", "yy-MM-dd HH m s")));
setConfigurablesOverride(evaluationProfile);
evaluationCleanup = onCleanup(@() clearConfigurablesOverride());
trainInterface("td3_no_glove_intent", "", "");
clear evaluationCleanup
evaluationDir = findNewestSubdir(evaluationBase);
end

function [row, motors] = summarizeCheckpoint(label, episode, ...
        checkpointPath, checkpointSha256, acceptanceDir, restDir, ...
        profile, restFalseActivationFraction)
variant = string(profile.observationVariant);
positionMin = profile.intentCalibration.limits.positionMin;
positionMax = profile.intentCalibration.limits.positionMax;
acceptance = analyzeNoGloveStage6Evaluation(acceptanceDir, ...
    "positionMin", positionMin, "positionMax", positionMax, ...
    "observationVariant", variant);
rest = analyzeNoGloveStage6Evaluation(restDir, ...
    "positionMin", positionMin, "positionMax", positionMax, ...
    "observationVariant", variant);
acceptanceState = summarizeNoGloveStage7nEpisodes( ...
    acceptanceDir, variant);
restState = summarizeNoGloveStage7nEpisodes(restDir, variant);

row = struct2table(struct( ...
    "variant", string(label), "observationVariant", variant, ...
    "stateLength", double(acceptance.stateLength), ...
    "episode", episode, "checkpointPath", checkpointPath, ...
    "checkpointSha256", checkpointSha256, ...
    "acceptanceDirectory", acceptanceDir, "restDirectory", restDir, ...
    "acceptanceEpisodeCount", acceptance.episodeCount, ...
    "restEpisodeCount", rest.episodeCount, ...
    "acceptanceAllFinite", acceptance.allFinite && ...
        acceptanceState.allFinite, ...
    "restAllFinite", rest.allFinite && restState.allFinite, ...
    "acceptancePositionViolations", ...
        acceptance.positionViolationEpisodeCount, ...
    "restPositionViolations", rest.positionViolationEpisodeCount, ...
    "trackingMse", acceptance.trackingMse, ...
    "trackingMae", acceptance.trackingMae, ...
    "velocityMse", acceptance.velocityMse, ...
    "actionL2", acceptance.actionL2, ...
    "deltaActionL2", acceptance.deltaActionL2, ...
    "saturationFraction", acceptance.saturationFraction, ...
    "restCommandComponentFraction", ...
        restState.commandComponentFraction, ...
    "restWindowAnyCommandFraction", ...
        restState.windowAnyCommandFraction, ...
    "restMeanAbsPwm", restState.meanAbsPwm, ...
    "restSaturationFraction", restState.saturationFraction, ...
    "restFalseActivationFraction", restFalseActivationFraction, ...
    "motor2FunctionalFlagCount", ...
        acceptance.motor2FunctionalFlagCount, ...
    "otherMotorFunctionalFlagCount", ...
        acceptance.otherMotorFunctionalFlagCount, ...
    "acceptanceSafetyInterventions", ...
        acceptance.positionSafetyInterventionCount, ...
    "restSafetyInterventions", rest.positionSafetyInterventionCount, ...
    "declaredRestFractionAcceptance", ...
        acceptanceState.declaredRestFraction, ...
    "holdLatchFractionAcceptance", ...
        acceptanceState.holdLatchFraction, ...
    "declaredRestFractionRest", restState.declaredRestFraction, ...
    "holdLatchFractionRest", restState.holdLatchFraction, ...
    "declaredRestReplayMismatchCount", ...
        acceptanceState.declaredRestReplayMismatchCount + ...
        restState.declaredRestReplayMismatchCount, ...
    "holdLatchReplayMismatchCount", ...
        acceptanceState.holdLatchReplayMismatchCount + ...
        restState.holdLatchReplayMismatchCount, ...
    "farStartedCount", sumFinite([acceptanceState.farStartedCount, ...
        restState.farStartedCount]), ...
    "farStartedLatchCount", sumFinite([ ...
        acceptanceState.farStartedLatchCount, ...
        restState.farStartedLatchCount]), ...
    "prematureHoldLatchCount", sumFinite([ ...
        acceptanceState.prematureHoldLatchCount, ...
        restState.prematureHoldLatchCount]), ...
    "latchActiveWindowAnyCommandFractionAcceptance", ...
        acceptanceState.latchActiveWindowAnyCommandFraction, ...
    "latchInactiveWindowAnyCommandFractionAcceptance", ...
        acceptanceState.latchInactiveWindowAnyCommandFraction, ...
    "latchActiveWindowAnyCommandFractionRest", ...
        restState.latchActiveWindowAnyCommandFraction, ...
    "latchInactiveWindowAnyCommandFractionRest", ...
        restState.latchInactiveWindowAnyCommandFraction));

motors = table(repmat(string(label), 4, 1), repmat(episode, 4, 1), ...
    (1:4)', acceptance.trackingMseByMotor(:), ...
    acceptance.trackingMaeByMotor(:), ...
    acceptance.deltaActionL2ByMotor(:), ...
    acceptance.saturationFractionByMotor(:), ...
    restState.commandComponentFractionByMotor(:), ...
    restState.meanAbsPwmByMotor(:), ...
    restState.saturationFractionByMotor(:), ...
    'VariableNames', ["variant", "episode", "motor", ...
    "trackingMse", "trackingMae", "deltaActionL2", ...
    "saturationFraction", "restCommandComponentFraction", ...
    "restMeanAbsPwm", "restSaturationFraction"]);
end

function value = sumFinite(values)
if all(isnan(values))
    value = NaN;
else
    value = sum(values, "omitnan");
end
end

function audit = buildRunAudit(control, candidate, profileAudit, ...
        datasetAudit, initializationAudit, checkpointSummary)
controlSeed = firstSeedResult(control.seedResults);
candidateSeed = firstSeedResult(candidate.seedResults);
audit = struct( ...
    "trainingEpisodeCountControl", max(control.checkpointTable.episode), ...
    "trainingEpisodeCountCandidate", max(candidate.checkpointTable.episode), ...
    "checkpointCountControl", height(control.checkpointTable), ...
    "checkpointCountCandidate", height(candidate.checkpointTable), ...
    "allCheckpointsEvaluated", height(checkpointSummary) == 8 && ...
        all(checkpointSummary.acceptanceEpisodeCount == 50) && ...
        all(checkpointSummary.restEpisodeCount == 24), ...
    "freshPolicies", control.manifest.newTraining && ...
        candidate.manifest.newTraining && ...
        strlength(string(control.manifest.checkpointLoadedForTraining)) == 0 && ...
        strlength(string(candidate.manifest.checkpointLoadedForTraining)) == 0, ...
    "historicalAgentLoaded", control.manifest.agent7250Loaded || ...
        candidate.manifest.agent7250Loaded, ...
    "hardwareUsed", control.manifest.hardwareUsed || ...
        candidate.manifest.hardwareUsed, ...
    "trainingAllFinite", controlSeed.trainingSafety.allFinite && ...
        candidateSeed.trainingSafety.allFinite, ...
    "trainingPositionViolationCountControl", ...
        controlSeed.trainingSafety.positionViolationEpisodeCount, ...
    "trainingPositionViolationCountCandidate", ...
        candidateSeed.trainingSafety.positionViolationEpisodeCount, ...
    "trainingSafetyInterventionCountControl", ...
        controlSeed.trainingSafety.positionSafetyInterventionCount, ...
    "trainingSafetyInterventionCountCandidate", ...
        candidateSeed.trainingSafety.positionSafetyInterventionCount, ...
    "initializationReproducible", ...
        initializationAudit.initializationReproducible, ...
    "profileMatched", profileAudit.profileMatched, ...
    "datasetContentsMatched", datasetAudit.allDatasetContentsEqual);
end

function result = firstSeedResult(seedResults)
% Direct child execution stores the scalar struct, whereas loading a saved
% child preserves the historical cell wrapper. Normalize both routes.
if iscell(seedResults)
    if numel(seedResults) ~= 1
        error("run_no_glove_stage7n_state_ablation:SeedResultCount", ...
            "ETAPA 7N requires exactly one seed result.");
    end
    result = seedResults{1};
elseif isstruct(seedResults) && isscalar(seedResults)
    result = seedResults;
else
    error("run_no_glove_stage7n_state_ablation:SeedResultType", ...
        "ETAPA 7N received an invalid seed-result container.");
end
end

function newestDir = findNewestSubdir(parentDir)
info = dir(parentDir);
info = info([info.isdir]);
info = info(~ismember({info.name}, {'.', '..'}));
if isempty(info)
    error("run_no_glove_stage7n_state_ablation:MissingOutput", ...
        "No output directory found under %s.", parentDir);
end
[~, idx] = max([info.datenum]);
newestDir = string(fullfile(info(idx).folder, info(idx).name));
end

function hashes = inventoryArtifacts(runRoot)
names = ["checkpoint_summary.csv", "motor_summary.csv", ...
    "checkpoint_comparison.csv", "gate_checks.csv", ...
    "profile_audit.csv", "dataset_audit.csv", ...
    "initialization_arrays.csv", "initialization_audit.csv", ...
    "run_audit.csv", "control60_initial_actor.bin", ...
    "candidate62_initial_actor.bin", "stage7n_results.mat", ...
    "offline_report.md", "reproducible_command.txt"];
hashes = repmat(struct("artifact", "", "sha256", ""), ...
    numel(names), 1);
for idx = 1:numel(names)
    path = fullfile(runRoot, names(idx));
    hashes(idx) = struct("artifact", names(idx), ...
        "sha256", fileSha256(path));
end
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7n_state_ablation(struct(" + ...
    "'resultsRoot','%s','stage7mRunRoot','%s'," + ...
    "'evaluationSeed',7601,'acceptanceSimulations',50," + ...
    "'restSimulations',24))", ...
    escape(matlabRoot), escape(string(fileparts(runRoot))), ...
    escape(options.stage7mRunRoot));
end

function textValue = buildOfflineReport(manifest, summary, analysis)
primary = summary(summary.episode == 200, :);
lines = [ ...
    "# ETAPA 7N — smoke conductual 60 frente a 62"; ""; ...
    "- Resultado de ejecución: PASS."; ...
    "- Resultado científico: `" + manifest.scientificResult + "`."; ...
    "- Gate científico: " + string(manifest.scientificGatePassed) + "."; ...
    "- Dos TD3 nuevos: seed 11, 200 episodios cada uno."; ...
    "- Checkpoints evaluados: 50, 100, 150 y 200; 50/24 episodios cada uno."; ...
    "- Único factor: `intentMarkov60` frente a " + ...
        "`intentDeclaredRestHoldMarkov62`."; ...
    "- Agent7250/Agent200 cargados: no/no."; ...
    "- Hardware/DTW: no/no."; ""; ...
    "## Checkpoint primario 200"; ""; ...
    sprintf("- Control MSE/action/delta/sat: %.9g / %.9g / %.9g / %.9g.", ...
        primary.trackingMse(1), primary.actionL2(1), ...
        primary.deltaActionL2(1), primary.saturationFraction(1)); ...
    sprintf("- Candidato MSE/action/delta/sat: %.9g / %.9g / %.9g / %.9g.", ...
        primary.trackingMse(2), primary.actionL2(2), ...
        primary.deltaActionL2(2), primary.saturationFraction(2)); ...
    ""; "## Gates"; ""; ...
    "Véase `gate_checks.csv`. No se autorizó piloto ni campaña."; ...
    "Clasificación: `" + analysis.classification + "`." ...
    ];
textValue = strjoin(lines, newline);
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function hash = fileSha256(filePath)
escaped = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escaped);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7n_state_ablation:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = string(strtrim(output));
end

function value = escape(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7n_state_ablation:WriteFailed", ...
        "Could not write %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
