function report = run_no_glove_stage7f_action_weight_ablation(options)
%run_no_glove_stage7f_action_weight_ablation runs the bounded paired smoke.
%
% Only intentRewardActionWeight changes: 0.01 versus 0.05. Both policies
% start from scratch with seed 11 and stop after 200 episodes.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7f_action_weight_ablation");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7f_action_weight_ablation:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testResults = runtests(fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage7fActionWeightAblation.m"));
save(fullfile(runRoot, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7f_action_weight_ablation:TestsFailed", ...
        "ETAPA 7F tests failed; training is forbidden. See %s.", runRoot);
end

fixed = struct( ...
    "phase", "smoke", "calibrationSeed", 11, ...
    "evaluationSeed", 7601, "evaluationSimulations", 50, ...
    "restSimulations", 24, "positionSafetyAblation", true);
controlOptions = fixed;
controlOptions.resultsRoot = fullfile(runRoot, "control_wu_0p01");
controlOptions.intentRewardActionWeight = 0.01;
candidateOptions = fixed;
candidateOptions.resultsRoot = fullfile(runRoot, "candidate_wu_0p05");
candidateOptions.intentRewardActionWeight = 0.05;

reuseCompletedRuns = strlength(options.completedControlRunRoot) > 0;
if reuseCompletedRuns
    controlReport = loadCompletedStage6Run(options.completedControlRunRoot);
    candidateReport = loadCompletedStage6Run( ...
        options.completedCandidateRunRoot);
else
    controlReport = run_no_glove_stage6_training(controlOptions);
    candidateReport = run_no_glove_stage6_training(candidateOptions);
end
assertBoundedFreshSmoke(controlReport, 0.01);
assertBoundedFreshSmoke(candidateReport, 0.05);

[profileAudit, initializationAudit, datasetAudit] = ...
    auditMatchedDesign(controlReport, candidateReport);
control = buildVariant("control", 0.01, controlReport);
candidate = buildVariant("candidate", 0.05, candidateReport);
analysis = analyzeNoGloveStage7fActionWeightAblation(control, candidate);
historicalControlAudit = auditHistoricalControl( ...
    options.historicalControlCheckpoint, controlReport);

variantSummary = analysis.variantSummary;
comparison = analysis.comparison;
gateChecks = analysis.gateChecks;
restMotorSummary = analysis.restMotorSummary;
checkpointInventory = [addVariantColumn( ...
    controlReport.checkpointTable, "control"); ...
    addVariantColumn(candidateReport.checkpointTable, "candidate")];
writetable(variantSummary, fullfile(runRoot, "variant_summary.csv"));
writetable(comparison, fullfile(runRoot, "comparison.csv"));
writetable(gateChecks, fullfile(runRoot, "gate_checks.csv"));
writetable(restMotorSummary, fullfile(runRoot, "rest_motor_summary.csv"));
writetable(checkpointInventory, ...
    fullfile(runRoot, "checkpoint_inventory.csv"));
writetable(struct2table(profileAudit), ...
    fullfile(runRoot, "profile_audit.csv"));
writetable(struct2table(initializationAudit), ...
    fullfile(runRoot, "initialization_audit.csv"));
writetable(struct2table(datasetAudit), ...
    fullfile(runRoot, "dataset_audit.csv"));
writetable(struct2table(historicalControlAudit), ...
    fullfile(runRoot, "historical_control_reproduction.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", "7F", "schemaVersion", 1, "result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7f_action_weight_ablation", ...
    "controlActionWeight", 0.01, "candidateActionWeight", 0.05, ...
    "singleChangedFactor", "intentRewardActionWeight", ...
    "protocol", fixed, "episodeBudgetPerVariant", 200, ...
    "seed", 11, "checkpointCadence", 50, ...
    "controlRunRoot", controlReport.outputPath, ...
    "candidateRunRoot", candidateReport.outputPath, ...
    "reusedCompletedChildRuns", reuseCompletedRuns, ...
    "controlManifestSha256", fileSha256(fullfile( ...
        controlReport.outputPath, "manifest.json")), ...
    "candidateManifestSha256", fileSha256(fullfile( ...
        candidateReport.outputPath, "manifest.json")), ...
    "profileAudit", profileAudit, ...
    "initializationAudit", initializationAudit, ...
    "datasetAudit", datasetAudit, ...
    "historicalControlAudit", historicalControlAudit, ...
    "thresholds", analysis.thresholds, ...
    "gatePassed", analysis.gatePassed, "gateChecks", analysis.checks, ...
    "comparison", table2struct(comparison), ...
    "control", table2struct(variantSummary(1, :)), ...
    "candidate", table2struct(variantSummary(2, :)), ...
    "rootCauseIdentified", false, ...
    "newTraining", true, "checkpointLoadedForTraining", false, ...
    "agent7250Loaded", false, "agent7250UsedAsStartingPoint", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "referenceSource", "emgIntent", ...
    "observationVariant", "intentMarkov60", ...
    "rewardType", "trackingIntentActionRateReward", ...
    "actionInterfaceVariant", "baselineQuantized", ...
    "simulationPositionSafetyEnabled", true, ...
    "simMotors", true, "simulatorUsed", true, ...
    "hardwareUsed", false, "dtwCalculated", false, ...
    "pilotAuthorized", false, "longCampaignAuthorized", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);
save(fullfile(runRoot, "stage7f_results.mat"), "manifest", ...
    "analysis", "control", "candidate", "controlReport", ...
    "candidateReport", "profileAudit", "initializationAudit", ...
    "datasetAudit", "historicalControlAudit", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "gatePassed", analysis.gatePassed, "outputPath", runRoot, ...
    "manifest", manifest, "analysis", analysis, ...
    "controlReport", controlReport, "candidateReport", candidateReport);
fprintf("ETAPA 7F ACTION WEIGHT ABLATION PASS\n");
fprintf("Scientific result: %s\n", analysis.classification);
fprintf("Gate passed: %d\n", analysis.gatePassed);
fprintf("Output: %s\n", runRoot);
disp(variantSummary);
disp(comparison);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7f_action_weight_ablation:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct("resultsRoot", "", ...
    "historicalControlCheckpoint", "", ...
    "completedControlRunRoot", "", ...
    "completedCandidateRunRoot", "");
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7f_action_weight_ablation:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.historicalControlCheckpoint = ...
    string(options.historicalControlCheckpoint);
options.completedControlRunRoot = string(options.completedControlRunRoot);
options.completedCandidateRunRoot = string(options.completedCandidateRunRoot);
if strlength(options.historicalControlCheckpoint) > 0 && ...
        ~isfile(options.historicalControlCheckpoint)
    error("run_no_glove_stage7f_action_weight_ablation:MissingHistoricalControl", ...
        "Historical control checkpoint not found: %s", ...
        options.historicalControlCheckpoint);
end
hasControl = strlength(options.completedControlRunRoot) > 0;
hasCandidate = strlength(options.completedCandidateRunRoot) > 0;
if xor(hasControl, hasCandidate)
    error("run_no_glove_stage7f_action_weight_ablation:IncompleteResume", ...
        "Both completed child run roots are required for offline resume.");
end
if hasControl
    assertCompletedRunRoot(options.completedControlRunRoot);
    assertCompletedRunRoot(options.completedCandidateRunRoot);
end
end

function assertCompletedRunRoot(runRoot)
required = ["manifest.json", "stage6_results.mat", ...
    fullfile("seed_11", "effective_training_profile.mat")];
for idx = 1:numel(required)
    if ~isfile(fullfile(runRoot, required(idx)))
        error("run_no_glove_stage7f_action_weight_ablation:InvalidResumeRun", ...
            "Completed child run is missing %s under %s.", ...
            required(idx), runRoot);
    end
end
end

function report = loadCompletedStage6Run(runRoot)
data = load(fullfile(runRoot, "stage6_results.mat"), ...
    "manifest", "seedResults", "seedTable", "checkpointTable");
report = struct("result", string(data.manifest.result), ...
    "phase", string(data.manifest.phase), ...
    "phaseGatePassed", logical(data.manifest.phaseGatePassed), ...
    "outputPath", string(runRoot), "manifest", data.manifest, ...
    "seedTable", data.seedTable, "checkpointTable", data.checkpointTable, ...
    "seedResults", {data.seedResults});
end

function assertBoundedFreshSmoke(report, expectedWeight)
m = report.manifest;
valid = string(m.phase) == "smoke" && m.protocol.episodes == 200 && ...
    isequal(double(m.seeds), 11) && m.newTraining && ...
    strlength(string(m.checkpointLoadedForTraining)) == 0 && ...
    ~m.agent7250Loaded && ~m.agent7250UsedAsStartingPoint && ...
    m.simMotors && ~m.hardwareUsed && m.positionSafetyAblation && ...
    string(m.referenceSource) == "emgIntent" && ...
    string(m.observationVariant) == "intentMarkov60" && ...
    string(m.actionInterfaceVariant) == "baselineQuantized" && ...
    m.intentRewardActionWeight == expectedWeight;
if ~valid
    error("run_no_glove_stage7f_action_weight_ablation:InvariantViolation", ...
        "A child smoke violated the pre-registered ETAPA 7F contract.");
end
end

function [profileAudit, initAudit, datasetAudit] = ...
        auditMatchedDesign(controlReport, candidateReport)
controlPath = fullfile(controlReport.outputPath, ...
    "seed_11", "effective_training_profile.mat");
candidatePath = fullfile(candidateReport.outputPath, ...
    "seed_11", "effective_training_profile.mat");
controlData = load(controlPath, "profile");
candidateData = load(candidatePath, "profile");
control = controlData.profile;
candidate = candidateData.profile;

controlNormalized = normalizeProfile(control);
candidateNormalized = normalizeProfile(candidate);
profileEqualExceptActionWeightAndPaths = ...
    isequaln(controlNormalized, candidateNormalized);
profileAudit = struct( ...
    "controlActionWeight", control.intentRewardActionWeight, ...
    "candidateActionWeight", candidate.intentRewardActionWeight, ...
    "equalExceptActionWeightAndOutputPaths", ...
        profileEqualExceptActionWeightAndPaths, ...
    "sameRandomSeed", control.randomSeed == candidate.randomSeed, ...
    "sameEpisodeBudget", ...
        control.trainingMaxEpisodes == candidate.trainingMaxEpisodes, ...
    "sameCheckpointCadence", ...
        control.trainingSaveAgentEvery == candidate.trainingSaveAgentEvery, ...
    "sameSafety", isequaln(control.simulationPositionSafety, ...
        candidate.simulationPositionSafety));
pairingChecks = [profileAudit.equalExceptActionWeightAndOutputPaths, ...
    profileAudit.sameRandomSeed, profileAudit.sameEpisodeBudget, ...
    profileAudit.sameCheckpointCadence, profileAudit.sameSafety];
if ~all(pairingChecks)
    error("run_no_glove_stage7f_action_weight_ablation:ProfileMismatch", ...
        "The two effective profiles differ beyond the allowed factor/paths.");
end

initAudit = compareInitialActors(control, candidate);
datasetAudit = compareDatasets(controlReport.manifest, ...
    candidateReport.manifest);
if ~initAudit.actorLearnablesExactlyEqual || ...
        ~datasetAudit.allDatasetContentsEqual
    error("run_no_glove_stage7f_action_weight_ablation:PairingFailed", ...
        "Initial actor or dataset pairing was not exact.");
end
end

function profile = normalizeProfile(profile)
profile.intentRewardActionWeight = 0;
profile.dataset_folder = "<matched-dataset-folder>";
profile = rmfield(profile, "agents_directory");
end

function audit = compareInitialActors(control, candidate)
clearConfigurablesOverride();
setConfigurablesOverride(control);
rng(double(control.randomSeed), "twister");
agentA = agentNoGloveIntentTd3( ...
    Env.defineObservationInfo(), Env.defineActionInfo());
paramsA = getLearnableParameters(getActor(agentA));
clearConfigurablesOverride();
setConfigurablesOverride(candidate);
rng(double(candidate.randomSeed), "twister");
agentB = agentNoGloveIntentTd3( ...
    Env.defineObservationInfo(), Env.defineActionInfo());
paramsB = getLearnableParameters(getActor(agentB));
clearConfigurablesOverride();
if numel(paramsA) ~= numel(paramsB)
    maxError = Inf;
    parameterCount = NaN;
else
    errors = zeros(numel(paramsA), 1);
    counts = zeros(numel(paramsA), 1);
    for idx = 1:numel(paramsA)
        a = numericParameter(paramsA{idx});
        b = numericParameter(paramsB{idx});
        errors(idx) = max(abs(a-b), [], "all");
        counts(idx) = numel(a);
    end
    maxError = max(errors);
    parameterCount = sum(counts);
end
audit = struct("randomSeed", double(control.randomSeed), ...
    "actorLearnableArrayCount", numel(paramsA), ...
    "actorLearnableParameterCount", parameterCount, ...
    "maximumActorInitializationError", maxError, ...
    "actorLearnablesExactlyEqual", maxError == 0);
end

function value = numericParameter(value)
if isa(value, "dlarray")
    value = extractdata(value);
end
if ~isnumeric(value)
    error("run_no_glove_stage7f_action_weight_ablation:LearnableType", ...
        "Actor learnables must be numeric or dlarray values.");
end
value = double(value);
end

function audit = compareDatasets(control, candidate)
names = ["trainingDatasetPath", "evaluationDatasetPath", "restDatasetPath"];
equal = false(1, numel(names));
for idx = 1:numel(names)
    a = load(string(control.(names(idx))), "emgs", "metadata");
    b = load(string(candidate.(names(idx))), "emgs", "metadata");
    equal(idx) = isequaln(a.emgs, b.emgs) && ...
        isequaln(a.metadata, b.metadata);
end
audit = struct("trainingDatasetContentEqual", equal(1), ...
    "evaluationDatasetContentEqual", equal(2), ...
    "restDatasetContentEqual", equal(3), ...
    "calibrationContentSha256Equal", ...
        string(control.calibrationContentSha256) == ...
        string(candidate.calibrationContentSha256), ...
    "allDatasetContentsEqual", all(equal));
end

function variant = buildVariant(label, actionWeight, childReport)
seed = childReport.seedResults{1};
restCommands = summarizeNoGloveStage7fRestCommands(seed.restDirectory);
restCommands.positionViolationEpisodeCount = ...
    seed.rest.positionViolationEpisodeCount;
restCommands.positionSafetyInterventionCount = ...
    seed.rest.positionSafetyInterventionCount;
training = selectSafetyMetrics(seed.trainingSafety);
acceptance = selectAcceptanceMetrics(seed.acceptance);
finalRow = childReport.checkpointTable(childReport.checkpointTable.isFinal, :);
variant = struct("label", label, "actionWeight", actionWeight, ...
    "training", training, "acceptance", acceptance, ...
    "rest", restCommands, ...
    "decodedRestFalseActivationFraction", ...
        childReport.manifest.restFalseActivationFraction, ...
    "checkpointSha256", string(finalRow.checkpointSha256));
end

function value = selectSafetyMetrics(source)
value = struct("allFinite", logical(source.allFinite), ...
    "positionViolationEpisodeCount", ...
        double(source.positionViolationEpisodeCount), ...
    "positionSafetyInterventionCount", ...
        double(source.positionSafetyInterventionCount));
end

function value = selectAcceptanceMetrics(source)
value = selectSafetyMetrics(source);
names = ["trackingMse", "trackingMae", "actionL2", ...
    "deltaActionL2", "saturationFraction", ...
    "motor2FunctionalFlagCount", "otherMotorFunctionalFlagCount"];
for idx = 1:numel(names)
    value.(names(idx)) = double(source.(names(idx)));
end
end

function tableValue = addVariantColumn(tableValue, label)
tableValue = addvars(tableValue, ...
    repmat(string(label), height(tableValue), 1), ...
    'Before', 1, 'NewVariableNames', "variant");
end

function audit = auditHistoricalControl(checkpointPath, controlReport)
audit = struct("attempted", false, "historicalCheckpointPath", "", ...
    "historicalCheckpointSha256", "", "stateCount", 0, ...
    "maximumRawActionError", NaN, "rawActionsExactlyEqual", false);
if strlength(checkpointPath) == 0
    return;
end
audit.attempted = true;
audit.historicalCheckpointPath = checkpointPath;
audit.historicalCheckpointSha256 = fileSha256(checkpointPath);
newPath = string(controlReport.seedTable.finalCheckpoint(1));
oldAgent = loadAgent(checkpointPath);
newAgent = loadAgent(newPath);
restDir = string(controlReport.seedTable.restDirectory(1));
states = readStates(restDir);
oldActions = evaluateFrozenActorStates(getActor(oldAgent), states);
newActions = evaluateFrozenActorStates(getActor(newAgent), states);
audit.stateCount = size(states, 1);
audit.maximumRawActionError = max(abs(oldActions-newActions), [], "all");
audit.rawActionsExactlyEqual = audit.maximumRawActionError == 0;
end

function agent = loadAgent(path)
variables = string(who("-file", path));
if any(variables == "saved_agent")
    data = load(path, "saved_agent");
    agent = data.saved_agent;
elseif any(variables == "agent")
    data = load(path, "agent");
    agent = data.agent;
else
    error("run_no_glove_stage7f_action_weight_ablation:InvalidCheckpoint", ...
        "Checkpoint %s contains no supported agent variable.", path);
end
end

function states = readStates(episodeDirectory)
files = dir(fullfile(episodeDirectory, "episode*.mat"));
parts = cell(numel(files), 1);
for idx = 1:numel(files)
    data = load(fullfile(files(idx).folder, files(idx).name), "stateLog");
    parts{idx} = double(data.stateLog);
end
states = vertcat(parts{:});
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
root = string(fileparts(runRoot));
historical = "";
if strlength(options.historicalControlCheckpoint) > 0
    historical = sprintf(", 'historicalControlCheckpoint','%s'", ...
        escapeQuote(options.historicalControlCheckpoint));
end
resume = "";
if strlength(options.completedControlRunRoot) > 0
    resume = sprintf(", 'completedControlRunRoot','%s'," + ...
        "'completedCandidateRunRoot','%s'", ...
        escapeQuote(options.completedControlRunRoot), ...
        escapeQuote(options.completedCandidateRunRoot));
end
command = sprintf("cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7f_action_weight_ablation(struct(" + ...
    "'resultsRoot','%s'%s%s))", escapeQuote(matlabRoot), ...
    escapeQuote(root), historical, resume);
end

function value = buildOfflineReport(manifest)
c = manifest.comparison;
lines = ["# ETAPA 7F - action weight ablation"; ""; ...
    "- Engineering result: PASS."; ...
    "- Scientific result: " + manifest.scientificResult + "."; ...
    "- Gate passed: " + string(manifest.gatePassed) + "."; ...
    sprintf("- ActionL2 relative reduction: %.9f.", c.actionL2Reduction); ...
    sprintf("- Tracking MSE ratio: %.9f.", c.trackingMseRatio); ...
    "- Changed factor: intentRewardActionWeight 0.01 -> 0.05."; ...
    "- Training: two fresh 200-episode seed-11 TD3 policies."; ...
    "- Hardware: no; simulator: yes; DTW: no; pilot: not authorized."];
value = strjoin(lines, newline);
end

function hashes = inventoryArtifacts(runRoot)
names = ["test_results.mat", "variant_summary.csv", "comparison.csv", ...
    "gate_checks.csv", "rest_motor_summary.csv", ...
    "checkpoint_inventory.csv", "profile_audit.csv", ...
    "initialization_audit.csv", "dataset_audit.csv", ...
    "historical_control_reproduction.csv", "stage7f_results.mat", ...
    "offline_report.md", "reproducible_command.txt"];
hashes = repmat(struct("path", "", "sha256", ""), numel(names), 1);
for idx = 1:numel(names)
    hashes(idx).path = names(idx);
    hashes(idx).sha256 = fileSha256(fullfile(runRoot, names(idx)));
end
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
commit = "unknown";
if status == 0
    commit = string(strtrim(output));
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[trackedStatus, trackedOutput] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = trackedStatus ~= 0 || ...
    strlength(strtrim(string(trackedOutput))) > 0;
end

function hash = fileSha256(path)
escaped = strrep(char(string(path)), "'", "''");
command = sprintf(['powershell -NoProfile -Command "(Get-FileHash ' ...
    '-Algorithm SHA256 -LiteralPath ''%s'').Hash"'], escaped);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7f_action_weight_ablation:HashFailed", ...
        "Could not hash %s.", path);
end
hash = string(strtrim(output));
end

function value = escapeQuote(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7f_action_weight_ablation:WriteFailed", ...
        "Could not open %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
