function report = run_no_glove_stage7l_declared_rest_eligibility_audit(options)
%run_no_glove_stage7l_declared_rest_eligibility_audit audits a latch offline.
%
% Frozen Stage 7K semantic labels and Stage 7I position errors are read as
% tables. No agent, Env, simulator, reward, training, DTW or hardware route is
% invoked.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", ...
        "stage7l_declared_rest_eligibility");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testResults = runtests(fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage7lDeclaredRestEligibility.m"));
save(fullfile(runRoot, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:TestsFailed", ...
        "ETAPA 7L tests failed. See %s.", runRoot);
end

[stage7k, stage7i, stage7j, frozen, sourceHashesBefore, ...
    parentAudit] = loadAndValidateInputs(options.stage7kRunRoot);
episodeHashesBefore = rehashEpisodeInputs(frozen.inputHashesBefore);
if ~isequal(frozen.inputHashesBefore, episodeHashesBefore)
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:EpisodeHash", ...
        "A frozen 7H episode differs from the Stage 7I inventory.");
end
analysis = analyzeNoGloveStage7lDeclaredRestEligibility( ...
    frozen.decisions, frozen.windows);
episodeHashesAfter = rehashEpisodeInputs(frozen.inputHashesBefore);
if ~isequal(episodeHashesBefore, episodeHashesAfter)
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:InputModified", ...
        "A frozen episode changed during the offline audit.");
end
sourceHashesAfter = hashFrozenSources(options.stage7kRunRoot, ...
    string(stage7k.stage7iRunRoot), string(stage7k.stage7jRunRoot));
if ~isequal(sourceHashesBefore, sourceHashesAfter)
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:SourceModified", ...
        "A frozen parent artifact changed during the offline audit.");
end

writetable(episodeHashesBefore, ...
    fullfile(runRoot, "episode_input_hashes.csv"));
writetable(sourceHashesBefore, fullfile(runRoot, "source_hashes.csv"));
writetable(parentAudit, fullfile(runRoot, "parent_audit.csv"));
writetable(analysis.windowAudit, ...
    fullfile(runRoot, "declared_rest_window_audit.csv"));
writetable(analysis.episodeAudit, ...
    fullfile(runRoot, "episode_audit.csv"));
writetable(analysis.segmentAudit, ...
    fullfile(runRoot, "stopped_segment_audit.csv"));
writetable(analysis.variantSummary, ...
    fullfile(runRoot, "variant_summary.csv"));
writetable(analysis.provenanceSummary, ...
    fullfile(runRoot, "provenance_summary.csv"));
writetable(analysis.gateChecks, fullfile(runRoot, "gate_checks.csv"));
writetable(analysis.sourceDecision, ...
    fullfile(runRoot, "source_decision.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = string(stage7k.agent7250CheckpointPath);
agent7250Hash = fileSha256(agent7250Path);
if agent7250Hash ~= string(stage7k.agent7250CheckpointSha256)
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:Agent7250Hash", ...
        "The canonical Agent7250 file changed.");
end
manifest = struct("stage", "7L", "schemaVersion", 1, ...
    "result", "PASS", "scientificResult", analysis.classification, ...
    "contractSupported", analysis.contractSupported, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", ...
        "run_no_glove_stage7l_declared_rest_eligibility_audit", ...
    "preregistrationCommit", ...
        "2bea46282206dc2406d4aaf38268389a682a5450", ...
    "stage7kRunRoot", options.stage7kRunRoot, ...
    "stage7iRunRoot", string(stage7k.stage7iRunRoot), ...
    "stage7jRunRoot", string(stage7k.stage7jRunRoot), ...
    "stage7kManifestSha256", sourceHashesBefore.sha256(1), ...
    "stage7kResultsSha256", sourceHashesBefore.sha256(2), ...
    "stage7kDecisionCorpusSha256", sourceHashesBefore.sha256(3), ...
    "stage7iManifestSha256", sourceHashesBefore.sha256(5), ...
    "stage7iResultsSha256", sourceHashesBefore.sha256(6), ...
    "stage7iWindowCorpusSha256", sourceHashesBefore.sha256(7), ...
    "stage7jManifestSha256", sourceHashesBefore.sha256(9), ...
    "inputEpisodeCount", height(episodeHashesBefore), ...
    "inputWindowCount", height(frozen.windows), ...
    "inputsPreserved", true, "parentAudit", table2struct(parentAudit), ...
    "thresholds", analysis.thresholds, ...
    "variantSummary", table2struct(analysis.variantSummary), ...
    "gateChecks", table2struct(analysis.gateChecks), ...
    "sourceDecision", table2struct(analysis.sourceDecision), ...
    "prefixCheckCount", analysis.prefixCheckCount, ...
    "prefixMismatchCount", analysis.prefixMismatchCount, ...
    "explicitMemoryRequired", analysis.explicitMemoryRequired, ...
    "proposedObservationVariant", analysis.proposedObservationVariant, ...
    "proposedObservationDimension", ...
        analysis.proposedObservationDimension, ...
    "observationVariantImplemented", false, ...
    "behavioralInterventionExecuted", false, ...
    "behavioralAblationAuthorized", false, ...
    "stage7jScientificResultPreserved", ...
        string(stage7j.scientificResult), ...
    "stage7jContractReauthorized", false, ...
    "rootCauseIdentified", false, ...
    "referenceSource", "emgIntent", ...
    "observationVariant", "intentMarkov60", ...
    "actionInterfaceVariant", "baselineQuantized", ...
    "policyChanged", false, "stateChanged", false, ...
    "rewardChanged", false, "referenceChanged", false, ...
    "quantizationChanged", false, "simulatorChanged", false, ...
    "safetyLayerChanged", false, "runTraining", false, ...
    "newTraining", false, "agentLoaded", false, ...
    "envCreated", false, "simulatorInvoked", false, ...
    "rewardFunctionInvoked", false, "dtwCalculated", false, ...
    "simMotors", true, "hardwareUsed", false, ...
    "pilotAuthorized", false, "longCampaignAuthorized", false, ...
    "agent7250Loaded", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", agent7250Hash, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);
save(fullfile(runRoot, "stage7l_results.mat"), "manifest", ...
    "analysis", "episodeHashesBefore", "sourceHashesBefore", ...
    "parentAudit", "stage7k", "stage7i", "stage7j", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "contractSupported", analysis.contractSupported, ...
    "outputPath", runRoot, "manifest", manifest, ...
    "analysis", analysis);
fprintf("ETAPA 7L DECLARED-REST ELIGIBILITY AUDIT PASS\n");
fprintf("Scientific result: %s\n", analysis.classification);
fprintf("Contract supported: %d\n", analysis.contractSupported);
fprintf("Output: %s\n", runRoot);
disp(analysis.variantSummary);
disp(analysis.gateChecks);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct("resultsRoot", "", "stage7kRunRoot", ...
    "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7k_artifacts\" + ...
    "stage7k_final\2026-08-28_21-25-50-214");
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.stage7kRunRoot = string(options.stage7kRunRoot);
if ~isfile(fullfile(options.stage7kRunRoot, "manifest.json"))
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:MissingStage7k", ...
        "ETAPA 7K manifest not found under %s.", options.stage7kRunRoot);
end
end

function [stage7k, stage7i, stage7j, frozen, hashes, audit] = ...
        loadAndValidateInputs(stage7kRoot)
stage7k = jsondecode(fileread(fullfile(stage7kRoot, "manifest.json")));
valid7k = string(stage7k.stage) == "7K" && ...
    string(stage7k.result) == "PASS" && ...
    string(stage7k.scientificResult) == ...
        "zeroReferenceMixedCausalMechanisms" && ...
    logical(stage7k.replayGatePassed) && ...
    double(stage7k.inputEpisodeCount) == 548 && ...
    double(stage7k.inputWindowCount) == 31220 && ...
    logical(stage7k.inputsPreserved) && ...
    ~logical(stage7k.latchContractReauthorized) && ...
    ~logical(stage7k.behavioralInterventionExecuted) && ...
    ~logical(stage7k.runTraining) && ~logical(stage7k.agentLoaded) && ...
    ~logical(stage7k.scientificReplaySimulatorInvoked) && ...
    ~logical(stage7k.dtwCalculated) && ~logical(stage7k.hardwareUsed) && ...
    ~logical(stage7k.agent7250Loaded);
if ~valid7k
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:Stage7kContract", ...
        "Input manifest is not the frozen ETAPA 7K result.");
end
stage7iRoot = string(stage7k.stage7iRunRoot);
stage7jRoot = string(stage7k.stage7jRunRoot);
stage7i = jsondecode(fileread(fullfile(stage7iRoot, "manifest.json")));
stage7j = jsondecode(fileread(fullfile(stage7jRoot, "manifest.json")));
validParents = string(stage7i.stage) == "7I" && ...
    string(stage7i.result) == "PASS" && ...
    string(stage7i.scientificResult) == ...
        "holdSupportNotSeparableFromFarCorrection" && ...
    logical(stage7i.episodeInputsPreserved) && ...
    ~logical(stage7i.runTraining) && ~logical(stage7i.hardwareUsed) && ...
    string(stage7j.stage) == "7J" && ...
    string(stage7j.result) == "PASS" && ...
    string(stage7j.scientificResult) == ...
        "latchedHoldNotSeparableFromFarCorrection" && ...
    ~logical(stage7j.contractSupported) && ...
    ~logical(stage7j.behavioralInterventionExecuted) && ...
    ~logical(stage7j.runTraining) && ~logical(stage7j.hardwareUsed);
if ~validParents
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:ParentContract", ...
        "Stage 7K does not point to the frozen 7I/7J results.");
end
required = ["stage7k_results.mat", "decision_provenance.csv", ...
    "source_decision.csv"];
for name = required
    if ~isfile(fullfile(stage7kRoot, name))
        error("run_no_glove_stage7l_declared_rest_eligibility_audit:Stage7kArtifact", ...
            "Frozen ETAPA 7K artifact %s is missing.", name);
    end
end
stage7kData = load(fullfile(stage7kRoot, "stage7k_results.mat"), ...
    "analysis");
stage7iData = load(fullfile(stage7iRoot, "stage7i_results.mat"), ...
    "windows", "episodeAudit", "inputHashesBefore");
if height(stage7kData.analysis.decisionAudit) ~= 31220 || ...
        string(stage7kData.analysis.classification) ~= ...
        string(stage7k.scientificResult) || ...
        height(stage7iData.windows) ~= 31220 || ...
        height(stage7iData.episodeAudit) ~= 548 || ...
        height(stage7iData.inputHashesBefore) ~= 548
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:ParentResults", ...
        "Frozen parent MAT files have unexpected contents.");
end
frozen = struct("decisions", stage7kData.analysis.decisionAudit, ...
    "windows", stage7iData.windows, ...
    "episodeAudit", stage7iData.episodeAudit, ...
    "inputHashesBefore", stage7iData.inputHashesBefore);
hashes = hashFrozenSources(stage7kRoot, stage7iRoot, stage7jRoot);
audit = table(string(stage7k.scientificResult), ...
    logical(stage7k.replayGatePassed), ...
    string(stage7i.scientificResult), ...
    string(stage7j.scientificResult), ...
    logical(stage7j.contractSupported), ...
    double(stage7k.inputEpisodeCount), ...
    double(stage7k.inputWindowCount), logical(stage7k.inputsPreserved), ...
    logical(stage7i.episodeInputsPreserved), ...
    'VariableNames', ["stage7kScientificResult", ...
    "stage7kReplayGatePassed", "stage7iScientificResult", ...
    "stage7jScientificResult", "stage7jContractSupported", ...
    "episodeCount", "windowCount", "stage7kInputsPreserved", ...
    "stage7iInputsPreserved"]);
end

function hashes = hashFrozenSources(stage7kRoot, stage7iRoot, stage7jRoot)
paths = [fullfile(stage7kRoot, "manifest.json"); ...
    fullfile(stage7kRoot, "stage7k_results.mat"); ...
    fullfile(stage7kRoot, "decision_provenance.csv"); ...
    fullfile(stage7kRoot, "source_decision.csv"); ...
    fullfile(stage7iRoot, "manifest.json"); ...
    fullfile(stage7iRoot, "stage7i_results.mat"); ...
    fullfile(stage7iRoot, "window_corpus.csv"); ...
    fullfile(stage7iRoot, "episode_input_hashes.csv"); ...
    fullfile(stage7jRoot, "manifest.json"); ...
    fullfile(stage7jRoot, "source_decision.csv")];
labels = ["stage7kManifest"; "stage7kResults"; ...
    "stage7kDecisionCorpus"; "stage7kSourceDecision"; ...
    "stage7iManifest"; "stage7iResults"; "stage7iWindowCorpus"; ...
    "stage7iEpisodeInventory"; "stage7jManifest"; ...
    "stage7jSourceDecision"];
sha256 = strings(numel(paths), 1);
bytes = zeros(numel(paths), 1);
for idx = 1:numel(paths)
    info = dir(paths(idx));
    if isempty(info)
        error("run_no_glove_stage7l_declared_rest_eligibility_audit:SourceMissing", ...
            "Frozen source %s is missing.", paths(idx));
    end
    sha256(idx) = fileSha256(paths(idx));
    bytes(idx) = info.bytes;
end
hashes = table(labels, paths, sha256, bytes);
end

function observed = rehashEpisodeInputs(expected)
observed = expected;
for idx = 1:height(expected)
    path = string(expected.path(idx));
    if ~isfile(path)
        error("run_no_glove_stage7l_declared_rest_eligibility_audit:EpisodeMissing", ...
            "Frozen episode %s is missing.", path);
    end
    info = dir(path);
    observed.bytes(idx) = info.bytes;
    observed.sha256(idx) = fileSha256(path);
end
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf("cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7l_declared_rest_eligibility_audit(struct(" + ...
    "'resultsRoot','%s','stage7kRunRoot','%s'))", ...
    escapeQuote(matlabRoot), escapeQuote(string(fileparts(runRoot))), ...
    escapeQuote(options.stage7kRunRoot));
end

function value = buildOfflineReport(manifest)
d = manifest.sourceDecision;
lines = ["# ETAPA 7L - declared-rest eligibility audit"; ""; ...
    "- Engineering result: PASS."; ...
    "- Scientific result: " + manifest.scientificResult + "."; ...
    "- Contract supported offline: " + ...
        string(manifest.contractSupported) + "."; ...
    sprintf("- Declared-rest windows: %d.", ...
        d.declaredRestWindowCount); ...
    sprintf("- Minimum per-variant steady-rest coverage: %.9f.", ...
        d.minimumVariantSteadyRestCoverage); ...
    sprintf("- Non-rest leakage windows: %d.", ...
        d.nonRestLeakageCount); ...
    sprintf("- Premature far-started latch windows: %d.", ...
        d.prematureFarStartedLatchCount); ...
    sprintf("- Memory-recovered windows: %d.", ...
        d.recoveredByMemoryCount); ...
    sprintf("- Difference from Stage 7J latch: %d windows (diagnostic).", ...
        d.stage7jLatchDifferenceCount); ...
    "- Stage 7J remains contractSupported=false."; ...
    "- State/reward/policy/training/DTW/hardware: unchanged/no/no/no/no/no."];
value = strjoin(lines, newline);
end

function hashes = inventoryArtifacts(runRoot)
names = ["test_results.mat", "episode_input_hashes.csv", ...
    "source_hashes.csv", "parent_audit.csv", ...
    "declared_rest_window_audit.csv", "episode_audit.csv", ...
    "stopped_segment_audit.csv", "variant_summary.csv", ...
    "provenance_summary.csv", "gate_checks.csv", ...
    "source_decision.csv", "stage7l_results.mat", ...
    "offline_report.md", "reproducible_command.txt"];
hashes = repmat(struct("path", "", "sha256", ""), numel(names), 1);
for idx = 1:numel(names)
    hashes(idx).path = names(idx);
    hashes(idx).sha256 = fileSha256(fullfile(runRoot, names(idx)));
end
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
commit = "unknown";
if status == 0
    commit = string(strtrim(output));
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[trackedStatus, trackedOutput] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = trackedStatus ~= 0 || ...
    strlength(strtrim(string(trackedOutput))) > 0;
end

function hash = fileSha256(path)
fid = fopen(path, "r");
if fid < 0
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:HashFailed", ...
        "Could not open %s for hashing.", path);
end
cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid, Inf, "*uint8");
digest = java.security.MessageDigest.getInstance("SHA-256");
digest.update(bytes);
digestBytes = typecast(digest.digest(), "uint8");
hash = upper(string(reshape(dec2hex(digestBytes, 2)', 1, [])));
end

function value = escapeQuote(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7l_declared_rest_eligibility_audit:WriteFailed", ...
        "Could not open %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
