function report = run_no_glove_stage5_plant_diagnostic(options)
%run_no_glove_stage5_plant_diagnostic conventional baseline and plant audit.
%
% The launcher is deterministic and simulation-only. It measures the
% unchanged SimController and encoder2Flex, then runs a quantized P baseline.
% It never creates/trains an agent or accesses physical hardware.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage5_plant");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runDir)
    error("run_no_glove_stage5_plant_diagnostic:OutputExists", ...
        "Refusing to reuse output directory %s.", runDir);
end
mkdir(runDir);

clearConfigurablesOverride();
rng(options.seed, "twister");
testPath = fullfile(matlabRoot, "tests", "no_glove", ...
    "testConventionalPlantDiagnostic.m");
testResults = runtests(testPath);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage5_plant_diagnostic:TestsFailed", ...
        "At least one ETAPA 5 test failed. See %s.", runDir);
end

[stage2Config, ~, calibration, expectedContext] = ...
    buildFixture(options.seed);
profile = buildNoGloveStage5Override( ...
    calibration, expectedContext, options.seed);
setConfigurablesOverride(profile);
configs = configurables();
assertSafeStage5Config(configs);
save(fullfile(runDir, "effective_profile.mat"), ...
    "profile", "configs", "stage2Config", "expectedContext");
save(fullfile(runDir, "intent_calibration.mat"), "calibration");

results = evaluateNoGloveStage5Plant(configs);
writetable(results.openLoopTrials, ...
    fullfile(runDir, "open_loop_trials.csv"));
writetable(results.plantByCondition, ...
    fullfile(runDir, "plant_by_condition.csv"));
writetable(results.plantByMotor, ...
    fullfile(runDir, "plant_by_motor.csv"));
writetable(results.baselineScenarios, ...
    fullfile(runDir, "conventional_baseline_scenarios.csv"));
writetable(results.baselineByMotor, ...
    fullfile(runDir, "conventional_baseline_by_motor.csv"));
functionalFlags = results.baselineScenarios( ...
    results.baselineScenarios.functionalFlag, :);
writetable(functionalFlags, ...
    fullfile(runDir, "conventional_functional_flags.csv"));
motor2Scenarios = results.baselineScenarios( ...
    results.baselineScenarios.motor == 2, :);
writetable(motor2Scenarios, ...
    fullfile(runDir, "motor2_conventional_scenarios.csv"));

openLoopFigurePath = fullfile(runDir, "open_loop_mid_pwm255.png");
baselineFigurePath = fullfile(runDir, "conventional_tracking.png");
createOpenLoopFigure(results, openLoopFigurePath);
createBaselineFigure(results, baselineFigurePath);

metrics = buildMetrics(results);
assertStage5Metrics(metrics);
save(fullfile(runDir, "stage5_results.mat"), ...
    "results", "metrics", "functionalFlags", "motor2Scenarios");
writeOfflineReport(fullfile(runDir, "offline_report.md"), ...
    metrics, results, calibration, runDir);

reproducibleCommand = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage5_plant_diagnostic(struct('seed',%d," + ...
    "'resultsRoot','%s'))", ...
    strrep(char(matlabRoot), "'", "''"), options.seed, ...
    strrep(char(options.resultsRoot), "'", "''"));
writeText(fullfile(runDir, "reproducible_command.txt"), ...
    reproducibleCommand);

sourceArtifacts = [ ...
    fullfile(matlabRoot, "src", "@SimController", "SimController.m"), ...
    fullfile(matlabRoot, "src", "@SimController", "prosthesis_simulator.m"), ...
    fullfile(matlabRoot, "src", "@SimController", "fit_C2.mat"), ...
    fullfile(matlabRoot, "src", "@SimController", "pattern_curve.mat"), ...
    fullfile(matlabRoot, "src", "preprocess", "encoder2Flex.m")];
sourceHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(sourceArtifacts), 1);
for sourceIdx = 1:numel(sourceArtifacts)
    sourceHashes(sourceIdx).path = string(sourceArtifacts(sourceIdx));
    sourceHashes(sourceIdx).sha256 = fileSha256(sourceArtifacts(sourceIdx));
end
writetable(struct2table(sourceHashes), ...
    fullfile(runDir, "unchanged_source_hashes.csv"));

primaryArtifacts = [ ...
    "effective_profile.mat", "intent_calibration.mat", ...
    "test_results.mat", "open_loop_trials.csv", ...
    "plant_by_condition.csv", "plant_by_motor.csv", ...
    "conventional_baseline_scenarios.csv", ...
    "conventional_baseline_by_motor.csv", ...
    "conventional_functional_flags.csv", ...
    "motor2_conventional_scenarios.csv", ...
    "open_loop_mid_pwm255.png", "conventional_tracking.png", ...
    "stage5_results.mat", "offline_report.md", ...
    "reproducible_command.txt", "unchanged_source_hashes.csv"];
artifactHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(primaryArtifacts), 1);
for artifactIdx = 1:numel(primaryArtifacts)
    artifactHashes(artifactIdx).path = primaryArtifacts(artifactIdx);
    artifactHashes(artifactIdx).sha256 = fileSha256( ...
        fullfile(runDir, primaryArtifacts(artifactIdx)));
end
writetable(struct2table(artifactHashes), ...
    fullfile(runDir, "artifact_hashes.csv"));

[gitCommit, gitDirty] = getGitState(repoRoot);
manifest = struct( ...
    "stage", 5, ...
    "schemaVersion", 1, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, ...
    "gitDirty", gitDirty, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage5_plant_diagnostic", ...
    "reproducibleCommand", string(reproducibleCommand), ...
    "seed", options.seed, ...
    "dataProvenance", "syntheticCalibration_directSimulatorProbe", ...
    "calibrationContentSha256", calibration.contentSha256, ...
    "referenceSource", configs.referenceSource, ...
    "observationVariant", configs.observationVariant, ...
    "actionInterfaceVariant", configs.actionInterfaceVariant, ...
    "controller", configs.conventionalController, ...
    "diagnostic", configs.plantDiagnostic, ...
    "simulatorModified", false, ...
    "encoder2FlexModified", false, ...
    "diagnosticBranchBehaviorPorted", false, ...
    "diagnosticBranchFilesInspected", [ ...
        "run_all_motor_actuation_sanity_check_extended.m", ...
        "run_motor2_simulation_sanity_check_extended.m"], ...
    "runTraining", false, ...
    "reinforcementLearningUsed", false, ...
    "agentUsed", false, ...
    "simMotors", true, ...
    "simulatorUsed", true, ...
    "connectGlove", false, ...
    "hardwareUsed", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "testsIncomplete", sum([testResults.Incomplete]), ...
    "metrics", metrics, ...
    "plantByMotor", table2struct(results.plantByMotor), ...
    "baselineByMotor", table2struct(results.baselineByMotor), ...
    "sourceHashes", sourceHashes, ...
    "artifactHashes", artifactHashes, ...
    "outputPath", runDir);
save(fullfile(runDir, "manifest.mat"), "manifest", "metrics", ...
    "sourceHashes", "artifactHashes");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct( ...
    "result", "PASS", ...
    "outputPath", runDir, ...
    "manifest", manifest, ...
    "metrics", metrics, ...
    "plantByMotor", results.plantByMotor, ...
    "baselineByMotor", results.baselineByMotor, ...
    "testResults", testResults);
fprintf("ETAPA 5 conventional baseline and plant diagnostic PASS\n");
fprintf("Output: %s\n", runDir);
disp(struct2table(metrics));
disp(results.plantByMotor);
disp(results.baselineByMotor);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage5_plant_diagnostic:InvalidOptions", ...
        "options must be a scalar struct.");
end
allowed = ["seed", "resultsRoot"];
unknown = setdiff(string(fieldnames(options)), allowed);
if ~isempty(unknown)
    error("run_no_glove_stage5_plant_diagnostic:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
if ~isfield(options, "seed")
    options.seed = 11;
end
if ~isfield(options, "resultsRoot")
    options.resultsRoot = "";
end
if ~isnumeric(options.seed) || ~isscalar(options.seed) || ...
        ~isfinite(options.seed) || options.seed < 0 || ...
        fix(options.seed) ~= options.seed
    error("run_no_glove_stage5_plant_diagnostic:InvalidSeed", ...
        "seed must be a nonnegative integer scalar.");
end
options.resultsRoot = string(options.resultsRoot);
if ~isscalar(options.resultsRoot) || ismissing(options.resultsRoot)
    error("run_no_glove_stage5_plant_diagnostic:InvalidResultsRoot", ...
        "resultsRoot must be a scalar string or character vector.");
end
end

function [config, dataset, calibration, expected] = buildFixture(seed)
config = buildNoGloveStage2OfflineConfig(seed);
dataset = buildSyntheticEmgIntentDataset(config);
calibration = calibrateEmgIntent(dataset.restCapture, ...
    dataset.instructionTrials, config.calibrationOptions);
options = config.calibrationOptions;
expected = struct( ...
    "userId", dataset.restCapture.userId, ...
    "sessionId", dataset.restCapture.sessionId, ...
    "channelOrder", dataset.restCapture.channelOrder, ...
    "sampleRateHz", dataset.restCapture.sampleRateHz, ...
    "windowLengthSamples", dataset.windowLengthSamples, ...
    "hopLengthSamples", dataset.hopLengthSamples, ...
    "dataProvenance", dataset.restCapture.dataProvenance, ...
    "motorOrder", options.motorOrder, ...
    "units", struct( ...
        "rawEmg", dataset.restCapture.rawEmgUnits, ...
        "envelope", options.envelopeUnits, ...
        "position", options.positionUnits, ...
        "velocity", options.velocityUnits, ...
        "acceleration", options.accelerationUnits), ...
    "synergyMatrixVersion", options.synergyMatrixVersion, ...
    "instructionProtocolVersion", options.instructionProtocolVersion, ...
    "sourceDomain", "rawEmgSameSession", ...
    "calibrationContentSha256", calibration.contentSha256);
end

function assertSafeStage5Config(configs)
unsafe = configs.run_training || configs.newTraining || ...
    ~configs.simMotors || configs.connect_glove || ~configs.usePrerecorded;
if unsafe || configs.referenceSource ~= "emgIntent" || ...
        configs.observationVariant ~= "intentMarkov60" || ...
        configs.actionInterfaceVariant ~= "baselineQuantized" || ...
        ~configs.quantizeCommandsForSimulation || configs.unifyActions || ...
        configs.conventionalController.type ~= "P" || ...
        any(configs.conventionalController.kd ~= 0) || ...
        any(configs.conventionalController.maxAction > 64 / 255 + eps)
    error("run_no_glove_stage5_plant_diagnostic:UnsafeConfig", ...
        "Effective configuration violates the ETAPA 5 profile.");
end
end

function metrics = buildMetrics(results)
openLoop = results.openLoopTrials;
baseline = results.baselineScenarios;
nondegenerate = baseline(~baseline.isDegenerateAtPositionLimit, :);
motor2 = nondegenerate(nondegenerate.motor == 2, :);
otherMotors = nondegenerate(nondegenerate.motor ~= 2, :);
criticalOpenLoop = [ ...
    openLoop.finalEncoderDelta, ...
    openLoop.finalNormalizedDelta, ...
    openLoop.maxNormalizedSpeedPerSec, ...
    openLoop.encoder2FlexMappingRmse];
criticalBaseline = [ ...
    baseline.trackingMse, baseline.trackingMae, ...
    baseline.finalAbsoluteError, baseline.actionL2, ...
    baseline.deltaActionL2, baseline.saturationFraction];
metrics = struct( ...
    "openLoopTrialCount", height(openLoop), ...
    "plantConditionCount", height(results.plantByCondition), ...
    "closedLoopScenarioCount", height(baseline), ...
    "nondegenerateClosedLoopCount", height(nondegenerate), ...
    "finiteCriticalFraction", mean(isfinite([ ...
        criticalOpenLoop(:); criticalBaseline(:)])), ...
    "openLoopDirectionMismatchCount", sum(~openLoop.directionConsistent), ...
    "openLoopPositionViolationTrialCount", ...
        sum(openLoop.positionViolationFraction > 0), ...
    "openLoopCommandSaturationFraction", ...
        mean(openLoop.commandSaturation), ...
    "openLoopTimeDeadResolutionMinSec", ...
        min(openLoop.samplePeriodSec), ...
    "openLoopTimeDeadMovingMeanSec", ...
        mean(openLoop.timeDeadSec, "omitnan"), ...
    "encoder2FlexImplementationMaxAbs", max([ ...
        openLoop.encoder2FlexImplementationMaxAbs; ...
        baseline.encoder2FlexImplementationMaxAbs]), ...
    "crossMotorMaxNormalizedDelta", max([ ...
        openLoop.crossMotorMaxNormalizedDelta; ...
        baseline.crossMotorMaxNormalizedDelta]), ...
    "baselineTrackingMseMean", mean(nondegenerate.trackingMse), ...
    "baselineTrackingMaeMean", mean(nondegenerate.trackingMae), ...
    "baselineActionL2Mean", mean(nondegenerate.actionL2), ...
    "baselineDeltaActionL2Mean", mean(nondegenerate.deltaActionL2), ...
    "baselineSaturationFraction", ...
        mean(nondegenerate.saturationFraction), ...
    "baselineFunctionalFlagCount", sum(nondegenerate.functionalFlag), ...
    "motor2FunctionalFlagCount", sum(motor2.functionalFlag), ...
    "otherMotorFunctionalFlagCount", sum(otherMotors.functionalFlag), ...
    "motor2WrongDirectionFlagCount", sum(motor2.wrongDirectionFlag), ...
    "hardwareUsed", false, ...
    "simulatorUsed", true, ...
    "reinforcementLearningUsed", false);
end

function assertStage5Metrics(metrics)
if metrics.openLoopTrialCount ~= 112 || ...
        metrics.plantConditionCount ~= 16 || ...
        metrics.closedLoopScenarioCount ~= 32 || ...
        metrics.nondegenerateClosedLoopCount ~= 24 || ...
        metrics.finiteCriticalFraction ~= 1 || ...
        metrics.encoder2FlexImplementationMaxAbs > 1e-12 || ...
        metrics.crossMotorMaxNormalizedDelta > 1e-12 || ...
        metrics.baselineSaturationFraction ~= 0 || ...
        metrics.hardwareUsed || ~metrics.simulatorUsed || ...
        metrics.reinforcementLearningUsed
    error("run_no_glove_stage5_plant_diagnostic:GateFailed", ...
        "At least one ETAPA 5 reproducibility gate failed.");
end
end

function createOpenLoopFigure(results, outputPath)
f = figure("Visible", "off", "Color", "w", ...
    "Position", [100, 100, 1400, 900]);
tiledlayout(f, 2, 2, "TileSpacing", "compact", "Padding", "compact");
for motorIdx = 1:4
    ax = nexttile;
    hold(ax, "on");
    for direction = [-1, 1]
        row = results.openLoopTrials( ...
            results.openLoopTrials.initialMode == "intermediate" & ...
            results.openLoopTrials.motor == motorIdx & ...
            results.openLoopTrials.direction == direction & ...
            results.openLoopTrials.requestedPwmMagnitude == 255, :);
        trace = results.openLoopTraces{row.traceIndex(1)};
        plot(ax, trace.time, trace.normalizedEncoder(:, motorIdx), ...
            "LineWidth", 1.4, ...
            "DisplayName", compose("PWM %+d", trace.appliedPwm));
    end
    yline(ax, 0, "k:", "HandleVisibility", "off");
    yline(ax, 1, "k:", "HandleVisibility", "off");
    grid(ax, "on");
    title(ax, "Motor " + motorIdx + " desde intermedia");
    xlabel(ax, "Tiempo [s]");
    ylabel(ax, "Encoder normalizado");
    legend(ax, "Location", "best");
end
sgtitle(f, "Planta sin modificar: escalones PWM máximos");
exportgraphics(f, outputPath, "Resolution", 180);
close(f);
end

function createBaselineFigure(results, outputPath)
f = figure("Visible", "off", "Color", "w", ...
    "Position", [100, 100, 1400, 900]);
tiledlayout(f, 2, 2, "TileSpacing", "compact", "Padding", "compact");
styles = ["-", "--"];
colors = lines(2);
for motorIdx = 1:4
    ax = nexttile;
    hold(ax, "on");
    for profileIdx = 1:2
        profileName = ["step", "ramp"];
        row = results.baselineScenarios( ...
            results.baselineScenarios.initialMode == "intermediate" & ...
            results.baselineScenarios.motor == motorIdx & ...
            results.baselineScenarios.profile == profileName(profileIdx) & ...
            results.baselineScenarios.direction == 1, :);
        trace = results.baselineTraces{row.traceIndex(1)};
        plot(ax, trace.time(2:end), ...
            trace.qReference(:, motorIdx), ...
            ":", "Color", colors(profileIdx, :), ...
            "HandleVisibility", "off");
        plot(ax, trace.time(2:end), ...
            trace.normalizedEncoder(2:end, motorIdx), ...
            styles(profileIdx), "Color", colors(profileIdx, :), ...
            "LineWidth", 1.4, "DisplayName", profileName(profileIdx));
    end
    grid(ax, "on");
    title(ax, "Motor " + motorIdx + " cierre");
    xlabel(ax, "Tiempo [s]");
    ylabel(ax, "q / q_{ref}");
    legend(ax, "Location", "best");
end
sgtitle(f, "Baseline P cuantizado; referencia punteada");
exportgraphics(f, outputPath, "Resolution", 180);
close(f);
end

function writeOfflineReport(reportPath, metrics, results, calibration, runDir)
motor2 = results.baselineByMotor(results.baselineByMotor.motor == 2, :);
motor3 = results.baselineByMotor(results.baselineByMotor.motor == 3, :);
lines = [ ...
    "# ETAPA 5 baseline convencional y diagnóstico de planta"; ...
    ""; ...
    "- Resultado de ejecución: PASS."; ...
    "- Barridos abiertos: " + metrics.openLoopTrialCount + "."; ...
    "- Escenarios cerrados: " + metrics.closedLoopScenarioCount + "."; ...
    "- Retardo medio detectado: " + compose("%.9g", ...
        metrics.openLoopTimeDeadMovingMeanSec) + " s, limitado por la " + ...
        "resolución del simulador."; ...
    "- Inconsistencias de dirección en planta: " + ...
        metrics.openLoopDirectionMismatchCount + "."; ...
    "- Trials con salida del rango [0,1]: " + ...
        metrics.openLoopPositionViolationTrialCount + "."; ...
    "- Flags baseline Motor 2: " + motor2.functionalFlagCount + ...
        ", dirección incorrecta: " + motor2.wrongDirectionFlagCount + "."; ...
    "- Flags baseline Motor 3: " + motor3.functionalFlagCount + "."; ...
    "- Movimiento cruzado máximo: " + compose("%.12g", ...
        metrics.crossMotorMaxNormalizedDelta) + "."; ...
    "- Residuo implementación encoder2Flex: " + compose("%.12g", ...
        metrics.encoder2FlexImplementationMaxAbs) + "."; ...
    "- Checksum calibración: `" + calibration.contentSha256 + "`."; ...
    "- Hardware/RL: no/no. Simulador: sí."; ...
    ""; ...
    "Los flags son hallazgos de la planta/baseline, no fallos ocultados ni " + ...
        "calibraciones aplicadas."; ...
    ""; ...
    "Ruta: `" + string(runDir) + "`." ...
    ];
writeText(reportPath, strjoin(lines, newline));
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end

function [commit, dirty] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status ~= 0
    commit = "unknown";
else
    commit = string(strtrim(output));
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
dirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function hash = fileSha256(filePath)
if ispc
    escapedPath = strrep(char(filePath), "'", "''");
    command = sprintf([ ...
        'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
        '-LiteralPath ''%s'').Hash"'], escapedPath);
else
    command = sprintf('sha256sum "%s"', char(filePath));
end
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage5_plant_diagnostic:HashFailed", ...
        "Could not calculate SHA-256 for %s.", filePath);
end
tokens = split(strtrim(string(output)));
hash = upper(tokens(1));
end

function writeText(filePath, content)
fid = fopen(filePath, "w");
if fid < 0
    error("run_no_glove_stage5_plant_diagnostic:WriteFailed", ...
        "Could not open %s for writing.", filePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s\n", content);
end
