function report = run_no_glove_stage6_training(options)
%run_no_glove_stage6_training runs one bounded ETAPA 6 training phase.
%
% Phases are intentionally separate. This launcher never advances from
% smoke to pilot or from pilot to campaign on its own.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
protocol = resolveProtocol(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
addpath(genpath(fullfile(matlabRoot, "tests")));

if options.phase == "pilot"
    assertPriorPhaseAuthorization(options.smokeManifestPath, "smoke");
elseif options.phase == "campaign"
    assertPriorPhaseAuthorization(options.pilotManifestPath, "pilot");
end
if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage6_" + options.phase);
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage6_training:OutputExists", ...
        "Refusing to reuse output directory %s.", runRoot);
end
mkdir(runRoot);

clearConfigurablesOverride();
rng(options.calibrationSeed, "twister");
testResults = runtests(fullfile(matlabRoot, "tests", "no_glove"), ...
    "IncludeSubfolders", true);
save(fullfile(runRoot, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage6_training:TestsFailed", ...
        "No-glove tests failed; training is forbidden. See %s.", runRoot);
end

corpus = buildNoGloveStage6SyntheticCorpus(options.calibrationSeed);
fixtureDir = fullfile(runRoot, "fixture");
mkdir(fixtureDir);
[trainingDatasetPath, evaluationDatasetPath, restDatasetPath] = ...
    writeCorpusDatasets(fixtureDir, corpus);
calibration = corpus.calibration;
expectedContext = corpus.expectedContext;
save(fullfile(fixtureDir, "intent_calibration.mat"), ...
    "calibration", "expectedContext");
writeText(fullfile(fixtureDir, "intent_calibration.json"), ...
    jsonencode(calibration, "PrettyPrint", true));

seedRows = repmat(emptySeedRow(), numel(protocol.seeds), 1);
seedResults = cell(numel(protocol.seeds), 1);
allCheckpointRows = cell(numel(protocol.seeds), 1);
for seedIdx = 1:numel(protocol.seeds)
    seed = protocol.seeds(seedIdx);
    seedRoot = fullfile(runRoot, sprintf("seed_%d", seed));
    trainingBase = fullfile(seedRoot, "training");
    mkdir(trainingBase);
    profile = buildNoGloveStage6Override( ...
        calibration, expectedContext, seed, protocol.episodes, ...
        protocol.saveEvery, trainingDatasetPath, trainingBase);
    profile.intentRewardActionWeight = options.intentRewardActionWeight;
    if options.intentHoldRewardEnabled
        profile.rewardType = "trackingIntentHoldActionReward";
        profile.intentHoldActionWeight = options.intentHoldActionWeight;
        profile.intentHoldVelocityTolerance = ...
            options.intentHoldVelocityTolerance;
        profile.intentHoldPositionMseTolerance = ...
            options.intentHoldPositionMseTolerance;
    end
    if options.positionSafetyAblation
        profile.simulationPositionSafety = ...
            buildNoGloveSimulationPositionSafety(calibration, true);
    end
    assertSafeTrainingProfile(profile, protocol, ...
        options.positionSafetyAblation, options);
    save(fullfile(seedRoot, "effective_training_profile.mat"), ...
        "profile", "protocol", "options");

    setConfigurablesOverride(profile);
    trainInterface("td3_no_glove_intent", "", "");
    clearConfigurablesOverride();
    trainingDir = findNewestSubdir(trainingBase);
    trainingAnalysis = analyzeExperimentRun(trainingDir, ...
        fullfile(seedRoot, "training_progress.png"));
    trainingSafety = analyzeNoGloveStage6Evaluation(trainingDir, ...
        "positionMin", calibration.limits.positionMin, ...
        "positionMax", calibration.limits.positionMax);
    checkpointTable = inventoryCheckpoints( ...
        trainingDir, seed, protocol.episodes);
    allCheckpointRows{seedIdx} = checkpointTable;
    finalCheckpoint = string(checkpointTable.checkpointPath( ...
        checkpointTable.isFinal));
    if numel(finalCheckpoint) ~= 1
        error("run_no_glove_stage6_training:MissingFinalCheckpoint", ...
            "Expected exactly one final checkpoint for seed %d.", seed);
    end

    acceptanceDir = runEvaluation( ...
        profile, finalCheckpoint, evaluationDatasetPath, ...
        fullfile(seedRoot, "acceptance"), ...
        options.evaluationSeed, options.evaluationSimulations);
    restDir = runEvaluation( ...
        profile, finalCheckpoint, restDatasetPath, ...
        fullfile(seedRoot, "steady_rest"), ...
        options.evaluationSeed, options.restSimulations);
    acceptance = analyzeNoGloveStage6Evaluation(acceptanceDir, ...
        "positionMin", calibration.limits.positionMin, ...
        "positionMax", calibration.limits.positionMax);
    rest = analyzeNoGloveStage6Evaluation(restDir, ...
        "positionMin", calibration.limits.positionMin, ...
        "positionMax", calibration.limits.positionMax);
    gate = classifyNoGloveStage6Gate( ...
        acceptance, rest, corpus.restFalseActivationFraction, trainingSafety);

    seedRows(seedIdx) = buildSeedRow( ...
        seed, protocol, trainingDir, finalCheckpoint, checkpointTable, ...
        trainingAnalysis, trainingSafety, acceptanceDir, acceptance, ...
        restDir, rest, gate);
    seedResult = struct( ...
        "seed", seed, ...
        "trainingDirectory", trainingDir, ...
        "finalCheckpoint", finalCheckpoint, ...
        "checkpointInventory", checkpointTable, ...
        "trainingAnalysis", trainingAnalysis, ...
        "trainingSafety", trainingSafety, ...
        "acceptanceDirectory", acceptanceDir, ...
        "acceptance", acceptance, ...
        "restDirectory", restDir, ...
        "rest", rest, ...
        "gate", gate);
    seedResults{seedIdx} = seedResult;
    save(fullfile(seedRoot, "seed_result.mat"), ...
        "seedResult");
end

seedTable = struct2table(seedRows);
checkpointTable = vertcat(allCheckpointRows{:});
writetable(seedTable, fullfile(runRoot, "seed_summary.csv"));
writetable(checkpointTable, fullfile(runRoot, "checkpoint_inventory.csv"));
phaseGatePassed = all(seedTable.gatePassed);
distribution = summarizeDistribution(seedTable);
writetable(struct2table(distribution), ...
    fullfile(runRoot, "multiseed_distribution.csv"));

[gitCommit, gitDirty] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", 6, ...
    "schemaVersion", 1, ...
    "phase", options.phase, ...
    "result", conditionalString(phaseGatePassed, "PASS", "PARTIAL"), ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, ...
    "gitDirty", gitDirty, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage6_training", ...
    "protocol", protocol, ...
    "seeds", protocol.seeds, ...
    "phaseGatePassed", phaseGatePassed, ...
    "calibrationSeed", options.calibrationSeed, ...
    "calibrationContentSha256", calibration.contentSha256, ...
    "calibrationDataProvenance", corpus.dataProvenance, ...
    "corpusFixtureVersion", corpus.fixtureVersion, ...
    "trainingDatasetPath", trainingDatasetPath, ...
    "trainingDatasetSha256", fileSha256(trainingDatasetPath), ...
    "evaluationDatasetPath", evaluationDatasetPath, ...
    "evaluationDatasetSha256", fileSha256(evaluationDatasetPath), ...
    "restDatasetPath", restDatasetPath, ...
    "restDatasetSha256", fileSha256(restDatasetPath), ...
    "restFalseActivationFraction", corpus.restFalseActivationFraction, ...
    "restWindowCount", corpus.restWindowCount, ...
    "referenceSource", "emgIntent", ...
    "observationVariant", "intentMarkov60", ...
    "stateLength", 60, ...
    "rewardType", conditionalString(options.intentHoldRewardEnabled, ...
        "trackingIntentHoldActionReward", ...
        "trackingIntentActionRateReward"), ...
    "intentRewardPositionWeight", 1.00, ...
    "intentRewardVelocityWeight", 0.00, ...
    "intentRewardActionWeight", options.intentRewardActionWeight, ...
    "intentRewardDeltaActionWeight", 0.05, ...
    "intentRewardSaturationWeight", 0.02, ...
    "intentRewardSoftActionLimit", 0.90, ...
    "intentHoldRewardEnabled", options.intentHoldRewardEnabled, ...
    "intentHoldActionWeight", options.intentHoldActionWeight, ...
    "intentHoldVelocityTolerance", ...
        options.intentHoldVelocityTolerance, ...
    "intentHoldPositionMseTolerance", ...
        options.intentHoldPositionMseTolerance, ...
    "actionInterfaceVariant", "baselineQuantized", ...
    "simulationPositionSafety", ...
        buildNoGloveSimulationPositionSafety( ...
            calibration, options.positionSafetyAblation), ...
    "positionSafetyAblation", options.positionSafetyAblation, ...
    "actorCriticArchitecture", "feedforward", ...
    "agentId", "td3_no_glove_intent", ...
    "newTraining", true, ...
    "checkpointLoadedForTraining", "", ...
    "agent7250Loaded", false, ...
    "agent7250UsedAsStartingPoint", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "reinforcementLearningUsed", true, ...
    "runTraining", true, ...
    "simMotors", true, ...
    "simulatorUsed", true, ...
    "usePrerecorded", true, ...
    "connectGlove", false, ...
    "hardwareUsed", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "priorGateManifestPath", resolvePriorManifestPath(options), ...
    "seedSummary", seedRows, ...
    "distribution", distribution, ...
    "outputPath", runRoot);
save(fullfile(runRoot, "stage6_results.mat"), ...
    "manifest", "seedResults", "seedTable", "checkpointTable", ...
    "distribution", "protocol", "options");
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
writeOfflineReport(fullfile(runRoot, "stage6_report.md"), manifest);

report = struct( ...
    "result", manifest.result, ...
    "phase", options.phase, ...
    "phaseGatePassed", phaseGatePassed, ...
    "outputPath", runRoot, ...
    "manifest", manifest, ...
    "seedTable", seedTable, ...
    "checkpointTable", checkpointTable, ...
    "seedResults", seedResults);
fprintf("ETAPA 6 %s %s\n", upper(options.phase), manifest.result);
fprintf("Output: %s\n", runRoot);
disp(seedTable);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage6_training:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "phase", "smoke", ...
    "resultsRoot", "", ...
    "calibrationSeed", 11, ...
    "evaluationSeed", 7601, ...
    "evaluationSimulations", 50, ...
    "restSimulations", 24, ...
    "smokeManifestPath", "", ...
    "pilotManifestPath", "", ...
    "positionSafetyAblation", false, ...
    "intentRewardActionWeight", 0.01, ...
    "intentHoldRewardEnabled", false, ...
    "intentHoldActionWeight", 0.00, ...
    "intentHoldVelocityTolerance", 1e-12, ...
    "intentHoldPositionMseTolerance", 1e-4);
allowed = string(fieldnames(defaults));
unknown = setdiff(string(fieldnames(options)), allowed);
if ~isempty(unknown)
    error("run_no_glove_stage6_training:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
fields = fieldnames(defaults);
for fieldIdx = 1:numel(fields)
    name = fields{fieldIdx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.phase = string(options.phase);
options.resultsRoot = string(options.resultsRoot);
options.smokeManifestPath = string(options.smokeManifestPath);
options.pilotManifestPath = string(options.pilotManifestPath);
if ~islogical(options.positionSafetyAblation) || ...
        ~isscalar(options.positionSafetyAblation)
    error("run_no_glove_stage6_training:InvalidSafetyAblationOption", ...
        "positionSafetyAblation must be a scalar logical value.");
end
if ~islogical(options.intentHoldRewardEnabled) || ...
        ~isscalar(options.intentHoldRewardEnabled)
    error("run_no_glove_stage6_training:InvalidHoldRewardOption", ...
        "intentHoldRewardEnabled must be a scalar logical value.");
end
if ~isnumeric(options.intentRewardActionWeight) || ...
        ~isscalar(options.intentRewardActionWeight) || ...
        ~isfinite(options.intentRewardActionWeight) || ...
        options.intentRewardActionWeight < 0
    error("run_no_glove_stage6_training:InvalidRewardActionWeight", ...
        "intentRewardActionWeight must be finite and nonnegative.");
end
holdFields = ["intentHoldActionWeight", ...
    "intentHoldVelocityTolerance", ...
    "intentHoldPositionMseTolerance"];
for fieldIdx = 1:numel(holdFields)
    name = holdFields(fieldIdx);
    value = options.(name);
    if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) || ...
            ~isfinite(value) || value < 0
        error("run_no_glove_stage6_training:InvalidHoldRewardValue", ...
            "%s must be a finite nonnegative scalar.", name);
    end
end
if ~isscalar(options.phase) || ...
        ~any(options.phase == ["smoke", "pilot", "campaign"])
    error("run_no_glove_stage6_training:InvalidPhase", ...
        "phase must be smoke, pilot or campaign.");
end
numericIntegerFields = ["calibrationSeed", "evaluationSeed", ...
    "evaluationSimulations", "restSimulations"];
for fieldIdx = 1:numel(numericIntegerFields)
    name = numericIntegerFields(fieldIdx);
    value = options.(name);
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
            value < 0 || fix(value) ~= value
        error("run_no_glove_stage6_training:InvalidIntegerOption", ...
            "%s must be a nonnegative integer.", name);
    end
end
if options.evaluationSimulations == 0 || options.restSimulations == 0
    error("run_no_glove_stage6_training:EmptyEvaluation", ...
        "Evaluation simulation counts must be positive.");
end
end

function protocol = resolveProtocol(options)
switch options.phase
    case "smoke"
        protocol = struct("phase", "smoke", "episodes", 200, ...
            "seeds", 11, "saveEvery", 50);
    case "pilot"
        protocol = struct("phase", "pilot", "episodes", 2000, ...
            "seeds", [11, 22, 33], "saveEvery", 200);
    case "campaign"
        protocol = struct("phase", "campaign", "episodes", 12000, ...
            "seeds", [11, 22, 33, 44, 55], "saveEvery", 1000);
end
end

function assertPriorPhaseAuthorization(manifestPath, expectedPhase)
if strlength(manifestPath) == 0 || ~isfile(manifestPath)
    error("run_no_glove_stage6_training:MissingPriorGateManifest", ...
        "%s requires a published %s manifest.", ...
        upper(nextPhase(expectedPhase)), expectedPhase);
end
prior = jsondecode(fileread(manifestPath));
if string(prior.phase) ~= expectedPhase || ...
        ~logical(prior.phaseGatePassed)
    error("run_no_glove_stage6_training:PriorGateFailed", ...
        "%s is forbidden unless the %s gate passed.", ...
        upper(nextPhase(expectedPhase)), expectedPhase);
end
end

function phase = nextPhase(previousPhase)
if previousPhase == "smoke"
    phase = "pilot";
else
    phase = "campaign";
end
end

function [trainingPath, evaluationPath, restPath] = ...
        writeCorpusDatasets(fixtureDir, corpus)
trainingPath = fullfile(fixtureDir, "stage6_training_emg_only.mat");
evaluationPath = fullfile(fixtureDir, "stage6_evaluation_emg_only.mat");
restPath = fullfile(fixtureDir, "stage6_steady_rest_emg_only.mat");
emgs = corpus.trainingEmgs;
metadata = corpus.trainingMetadata;
save(trainingPath, "emgs", "metadata");
emgs = corpus.evaluationEmgs;
metadata = corpus.evaluationMetadata;
save(evaluationPath, "emgs", "metadata");
emgs = corpus.restEmgs;
metadata = corpus.restMetadata;
save(restPath, "emgs", "metadata");
end

function assertSafeTrainingProfile( ...
        profile, protocol, expectedSafetyEnabled, options)
expectedRewardType = conditionalString(options.intentHoldRewardEnabled, ...
    "trackingIntentHoldActionReward", ...
    "trackingIntentActionRateReward");
holdSettingsMatch = ~options.intentHoldRewardEnabled || ( ...
    isfield(profile, "intentHoldActionWeight") && ...
    isfield(profile, "intentHoldVelocityTolerance") && ...
    isfield(profile, "intentHoldPositionMseTolerance") && ...
    profile.intentHoldActionWeight == options.intentHoldActionWeight && ...
    profile.intentHoldVelocityTolerance == ...
        options.intentHoldVelocityTolerance && ...
    profile.intentHoldPositionMseTolerance == ...
        options.intentHoldPositionMseTolerance);
safe = profile.run_training && profile.newTraining && ...
    strlength(string(profile.agentFile)) == 0 && ...
    string(profile.agent_id) == "td3_no_glove_intent" && ...
    profile.referenceSource == "emgIntent" && ...
    profile.observationVariant == "intentMarkov60" && ...
    profile.rewardType == expectedRewardType && ...
    profile.actionInterfaceVariant == "baselineQuantized" && ...
    profile.usePrerecorded && profile.simMotors && ...
    ~profile.connect_glove && ~profile.td3.useRecurrent && ...
    ~profile.td3Residual.enabled && ...
    profile.simulationPositionSafety.enabled == expectedSafetyEnabled && ...
    string(profile.simulationPositionSafety.mode) == ...
        "clipTrajectoryOutput" && ...
    profile.intentRewardPositionWeight == 1.00 && ...
    profile.intentRewardVelocityWeight == 0.00 && ...
    profile.intentRewardActionWeight == options.intentRewardActionWeight && ...
    profile.intentRewardDeltaActionWeight == 0.05 && ...
    profile.intentRewardSaturationWeight == 0.02 && ...
    profile.intentRewardSoftActionLimit == 0.90 && ...
    holdSettingsMatch && ...
    profile.trainingMaxEpisodes == protocol.episodes;
if ~safe
    error("run_no_glove_stage6_training:UnsafeTrainingProfile", ...
        "ETAPA 6 training profile violates an invariant.");
end
end

function evaluationDir = runEvaluation( ...
        trainingProfile, checkpointPath, datasetPath, evaluationBase, ...
        evaluationSeed, simulationCount)
mkdir(evaluationBase);
[datasetFolder, datasetStem] = fileparts(datasetPath);
profile = trainingProfile;
profile.run_training = false;
profile.newTraining = false;
profile.agentFile = checkpointPath;
profile.agent_id = "td3_no_glove_intent";
profile.randomSeed = evaluationSeed;
profile.dataset = {char(string(datasetStem))};
profile.dataset_folder = string(datasetFolder);
profile.flagSaveTraining = true;
profile.episode_save_freq = 1;
profile.plotEpisodeOnTest = false;
profile.simOpts = rlSimulationOptions( ...
    "MaxSteps", profile.maxNumberStepsInEpisodes, ...
    "NumSimulations", simulationCount, ...
    "StopOnError", "on", ...
    "UseParallel", false);
profile.agents_directory = @(agent_id, variant) fullfile( ...
    evaluationBase, string(datetime("now", "Format", "yy-MM-dd HH m s")));
setConfigurablesOverride(profile);
trainInterface("td3_no_glove_intent", "", "");
clearConfigurablesOverride();
evaluationDir = findNewestSubdir(evaluationBase);
end

function checkpointTable = inventoryCheckpoints(trainingDir, seed, finalEpisode)
files = dir(fullfile(trainingDir, "Agent*.mat"));
if isempty(files)
    error("run_no_glove_stage6_training:NoCheckpoints", ...
        "Training produced no checkpoints in %s.", trainingDir);
end
episode = zeros(numel(files), 1);
path = strings(numel(files), 1);
sha256 = strings(numel(files), 1);
bytes = zeros(numel(files), 1);
for fileIdx = 1:numel(files)
    token = regexp(files(fileIdx).name, '^Agent(\d+)\.mat$', ...
        'tokens', 'once');
    if isempty(token)
        error("run_no_glove_stage6_training:UnexpectedCheckpointName", ...
            "Unexpected checkpoint %s.", files(fileIdx).name);
    end
    episode(fileIdx) = str2double(token{1});
    path(fileIdx) = string(fullfile(files(fileIdx).folder, files(fileIdx).name));
    sha256(fileIdx) = fileSha256(path(fileIdx));
    bytes(fileIdx) = files(fileIdx).bytes;
end
[episode, order] = sort(episode);
path = path(order);
sha256 = sha256(order);
bytes = bytes(order);
checkpointTable = table( ...
    repmat(seed, numel(files), 1), episode, path, sha256, bytes, ...
    episode == finalEpisode, ...
    'VariableNames', {'seed', 'episode', 'checkpointPath', ...
    'checkpointSha256', 'bytes', 'isFinal'});
end

function row = emptySeedRow()
row = struct( ...
    "seed", 0, "episodeBudget", 0, "checkpointCount", 0, ...
    "trainingDirectory", "", "finalCheckpoint", "", ...
    "trainingAverageRewardFinal", NaN, ...
    "trainingPositionViolationEpisodeCount", 0, ...
    "trainingPositionSafetyInterventionCount", 0, ...
    "acceptanceDirectory", "", "trackingMse", NaN, ...
    "trackingMae", NaN, "velocityMse", NaN, "actionL2", NaN, ...
    "deltaActionL2", NaN, "saturationFraction", NaN, ...
    "positionViolationEpisodeCount", 0, ...
    "acceptancePositionSafetyInterventionCount", 0, ...
    "motor2FunctionalFlagCount", 0, ...
    "otherMotorFunctionalFlagCount", 0, ...
    "restDirectory", "", "restSaturationFraction", NaN, ...
    "restFalseActivationFraction", NaN, "gatePassed", false);
end

function row = buildSeedRow( ...
        seed, protocol, trainingDir, finalCheckpoint, checkpointTable, ...
        trainingAnalysis, trainingSafety, acceptanceDir, acceptance, ...
        restDir, rest, gate)
row = emptySeedRow();
row.seed = seed;
row.episodeBudget = protocol.episodes;
row.checkpointCount = height(checkpointTable);
row.trainingDirectory = trainingDir;
row.finalCheckpoint = finalCheckpoint;
if isfield(trainingAnalysis.trainingSummary, "averageRewardFinal")
    row.trainingAverageRewardFinal = ...
        trainingAnalysis.trainingSummary.averageRewardFinal;
end
row.trainingPositionViolationEpisodeCount = ...
    trainingSafety.positionViolationEpisodeCount;
row.trainingPositionSafetyInterventionCount = ...
    trainingSafety.positionSafetyInterventionCount;
row.acceptanceDirectory = acceptanceDir;
row.trackingMse = acceptance.trackingMse;
row.trackingMae = acceptance.trackingMae;
row.velocityMse = acceptance.velocityMse;
row.actionL2 = acceptance.actionL2;
row.deltaActionL2 = acceptance.deltaActionL2;
row.saturationFraction = acceptance.saturationFraction;
row.positionViolationEpisodeCount = ...
    acceptance.positionViolationEpisodeCount;
row.acceptancePositionSafetyInterventionCount = ...
    acceptance.positionSafetyInterventionCount;
row.motor2FunctionalFlagCount = acceptance.motor2FunctionalFlagCount;
row.otherMotorFunctionalFlagCount = ...
    acceptance.otherMotorFunctionalFlagCount;
row.restDirectory = restDir;
row.restSaturationFraction = rest.saturationFraction;
row.restFalseActivationFraction = gate.restFalseActivationFraction;
row.gatePassed = gate.passed;
end

function distribution = summarizeDistribution(seedTable)
distribution = struct( ...
    "seedCount", height(seedTable), ...
    "trackingMseMean", mean(seedTable.trackingMse), ...
    "trackingMseStd", std(seedTable.trackingMse), ...
    "trackingMaeMean", mean(seedTable.trackingMae), ...
    "trackingMaeStd", std(seedTable.trackingMae), ...
    "actionL2Mean", mean(seedTable.actionL2), ...
    "actionL2Std", std(seedTable.actionL2), ...
    "deltaActionL2Mean", mean(seedTable.deltaActionL2), ...
    "deltaActionL2Std", std(seedTable.deltaActionL2), ...
    "saturationFractionMean", mean(seedTable.saturationFraction), ...
    "saturationFractionStd", std(seedTable.saturationFraction), ...
    "restSaturationFractionMean", ...
        mean(seedTable.restSaturationFraction), ...
    "trainingPositionSafetyInterventionCount", ...
        sum(seedTable.trainingPositionSafetyInterventionCount), ...
    "acceptancePositionSafetyInterventionCount", ...
        sum(seedTable.acceptancePositionSafetyInterventionCount), ...
    "gatePassCount", sum(seedTable.gatePassed));
end

function newestDir = findNewestSubdir(parentDir)
info = dir(parentDir);
info = info([info.isdir]);
info = info(~ismember({info.name}, {'.', '..'}));
if isempty(info)
    error("run_no_glove_stage6_training:MissingOutputDirectory", ...
        "No output directory found under %s.", parentDir);
end
[~, idx] = max([info.datenum]);
newestDir = string(fullfile(info(idx).folder, info(idx).name));
end

function [commit, dirty] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
dirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function hash = fileSha256(filePath)
escaped = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escaped);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage6_training:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = string(strtrim(output));
end

function value = conditionalString(condition, trueValue, falseValue)
if condition
    value = string(trueValue);
else
    value = string(falseValue);
end
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
reproRoot = string(fileparts(runRoot));
authorizationOption = "";
if options.phase == "pilot"
    authorizationOption = sprintf(",'smokeManifestPath','%s'", ...
        strrep(char(options.smokeManifestPath), "'", "''"));
elseif options.phase == "campaign"
    authorizationOption = sprintf(",'pilotManifestPath','%s'", ...
        strrep(char(options.pilotManifestPath), "'", "''"));
end
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage6_training(struct('phase','%s'," + ...
    "'resultsRoot','%s','calibrationSeed',%d," + ...
    "'evaluationSeed',%d,'evaluationSimulations',%d," + ...
    "'restSimulations',%d,'positionSafetyAblation',%s," + ...
    "'intentRewardActionWeight',%.17g," + ...
    "'intentHoldRewardEnabled',%s,'intentHoldActionWeight',%.17g," + ...
    "'intentHoldVelocityTolerance',%.17g," + ...
    "'intentHoldPositionMseTolerance',%.17g%s))", ...
    strrep(char(matlabRoot), "'", "''"), options.phase, ...
    strrep(char(reproRoot), "'", "''"), options.calibrationSeed, ...
    options.evaluationSeed, options.evaluationSimulations, ...
    options.restSimulations, mat2str(options.positionSafetyAblation), ...
    options.intentRewardActionWeight, ...
    mat2str(options.intentHoldRewardEnabled), ...
    options.intentHoldActionWeight, ...
    options.intentHoldVelocityTolerance, ...
    options.intentHoldPositionMseTolerance, ...
    authorizationOption);
end

function manifestPath = resolvePriorManifestPath(options)
if options.phase == "pilot"
    manifestPath = options.smokeManifestPath;
elseif options.phase == "campaign"
    manifestPath = options.pilotManifestPath;
else
    manifestPath = "";
end
end

function writeOfflineReport(reportPath, manifest)
lines = strings(0, 1);
lines(end+1) = "# ETAPA 6 " + upper(manifest.phase);
lines(end+1) = "";
lines(end+1) = "- Resultado del gate: " + manifest.result + ".";
lines(end+1) = sprintf("- Episodios por seed: %d.", ...
    manifest.protocol.episodes);
lines(end+1) = "- Seeds: [" + strjoin(string(manifest.seeds), ",") + "].";
lines(end+1) = "- Calibración sintética: `" + ...
    manifest.calibrationContentSha256 + "`.";
lines(end+1) = "- Agent7250 cargado/usado: no/no.";
lines(end+1) = "- Ablación de límites de posición: " + ...
    string(manifest.positionSafetyAblation) + ".";
lines(end+1) = "- Hardware: no; simulador: sí.";
lines(end+1) = "- Métricas por seed: `seed_summary.csv`.";
writeText(reportPath, strjoin(lines, newline));
end

function writeText(filePath, value)
fid = fopen(filePath, "w");
if fid < 0
    error("run_no_glove_stage6_training:WriteFailed", ...
        "Could not open %s.", filePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
