function report = run_no_glove_stage7u_motion_permission_ablation(options)
%run_no_glove_stage7u_motion_permission_ablation audits a motionPermission
%gate inserted between u_actor_raw and quantization, using only already
%recorded ETAPA 7S/7N logs. No actor is loaded, no Env/simulator is run, no
%training happens.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));
clearConfigurablesOverride();

testFiles = fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage7uMotionPermissionAblation.m");
testResults = runtests(testFiles);
if ~all([testResults.Passed])
    error("run_no_glove_stage7u_motion_permission_ablation:TestsFailed", ...
        "ETAPA 7U tests failed.");
end

data = loadNoGloveStage7uEvidence( ...
    "stage7sRunRoot", options.stage7sRunRoot, ...
    "acceptanceEpisodeDirectory", options.acceptanceEpisodeDirectory);
analysis = analyzeNoGloveStage7uMotionPermission(data);

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7u_motion_permission_ablation");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7u_motion_permission_ablation:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

writetable(analysis.restTable, fullfile(runRoot, "rest_component_table.csv"));
writetable(analysis.acceptanceStepTable, ...
    fullfile(runRoot, "acceptance_step_table.csv"));
if height(analysis.falseInhibitionViolations) > 0
    writetable(analysis.falseInhibitionViolations, ...
        fullfile(runRoot, "false_inhibition_violations.csv"));
end

operationalChecks = struct( ...
    "restGateActiveAllFalse", analysis.restGateActiveAllFalse, ...
    "falseInhibitionExactlyZero", ...
        analysis.acceptanceSummary.falseInhibitionExactlyZero, ...
    "actorNotLoaded", ~data.actorLoaded && ~analysis.actorLoaded, ...
    "actorNotRetrained", ~data.actorRetrained && ~analysis.actorRetrained, ...
    "noEnvironment", ~data.environmentUsed && ~analysis.environmentUsed, ...
    "noNewSimulation", ~data.simulationUsed && ~analysis.simulationUsed, ...
    "noTraining", ~data.trainingUsed && ~analysis.trainingUsed, ...
    "noHardware", ~data.hardwareUsed, ...
    "quantizationNotRecomputed", ~analysis.quantizationRecomputed, ...
    "safetyNotRecomputed", ~analysis.safetyRecomputed, ...
    "rewardUnchanged", ~analysis.rewardChanged, ...
    "gateUnchanged", ~analysis.gateChanged, ...
    "stateUnchanged", ~analysis.stateChanged, ...
    "datasetUnchanged", ~analysis.datasetChanged);
writetable(struct2table(operationalChecks), ...
    fullfile(runRoot, "operational_checks.csv"));
if ~all(struct2array(operationalChecks))
    error("run_no_glove_stage7u_motion_permission_ablation:OperationalGate", ...
        "An ETAPA 7U operational invariant failed.");
end

[gitCommit, gitDirty] = getGitState(repoRoot);
manifest = struct( ...
    "stage", "7U", "schemaVersion", 1, "result", "PASS", ...
    "improvementValidated", analysis.improvementValidated, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7u_motion_permission_ablation", ...
    "preregistrationDoc", "07u_preregistration.md", ...
    "restCohort", struct( ...
        "gateActiveAllFalse", analysis.restGateActiveAllFalse, ...
        "baseline", analysis.restSummary.baseline, ...
        "gated", analysis.restSummary.gated), ...
    "acceptanceCohort", analysis.acceptanceSummary, ...
    "operationalChecks", operationalChecks, ...
    "actorLoaded", false, "actorRetrained", false, ...
    "environmentUsed", false, "simulationUsed", false, ...
    "trainingUsed", false, "hardwareUsed", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);
save(fullfile(runRoot, "stage7u_results.mat"), ...
    "manifest", "analysis", "operationalChecks", "options", "-v7.3");
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "improvementValidated", analysis.improvementValidated, ...
    "outputPath", runRoot, "manifest", manifest, "analysis", analysis);
fprintf("ETAPA 7U MOTION-PERMISSION ABLATION PASS\n");
fprintf("Improvement validated: %s\n", analysis.improvementValidated);
fprintf("Rest gated PWM!=0 fraction: %.6f (baseline %.6f)\n", ...
    analysis.restSummary.gated.restPWMNonZeroFraction, ...
    analysis.restSummary.baseline.restPWMNonZeroFraction);
fprintf("Acceptance false-inhibition steps: %d of %d\n", ...
    analysis.acceptanceSummary.falseInhibitionStepCount, ...
    analysis.acceptanceSummary.totalSteps);
fprintf("Output: %s\n", runRoot);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7u_motion_permission_ablation:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "resultsRoot", "", ...
    "stage7sRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7s_artifacts\stage7s_final\2026-08-31_22-58-01-555", ...
    "acceptanceEpisodeDirectory", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7n_artifacts\stage7n_corrected_final\2026-08-29_07-34-46-814\checkpoint_evaluations\control60\episode_200\acceptance\26-08-29 07 36 5");
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7u_motion_permission_ablation:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.stage7sRunRoot = string(options.stage7sRunRoot);
options.acceptanceEpisodeDirectory = string(options.acceptanceEpisodeDirectory);
end

function [commit, dirty] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
dirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7u_motion_permission_ablation:WriteFailed", ...
        "Could not write %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
