function report = run_no_glove_stage2_offline_validation(options)
%run_no_glove_stage2_offline_validation validates ETAPA 2 offline.
%
% This launcher does not construct Env, load an agent, train, call the
% simulator or access hardware. It uses a labelled deterministic synthetic
% fixture because the published dataset lacks rest and thumb-opposition
% calibration instructions.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage2_offline");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runDir)
    error("run_no_glove_stage2_offline_validation:OutputExists", ...
        "Refusing to reuse existing output directory %s.", runDir);
end
mkdir(runDir);

clearConfigurablesOverride();
rng(options.seed, "twister");
testPath = fullfile(matlabRoot, "tests", "no_glove", ...
    "testEmgIntentOffline.m");
testResults = runtests(testPath);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage2_offline_validation:TestsFailed", ...
        "At least one ETAPA 2 offline test failed. See %s.", runDir);
end

config = buildNoGloveStage2OfflineConfig(options.seed);
assertSafeOfflineConfig(config);
dataset = buildSyntheticEmgIntentDataset(config);
calibration = calibrateEmgIntent(dataset.restCapture, ...
    dataset.instructionTrials, config.calibrationOptions);
calibrationOptions = config.calibrationOptions;
expectedUnits = struct( ...
    "rawEmg", dataset.restCapture.rawEmgUnits, ...
    "envelope", calibrationOptions.envelopeUnits, ...
    "position", calibrationOptions.positionUnits, ...
    "velocity", calibrationOptions.velocityUnits, ...
    "acceleration", calibrationOptions.accelerationUnits);
expectedContext = struct( ...
    "userId", dataset.restCapture.userId, ...
    "sessionId", dataset.restCapture.sessionId, ...
    "channelOrder", dataset.restCapture.channelOrder, ...
    "sampleRateHz", dataset.restCapture.sampleRateHz, ...
    "windowLengthSamples", dataset.windowLengthSamples, ...
    "hopLengthSamples", dataset.hopLengthSamples, ...
    "dataProvenance", dataset.restCapture.dataProvenance, ...
    "motorOrder", calibrationOptions.motorOrder, ...
    "units", expectedUnits, ...
    "synergyMatrixVersion", ...
        calibrationOptions.synergyMatrixVersion, ...
    "instructionProtocolVersion", ...
        calibrationOptions.instructionProtocolVersion, ...
    "sourceDomain", "rawEmgSameSession", ...
    "calibrationContentSha256", calibration.contentSha256);
calibrationValidation = validateIntentCalibration( ...
    calibration, expectedContext);
if ~calibrationValidation.isValid
    error("run_no_glove_stage2_offline_validation:InvalidCalibration", ...
        "Calibration validation failed: %s", ...
        strjoin(calibrationValidation.issues, "; "));
end

[intentVelocity, intent, finalGateState, decoderDetails] = ...
    mapEmgToIntentVelocity(dataset.evaluationRawEmg, calibration, ...
    expectedContext);
restMask = ~decoderDetails.gateActive;
[referenceHistory, appliedVelocity, finalReferenceState, ...
    referenceDiagnostics] = updateIntentReference( ...
    dataset.initialEncoder, intentVelocity, calibration, restMask);

% Historical 40-feature path is computed and saved independently. It never
% feeds envelope normalization or the decoder.
featureProfile = buildNoGloveStage1Override(options.seed);
setConfigurablesOverride(featureProfile);
featureConfigs = configurables();
assertSafeFeatureProfile(featureConfigs);
wmoosFeatures40 = computeWmoosFeatureHistory( ...
    dataset.evaluationRawEmg, dataset.windowLengthSamples, ...
    featureConfigs.fGetFeatures);
clearConfigurablesOverride();

metrics = computeMetrics(dataset, calibration, intent, intentVelocity, ...
    decoderDetails, referenceHistory, appliedVelocity, ...
    referenceDiagnostics, wmoosFeatures40);
assertOfflineGates(metrics, calibration);
scenarioMetrics = buildScenarioMetrics(dataset, intent, intentVelocity, ...
    decoderDetails, referenceHistory, appliedVelocity);
intentTrace = buildIntentTrace(dataset, intent, intentVelocity, ...
    decoderDetails, referenceHistory, appliedVelocity);

effectiveConfigPath = fullfile(runDir, "effective_config.mat");
save(effectiveConfigPath, "config", "featureProfile", "expectedContext");
datasetPath = fullfile(runDir, "synthetic_calibration_dataset.mat");
save(datasetPath, "dataset");
calibrationPath = fullfile(runDir, "intent_calibration.mat");
save(calibrationPath, "calibration", "calibrationValidation");
writeText(fullfile(runDir, "intent_calibration.json"), ...
    jsonencode(calibration, "PrettyPrint", true));

calibrationChannels = table( ...
    calibration.channelOrder(:), ...
    calibration.baselineMedian(:), ...
    calibration.signalLevel(:), ...
    calibration.restEnvelopeMad(:), ...
    calibration.requiredSignalRange(:), ...
    calibration.activeChannelMask(:), ...
    calibration.decoder.W(1, :)', ...
    calibration.decoder.W(2, :)', ...
    'VariableNames', cellstr(["channel", "baselineMedian", "signalLevel", ...
    "restEnvelopeMad", "requiredSignalRange", "active", "W1", "W2"]));
writetable(calibrationChannels, ...
    fullfile(runDir, "calibration_channels.csv"));
decoderW = array2table(calibration.decoder.W, ...
    'VariableNames', cellstr(calibration.channelOrder), ...
    'RowNames', {'closureOpening', 'thumbOpposition'});
writetable(decoderW, fullfile(runDir, "decoder_W.csv"), ...
    'WriteRowNames', true);
synergyB = array2table(calibration.synergy.matrix, ...
    'VariableNames', {'closureOpening', 'thumbOpposition'}, ...
    'RowNames', cellstr(calibration.motorOrder));
writetable(synergyB, fullfile(runDir, "synergy_B.csv"), ...
    'WriteRowNames', true);
writetable(intentTrace, fullfile(runDir, "intent_trace.csv"));
writetable(scenarioMetrics, fullfile(runDir, "scenario_metrics.csv"));
wmoosTable = array2table(wmoosFeatures40, ...
    'VariableNames', cellstr("wmoos" + (1:40)));
wmoosTable.windowIndex = (1:height(wmoosTable))';
wmoosTable = movevars(wmoosTable, "windowIndex", "Before", 1);
writetable(wmoosTable, fullfile(runDir, "wmoos_features40.csv"));

offlineResultsPath = fullfile(runDir, "offline_results.mat");
save(offlineResultsPath, "metrics", "scenarioMetrics", "intentTrace", ...
    "wmoosFeatures40", "intent", "intentVelocity", ...
    "decoderDetails", "referenceHistory", "appliedVelocity", ...
    "finalGateState", "finalReferenceState", "referenceDiagnostics");
figurePath = fullfile(runDir, "intent_offline_report.png");
createOfflineFigure(figurePath, dataset, intent, decoderDetails, ...
    appliedVelocity, referenceHistory);
reportPath = fullfile(runDir, "offline_report.md");
writeOfflineReport(reportPath, metrics, calibration, runDir);

reproducibleCommand = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage2_offline_validation(struct('seed',%d," + ...
    "'resultsRoot','%s'))", ...
    strrep(char(matlabRoot), "'", "''"), options.seed, ...
    strrep(char(options.resultsRoot), "'", "''"));
writeText(fullfile(runDir, "reproducible_command.txt"), ...
    reproducibleCommand);

primaryArtifacts = [ ...
    "effective_config.mat", "synthetic_calibration_dataset.mat", ...
    "intent_calibration.mat", "intent_calibration.json", ...
    "calibration_channels.csv", "decoder_W.csv", "synergy_B.csv", ...
    "intent_trace.csv", "scenario_metrics.csv", ...
    "wmoos_features40.csv", "offline_results.mat", ...
    "test_results.mat", "intent_offline_report.png", "offline_report.md", ...
    "reproducible_command.txt"];
artifactHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(primaryArtifacts), 1);
for artifactIdx = 1:numel(primaryArtifacts)
    artifactHashes(artifactIdx).path = primaryArtifacts(artifactIdx);
    artifactHashes(artifactIdx).sha256 = fileSha256( ...
        fullfile(runDir, primaryArtifacts(artifactIdx)));
end
artifactHashTable = struct2table(artifactHashes);
writetable(artifactHashTable, fullfile(runDir, "artifact_hashes.csv"));

[gitCommit, gitDirty] = getGitState(repoRoot);
normValuesPath = fullfile(matlabRoot, "config", "normValues.mat");
manifest = struct( ...
    "stage", 2, ...
    "schemaVersion", 1, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, ...
    "gitDirty", gitDirty, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage2_offline_validation", ...
    "reproducibleCommand", string(reproducibleCommand), ...
    "seed", options.seed, ...
    "dataProvenance", config.dataProvenance, ...
    "fixtureVersion", config.fixtureVersion, ...
    "userId", calibration.userId, ...
    "sessionId", calibration.sessionId, ...
    "channelOrder", calibration.channelOrder, ...
    "sampleRateHz", calibration.sampleRateHz, ...
    "windowLengthSamples", calibration.windowLengthSamples, ...
    "hopLengthSamples", calibration.hopLengthSamples, ...
    "calibrationContentSha256", calibration.contentSha256, ...
    "synergyMatrixVersion", calibration.synergy.version, ...
    "synergyMatrix", calibration.synergy.matrix, ...
    "motorOrder", calibration.motorOrder, ...
    "restGate", calibration.restGate, ...
    "limits", calibration.limits, ...
    "effectiveConfigSha256", fileSha256(effectiveConfigPath), ...
    "normValuesPath", normValuesPath, ...
    "normValuesSha256", fileSha256(normValuesPath), ...
    "referenceSource", "emgIntent", ...
    "wmoosUsedForIntent", false, ...
    "wmoosFeaturesComputedSeparately", true, ...
    "runTraining", false, ...
    "reinforcementLearningUsed", false, ...
    "simMotors", true, ...
    "simulatorUsed", false, ...
    "usePrerecorded", true, ...
    "connectGlove", false, ...
    "hardwareUsed", false, ...
    "checkpointUsed", "", ...
    "agent7250Used", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "testsIncomplete", sum([testResults.Incomplete]), ...
    "metrics", metrics, ...
    "artifactHashes", artifactHashes, ...
    "artifactHashesCsvSha256", fileSha256( ...
        fullfile(runDir, "artifact_hashes.csv")), ...
    "outputPath", runDir);
save(fullfile(runDir, "manifest.mat"), "manifest", "metrics", ...
    "artifactHashes");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct( ...
    "result", "PASS", ...
    "outputPath", runDir, ...
    "manifest", manifest, ...
    "metrics", metrics, ...
    "scenarioMetrics", scenarioMetrics, ...
    "testResults", testResults);

fprintf("ETAPA 2 offline validation PASS\n");
fprintf("Output: %s\n", runDir);
disp(struct2table(metrics));
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage2_offline_validation:InvalidOptions", ...
        "options must be a scalar struct.");
end
allowedFields = ["seed", "resultsRoot"];
unknownFields = setdiff(string(fieldnames(options)), allowedFields);
if ~isempty(unknownFields)
    error("run_no_glove_stage2_offline_validation:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknownFields, ", "));
end
defaults = struct("seed", 11, "resultsRoot", "");
defaultFields = fieldnames(defaults);
for fieldIdx = 1:numel(defaultFields)
    fieldName = defaultFields{fieldIdx};
    if ~isfield(options, fieldName) || isempty(options.(fieldName))
        options.(fieldName) = defaults.(fieldName);
    end
end
if ~isnumeric(options.seed) || ~isreal(options.seed) || ...
        ~isscalar(options.seed) || ~isfinite(options.seed) || ...
        options.seed < 0 || fix(options.seed) ~= options.seed
    error("run_no_glove_stage2_offline_validation:InvalidSeed", ...
        "seed must be a nonnegative integer.");
end
options.resultsRoot = string(options.resultsRoot);
if ~isscalar(options.resultsRoot) || ismissing(options.resultsRoot)
    error("run_no_glove_stage2_offline_validation:InvalidResultsRoot", ...
        "resultsRoot must be a scalar string or character vector.");
end
end

function assertSafeOfflineConfig(config)
safe = config.stage == 2 && config.dataProvenance == "synthetic" && ...
    config.referenceSource == "emgIntent" && config.simMotors && ...
    ~config.connectGlove && config.usePrerecorded && ...
    ~config.runTraining && ~config.newTraining && ...
    ~config.simulatorUsed && ~config.hardwareUsed && ...
    ~config.reinforcementLearningUsed && ~config.agent7250Used && ...
    ~config.wmoosUsedForIntent;
if ~safe
    error("run_no_glove_stage2_offline_validation:UnsafeConfig", ...
        "The ETAPA 2 configuration must remain offline and hardware-free.");
end
end

function assertSafeFeatureProfile(configs)
safe = ~configs.run_training && ~configs.newTraining && ...
    configs.usePrerecorded && configs.simMotors && ...
    ~configs.connect_glove && configs.referenceSource == "emgIntent";
if ~safe
    error("run_no_glove_stage2_offline_validation:UnsafeFeatureProfile", ...
        "The isolated historical-feature profile is unsafe.");
end
end

function features = computeWmoosFeatureHistory(rawEmg, windowLength, calculator)
windowCount = floor(size(rawEmg, 1) / windowLength);
features = zeros(windowCount, 40);
for windowIdx = 1:windowCount
    rows = (windowIdx - 1) * windowLength + (1:windowLength);
    featureColumn = calculator(rawEmg(rows, :));
    if ~isequal(size(featureColumn), [40, 1]) || ...
            ~isreal(featureColumn) || any(~isfinite(featureColumn))
        error("run_no_glove_stage2_offline_validation:InvalidWmoosFeatures", ...
            "Historical feature window %d is not a finite 40-vector.", ...
            windowIdx);
    end
    features(windowIdx, :) = featureColumn';
end
end

function metrics = computeMetrics(dataset, calibration, intent, intentVelocity, ...
        details, qRef, vRef, referenceDiagnostics, wmoosFeatures40)
allValues = [details.envelope(:); details.normalizedActivation(:); ...
    details.decodedIntent(:); intent(:); intentVelocity(:); ...
    qRef(:); vRef(:); wmoosFeatures40(:)];
initialVelocity = zeros(1, 4);
acceleration = diff([initialVelocity; vRef], 1, 1) ./ ...
    calibration.limits.deltaT;
positionBelow = qRef < calibration.limits.positionMin - 1e-12;
positionAbove = qRef > calibration.limits.positionMax + 1e-12;
velocityExceeded = abs(vRef) > calibration.limits.velocityMax + 1e-12;
accelerationExceeded = abs(acceleration) > ...
    calibration.limits.accelerationMax + 1e-12;
activationExceeded = details.normalizedActivation < -1e-12 | ...
    details.normalizedActivation > 1 + 1e-12;
intentExceeded = abs(intent) > 1 + 1e-12;

previousQ = [dataset.initialEncoder; qRef(1:end-1, :)];
restRows = ~details.gateActive;
if any(restRows)
    restDrift = max(abs(qRef(restRows, :) - previousQ(restRows, :)), [], "all");
else
    restDrift = NaN;
end
isolatedRestNoise = ismember(dataset.evaluationWindowScenario, ...
    ["rest_initial", "transient_noise", "rest_after_noise"]);
falseActivationFraction = mean(details.gateActive(isolatedRestNoise));

movementRows = details.gateActive & ...
    any(dataset.evaluationExpectedDirection ~= 0, 2);
correct = false(sum(movementRows), 1);
movementIntent = intent(movementRows, :);
movementExpected = dataset.evaluationExpectedDirection(movementRows, :);
for rowIdx = 1:size(movementIntent, 1)
    instructedAxes = movementExpected(rowIdx, :) ~= 0;
    correct(rowIdx) = all(sign(movementIntent(rowIdx, instructedAxes)) == ...
        sign(movementExpected(rowIdx, instructedAxes)));
end
if isempty(correct)
    signedIntentAccuracy = NaN;
else
    signedIntentAccuracy = mean(correct);
end

metrics = struct( ...
    "windowCount", size(intent, 1), ...
    "finiteFraction", mean(isfinite(allValues)), ...
    "activeChannelCount", sum(calibration.activeChannelMask), ...
    "flatChannelCount", sum(calibration.flatChannelMask), ...
    "flatChannelMaxActivation", max(abs(details.normalizedActivation(:, ...
        calibration.flatChannelMask)), [], "all"), ...
    "decoderTrainingRmse", calibration.decoder.trainingRmse, ...
    "decoderActiveWeightRank", rank(calibration.decoder.W(:, ...
        calibration.activeChannelMask)), ...
    "synergyMatrixRank", rank(calibration.synergy.matrix), ...
    "activationViolationCount", sum(activationExceeded, "all"), ...
    "intentViolationCount", sum(intentExceeded, "all"), ...
    "velocityViolationCount", sum(velocityExceeded, "all"), ...
    "positionViolationCount", sum(positionBelow | positionAbove, "all"), ...
    "accelerationViolationCount", sum(accelerationExceeded, "all"), ...
    "restDriftMaxAbs", restDrift, ...
    "falseActivationFractionSynthetic", falseActivationFraction, ...
    "signedIntentAccuracySynthetic", signedIntentAccuracy, ...
    "referenceResetError", max(abs( ...
        referenceDiagnostics.initialPosition - dataset.initialEncoder)), ...
    "maxVelocityObserved", max(abs(vRef), [], "all"), ...
    "maxAccelerationObserved", max(abs(acceleration), [], "all"), ...
    "brakingLimitedFraction", mean(referenceDiagnostics.brakingLimited, "all"), ...
    "positionLimitedFraction", mean(referenceDiagnostics.positionLimited, "all"), ...
    "wmoosFeatureMin", min(wmoosFeatures40, [], "all"), ...
    "wmoosFeatureMax", max(wmoosFeatures40, [], "all"), ...
    "wmoosUsedForIntent", false, ...
    "hardwareUsed", false, ...
    "simulatorUsed", false, ...
    "reinforcementLearningUsed", false);
end

function assertOfflineGates(metrics, calibration)
passes = metrics.finiteFraction == 1 && ...
    metrics.activeChannelCount >= 2 && metrics.flatChannelMaxActivation == 0 && ...
    metrics.decoderActiveWeightRank == 2 && metrics.synergyMatrixRank == 2 && ...
    metrics.decoderTrainingRmse < 0.05 && ...
    metrics.activationViolationCount == 0 && ...
    metrics.intentViolationCount == 0 && metrics.velocityViolationCount == 0 && ...
    metrics.positionViolationCount == 0 && ...
    metrics.accelerationViolationCount == 0 && ...
    metrics.restDriftMaxAbs <= 1e-12 && ...
    metrics.falseActivationFractionSynthetic == 0 && ...
    metrics.signedIntentAccuracySynthetic == 1 && ...
    metrics.referenceResetError <= 1e-12 && ...
    metrics.maxVelocityObserved <= max(calibration.limits.velocityMax) + 1e-12 && ...
    metrics.maxAccelerationObserved <= ...
    max(calibration.limits.accelerationMax) + 1e-12;
if ~passes
    error("run_no_glove_stage2_offline_validation:GateFailed", ...
        "One or more deterministic ETAPA 2 offline gates failed.");
end
end

function scenarioMetrics = buildScenarioMetrics( ...
        dataset, intent, intentVelocity, details, qRef, vRef)
scenarioNames = unique(dataset.evaluationWindowScenario, "stable");
rows = repmat(struct( ...
    "scenario", "", "windowCount", 0, "meanActivity", NaN, ...
    "gateActiveFraction", NaN, "meanIntent1", NaN, "meanIntent2", NaN, ...
    "maxDecodedVelocityAbs", NaN, "maxAppliedVelocityAbs", NaN, ...
    "maxPerMotorReferenceRange", NaN), numel(scenarioNames), 1);
for scenarioIdx = 1:numel(scenarioNames)
    selected = dataset.evaluationWindowScenario == scenarioNames(scenarioIdx);
    selectedQ = qRef(selected, :);
    rows(scenarioIdx) = struct( ...
        "scenario", scenarioNames(scenarioIdx), ...
        "windowCount", sum(selected), ...
        "meanActivity", mean(details.activity(selected)), ...
        "gateActiveFraction", mean(details.gateActive(selected)), ...
        "meanIntent1", mean(intent(selected, 1)), ...
        "meanIntent2", mean(intent(selected, 2)), ...
        "maxDecodedVelocityAbs", max(abs(intentVelocity(selected, :)), [], "all"), ...
        "maxAppliedVelocityAbs", max(abs(vRef(selected, :)), [], "all"), ...
        "maxPerMotorReferenceRange", max( ...
        max(selectedQ, [], 1) - min(selectedQ, [], 1)));
end
scenarioMetrics = struct2table(rows);
end

function trace = buildIntentTrace( ...
        dataset, intent, intentVelocity, details, qRef, vRef)
windowCount = size(intent, 1);
trace = table( ...
    (1:windowCount)', dataset.evaluationWindowScenario, ...
    dataset.evaluationIntendedRest, details.activity, ...
    details.gateActive, details.lowActivityCountdown, ...
    details.onCount, details.offCount, ...
    'VariableNames', cellstr(["windowIndex", "scenario", "intendedRest", ...
    "activity", "gateActive", "lowActivityCountdown", ...
    "onCount", "offCount"]));
for channelIdx = 1:size(details.envelope, 2)
    trace.("envelope" + channelIdx) = details.envelope(:, channelIdx);
    trace.("activation" + channelIdx) = ...
        details.normalizedActivation(:, channelIdx);
end
for intentIdx = 1:2
    trace.("decodedIntent" + intentIdx) = ...
        details.decodedIntent(:, intentIdx);
    trace.("intent" + intentIdx) = intent(:, intentIdx);
end
for motorIdx = 1:4
    trace.("decodedVelocity" + motorIdx) = intentVelocity(:, motorIdx);
    trace.("appliedVelocity" + motorIdx) = vRef(:, motorIdx);
    trace.("reference" + motorIdx) = qRef(:, motorIdx);
end
end

function createOfflineFigure(figurePath, dataset, intent, details, vRef, qRef)
figureHandle = figure("Visible", "off", "Color", "white", ...
    "Position", [100, 100, 1300, 900]);
cleanup = onCleanup(@() close(figureHandle));
layout = tiledlayout(4, 1, "TileSpacing", "compact", "Padding", "compact");
windowIndex = (1:size(intent, 1))';

nexttile(layout);
plot(windowIndex, details.normalizedActivation, "LineWidth", 1);
ylabel("a_t");
ylim([-0.02, 1.02]);
title("Same-session normalized raw-EMG envelope (synthetic fixture)");
legend(cellstr(dataset.channelOrder), "Location", "eastoutside", ...
    "Interpreter", "none");
grid on;

nexttile(layout);
plot(windowIndex, intent, "LineWidth", 1.3);
hold on;
stairs(windowIndex, double(details.gateActive), "k--", "LineWidth", 1);
hold off;
ylabel("z_t / gate");
ylim([-1.05, 1.05]);
legend({"closure/opening", "thumb opposition", "gate active"}, ...
    "Location", "eastoutside");
grid on;

nexttile(layout);
plot(windowIndex, vRef, "LineWidth", 1.2);
ylabel("v_{ref}");
legend({"M1", "M2", "M3", "M4"}, "Location", "eastoutside");
grid on;

nexttile(layout);
plot(windowIndex, qRef, "LineWidth", 1.2);
xlabel("Causal 0.2 s window");
ylabel("q_{ref}");
ylim([-0.02, 1.02]);
legend({"M1", "M2", "M3", "M4"}, "Location", "eastoutside");
grid on;

title(layout, "ETAPA 2 offline EMG-intent validation; no RL/simulator/hardware");
exportgraphics(figureHandle, figurePath, "Resolution", 220);
end

function writeOfflineReport(reportPath, metrics, calibration, runDir)
lines = [ ...
    "# ETAPA 2: validación offline EMG-intención"; ...
    ""; ...
    "Resultado: **PASS**"; ...
    ""; ...
    "Este replay usa un fixture sintético determinista. No es evidencia de " + ...
        "separabilidad EMG humana ni de límites mecánicos validados."; ...
    ""; ...
    "- Fuente: EMG cruda sintética normalizada como Myo ADC; no WMoos."; ...
    "- Sinergias: r=2 (cierre/apertura y oposición/liberación del pulgar)."; ...
    "- B: `" + calibration.synergy.version + "`, explícita 4x2 y rango 2."; ...
    "- Checksum de calibración: `" + calibration.contentSha256 + "`."; ...
    "- Ventanas: " + metrics.windowCount + " de " + ...
        calibration.windowLengthSamples + " muestras a " + ...
        calibration.sampleRateHz + " Hz."; ...
    "- RMSE del ajuste sintético: " + compose("%.12f", ...
        metrics.decoderTrainingRmse) + "."; ...
    "- Activación falsa sintética en reposo/ruido aislado: " + ...
        compose("%.12f", metrics.falseActivationFractionSynthetic) + "."; ...
    "- Deriva máxima en reposo: " + ...
        compose("%.12g", metrics.restDriftMaxAbs) + "."; ...
    "- Violaciones posición/velocidad/aceleración: " + ...
        metrics.positionViolationCount + "/" + ...
        metrics.velocityViolationCount + "/" + ...
        metrics.accelerationViolationCount + "."; ...
    "- WMoos se guardó por separado; rango observado [" + ...
        compose("%.6f", metrics.wmoosFeatureMin) + ", " + ...
        compose("%.6f", metrics.wmoosFeatureMax) + ...
        "] y no fue tratado como amplitud [0,1]."; ...
    "- Hardware, simulador, RL y Agent7250 usados: no/no/no/no."; ...
    ""; ...
    "Ruta de artefactos: `" + string(runDir) + "`." ...
    ];
writeText(reportPath, strjoin(lines, newline));
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end

function [commit, dirty] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status ~= 0
    commit = "unknown";
else
    commit = string(strtrim(output));
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
dirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function hash = fileSha256(filePath)
if ispc
    escapedPath = strrep(char(filePath), "'", "''");
    command = sprintf([ ...
        'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
        '-LiteralPath ''%s'').Hash"'], escapedPath);
else
    command = sprintf('sha256sum "%s"', char(filePath));
end
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage2_offline_validation:HashFailed", ...
        "Could not calculate SHA-256 for %s.", filePath);
end
tokens = split(strtrim(string(output)));
hash = upper(tokens(1));
end

function writeText(filePath, content)
fid = fopen(filePath, "w");
if fid < 0
    error("run_no_glove_stage2_offline_validation:WriteFailed", ...
        "Could not open %s for writing.", filePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s\n", content);
end
