function report = run_no_glove_stage7q_command_attribution(options)
%run_no_glove_stage7q_command_attribution attributes frozen actor commands.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));

data = loadNoGloveStage7qCheckpointSet( ...
    options.stage7pRunRoot, options.stage7nRunRoot);
if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7q_command_attribution");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7q_command_attribution:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testFiles = [ ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7qCommandAttribution.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7pInterfaceDiagnostic.m")];
testResults = runtests(testFiles);
save(fullfile(runRoot, "preflight_test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7q_command_attribution:TestsFailed", ...
        "ETAPA 7Q tests failed. See %s.", runRoot);
end

states = double(data.primaryCorpus.states);
checkpointRows = data.checkpointTable;
sharedEvaluations = repmat(struct("episode", 0, "raw", [], ...
    "effective", [], "pwm", [], "gradients", []), 4, 1);
replayParts = cell(4, 1);
gradientAuditParts = cell(4, 1);
for checkpointIdx = 1:4
    checkpointEpisode = double(checkpointRows.episode(checkpointIdx));
    checkpointPath = string(checkpointRows.checkpointPath(checkpointIdx));
    agent = loadSavedAgent(checkpointPath);
    actor = getActor(agent);
    model = getModel(actor);
    raw = evaluateFrozenActorModelStates(model, states);
    gradients = evaluateFrozenActorStateGradients(model, states, ...
        "batchSize", options.gradientBatchSize);
    [effective, pwm] = quantizeRows(raw, data.actuator);
    sharedEvaluations(checkpointIdx) = struct( ...
        "episode", checkpointEpisode, "raw", raw, ...
        "effective", effective, "pwm", pwm, ...
        "gradients", gradients);

    own = data.ownCorpora(checkpointIdx).corpus;
    ownBatch = evaluateFrozenActorModelStates(model, own.states);
    [~, ownBatchPwm] = quantizeRows(ownBatch, data.actuator);
    sampleIndices = unique(round(linspace(1, size(own.states, 1), 8)));
    serialSample = evaluateFrozenActorStates(actor, ...
        own.states(sampleIndices, :));
    replayParts{checkpointIdx} = table(checkpointEpisode, ...
        size(own.states, 1), numel(sampleIndices), ...
        max(abs(ownBatch-own.rawAction), [], "all"), ...
        max(abs(serialSample-ownBatch(sampleIndices, :)), [], "all"), ...
        sum(ownBatchPwm ~= own.pwm, "all"), ...
        'VariableNames', ["checkpointEpisode", "evaluatedWindowCount", ...
        "serialSampleCount", "batchSavedMaximumError", ...
        "serialBatchSampleMaximumError", "pwmMismatchCount"]);
    gradientAuditParts{checkpointIdx} = auditGradients( ...
        model, states, gradients, checkpointEpisode, ...
        options.gradientFiniteDifferenceStep);
    clear agent actor model raw effective pwm gradients ownBatch ownBatchPwm
end
replayAudit = vertcat(replayParts{:});
gradientAudit = vertcat(gradientAuditParts{:});
writetable(replayAudit, fullfile(runRoot, "actor_replay_audit.csv"));
writetable(gradientAudit, fullfile(runRoot, "gradient_audit.csv"));
if any(replayAudit.batchSavedMaximumError > 1e-5) || ...
        any(replayAudit.serialBatchSampleMaximumError > 1e-5) || ...
        any(replayAudit.pwmMismatchCount ~= 0) || ...
        any(~gradientAudit.withinTolerance)
    error("run_no_glove_stage7q_command_attribution:ReplayGate", ...
        "Actor replay or gradient audit failed.");
end

analysis = analyzeNoGloveStage7qAttribution( ...
    data.primaryCorpus, sharedEvaluations, data.ownCorpora);
inputInventory = buildInputInventory(data, options);
writetable(data.checkpointInventory, ...
    fullfile(runRoot, "checkpoint_inventory.csv"));
writetable(inputInventory, fullfile(runRoot, "input_inventory.csv"));
writetable(analysis.primaryComponents, ...
    fullfile(runRoot, "primary_zero_demand_components.csv"));
writetable(analysis.gradientComponents, ...
    fullfile(runRoot, "gradient_components.csv"));
writetable(analysis.gradientSummary, ...
    fullfile(runRoot, "gradient_block_summary.csv"));
writetable(analysis.associationSummary, ...
    fullfile(runRoot, "block_association_summary.csv"));
writetable(analysis.temporalSummary, ...
    fullfile(runRoot, "temporal_contribution_summary.csv"));
writetable(analysis.priorActionSummary, ...
    fullfile(runRoot, "prior_action_summary.csv"));
writetable(analysis.sharedCheckpointSummary, ...
    fullfile(runRoot, "shared_checkpoint_summary.csv"));
writetable(analysis.ownCheckpointSummary, ...
    fullfile(runRoot, "own_checkpoint_summary.csv"));
writetable(analysis.blockDecisionAudit, ...
    fullfile(runRoot, "block_decision_audit.csv"));
writetable(analysis.decisionAudit, ...
    fullfile(runRoot, "decision_audit.csv"));

operationalChecks = struct( ...
    "stage7pValidated", data.stage7p.validated, ...
    "stage7nValidated", data.stage7n.validated, ...
    "allCheckpointHashesMatched", all( ...
        data.checkpointInventory.expectedSha256 == ...
        data.checkpointInventory.actualSha256), ...
    "state60Selected", analysis.stateDecision == "intentMarkov60", ...
    "state62Rejected", analysis.state62Disposition == ...
        "provisionallyRejected", ...
    "primaryCohortMatched", analysis.primaryComponentCount == 2064, ...
    "allReplayPassed", all(replayAudit.batchSavedMaximumError <= 1e-5) && ...
        all(replayAudit.serialBatchSampleMaximumError <= 1e-5) && ...
        all(replayAudit.pwmMismatchCount == 0), ...
    "allGradientAuditsPassed", all(gradientAudit.withinTolerance), ...
    "trainingLogsExcluded", ~data.trainingLogsUsed, ...
    "stateCounterfactualExcluded", ~analysis.stateCounterfactualUsed, ...
    "futureLeakageExcluded", ~analysis.futureLeakageUsed, ...
    "rewardUnchanged", true, "quantizationUnchanged", true, ...
    "td3Unchanged", true, "simulatorUnchanged", true, ...
    "safetyUnchanged", true, "gateUnchanged", true, ...
    "noTraining", true, "noEnvironment", true, ...
    "noSimulation", true, "noHardware", true, "noDtw", true);
if ~all(struct2array(operationalChecks))
    error("run_no_glove_stage7q_command_attribution:OperationalGate", ...
        "An ETAPA 7Q operational invariant failed.");
end
writetable(struct2table(operationalChecks), ...
    fullfile(runRoot, "operational_checks.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", "7Q", "schemaVersion", 1, "result", "PASS", ...
    "scientificResult", analysis.scientificResult, ...
    "stateDecision", analysis.stateDecision, ...
    "state62Disposition", analysis.state62Disposition, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7q_command_attribution", ...
    "preregistrationCommit", "61766bf3", ...
    "parentStage7p", compactParent(data.stage7p), ...
    "parentStage7n", compactParent(data.stage7n), ...
    "checkpoints", table2struct(data.checkpointInventory), ...
    "primaryComponentCount", analysis.primaryComponentCount, ...
    "primaryWindowCount", analysis.primaryWindowCount, ...
    "agent200OutwardComponentCount", ...
        analysis.agent200OutwardComponentCount, ...
    "decisionThresholds", decisionThresholds(), ...
    "operationalChecks", operationalChecks, ...
    "rewardChanged", false, "quantizationChanged", false, ...
    "td3Changed", false, "simulatorChanged", false, ...
    "safetyLayerChanged", false, "restGateChanged", false, ...
    "trainingUsed", false, "environmentUsed", false, ...
    "simulationUsed", false, "simMotors", true, ...
    "hardwareUsed", false, "myoUsed", false, ...
    "gloveUsed", false, "dtwCalculated", false, ...
    "stateCounterfactualUsed", false, ...
    "agent7250Loaded", false, "agent7250Used", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "state62CheckpointLoaded", false, ...
    "smokeAuthorized", false, "smokeExecuted", false, ...
    "pilotAuthorized", false, "pilotExecuted", false, ...
    "campaignAuthorized", false, "campaignExecuted", false, ...
    "futureAblationExecuted", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);

save(fullfile(runRoot, "stage7q_results.mat"), ...
    "manifest", "analysis", "sharedEvaluations", ...
    "replayAudit", "gradientAudit", "operationalChecks", ...
    "inputInventory", "options", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest, analysis));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.scientificResult, ...
    "stateDecision", analysis.stateDecision, ...
    "outputPath", runRoot, "manifest", manifest, ...
    "analysis", analysis);
fprintf("ETAPA 7Q COMMAND ATTRIBUTION PASS\n");
fprintf("Scientific result: %s\n", analysis.scientificResult);
fprintf("Primary components: %d\n", analysis.primaryComponentCount);
fprintf("Output: %s\n", runRoot);
disp(analysis.decisionAudit);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7q_command_attribution:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "resultsRoot", "", ...
    "stage7pRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7p_artifacts\stage7p_final\2026-08-29_23-15-59-803", ...
    "stage7nRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7n_artifacts\stage7n_corrected_final\2026-08-29_07-34-46-814", ...
    "gradientBatchSize", 512, ...
    "gradientFiniteDifferenceStep", 1e-3);
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7q_command_attribution:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.stage7pRunRoot = string(options.stage7pRunRoot);
options.stage7nRunRoot = string(options.stage7nRunRoot);
if ~isscalar(options.gradientBatchSize) || ...
        options.gradientBatchSize < 1 || ...
        fix(options.gradientBatchSize) ~= options.gradientBatchSize || ...
        ~isscalar(options.gradientFiniteDifferenceStep) || ...
        options.gradientFiniteDifferenceStep <= 0
    error("run_no_glove_stage7q_command_attribution:InvalidNumericOption", ...
        "Gradient options must be positive and batchSize integer.");
end
end

function [effective, pwm] = quantizeRows(raw, actuator)
effective = zeros(size(raw));
pwm = zeros(size(raw));
for row = 1:size(raw, 1)
    [effectiveValue, pwmValue] = quantizeBaselineAction(raw(row, :), ...
        actuator.maxPwm, actuator.activationThreshold, ...
        actuator.commandLevels);
    effective(row, :) = double(effectiveValue(:))';
    pwm(row, :) = double(pwmValue(:))';
end
end

function audit = auditGradients(model, states, fullGradients, ...
        checkpointEpisode, step)
indices = unique(round(linspace(1, size(states, 1), 8)));
analytic = fullGradients(indices, :, :);
finite = nan(size(analytic));
forwardSlope = nan(size(analytic));
backwardSlope = nan(size(analytic));
base = evaluateFrozenActorModelStates(model, states(indices, :));
for inputIdx = 1:60
    plus = states(indices, :);
    minus = states(indices, :);
    plus(:, inputIdx) = plus(:, inputIdx)+step;
    minus(:, inputIdx) = minus(:, inputIdx)-step;
    plusValue = evaluateFrozenActorModelStates(model, plus);
    minusValue = evaluateFrozenActorModelStates(model, minus);
    finite(:, :, inputIdx) = (plusValue-minusValue)./(2*step);
    forwardSlope(:, :, inputIdx) = (plusValue-base)./step;
    backwardSlope(:, :, inputIdx) = (base-minusValue)./step;
end
errorValue = abs(analytic-finite);
absoluteTolerance = 2e-4;
relativeTolerance = 5e-2;
tolerance = max(absoluteTolerance, relativeTolerance.*abs(analytic));
centralFailure = errorValue > tolerance;
nonsmooth = abs(forwardSlope-backwardSlope) > absoluteTolerance;
oneSidedError = min(abs(analytic-forwardSlope), ...
    abs(analytic-backwardSlope));
nonsmoothException = centralFailure & nonsmooth & ...
    oneSidedError <= tolerance;
unexplainedFailure = centralFailure & ~nonsmoothException;
audit = table(checkpointEpisode, numel(indices), step, ...
    absoluteTolerance, relativeTolerance, ...
    max(errorValue, [], "all"), max(tolerance, [], "all"), ...
    sum(centralFailure, "all"), sum(nonsmoothException, "all"), ...
    sum(unexplainedFailure, "all"), ~any(unexplainedFailure, "all"), ...
    'VariableNames', ["checkpointEpisode", "sampleCount", "step", ...
    "absoluteTolerance", "relativeTolerance", ...
    "maximumAbsoluteError", "maximumTolerance", ...
    "centralFailureCount", "nonsmoothExceptionCount", ...
    "unexplainedFailureCount", "withinTolerance"]);
end

function inventory = buildInputInventory(data, options)
category = strings(0, 1);
checkpointEpisode = zeros(0, 1);
source = strings(0, 1);
episode = zeros(0, 1);
filePath = strings(0, 1);
bytes = zeros(0, 1);
sha256 = strings(0, 1);
parentPaths = [ ...
    fullfile(options.stage7pRunRoot, "manifest.json"); ...
    fullfile(options.stage7pRunRoot, "stage7p_results.mat"); ...
    fullfile(options.stage7nRunRoot, "manifest.json"); ...
    fullfile(options.stage7nRunRoot, "checkpoint_summary.csv")];
for idx = 1:numel(parentPaths)
    [category, checkpointEpisode, source, episode, filePath, ...
        bytes, sha256] = appendInventory(category, checkpointEpisode, ...
        source, episode, filePath, bytes, sha256, "parent", 0, ...
        "", 0, parentPaths(idx));
end
for idx = 1:height(data.checkpointInventory)
    [category, checkpointEpisode, source, episode, filePath, ...
        bytes, sha256] = appendInventory(category, checkpointEpisode, ...
        source, episode, filePath, bytes, sha256, "checkpoint", ...
        data.checkpointInventory.episode(idx), "", 0, ...
        data.checkpointInventory.checkpointPath(idx));
end
for corpusIdx = 1:numel(data.ownCorpora)
    rows = data.ownCorpora(corpusIdx).corpus.inventory;
    for row = 1:height(rows)
        [category, checkpointEpisode, source, episode, filePath, ...
            bytes, sha256] = appendInventory(category, ...
            checkpointEpisode, source, episode, filePath, bytes, ...
            sha256, "episode", data.ownCorpora(corpusIdx).episode, ...
            rows.source(row), rows.episode(row), rows.filePath(row));
    end
end
inventory = table(category, checkpointEpisode, source, episode, ...
    filePath, bytes, sha256);
end

function [category, checkpointEpisode, source, episode, filePath, ...
        bytes, sha256] = appendInventory(category, checkpointEpisode, ...
        source, episode, filePath, bytes, sha256, newCategory, ...
        newCheckpoint, newSource, newEpisode, newPath)
info = dir(newPath);
category(end+1, 1) = string(newCategory);
checkpointEpisode(end+1, 1) = double(newCheckpoint);
source(end+1, 1) = string(newSource);
episode(end+1, 1) = double(newEpisode);
filePath(end+1, 1) = string(newPath);
bytes(end+1, 1) = info.bytes;
sha256(end+1, 1) = fileSha256(newPath);
end

function parent = compactParent(value)
parent = struct("runRoot", value.runRoot, ...
    "manifestSha256", value.manifestSha256, ...
    "gitCommit", string(value.manifest.gitCommit), ...
    "scientificResult", string(value.manifest.scientificResult), ...
    "validated", value.validated);
end

function thresholds = decisionThresholds()
thresholds = struct( ...
    "minimumMotorAgreement", 3, ...
    "minimumSensitivityShare", 0.50, ...
    "minimumSensitivityRatio", 2, ...
    "minimumAssociationR2", 0.25, ...
    "minimumAssociationMargin", 0.10, ...
    "minimumTemporalShare", 0.50, ...
    "latePwmRelativeIncrease", 0.25, ...
    "lateFractionIncrease", 0.10);
end

function hashes = inventoryArtifacts(runRoot)
names = ["preflight_test_results.mat", "checkpoint_inventory.csv", ...
    "input_inventory.csv", "actor_replay_audit.csv", ...
    "gradient_audit.csv", "primary_zero_demand_components.csv", ...
    "gradient_components.csv", "gradient_block_summary.csv", ...
    "block_association_summary.csv", ...
    "temporal_contribution_summary.csv", "prior_action_summary.csv", ...
    "shared_checkpoint_summary.csv", "own_checkpoint_summary.csv", ...
    "block_decision_audit.csv", "decision_audit.csv", ...
    "operational_checks.csv", "stage7q_results.mat", ...
    "offline_report.md", "reproducible_command.txt"];
hashes = repmat(struct("artifact", "", "sha256", ""), ...
    numel(names), 1);
for idx = 1:numel(names)
    path = fullfile(runRoot, names(idx));
    hashes(idx) = struct("artifact", names(idx), ...
        "sha256", fileSha256(path));
end
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7q_command_attribution(struct(" + ...
    "'resultsRoot','%s','stage7pRunRoot','%s'," + ...
    "'stage7nRunRoot','%s'))", escape(matlabRoot), ...
    escape(string(fileparts(runRoot))), ...
    escape(options.stage7pRunRoot), escape(options.stage7nRunRoot));
end

function value = buildOfflineReport(manifest, analysis)
decision = analysis.decisionAudit;
lines = [ ...
    "# ETAPA 7Q - atribucion offline de comandos"; ""; ...
    "- Resultado: PASS."; ...
    "- Resultado cientifico: `" + manifest.scientificResult + "`."; ...
    "- Estado: `intentMarkov60`; state62 rechazado provisionalmente."; ...
    sprintf("- Cohorte primaria: %d componentes en %d ventanas.", ...
        manifest.primaryComponentCount, manifest.primaryWindowCount); ...
    sprintf("- Ratio PWM Agent200/maximo anterior: %.9g.", ...
        decision.agent200ToEarlierMaxMeanAbsPwmRatio); ...
    sprintf("- Incremento outward Agent200: %.9g.", ...
        decision.agent200OutwardFractionIncrease); ...
    "- Entrenamiento/Env/simulacion/hardware/DTW: no/no/no/no/no."; ...
    ""; "No se ejecuto ninguna ablacion ni se autorizo smoke o piloto." ...
    ];
value = strjoin(lines, newline);
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function hash = fileSha256(filePath)
escaped = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escaped);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7q_command_attribution:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = string(strtrim(output));
end

function value = escape(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7q_command_attribution:WriteFailed", ...
        "Could not write %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
