function report = run_no_glove_stage7t_gate_stress_consequence_audit(options)
%run_no_glove_stage7t_gate_stress_consequence_audit audits frozen 7S logs.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));
clearConfigurablesOverride();

data = loadNoGloveStage7tEvidence(options.stage7sRunRoot);
if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", ...
        "stage7t_gate_stress_consequence_audit");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7t_gate_stress_consequence_audit:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testFiles = [ ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7tGateStressAudit.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7sProspectiveRestSupport.m")];
testResults = runtests(testFiles);
save(fullfile(runRoot, "preflight_test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7t_gate_stress_consequence_audit:TestsFailed", ...
        "ETAPA 7T tests failed. See %s.", runRoot);
end

frozenStates = data.corpus.states;
analysis = analyzeNoGloveStage7tGateStress(data);
if ~isequal(frozenStates, data.corpus.states)
    error("run_no_glove_stage7t_gate_stress_consequence_audit:StateMutation", ...
        "The audit changed a frozen state.");
end
inputInventory = buildInputInventory(data, options);

writetable(analysis.alignmentAudit, ...
    fullfile(runRoot, "causal_input_alignment.csv"));
writetable(analysis.captureUsage, ...
    fullfile(runRoot, "capture_usage.csv"));
writetable(analysis.componentTable, ...
    fullfile(runRoot, "command_components.csv"));
writetable(analysis.globalCommandSummary, ...
    fullfile(runRoot, "command_summary_global.csv"));
writetable(analysis.channelCommandSummary, ...
    fullfile(runRoot, "command_summary_by_channel.csv"));
writetable(analysis.sideCommandSummary, ...
    fullfile(runRoot, "command_summary_by_side.csv"));
writetable(analysis.poseCommandSummary, ...
    fullfile(runRoot, "command_summary_by_pose.csv"));
writetable(analysis.stepCommandSummary, ...
    fullfile(runRoot, "command_summary_by_step.csv"));
writetable(analysis.decision.channelAudit, ...
    fullfile(runRoot, "classification_channel_audit.csv"));
writetable(analysis.decision.motorAudit, ...
    fullfile(runRoot, "classification_motor_audit.csv"));
writetable(analysis.emgDistanceTable, ...
    fullfile(runRoot, "emg_nearest_acceptance.csv"));
writetable(analysis.emgDistanceSummary, ...
    fullfile(runRoot, "emg_distance_summary.csv"));
writetable(analysis.context.queryTable, ...
    fullfile(runRoot, "context_query_audit.csv"));
writetable(analysis.context.blockTable, ...
    fullfile(runRoot, "context_block_audit.csv"));
writetable(analysis.context.phaseSummary, ...
    fullfile(runRoot, "context_phase_summary.csv"));
writetable(analysis.context.stepSummary, ...
    fullfile(runRoot, "context_step_summary.csv"));
writetable(analysis.context.blockSummary, ...
    fullfile(runRoot, "context_block_summary.csv"));
writetable(inputInventory, fullfile(runRoot, "input_inventory.csv"));

operationalChecks = struct( ...
    "stage7sValidated", data.parentValidated, ...
    "scientificParentFailurePreserved", ...
        string(data.parentManifest.scientificResult) == ...
        "prospectiveSupportFailed", ...
    "state60Selected", analysis.stateDecision == "intentMarkov60", ...
    "state62Rejected", analysis.state62Disposition == ...
        "provisionallyRejected", ...
    "prospectiveStateCountExact", ...
        analysis.prospectiveStateCount == 1600, ...
    "prospectiveComponentCountExact", ...
        analysis.prospectiveComponentCount == 6400, ...
    "causalInputAlignment", analysis.alignmentPassed, ...
    "firstStepMechanicalInvariant", analysis.firstStepInvariant, ...
    "upperEquilibriumConsistent", ...
        analysis.equilibriumEndpoints.upperEquilibriumConsistent, ...
    "referenceFrozen", analysis.referenceFrozen, ...
    "statesUnchanged", isequal(frozenStates, data.corpus.states), ...
    "completeObservedStatesOnly", ...
        ~analysis.stateCounterfactualUsed && ~analysis.hybridStateUsed, ...
    "distanceOmissionNotActorInput", ...
        analysis.context.distanceBlockOmissionOnly && ...
        ~analysis.context.actorEvaluated, ...
    "actorsNotLoaded", ~data.actorsLoaded && ~analysis.actorLoaded, ...
    "actorNotEvaluated", ~analysis.actorEvaluated, ...
    "rewardUnchanged", ~analysis.rewardChanged, ...
    "quantizationUnchanged", ~analysis.quantizationChanged, ...
    "td3Unchanged", ~analysis.td3Changed, ...
    "simulatorUnchanged", ~analysis.simulatorChanged, ...
    "safetyUnchanged", ~analysis.safetyChanged, ...
    "gateUnchanged", ~analysis.gateChanged, ...
    "noTraining", ~analysis.trainingUsed, ...
    "noEnvironment", ~analysis.environmentUsed, ...
    "noNewSimulation", ~analysis.simulationUsed, ...
    "noHardware", ~analysis.hardwareUsed, ...
    "noDtw", ~analysis.dtwCalculated, ...
    "noPilot", true, "noCampaign", true);
if ~all(struct2array(operationalChecks))
    error("run_no_glove_stage7t_gate_stress_consequence_audit:OperationalGate", ...
        "An ETAPA 7T operational invariant failed.");
end
writetable(struct2table(operationalChecks), ...
    fullfile(runRoot, "operational_checks.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
firstGlobal = analysis.globalCommandSummary( ...
    analysis.globalCommandSummary.group == "firstStep" & ...
    analysis.globalCommandSummary.motor == 0, :);
postGlobal = analysis.globalCommandSummary( ...
    analysis.globalCommandSummary.group == "postFirst" & ...
    analysis.globalCommandSummary.motor == 0, :);
firstContext = analysis.context.phaseSummary( ...
    analysis.context.phaseSummary.group == "firstStep" & ...
    analysis.context.phaseSummary.motor == 0, :);
postContext = analysis.context.phaseSummary( ...
    analysis.context.phaseSummary.group == "postFirst" & ...
    analysis.context.phaseSummary.motor == 0, :);
emgGlobal = analysis.emgDistanceSummary( ...
    analysis.emgDistanceSummary.phase == "ALL" & ...
    analysis.emgDistanceSummary.dominantChannel == 0, :);
manifest = struct( ...
    "stage", "7T", "schemaVersion", 1, "result", "PASS", ...
    "scientificResult", analysis.scientificResult, ...
    "recommendation", analysis.recommendation, ...
    "stateDecision", analysis.stateDecision, ...
    "state62Disposition", analysis.state62Disposition, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", ...
        "run_no_glove_stage7t_gate_stress_consequence_audit", ...
    "preregistrationCommit", "61bb06ee", ...
    "parentStage7s", compactParent(data), ...
    "prospectiveStateCount", analysis.prospectiveStateCount, ...
    "prospectiveComponentCount", analysis.prospectiveComponentCount, ...
    "firstStep", table2struct(firstGlobal), ...
    "postFirst", table2struct(postGlobal), ...
    "firstStepContext", table2struct(firstContext), ...
    "postFirstContext", table2struct(postContext), ...
    "emgDistance", table2struct(emgGlobal), ...
    "passedChannelCount", analysis.decision.passedChannelCount, ...
    "passedMotorCount", analysis.decision.passedMotorCount, ...
    "minimumNonzeroAbsolutePwm", ...
        analysis.minimumNonzeroAbsolutePwm, ...
    "firstStepLowerEndpointFraction", ...
        analysis.firstStepLowerEndpointFraction, ...
    "firstStepUpperEndpointFraction", ...
        analysis.firstStepUpperEndpointFraction, ...
    "equilibriumEndpoints", analysis.equilibriumEndpoints, ...
    "simulationSafetyInterventionCount", ...
        analysis.simulationSafetyInterventionCount, ...
    "contextQueryCount", analysis.context.queryCount, ...
    "contextFullMatchCount", analysis.context.fullMatchCount, ...
    "captureCountUsed", sum(analysis.captureUsage.used), ...
    "operationalChecks", operationalChecks, ...
    "rewardChanged", false, "quantizationChanged", false, ...
    "td3Changed", false, "simulatorChanged", false, ...
    "safetyLayerChanged", false, "restGateChanged", false, ...
    "trainingUsed", false, "environmentUsed", false, ...
    "simulationUsed", false, "simMotors", true, ...
    "hardwareUsed", false, "myoUsed", false, ...
    "gloveUsed", false, "dtwCalculated", false, ...
    "stateCounterfactualUsed", false, "hybridStateUsed", false, ...
    "agentCheckpointsLoaded", false, "actorEvaluated", false, ...
    "agent7250Loaded", false, "agent7250Used", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "smokeAuthorized", false, "smokeExecuted", false, ...
    "pilotAuthorized", false, "pilotExecuted", false, ...
    "campaignAuthorized", false, "campaignExecuted", false, ...
    "futureAblationExecuted", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);

save(fullfile(runRoot, "stage7t_results.mat"), ...
    "manifest", "analysis", "operationalChecks", ...
    "inputInventory", "options", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.scientificResult, ...
    "recommendation", analysis.recommendation, ...
    "stateDecision", analysis.stateDecision, ...
    "outputPath", runRoot, "manifest", manifest, ...
    "analysis", analysis);
fprintf("ETAPA 7T GATE-STRESS CONSEQUENCE AUDIT PASS\n");
fprintf("Scientific result: %s\n", analysis.scientificResult);
fprintf("Recommendation: %s\n", analysis.recommendation);
fprintf("Output: %s\n", runRoot);
disp(firstGlobal);
disp(postContext);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7t_gate_stress_consequence_audit:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "resultsRoot", "", ...
    "stage7sRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7s_artifacts\stage7s_final\2026-08-31_22-58-01-555");
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7t_gate_stress_consequence_audit:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.stage7sRunRoot = string(options.stage7sRunRoot);
end

function inventory = buildInputInventory(data, options)
category = strings(0, 1);
source = strings(0, 1);
episode = zeros(0, 1);
filePath = strings(0, 1);
bytes = zeros(0, 1);
sha256 = strings(0, 1);
parentPaths = [ ...
    fullfile(options.stage7sRunRoot, "manifest.json"); ...
    fullfile(options.stage7sRunRoot, "stage7s_results.mat"); ...
    fullfile(options.stage7sRunRoot, "acquisition_lock.mat"); ...
    fullfile(options.stage7sRunRoot, "dataset_design.mat"); ...
    string(data.parentManifest.datasetPath); data.configsPath];
for idx = 1:numel(parentPaths)
    [category, source, episode, filePath, bytes, sha256] = ...
        appendInventory(category, source, episode, filePath, bytes, ...
        sha256, "parent", "", 0, parentPaths(idx));
end
for idx = 1:height(data.restEpisodeInventory)
    row = data.restEpisodeInventory(idx, :);
    [category, source, episode, filePath, bytes, sha256] = ...
        appendInventory(category, source, episode, filePath, bytes, ...
        sha256, "episode", row.source, row.episode, row.filePath);
end
inventory = table(category, source, episode, filePath, bytes, sha256);
end

function [category, source, episode, filePath, bytes, sha256] = ...
        appendInventory(category, source, episode, filePath, bytes, ...
        sha256, newCategory, newSource, newEpisode, newPath)
info = dir(newPath);
if isempty(info)
    error("run_no_glove_stage7t_gate_stress_consequence_audit:MissingInput", ...
        "Missing input %s.", newPath);
end
category(end+1, 1) = string(newCategory);
source(end+1, 1) = string(newSource);
episode(end+1, 1) = double(newEpisode);
filePath(end+1, 1) = string(newPath);
bytes(end+1, 1) = info.bytes;
sha256(end+1, 1) = fileSha256(newPath);
end

function parent = compactParent(data)
parent = struct( ...
    "runRoot", data.stage7sRunRoot, ...
    "manifestSha256", data.expectedHashes.manifest, ...
    "resultsSha256", data.expectedHashes.results, ...
    "acquisitionLockSha256", data.expectedHashes.lock, ...
    "datasetSha256", data.expectedHashes.dataset, ...
    "gitCommit", string(data.parentManifest.gitCommit), ...
    "scientificResult", string(data.parentManifest.scientificResult), ...
    "validated", data.parentValidated);
end

function hashes = inventoryArtifacts(runRoot)
names = ["preflight_test_results.mat", "causal_input_alignment.csv", ...
    "capture_usage.csv", "command_components.csv", ...
    "command_summary_global.csv", "command_summary_by_channel.csv", ...
    "command_summary_by_side.csv", "command_summary_by_pose.csv", ...
    "command_summary_by_step.csv", ...
    "classification_channel_audit.csv", ...
    "classification_motor_audit.csv", "emg_nearest_acceptance.csv", ...
    "emg_distance_summary.csv", "context_query_audit.csv", ...
    "context_block_audit.csv", "context_phase_summary.csv", ...
    "context_step_summary.csv", "context_block_summary.csv", ...
    "input_inventory.csv", "operational_checks.csv", ...
    "stage7t_results.mat", "offline_report.md", ...
    "reproducible_command.txt"];
hashes = repmat(struct("relativePath", "", "sha256", ""), ...
    numel(names), 1);
for idx = 1:numel(names)
    path = fullfile(runRoot, names(idx));
    hashes(idx) = struct("relativePath", names(idx), ...
        "sha256", fileSha256(path));
end
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7t_gate_stress_consequence_audit(struct(" + ...
    "'resultsRoot','%s','stage7sRunRoot','%s'))", ...
    escape(matlabRoot), escape(string(fileparts(runRoot))), ...
    escape(options.stage7sRunRoot));
end

function value = buildOfflineReport(manifest)
lines = [ ...
    "# ETAPA 7T - consecuencias del estres sintetico del gate"; ""; ...
    "- Resultado operativo: PASS."; ...
    "- Resultado cientifico: `" + manifest.scientificResult + "`."; ...
    "- Recomendacion: `" + manifest.recommendation + "`."; ...
    sprintf("- Estados/componentes: %d/%d.", ...
        manifest.prospectiveStateCount, ...
        manifest.prospectiveComponentCount); ...
    sprintf("- Canales/motores que pasan regla: %d/%d.", ...
        manifest.passedChannelCount, manifest.passedMotorCount); ...
    sprintf("- Queries/matches de contexto: %d/%d.", ...
        manifest.contextQueryCount, manifest.contextFullMatchCount); ...
    "- Actor/Env/nueva simulacion/entrenamiento/hardware: no/no/no/no/no."; ...
    ""; ...
    "El dataset es un estres sintetico; no constituye reposo humano." ...
    ];
value = strjoin(lines, newline);
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function hash = fileSha256(filePath)
escaped = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escaped);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7t_gate_stress_consequence_audit:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = upper(string(strtrim(output)));
end

function value = escape(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7t_gate_stress_consequence_audit:WriteFailed", ...
        "Could not write %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
