function report = run_no_glove_stage7s_prospective_rest_support(options)
%run_no_glove_stage7s_prospective_rest_support acquires causal rest support.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));
clearConfigurablesOverride();

data = loadNoGloveStage7sEvidence(options.stage7rRunRoot, ...
    options.stage7qRunRoot, options.stage7pRunRoot, ...
    options.stage7nRunRoot);
if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", ...
        "stage7s_prospective_rest_support");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7s_prospective_rest_support:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testFiles = [ ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7sProspectiveRestSupport.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7rRealStateEmgAttribution.m")];
testResults = runtests(testFiles);
save(fullfile(runRoot, "preflight_test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7s_prospective_rest_support:TestsFailed", ...
        "ETAPA 7S tests failed. See %s.", runRoot);
end

design = buildNoGloveStage7sRestSupportCorpus( ...
    data.profile, data.frozenEmgScale, ...
    "seed", options.seed, "episodeCount", options.episodeCount, ...
    "windowCount", options.windowCount);
fixtureRoot = fullfile(runRoot, "fixture");
mkdir(fixtureRoot);
datasetPath = fullfile(fixtureRoot, ...
    "stage7s_prospective_declared_rest.mat");
emgs = design.emgs;
metadata = design.metadata;
save(datasetPath, "emgs", "metadata", "-v7.3");
writetable(design.designTable, ...
    fullfile(runRoot, "prospective_emg_design.csv"));
writetable(struct2table(design.checks), ...
    fullfile(runRoot, "dataset_contract.csv"));
save(fullfile(runRoot, "dataset_design.mat"), "design", "-v7.3");

checkpointPath = string(data.agent200Row.checkpointPath);
evaluationBase = fullfile(runRoot, "agent200_acquisition");
mkdir(evaluationBase);
profile = configureEvaluationProfile(data.profile, checkpointPath, ...
    datasetPath, evaluationBase, options);
profileAudit = validateNoGloveStage7sEvaluationProfile( ...
    profile, checkpointPath, datasetPath, ...
    "seed", options.seed, "episodeCount", options.episodeCount, ...
    "maxSteps", options.maxSteps);
writetable(struct2table(profileAudit), ...
    fullfile(runRoot, "evaluation_profile_audit.csv"));
save(fullfile(runRoot, "effective_evaluation_profile.mat"), ...
    "profile", "options");

setConfigurablesOverride(profile);
overrideCleanup = onCleanup(@() clearConfigurablesOverride());
trainInterface("td3_no_glove_intent", "", "");
clear overrideCleanup
clearConfigurablesOverride();
acquisitionDirectory = findNewestSubdir(evaluationBase);

sources = struct( ...
    "acceptance", string(data.agent200Row.acceptanceDirectory), ...
    "steadyRest", acquisitionDirectory);
corpus = loadNoGloveStage7pInterfaceCorpus(sources, data.actuator);
acceptanceInvariant = validateAcceptanceInvariant( ...
    corpus, data.primaryCorpus);
expectedPrimaryCount = sum(corpus.zeroControlDemand & ...
    ismember(corpus.metadata.gateContext, ...
    ["initialRest", "declaredRest"]), "all");
pairSet = buildNoGloveStage7rRealPairs(corpus, ...
    "expectedPrimaryComponentCount", expectedPrimaryCount, ...
    "emgScaleOverride", data.frozenEmgScale, ...
    "contextScaleOverride", data.frozenContextScale);
acquisition = summarizeNoGloveStage7sAcquisition( ...
    corpus, pairSet, data.profile.intentCalibration, ...
    data.frozenEmgScale, data.frozenContextScale, ...
    acceptanceInvariant);
supportGate = classifyNoGloveStage7sSupportGate( ...
    acquisition, pairSet.supportSummary, ...
    "expectedEpisodeCount", options.episodeCount, ...
    "expectedStateCount", options.episodeCount*options.maxSteps);

episodeInventory = addEpisodeHashes(corpus.inventory);
writetable(episodeInventory, ...
    fullfile(runRoot, "source_episode_inventory.csv"));
writetable(corpus.alignmentAudit, ...
    fullfile(runRoot, "temporal_alignment_audit.csv"));
writetable(pairSet.table, fullfile(runRoot, "real_pairs.csv"));
writetable(pairSet.supportSummary, ...
    fullfile(runRoot, "pair_support_summary.csv"));
writetable(pairSet.gridSummary, ...
    fullfile(runRoot, "matching_grid_summary.csv"));
writetable(struct2table(acquisition), ...
    fullfile(runRoot, "acquisition_summary.csv"));
writetable(struct2table(supportGate.checks), ...
    fullfile(runRoot, "support_gate_checks.csv"));
writetable(struct2table(rmfield(supportGate, "checks")), ...
    fullfile(runRoot, "support_gate_decision.csv"));

lockPath = fullfile(runRoot, "acquisition_lock.mat");
save(lockPath, "corpus", "pairSet", "acquisition", ...
    "supportGate", "episodeInventory", "-v7.3");
lock = struct( ...
    "schemaVersion", 1, "stage", "7S", ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "datasetSha256", fileSha256(datasetPath), ...
    "episodeInventorySha256", fileSha256(fullfile(runRoot, ...
        "source_episode_inventory.csv")), ...
    "acquisitionLockSha256", fileSha256(lockPath), ...
    "episodeCount", acquisition.episodeCount, ...
    "stateCount", acquisition.stateCount, ...
    "primaryComponentCount", expectedPrimaryCount, ...
    "pairCount", pairSet.pairCount, ...
    "supportPassed", supportGate.passed, ...
    "modelsAuthorized", supportGate.modelsAuthorized);
writeText(fullfile(runRoot, "acquisition_lock.json"), ...
    jsonencode(lock, "PrettyPrint", true));

sharedEvaluations = struct([]);
replayAudit = table();
analysis = struct();
modelsExecuted = false;
scientificResult = supportGate.scientificResult;
if supportGate.modelsAuthorized
    [sharedEvaluations, replayAudit] = evaluateCheckpointSet( ...
        data, corpus);
    writetable(replayAudit, fullfile(runRoot, "actor_replay_audit.csv"));
    if any(~replayAudit.replayPassed)
        error("run_no_glove_stage7s_prospective_rest_support:ReplayFailed", ...
            "A frozen actor failed replay after acquisition lock.");
    end
    analysis = analyzeNoGloveStage7rEmgAttribution( ...
        pairSet, sharedEvaluations);
    scientificResult = analysis.scientificResult;
    modelsExecuted = true;
    writeAnalysisTables(runRoot, analysis);
else
    writetable(replayAudit, fullfile(runRoot, "actor_replay_audit.csv"));
end

inputInventory = buildInputInventory(data, options);
writetable(inputInventory, fullfile(runRoot, "input_inventory.csv"));
operationalChecks = struct( ...
    "stage7rValidated", data.stage7r.validated, ...
    "stage7qValidated", data.stage7q.validated, ...
    "stage7pValidated", data.stage7p.validated, ...
    "stage7nValidated", data.stage7n.validated, ...
    "state60Selected", true, "state62Rejected", true, ...
    "datasetContractPassed", all(struct2array(design.checks)), ...
    "profileContractPassed", all(struct2array(profileAudit)), ...
    "acceptanceInvariant", acceptanceInvariant, ...
    "acquisitionLockedBeforeModels", true, ...
    "modelExecutionRespectedGate", ...
        modelsExecuted == supportGate.modelsAuthorized, ...
    "rewardUnchanged", true, "quantizationUnchanged", true, ...
    "td3Unchanged", true, "simulatorUnchanged", true, ...
    "safetyUnchanged", true, "gateUnchanged", true, ...
    "noTraining", true, "simMotors", true, ...
    "noHardware", true, "noMyo", true, "noGlove", true, ...
    "noDtw", true, "noPilot", true, "noCampaign", true);
if ~all(struct2array(operationalChecks))
    error("run_no_glove_stage7s_prospective_rest_support:OperationalGate", ...
        "An ETAPA 7S operational invariant failed.");
end
writetable(struct2table(operationalChecks), ...
    fullfile(runRoot, "operational_checks.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = ...
    getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", "7S", "schemaVersion", 1, "result", "PASS", ...
    "scientificResult", scientificResult, ...
    "supportGateResult", supportGate.scientificResult, ...
    "supportGatePassed", supportGate.passed, ...
    "stateDecision", "intentMarkov60", ...
    "state62Disposition", "provisionallyRejected", ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7s_prospective_rest_support", ...
    "preregistrationCommit", "32bd9129", ...
    "parentStage7r", compactParent(data.stage7r), ...
    "parentStage7q", compactParent(data.stage7q), ...
    "seed", options.seed, "episodeCount", options.episodeCount, ...
    "windowCount", options.windowCount, ...
    "maxSteps", options.maxSteps, ...
    "targetActivity", design.metadata.targetActivity, ...
    "thetaOn", design.metadata.thetaOn, ...
    "thetaOff", design.metadata.thetaOff, ...
    "physiologicalRestEvidence", false, ...
    "minimumCrossDominantEmgRms", ...
        design.minimumCrossDominantEmgRms, ...
    "datasetPath", datasetPath, ...
    "datasetSha256", lock.datasetSha256, ...
    "acquisitionDirectory", acquisitionDirectory, ...
    "acquisitionLockSha256", lock.acquisitionLockSha256, ...
    "acceptanceEpisodeCount", 50, ...
    "prospectiveRestEpisodeCount", acquisition.episodeCount, ...
    "prospectiveRestStateCount", acquisition.stateCount, ...
    "primaryComponentCount", expectedPrimaryCount, ...
    "pairCount", pairSet.pairCount, ...
    "steadyRestCrossSupportedMotorCount", ...
        supportGate.steadyRestCrossSupportedMotorCount, ...
    "globalCrossSupportedMotorCount", ...
        supportGate.globalCrossSupportedMotorCount, ...
    "globalWithinSupportedMotorCount", ...
        supportGate.globalWithinSupportedMotorCount, ...
    "modelsExecuted", modelsExecuted, ...
    "agent200LoadedForSimulation", true, ...
    "checkpointActorsLoadedForOfflineInference", modelsExecuted, ...
    "agent7250Loaded", false, "agent7250Used", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "trainingUsed", false, "simulationUsed", true, ...
    "simMotors", true, "hardwareUsed", false, ...
    "myoUsed", false, "gloveUsed", false, ...
    "dtwCalculated", false, "rewardChanged", false, ...
    "quantizationChanged", false, "td3Changed", false, ...
    "simulatorChanged", false, "safetyLayerChanged", false, ...
    "restGateChanged", false, "stateCounterfactualUsed", false, ...
    "hybridStateUsed", false, "smokeAuthorized", false, ...
    "smokeExecuted", false, "pilotAuthorized", false, ...
    "pilotExecuted", false, "campaignAuthorized", false, ...
    "campaignExecuted", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "operationalChecks", operationalChecks, ...
    "outputPath", runRoot);

save(fullfile(runRoot, "stage7s_results.mat"), ...
    "manifest", "design", "corpus", "pairSet", "acquisition", ...
    "supportGate", "sharedEvaluations", "replayAudit", "analysis", ...
    "operationalChecks", "inputInventory", "profileAudit", ...
    "episodeInventory", "lock", "options", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct( ...
    "result", "PASS", "scientificResult", scientificResult, ...
    "supportGatePassed", supportGate.passed, ...
    "modelsExecuted", modelsExecuted, "outputPath", runRoot, ...
    "manifest", manifest, "supportGate", supportGate, ...
    "analysis", analysis);
fprintf("ETAPA 7S PROSPECTIVE REST SUPPORT PASS\n");
fprintf("Support gate: %s (%d)\n", ...
    supportGate.scientificResult, supportGate.passed);
fprintf("Scientific result: %s\n", scientificResult);
fprintf("Prospective states/pairs: %d/%d\n", ...
    acquisition.stateCount, pairSet.pairCount);
fprintf("Output: %s\n", runRoot);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7s_prospective_rest_support:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "resultsRoot", "", ...
    "stage7rRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7r_artifacts\stage7r_final\2026-08-31_21-42-38-792", ...
    "stage7qRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7q_artifacts\stage7q_final\2026-08-30_16-44-30-296", ...
    "stage7pRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7p_artifacts\stage7p_final\2026-08-29_23-15-59-803", ...
    "stage7nRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7n_artifacts\stage7n_corrected_final\2026-08-29_07-34-46-814", ...
    "seed", 7701, "episodeCount", 80, ...
    "windowCount", 21, "maxSteps", 20);
unknown = setdiff(string(fieldnames(options)), ...
    string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7s_prospective_rest_support:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
stringFields = ["resultsRoot", "stage7rRunRoot", ...
    "stage7qRunRoot", "stage7pRunRoot", "stage7nRunRoot"];
for field = stringFields
    options.(field) = string(options.(field));
end
if options.seed ~= 7701 || options.episodeCount ~= 80 || ...
        options.windowCount ~= 21 || options.maxSteps ~= 20
    error("run_no_glove_stage7s_prospective_rest_support:ProtocolChanged", ...
        "ETAPA 7S requires seed 7701, 80 episodes and 21/20 windows/steps.");
end
end

function profile = configureEvaluationProfile( ...
        frozen, checkpointPath, datasetPath, evaluationBase, options)
[datasetFolder, datasetStem] = fileparts(datasetPath);
profile = frozen;
profile.run_training = false;
profile.newTraining = false;
profile.agentFile = checkpointPath;
profile.agent_id = "td3_no_glove_intent";
profile.randomSeed = options.seed;
profile.dataset = {char(string(datasetStem))};
profile.dataset_folder = string(datasetFolder);
profile.flagSaveTraining = true;
profile.episode_save_freq = 1;
profile.plotEpisodeOnTest = false;
profile.verbose = false;
profile.simOpts = rlSimulationOptions( ...
    "MaxSteps", options.maxSteps, ...
    "NumSimulations", options.episodeCount, ...
    "StopOnError", "on", "UseParallel", false);
profile.agents_directory = @(agent_id, variant) fullfile( ...
    evaluationBase, string(datetime("now", ...
    "Format", "yy-MM-dd HH m s")));
end

function value = validateAcceptanceInvariant(corpus, parent)
newMask = corpus.metadata.source == "acceptance";
oldMask = parent.metadata.source == "acceptance";
value = sum(newMask) == 3050 && sum(oldMask) == 3050 && ...
    isequal(corpus.states(newMask, :), parent.states(oldMask, :)) && ...
    isequal(corpus.rawAction(newMask, :), ...
        parent.rawAction(oldMask, :)) && ...
    isequal(corpus.effectiveAction(newMask, :), ...
        parent.effectiveAction(oldMask, :)) && ...
    isequal(corpus.pwm(newMask, :), parent.pwm(oldMask, :)) && ...
    isequal(corpus.qAfter(newMask, :), parent.qAfter(oldMask, :));
if ~value
    error("run_no_glove_stage7s_prospective_rest_support:AcceptanceChanged", ...
        "The frozen Agent200 acceptance corpus changed.");
end
end

function inventory = addEpisodeHashes(inventory)
sha256 = strings(height(inventory), 1);
bytes = zeros(height(inventory), 1);
for idx = 1:height(inventory)
    path = string(inventory.filePath(idx));
    info = dir(path);
    bytes(idx) = info.bytes;
    sha256(idx) = fileSha256(path);
end
inventory.bytes = bytes;
inventory.sha256 = sha256;
end

function [evaluations, audit] = evaluateCheckpointSet(data, corpus)
rows = sortrows(data.checkpointTable, "episode");
evaluations = repmat(struct("episode", 0, "raw", [], ...
    "effective", [], "pwm", []), height(rows), 1);
auditParts = cell(height(rows), 1);
newAcceptance = corpus.metadata.source == "acceptance";
parentAcceptance = data.primaryCorpus.metadata.source == "acceptance";
for idx = 1:height(rows)
    episode = double(rows.episode(idx));
    checkpointPath = string(rows.checkpointPath(idx));
    agent = loadSavedAgent(checkpointPath);
    actor = getActor(agent);
    model = getModel(actor);
    raw = evaluateFrozenActorModelStates(model, corpus.states);
    [effective, pwm] = quantizeRows(raw, data.actuator);
    evaluations(idx) = struct("episode", episode, "raw", raw, ...
        "effective", effective, "pwm", pwm);
    parentIdx = find([data.sharedEvaluations.episode] == episode, 1);
    acceptanceRawError = max(abs(raw(newAcceptance, :) - ...
        data.sharedEvaluations(parentIdx).raw(parentAcceptance, :)), ...
        [], "all");
    acceptancePwmMismatch = sum(pwm(newAcceptance, :) ~= ...
        data.sharedEvaluations(parentIdx).pwm(parentAcceptance, :), "all");
    savedRawError = NaN;
    savedPwmMismatch = NaN;
    if episode == 200
        savedRawError = max(abs(raw-corpus.rawAction), [], "all");
        savedPwmMismatch = sum(pwm ~= corpus.pwm, "all");
    end
    replayPassed = acceptanceRawError <= 1e-5 && ...
        acceptancePwmMismatch == 0 && ...
        (episode ~= 200 || (savedRawError <= 1e-5 && ...
        savedPwmMismatch == 0));
    auditParts{idx} = table(episode, checkpointPath, ...
        string(rows.checkpointSha256(idx)), size(raw, 1), ...
        acceptanceRawError, acceptancePwmMismatch, ...
        savedRawError, savedPwmMismatch, replayPassed, ...
        'VariableNames', ["checkpointEpisode", "checkpointPath", ...
        "checkpointSha256", "evaluatedStateCount", ...
        "acceptanceRawMaximumError", "acceptancePwmMismatchCount", ...
        "agent200SavedRawMaximumError", ...
        "agent200SavedPwmMismatchCount", "replayPassed"]);
    clear agent actor model raw effective pwm
end
audit = vertcat(auditParts{:});
end

function [effective, pwm] = quantizeRows(raw, actuator)
effective = zeros(size(raw));
pwm = zeros(size(raw));
for row = 1:size(raw, 1)
    [e, p] = quantizeBaselineAction(raw(row, :), ...
        actuator.maxPwm, actuator.activationThreshold, ...
        actuator.commandLevels);
    effective(row, :) = double(e(:)');
    pwm(row, :) = double(p(:)');
end
end

function writeAnalysisTables(runRoot, analysis)
writetable(analysis.pairActionTable, ...
    fullfile(runRoot, "pair_actions.csv"));
writetable(analysis.familyModelSummary, ...
    fullfile(runRoot, "family_model_summary.csv"));
writetable(analysis.channelModelSummary, ...
    fullfile(runRoot, "channel_model_summary.csv"));
writetable(analysis.familyDecisionAudit, ...
    fullfile(runRoot, "family_decision_audit.csv"));
writetable(analysis.allEmgDecisionAudit, ...
    fullfile(runRoot, "all_emg_decision_audit.csv"));
writetable(analysis.supportDecisionAudit, ...
    fullfile(runRoot, "model_support_decision_audit.csv"));
end

function inventory = buildInputInventory(data, options)
paths = [ ...
    fullfile(options.stage7rRunRoot, "manifest.json"); ...
    fullfile(options.stage7rRunRoot, "stage7r_results.mat"); ...
    fullfile(options.stage7qRunRoot, "manifest.json"); ...
    fullfile(options.stage7qRunRoot, "stage7q_results.mat"); ...
    fullfile(options.stage7pRunRoot, "manifest.json"); ...
    fullfile(options.stage7pRunRoot, "stage7p_results.mat"); ...
    fullfile(options.stage7nRunRoot, "manifest.json"); ...
    fullfile(options.stage7nRunRoot, "checkpoint_summary.csv"); ...
    data.profilePath; data.normPath; ...
    string(data.checkpointInventory.checkpointPath)];
category = [repmat("parent", 8, 1); "profile"; ...
    "normalization"; repmat("checkpoint", 4, 1)];
acceptanceFiles = string(data.primaryCorpus.inventory.filePath( ...
    data.primaryCorpus.inventory.source == "acceptance"));
paths = [paths; acceptanceFiles];
category = [category; repmat("frozenAcceptanceEpisode", ...
    numel(acceptanceFiles), 1)];
bytes = zeros(numel(paths), 1);
sha256 = strings(numel(paths), 1);
for idx = 1:numel(paths)
    info = dir(paths(idx));
    bytes(idx) = info.bytes;
    sha256(idx) = fileSha256(paths(idx));
end
inventory = table(category, paths, bytes, sha256, ...
    'VariableNames', ["category", "filePath", "bytes", "sha256"]);
end

function parent = compactParent(value)
parent = struct("runRoot", value.runRoot, ...
    "manifestSha256", value.manifestSha256, ...
    "gitCommit", string(value.manifest.gitCommit), ...
    "scientificResult", string(value.manifest.scientificResult), ...
    "validated", value.validated);
end

function hashes = inventoryArtifacts(runRoot)
files = dir(fullfile(runRoot, "**", "*"));
files = files(~[files.isdir]);
fullPaths = string(fullfile({files.folder}, {files.name}))';
manifestPath = string(fullfile(runRoot, "manifest.json"));
fullPaths = fullPaths(fullPaths ~= manifestPath);
relativePath = erase(fullPaths, string(runRoot)+filesep);
sha256 = strings(numel(fullPaths), 1);
for idx = 1:numel(fullPaths)
    sha256(idx) = fileSha256(fullPaths(idx));
end
hashes = table2struct(table(relativePath, sha256));
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7s_prospective_rest_support(struct(" + ...
    "'resultsRoot','%s','stage7rRunRoot','%s'," + ...
    "'stage7qRunRoot','%s','stage7pRunRoot','%s'," + ...
    "'stage7nRunRoot','%s'))", ...
    escape(matlabRoot), escape(string(fileparts(runRoot))), ...
    escape(options.stage7rRunRoot), escape(options.stage7qRunRoot), ...
    escape(options.stage7pRunRoot), escape(options.stage7nRunRoot));
end

function value = buildOfflineReport(manifest)
lines = [ ...
    "# ETAPA 7S - soporte prospectivo en reposo declarado"; ""; ...
    "- Resultado operativo: PASS."; ...
    "- Gate de soporte: `"+manifest.supportGateResult+"`."; ...
    "- Resultado científico: `"+manifest.scientificResult+"`."; ...
    sprintf("- Episodios/estados prospectivos: %d/%d.", ...
        manifest.prospectiveRestEpisodeCount, ...
        manifest.prospectiveRestStateCount); ...
    sprintf("- Motores soportados steadyRest cross: %d/4.", ...
        manifest.steadyRestCrossSupportedMotorCount); ...
    sprintf("- Modelos confirmatorios ejecutados: %d.", ...
        manifest.modelsExecuted); ...
    "- El dataset es sintético y no es evidencia de reposo fisiológico."; ...
    "- Entrenamiento/hardware/Myo/guante/DTW: no/no/no/no/no."; ...
    ""; "No se autoriza smoke, piloto ni campaña." ...
    ];
value = strjoin(lines, newline);
end

function newestDir = findNewestSubdir(parentDir)
entries = dir(parentDir);
entries = entries([entries.isdir] & ...
    ~ismember({entries.name}, {'.', '..'}));
if isempty(entries)
    error("run_no_glove_stage7s_prospective_rest_support:MissingOutput", ...
        "No evaluation directory was created under %s.", parentDir);
end
[~, idx] = max([entries.datenum]);
newestDir = string(fullfile(entries(idx).folder, entries(idx).name));
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status ~= 0
    commit = "unknown";
else
    commit = string(strtrim(output));
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=all', repoRoot));
if status ~= 0
    dirty = true;
    trackedDirty = true;
    statusText = "git status failed";
else
    statusText = string(strtrim(output));
    dirty = strlength(statusText) > 0;
    lines = splitlines(statusText);
    lines = lines(strlength(lines) > 0);
    trackedDirty = any(~startsWith(lines, "??"));
end
end

function hash = fileSha256(filePath)
escaped = strrep(char(filePath), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escaped);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7s_prospective_rest_support:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = string(strtrim(output));
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7s_prospective_rest_support:WriteFailed", ...
        "Could not write %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function value = escape(value)
value = strrep(string(value), "'", "''");
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
