function report = run_no_glove_stage7g_action_margin_analysis(options)
%run_no_glove_stage7g_action_margin_analysis audits thresholds offline.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7g_action_margin_analysis");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7g_action_margin_analysis:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testResults = runtests(fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage7gActionMargins.m"));
save(fullfile(runRoot, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7g_action_margin_analysis:TestsFailed", ...
        "ETAPA 7G tests failed. See %s.", runRoot);
end

[stage7f, child, profiles, sourceAudit] = loadAndValidateInputs( ...
    options.stage7fRunRoot);
inputHashesBefore = inventoryEpisodeInputs(child);
[controlComponents, controlEpisodeAudit] = ...
    loadNoGloveStage7gActionCorpus("control", ...
    child.control.acceptanceDirectory, child.control.restDirectory);
[candidateComponents, candidateEpisodeAudit] = ...
    loadNoGloveStage7gActionCorpus("candidate", ...
    child.candidate.acceptanceDirectory, child.candidate.restDirectory);
components = [controlComponents; candidateComponents];
episodeAudit = [controlEpisodeAudit; candidateEpisodeAudit];
validateEpisodeInventory(episodeAudit);
referenceAudit = auditMatchedReferences(components);

actuator = struct("maxPwm", max(abs(double(profiles.control.speeds))), ...
    "activationThreshold", ...
        double(profiles.control.actionCommandActivationThreshold), ...
    "commandLevels", double(profiles.control.actionCommandLevels));
analysis = analyzeNoGloveStage7gActionMargins(components, actuator);
inputHashesAfter = inventoryEpisodeInputs(child);
if ~isequal(inputHashesBefore, inputHashesAfter)
    error("run_no_glove_stage7g_action_margin_analysis:InputModified", ...
        "A source episode changed during the offline analysis.");
end
sourceHashesAfter = hashSourceFiles(options.stage7fRunRoot, child);
if ~isequal(sourceAudit.sourceHashesBefore, sourceHashesAfter)
    error("run_no_glove_stage7g_action_margin_analysis:SourceModified", ...
        "A source manifest, profile or checkpoint changed.");
end

distributionSummary = analysis.distributionSummary;
thresholdCurve = analysis.thresholdCurve;
thresholdDecision = analysis.thresholdDecision;
sourceDecision = analysis.sourceDecision;
quantizationAudit = struct2table(analysis.quantizationAudit);
profileAudit = buildProfileAudit(profiles, actuator);
writetable(inputHashesBefore, ...
    fullfile(runRoot, "episode_input_hashes.csv"));
writetable(episodeAudit, fullfile(runRoot, "episode_audit.csv"));
writetable(referenceAudit, fullfile(runRoot, "reference_audit.csv"));
writetable(profileAudit, fullfile(runRoot, "profile_audit.csv"));
writetable(quantizationAudit, ...
    fullfile(runRoot, "quantization_replay_audit.csv"));
writetable(distributionSummary, ...
    fullfile(runRoot, "action_distribution_summary.csv"));
writetable(thresholdCurve, fullfile(runRoot, "threshold_curve.csv"));
writetable(thresholdDecision, ...
    fullfile(runRoot, "threshold_decision.csv"));
writetable(sourceDecision, fullfile(runRoot, "source_decision.csv"));
writetable(components, fullfile(runRoot, "action_components.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct("stage", "7G", "schemaVersion", 1, ...
    "result", "PASS", "scientificResult", analysis.classification, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7g_action_margin_analysis", ...
    "stage7fRunRoot", options.stage7fRunRoot, ...
    "stage7fManifestSha256", sourceAudit.stage7fManifestSha256, ...
    "controlManifestSha256", sourceAudit.controlManifestSha256, ...
    "candidateManifestSha256", sourceAudit.candidateManifestSha256, ...
    "controlCheckpointSha256", sourceAudit.controlCheckpointSha256, ...
    "candidateCheckpointSha256", sourceAudit.candidateCheckpointSha256, ...
    "episodeInputCount", height(inputHashesBefore), ...
    "episodeInputsPreserved", true, ...
    "componentCount", height(components), ...
    "windowCount", analysis.quantizationAudit.windowCount, ...
    "referenceAudit", table2struct(referenceAudit), ...
    "profileAudit", table2struct(profileAudit), ...
    "quantizationAudit", analysis.quantizationAudit, ...
    "thresholds", analysis.thresholds, ...
    "currentActivationThreshold", analysis.currentActivationThreshold, ...
    "thresholdDecision", table2struct(thresholdDecision), ...
    "sourceDecision", table2struct(sourceDecision), ...
    "thresholdAppliedToEnvironment", false, ...
    "referenceSource", "emgIntent", ...
    "observationVariant", "intentMarkov60", ...
    "actionInterfaceVariant", "baselineQuantized", ...
    "policyChanged", false, "quantizationChanged", false, ...
    "rewardChanged", false, "referenceChanged", false, ...
    "simulatorChanged", false, "safetyLayerChanged", false, ...
    "runTraining", false, "newTraining", false, ...
    "agentLoaded", false, "envCreated", false, ...
    "simulatorInvoked", false, "rewardFunctionInvoked", false, ...
    "dtwCalculated", false, "hardwareUsed", false, ...
    "agent7250Loaded", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "rootCauseIdentified", false, ...
    "behavioralInterventionExecuted", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);
save(fullfile(runRoot, "stage7g_results.mat"), "manifest", ...
    "analysis", "components", "episodeAudit", "inputHashesBefore", ...
    "referenceAudit", "profileAudit", "actuator", "stage7f", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "outputPath", runRoot, "manifest", manifest, ...
    "analysis", analysis);
fprintf("ETAPA 7G ACTION MARGIN ANALYSIS PASS\n");
fprintf("Scientific result: %s\n", analysis.classification);
fprintf("Output: %s\n", runRoot);
disp(thresholdDecision);
disp(sourceDecision);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7g_action_margin_analysis:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct("resultsRoot", "", "stage7fRunRoot", ...
    "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7f_artifacts\" + ...
    "stage7f_final\2026-08-27_21-23-09-959");
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7g_action_margin_analysis:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.stage7fRunRoot = string(options.stage7fRunRoot);
if ~isfile(fullfile(options.stage7fRunRoot, "manifest.json"))
    error("run_no_glove_stage7g_action_margin_analysis:MissingStage7f", ...
        "ETAPA 7F manifest not found under %s.", options.stage7fRunRoot);
end
end

function [stage7f, child, profiles, audit] = loadAndValidateInputs(root)
manifestPath = fullfile(root, "manifest.json");
stage7f = jsondecode(fileread(manifestPath));
if string(stage7f.stage) ~= "7F" || string(stage7f.result) ~= "PASS" || ...
        logical(stage7f.hardwareUsed) || logical(stage7f.pilotAuthorized) || ...
        string(stage7f.observationVariant) ~= "intentMarkov60" || ...
        string(stage7f.actionInterfaceVariant) ~= "baselineQuantized"
    error("run_no_glove_stage7g_action_margin_analysis:Stage7fContract", ...
        "Input manifest is not the frozen ETAPA 7F result.");
end
control = loadChild(string(stage7f.controlRunRoot));
candidate = loadChild(string(stage7f.candidateRunRoot));
child = struct("control", control, "candidate", candidate);
controlProfile = load(fullfile(control.runRoot, ...
    "seed_11", "effective_training_profile.mat"), "profile");
candidateProfile = load(fullfile(candidate.runRoot, ...
    "seed_11", "effective_training_profile.mat"), "profile");
profiles = struct("control", controlProfile.profile, ...
    "candidate", candidateProfile.profile);
if profiles.control.intentRewardActionWeight ~= 0.01 || ...
        profiles.candidate.intentRewardActionWeight ~= 0.05 || ...
        ~isequal(profiles.control.actionCommandActivationThreshold, ...
            profiles.candidate.actionCommandActivationThreshold) || ...
        ~isequal(profiles.control.actionCommandLevels, ...
            profiles.candidate.actionCommandLevels) || ...
        ~isequal(profiles.control.speeds, profiles.candidate.speeds)
    error("run_no_glove_stage7g_action_margin_analysis:ProfileContract", ...
        "7F profiles do not preserve a common actuator interface.");
end
sourceHashes = hashSourceFiles(root, child);
if sourceHashes.sha256(6) ~= child.control.finalCheckpointSha256 || ...
        sourceHashes.sha256(7) ~= child.candidate.finalCheckpointSha256 || ...
        sourceHashes.sha256(6) ~= string(stage7f.control.checkpointSha256) || ...
        sourceHashes.sha256(7) ~= string(stage7f.candidate.checkpointSha256)
    error("run_no_glove_stage7g_action_margin_analysis:CheckpointHash", ...
        "A frozen Agent200 hash disagrees with the 7F inventories.");
end
audit = struct("stage7fManifestSha256", sourceHashes.sha256(1), ...
    "controlManifestSha256", sourceHashes.sha256(2), ...
    "candidateManifestSha256", sourceHashes.sha256(3), ...
    "controlCheckpointSha256", sourceHashes.sha256(6), ...
    "candidateCheckpointSha256", sourceHashes.sha256(7), ...
    "sourceHashesBefore", sourceHashes);
end

function value = loadChild(root)
data = load(fullfile(root, "stage6_results.mat"), ...
    "seedResults", "seedTable", "checkpointTable");
seed = data.seedResults{1};
final = data.checkpointTable(data.checkpointTable.isFinal, :);
value = struct("runRoot", root, ...
    "acceptanceDirectory", string(seed.acceptanceDirectory), ...
    "restDirectory", string(seed.restDirectory), ...
    "finalCheckpoint", string(final.checkpointPath), ...
    "finalCheckpointSha256", string(final.checkpointSha256));
end

function hashes = hashSourceFiles(stage7fRoot, child)
paths = [fullfile(stage7fRoot, "manifest.json"); ...
    fullfile(child.control.runRoot, "manifest.json"); ...
    fullfile(child.candidate.runRoot, "manifest.json"); ...
    fullfile(child.control.runRoot, "seed_11", ...
        "effective_training_profile.mat"); ...
    fullfile(child.candidate.runRoot, "seed_11", ...
        "effective_training_profile.mat"); ...
    child.control.finalCheckpoint; child.candidate.finalCheckpoint];
labels = ["stage7fManifest"; "controlManifest"; "candidateManifest"; ...
    "controlProfile"; "candidateProfile"; ...
    "controlAgent200"; "candidateAgent200"];
sha256 = strings(numel(paths), 1);
for idx = 1:numel(paths)
    sha256(idx) = fileSha256(paths(idx));
end
hashes = table(labels, paths, sha256);
end

function tableValue = inventoryEpisodeInputs(child)
parts = cell(4, 1);
parts{1} = hashEpisodeDirectory("control", "acceptance", ...
    child.control.acceptanceDirectory);
parts{2} = hashEpisodeDirectory("control", "steadyRest", ...
    child.control.restDirectory);
parts{3} = hashEpisodeDirectory("candidate", "acceptance", ...
    child.candidate.acceptanceDirectory);
parts{4} = hashEpisodeDirectory("candidate", "steadyRest", ...
    child.candidate.restDirectory);
tableValue = vertcat(parts{:});
end

function tableValue = hashEpisodeDirectory(variant, source, directory)
files = dir(fullfile(directory, "episode*.mat"));
[~, order] = sort({files.name});
files = files(order);
episode = zeros(numel(files), 1);
path = strings(numel(files), 1);
sha256 = strings(numel(files), 1);
bytes = zeros(numel(files), 1);
for idx = 1:numel(files)
    token = regexp(files(idx).name, '^episode(\d+)\.mat$', ...
        'tokens', 'once');
    episode(idx) = str2double(token{1});
    path(idx) = string(fullfile(files(idx).folder, files(idx).name));
    sha256(idx) = fileSha256(path(idx));
    bytes(idx) = files(idx).bytes;
end
tableValue = table(repmat(variant, numel(files), 1), ...
    repmat(source, numel(files), 1), episode, path, sha256, bytes, ...
    'VariableNames', ["variant", "source", "episode", "path", ...
    "sha256", "bytes"]);
end

function validateEpisodeInventory(audit)
expected = table(["control"; "control"; "candidate"; "candidate"], ...
    ["acceptance"; "steadyRest"; "acceptance"; "steadyRest"], ...
    [50; 24; 50; 24], [61; 15; 61; 15], ...
    'VariableNames', ["variant", "source", "episodeCount", "stepCount"]);
for idx = 1:height(expected)
    rows = audit.variant == expected.variant(idx) & ...
        audit.source == expected.source(idx);
    if sum(rows) ~= expected.episodeCount(idx) || ...
            any(audit.stepCount(rows) ~= expected.stepCount(idx))
        error("run_no_glove_stage7g_action_margin_analysis:EpisodeInventory", ...
            "Unexpected %s/%s episode inventory.", ...
            expected.variant(idx), expected.source(idx));
    end
end
end

function audit = auditMatchedReferences(components)
control = components(components.variant == "control", :);
candidate = components(components.variant == "candidate", :);
keysControl = string(control.source)+"|"+string(control.episode)+"|"+ ...
    string(control.step)+"|"+string(control.motor);
keysCandidate = string(candidate.source)+"|"+ ...
    string(candidate.episode)+"|"+string(candidate.step)+"|"+ ...
    string(candidate.motor);
[keysControl, orderControl] = sort(keysControl);
[keysCandidate, orderCandidate] = sort(keysCandidate);
if ~isequal(keysControl, keysCandidate)
    error("run_no_glove_stage7g_action_margin_analysis:ReferenceKeys", ...
        "Control and candidate do not share the same reference rows.");
end
errorValue = max(abs(control.referenceVelocity(orderControl)- ...
    candidate.referenceVelocity(orderCandidate)));
audit = table(numel(keysControl), errorValue, errorValue == 0, ...
    'VariableNames', ["componentCountPerVariant", ...
    "maximumReferenceVelocityDifference", "referencesExactlyEqual"]);
end

function value = buildProfileAudit(profiles, actuator)
value = table(profiles.control.intentRewardActionWeight, ...
    profiles.candidate.intentRewardActionWeight, actuator.maxPwm, ...
    actuator.activationThreshold, ...
    string(mat2str(actuator.commandLevels)), ...
    string(profiles.control.observationVariant), ...
    string(profiles.control.actionInterfaceVariant), ...
    logical(profiles.control.simMotors), ...
    logical(profiles.control.simulationPositionSafety.enabled), ...
    'VariableNames', ["controlActionWeight", "candidateActionWeight", ...
    "maxPwm", "activationThreshold", "commandLevels", ...
    "observationVariant", "actionInterfaceVariant", "simMotors", ...
    "positionSafetyEnabled"]);
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf("cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7g_action_margin_analysis(struct(" + ...
    "'resultsRoot','%s','stage7fRunRoot','%s'))", ...
    escapeQuote(matlabRoot), escapeQuote(string(fileparts(runRoot))), ...
    escapeQuote(options.stage7fRunRoot));
end

function value = buildOfflineReport(manifest)
d = manifest.sourceDecision;
lines = ["# ETAPA 7G - offline action margin analysis"; ""; ...
    "- Engineering result: PASS."; ...
    "- Scientific result: " + manifest.scientificResult + "."; ...
    "- Candidate feasible threshold: " + ...
        string(d.feasibleThresholdExists) + "."; ...
    sprintf("- Rest-only threshold: %.17g.", d.minimumRestOnlyThreshold); ...
    sprintf("- Movement loss at rest threshold: %.9f.", ...
        d.movementCommandLossAtRestThreshold); ...
    sprintf("- Motor 2 loss at rest threshold: %.9f.", ...
        d.motor2CommandLossAtRestThreshold); ...
    "- Threshold applied: no; training/simulation/hardware: no/no/no."];
value = strjoin(lines, newline);
end

function hashes = inventoryArtifacts(runRoot)
names = ["test_results.mat", "episode_input_hashes.csv", ...
    "episode_audit.csv", "reference_audit.csv", "profile_audit.csv", ...
    "quantization_replay_audit.csv", "action_distribution_summary.csv", ...
    "threshold_curve.csv", "threshold_decision.csv", ...
    "source_decision.csv", "action_components.csv", ...
    "stage7g_results.mat", "offline_report.md", ...
    "reproducible_command.txt"];
hashes = repmat(struct("path", "", "sha256", ""), numel(names), 1);
for idx = 1:numel(names)
    hashes(idx).path = names(idx);
    hashes(idx).sha256 = fileSha256(fullfile(runRoot, names(idx)));
end
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
commit = "unknown";
if status == 0
    commit = string(strtrim(output));
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[trackedStatus, trackedOutput] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = trackedStatus ~= 0 || ...
    strlength(strtrim(string(trackedOutput))) > 0;
end

function hash = fileSha256(path)
escaped = strrep(char(string(path)), "'", "''");
command = sprintf(['powershell -NoProfile -Command "(Get-FileHash ' ...
    '-Algorithm SHA256 -LiteralPath ''%s'').Hash"'], escaped);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7g_action_margin_analysis:HashFailed", ...
        "Could not hash %s.", path);
end
hash = string(strtrim(output));
end

function value = escapeQuote(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7g_action_margin_analysis:WriteFailed", ...
        "Could not open %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
