function results = run_residual_lift_longrun(options)
%run_residual_lift_longrun prepares a sparse-save long residual evaluation.
%
% This wrapper keeps the published Residual Lift method unchanged, but it
% is configured for long evaluation-oriented training on another machine:
% no live plots, sparse checkpointing, sparse per-episode saves, and final
% audit/test enabled.

arguments
    options = struct()
end

options = normalizeLongrunOptions(options);

paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
workspaceRoot = char(paths.workspaceRoot);

pilotOptions = struct( ...
    "baseCheckpointPath", options.baseCheckpointPath, ...
    "baseLabel", options.baseLabel, ...
    "residualScale", options.residualScale, ...
    "residualHiddenUnits", options.residualHiddenUnits, ...
    "explorationStd", options.explorationStd, ...
    "explorationStdMin", options.explorationStdMin, ...
    "explorationStdDecayRate", options.explorationStdDecayRate, ...
    "resetExperienceBufferBeforeTraining", options.resetExperienceBufferBeforeTraining, ...
    "trainingEpisodes", options.trainingEpisodes, ...
    "trainingSaveEvery", options.trainingSaveEvery, ...
    "trainingPlots", options.trainingPlots, ...
    "flagSaveTraining", options.flagSaveTraining, ...
    "episodeSaveFreq", options.episodeSaveFreq, ...
    "randomSeed", options.randomSeed, ...
    "enableDetailedActionDiagnostics", options.enableDetailedActionDiagnostics, ...
    "savePerMotorMetrics", options.savePerMotorMetrics, ...
    "auditFastSimulations", options.auditFastSimulations, ...
    "auditFullSimulations", options.auditFullSimulations, ...
    "auditTopK", options.auditTopK, ...
    "auditEveryK", options.auditEveryK, ...
    "auditTailCount", options.auditTailCount, ...
    "visualTestSimulations", options.visualTestSimulations, ...
    "alwaysRunVisualTest", options.alwaysRunVisualTest, ...
    "pretestTrackingMseMax", options.pretestTrackingMseMax, ...
    "pretestSaturationFractionMax", options.pretestSaturationFractionMax, ...
    "pretestActionL2Max", options.pretestActionL2Max, ...
    "resultsRoot", resolveLongrunResultsRoot(options.resultsRoot, workspaceRoot));

results = run_residual_lift_pilot(pilotOptions);
end

function options = normalizeLongrunOptions(options)
defaults = struct( ...
    "baseCheckpointPath", getAgent7250CheckpointPath(), ...
    "baseLabel", "Agent7250", ...
    "residualScale", 0.20, ...
    "residualHiddenUnits", 32, ...
    "explorationStd", 0.02, ...
    "explorationStdMin", 0.002, ...
    "explorationStdDecayRate", 1e-4, ...
    "resetExperienceBufferBeforeTraining", false, ...
    "trainingEpisodes", 50000, ...
    "trainingSaveEvery", 500, ...
    "trainingPlots", "none", ...
    "flagSaveTraining", true, ...
    "episodeSaveFreq", 500, ...
    "randomSeed", NaN, ...
    "enableDetailedActionDiagnostics", false, ...
    "savePerMotorMetrics", false, ...
    "auditFastSimulations", 20, ...
    "auditFullSimulations", 50, ...
    "auditTopK", 2, ...
    "auditEveryK", 500, ...
    "auditTailCount", 20, ...
    "visualTestSimulations", 50, ...
    "alwaysRunVisualTest", true, ...
    "pretestTrackingMseMax", 0.044022, ...
    "pretestSaturationFractionMax", 0.35271, ...
    "pretestActionL2Max", 0.57794, ...
    "resultsRoot", "");

fields = fieldnames(defaults);
for i = 1:numel(fields)
    if ~isfield(options, fields{i}) || isempty(options.(fields{i}))
        options.(fields{i}) = defaults.(fields{i});
    end
end

options.baseCheckpointPath = string(options.baseCheckpointPath);
options.baseLabel = string(options.baseLabel);
options.trainingPlots = string(options.trainingPlots);
end

function resultsRoot = resolveLongrunResultsRoot(requestedRoot, repoRoot)
requestedRoot = string(requestedRoot);
if strlength(requestedRoot) > 0
    resultsRoot = char(requestedRoot);
else
    resultsRoot = fullfile( ...
        repoRoot, "Agentes", "residual_lift_longrun", ...
        string(datetime("now", "Format", "yy-MM-dd HH mm ss")));
end
end
