function report = run_no_glove_stage6b_boundary_diagnostic(options)
%run_no_glove_stage6b_boundary_diagnostic diagnoses a failed smoke offline.
%
% This launcher reads saved episode logs only. It does not load an agent,
% invoke an environment, run a simulator, train, evaluate or calculate DTW.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));

[inputManifest, inputManifestPath] = loadAndValidateInput(options.stage6RunRoot);
if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage6b_boundary_diagnostic");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runDir)
    error("run_no_glove_stage6b_boundary_diagnostic:OutputExists", ...
        "Refusing to reuse output directory %s.", runDir);
end
mkdir(runDir);

clearConfigurablesOverride();
testPath = fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage6BoundaryDiagnostic.m");
testResults = runtests(testPath);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage6b_boundary_diagnostic:TestsFailed", ...
        "ETAPA 6B tests failed; diagnostic is forbidden. See %s.", runDir);
end

analysisOptions = struct( ...
    "positionMin", double(inputManifest.simulationPositionSafety.positionMin), ...
    "positionMax", double(inputManifest.simulationPositionSafety.positionMax), ...
    "positionTolerance", options.positionTolerance, ...
    "activeVelocityThreshold", options.activeVelocityThreshold, ...
    "motionTolerance", options.motionTolerance, ...
    "positionErrorTolerance", options.positionErrorTolerance, ...
    "saturationThreshold", options.saturationThreshold);
analysisArguments = namedargs2cell(analysisOptions);

seedSummaries = inputManifest.seedSummary;
if ~isstruct(seedSummaries)
    error("run_no_glove_stage6b_boundary_diagnostic:InvalidSeedSummary", ...
        "Input manifest seedSummary must be a struct or struct array.");
end
seedAnalyses = cell(numel(seedSummaries), 3);
componentTables = cell(numel(seedSummaries), 3);
motorTables = cell(numel(seedSummaries), 3);
conditionTables = cell(numel(seedSummaries), 3);
evidenceTables = cell(numel(seedSummaries), 3);
splitNames = ["training", "acceptance", "steady_rest"];
directoryFields = ["trainingDirectory", "acceptanceDirectory", "restDirectory"];
for seedIdx = 1:numel(seedSummaries)
    seed = double(seedSummaries(seedIdx).seed);
    for splitIdx = 1:numel(splitNames)
        episodeDirectory = string( ...
            seedSummaries(seedIdx).(directoryFields(splitIdx)));
        analysis = analyzeNoGloveStage6BoundaryDiagnostics( ...
            episodeDirectory, splitNames(splitIdx), analysisArguments{:});
        seedAnalyses{seedIdx, splitIdx} = analysis;
        componentTables{seedIdx, splitIdx} = addSeed( ...
            analysis.componentTable, seed);
        motorTables{seedIdx, splitIdx} = addSeed( ...
            analysis.motorSummary, seed);
        conditionTables{seedIdx, splitIdx} = addSeed( ...
            analysis.conditionSummary, seed);
        evidenceTables{seedIdx, splitIdx} = addSeed( ...
            analysis.hypothesisEvidence, seed);
    end
end

componentDiagnostics = vertcat(componentTables{:});
motorSummary = vertcat(motorTables{:});
conditionSummary = vertcat(conditionTables{:});
hypothesisEvidence = vertcat(evidenceTables{:});
keyFindings = buildKeyFindings(motorSummary, seedAnalyses);

writetable(componentDiagnostics, ...
    fullfile(runDir, "component_diagnostics.csv"));
writetable(motorSummary, fullfile(runDir, "motor_summary.csv"));
writetable(conditionSummary, fullfile(runDir, "condition_summary.csv"));
writetable(hypothesisEvidence, ...
    fullfile(runDir, "hypothesis_evidence.csv"));
save(fullfile(runDir, "stage6b_results.mat"), ...
    "componentDiagnostics", "motorSummary", "conditionSummary", ...
    "hypothesisEvidence", "keyFindings", "analysisOptions", ...
    "inputManifest", "options", "seedAnalyses", "-v7.3");

reproducibleCommand = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage6b_boundary_diagnostic(struct(" + ...
    "'stage6RunRoot','%s','resultsRoot','%s'," + ...
    "'positionTolerance',%.17g,'activeVelocityThreshold',%.17g," + ...
    "'motionTolerance',%.17g,'positionErrorTolerance',%.17g," + ...
    "'saturationThreshold',%.17g))", ...
    escape(matlabRoot), escape(options.stage6RunRoot), ...
    escape(options.resultsRoot), options.positionTolerance, ...
    options.activeVelocityThreshold, options.motionTolerance, ...
    options.positionErrorTolerance, options.saturationThreshold);
writeText(fullfile(runDir, "reproducible_command.txt"), ...
    reproducibleCommand);
writeOfflineReport(fullfile(runDir, "offline_report.md"), ...
    keyFindings, motorSummary, inputManifest, runDir);

primaryArtifacts = [ ...
    "component_diagnostics.csv", "motor_summary.csv", ...
    "condition_summary.csv", "hypothesis_evidence.csv", ...
    "stage6b_results.mat", "test_results.mat", ...
    "reproducible_command.txt", "offline_report.md"];
artifactHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(primaryArtifacts), 1);
for artifactIdx = 1:numel(primaryArtifacts)
    artifactHashes(artifactIdx).path = primaryArtifacts(artifactIdx);
    artifactHashes(artifactIdx).sha256 = fileSha256( ...
        fullfile(runDir, primaryArtifacts(artifactIdx)));
end
writetable(struct2table(artifactHashes), ...
    fullfile(runDir, "artifact_hashes.csv"));

[gitCommit, gitDirty, trackedDirty, gitStatus] = getGitState(repoRoot);
manifest = struct( ...
    "stage", "6B", ...
    "schemaVersion", 1, ...
    "result", "PASS", ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, ...
    "gitDirty", gitDirty, ...
    "gitTrackedDirty", trackedDirty, ...
    "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage6b_boundary_diagnostic", ...
    "inputStage6RunRoot", options.stage6RunRoot, ...
    "inputManifestPath", inputManifestPath, ...
    "inputManifestSha256", fileSha256(inputManifestPath), ...
    "inputGitCommit", string(inputManifest.gitCommit), ...
    "inputPhaseGatePassed", logical(inputManifest.phaseGatePassed), ...
    "inputPositionSafetyAblation", ...
        logical(inputManifest.positionSafetyAblation), ...
    "inputFinalCheckpoint", string(seedSummaries(end).finalCheckpoint), ...
    "inputFinalCheckpointSha256", ...
        fileSha256(string(seedSummaries(end).finalCheckpoint)), ...
    "seeds", double(inputManifest.seeds), ...
    "analysisOptions", analysisOptions, ...
    "temporalContract", struct( ...
        "state", "stateLog(t) before action_t", ...
        "command", "actionPwmLog(t)", ...
        "nextEncoder", "trackingPredictionHistory(t)", ...
        "reference", "referenceHistory(t) visible before action_t"), ...
    "keyFindings", keyFindings, ...
    "runTraining", false, ...
    "reinforcementLearningInvoked", false, ...
    "agentLoaded", false, ...
    "simulatorInvoked", false, ...
    "dtwCalculated", false, ...
    "stage7Executed", false, ...
    "simMotorsFromInput", logical(inputManifest.simMotors), ...
    "hardwareUsed", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "artifactHashes", artifactHashes, ...
    "outputPath", runDir);
save(fullfile(runDir, "manifest.mat"), "manifest", "artifactHashes");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct( ...
    "result", "PASS", ...
    "outputPath", runDir, ...
    "manifest", manifest, ...
    "keyFindings", keyFindings, ...
    "motorSummary", motorSummary, ...
    "hypothesisEvidence", hypothesisEvidence, ...
    "testResults", testResults);
fprintf("ETAPA 6B OFFLINE DIAGNOSTIC PASS\n");
fprintf("Output: %s\n", runDir);
disp(motorSummary);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage6b_boundary_diagnostic:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "stage6RunRoot", "", "resultsRoot", "", ...
    "positionTolerance", 1e-9, ...
    "activeVelocityThreshold", 0.005, ...
    "motionTolerance", 1e-4, ...
    "positionErrorTolerance", 1e-4, ...
    "saturationThreshold", 0.95);
allowed = string(fieldnames(defaults));
unknown = setdiff(string(fieldnames(options)), allowed);
if ~isempty(unknown)
    error("run_no_glove_stage6b_boundary_diagnostic:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
fields = fieldnames(defaults);
for fieldIdx = 1:numel(fields)
    fieldName = fields{fieldIdx};
    if ~isfield(options, fieldName) || isempty(options.(fieldName))
        options.(fieldName) = defaults.(fieldName);
    end
end
options.stage6RunRoot = string(options.stage6RunRoot);
options.resultsRoot = string(options.resultsRoot);
if ~isscalar(options.stage6RunRoot) || ...
        strlength(options.stage6RunRoot) == 0
    error("run_no_glove_stage6b_boundary_diagnostic:MissingInput", ...
        "stage6RunRoot is required.");
end
numericFields = ["positionTolerance", "activeVelocityThreshold", ...
    "motionTolerance", "positionErrorTolerance", "saturationThreshold"];
for fieldIdx = 1:numel(numericFields)
    fieldName = numericFields(fieldIdx);
    value = options.(fieldName);
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value < 0
        error("run_no_glove_stage6b_boundary_diagnostic:InvalidThreshold", ...
            "%s must be a finite nonnegative scalar.", fieldName);
    end
end
if options.saturationThreshold > 1
    error("run_no_glove_stage6b_boundary_diagnostic:InvalidThreshold", ...
        "saturationThreshold must not exceed one.");
end
end

function [manifest, manifestPath] = loadAndValidateInput(stage6RunRoot)
manifestPath = fullfile(stage6RunRoot, "manifest.json");
if ~isfile(manifestPath)
    error("run_no_glove_stage6b_boundary_diagnostic:ManifestNotFound", ...
        "Input ETAPA 6 manifest not found: %s", manifestPath);
end
manifest = jsondecode(fileread(manifestPath));
required = ["stage", "phase", "phaseGatePassed", ...
    "positionSafetyAblation", "simulationPositionSafety", ...
    "referenceSource", "observationVariant", "actionInterfaceVariant", ...
    "simMotors", "hardwareUsed", "seedSummary", "gitCommit"];
if ~all(isfield(manifest, cellstr(required)))
    error("run_no_glove_stage6b_boundary_diagnostic:InvalidManifest", ...
        "Input manifest lacks the ETAPA 6A audit contract.");
end
valid = double(manifest.stage) == 6 && string(manifest.phase) == "smoke" && ...
    ~logical(manifest.phaseGatePassed) && ...
    logical(manifest.positionSafetyAblation) && ...
    logical(manifest.simulationPositionSafety.enabled) && ...
    string(manifest.referenceSource) == "emgIntent" && ...
    string(manifest.observationVariant) == "intentMarkov60" && ...
    string(manifest.actionInterfaceVariant) == "baselineQuantized" && ...
    logical(manifest.simMotors) && ~logical(manifest.hardwareUsed);
if ~valid
    error("run_no_glove_stage6b_boundary_diagnostic:IncompatibleManifest", ...
        "ETAPA 6B requires the failed, position-limited no-glove smoke.");
end
seedSummaries = manifest.seedSummary;
directoryFields = ["trainingDirectory", "acceptanceDirectory", "restDirectory"];
requiredSeedFields = ["seed", directoryFields, "finalCheckpoint"];
for seedIdx = 1:numel(seedSummaries)
    if ~all(isfield(seedSummaries(seedIdx), cellstr(requiredSeedFields)))
        error("run_no_glove_stage6b_boundary_diagnostic:InvalidSeedSummary", ...
            "A seed summary is incomplete.");
    end
    for fieldIdx = 1:numel(directoryFields)
        if ~isfolder(string(seedSummaries(seedIdx).(directoryFields(fieldIdx))))
            error("run_no_glove_stage6b_boundary_diagnostic:EpisodeDirectoryNotFound", ...
                "Saved episode directory is missing for seed %d.", ...
                double(seedSummaries(seedIdx).seed));
        end
    end
    if ~isfile(string(seedSummaries(seedIdx).finalCheckpoint))
        error("run_no_glove_stage6b_boundary_diagnostic:CheckpointNotFound", ...
            "Final checkpoint recorded by ETAPA 6 is missing.");
    end
end
end

function output = addSeed(input, seed)
output = input;
output.seed = repmat(seed, height(output), 1);
output = movevars(output, "seed", "Before", 1);
end

function findings = buildKeyFindings(motorSummary, seedAnalyses)
acceptance = motorSummary(motorSummary.split == "acceptance", :);
rest = motorSummary(motorSummary.split == "steady_rest", :);
training = motorSummary(motorSummary.split == "training", :);
findings = struct( ...
    "schemaVersion", 1, ...
    "nextStateAlignmentMaxAbs", max(cellfun( ...
        @(value) value.nextStateAlignmentMaxAbs, seedAnalyses), [], "all"), ...
    "referenceAlignmentMaxAbs", max(cellfun( ...
        @(value) value.referenceAlignmentMaxAbs, seedAnalyses), [], "all"), ...
    "acceptanceActiveReferenceStepsByMotor", ...
        vectorByMotor(acceptance, "activeReferenceSteps"), ...
    "acceptanceNoMotionActiveStepsByMotor", ...
        vectorByMotor(acceptance, "noMotionActiveSteps"), ...
    "acceptanceNoMotionBoundaryOrSafetyByMotor", ...
        vectorByMotor(acceptance, "noMotionBoundaryOrSafetySteps"), ...
    "acceptanceNoMotionInteriorZeroPwmByMotor", ...
        vectorByMotor(acceptance, "noMotionInteriorZeroPwmSteps"), ...
    "acceptanceNoMotionInteriorNonzeroPwmByMotor", ...
        vectorByMotor(acceptance, "noMotionInteriorNonzeroPwmSteps"), ...
    "acceptanceCommandOpposesVelocityByMotor", ...
        vectorByMotor(acceptance, "wrongCommandDirectionActiveSteps"), ...
    "acceptanceCommandOpposesPositionErrorByMotor", ...
        vectorByMotor(acceptance, "wrongCommandPositionErrorSteps"), ...
    "acceptanceResponseOpposesCommandByMotor", ...
        vectorByMotor(acceptance, "responseOpposesCommandSteps"), ...
    "acceptanceOutwardReferenceAtLimitByMotor", ...
        vectorByMotor(acceptance, "outwardReferenceAtLimitSteps"), ...
    "acceptanceOutwardCommandAtBoundaryByMotor", ...
        vectorByMotor(acceptance, "outwardCommandAtBoundarySteps"), ...
    "acceptanceSaturatedZeroReferenceByMotor", ...
        vectorByMotor(acceptance, "saturatedZeroReferenceSteps"), ...
    "restNonzeroPwmZeroReferenceByMotor", ...
        vectorByMotor(rest, "nonzeroPwmZeroReferenceSteps"), ...
    "restZeroControlDemandStepsByMotor", ...
        vectorByMotor(rest, "zeroControlDemandSteps"), ...
    "restNonzeroPwmZeroControlDemandByMotor", ...
        vectorByMotor(rest, "nonzeroPwmZeroControlDemandSteps"), ...
    "restSaturatedZeroReferenceByMotor", ...
        vectorByMotor(rest, "saturatedZeroReferenceSteps"), ...
    "restSaturatedZeroControlDemandByMotor", ...
        vectorByMotor(rest, "saturatedZeroControlDemandSteps"), ...
    "restOutwardCommandAtBoundaryByMotor", ...
        vectorByMotor(rest, "outwardCommandAtBoundarySteps"), ...
    "trainingSafetyInterventionSamplesByMotor", ...
        vectorByMotor(training, "safetyInterventionSampleCount"), ...
    "causalClaimMade", false, ...
    "dtwCalculated", false, ...
    "stage7Executed", false);
end

function values = vectorByMotor(tableValue, fieldName)
values = zeros(1, 4);
for motorIdx = 1:4
    rows = tableValue.motor == motorIdx;
    values(motorIdx) = sum(tableValue.(fieldName)(rows));
end
end

function writeOfflineReport(reportPath, findings, motorSummary, inputManifest, runDir)
acceptance = motorSummary(motorSummary.split == "acceptance", :);
rest = motorSummary(motorSummary.split == "steady_rest", :);
lines = strings(0, 1);
lines(end+1) = "# ETAPA 6B — diagnóstico offline de borde y respuesta";
lines(end+1) = "";
lines(end+1) = "- Resultado de ejecución: PASS.";
lines(end+1) = "- Gate de la política de entrada: " + ...
    string(inputManifest.phaseGatePassed) + ".";
lines(end+1) = "- Error máximo de alineación estado siguiente: " + ...
    compose("%.17g", findings.nextStateAlignmentMaxAbs) + ".";
lines(end+1) = "- Error máximo de alineación de referencia: " + ...
    compose("%.17g", findings.referenceAlignmentMaxAbs) + ".";
lines(end+1) = "- No se cargó agente, no se invocó simulador y no se calculó DTW.";
lines(end+1) = "";
lines(end+1) = "## Aceptación por motor";
lines(end+1) = "";
acceptanceLines = strings(1, 4);
acceptanceFormat = "- M%d: referencia activa %d; sin movimiento %d " + ...
    "(borde/seguridad %d, interior PWM=0 %d, interior PWM~=0 %d); " + ...
    "PWM opuesto a v_ref %d; PWM opuesto a q_ref-q %d; " + ...
    "respuesta opuesta a PWM %d.";
for motorIdx = 1:4
    row = acceptance(acceptance.motor == motorIdx, :);
    acceptanceLines(motorIdx) = sprintf(acceptanceFormat, motorIdx, ...
        row.activeReferenceSteps, row.noMotionActiveSteps, ...
        row.noMotionBoundaryOrSafetySteps, ...
        row.noMotionInteriorZeroPwmSteps, ...
        row.noMotionInteriorNonzeroPwmSteps, ...
        row.wrongCommandDirectionActiveSteps, ...
        row.wrongCommandPositionErrorSteps, ...
        row.responseOpposesCommandSteps);
end
lines = [lines, acceptanceLines];
lines(end+1) = "";
lines(end+1) = "## Reposo por motor";
lines(end+1) = "";
restLines = strings(1, 4);
restFormat = "- M%d: PWM no cero con v_ref=0: %d; " + ...
    "PWM no cero sin demanda v_ref/q_ref-q: %d; " + ...
    "saturación con v_ref=0: %d; saturación sin demanda: %d; " + ...
    "PWM hacia fuera en límite: %d.";
for motorIdx = 1:4
    row = rest(rest.motor == motorIdx, :);
    restLines(motorIdx) = sprintf(restFormat, motorIdx, ...
        row.nonzeroPwmZeroReferenceSteps, ...
        row.nonzeroPwmZeroControlDemandSteps, ...
        row.saturatedZeroReferenceSteps, ...
        row.saturatedZeroControlDemandSteps, ...
        row.outwardCommandAtBoundarySteps);
end
lines = [lines, restLines];
lines(end+1) = "";
lines(end+1) = "Los conteos son evidencia observacional estratificada; no se declara " + ...
    "una causa raíz única ni se autoriza ETAPA 7.";
lines(end+1) = "";
lines(end+1) = "Ruta: `" + string(runDir) + "`.";
writeText(reportPath, strjoin(lines, newline));
end

function escaped = escape(value)
escaped = strrep(char(string(value)), "'", "''");
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[workingStatus, ~] = system(sprintf('git -C "%s" diff --quiet', repoRoot));
[indexStatus, ~] = system(sprintf('git -C "%s" diff --cached --quiet', repoRoot));
trackedDirty = workingStatus ~= 0 || indexStatus ~= 0;
end

function hash = fileSha256(filePath)
escapedPath = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escapedPath);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage6b_boundary_diagnostic:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = upper(string(strtrim(output)));
end

function writeText(filePath, value)
fid = fopen(filePath, "w");
if fid < 0
    error("run_no_glove_stage6b_boundary_diagnostic:WriteFailed", ...
        "Could not open %s.", filePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
