function report = run_no_glove_stage7o_bit_counterfactual_audit(options)
%run_no_glove_stage7o_bit_counterfactual_audit audits bits 61/62 offline.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
addpath(genpath(fullfile(matlabRoot, "tests")));
addpath(genpath(fullfile(matlabRoot, "workflows", "published")));

parent = validateStage7n(options.stage7nRunRoot);
if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage7o_bit_counterfactual");
end
runRoot = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runRoot)
    error("run_no_glove_stage7o_bit_counterfactual_audit:OutputExists", ...
        "Refusing to reuse %s.", runRoot);
end
mkdir(runRoot);

testFiles = [ ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testNoGloveStage7oBitCounterfactual.m"), ...
    fullfile(matlabRoot, "tests", "no_glove", ...
        "testIntentDeclaredRestHoldMarkov62.m")];
testResults = runtests(testFiles);
save(fullfile(runRoot, "preflight_test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage7o_bit_counterfactual_audit:TestsFailed", ...
        "ETAPA 7O tests failed. See %s.", runRoot);
end

[checkpointAudit, pathsByEpisode, controlPath] = ...
    auditCheckpoints(parent.checkpointSummary);
actuator = loadActuatorContract(pathsByEpisode("200"));
sources = struct( ...
    "training", string(fileparts(pathsByEpisode("200"))), ...
    "acceptance", parent.primaryCandidate.acceptanceDirectory, ...
    "steadyRest", parent.primaryCandidate.restDirectory);
corpus = loadNoGloveStage7oBitCorpus(sources, ...
    "maxPerContext", options.maxPerContext);
corpus.inventory.sha256 = strings(height(corpus.inventory), 1);
corpus.inventory.bytes = zeros(height(corpus.inventory), 1);
for fileIdx = 1:height(corpus.inventory)
    pathValue = corpus.inventory.filePath(fileIdx);
    corpus.inventory.sha256(fileIdx) = fileSha256(pathValue);
    info = dir(pathValue);
    corpus.inventory.bytes(fileIdx) = info.bytes;
end
save(fullfile(runRoot, "counterfactual_corpus.mat"), ...
    "corpus", "sources", "-v7.3");
writetable(corpus.metadata, fullfile(runRoot, "corpus_rows.csv"));
writetable(corpus.inventory, fullfile(runRoot, "input_inventory.csv"));
writetable(corpus.contextCounts, fullfile(runRoot, "context_counts.csv"));
writetable(corpus.sourceCounts, fullfile(runRoot, "source_counts.csv"));

episodes = [50, 100, 150, 200];
effectParts = cell(numel(episodes), 1);
gradientParts = cell(numel(episodes), 1);
replayRows = repmat(emptyReplayRow(), numel(episodes), 1);
gradientAuditRows = repmat(emptyGradientAuditRow(), numel(episodes), 1);
for episodeIdx = 1:numel(episodes)
    episode = episodes(episodeIdx);
    agent = loadSavedAgent(pathsByEpisode(string(episode)));
    value = evaluateNoGloveStage7oCheckpoint( ...
        agent, episode, corpus, actuator);
    effectParts{episodeIdx} = value.effects;
    gradientParts{episodeIdx} = value.gradients;
    replayRows(episodeIdx) = addEpisode(value.replayAudit, episode);
    gradientAuditRows(episodeIdx) = addEpisode( ...
        value.gradientAudit, episode);
    clear agent value
end
effects = vertcat(effectParts{:});
gradients = vertcat(gradientParts{:});
replayAudit = struct2table(replayRows);
gradientAudit = struct2table(gradientAuditRows);
writetable(replayAudit, fullfile(runRoot, "actor_replay_audit.csv"));
writetable(gradientAudit, fullfile(runRoot, "gradient_audit.csv"));
if any(~gradientAudit.withinTolerance)
    error("run_no_glove_stage7o_bit_counterfactual_audit:GradientAudit", ...
        "Analytic gradients did not match finite differences.");
end
primaryReplay = replayAudit(replayAudit.checkpointEpisode == 200, :);
if primaryReplay.serialSavedMaximumError > 1e-12 || ...
        primaryReplay.batchSerialMaximumError > 1e-6 || ...
        primaryReplay.batchSerialPwmMismatchCount ~= 0
    error("run_no_glove_stage7o_bit_counterfactual_audit:ActorReplay", ...
        "Frozen Agent200 does not reproduce its published evaluation.");
end

analysis = analyzeNoGloveStage7oBitEffects(effects, gradients);
[controlRows, controlAudit] = evaluateControlReference( ...
    controlPath, corpus, actuator);
operationalChecks = struct( ...
    "parentValidated", parent.validated, ...
    "checkpointHashesMatched", all(checkpointAudit.hashMatched), ...
    "primaryCheckpointsFrozen", ...
        any(checkpointAudit.label == "control60" & ...
            checkpointAudit.checkpointEpisode == 200) && ...
        any(checkpointAudit.label == "candidate62" & ...
            checkpointAudit.checkpointEpisode == 200), ...
    "corpusCausalReplay", corpus.causalReplayMismatchCount == 0, ...
    "prefixInvariant", isequal(corpus.states(:, 1:60), corpus.prefix60), ...
    "actorReplay", primaryReplay.serialSavedMaximumError <= 1e-12 && ...
        primaryReplay.batchSerialMaximumError <= 1e-6 && ...
        primaryReplay.batchSerialPwmMismatchCount == 0, ...
    "gradientAudit", all(gradientAudit.withinTolerance), ...
    "allFinite", all(isfinite(effects.deltaRaw)) && ...
        all(isfinite(gradients.gradient)) && controlAudit.allFinite, ...
    "oodExcluded", ~analysis.oodIncludedInClassification, ...
    "noTraining", true, "noEnvironment", true, ...
    "noSimulation", true, "noHardware", true, "noDtw", true);
if ~all(struct2array(operationalChecks))
    error("run_no_glove_stage7o_bit_counterfactual_audit:OperationalGate", ...
        "An ETAPA 7O operational invariant failed.");
end

effectSummary = analysis.effectSummary;
overallSummary = analysis.overallSummary;
gradientSummary = analysis.gradientSummary;
oodSummary = effectSummary(~effectSummary.causalValid, :);
causalSummary = effectSummary(effectSummary.causalValid, :);
writetable(checkpointAudit, fullfile(runRoot, "checkpoint_audit.csv"));
writetable(replayAudit, fullfile(runRoot, "actor_replay_audit.csv"));
writetable(gradientAudit, fullfile(runRoot, "gradient_audit.csv"));
writetable(effects, fullfile(runRoot, "counterfactual_effects.csv"));
writetable(gradients, fullfile(runRoot, "bit_gradients.csv"));
writetable(causalSummary, fullfile(runRoot, "causal_effect_summary.csv"));
writetable(oodSummary, fullfile(runRoot, "ood_01_summary.csv"));
writetable(overallSummary, fullfile(runRoot, "overall_summary.csv"));
writetable(gradientSummary, fullfile(runRoot, "gradient_summary.csv"));
writetable(controlRows, fullfile(runRoot, "control60_reference.csv"));
writetable(analysis.classificationAudit, ...
    fullfile(runRoot, "classification.csv"));
writetable(struct2table(operationalChecks), ...
    fullfile(runRoot, "operational_checks.csv"));

[gitCommit, gitDirty, gitTrackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", "7O", "schemaVersion", 1, "result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "recommendation", analysis.recommendation, ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, "gitDirty", gitDirty, ...
    "gitTrackedDirty", gitTrackedDirty, "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage7o_bit_counterfactual_audit", ...
    "preregistrationCommit", ...
        "09e04c779375bcb9ebc71c36debd0d47c294023e", ...
    "protocolAmendment", struct( ...
        "document", "docs/no_glove_experiment/07o_protocol_amendment.md", ...
        "reason", "singlePrecisionFiniteDifferenceCancellation", ...
        "classificationObservedBeforeAmendment", false, ...
        "failedAttemptPath", ...
            "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7o_artifacts\stage7o_final\2026-08-29_22-10-43-085"), ...
    "parentStage7n", rmfield(parent, ...
        {'checkpointSummary', 'primaryCandidate'}), ...
    "checkpointAudit", table2struct(checkpointAudit), ...
    "primaryCheckpointEpisode", 200, ...
    "secondaryCheckpointEpisodes", [50, 100, 150], ...
    "control60PrimaryCheckpointPath", controlPath, ...
    "candidate62PrimaryCheckpointPath", pathsByEpisode("200"), ...
    "corpusSources", sources, ...
    "corpusAvailableRowCount", corpus.allAvailableRowCount, ...
    "corpusSelectedRowCount", corpus.selectedRowCount, ...
    "maxPerContext", corpus.maxPerContext, ...
    "corpusContentSha256", fileSha256(fullfile( ...
        runRoot, "counterfactual_corpus.mat")), ...
    "contrasts", ["restEffect:00To10", "latchEffect:10To11"], ...
    "oodContrast", "oodInvalid01:00To01", ...
    "oodIncludedInClassification", false, ...
    "rawTolerance", 1e-6, "dominanceMargin", 0.05, ...
    "gradientValidation", struct("finiteDifferenceStep", 1e-2, ...
        "absoluteTolerance", 1e-4, "relativeTolerance", 5e-2), ...
    "macroNetBenefit", analysis.macroNetBenefit, ...
    "positiveCellCount", analysis.positiveCellCount, ...
    "negativeCellCount", analysis.negativeCellCount, ...
    "rawSensitive", analysis.rawSensitive, ...
    "pwmSensitive", analysis.pwmSensitive, ...
    "operationalChecks", operationalChecks, ...
    "actuator", actuator, ...
    "rewardChanged", false, "quantizationChanged", false, ...
    "td3Changed", false, "simulatorChanged", false, ...
    "safetyLayerChanged", false, ...
    "reinforcementLearningUsed", false, "runTraining", false, ...
    "environmentUsed", false, "simulationUsed", false, ...
    "simMotors", true, "hardwareUsed", false, ...
    "myoUsed", false, "gloveUsed", false, "dtwCalculated", false, ...
    "agent7250Loaded", false, "agent7250Used", false, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "pilotAuthorized", false, "pilotExecuted", false, ...
    "campaignAuthorized", false, "campaignExecuted", false, ...
    "issuesForNextStage", [ ...
        "pwmDiscontinuity0To64", ...
        "smallSpecificSaturationPenalty", ...
        "sharedRestGate", ...
        "numerousSafetyInterventions"], ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "outputPath", runRoot);

save(fullfile(runRoot, "stage7o_results.mat"), ...
    "manifest", "analysis", "effects", "gradients", ...
    "effectSummary", "overallSummary", "gradientSummary", ...
    "oodSummary", "controlRows", "controlAudit", ...
    "checkpointAudit", "replayAudit", "gradientAudit", ...
    "operationalChecks", "corpus", "actuator", "options", "-v7.3");
writeText(fullfile(runRoot, "offline_report.md"), ...
    buildOfflineReport(manifest, analysis, corpus.contextCounts));
writeText(fullfile(runRoot, "reproducible_command.txt"), ...
    buildReproducibleCommand(matlabRoot, options, runRoot));
manifest.artifactHashes = inventoryArtifacts(runRoot);
writeText(fullfile(runRoot, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct("result", "PASS", ...
    "scientificResult", analysis.classification, ...
    "recommendation", analysis.recommendation, ...
    "outputPath", runRoot, "manifest", manifest, ...
    "analysis", analysis, "contextCounts", corpus.contextCounts);
fprintf("ETAPA 7O BIT COUNTERFACTUAL AUDIT PASS\n");
fprintf("Classification: %s\n", analysis.classification);
fprintf("Recommendation: %s\n", analysis.recommendation);
fprintf("Output: %s\n", runRoot);
disp(analysis.primaryContrasts);
disp(corpus.contextCounts);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage7o_bit_counterfactual_audit:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "resultsRoot", "", ...
    "stage7nRunRoot", ...
        "C:\Users\Cesarbmm\ProtesisPracticas_no_glove_stage7n_artifacts\stage7n_corrected_final\2026-08-29_07-34-46-814", ...
    "maxPerContext", 512);
unknown = setdiff(string(fieldnames(options)), string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage7o_bit_counterfactual_audit:UnknownOption", ...
        "Unknown option(s): %s", strjoin(unknown, ", "));
end
names = fieldnames(defaults);
for idx = 1:numel(names)
    name = names{idx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.resultsRoot = string(options.resultsRoot);
options.stage7nRunRoot = string(options.stage7nRunRoot);
if options.maxPerContext ~= 512
    error("run_no_glove_stage7o_bit_counterfactual_audit:ProtocolChanged", ...
        "ETAPA 7O requires maxPerContext=512.");
end
end

function parent = validateStage7n(runRoot)
manifestPath = fullfile(runRoot, "manifest.json");
summaryPath = fullfile(runRoot, "checkpoint_summary.csv");
if ~isfile(manifestPath) || ~isfile(summaryPath)
    error("run_no_glove_stage7o_bit_counterfactual_audit:MissingStage7n", ...
        "Canonical ETAPA 7N artifacts are missing.");
end
expectedHash = ...
    "082DADB41DAA1DAB6AE2B5E02AE15191479410F10B5DF0398837814BFC53D480";
actualHash = fileSha256(manifestPath);
m = jsondecode(fileread(manifestPath));
valid = actualHash == expectedHash && string(m.stage) == "7N" && ...
    string(m.result) == "PASS" && ...
    string(m.scientificResult) == "actionRegularityGateFailed" && ...
    ~logical(m.hardwareUsed) && ~logical(m.dtwCalculated);
if ~valid
    error("run_no_glove_stage7o_bit_counterfactual_audit:Stage7nChanged", ...
        "ETAPA 7N does not match the pre-registered parent.");
end
summary = readtable(summaryPath, "TextType", "string");
primary = summary(summary.variant == "candidate62" & ...
    summary.episode == 200, :);
if height(primary) ~= 1
    error("run_no_glove_stage7o_bit_counterfactual_audit:PrimaryRow", ...
        "ETAPA 7N must contain exactly one candidate62 Agent200 row.");
end
parent = struct("runRoot", runRoot, "manifestPath", manifestPath, ...
    "manifestSha256", actualHash, "gitCommit", string(m.gitCommit), ...
    "scientificResult", string(m.scientificResult), ...
    "validated", true, "checkpointSummary", summary, ...
    "primaryCandidate", table2struct(primary));
end

function [audit, candidatePaths, controlPath] = auditCheckpoints(summary)
expectedEpisodes = [50, 100, 150, 200];
expectedCandidateHashes = [ ...
    "B4E9D705EB713DC1507B0FD55785A24186C239C0BF263F38E06E3E0FE792BA55", ...
    "3F82182EE3F99FBEF23D327A76900B13A9B481FF9EBB707F66AD4D74D2F7F17F", ...
    "301231C840DF2E6704149AF380D496B84575D66C50AB422737C753A9287850FC", ...
    "2A51F0F1F8800C2F44F6C632109EBB0A3E146907496A47EA0DED85450AB92E69"];
candidatePaths = dictionary(string.empty, string.empty);
rows = cell(5, 1);
for idx = 1:numel(expectedEpisodes)
    episode = expectedEpisodes(idx);
    match = summary(summary.variant == "candidate62" & ...
        summary.episode == episode, :);
    if height(match) ~= 1
        error("run_no_glove_stage7o_bit_counterfactual_audit:CheckpointRow", ...
            "Missing candidate62 Agent%d.", episode);
    end
    path = string(match.checkpointPath);
    actual = fileSha256(path);
    expected = expectedCandidateHashes(idx);
    rows{idx} = table("candidate62", episode, path, expected, actual, ...
        actual == expected, episode == 200, ...
        'VariableNames', ["label", "checkpointEpisode", ...
        "checkpointPath", "expectedSha256", "actualSha256", ...
        "hashMatched", "primary"]);
    candidatePaths(string(episode)) = path;
end
control = summary(summary.variant == "control60" & ...
    summary.episode == 200, :);
if height(control) ~= 1
    error("run_no_glove_stage7o_bit_counterfactual_audit:ControlRow", ...
        "Missing control60 Agent200.");
end
controlPath = string(control.checkpointPath);
expected = ...
    "440F003450A368A13A0E5DACB04FD7755BB929033EB879B217E47F32B5AA185E";
actual = fileSha256(controlPath);
rows{5} = table("control60", 200, controlPath, expected, actual, ...
    actual == expected, true, ...
    'VariableNames', ["label", "checkpointEpisode", ...
    "checkpointPath", "expectedSha256", "actualSha256", ...
    "hashMatched", "primary"]);
audit = vertcat(rows{:});
if ~all(audit.hashMatched)
    error("run_no_glove_stage7o_bit_counterfactual_audit:CheckpointChanged", ...
        "A frozen checkpoint hash changed.");
end
end

function actuator = loadActuatorContract(checkpointPath)
configPath = fullfile(fileparts(checkpointPath), "00_configs.mat");
data = load(configPath, "configs");
c = data.configs;
valid = string(c.actionInterfaceVariant) == "baselineQuantized" && ...
    logical(c.quantizeCommandsForSimulation) && ~logical(c.unifyActions) && ...
    c.actionCommandActivationThreshold == 0.05 && ...
    isequal(double(c.actionCommandLevels), ...
        [0, 64, 96, 128, 160, 192, 224, 255]) && ...
    all(double(c.speeds) == 255);
% The saved config belongs to training and therefore run_training=true.
valid = valid && logical(c.run_training) && logical(c.simMotors) && ...
    ~logical(c.connect_glove) && ...
    string(c.rewardType) == "trackingIntentActionRateReward";
if ~valid
    error("run_no_glove_stage7o_bit_counterfactual_audit:ActuatorContract", ...
        "Frozen Agent200 configuration changed.");
end
actuator = struct("interface", "baselineQuantized", ...
    "maxPwm", 255, "activationThreshold", 0.05, ...
    "commandLevels", double(c.actionCommandLevels), ...
    "saturationThreshold", 0.95);
end

function [summary, audit] = evaluateControlReference( ...
        checkpointPath, corpus, actuator)
agent = loadSavedAgent(checkpointPath);
actor = getActor(agent);
model = getModel(actor);
raw = evaluateFrozenActorModelStates(model, corpus.prefix60);
[effective, pwm] = quantizeRows(raw, actuator);
contexts = unique(corpus.metadata.context, "stable");
parts = cell(numel(contexts)*4, 1);
cursor = 0;
for context = contexts'
    for motor = 1:4
        mask = corpus.metadata.context == context;
        cursor = cursor+1;
        parts{cursor} = table(context, motor, sum(mask), ...
            mean(raw(mask, motor)), mean(abs(raw(mask, motor))), ...
            mean(abs(pwm(mask, motor))), mean(pwm(mask, motor) ~= 0), ...
            mean(abs(effective(mask, motor)) >= 0.95), ...
            'VariableNames', ["context", "motor", "sampleCount", ...
            "meanRawAction", "meanAbsRawAction", "meanAbsPwm", ...
            "commandActiveFraction", "saturationFraction"]);
    end
end
summary = vertcat(parts{1:cursor});
audit = struct("allFinite", all(isfinite([raw(:); effective(:); pwm(:)])), ...
    "stateCount", size(raw, 1), "checkpointPath", checkpointPath, ...
    "checkpointSha256", fileSha256(checkpointPath));
end

function [effective, pwm] = quantizeRows(raw, actuator)
effective = nan(size(raw));
pwm = nan(size(raw));
for rowIdx = 1:size(raw, 1)
    [e, p] = quantizeBaselineAction(raw(rowIdx, :), ...
        actuator.maxPwm, actuator.activationThreshold, ...
        actuator.commandLevels);
    effective(rowIdx, :) = double(e(:))';
    pwm(rowIdx, :) = double(p(:))';
end
end

function row = emptyReplayRow()
row = struct("checkpointEpisode", 0, "evaluatedRowCount", 0, ...
    "serialSavedMaximumError", NaN, ...
    "batchSerialMaximumError", NaN, ...
    "batchSerialPwmMismatchCount", NaN);
end

function row = emptyGradientAuditRow()
row = struct("checkpointEpisode", 0, "sampleCount", 0, ...
    "step", NaN, "absoluteTolerance", NaN, ...
    "relativeTolerance", NaN, "maximumAbsoluteError", NaN, ...
    "maximumTolerance", NaN, "withinTolerance", false);
end

function output = addEpisode(input, episode)
if isfield(input, "withinTolerance")
    output = input;
    output.checkpointEpisode = episode;
    output = orderfields(output, fieldnames(emptyGradientAuditRow()));
else
    output = input;
    output.checkpointEpisode = episode;
    output = orderfields(output, fieldnames(emptyReplayRow()));
end
end

function hashes = inventoryArtifacts(runRoot)
names = ["counterfactual_corpus.mat", "corpus_rows.csv", ...
    "input_inventory.csv", "context_counts.csv", "source_counts.csv", ...
    "checkpoint_audit.csv", "actor_replay_audit.csv", ...
    "gradient_audit.csv", "counterfactual_effects.csv", ...
    "bit_gradients.csv", "causal_effect_summary.csv", ...
    "ood_01_summary.csv", "overall_summary.csv", ...
    "gradient_summary.csv", "control60_reference.csv", ...
    "classification.csv", "operational_checks.csv", ...
    "stage7o_results.mat", "offline_report.md", ...
    "reproducible_command.txt"];
hashes = repmat(struct("artifact", "", "sha256", ""), ...
    numel(names), 1);
for idx = 1:numel(names)
    path = fullfile(runRoot, names(idx));
    hashes(idx) = struct("artifact", names(idx), ...
        "sha256", fileSha256(path));
end
end

function command = buildReproducibleCommand(matlabRoot, options, runRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage7o_bit_counterfactual_audit(struct(" + ...
    "'resultsRoot','%s','stage7nRunRoot','%s'," + ...
    "'maxPerContext',512))", escape(matlabRoot), ...
    escape(string(fileparts(runRoot))), escape(options.stage7nRunRoot));
end

function textValue = buildOfflineReport(manifest, analysis, contextCounts)
primary = analysis.primaryContrasts;
lines = [ ...
    "# ETAPA 7O — auditoría contrafactual de bits 61/62"; ""; ...
    "- Resultado de ejecución: PASS."; ...
    "- Clasificación: `" + manifest.scientificResult + "`."; ...
    "- Recomendación: `" + manifest.recommendation + "`."; ...
    "- Entrenamiento/Env/simulación/hardware/DTW: no/no/no/no/no."; ...
    "- Agent200 es primario; 50/100/150 son secundarios."; ""; ...
    sprintf("- Filas disponibles/seleccionadas: %d/%d.", ...
        manifest.corpusAvailableRowCount, ...
        manifest.corpusSelectedRowCount); ...
    sprintf("- macroNetBenefit: %.9g.", manifest.macroNetBenefit); ...
    sprintf("- Celdas favorables/adversas: %d/%d.", ...
        manifest.positiveCellCount, manifest.negativeCellCount); ...
    ""; "## Contrastes primarios"; ""; ...
    "Véase `overall_summary.csv` y `causal_effect_summary.csv`."; ...
    "Filas primarias: " + string(height(primary)) + "."; ...
    ""; "## Contextos"; ""; ...
    "Véase `context_counts.csv`; contextos registrados: " + ...
        string(height(contextCounts)) + "."; ...
    ""; "No se autorizó piloto ni campaña." ...
    ];
textValue = strjoin(lines, newline);
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=no', repoRoot));
trackedDirty = status ~= 0 || strlength(strtrim(string(output))) > 0;
end

function hash = fileSha256(filePath)
escaped = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escaped);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage7o_bit_counterfactual_audit:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = string(strtrim(output));
end

function value = escape(value)
value = strrep(char(string(value)), "'", "''");
end

function writeText(path, value)
fid = fopen(path, "w");
if fid < 0
    error("run_no_glove_stage7o_bit_counterfactual_audit:WriteFailed", ...
        "Could not write %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
