function report = run_no_glove_stage6c_matched_controller(options)
%run_no_glove_stage6c_matched_controller paired Agent200/P comparison.
%
% Reads immutable ETAPA 6A Agent200 traces and simulates the validated
% ETAPA 5 P controller against exactly the same q_ref, v_ref and initial
% position. It does not load an agent, train RL, calculate DTW or use
% hardware.

arguments
    options struct = struct()
end

options = normalizeOptions(options);
paths = resolveMatlabCodePaths(string(mfilename("fullpath")));
matlabRoot = string(paths.matlabRoot);
repoRoot = string(paths.workspaceRoot);
originalDir = string(pwd);
cleanup = onCleanup(@() cleanupRuntime(originalDir));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "tests")));
clearConfigurablesOverride();

[inputManifest, inputManifestPath] = loadInputManifest( ...
    options.stage6RunRoot);
seedSummary = inputManifest.seedSummary;
if numel(seedSummary) ~= 1 || double(seedSummary.seed) ~= 11 || ...
        ~endsWith(string(seedSummary.finalCheckpoint), "Agent200.mat")
    error("run_no_glove_stage6c_matched_controller:UnexpectedSource", ...
        "ETAPA 6C requires the bounded seed-11 Agent200 smoke source.");
end

if strlength(options.resultsRoot) == 0
    options.resultsRoot = fullfile(repoRoot, "Agentes", ...
        "no_glove_intent_control", "stage6c_matched_controller");
end
runDir = fullfile(options.resultsRoot, ...
    string(datetime("now", "Format", "yyyy-MM-dd_HH-mm-ss-SSS")));
if isfolder(runDir)
    error("run_no_glove_stage6c_matched_controller:OutputExists", ...
        "Refusing to reuse output directory %s.", runDir);
end
mkdir(runDir);

testPath = fullfile(matlabRoot, "tests", "no_glove", ...
    "testNoGloveStage6cMatchedController.m");
testResults = runtests(testPath);
save(fullfile(runDir, "test_results.mat"), "testResults");
if ~all([testResults.Passed])
    error("run_no_glove_stage6c_matched_controller:TestsFailed", ...
        "ETAPA 6C tests failed; comparison is forbidden. See %s.", runDir);
end

seedRoot = fileparts(fileparts(string(seedSummary.trainingDirectory)));
profilePath = fullfile(seedRoot, "effective_training_profile.mat");
if ~isfile(profilePath)
    error("run_no_glove_stage6c_matched_controller:ProfileNotFound", ...
        "Effective ETAPA 6A profile not found: %s.", profilePath);
end
profileData = load(profilePath, "profile");
profile = buildMatchedProfile(profileData.profile);
save(fullfile(runDir, "effective_stage6c_profile.mat"), ...
    "profile", "options");

acceptanceDir = string(seedSummary.acceptanceDirectory);
restDir = string(seedSummary.restDirectory);
sourceHashesBefore = inventorySourceEpisodes(acceptanceDir, restDir);

evaluationOptions = struct( ...
    "activeVelocityThreshold", options.activeVelocityThreshold, ...
    "motionTolerance", options.motionTolerance, ...
    "positionTolerance", options.positionTolerance, ...
    "saturationThreshold", options.saturationThreshold, ...
    "simulatorSamplingPeriod", options.simulatorSamplingPeriod);
evaluationArguments = namedargs2cell(evaluationOptions);
acceptance = evaluateNoGloveStage6cMatchedController( ...
    acceptanceDir, profile, "acceptance", evaluationArguments{:});
rest = evaluateNoGloveStage6cMatchedController( ...
    restDir, profile, "steady_rest", evaluationArguments{:});

sourceHashesAfter = inventorySourceEpisodes(acceptanceDir, restDir);
if ~isequal(sourceHashesBefore, sourceHashesAfter)
    error("run_no_glove_stage6c_matched_controller:SourceModified", ...
        "An immutable source episode changed during ETAPA 6C.");
end
sourceEpisodeHashes = sourceHashesBefore;

comparisonSummary = [addSplit(acceptance.aggregateSummary, "acceptance"); ...
    addSplit(rest.aggregateSummary, "steady_rest")];
motorSummary = [addSplit(acceptance.motorSummary, "acceptance"); ...
    addSplit(rest.motorSummary, "steady_rest")];
episodeSummary = [addSplit(acceptance.episodeSummary, "acceptance"); ...
    addSplit(rest.episodeSummary, "steady_rest")];
pairingSummary = [addSplit(acceptance.pairingTable, "acceptance"); ...
    addSplit(rest.pairingTable, "steady_rest")];

writetable(comparisonSummary, ...
    fullfile(runDir, "comparison_summary.csv"));
writetable(motorSummary, fullfile(runDir, "motor_summary.csv"));
writetable(episodeSummary, fullfile(runDir, "episode_summary.csv"));
writetable(pairingSummary, fullfile(runDir, "pairing_summary.csv"));
writetable(sourceEpisodeHashes, ...
    fullfile(runDir, "source_episode_hashes.csv"));
save(fullfile(runDir, "stage6c_results.mat"), ...
    "acceptance", "rest", "comparisonSummary", "motorSummary", ...
    "episodeSummary", "pairingSummary", "sourceEpisodeHashes", ...
    "evaluationOptions", "inputManifest", "-v7.3");

reproducibleCommand = buildReproducibleCommand( ...
    matlabRoot, options, fileparts(runDir));
writeText(fullfile(runDir, "reproducible_command.txt"), ...
    reproducibleCommand);
writeOfflineReport(fullfile(runDir, "offline_report.md"), ...
    comparisonSummary, acceptance, rest, profile, runDir);

primaryArtifacts = [ ...
    "comparison_summary.csv", "motor_summary.csv", ...
    "episode_summary.csv", "pairing_summary.csv", ...
    "source_episode_hashes.csv", "stage6c_results.mat", ...
    "effective_stage6c_profile.mat", "test_results.mat", ...
    "reproducible_command.txt", "offline_report.md"];
artifactHashes = repmat(struct("path", "", "sha256", ""), ...
    numel(primaryArtifacts), 1);
for artifactIdx = 1:numel(primaryArtifacts)
    artifactHashes(artifactIdx).path = primaryArtifacts(artifactIdx);
    artifactHashes(artifactIdx).sha256 = fileSha256( ...
        fullfile(runDir, primaryArtifacts(artifactIdx)));
end
writetable(struct2table(artifactHashes), ...
    fullfile(runDir, "artifact_hashes.csv"));

[gitCommit, gitDirty, trackedDirty, gitStatus] = getGitState(repoRoot);
agent7250Path = getAgent7250CheckpointPath();
manifest = struct( ...
    "stage", "6C", ...
    "schemaVersion", 1, ...
    "result", "PASS", ...
    "createdAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    "gitCommit", gitCommit, ...
    "gitDirty", gitDirty, ...
    "gitTrackedDirty", trackedDirty, ...
    "gitStatus", gitStatus, ...
    "matlabVersion", string(version), ...
    "launcher", "run_no_glove_stage6c_matched_controller", ...
    "inputStage6RunRoot", options.stage6RunRoot, ...
    "inputManifestPath", inputManifestPath, ...
    "inputManifestSha256", fileSha256(inputManifestPath), ...
    "inputGitCommit", string(inputManifest.gitCommit), ...
    "inputPhaseGatePassed", logical(inputManifest.phaseGatePassed), ...
    "inputFinalCheckpoint", string(seedSummary.finalCheckpoint), ...
    "inputFinalCheckpointSha256", ...
        fileSha256(string(seedSummary.finalCheckpoint)), ...
    "inputEvaluationDatasetPath", ...
        string(inputManifest.evaluationDatasetPath), ...
    "inputEvaluationDatasetSha256", ...
        fileSha256(string(inputManifest.evaluationDatasetPath)), ...
    "inputRestDatasetPath", string(inputManifest.restDatasetPath), ...
    "inputRestDatasetSha256", ...
        fileSha256(string(inputManifest.restDatasetPath)), ...
    "inputCalibrationContentSha256", ...
        string(inputManifest.calibrationContentSha256), ...
    "seed", 11, ...
    "evaluationSeed", 7601, ...
    "acceptanceEpisodeCount", acceptance.pairing.episodeCount, ...
    "restEpisodeCount", rest.pairing.episodeCount, ...
    "acceptanceReferenceMaxAbs", acceptance.pairing.referenceMaxAbs, ...
    "restReferenceMaxAbs", rest.pairing.referenceMaxAbs, ...
    "acceptanceInitialPositionMaxAbs", ...
        acceptance.pairing.initialPositionMaxAbs, ...
    "restInitialPositionMaxAbs", rest.pairing.initialPositionMaxAbs, ...
    "commandSources", ["Agent200", "conventionalP"], ...
    "independentVariable", "commandSource", ...
    "controller", profile.conventionalController, ...
    "actionInterfaceVariant", string(profile.actionInterfaceVariant), ...
    "simulationPositionSafety", profile.simulationPositionSafety, ...
    "evaluationOptions", evaluationOptions, ...
    "sourceEpisodeHashesPreserved", true, ...
    "runTraining", false, ...
    "agentLoaded", false, ...
    "reinforcementLearningInvoked", false, ...
    "agent200TraceReadOnly", true, ...
    "agent7250CheckpointPath", agent7250Path, ...
    "agent7250CheckpointSha256", fileSha256(agent7250Path), ...
    "agent7250Loaded", false, ...
    "agent7250Used", false, ...
    "simMotors", true, ...
    "simulatorInvokedForConventionalOnly", true, ...
    "hardwareUsed", false, ...
    "dtwCalculated", false, ...
    "stage7Executed", false, ...
    "stage6GatePassed", false, ...
    "testsTotal", numel(testResults), ...
    "testsPassed", sum([testResults.Passed]), ...
    "testsFailed", sum([testResults.Failed]), ...
    "artifactHashes", artifactHashes, ...
    "outputPath", runDir);
save(fullfile(runDir, "manifest.mat"), "manifest", "artifactHashes");
writeText(fullfile(runDir, "manifest.json"), ...
    jsonencode(manifest, "PrettyPrint", true));

report = struct( ...
    "result", "PASS", ...
    "outputPath", runDir, ...
    "manifest", manifest, ...
    "comparisonSummary", comparisonSummary, ...
    "motorSummary", motorSummary, ...
    "acceptance", acceptance, ...
    "rest", rest, ...
    "testResults", testResults);
fprintf("ETAPA 6C MATCHED CONTROLLER PASS\n");
fprintf("Output: %s\n", runDir);
disp(comparisonSummary);
end

function options = normalizeOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error("run_no_glove_stage6c_matched_controller:InvalidOptions", ...
        "options must be a scalar struct.");
end
defaults = struct( ...
    "stage6RunRoot", "", "resultsRoot", "", ...
    "activeVelocityThreshold", 0.005, ...
    "motionTolerance", 1e-4, ...
    "positionTolerance", 1e-9, ...
    "saturationThreshold", 0.95, ...
    "simulatorSamplingPeriod", 0.14);
unknown = setdiff(string(fieldnames(options)), ...
    string(fieldnames(defaults)));
if ~isempty(unknown)
    error("run_no_glove_stage6c_matched_controller:UnknownOption", ...
        "Unknown option(s): %s.", strjoin(unknown, ", "));
end
fields = fieldnames(defaults);
for fieldIdx = 1:numel(fields)
    name = fields{fieldIdx};
    if ~isfield(options, name) || isempty(options.(name))
        options.(name) = defaults.(name);
    end
end
options.stage6RunRoot = string(options.stage6RunRoot);
options.resultsRoot = string(options.resultsRoot);
if ~isscalar(options.stage6RunRoot) || ...
        strlength(options.stage6RunRoot) == 0
    error("run_no_glove_stage6c_matched_controller:MissingInput", ...
        "stage6RunRoot is required.");
end
numericFields = ["activeVelocityThreshold", "motionTolerance", ...
    "positionTolerance", "saturationThreshold", ...
    "simulatorSamplingPeriod"];
for fieldIdx = 1:numel(numericFields)
    name = numericFields(fieldIdx);
    value = options.(name);
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
            value < 0
        error("run_no_glove_stage6c_matched_controller:InvalidOption", ...
            "%s must be a finite nonnegative scalar.", name);
    end
end
if options.saturationThreshold > 1 || ...
        options.simulatorSamplingPeriod <= 0
    error("run_no_glove_stage6c_matched_controller:InvalidOption", ...
        "Invalid saturation threshold or simulator sampling period.");
end
end

function [manifest, manifestPath] = loadInputManifest(stage6RunRoot)
manifestPath = fullfile(stage6RunRoot, "manifest.json");
if ~isfile(manifestPath)
    error("run_no_glove_stage6c_matched_controller:ManifestNotFound", ...
        "ETAPA 6A manifest not found: %s.", manifestPath);
end
manifest = jsondecode(fileread(manifestPath));
required = ["stage", "phase", "phaseGatePassed", ...
    "positionSafetyAblation", "simulationPositionSafety", ...
    "referenceSource", "observationVariant", ...
    "actionInterfaceVariant", "simMotors", "hardwareUsed", ...
    "seedSummary", "evaluationDatasetPath", "restDatasetPath", ...
    "calibrationContentSha256", "gitCommit"];
if ~all(isfield(manifest, cellstr(required)))
    error("run_no_glove_stage6c_matched_controller:InvalidManifest", ...
        "Input manifest lacks the ETAPA 6A audit contract.");
end
valid = double(manifest.stage) == 6 && ...
    string(manifest.phase) == "smoke" && ...
    ~logical(manifest.phaseGatePassed) && ...
    logical(manifest.positionSafetyAblation) && ...
    logical(manifest.simulationPositionSafety.enabled) && ...
    string(manifest.referenceSource) == "emgIntent" && ...
    string(manifest.observationVariant) == "intentMarkov60" && ...
    string(manifest.actionInterfaceVariant) == "baselineQuantized" && ...
    logical(manifest.simMotors) && ~logical(manifest.hardwareUsed);
if ~valid
    error("run_no_glove_stage6c_matched_controller:IncompatibleManifest", ...
        "ETAPA 6C requires the failed position-limited ETAPA 6A smoke.");
end
seed = manifest.seedSummary;
paths = [string(seed.acceptanceDirectory), ...
    string(seed.restDirectory), string(seed.finalCheckpoint), ...
    string(manifest.evaluationDatasetPath), ...
    string(manifest.restDatasetPath)];
if ~isfolder(paths(1)) || ~isfolder(paths(2)) || ...
        any(~isfile(paths(3:end)))
    error("run_no_glove_stage6c_matched_controller:MissingInputArtifact", ...
        "One or more ETAPA 6A source artifacts are missing.");
end
end

function profile = buildMatchedProfile(trainingProfile)
required = ["intentCalibration", "intentExpectedContext", ...
    "randomSeed", "simulationPositionSafety"];
if ~all(isfield(trainingProfile, cellstr(required)))
    error("run_no_glove_stage6c_matched_controller:InvalidProfile", ...
        "ETAPA 6A effective profile is incomplete.");
end
stage5 = buildNoGloveStage5Override( ...
    trainingProfile.intentCalibration, ...
    trainingProfile.intentExpectedContext, 11);
profile = trainingProfile;
profile.conventionalController = stage5.conventionalController;
profile.run_training = false;
profile.newTraining = false;
profile.agentFile = "";
profile.flagSaveTraining = false;
profile.plotEpisodeOnTest = false;
profile.simMotors = true;
profile.connect_glove = false;
profile.usePrerecorded = true;
profile.referenceSource = "emgIntent";
profile.observationVariant = "intentMarkov60";
profile.actionInterfaceVariant = "baselineQuantized";
profile.quantizeCommandsForSimulation = true;
profile.unifyActions = false;
expectedController = struct( ...
    "schemaVersion", 1, "type", "P", ...
    "kp", 1.5 * ones(4, 1), "kd", zeros(4, 1), ...
    "maxAction", (64 / 255) * ones(4, 1), ...
    "positionTolerance", 0.01 * ones(4, 1), ...
    "velocityTolerance", 0.03 * ones(4, 1));
if ~isequal(profile.conventionalController, expectedController)
    error("run_no_glove_stage6c_matched_controller:ControllerDrift", ...
        "The validated ETAPA 5 P controller has changed.");
end
end

function inventory = inventorySourceEpisodes(acceptanceDir, restDir)
directories = [acceptanceDir, restDir];
splits = ["acceptance", "steady_rest"];
rows = cell(0, 1);
for splitIdx = 1:2
    files = dir(fullfile(directories(splitIdx), "episode*.mat"));
    [~, order] = sort({files.name});
    files = files(order);
    for fileIdx = 1:numel(files)
        filePath = string(fullfile(files(fileIdx).folder, files(fileIdx).name));
        rows{end+1, 1} = struct( ...
            "split", splits(splitIdx), ...
            "fileName", string(files(fileIdx).name), ...
            "path", filePath, ...
            "bytes", files(fileIdx).bytes, ...
            "sha256", fileSha256(filePath)); %#ok<AGROW>
    end
end
if isempty(rows)
    error("run_no_glove_stage6c_matched_controller:NoSourceEpisodes", ...
        "No immutable Agent200 source episodes were found.");
end
inventory = struct2table(vertcat(rows{:}));
end

function output = addSplit(input, splitName)
output = input;
output.split = repmat(splitName, height(output), 1);
output = movevars(output, "split", "Before", 1);
end

function command = buildReproducibleCommand(matlabRoot, options, resultsRoot)
command = sprintf( ...
    "cd('%s'); addpath(genpath(pwd)); " + ...
    "run_no_glove_stage6c_matched_controller(struct(" + ...
    "'stage6RunRoot','%s','resultsRoot','%s'," + ...
    "'activeVelocityThreshold',%.17g,'motionTolerance',%.17g," + ...
    "'positionTolerance',%.17g,'saturationThreshold',%.17g," + ...
    "'simulatorSamplingPeriod',%.17g))", ...
    escape(matlabRoot), escape(options.stage6RunRoot), ...
    escape(resultsRoot), options.activeVelocityThreshold, ...
    options.motionTolerance, options.positionTolerance, ...
    options.saturationThreshold, options.simulatorSamplingPeriod);
end

function writeOfflineReport(pathValue, comparison, ...
        acceptance, rest, profile, runDir)
lines = strings(0, 1);
lines(end+1) = "# ETAPA 6C - comparación emparejada de comando";
lines(end+1) = "";
lines(end+1) = "- Ejecución: PASS; el gate de ETAPA 6 permanece fallido.";
lines(end+1) = "- Variable intervenida: fuente de comando (Agent200 vs P).";
lines(end+1) = "- q_ref, v_ref e inicio por episodio: coincidencia exacta.";
lines(end+1) = "- Control P: kp=1.5, kd=0, límite 64/255.";
lines(end+1) = "- Interfaz: " + string(profile.actionInterfaceVariant) + ".";
lines(end+1) = "- Agent200 no fue cargado: se leyeron sus trazas inmutables.";
lines(end+1) = "- Hardware no; simulador solo para el controlador P; DTW no.";
lines(end+1) = "";
lines(end+1) = "## Resumen";
lines(end+1) = "";
for rowIdx = 1:height(comparison)
    row = comparison(rowIdx, :);
    lines(end+1) = sprintf( ...
        "- %s/%s: MSE %.9f; MAE %.9f; actionL2 %.9f; " + ...
        "deltaActionL2 %.9f; saturación %.9f; seguridad %d; " + ...
        "flags M2 %d; otros %d.", ...
        row.split, row.commandSource, row.trackingMse, ...
        row.trackingMae, row.actionL2, row.deltaActionL2, ...
        row.saturationFraction, row.safetyInterventionCount, ...
        row.motor2FunctionalFlagCount, ...
        row.otherMotorFunctionalFlagCount); %#ok<AGROW>
end
lines(end+1) = "";
lines(end+1) = sprintf( ...
    "- Aceptación emparejada: %d episodios; error q_ref %.17g.", ...
    acceptance.pairing.episodeCount, acceptance.pairing.referenceMaxAbs);
lines(end+1) = sprintf( ...
    "- Reposo emparejado: %d episodios; error q_ref %.17g.", ...
    rest.pairing.episodeCount, rest.pairing.referenceMaxAbs);
lines(end+1) = "";
lines(end+1) = "Las diferencias son evidencia comparativa del origen del " + ...
    "comando bajo este controlador P conservador; no demuestran por sí " + ...
    "solas una causa raíz única.";
lines(end+1) = "";
lines(end+1) = "Detalle por motor en `motor_summary.csv`.";
lines(end+1) = "Ruta: `" + string(runDir) + "`.";
writeText(pathValue, strjoin(lines, newline));
end

function [commit, dirty, trackedDirty, statusText] = getGitState(repoRoot)
[status, output] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
if status == 0
    commit = string(strtrim(output));
else
    commit = "unknown";
end
[status, output] = system(sprintf('git -C "%s" status --porcelain', repoRoot));
statusText = string(strtrim(output));
dirty = status ~= 0 || strlength(statusText) > 0;
[workingStatus, ~] = system(sprintf('git -C "%s" diff --quiet', repoRoot));
[indexStatus, ~] = system(sprintf('git -C "%s" diff --cached --quiet', repoRoot));
trackedDirty = workingStatus ~= 0 || indexStatus ~= 0;
end

function hash = fileSha256(filePath)
escapedPath = strrep(char(string(filePath)), "'", "''");
command = sprintf([ ...
    'powershell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 ' ...
    '-LiteralPath ''%s'').Hash"'], escapedPath);
[status, output] = system(command);
if status ~= 0
    error("run_no_glove_stage6c_matched_controller:HashFailed", ...
        "Could not hash %s.", filePath);
end
hash = upper(string(strtrim(output)));
end

function escaped = escape(value)
escaped = strrep(char(string(value)), "'", "''");
end

function writeText(filePath, value)
fid = fopen(filePath, "w");
if fid < 0
    error("run_no_glove_stage6c_matched_controller:WriteFailed", ...
        "Could not open %s.", filePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end

function cleanupRuntime(originalDir)
clearConfigurablesOverride();
if isfolder(originalDir)
    cd(originalDir);
end
end
