function results = evaluateCheckpointSuite(checkpointPaths, numSimulationsFast, numSimulationsFull, topK)
%evaluateCheckpointSuite audits checkpoints across experiments in two phases.

arguments
    checkpointPaths (1, :) string = defaultCheckpointPaths()
    numSimulationsFast (1, 1) double {mustBeInteger, mustBePositive} = 50
    numSimulationsFull (1, 1) double {mustBeInteger, mustBePositive} = 200
    topK (1, 1) double {mustBeInteger, mustBePositive} = 3
end

close all
clc
rng('default');

srcDir = fileparts(mfilename("fullpath"));
matlabRoot = fileparts(srcDir);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));
try
    resultsRoot = fullfile( ...
        "C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
        "checkpoint_audit", ...
        string(datetime("now", "Format", "yy-MM-dd HH mm ss")));
    mkdir(resultsRoot);

    phaseAFolder = fullfile(resultsRoot, "phaseA_fast");
    phaseBFolder = fullfile(resultsRoot, "phaseB_full");
    mkdir(phaseAFolder);
    mkdir(phaseBFolder);

    phaseASimOpts = rlSimulationOptions( ...
        'MaxSteps', 500, ...
        'NumSimulations', numSimulationsFast, ...
        'StopOnError', 'on', ...
        'UseParallel', false);
    phaseBSimOpts = rlSimulationOptions( ...
        'MaxSteps', 500, ...
        'NumSimulations', numSimulationsFull, ...
        'StopOnError', 'on', ...
        'UseParallel', false);

    phaseATable = runCheckpointBatch( ...
        checkpointPaths, phaseAFolder, phaseASimOpts);
    phaseATable = rankResultsTable(phaseATable);

    shortlistCount = min(topK, height(phaseATable));
    shortlistPaths = string(phaseATable.checkpointPath(1:shortlistCount));
    phaseBTable = runCheckpointBatch( ...
        shortlistPaths, phaseBFolder, phaseBSimOpts);
    phaseBTable = rankResultsTable(phaseBTable);

    results = struct( ...
        "resultsRoot", resultsRoot, ...
        "phaseATable", phaseATable, ...
        "phaseBTable", phaseBTable, ...
        "bestCheckpointPath", string(phaseBTable.checkpointPath(1)), ...
        "bestCheckpointLabel", string(phaseBTable.checkpointLabel(1)));

    writetable(phaseATable, fullfile(resultsRoot, "checkpoint_audit_phaseA.csv"));
    writetable(phaseBTable, fullfile(resultsRoot, "checkpoint_audit_phaseB.csv"));
    save(fullfile(resultsRoot, "checkpoint_audit_results.mat"), ...
        "results", "phaseATable", "phaseBTable", ...
        "checkpointPaths", "numSimulationsFast", "numSimulationsFull", "topK");

    clearConfigurablesOverride();

    disp(phaseATable)
    disp(phaseBTable)
    fprintf("Best checkpoint by protocol: %s\n", results.bestCheckpointPath);
    fprintf("Results saved to %s\n", resultsRoot);
catch ME
    clearConfigurablesOverride();
    rethrow(ME);
end
end

function checkpointPaths = defaultCheckpointPaths()
checkpointPaths = [
    fullfile("C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 21 41 14", "Agent250.mat")
    fullfile("C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 21 41 14", "Agent1000.mat")
    fullfile("C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 21 41 14", "Agent3500.mat")
    fullfile("C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 21 41 14", "Agent4250.mat")
    fullfile("C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 21 41 14", "Agent5000.mat")
    fullfile("C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 23 59 27", "Agent100.mat")
    fullfile("C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 23 59 27", "Agent200.mat")
    fullfile("C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 23 59 27", "Agent500.mat")
    fullfile("C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 23 59 27", "Agent1000.mat")
    fullfile("C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 23 59 27", "Agent2000.mat")
    fullfile("C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 23 59 27", "Agent3000.mat")
    ];
end

function resultsTable = runCheckpointBatch(checkpointPaths, outputRoot, simOpts)
rowTemplate = struct( ...
    "checkpointLabel", "", ...
    "checkpointPath", "", ...
    "numEpisodes", 0, ...
    "episodeRewardMean", NaN, ...
    "episodeRewardStd", NaN, ...
    "trackingMseMean", NaN, ...
    "trackingMseStd", NaN, ...
    "trackingMaeMean", NaN, ...
    "trackingMaeStd", NaN, ...
    "actionL2Mean", NaN, ...
    "actionL2Std", NaN, ...
    "absPwmMean", NaN, ...
    "absPwmStd", NaN, ...
    "saturationFractionMean", NaN, ...
    "saturationFractionStd", NaN, ...
    "deltaActionL2Mean", NaN, ...
    "deltaActionL2Std", NaN, ...
    "stepsPerEpisodeMean", NaN, ...
    "stepsPerEpisodeStd", NaN);

rows = repmat(rowTemplate, numel(checkpointPaths), 1);
for i = 1:numel(checkpointPaths)
    checkpointPath = checkpointPaths(i);
    if ~isfile(checkpointPath)
        error("Checkpoint not found: %s", checkpointPath);
    end

    checkpointLabel = buildCheckpointLabel(checkpointPath);
    runDir = fullfile(outputRoot, checkpointLabel);
    mkdir(runDir);

    checkpointMeta = loadCheckpointMetadata(checkpointPath);
    applyConfigurablesOverride(checkpointMeta.override);
    configs = configurables();
    hardware = definitions();
    [emg, glove] = getDataset(configs.dataset, configs.dataset_folder);

    agent = loadSavedAgent(checkpointPath);
    env = Env(runDir, true, emg, glove);
    env.log(sprintf("Checkpoint audit for %s", checkpointLabel));

    trainingInfo = sim(agent, env, simOpts); %#ok<NASGU>
    summary = summarizeEpisodeDirectory(runDir);

    save(fullfile(runDir, "audit_run.mat"), ...
        "summary", "checkpointPath", "checkpointLabel", ...
        "configs", "hardware", "simOpts", "checkpointMeta");

    rows(i) = mergeSummary(rowTemplate, checkpointLabel, checkpointPath, summary);
    clear env agent trainingInfo
end

resultsTable = struct2table(rows);
end

function checkpointLabel = buildCheckpointLabel(checkpointPath)
[checkpointFolder, checkpointName, ext] = fileparts(checkpointPath);
[~, experimentLabel] = fileparts(checkpointFolder);
checkpointLabel = matlab.lang.makeValidName( ...
    sprintf("%s__%s%s", experimentLabel, checkpointName, ext), ...
    'ReplacementStyle', 'delete');
checkpointLabel = string(checkpointLabel);
end

function resultsTable = rankResultsTable(resultsTable)
[~, order] = sortrows( ...
    [resultsTable.trackingMseMean, ...
     resultsTable.saturationFractionMean, ...
     resultsTable.deltaActionL2Mean, ...
     resultsTable.actionL2Mean], ...
    [1 2 3 4]);
resultsTable = resultsTable(order, :);
end

function agent = loadSavedAgent(checkpointPath)
vars = who('-file', checkpointPath);
if any(strcmp(vars, "agent"))
    aux = load(checkpointPath, "agent");
    agent = aux.agent;
elseif any(strcmp(vars, "saved_agent"))
    aux = load(checkpointPath, "saved_agent");
    agent = aux.saved_agent;
else
    error("Checkpoint %s does not contain an agent variable", checkpointPath);
end
end

function row = mergeSummary(rowTemplate, checkpointLabel, checkpointPath, summary)
row = rowTemplate;
row.checkpointLabel = checkpointLabel;
row.checkpointPath = checkpointPath;
fields = fieldnames(summary);
for k = 1:numel(fields)
    row.(fields{k}) = summary.(fields{k});
end
end

function checkpointMeta = loadCheckpointMetadata(checkpointPath)
checkpointDir = fileparts(checkpointPath);
configPath = fullfile(checkpointDir, "00_configs.mat");

checkpointMeta = struct( ...
    "configPath", string(configPath), ...
    "override", struct());

if ~isfile(configPath)
    return;
end

aux = load(configPath, "configs");
if ~isfield(aux, "configs")
    return;
end

savedConfigs = aux.configs;
overrideFields = [ ...
    "stateLength", ...
    "rewardType", ...
    "rewardActionWeight", ...
    "rewardProgressWeight", ...
    "rewardSmoothnessWeight", ...
    "rewardDeltaActionWeight", ...
    "unifyActions", ...
    "speeds", ...
    "quantizeCommandsForSimulation", ...
    "actionCommandActivationThreshold", ...
    "actionCommandLevels", ...
    "rf_modify_actions", ...
    "plotEpisodeOnTest", ...
    "usePrerecorded", ...
    "simMotors", ...
    "connect_glove", ...
    "dataset", ...
    "dataset_folder", ...
    "numEMGFeatures", ...
    "encodersLimits", ...
    "EMGFeaturesLimits" ...
    ];

override = struct();
for i = 1:numel(overrideFields)
    fieldName = overrideFields(i);
    if isfield(savedConfigs, fieldName)
        override.(fieldName) = savedConfigs.(fieldName);
    end
end
override.run_training = false;
override.newTraining = false;
override.plotEpisodeOnTest = false;

checkpointMeta.override = override;
end

function applyConfigurablesOverride(override)
setappdata(0, 'configurables_override', override);
clear classes
clear configurables
end

function clearConfigurablesOverride()
if isappdata(0, 'configurables_override')
    rmappdata(0, 'configurables_override');
end
clear classes
clear configurables
end
