function results = run_agent7250_residual_alpha_sweep(options)
%run_agent7250_residual_alpha_sweep evaluates a short residual-scale sweep.
%
% Each combination rebuilds a fresh residual TD3 policy on top of
% Agent7250 and reuses the validated residual pilot workflow, including
% training, checkpoint audit, and optional visual test if the pretest gate
% is passed.

arguments
    options = struct()
end

options = normalizeSweepOptions(options);

srcDir = fileparts(mfilename("fullpath"));
matlabRoot = fileparts(srcDir);
repoRoot = fileparts(fileparts(matlabRoot));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));

clearConfigurablesOverride();
cleanup = onCleanup(@() clearConfigurablesOverride()); %#ok<NASGU>

benchmark = getAgent7250Benchmark();
resultsRoot = resolveResultsRoot(options.resultsRoot, repoRoot);
mkdir(resultsRoot);
trainingRunsRoot = fullfile(resultsRoot, "training_runs");
mkdir(trainingRunsRoot);

comboRows = cell(numel(options.residualScales), 1);
comboResults = cell(numel(options.residualScales), 1);

for i = 1:numel(options.residualScales)
    residualScale = double(options.residualScales(i));
    comboLabel = buildComboLabel(residualScale);
    comboRoot = fullfile(trainingRunsRoot, comboLabel);

    pilotOptions = struct( ...
        "checkpointPath", string(options.checkpointPath), ...
        "residualScale", residualScale, ...
        "residualHiddenUnits", options.residualHiddenUnits, ...
        "explorationStd", options.explorationStd, ...
        "explorationStdMin", options.explorationStdMin, ...
        "explorationStdDecayRate", options.explorationStdDecayRate, ...
        "resetExperienceBufferBeforeTraining", logical(options.resetExperienceBufferBeforeTraining), ...
        "trainingEpisodes", options.trainingEpisodes, ...
        "trainingSaveEvery", options.trainingSaveEvery, ...
        "trainingPlots", string(options.trainingPlots), ...
        "enableDetailedActionDiagnostics", options.enableDetailedActionDiagnostics, ...
        "savePerMotorMetrics", options.savePerMotorMetrics, ...
        "auditFastSimulations", options.auditFastSimulations, ...
        "auditFullSimulations", options.auditFullSimulations, ...
        "auditTopK", options.auditTopK, ...
        "auditEveryK", options.auditEveryK, ...
        "auditTailCount", options.auditTailCount, ...
        "visualTestSimulations", options.visualTestSimulations, ...
        "pretestTrackingMseMax", options.pretestTrackingMseMax, ...
        "pretestSaturationFractionMax", options.pretestSaturationFractionMax, ...
        "pretestActionL2Max", options.pretestActionL2Max, ...
        "resultsRoot", comboRoot);

    comboResult = run_agent7250_residual_policy_pilot(pilotOptions);
    comboResults{i} = comboResult;
    comboRows{i} = buildComboRow(comboResult, residualScale, comboLabel);
end

summaryTable = struct2table(vertcat(comboRows{:}));
summaryTable = rankSweepTable(summaryTable);

bestRow = table2struct(summaryTable(1, :));
results = struct( ...
    "resultsRoot", string(resultsRoot), ...
    "benchmark", benchmark, ...
    "options", options, ...
    "summaryTable", summaryTable, ...
    "bestRow", bestRow, ...
    "comboResults", {comboResults});

writetable(summaryTable, fullfile(resultsRoot, "agent7250_residual_alpha_sweep_summary.csv"));
save(fullfile(resultsRoot, "agent7250_residual_alpha_sweep_results.mat"), ...
    "results", "summaryTable", "bestRow", "benchmark", "options", "comboResults");
writeTextFile(fullfile(resultsRoot, "agent7250_residual_alpha_sweep_summary.txt"), ...
    buildSummaryText(results));
end

function options = normalizeSweepOptions(options)
defaults = struct( ...
    "checkpointPath", getAgent7250CheckpointPath(), ...
    "residualScales", [0.10 0.20 0.30], ...
    "residualHiddenUnits", 32, ...
    "explorationStd", 0.02, ...
    "explorationStdMin", 0.002, ...
    "explorationStdDecayRate", 1e-4, ...
    "resetExperienceBufferBeforeTraining", false, ...
    "trainingEpisodes", 2000, ...
    "trainingSaveEvery", 50, ...
    "trainingPlots", "none", ...
    "enableDetailedActionDiagnostics", false, ...
    "savePerMotorMetrics", true, ...
    "auditFastSimulations", 20, ...
    "auditFullSimulations", 50, ...
    "auditTopK", 2, ...
    "auditEveryK", 50, ...
    "auditTailCount", 12, ...
    "visualTestSimulations", 50, ...
    "pretestTrackingMseMax", 0.044022, ...
    "pretestSaturationFractionMax", 0.35271, ...
    "pretestActionL2Max", 0.57794, ...
    "resultsRoot", "");

fields = fieldnames(defaults);
for i = 1:numel(fields)
    if ~isfield(options, fields{i}) || isempty(options.(fields{i}))
        options.(fields{i}) = defaults.(fields{i});
    end
end

options.checkpointPath = string(options.checkpointPath);
options.trainingPlots = string(options.trainingPlots);
options.residualScales = double(options.residualScales(:)).';
end

function comboRow = buildComboRow(comboResult, residualScale, comboLabel)
auditRow = comboResult.bestAuditRow;
visualExecuted = logical(comboResult.visualTestExecuted);

if visualExecuted
    finalSummary = comboResult.visualTestSummary;
    finalDecision = comboResult.visualBenchmarkDecision;
    finalTrackingMse = double(finalSummary.trackingMseMean);
    finalTrackingMae = double(finalSummary.trackingMaeMean);
    finalActionL2 = double(finalSummary.actionL2Mean);
    finalSaturationFraction = double(finalSummary.saturationFractionMean);
    finalDeltaActionL2 = double(finalSummary.deltaActionL2Mean);
    finalStatus = string(finalDecision.status);
    metricsSource = "visual";
else
    finalTrackingMse = double(auditRow.trackingMseMean);
    finalTrackingMae = double(auditRow.trackingMaeMean);
    finalActionL2 = double(auditRow.actionL2Mean);
    finalSaturationFraction = double(auditRow.saturationFractionMean);
    finalDeltaActionL2 = double(auditRow.deltaActionL2Mean);
    finalStatus = string(auditRow.benchmarkStatus);
    metricsSource = "audit";
end

comboRow = struct( ...
    "comboLabel", string(comboLabel), ...
    "residualScale", double(residualScale), ...
    "resultsRoot", string(comboResult.resultsRoot), ...
    "trainingRunDir", string(comboResult.trainingRunDir), ...
    "bestCheckpointPath", string(auditRow.checkpointPath), ...
    "bestCheckpointEpisode", double(auditRow.checkpointEpisode), ...
    "auditBenchmarkStatus", string(auditRow.benchmarkStatus), ...
    "auditTrackingMseMean", double(auditRow.trackingMseMean), ...
    "auditTrackingMaeMean", double(auditRow.trackingMaeMean), ...
    "auditActionL2Mean", double(auditRow.actionL2Mean), ...
    "auditSaturationFractionMean", double(auditRow.saturationFractionMean), ...
    "auditDeltaActionL2Mean", double(auditRow.deltaActionL2Mean), ...
    "auditResidualActionL2Mean", getStructField(auditRow, "residualActionL2Mean", NaN), ...
    "auditResidualFractionNearCapMean", getStructField(auditRow, "residualFractionNearCapMean", NaN), ...
    "auditBaseToFinalActionDeltaMean", getStructField(auditRow, "baseToFinalActionDeltaMean", NaN), ...
    "auditSignOverrideFractionMean", getStructField(auditRow, "signOverrideFractionMean", NaN), ...
    "pretestGatePassed", logical(comboResult.gateDecision.passed), ...
    "visualTestExecuted", visualExecuted, ...
    "finalMetricsSource", string(metricsSource), ...
    "finalBenchmarkStatus", string(finalStatus), ...
    "finalTrackingMseMean", finalTrackingMse, ...
    "finalTrackingMaeMean", finalTrackingMae, ...
    "finalActionL2Mean", finalActionL2, ...
    "finalSaturationFractionMean", finalSaturationFraction, ...
    "finalDeltaActionL2Mean", finalDeltaActionL2, ...
    "trainingAverageRewardFinal", getStructField(comboResult.trainingResult.trainingSummary, "averageRewardFinal", NaN), ...
    "bestAverageRewardEpisode", getStructField(comboResult.trainingResult.trainingSummary, "bestAverageRewardEpisode", NaN));
end

function resultsRoot = resolveResultsRoot(requestedRoot, repoRoot)
requestedRoot = string(requestedRoot);
if strlength(requestedRoot) > 0
    resultsRoot = char(requestedRoot);
else
    resultsRoot = fullfile( ...
        repoRoot, "Agentes", "agent7250_residual_alpha_sweep", ...
        string(datetime("now", "Format", "yy-MM-dd HH mm ss")));
end
end

function comboLabel = buildComboLabel(residualScale)
comboText = regexprep(sprintf('%.2f', residualScale), '\.', 'p');
comboLabel = "alpha_" + comboText;
end

function rankedTable = rankSweepTable(summaryTable)
statusRank = arrayfun(@mapStatusToRank, string(summaryTable.finalBenchmarkStatus));
summaryTable.statusRank = statusRank;

rankedTable = sortrows(summaryTable, ...
    {'statusRank', 'finalTrackingMseMean', 'finalSaturationFractionMean', 'finalActionL2Mean', 'finalDeltaActionL2Mean'}, ...
    {'descend', 'ascend', 'ascend', 'ascend', 'ascend'});
rankedTable.statusRank = [];
end

function rank = mapStatusToRank(status)
switch string(status)
    case "ConditionA"
        rank = 2;
    case "ConditionB"
        rank = 1;
    otherwise
        rank = 0;
end
end

function value = getStructField(s, fieldName, defaultValue)
if isstruct(s) && isfield(s, fieldName)
    value = s.(fieldName);
else
    value = defaultValue;
end
end

function textValue = buildSummaryText(results)
summaryTable = results.summaryTable;
bestRow = results.bestRow;
benchmark = results.benchmark;
options = results.options;

lines = strings(0, 1);
lines(end+1) = "Agent7250 residual alpha sweep";
lines(end+1) = "==============================";
lines(end+1) = "";
lines(end+1) = sprintf("Base checkpoint: %s", string(options.checkpointPath));
lines(end+1) = sprintf("Residual scales: [%s]", join(string(options.residualScales), ", "));
lines(end+1) = sprintf("Training episodes per combo: %d", options.trainingEpisodes);
lines(end+1) = sprintf("Exploration std/min/decay = %.4f / %.4f / %.6g", ...
    options.explorationStd, options.explorationStdMin, options.explorationStdDecayRate);
lines(end+1) = "";
lines(end+1) = sprintf("Benchmark: %s", benchmark.label);
lines(end+1) = sprintf( ...
    "Benchmark trackingMSE = %.6f | saturationFraction = %.6f | actionL2 = %.6f", ...
    benchmark.trackingMse, benchmark.saturationFraction, benchmark.actionL2);
lines(end+1) = "";
lines(end+1) = sprintf("Best alpha: %.2f", bestRow.residualScale);
lines(end+1) = sprintf("Best final status: %s", bestRow.finalBenchmarkStatus);
lines(end+1) = sprintf( ...
    "Best final metrics: trackingMSE = %.6f | saturationFraction = %.6f | actionL2 = %.6f | deltaActionL2 = %.6f", ...
    bestRow.finalTrackingMseMean, bestRow.finalSaturationFractionMean, ...
    bestRow.finalActionL2Mean, bestRow.finalDeltaActionL2Mean);
lines(end+1) = "";
lines(end+1) = strtrim(string(evalc("disp(summaryTable)")));
textValue = strjoin(lines, newline);
end

function writeTextFile(filePath, textValue)
fid = fopen(filePath, "w");
if fid < 0
    error("Could not open %s for writing.", filePath);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, "%s", textValue);
end
