function results = run_agent7250_aligned_action_pilot(options)
%run_agent7250_aligned_action_pilot continues Agent7250 with aligned action warp.

arguments
    options = struct()
end

options = normalizePilotOptions(options);

srcDir = fileparts(mfilename("fullpath"));
matlabRoot = fileparts(srcDir);
repoRoot = fileparts(fileparts(matlabRoot));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));

clearConfigurablesOverride();
cleanup = onCleanup(@() clearConfigurablesOverride()); %#ok<NASGU>

baseConfigs = configurables();
benchmark = getAgent7250Benchmark();
resultsRoot = resolveResultsRoot(options.resultsRoot, repoRoot);
mkdir(resultsRoot);
trainingBaseDir = fullfile(resultsRoot, "training_run");
mkdir(trainingBaseDir);

override = buildPilotOverride(baseConfigs, options, trainingBaseDir);
protocolInfo = buildProtocolInfo(baseConfigs, options);

try
    setConfigurablesOverride(override);
    trainInterface("td3", "alignedAction", "pilot");
    clearConfigurablesOverride();

    runDir = findNewestSubdir(trainingBaseDir);
    trainingResult = analyzeExperimentRun(runDir);

    auditOptions = struct( ...
        "experimentDir", runDir, ...
        "samplingPolicy", struct( ...
            "mode", "tail_every_k_last_n", ...
            "k", options.auditEveryK, ...
            "n", options.auditTailCount), ...
        "resultsRoot", fullfile(resultsRoot, "audit"), ...
        "verbose", false);
    auditResults = runCheckpointAudit( ...
        options.auditFastSimulations, ...
        options.auditFullSimulations, ...
        options.auditTopK, ...
        auditOptions);

    bestRow = table2struct(auditResults.phaseBTable(1, :));
    gateDecision = evaluatePilotGate(bestRow, options);

    visualTestRunDir = "";
    visualTestSummary = struct();
    visualBenchmarkDecision = struct();
    visualTestExecuted = false;

    if gateDecision.passed
        visualTestRoot = fullfile(resultsRoot, "visual_test");
        mkdir(visualTestRoot);
        runCheckpointTest(string(bestRow.checkpointPath), ...
            options.visualTestSimulations, true, struct( ...
            "resultsRoot", visualTestRoot));
        visualTestRunDir = findNewestSubdir(visualTestRoot);
        visualTestResult = analyzeExperimentRun(visualTestRunDir);
        visualTestSummary = visualTestResult.episodeSummary;
        visualBenchmarkDecision = classifyBenchmarkAcceptance(visualTestSummary, benchmark);
        visualTestExecuted = true;
    end

    consolidatedRow = buildPilotResultRow( ...
        bestRow, gateDecision, visualTestSummary, visualBenchmarkDecision, ...
        visualTestExecuted, runDir, visualTestRunDir, trainingResult);
    consolidatedTable = struct2table(consolidatedRow);

    results = struct( ...
        "resultsRoot", string(resultsRoot), ...
        "benchmark", benchmark, ...
        "options", options, ...
        "protocolInfo", protocolInfo, ...
        "trainingRunDir", string(runDir), ...
        "trainingResult", trainingResult, ...
        "auditResults", auditResults, ...
        "bestAuditRow", bestRow, ...
        "gateDecision", gateDecision, ...
        "visualTestExecuted", visualTestExecuted, ...
        "visualTestRunDir", string(visualTestRunDir), ...
        "visualTestSummary", visualTestSummary, ...
        "visualBenchmarkDecision", visualBenchmarkDecision, ...
        "consolidatedTable", consolidatedTable);

    writetable(consolidatedTable, fullfile(resultsRoot, "agent7250_aligned_action_pilot_summary.csv"));
    save(fullfile(resultsRoot, "agent7250_aligned_action_pilot_results.mat"), ...
        "results", "consolidatedTable", "benchmark", "options", "protocolInfo", ...
        "trainingResult", "auditResults", "bestRow", "gateDecision", ...
        "visualTestSummary", "visualBenchmarkDecision");
    writeTextFile(fullfile(resultsRoot, "agent7250_aligned_action_pilot_summary.txt"), ...
        buildSummaryText(results, consolidatedTable));
catch ME
    clearConfigurablesOverride();
    rethrow(ME);
end
end

function options = normalizePilotOptions(options)
defaults = struct( ...
    "checkpointPath", getAgent7250CheckpointPath(), ...
    "actionInterfaceVariant", "alignedContinuousWarp", ...
    "actionWarpDeadzone", 0.05, ...
    "actionWarpOutputLevels", [64 96 128 160 192 224 255] / 255, ...
    "explorationStd", 0.05, ...
    "explorationStdMin", 0.005, ...
    "explorationStdDecayRate", 1e-4, ...
    "resetExperienceBufferBeforeTraining", false, ...
    "trainingEpisodes", 1500, ...
    "trainingSaveEvery", 50, ...
    "trainingPlots", "training-progress", ...
    "enableDetailedActionDiagnostics", false, ...
    "savePerMotorMetrics", true, ...
    "auditFastSimulations", 20, ...
    "auditFullSimulations", 50, ...
    "auditTopK", 2, ...
    "auditEveryK", 50, ...
    "auditTailCount", 12, ...
    "visualTestSimulations", 50, ...
    "pretestTrackingMseMax", 0.044022, ...
    "pretestSaturationFractionMax", 0.35271, ...
    "pretestActionL2Max", 0.57794, ...
    "resultsRoot", "");

fields = fieldnames(defaults);
for i = 1:numel(fields)
    if ~isfield(options, fields{i}) || isempty(options.(fields{i}))
        options.(fields{i}) = defaults.(fields{i});
    end
end

options.checkpointPath = string(options.checkpointPath);
options.actionInterfaceVariant = string(options.actionInterfaceVariant);
options.trainingPlots = string(options.trainingPlots);
options.actionWarpOutputLevels = double(options.actionWarpOutputLevels);
end

function override = buildPilotOverride(baseConfigs, options, trainingBaseDir)
override = buildMarkov52BaselineOverride(baseConfigs, struct( ...
    "run_training", true, ...
    "newTraining", false, ...
    "agentFile", string(options.checkpointPath), ...
    "agent_id", "td3", ...
    "trainingMaxEpisodes", options.trainingEpisodes, ...
    "trainingSaveAgentEvery", options.trainingSaveEvery, ...
    "trainingPlots", string(options.trainingPlots), ...
    "plotEpisodeOnTest", false, ...
    "enableDetailedActionDiagnostics", options.enableDetailedActionDiagnostics, ...
    "savePerMotorMetrics", options.savePerMotorMetrics, ...
    "actionInterfaceVariant", options.actionInterfaceVariant, ...
    "actionWarpDeadzone", options.actionWarpDeadzone, ...
    "actionWarpOutputLevels", options.actionWarpOutputLevels));

override.td3.explorationStd = options.explorationStd;
override.td3.explorationStdMin = options.explorationStdMin;
override.td3.explorationStdDecayRate = options.explorationStdDecayRate;
override.td3.resetExperienceBufferBeforeTraining = ...
    logical(options.resetExperienceBufferBeforeTraining);
override.agents_directory = @(agent_id, variant) fullfile( ...
    trainingBaseDir, string(datetime("now", "Format", "yy-MM-dd HH m s")));
end

function protocolInfo = buildProtocolInfo(baseConfigs, options)
levels = sort(unique(abs(double(baseConfigs.actionCommandLevels(:)))));
levels = levels(levels > 0);
if isempty(levels)
    firstEffectiveActionLevel = NaN;
else
    firstEffectiveActionLevel = levels(1) / max(abs(double(baseConfigs.speeds(:))));
end

protocolInfo = struct( ...
    "checkpointPath", string(options.checkpointPath), ...
    "actionInterfaceVariant", string(options.actionInterfaceVariant), ...
    "activationThreshold", double(baseConfigs.actionCommandActivationThreshold), ...
    "firstEffectiveActionLevel", double(firstEffectiveActionLevel), ...
    "actionWarpDeadzone", double(options.actionWarpDeadzone), ...
    "actionWarpOutputLevels", double(options.actionWarpOutputLevels), ...
    "explorationStd", double(options.explorationStd), ...
    "explorationStdMin", double(options.explorationStdMin), ...
    "explorationStdDecayRate", double(options.explorationStdDecayRate));
end

function gateDecision = evaluatePilotGate(bestRow, options)
trackingMse = double(bestRow.trackingMseMean);
saturationFraction = double(bestRow.saturationFractionMean);
actionL2 = double(bestRow.actionL2Mean);

gateDecision = struct( ...
    "passed", ...
        trackingMse <= options.pretestTrackingMseMax && ...
        saturationFraction <= options.pretestSaturationFractionMax && ...
        actionL2 <= options.pretestActionL2Max, ...
    "trackingMseMax", double(options.pretestTrackingMseMax), ...
    "saturationFractionMax", double(options.pretestSaturationFractionMax), ...
    "actionL2Max", double(options.pretestActionL2Max), ...
    "trackingMseDeltaToGate", trackingMse - options.pretestTrackingMseMax, ...
    "saturationFractionDeltaToGate", saturationFraction - options.pretestSaturationFractionMax, ...
    "actionL2DeltaToGate", actionL2 - options.pretestActionL2Max);
end

function row = buildPilotResultRow(bestRow, gateDecision, visualTestSummary, visualBenchmarkDecision, visualTestExecuted, runDir, visualTestRunDir, trainingResult)
row = struct( ...
    "trainingRunDir", string(runDir), ...
    "bestCheckpointPath", string(bestRow.checkpointPath), ...
    "bestCheckpointEpisode", double(bestRow.checkpointEpisode), ...
    "trackingMseMean", double(bestRow.trackingMseMean), ...
    "trackingMaeMean", double(bestRow.trackingMaeMean), ...
    "actionL2Mean", double(bestRow.actionL2Mean), ...
    "saturationFractionMean", double(bestRow.saturationFractionMean), ...
    "deltaActionL2Mean", double(bestRow.deltaActionL2Mean), ...
    "benchmarkStatus", string(bestRow.benchmarkStatus), ...
    "meetsConditionA", logical(bestRow.meetsConditionA), ...
    "meetsConditionB", logical(bestRow.meetsConditionB), ...
    "pretestGatePassed", logical(gateDecision.passed), ...
    "visualTestExecuted", logical(visualTestExecuted), ...
    "visualTestRunDir", string(visualTestRunDir), ...
    "visualTrackingMseMean", getStructField(visualTestSummary, "trackingMseMean", NaN), ...
    "visualTrackingMaeMean", getStructField(visualTestSummary, "trackingMaeMean", NaN), ...
    "visualActionL2Mean", getStructField(visualTestSummary, "actionL2Mean", NaN), ...
    "visualSaturationFractionMean", getStructField(visualTestSummary, "saturationFractionMean", NaN), ...
    "visualDeltaActionL2Mean", getStructField(visualTestSummary, "deltaActionL2Mean", NaN), ...
    "visualBenchmarkStatus", string(getStructField(visualBenchmarkDecision, "status", "")), ...
    "trainingAverageRewardFinal", getStructField(trainingResult.trainingSummary, "averageRewardFinal", NaN), ...
    "bestAverageRewardEpisode", getStructField(trainingResult.trainingSummary, "bestAverageRewardEpisode", NaN));
end

function resultsRoot = resolveResultsRoot(requestedRoot, repoRoot)
requestedRoot = string(requestedRoot);
if strlength(requestedRoot) > 0
    resultsRoot = char(requestedRoot);
else
    resultsRoot = fullfile( ...
        repoRoot, "Agentes", "agent7250_aligned_action_pilot", ...
        string(datetime("now", "Format", "yy-MM-dd HH mm ss")));
end
end

function newestDir = findNewestSubdir(parentDir)
dirInfo = dir(parentDir);
dirInfo = dirInfo([dirInfo.isdir]);
dirInfo = dirInfo(~ismember({dirInfo.name}, {'.', '..'}));
if isempty(dirInfo)
    error("No training subdirectory found in %s", parentDir);
end
[~, idx] = max([dirInfo.datenum]);
newestDir = string(fullfile(dirInfo(idx).folder, dirInfo(idx).name));
end

function value = getStructField(s, fieldName, defaultValue)
if isstruct(s) && isfield(s, fieldName)
    value = s.(fieldName);
else
    value = defaultValue;
end
end

function textValue = buildSummaryText(results, consolidatedTable)
protocolInfo = results.protocolInfo;
benchmark = results.benchmark;
gateDecision = results.gateDecision;

lines = strings(0, 1);
lines(end+1) = "Agent7250 aligned-action pilot";
lines(end+1) = "============================";
lines(end+1) = "";
lines(end+1) = sprintf("Checkpoint base: %s", protocolInfo.checkpointPath);
lines(end+1) = sprintf("Interface variant: %s", protocolInfo.actionInterfaceVariant);
lines(end+1) = sprintf("Activation threshold = %.6f", protocolInfo.activationThreshold);
lines(end+1) = sprintf("First effective action level = %.6f", protocolInfo.firstEffectiveActionLevel);
lines(end+1) = sprintf("Warp deadzone = %.6f", protocolInfo.actionWarpDeadzone);
lines(end+1) = sprintf("Warp levels = [%s]", join(string(protocolInfo.actionWarpOutputLevels), ", "));
lines(end+1) = sprintf("Exploration std/min/decay = %.4f / %.4f / %.6g", ...
    protocolInfo.explorationStd, protocolInfo.explorationStdMin, protocolInfo.explorationStdDecayRate);
lines(end+1) = "";
lines(end+1) = sprintf("Benchmark: %s", benchmark.label);
lines(end+1) = sprintf( ...
    "Benchmark trackingMSE = %.6f | saturationFraction = %.6f | actionL2 = %.6f", ...
    benchmark.trackingMse, benchmark.saturationFraction, benchmark.actionL2);
lines(end+1) = "";
lines(end+1) = sprintf("Pre-test gate passed: %d", gateDecision.passed);
lines(end+1) = sprintf("Gate thresholds: trackingMSE <= %.6f | saturationFraction <= %.6f | actionL2 <= %.6f", ...
    gateDecision.trackingMseMax, gateDecision.saturationFractionMax, gateDecision.actionL2Max);
lines(end+1) = "";
lines(end+1) = strtrim(string(evalc("disp(consolidatedTable)")));
textValue = strjoin(lines, newline);
end

function writeTextFile(filePath, textValue)
fid = fopen(filePath, "w");
if fid < 0
    error("Could not open %s for writing.", filePath);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, "%s", textValue);
end
