function results = run_markov52_regularization_sweep(options)
%run_markov52_regularization_sweep runs a controlled markov52 lambda sweep.

arguments
    options = struct()
end

options = normalizeSweepOptions(options);

srcDir = fileparts(mfilename("fullpath"));
matlabRoot = fileparts(srcDir);
repoRoot = fileparts(fileparts(matlabRoot));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));

clearSweepOverride();
cleanup = onCleanup(@() clearSweepOverride()); %#ok<NASGU>

baseConfigs = configurables();
benchmark = getAgent7250Benchmark();
resultsRoot = resolveSweepResultsRoot( ...
    options.resultsRoot, repoRoot, "markov52_regularization_sweep");
mkdir(resultsRoot);
mkdir(fullfile(resultsRoot, "training_runs"));

weightGrid = allWeightPairs(options.actionWeights, options.deltaWeights);
rows = cell(height(weightGrid), 1);

for i = 1:height(weightGrid)
    actionWeight = weightGrid.rewardActionWeight(i);
    deltaWeight = weightGrid.rewardDeltaActionWeight(i);
    comboLabel = buildLambdaLabel(actionWeight, deltaWeight);
    comboBaseDir = fullfile(resultsRoot, "training_runs", comboLabel);
    mkdir(comboBaseDir);

    try
        override = buildRegularizationOverride(baseConfigs, options, comboBaseDir, actionWeight, deltaWeight);
        setConfigurablesOverride(override);

        trainInterface("td3", "regSweep", comboLabel);
        clearSweepOverride();

        runDir = findNewestSubdir(comboBaseDir);
        trainingResult = analyzeExperimentRun(runDir);
        auditOptions = struct( ...
            "experimentDir", runDir, ...
            "samplingPolicy", struct( ...
                "mode", "tail_every_k_last_n", ...
                "k", options.auditEveryK, ...
                "n", options.auditTailCount), ...
            "resultsRoot", fullfile(comboBaseDir, "audit"), ...
            "verbose", false);
        auditResults = runCheckpointAudit( ...
            options.auditFastSimulations, ...
            options.auditFullSimulations, ...
            options.auditTopK, ...
            auditOptions);

        bestRow = table2struct(auditResults.phaseBTable(1, :));
        rows{i} = struct( ...
            "comboLabel", string(comboLabel), ...
            "rewardActionWeight", actionWeight, ...
            "rewardDeltaActionWeight", deltaWeight, ...
            "experimentDir", string(runDir), ...
            "bestCheckpointPath", string(bestRow.checkpointPath), ...
            "bestCheckpointEpisode", double(bestRow.checkpointEpisode), ...
            "trackingMseMean", double(bestRow.trackingMseMean), ...
            "trackingMaeMean", double(bestRow.trackingMaeMean), ...
            "actionL2Mean", double(bestRow.actionL2Mean), ...
            "saturationFractionMean", double(bestRow.saturationFractionMean), ...
            "deltaActionL2Mean", double(bestRow.deltaActionL2Mean), ...
            "benchmarkStatus", string(bestRow.benchmarkStatus), ...
            "meetsConditionA", logical(bestRow.meetsConditionA), ...
            "meetsConditionB", logical(bestRow.meetsConditionB), ...
            "trackingMsePctVsBenchmark", double(bestRow.trackingMsePctVsBenchmark), ...
            "saturationFractionPctVsBenchmark", double(bestRow.saturationFractionPctVsBenchmark), ...
            "actionL2PctVsBenchmark", double(bestRow.actionL2PctVsBenchmark), ...
            "deltaActionL2PctVsBenchmark", double(bestRow.deltaActionL2PctVsBenchmark), ...
            "bestAverageRewardEpisode", getStructField(trainingResult.trainingSummary, "bestAverageRewardEpisode", NaN), ...
            "trainingAverageRewardFinal", getStructField(trainingResult.trainingSummary, "averageRewardFinal", NaN), ...
            "status", "ok", ...
            "errorMessage", "");

        save(fullfile(comboBaseDir, "combination_result.mat"), ...
            "trainingResult", "auditResults", "bestRow", "benchmark", ...
            "actionWeight", "deltaWeight", "comboLabel", "options");
    catch ME
        clearSweepOverride();
        rows{i} = struct( ...
            "comboLabel", string(comboLabel), ...
            "rewardActionWeight", actionWeight, ...
            "rewardDeltaActionWeight", deltaWeight, ...
            "experimentDir", string(comboBaseDir), ...
            "bestCheckpointPath", "", ...
            "bestCheckpointEpisode", NaN, ...
            "trackingMseMean", NaN, ...
            "trackingMaeMean", NaN, ...
            "actionL2Mean", NaN, ...
            "saturationFractionMean", NaN, ...
            "deltaActionL2Mean", NaN, ...
            "benchmarkStatus", "Error", ...
            "meetsConditionA", false, ...
            "meetsConditionB", false, ...
            "trackingMsePctVsBenchmark", NaN, ...
            "saturationFractionPctVsBenchmark", NaN, ...
            "actionL2PctVsBenchmark", NaN, ...
            "deltaActionL2PctVsBenchmark", NaN, ...
            "bestAverageRewardEpisode", NaN, ...
            "trainingAverageRewardFinal", NaN, ...
            "status", "error", ...
            "errorMessage", string(ME.message));
    end
end

consolidatedTable = struct2table(vertcat(rows{:}));
if any(strcmp(consolidatedTable.Properties.VariableNames, "status"))
    consolidatedTable.statusRank = double(consolidatedTable.status ~= "ok");
    consolidatedTable = sortrows( ...
        consolidatedTable, ...
        {'statusRank', 'trackingMseMean', 'saturationFractionMean', 'deltaActionL2Mean', 'actionL2Mean'}, ...
        {'ascend', 'ascend', 'ascend', 'ascend', 'ascend'});
end

results = struct( ...
    "resultsRoot", string(resultsRoot), ...
    "benchmark", benchmark, ...
    "options", options, ...
    "consolidatedTable", consolidatedTable);

writetable(consolidatedTable, fullfile(resultsRoot, "regularization_sweep_summary.csv"));
save(fullfile(resultsRoot, "regularization_sweep_results.mat"), "results", "consolidatedTable", "benchmark", "options");
writeTextFile(fullfile(resultsRoot, "regularization_sweep_summary.txt"), buildSweepSummaryText( ...
    "markov52 regularization sweep", consolidatedTable, benchmark));
end

function options = normalizeSweepOptions(options)
defaults = struct( ...
    "actionWeights", [0.01 0.015 0.02], ...
    "deltaWeights", [0.05 0.075 0.10], ...
    "trainingEpisodes", 3000, ...
    "trainingSaveEvery", 100, ...
    "trainingPlots", "none", ...
    "auditFastSimulations", 10, ...
    "auditFullSimulations", 30, ...
    "auditTopK", 1, ...
    "auditEveryK", 100, ...
    "auditTailCount", 8, ...
    "resultsRoot", "", ...
    "enableDetailedActionDiagnostics", false, ...
    "savePerMotorMetrics", true);

fields = fieldnames(defaults);
for i = 1:numel(fields)
    if ~isfield(options, fields{i}) || isempty(options.(fields{i}))
        options.(fields{i}) = defaults.(fields{i});
    end
end
end

function override = buildRegularizationOverride(baseConfigs, options, comboBaseDir, actionWeight, deltaWeight)
override = struct();
override.run_training = true;
override.newTraining = true;
override.usePrerecorded = true;
override.simMotors = true;
override.connect_glove = false;
override.observationVariant = "markov52";
override.rewardType = 'trackingMseActionRateReward';
override.rewardActionWeight = actionWeight;
override.rewardDeltaActionWeight = deltaWeight;
override.trainingMaxEpisodes = options.trainingEpisodes;
override.trainingSaveAgentEvery = options.trainingSaveEvery;
override.trainingPlots = string(options.trainingPlots);
override.plotEpisodeOnTest = false;
override.enableDetailedActionDiagnostics = options.enableDetailedActionDiagnostics;
override.savePerMotorMetrics = options.savePerMotorMetrics;
override.quantizeCommandsForSimulation = true;
td3 = baseConfigs.td3;
td3.useRecurrent = false;
override.td3 = td3;
override.agents_directory = @(agent_id, variant) fullfile( ...
    comboBaseDir, string(datetime("now", "Format", "yy-MM-dd HH m s")));
end

function gridTable = allWeightPairs(actionWeights, deltaWeights)
[actionGrid, deltaGrid] = ndgrid(actionWeights, deltaWeights);
gridTable = table(actionGrid(:), deltaGrid(:), ...
    'VariableNames', {'rewardActionWeight', 'rewardDeltaActionWeight'});
end

function label = buildLambdaLabel(actionWeight, deltaWeight)
label = sprintf("action_%s__delta_%s", encodeNumeric(actionWeight), encodeNumeric(deltaWeight));
end

function encoded = encodeNumeric(value)
encoded = strrep(sprintf("%.4f", value), ".", "p");
encoded = regexprep(encoded, "p?0+$", "");
encoded = regexprep(encoded, "p$", "");
end

function resultsRoot = resolveSweepResultsRoot(requestedRoot, repoRoot, folderName)
requestedRoot = string(requestedRoot);
if strlength(requestedRoot) > 0
    resultsRoot = char(requestedRoot);
else
    resultsRoot = fullfile( ...
        repoRoot, "Agentes", folderName, ...
        string(datetime("now", "Format", "yy-MM-dd HH mm ss")));
end
end

function newestDir = findNewestSubdir(parentDir)
dirInfo = dir(parentDir);
dirInfo = dirInfo([dirInfo.isdir]);
dirInfo = dirInfo(~ismember({dirInfo.name}, {'.', '..'}));
if isempty(dirInfo)
    error("No training subdirectory found in %s", parentDir);
end
[~, idx] = max([dirInfo.datenum]);
newestDir = string(fullfile(dirInfo(idx).folder, dirInfo(idx).name));
end

function clearSweepOverride()
clearConfigurablesOverride();
end

function value = getStructField(s, fieldName, defaultValue)
if isstruct(s) && isfield(s, fieldName)
    value = s.(fieldName);
else
    value = defaultValue;
end
end

function textValue = buildSweepSummaryText(titleText, consolidatedTable, benchmark)
lines = strings(0, 1);
lines(end+1) = string(titleText);
lines(end+1) = join(repmat("=", 1, strlength(titleText)), "");
lines(end+1) = "";
lines(end+1) = sprintf("Benchmark: %s", string(benchmark.label));
lines(end+1) = sprintf("trackingMSE = %.6f | saturationFraction = %.6f | actionL2 = %.6f", ...
    benchmark.trackingMse, benchmark.saturationFraction, benchmark.actionL2);
lines(end+1) = "";
lines(end+1) = strtrim(string(evalc("disp(consolidatedTable)")));
textValue = strjoin(lines, newline);
end

function writeTextFile(filePath, textValue)
fid = fopen(filePath, "w");
if fid < 0
    error("Could not open %s for writing.", filePath);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, "%s", textValue);
end
