function results = run_agent7250_residual_alpha_refinement_sweep(options)
%run_agent7250_residual_alpha_refinement_sweep explores around alpha=0.20.
%
% This wrapper keeps the validated residual TD3 setup intact and only
% performs a narrow search around the best current residual scale.

arguments
    options = struct()
end

options = normalizeRefinementOptions(options);

sweepOptions = struct( ...
    "checkpointPath", string(options.checkpointPath), ...
    "residualScales", options.residualScales, ...
    "residualHiddenUnits", options.residualHiddenUnits, ...
    "explorationStd", options.explorationStd, ...
    "explorationStdMin", options.explorationStdMin, ...
    "explorationStdDecayRate", options.explorationStdDecayRate, ...
    "resetExperienceBufferBeforeTraining", logical(options.resetExperienceBufferBeforeTraining), ...
    "trainingEpisodes", options.trainingEpisodes, ...
    "trainingSaveEvery", options.trainingSaveEvery, ...
    "trainingPlots", string(options.trainingPlots), ...
    "enableDetailedActionDiagnostics", options.enableDetailedActionDiagnostics, ...
    "savePerMotorMetrics", options.savePerMotorMetrics, ...
    "auditFastSimulations", options.auditFastSimulations, ...
    "auditFullSimulations", options.auditFullSimulations, ...
    "auditTopK", options.auditTopK, ...
    "auditEveryK", options.auditEveryK, ...
    "auditTailCount", options.auditTailCount, ...
    "visualTestSimulations", options.visualTestSimulations, ...
    "pretestTrackingMseMax", options.pretestTrackingMseMax, ...
    "pretestSaturationFractionMax", options.pretestSaturationFractionMax, ...
    "pretestActionL2Max", options.pretestActionL2Max, ...
    "resultsRoot", string(options.resultsRoot));

results = run_agent7250_residual_alpha_sweep(sweepOptions);
end

function options = normalizeRefinementOptions(options)
defaults = struct( ...
    "checkpointPath", getAgent7250CheckpointPath(), ...
    "residualScales", [0.18 0.20 0.22 0.25], ...
    "residualHiddenUnits", 32, ...
    "explorationStd", 0.02, ...
    "explorationStdMin", 0.002, ...
    "explorationStdDecayRate", 1e-4, ...
    "resetExperienceBufferBeforeTraining", false, ...
    "trainingEpisodes", 2000, ...
    "trainingSaveEvery", 50, ...
    "trainingPlots", "none", ...
    "enableDetailedActionDiagnostics", false, ...
    "savePerMotorMetrics", true, ...
    "auditFastSimulations", 20, ...
    "auditFullSimulations", 50, ...
    "auditTopK", 2, ...
    "auditEveryK", 50, ...
    "auditTailCount", 12, ...
    "visualTestSimulations", 50, ...
    "pretestTrackingMseMax", 0.044022, ...
    "pretestSaturationFractionMax", 0.35271, ...
    "pretestActionL2Max", 0.57794, ...
    "resultsRoot", "");

fields = fieldnames(defaults);
for i = 1:numel(fields)
    if ~isfield(options, fields{i}) || isempty(options.(fields{i}))
        options.(fields{i}) = defaults.(fields{i});
    end
end

options.checkpointPath = string(options.checkpointPath);
options.trainingPlots = string(options.trainingPlots);
options.residualScales = double(options.residualScales(:)).';
end
