function results = run_residual_lift_pilot(options)
%run_residual_lift_pilot trains a residual TD3 policy over a frozen base.

arguments
    options = struct()
end

options = normalizePilotOptions(options);

srcDir = fileparts(mfilename("fullpath"));
matlabRoot = fileparts(srcDir);
repoRoot = fileparts(fileparts(matlabRoot));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));

clearConfigurablesOverride();
cleanup = onCleanup(@() clearConfigurablesOverride()); %#ok<NASGU>

baseConfigs = configurables();
benchmark = getAgent7250Benchmark();
resultsRoot = resolveResultsRoot(options.resultsRoot, repoRoot);
mkdir(resultsRoot);
trainingBaseDir = fullfile(resultsRoot, "training_run");
mkdir(trainingBaseDir);

override = buildPilotOverride(baseConfigs, options, trainingBaseDir);
protocolInfo = buildProtocolInfo(options);

try
    setConfigurablesOverride(override);
    trainInterface("td3_residual_lift", "", "");
    clearConfigurablesOverride();

    runDir = findNewestSubdir(trainingBaseDir);
    trainingResult = analyzeExperimentRun(runDir);

    auditOptions = struct( ...
        "experimentDir", runDir, ...
        "samplingPolicy", struct( ...
            "mode", "tail_every_k_last_n", ...
            "k", options.auditEveryK, ...
            "n", options.auditTailCount), ...
        "resultsRoot", fullfile(resultsRoot, "audit"), ...
        "verbose", false);
    auditResults = runCheckpointAudit( ...
        options.auditFastSimulations, ...
        options.auditFullSimulations, ...
        options.auditTopK, ...
        auditOptions);

    bestRow = table2struct(auditResults.phaseBTable(1, :));
    gateDecision = evaluatePilotGate(bestRow, options);

    visualTestRunDir = "";
    visualTestSummary = struct();
    visualBenchmarkDecision = struct();
    visualTestExecuted = false;

    if gateDecision.passed
        visualTestRoot = fullfile(resultsRoot, "visual_test");
        mkdir(visualTestRoot);
        runCheckpointTest(string(bestRow.checkpointPath), ...
            options.visualTestSimulations, true, struct( ...
            "resultsRoot", visualTestRoot));
        visualTestRunDir = findNewestSubdir(visualTestRoot);
        visualTestResult = analyzeExperimentRun(visualTestRunDir);
        visualTestSummary = visualTestResult.episodeSummary;
        visualBenchmarkDecision = classifyBenchmarkAcceptance(visualTestSummary, benchmark);
        visualTestExecuted = true;
    end

    consolidatedRow = buildPilotResultRow( ...
        bestRow, gateDecision, visualTestSummary, visualBenchmarkDecision, ...
        visualTestExecuted, runDir, visualTestRunDir, trainingResult);
    consolidatedTable = struct2table(consolidatedRow);

    results = struct( ...
        "resultsRoot", string(resultsRoot), ...
        "benchmark", benchmark, ...
        "options", options, ...
        "protocolInfo", protocolInfo, ...
        "trainingRunDir", string(runDir), ...
        "trainingResult", trainingResult, ...
        "auditResults", auditResults, ...
        "bestAuditRow", bestRow, ...
        "gateDecision", gateDecision, ...
        "visualTestExecuted", visualTestExecuted, ...
        "visualTestRunDir", string(visualTestRunDir), ...
        "visualTestSummary", visualTestSummary, ...
        "visualBenchmarkDecision", visualBenchmarkDecision, ...
        "consolidatedTable", consolidatedTable);

    writetable(consolidatedTable, fullfile(resultsRoot, "residual_lift_pilot_summary.csv"));
    save(fullfile(resultsRoot, "residual_lift_pilot_results.mat"), ...
        "results", "consolidatedTable", "benchmark", "options", "protocolInfo", ...
        "trainingResult", "auditResults", "bestRow", "gateDecision", ...
        "visualTestSummary", "visualBenchmarkDecision");
    writeTextFile(fullfile(resultsRoot, "residual_lift_pilot_summary.txt"), ...
        buildSummaryText(results, consolidatedTable));
catch ME
    clearConfigurablesOverride();
    rethrow(ME);
end
end

function options = normalizePilotOptions(options)
if isfield(options, "checkpointPath") && ~isfield(options, "baseCheckpointPath")
    options.baseCheckpointPath = options.checkpointPath;
end

defaults = struct( ...
    "baseCheckpointPath", getAgent7250CheckpointPath(), ...
    "baseLabel", "", ...
    "residualScale", 0.20, ...
    "residualHiddenUnits", 32, ...
    "explorationStd", 0.02, ...
    "explorationStdMin", 0.002, ...
    "explorationStdDecayRate", 1e-4, ...
    "resetExperienceBufferBeforeTraining", false, ...
    "trainingEpisodes", 2000, ...
    "trainingSaveEvery", 50, ...
    "trainingPlots", "training-progress", ...
    "enableDetailedActionDiagnostics", false, ...
    "savePerMotorMetrics", true, ...
    "auditFastSimulations", 20, ...
    "auditFullSimulations", 50, ...
    "auditTopK", 2, ...
    "auditEveryK", 50, ...
    "auditTailCount", 12, ...
    "visualTestSimulations", 50, ...
    "pretestTrackingMseMax", 0.044022, ...
    "pretestSaturationFractionMax", 0.35271, ...
    "pretestActionL2Max", 0.57794, ...
    "resultsRoot", "");

fields = fieldnames(defaults);
for i = 1:numel(fields)
    if ~isfield(options, fields{i}) || isempty(options.(fields{i}))
        options.(fields{i}) = defaults.(fields{i});
    end
end

options.baseCheckpointPath = string(options.baseCheckpointPath);
options.baseLabel = inferBaseLabel(options.baseLabel, options.baseCheckpointPath);
options.trainingPlots = string(options.trainingPlots);
end

function override = buildPilotOverride(baseConfigs, options, trainingBaseDir)
override = buildMarkov52BaselineOverride(baseConfigs, struct( ...
    "run_training", true, ...
    "newTraining", true, ...
    "agentFile", "", ...
    "agent_id", "td3_residual_lift", ...
    "trainingMaxEpisodes", options.trainingEpisodes, ...
    "trainingSaveAgentEvery", options.trainingSaveEvery, ...
    "trainingPlots", string(options.trainingPlots), ...
    "plotEpisodeOnTest", false, ...
    "enableDetailedActionDiagnostics", options.enableDetailedActionDiagnostics, ...
    "savePerMotorMetrics", options.savePerMotorMetrics));

override.td3.useRecurrent = false;
override.td3.explorationStd = options.explorationStd;
override.td3.explorationStdMin = options.explorationStdMin;
override.td3.explorationStdDecayRate = options.explorationStdDecayRate;
override.td3.resetExperienceBufferBeforeTraining = ...
    logical(options.resetExperienceBufferBeforeTraining);

override.td3Residual = baseConfigs.td3Residual;
override.td3Residual.enabled = true;
override.td3Residual.logDiagnostics = true;
override.td3Residual.baseCheckpointPath = string(options.baseCheckpointPath);
override.td3Residual.baseLabel = string(options.baseLabel);
override.td3Residual.residualScale = options.residualScale;
override.td3Residual.hiddenUnits = options.residualHiddenUnits;

override.agents_directory = @(agent_id, variant) fullfile( ...
    trainingBaseDir, string(datetime("now", "Format", "yy-MM-dd HH m s")));
end

function protocolInfo = buildProtocolInfo(options)
protocolInfo = struct( ...
    "baseCheckpointPath", string(options.baseCheckpointPath), ...
    "baseLabel", string(options.baseLabel), ...
    "residualScale", double(options.residualScale), ...
    "residualHiddenUnits", double(options.residualHiddenUnits), ...
    "explorationStd", double(options.explorationStd), ...
    "explorationStdMin", double(options.explorationStdMin), ...
    "explorationStdDecayRate", double(options.explorationStdDecayRate), ...
    "resetExperienceBufferBeforeTraining", logical(options.resetExperienceBufferBeforeTraining));
end

function gateDecision = evaluatePilotGate(bestRow, options)
trackingMse = double(bestRow.trackingMseMean);
saturationFraction = double(bestRow.saturationFractionMean);
actionL2 = double(bestRow.actionL2Mean);

gateDecision = struct( ...
    "passed", ...
        trackingMse <= options.pretestTrackingMseMax && ...
        saturationFraction <= options.pretestSaturationFractionMax && ...
        actionL2 <= options.pretestActionL2Max, ...
    "trackingMseMax", double(options.pretestTrackingMseMax), ...
    "saturationFractionMax", double(options.pretestSaturationFractionMax), ...
    "actionL2Max", double(options.pretestActionL2Max), ...
    "trackingMseDeltaToGate", trackingMse - options.pretestTrackingMseMax, ...
    "saturationFractionDeltaToGate", saturationFraction - options.pretestSaturationFractionMax, ...
    "actionL2DeltaToGate", actionL2 - options.pretestActionL2Max);
end

function row = buildPilotResultRow(bestRow, gateDecision, visualTestSummary, visualBenchmarkDecision, visualTestExecuted, runDir, visualTestRunDir, trainingResult)
row = struct( ...
    "trainingRunDir", string(runDir), ...
    "bestCheckpointPath", string(bestRow.checkpointPath), ...
    "bestCheckpointEpisode", double(bestRow.checkpointEpisode), ...
    "trackingMseMean", double(bestRow.trackingMseMean), ...
    "trackingMaeMean", double(bestRow.trackingMaeMean), ...
    "actionL2Mean", double(bestRow.actionL2Mean), ...
    "saturationFractionMean", double(bestRow.saturationFractionMean), ...
    "deltaActionL2Mean", double(bestRow.deltaActionL2Mean), ...
    "residualActionL2Mean", getTableField(bestRow, "residualActionL2Mean", NaN), ...
    "residualFractionNearCapMean", getTableField(bestRow, "residualFractionNearCapMean", NaN), ...
    "baseToFinalActionDeltaMean", getTableField(bestRow, "baseToFinalActionDeltaMean", NaN), ...
    "signOverrideFractionMean", getTableField(bestRow, "signOverrideFractionMean", NaN), ...
    "benchmarkStatus", string(bestRow.benchmarkStatus), ...
    "meetsConditionA", logical(bestRow.meetsConditionA), ...
    "meetsConditionB", logical(bestRow.meetsConditionB), ...
    "pretestGatePassed", logical(gateDecision.passed), ...
    "visualTestExecuted", logical(visualTestExecuted), ...
    "visualTestRunDir", string(visualTestRunDir), ...
    "visualTrackingMseMean", getStructField(visualTestSummary, "trackingMseMean", NaN), ...
    "visualTrackingMaeMean", getStructField(visualTestSummary, "trackingMaeMean", NaN), ...
    "visualActionL2Mean", getStructField(visualTestSummary, "actionL2Mean", NaN), ...
    "visualSaturationFractionMean", getStructField(visualTestSummary, "saturationFractionMean", NaN), ...
    "visualDeltaActionL2Mean", getStructField(visualTestSummary, "deltaActionL2Mean", NaN), ...
    "visualBenchmarkStatus", string(getStructField(visualBenchmarkDecision, "status", "")), ...
    "trainingAverageRewardFinal", getStructField(trainingResult.trainingSummary, "averageRewardFinal", NaN), ...
    "bestAverageRewardEpisode", getStructField(trainingResult.trainingSummary, "bestAverageRewardEpisode", NaN));
end

function resultsRoot = resolveResultsRoot(requestedRoot, repoRoot)
requestedRoot = string(requestedRoot);
if strlength(requestedRoot) > 0
    resultsRoot = char(requestedRoot);
else
    resultsRoot = fullfile( ...
        repoRoot, "Agentes", "residual_lift_pilot", ...
        string(datetime("now", "Format", "yy-MM-dd HH mm ss")));
end
end

function newestDir = findNewestSubdir(parentDir)
dirInfo = dir(parentDir);
dirInfo = dirInfo([dirInfo.isdir]);
dirInfo = dirInfo(~ismember({dirInfo.name}, {'.', '..'}));
if isempty(dirInfo)
    error("No training subdirectory found in %s", parentDir);
end
[~, idx] = max([dirInfo.datenum]);
newestDir = string(fullfile(dirInfo(idx).folder, dirInfo(idx).name));
end

function value = getStructField(s, fieldName, defaultValue)
if isstruct(s) && isfield(s, fieldName)
    value = s.(fieldName);
else
    value = defaultValue;
end
end

function value = getTableField(s, fieldName, defaultValue)
if isstruct(s) && isfield(s, fieldName)
    value = s.(fieldName);
else
    value = defaultValue;
end
end

function baseLabel = inferBaseLabel(requestedLabel, checkpointPath)
requestedLabel = string(requestedLabel);
if strlength(strtrim(requestedLabel)) > 0
    baseLabel = requestedLabel;
    return;
end
[~, stem, ~] = fileparts(char(checkpointPath));
if strlength(string(stem)) == 0
    baseLabel = "base_checkpoint";
else
    baseLabel = string(stem);
end
end

function textValue = buildSummaryText(results, consolidatedTable)
protocolInfo = results.protocolInfo;
benchmark = results.benchmark;
gateDecision = results.gateDecision;

lines = strings(0, 1);
lines(end+1) = "Residual Lift pilot";
lines(end+1) = "===================";
lines(end+1) = "";
lines(end+1) = sprintf("Frozen base label: %s", protocolInfo.baseLabel);
lines(end+1) = sprintf("Frozen base checkpoint: %s", protocolInfo.baseCheckpointPath);
lines(end+1) = sprintf("Residual scale = %.4f | hidden units = %d", ...
    protocolInfo.residualScale, protocolInfo.residualHiddenUnits);
lines(end+1) = sprintf("Exploration std/min/decay = %.4f / %.4f / %.6g", ...
    protocolInfo.explorationStd, protocolInfo.explorationStdMin, protocolInfo.explorationStdDecayRate);
lines(end+1) = sprintf("Reset experience buffer before training = %d", ...
    protocolInfo.resetExperienceBufferBeforeTraining);
lines(end+1) = "";
lines(end+1) = sprintf("Reference benchmark: %s", benchmark.label);
lines(end+1) = sprintf( ...
    "Benchmark trackingMSE = %.6f | saturationFraction = %.6f | actionL2 = %.6f", ...
    benchmark.trackingMse, benchmark.saturationFraction, benchmark.actionL2);
lines(end+1) = "";
lines(end+1) = sprintf("Pre-test gate passed: %d", gateDecision.passed);
lines(end+1) = sprintf("Gate thresholds: trackingMSE <= %.6f | saturationFraction <= %.6f | actionL2 <= %.6f", ...
    gateDecision.trackingMseMax, gateDecision.saturationFractionMax, gateDecision.actionL2Max);
lines(end+1) = "";
lines(end+1) = strtrim(string(evalc("disp(consolidatedTable)")));
textValue = strjoin(lines, newline);
end

function writeTextFile(filePath, textValue)
fid = fopen(filePath, "w");
if fid < 0
    error("Could not open %s for writing.", filePath);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, "%s", textValue);
end
