function trainingInfo = runCheckpointTest(checkpointPath, numSimulations, plotEpisodes)
%runCheckpointTest evaluates a saved checkpoint in simulation mode.

arguments
    checkpointPath (1, 1) string = defaultCheckpointPath()
    numSimulations (1, 1) double {mustBeInteger, mustBePositive} = 50
    plotEpisodes (1, 1) logical = true
end

srcDir = fileparts(mfilename("fullpath"));
matlabRoot = fileparts(srcDir);
cd(matlabRoot);

addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));

override = struct( ...
    "run_training", false, ...
    "newTraining", false, ...
    "agentFile", checkpointPath, ...
    "agent_id", "td3", ...
    "plotEpisodeOnTest", plotEpisodes, ...
    "verbose", false, ...
    "stateLength", 52, ...
    "rewardType", "trackingMseActionRateReward", ...
    "usePrerecorded", true, ...
    "simMotors", true, ...
    "connect_glove", false, ...
    "simOpts", rlSimulationOptions( ...
        'MaxSteps', 500, ...
        'NumSimulations', numSimulations, ...
        'StopOnError', 'on', ...
        'UseParallel', false));

setappdata(0, 'configurables_override', override);
cleanup = onCleanup(@() clearConfigurablesOverride()); %#ok<NASGU>

trainingInfo = trainInterface("td3", "", "");
end

function checkpointPath = defaultCheckpointPath()
checkpointPath = fullfile( ...
    "C:\Users\pc\Desktop\PROTESIS_PRACTICAS\Agentes", ...
    "trainedAgentsProtesisTest", "td3", "_", ...
    "26-03-19 02 26 41", "Agent2000.mat");
end

function clearConfigurablesOverride()
if isappdata(0, 'configurables_override')
    rmappdata(0, 'configurables_override');
end
end
