function trainingInfo = runCheckpointTest(checkpointPath, numSimulations, plotEpisodes)
%runCheckpointTest evaluates a saved checkpoint in simulation mode.

arguments
    checkpointPath (1, 1) string = defaultCheckpointPath()
    numSimulations (1, 1) double {mustBeInteger, mustBePositive} = 50
    plotEpisodes (1, 1) logical = true
end

srcDir = fileparts(mfilename("fullpath"));
matlabRoot = fileparts(srcDir);
cd(matlabRoot);

addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));

override = loadCheckpointOverride(checkpointPath);
override = mergeStructs(override, struct( ...
    "run_training", false, ...
    "newTraining", false, ...
    "agentFile", checkpointPath, ...
    "agent_id", "td3", ...
    "plotEpisodeOnTest", plotEpisodes, ...
    "verbose", false, ...
    "usePrerecorded", true, ...
    "simMotors", true, ...
    "connect_glove", false, ...
    "simOpts", rlSimulationOptions( ...
        'MaxSteps', 500, ...
        'NumSimulations', numSimulations, ...
        'StopOnError', 'on', ...
        'UseParallel', false)));

setappdata(0, 'configurables_override', override);
cleanup = onCleanup(@() clearConfigurablesOverride()); %#ok<NASGU>

trainingInfo = trainInterface("td3", "", "");
end

function checkpointPath = defaultCheckpointPath()
srcDir = fileparts(mfilename("fullpath"));
matlabRoot = fileparts(srcDir);
repoRoot = fileparts(fileparts(matlabRoot));
checkpointPath = fullfile( ...
    repoRoot, "Agentes", ...
    "trainedAgentsProtesisTest", "td3", "_", ...
    "26-03-19 11 24 39", "Agent2000.mat");
end

function override = loadCheckpointOverride(checkpointPath)
override = struct();
configPath = fullfile(fileparts(checkpointPath), "00_configs.mat");
if ~isfile(configPath)
    return;
end

aux = load(configPath, "configs");
if ~isfield(aux, "configs")
    return;
end

savedConfigs = aux.configs;
overrideFields = [ ...
    "stateLength", ...
    "rewardType", ...
    "rewardActionWeight", ...
    "rewardProgressWeight", ...
    "rewardSmoothnessWeight", ...
    "rewardDeltaActionWeight", ...
    "unifyActions", ...
    "speeds", ...
    "quantizeCommandsForSimulation", ...
    "actionCommandActivationThreshold", ...
    "actionCommandLevels", ...
    "rf_modify_actions", ...
    "usePrerecorded", ...
    "simMotors", ...
    "connect_glove", ...
    "dataset", ...
    "dataset_folder", ...
    "numEMGFeatures", ...
    "observationVariant", ...
    "emgHistoryLength", ...
    "encodersLimits", ...
    "EMGFeaturesLimits" ...
    ];

for i = 1:numel(overrideFields)
    fieldName = overrideFields(i);
    if isfield(savedConfigs, fieldName)
        override.(fieldName) = savedConfigs.(fieldName);
    end
end
end

function merged = mergeStructs(baseStruct, patchStruct)
merged = baseStruct;
fields = fieldnames(patchStruct);
for i = 1:numel(fields)
    merged.(fields{i}) = patchStruct.(fields{i});
end
end

function clearConfigurablesOverride()
if isappdata(0, 'configurables_override')
    rmappdata(0, 'configurables_override');
end
end
