function results = runCheckpointAudit(numSimulationsFast, numSimulationsFull, topK)
%runCheckpointAudit runs the checkpoint audit suite with default paths.

arguments
    numSimulationsFast (1, 1) double {mustBeInteger, mustBePositive} = 50
    numSimulationsFull (1, 1) double {mustBeInteger, mustBePositive} = 200
    topK (1, 1) double {mustBeInteger, mustBePositive} = 3
end

srcDir = fileparts(mfilename("fullpath"));
matlabRoot = fileparts(srcDir);
repoRoot = fileparts(fileparts(matlabRoot));
cd(matlabRoot);
addpath(genpath(fullfile(matlabRoot, "src")));
addpath(genpath(fullfile(matlabRoot, "config")));
addpath(genpath(fullfile(matlabRoot, "lib")));
addpath(genpath(fullfile(matlabRoot, "agents")));

results = evaluateCheckpointSuite( ...
    evaluateCheckpointSuiteDefaults(repoRoot), ...
    numSimulationsFast, numSimulationsFull, topK);
end

function checkpointPaths = evaluateCheckpointSuiteDefaults(repoRoot)
checkpointPaths = [
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 21 41 14", "Agent250.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 21 41 14", "Agent1000.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 21 41 14", "Agent3500.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 21 41 14", "Agent4250.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 21 41 14", "Agent5000.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 23 59 27", "Agent100.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 23 59 27", "Agent200.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 23 59 27", "Agent500.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 23 59 27", "Agent1000.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 23 59 27", "Agent2000.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-18 23 59 27", "Agent3000.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-19 02 26 41", "Agent1700.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-19 02 26 41", "Agent1800.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-19 02 26 41", "Agent1850.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-19 02 26 41", "Agent1900.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-19 02 26 41", "Agent1950.mat")
    fullfile(repoRoot, "Agentes", ...
        "trainedAgentsProtesisTest", "td3", "_", ...
        "26-03-19 02 26 41", "Agent2000.mat")
    ];
end
