function summary = summarizeEpisodeDirectory(episodeDir)
%summarizeEpisodeDirectory aggregates episode-level metrics saved to disk.

arguments
    episodeDir (1, 1) string
end

episodeFiles = dir(fullfile(episodeDir, "episode*.mat"));
if isempty(episodeFiles)
    error("No episode files found in %s", episodeDir);
end

numEpisodes = numel(episodeFiles);
episodeReward = nan(numEpisodes, 1);
trackingMseMean = nan(numEpisodes, 1);
trackingMaeMean = nan(numEpisodes, 1);
actionL2Mean = nan(numEpisodes, 1);
absPwmMean = nan(numEpisodes, 1);
saturationFractionMean = nan(numEpisodes, 1);
deltaActionL2Mean = nan(numEpisodes, 1);
stepsPerEpisode = nan(numEpisodes, 1);

for i = 1:numEpisodes
    data = load(fullfile(episodeFiles(i).folder, episodeFiles(i).name), ...
        "rewardLog", "trackingMseLog", "trackingMaeLog", "actionL2Log", ...
        "actionPwmLog", "actionSatLog");

    validSteps = ~isnan(data.rewardLog);
    stepsPerEpisode(i) = sum(validSteps);
    episodeReward(i) = sum(data.rewardLog(validSteps), "omitnan");
    trackingMseMean(i) = mean(data.trackingMseLog(~isnan(data.trackingMseLog)), ...
        "omitnan");
    trackingMaeMean(i) = mean(data.trackingMaeLog(~isnan(data.trackingMaeLog)), ...
        "omitnan");
    actionL2Mean(i) = mean(data.actionL2Log(~isnan(data.actionL2Log)), ...
        "omitnan");

    validPwm = ~isnan(data.actionPwmLog);
    absPwmMean(i) = mean(abs(data.actionPwmLog(validPwm)), "omitnan");

    validSat = ~isnan(data.actionSatLog);
    saturationFractionMean(i) = mean(abs(data.actionSatLog(validSat)) >= 0.95, ...
        "omitnan");

    actionSat = data.actionSatLog;
    validRows = all(~isnan(actionSat), 2);
    actionSat = actionSat(validRows, :);
    if size(actionSat, 1) >= 2
        delta = diff(actionSat, 1, 1);
        deltaActionL2Mean(i) = mean(sum(delta.^2, 2), "omitnan");
    else
        deltaActionL2Mean(i) = 0;
    end
end

summary = struct(...
    "numEpisodes", numEpisodes, ...
    "episodeRewardMean", mean(episodeReward, "omitnan"), ...
    "episodeRewardStd", std(episodeReward, 0, "omitnan"), ...
    "trackingMseMean", mean(trackingMseMean, "omitnan"), ...
    "trackingMseStd", std(trackingMseMean, 0, "omitnan"), ...
    "trackingMaeMean", mean(trackingMaeMean, "omitnan"), ...
    "trackingMaeStd", std(trackingMaeMean, 0, "omitnan"), ...
    "actionL2Mean", mean(actionL2Mean, "omitnan"), ...
    "actionL2Std", std(actionL2Mean, 0, "omitnan"), ...
    "absPwmMean", mean(absPwmMean, "omitnan"), ...
    "absPwmStd", std(absPwmMean, 0, "omitnan"), ...
    "saturationFractionMean", mean(saturationFractionMean, "omitnan"), ...
    "saturationFractionStd", std(saturationFractionMean, 0, "omitnan"), ...
    "deltaActionL2Mean", mean(deltaActionL2Mean, "omitnan"), ...
    "deltaActionL2Std", std(deltaActionL2Mean, 0, "omitnan"), ...
    "stepsPerEpisodeMean", mean(stepsPerEpisode, "omitnan"), ...
    "stepsPerEpisodeStd", std(stepsPerEpisode, 0, "omitnan"));
end
