function summary = summarizeResidualStopbandCampaign(perSeedTable, benchmark, options)
%summarizeResidualStopbandCampaign aggregates stop-band discovery/confirmation runs.

arguments
    perSeedTable table
    benchmark struct = getAgent7250Benchmark()
    options = struct()
end

defaults = struct( ...
    "roundToEpisode", 250, ...
    "fallbackEpisode", 2000, ...
    "clampRange", [1750 3000], ...
    "mode", "discovery");

fields = fieldnames(defaults);
for i = 1:numel(fields)
    if ~isfield(options, fields{i}) || isempty(options.(fields{i}))
        options.(fields{i}) = defaults.(fields{i});
    end
end

statuses = string(perSeedTable.finalStatus);
acceptedMask = statuses == "ConditionA" | statuses == "ConditionB";
acceptedEpisodes = double(perSeedTable.selectedCheckpointEpisode(acceptedMask));

trackingStats = computeSummaryStats(perSeedTable.finalTrackingMse);
trackingMaeStats = computeSummaryStats(perSeedTable.finalTrackingMae);
actionStats = computeSummaryStats(perSeedTable.finalActionL2);
saturationStats = computeSummaryStats(perSeedTable.finalSaturationFraction);
deltaStats = computeSummaryStats(perSeedTable.finalDeltaActionL2);

[bestIdx, worstIdx] = resolveBestWorstIndices(perSeedTable);
[stopBandEpisode, stopBandWindow, stopBandDecision] = deriveStopBandEpisode(acceptedEpisodes, options);

aggregateDecision = classifyBenchmarkAcceptance(struct( ...
    "trackingMseMean", trackingStats.mean, ...
    "saturationFractionMean", saturationStats.mean, ...
    "actionL2Mean", actionStats.mean, ...
    "deltaActionL2Mean", deltaStats.mean), benchmark);

promotionSupported = ...
    sum(acceptedMask) >= 3 && ...
    (aggregateDecision.meetsConditionA || aggregateDecision.meetsConditionB) && ...
    actionStats.mean < benchmark.actionL2 && ...
    saturationStats.mean < benchmark.saturationFraction;

summary = struct( ...
    "mode", string(options.mode), ...
    "numSeeds", height(perSeedTable), ...
    "acceptedCount", sum(acceptedMask), ...
    "conditionACount", sum(statuses == "ConditionA"), ...
    "conditionBCount", sum(statuses == "ConditionB"), ...
    "rejectedCount", sum(statuses == "Rejected"), ...
    "acceptedWinnerEpisodes", acceptedEpisodes(:)', ...
    "trackingMseMean", trackingStats.mean, ...
    "trackingMseStd", trackingStats.std, ...
    "trackingMaeMean", trackingMaeStats.mean, ...
    "trackingMaeStd", trackingMaeStats.std, ...
    "actionL2Mean", actionStats.mean, ...
    "actionL2Std", actionStats.std, ...
    "saturationFractionMean", saturationStats.mean, ...
    "saturationFractionStd", saturationStats.std, ...
    "deltaActionL2Mean", deltaStats.mean, ...
    "deltaActionL2Std", deltaStats.std, ...
    "aggregateBenchmarkDecision", aggregateDecision, ...
    "stopBandEpisode", stopBandEpisode, ...
    "stopBandWindow", stopBandWindow, ...
    "stopBandDecision", stopBandDecision, ...
    "bestSeed", double(perSeedTable.seed(bestIdx)), ...
    "bestSeedCheckpointPath", string(perSeedTable.selectedCheckpointPath(bestIdx)), ...
    "bestSeedEpisode", double(perSeedTable.selectedCheckpointEpisode(bestIdx)), ...
    "worstSeed", double(perSeedTable.seed(worstIdx)), ...
    "worstSeedCheckpointPath", string(perSeedTable.selectedCheckpointPath(worstIdx)), ...
    "worstSeedEpisode", double(perSeedTable.selectedCheckpointEpisode(worstIdx)), ...
    "promotionSupported", logical(promotionSupported), ...
    "conclusion", buildConclusion(string(options.mode), promotionSupported));
end

function stats = computeSummaryStats(values)
values = double(values(:));
stats = struct( ...
    "mean", mean(values, "omitnan"), ...
    "std", std(values, 0, "omitnan"));
end

function [bestIdx, worstIdx] = resolveBestWorstIndices(perSeedTable)
rank = arrayfun(@mapStatusToRank, string(perSeedTable.finalStatus));
tracking = double(perSeedTable.finalTrackingMse);
saturation = double(perSeedTable.finalSaturationFraction);
deltaAction = double(perSeedTable.finalDeltaActionL2);
action = double(perSeedTable.finalActionL2);

scoreTable = table( ...
    (1:height(perSeedTable))', rank(:), tracking(:), saturation(:), ...
    deltaAction(:), action(:), ...
    'VariableNames', {'idx','rank','tracking','saturation','deltaAction','action'});

bestTable = sortrows(scoreTable, ...
    {'rank','tracking','saturation','deltaAction','action'}, ...
    {'descend','ascend','ascend','ascend','ascend'});
bestIdx = double(bestTable.idx(1));

worstTable = sortrows(scoreTable, ...
    {'rank','tracking','saturation','deltaAction','action'}, ...
    {'ascend','descend','descend','descend','descend'});
worstIdx = double(worstTable.idx(1));
end

function rank = mapStatusToRank(status)
switch string(status)
    case "ConditionA"
        rank = 2;
    case "ConditionB"
        rank = 1;
    otherwise
        rank = 0;
end
end

function [episodeValue, windowValue, decision] = deriveStopBandEpisode(acceptedEpisodes, options)
roundTo = double(options.roundToEpisode);
fallbackEpisode = double(options.fallbackEpisode);
clampRange = double(options.clampRange(:))';

decision = struct( ...
    "rule", "", ...
    "acceptedCount", numel(acceptedEpisodes));

if isempty(acceptedEpisodes)
    episodeValue = fallbackEpisode;
    decision.rule = "fallback_no_accepted_seed";
elseif numel(acceptedEpisodes) >= 3
    episodeValue = roundToNearest(median(acceptedEpisodes), roundTo);
    decision.rule = "median_over_accepted_seeds";
else
    episodeValue = roundToNearest(median(acceptedEpisodes), roundTo);
    episodeValue = min(max(episodeValue, clampRange(1)), clampRange(2));
    decision.rule = "clamped_median_over_sparse_accepted_seeds";
end

windowValue = [episodeValue - roundTo, episodeValue + roundTo];
end

function roundedValue = roundToNearest(value, step)
roundedValue = step * round(double(value) / step);
end

function conclusion = buildConclusion(mode, promotionSupported)
if string(mode) == "confirmation"
    if promotionSupported
        conclusion = "La fase confirma una stop-band residual suficientemente estable para seguir como linea activa.";
    else
        conclusion = "La fase no confirma una stop-band residual estable; se mantiene el punto actual del proyecto.";
    end
else
    if promotionSupported
        conclusion = "Discovery encontro una banda prometedora y consistente para pasar a confirmacion.";
    else
        conclusion = "Discovery no estabilizo la linea, pero deja una stop-band operativa para confirmacion o cierre.";
    end
end
end
